### ISSUE TITLE
Plugin: E-Mail / Templates

### ISSUE THREAD

**Issue by dergel** [yakamara/redaxo_yform#1]
mit REX_YDATA[id="name" prefix="Name:"] Felder versehen, um die diversen Varianten abdecken zu können. Siehe REX_VARS

**Comment by tbaddade** [comment]
Finde REX_YFORM oder REX_YFORM_DATA sinnvoller. REX_YDATA klingt für mich nach Daten aller Y-AddOns :)

**Comment by dergel** [comment]
das stimmt.. richtig wäre REX_YFORM_DATA .. aber das ist irgendwie so lang ..

**Comment by dergel** [comment]
und ist nun bereits drin .. REX_YFORM_DATA
