### ISSUE TITLE
Reload im Modul

### ISSUE THREAD

**Issue by Sioweb** [yakamara/redaxo_yform#10]
Ho!

Wenn ich im Modul auf eine der Value-Optionen klicke, lädt Redaxo via PJAX die Seite neu. Ich weiß nicht was hier geplant ist, aber cool wäre es wenn die Optionen dann direkt in das Textarea eingefügt werden. Vielleicht ist es das ja schon und wird nur durch PJAX unterbrochen.

lg Sascha

**Comment by dergel** [comment]
lang ists her.. aber leider verstehe ich noch nicht ganz was du mit den optinen meinst .. kannst du mir das konkrete Beispiel hier reinschreiben ?
