### ISSUE TITLE
Value be_manager_relation :: popup multiple zeigt bei übernehmen nur die Id im select

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#100]
Öffnet man das Popup und klickt auf übernehmen, erscheint im `<select>` nur `[Id=24]`

**Comment by gharlan** [comment]
Hab ich schon gefixt: https://github.com/yakamara/redaxo_yform/commit/7f95d3e632297a983429db644a5bc27ec74ab88c
Kannst du bestätigen, dass der Fix funktioniert?

**Comment by tbaddade** [comment]
Fix funktioniert.
