### ISSUE TITLE
Darstellung der Tabellen so lala

### ISSUE THREAD

**Issue by dergel** [yakamara/redaxo_yform#1000]
gerade auch wenn man viele Tabellen hat

- eher tabellennamen anzeigen und danach sortieren
- immer alle tabellen anzeigen und nicht blättern

**Comment by alxndr-w** [comment]
OT: 🎉 Glückwunsch zum 1000. Issue bei YForm

**Comment by dergel** [comment]
oh gott.. 1000 :)
