### ISSUE TITLE
YForm Table Manager: Value "other"

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/redaxo_yform#1005]
Ist ein PR erwünscht, der ein Feld namens `other`, in dem ausschließlich DB-Tabellen-Feldtypen gelistet sind, die sich nicht mit anderen Values erstellen lassen?

z.B.

![image](https://user-images.githubusercontent.com/3855487/109558120-4b045880-7ad9-11eb-863d-1c978f96319a.png)

json, enum, set, binary, bit, tinyint ...

Ich würde es begrüßen, weil es ein Feldtyp ist, mit dem man sicherstellen kann, dass YForm Table Manager nicht ganz spezifische Anwendungsfälle mit bestimmten Optimierungen unterbindet/überschreibt.

**Comment by dergel** [comment]
Eigentlich nicht gewünscht. Für mich sollten eigentlich keine DB spezifischen Dinge genutzt werden. Gerne aber Felder, die einzelne Fälle abdecken, bei denen diese Feldtypen nötig werden.
