### ISSUE TITLE
Beeinflussen der Header in rex_yform_rest::sendContent

### ISSUE THREAD

**Issue by DanielWeitenauer** [yakamara/redaxo_yform#1006]
Aktuell gibt es keine Möglichkeit, die Header der Response zu beeinflussen, um z.B. `Access-Control-Allow-Origin: *` oder `'Access-Control-Allow-Methods: GET` setzen zu können.

Vorschlag von Jan in Slack:

> wenn wir diese methode in die route schieben und header methoden ergänzen wären wir schon einen schritt weiter

**Comment by dergel** [comment]
Was meinst du Daniel .. send in die Route legen und dann beeinflussbar machen. Ich frage mich nur ob wir das frei machen sollten oder bestimmte header wie allow origin schon vorgeben ? Ich habe die REST API Hauptsächlich für Abgleichen zwischen System an gedacht, wenn sowas im Frontend genutzt werden soll, brauche ich ein wenig Input von dir/euch.

**Comment by DanielWeitenauer** [comment]
Ich denke, den Access-Control-Allow-Origin sollte man aus Sicherheitsgründen nur explizit setzen wenn es gebraucht wird. 
Die aus meiner Sicht sauberste Lösung wäre, das Setzen der Header in die Route zu nehmen und per Kind-Klasse überschreibbar zu machen, da die Header ja doch einige sicherheitsrelevante Einstellungen enthalten, die jeder Admin selbst kontrollieren sollte.
Eventuell ein paar Beispiel-Klassen fürs Copy-Pasten mitgeben?

**Comment by dergel** [comment]
aber wahrscheinlich ist es sinnvoll pro request art den header setzen zu können, oder ?
für get, post, ...

**Comment by dergel** [comment]
Ist eingebaut, inkls. Ergänzung in der DOku .. Gerne nochmal extra testen.
