### ISSUE TITLE
Neuen typ Signature anlegen

### ISSUE THREAD

**Issue by dergel** [yakamara/redaxo_yform#1007]
https://codepen.io/nonsalant/pen/JYpjvE

**Comment by alxndr-w** [comment]
Scheint auf einen nicht mehr gepflegten Fork zu verweisen, hier ist das Original: http://brinley.github.io/jSignature/

**Comment by alxndr-w** [comment]
Sorry, kurze Ergänzung nach ein paar Minuten Googlen: Das hier sieht auch interessant aus und ergibt "schönere" Unterschriften, ist außerdem frei von jQuery: http://szimek.github.io/signature_pad/

**Comment by dergel** [comment]
ist nun drin
