### ISSUE TITLE
R5.12.0 kollidiert mit YForm 3.4.1

### ISSUE THREAD

**Issue by christophboecker** [yakamara/redaxo_yform#1008]
Hallo Jan,

im Repository-Master ist die Änderung auf PHP7+8 schon drin, aber im aktuellen Release im Installer (3.4.1) wird noch allein PHP 7 vorausgesetzt. Update auf R5.12.0 (final, nicht beta) crashed bei mir.

**Comment by alxndr-w** [comment]
Das hat dann nichts mit 5.12 zu tun, oder?

**Comment by christophboecker** [comment]
Autsch, Du hast recht. Ich hab noch PHP 8 an statt 7.4. Ich ziehe das Issue gebührend zerknirscht zurück.
