### ISSUE TITLE
Value mediafile :: label nicht vorbelegt

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#101]
Wenn ein Feld noch nicht zugewiesen wurde und man nutzt dann das Value `mediafile`wird nur die Bezeichnung vorbelegt und nicht das `label`. Bei anderen Values sind beide Textfelder ausgefüllt.

**Comment by dergel** [comment]
das verstehe ich leider nicht .. kannst du mir das anders beschreiben ?

**Comment by tbaddade** [comment]
Wenn ein Feld gelöscht wurde, stehen diese oben als Buttons zur Auswahl. Verwendet man eines dieser Felder und wählt dann das Value mediafile ist nur die Bezeichnung vorbelegt und nicht das label.
Besser? Sonst gern per Telefon :)

**Comment by dergel** [comment]
https://github.com/yakamara/redaxo_yform/commit/f3c49fcead487d4528832ac85083c3afaea33736
