### ISSUE TITLE
E-Mail Template body (plain) wird abgeschnitten, wenn "<" in einem Wort enthalten ist

### ISSUE THREAD

**Issue by tyrant88** [yakamara/redaxo_yform#1015]
Sobald im plaintext body eines E-Mail Templates so etwas auftaucht `abc<def` wird, wird alles ab dem "Kleiner"-Zeichen abgeschnitten. Dabei ist es egal, ob es unmittelbar im Template steht oder über eine Variable hereinkommt.

Wenn nach dem "<" ein Space folgt, funktioniert alles. Das legt nahe, das eine Art "strip_tags" das Problem verursacht, weil der String dann nicht für ein HTML-Tag gehalten wird.

![Zwischenablage-2](https://user-images.githubusercontent.com/1277494/111979892-e485bf80-8b05-11eb-831c-659c89a7d25b.jpg)

**Comment by tyrant88** [comment]
REDAXO 5.11.1, YForm 3.4.1

**Comment by dergel** [comment]
Danke für den Hinweis Norbert. Testest du die aktuelle Version noch auf alle Varianten. Nur Text. Nur HTML, Beides ob das in allen KOmbinationen klappt ?

**Comment by tyrant88** [comment]
Ich habe jetzt aus Zeitgründen nur die geänderten Zeilen als Hotfix ins Projekt eingebaut und damit alle Kombinationen aus PlainText und HTML-Body getestet. Klappt natürlich.
