### ISSUE TITLE
Metadaten eines REDAXO-Artikels als Relationsfeld

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/redaxo_yform#1017]
Ist es möglich, die Meta-Feldtypen von der REDAXO-Struktur um ein YForm-Auswahlfeld zu erweitern, das statt die ID/IDs ins Value zu schreiben diese als Paar(e) (artikel_id / datensatz_id) in eine definierte YForm-Tabelle schreibt? 

Ich bräuchte quasi das Gegenstück zu be_category in YForm, sodass die Relation erstellt wird, egal, ob ich einen Datensatz aus YForm einem Artikel zuordne oder umgekehrt einen Artikel mit einem Slice verknüpfe.

**Comment by christophboecker** [comment]
Mal dumm gefragt: ist das ein YForm-Thema oder eher ein Core-Thema (mehr Features für Meta-Felder wie z.B. Validierung)? Hilft https://redaxo.org/doku/main/metainformationen#callback weiter oder einer der ART_-EPs? Oder ich verstehe nicht, was Du beabsichtigst.

**Comment by dergel** [comment]
sehe ich auch bei REDAXO
