### ISSUE TITLE
Value be_manager_relation :: popup multiple Auswahl der Einträge

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#102]
Einträge die bereits im `<select>`vorhanden snd kann man nicht nochmals auswählen. Hier würde ich den "Übernehmen" Button entweder gar nicht anzeigen oder zumindest disabled setzen.

Einträge die während des geöffneten Popup übernommen werden, können mehrfach ausgewählt werden. Die Zuweisung wird zwar nur einmal gespeichert, ist aber dennoch verwirrend. Sobald also einmal auf übernehmen geklickt wurde, sollte auch dieser Button auf disabled gesetzt werden.

**Comment by dergel** [comment]
das ist mittlerweile so, das jeder eintrag, auch wenn er doppelt ausgewählt wird, auch entsprechend gespeichert wird. Doppelungen können ja erwünscht sein. Deswegen muss man nun erstmal nicht bestimmte übernehmen Buttons wegblenden.
