### ISSUE TITLE
Verschachtelte Kategorien als Select

### ISSUE THREAD

**Issue by marcohanke** [yakamara/redaxo_yform#1026]
Tableset aus Slack von Christoph Gerber mit verschachtelten Kategorien und Unterkategorien

`{"chg_test":{"table":{"id":"4","status":"1","table_name":"chg_test","name":"Speisen und Getr\u00e4nke","description":"","list_amount":"50","list_sortfield":"unterkategorie","list_sortorder":"ASC","prio":"4","search":"0","hidden":"0","export":"0","import":"0","mass_deletion":"0","mass_edit":"0","schema_overwrite":"1","history":"0"},"fields":[{"id":"92","table_name":"chg_test","prio":"1","type_id":"value","type_name":"choice","db_type":"text","list_hidden":"0","search":"1","name":"unterkategorie","label":"Unterkategorie","not_required":"","options":"","multiple":"0","default":"","size":"","only_empty":"","message":"","table":"","hashname":"","password_hash":"","no_db":"0","password_label":"","field":"","type":"","empty_value":"","empty_option":"","max_size":"","types":"","fields":"","position":"","address":"","width":"","height":"","show_value":"","html":"","notice":"","regex":"","pattern":"","format":"","current_date":"","widget":"","attributes":"","query":"","category":"","year_start":"","year_end":"","values":"","rules":"","nonce_key":"","nonce_referer":"","sizes":"","messages":"","rules_message":"","script":"","max":"","infotext_1":"","infotext_2":"","choices":"select u.id as value,u.name as label,concat(a.name,' ',k.name) as group_label from chg_unterkategorie u  join chg_kategorie k on k.id=u.kategorie_id  join chg_art a on a.id=k.art_id order by a.prio,k.prio,u.prio","expanded":"0","scope":"","columns":"","googleapikey":"","unit":"","precision":"","scale":"","group_by":"group_label"},{"id":"93","table_name":"chg_test","prio":"2","type_id":"value","type_name":"text","db_type":"varchar(191)","list_hidden":"0","search":"1","name":"name","label":"Bezeichnung","not_required":"","options":"","multiple":"","default":"","size":"","only_empty":"","message":"","table":"","hashname":"","password_hash":"","no_db":"0","password_label":"","field":"","type":"","empty_value":"","empty_option":"","max_size":"","types":"","fields":"","position":"","address":"","width":"","height":"","show_value":"","html":"","notice":"","regex":"","pattern":"","format":"","current_date":"","widget":"","attributes":"","query":"","category":"","year_start":"","year_end":"","values":"","rules":"","nonce_key":"","nonce_referer":"","sizes":"","messages":"","rules_message":"","script":"","max":"","infotext_1":"","infotext_2":"","choices":"","expanded":"","scope":"","columns":"","googleapikey":"","unit":"","precision":"","scale":"","group_by":""},{"id":"94","table_name":"chg_test","prio":"3","type_id":"value","type_name":"text","db_type":"varchar(191)","list_hidden":"1","search":"0","name":"beschreibung","label":"Beschreibung","not_required":"","options":"","multiple":"","default":"","size":"","only_empty":"","message":"","table":"","hashname":"","password_hash":"","no_db":"0","password_label":"","field":"","type":"","empty_value":"","empty_option":"","max_size":"","types":"","fields":"","position":"","address":"","width":"","height":"","show_value":"","html":"","notice":"","regex":"","pattern":"","format":"","current_date":"","widget":"","attributes":"","query":"","category":"","year_start":"","year_end":"","values":"","rules":"","nonce_key":"","nonce_referer":"","sizes":"","messages":"","rules_message":"","script":"","max":"","infotext_1":"","infotext_2":"","choices":"","expanded":"","scope":"","columns":"","googleapikey":"","unit":"","precision":"","scale":"","group_by":""},{"id":"105","table_name":"chg_test","prio":"4","type_id":"value","type_name":"number","db_type":"","list_hidden":"0","search":"1","name":"preis","label":"Preis","not_required":"","options":"","multiple":"","default":"","size":"","only_empty":"","message":"","table":"","hashname":"","password_hash":"","no_db":"0","password_label":"","field":"","type":"","empty_value":"","empty_option":"","max_size":"","types":"","fields":"","position":"","address":"","width":"","height":"","show_value":"","html":"","notice":"","regex":"","pattern":"","format":"","current_date":"","widget":"","attributes":"","query":"","category":"","year_start":"","year_end":"","values":"","rules":"","nonce_key":"","nonce_referer":"","sizes":"","messages":"","rules_message":"","script":"","max":"","infotext_1":"","infotext_2":"","choices":"","expanded":"","scope":"","columns":"","googleapikey":"","unit":"","precision":"5","scale":"2","group_by":""},{"id":"106","table_name":"chg_test","prio":"5","type_id":"value","type_name":"be_media","db_type":"text","list_hidden":"1","search":"0","name":"bild","label":"Bild","not_required":"","options":"","multiple":"0","default":"","size":"","only_empty":"","message":"","table":"","hashname":"","password_hash":"","no_db":"","password_label":"","field":"","type":"","empty_value":"","empty_option":"","max_size":"","types":"","fields":"","position":"","address":"","width":"","height":"","show_value":"","html":"","notice":"","regex":"","pattern":"","format":"","current_date":"","widget":"","attributes":"","query":"","category":"","year_start":"","year_end":"","values":"","rules":"","nonce_key":"","nonce_referer":"","sizes":"","messages":"","rules_message":"","script":"","max":"","infotext_1":"","infotext_2":"","choices":"","expanded":"","scope":"","columns":"","googleapikey":"","unit":"","precision":"","scale":"","group_by":""}]},"chg_kategorie":{"table":{"id":"5","status":"1","table_name":"chg_kategorie","name":"chg_kategorie","description":"","list_amount":"50","list_sortfield":"prio","list_sortorder":"ASC","prio":"5","search":"0","hidden":"0","export":"0","import":"0","mass_deletion":"0","mass_edit":"0","schema_overwrite":"1","history":"0"},"fields":[{"id":"95","table_name":"chg_kategorie","prio":"1","type_id":"value","type_name":"text","db_type":"","list_hidden":"0","search":"0","name":"name","label":"name","not_required":"","options":"","multiple":"","default":"","size":"","only_empty":"","message":"","table":"","hashname":"","password_hash":"","no_db":"0","password_label":"","field":"","type":"","empty_value":"","empty_option":"","max_size":"","types":"","fields":"","position":"","address":"","width":"","height":"","show_value":"","html":"","notice":"","regex":"","pattern":"","format":"","current_date":"","widget":"","attributes":"","query":"","category":"","year_start":"","year_end":"","values":"","rules":"","nonce_key":"","nonce_referer":"","sizes":"","messages":"","rules_message":"","script":"","max":"","infotext_1":"","infotext_2":"","choices":"","expanded":"","scope":"","columns":"","googleapikey":"","unit":"","precision":"","scale":"","group_by":""},{"id":"96","table_name":"chg_kategorie","prio":"2","type_id":"validate","type_name":"size_range","db_type":"","list_hidden":"1","search":"0","name":"name","label":"","not_required":"","options":"","multiple":"","default":"","size":"","only_empty":"","message":"error: size max in name is 50","table":"","hashname":"","password_hash":"","no_db":"","password_label":"","field":"","type":"","empty_value":"","empty_option":"","max_size":"","types":"","fields":"","position":"","address":"","width":"","height":"","show_value":"","html":"","notice":"","regex":"","pattern":"","format":"","current_date":"","widget":"","attributes":"","query":"","category":"","year_start":"","year_end":"","values":"","rules":"","nonce_key":"","nonce_referer":"","sizes":"","messages":"","rules_message":"","script":"","max":"50","infotext_1":"","infotext_2":"","choices":"","expanded":"","scope":"","columns":"","googleapikey":"","unit":"","precision":"","scale":"","group_by":""},{"id":"110","table_name":"chg_kategorie","prio":"3","type_id":"value","type_name":"prio","db_type":"int","list_hidden":"1","search":"0","name":"prio","label":"Reihenfolge","not_required":"","options":"","multiple":"","default":"","size":"","only_empty":"","message":"","table":"","hashname":"","password_hash":"","no_db":"","password_label":"","field":"","type":"","empty_value":"","empty_option":"","max_size":"","types":"","fields":"name","position":"","address":"","width":"","height":"","show_value":"","html":"","notice":"","regex":"","pattern":"","format":"","current_date":"","widget":"","attributes":"","query":"","category":"","year_start":"","year_end":"","values":"","rules":"","nonce_key":"","nonce_referer":"","sizes":"","messages":"","rules_message":"","script":"","max":"","infotext_1":"","infotext_2":"","choices":"","expanded":"","scope":"art_id","columns":"","googleapikey":"","unit":"","precision":"","scale":"","group_by":""},{"id":"111","table_name":"chg_kategorie","prio":"4","type_id":"value","type_name":"choice","db_type":"text","list_hidden":"1","search":"0","name":"art_id","label":"Kategorie","not_required":"","options":"","multiple":"0","default":"","size":"","only_empty":"","message":"","table":"","hashname":"","password_hash":"","no_db":"0","password_label":"","field":"","type":"","empty_value":"","empty_option":"","max_size":"","types":"","fields":"","position":"","address":"","width":"","height":"","show_value":"","html":"","notice":"","regex":"","pattern":"","format":"","current_date":"","widget":"","attributes":"","query":"","category":"","year_start":"","year_end":"","values":"","rules":"","nonce_key":"","nonce_referer":"","sizes":"","messages":"","rules_message":"","script":"","max":"","infotext_1":"","infotext_2":"","choices":"select id,name from chg_art order by prio","expanded":"0","scope":"","columns":"","googleapikey":"","unit":"","precision":"","scale":"","group_by":""}]},"chg_unterkategorie":{"table":{"id":"6","status":"1","table_name":"chg_unterkategorie","name":"chg_unterkategorie","description":"","list_amount":"50","list_sortfield":"prio","list_sortorder":"ASC","prio":"6","search":"0","hidden":"0","export":"0","import":"0","mass_deletion":"0","mass_edit":"0","schema_overwrite":"1","history":"0"},"fields":[{"id":"99","table_name":"chg_unterkategorie","prio":"1","type_id":"value","type_name":"text","db_type":"","list_hidden":"0","search":"0","name":"name","label":"name","not_required":"","options":"","multiple":"","default":"","size":"","only_empty":"","message":"","table":"","hashname":"","password_hash":"","no_db":"0","password_label":"","field":"","type":"","empty_value":"","empty_option":"","max_size":"","types":"","fields":"","position":"","address":"","width":"","height":"","show_value":"","html":"","notice":"","regex":"","pattern":"","format":"","current_date":"","widget":"","attributes":"","query":"","category":"","year_start":"","year_end":"","values":"","rules":"","nonce_key":"","nonce_referer":"","sizes":"","messages":"","rules_message":"","script":"","max":"","infotext_1":"","infotext_2":"","choices":"","expanded":"","scope":"","columns":"","googleapikey":"","unit":"","precision":"","scale":"","group_by":""},{"id":"100","table_name":"chg_unterkategorie","prio":"2","type_id":"validate","type_name":"size_range","db_type":"","list_hidden":"1","search":"0","name":"name","label":"","not_required":"","options":"","multiple":"","default":"","size":"","only_empty":"","message":"error: size max in name is 50","table":"","hashname":"","password_hash":"","no_db":"","password_label":"","field":"","type":"","empty_value":"","empty_option":"","max_size":"","types":"","fields":"","position":"","address":"","width":"","height":"","show_value":"","html":"","notice":"","regex":"","pattern":"","format":"","current_date":"","widget":"","attributes":"","query":"","category":"","year_start":"","year_end":"","values":"","rules":"","nonce_key":"","nonce_referer":"","sizes":"","messages":"","rules_message":"","script":"","max":"50","infotext_1":"","infotext_2":"","choices":"","expanded":"","scope":"","columns":"","googleapikey":"","unit":"","precision":"","scale":"","group_by":""},{"id":"104","table_name":"chg_unterkategorie","prio":"3","type_id":"value","type_name":"choice","db_type":"int","list_hidden":"0","search":"1","name":"kategorie_id","label":"Kategorie","not_required":"","options":"","multiple":"0","default":"","size":"","only_empty":"","message":"","table":"","hashname":"","password_hash":"","no_db":"0","password_label":"","field":"","type":"","empty_value":"","empty_option":"","max_size":"","types":"","fields":"","position":"","address":"","width":"","height":"","show_value":"","html":"","notice":"","regex":"","pattern":"","format":"","current_date":"","widget":"","attributes":"","query":"","category":"","year_start":"","year_end":"","values":"","rules":"","nonce_key":"","nonce_referer":"","sizes":"","messages":"","rules_message":"","script":"","max":"","infotext_1":"","infotext_2":"","choices":"select id,name from chg_kategorie","expanded":"0","scope":"","columns":"","googleapikey":"","unit":"","precision":"","scale":"","group_by":""},{"id":"112","table_name":"chg_unterkategorie","prio":"4","type_id":"value","type_name":"prio","db_type":"int","list_hidden":"1","search":"0","name":"prio","label":"Reihenfolge","not_required":"","options":"","multiple":"","default":"","size":"","only_empty":"","message":"","table":"","hashname":"","password_hash":"","no_db":"","password_label":"","field":"","type":"","empty_value":"","empty_option":"","max_size":"","types":"","fields":"name","position":"","address":"","width":"","height":"","show_value":"","html":"","notice":"","regex":"","pattern":"","format":"","current_date":"","widget":"","attributes":"","query":"","category":"","year_start":"","year_end":"","values":"","rules":"","nonce_key":"","nonce_referer":"","sizes":"","messages":"","rules_message":"","script":"","max":"","infotext_1":"","infotext_2":"","choices":"","expanded":"","scope":"kategorie_id","columns":"","googleapikey":"","unit":"","precision":"","scale":"","group_by":""}]},"chg_art":{"table":{"id":"7","status":"1","table_name":"chg_art","name":"chg_art","description":"","list_amount":"50","list_sortfield":"prio","list_sortorder":"ASC","prio":"7","search":"0","hidden":"0","export":"0","import":"0","mass_deletion":"0","mass_edit":"0","schema_overwrite":"1","history":"0"},"fields":[{"id":"107","table_name":"chg_art","prio":"1","type_id":"value","type_name":"text","db_type":"varchar(191)","list_hidden":"0","search":"0","name":"name","label":"name","not_required":"","options":"","multiple":"","default":"","size":"","only_empty":"","message":"","table":"","hashname":"","password_hash":"","no_db":"0","password_label":"","field":"","type":"","empty_value":"","empty_option":"","max_size":"","types":"","fields":"","position":"","address":"","width":"","height":"","show_value":"","html":"","notice":"","regex":"","pattern":"","format":"","current_date":"","widget":"","attributes":"","query":"","category":"","year_start":"","year_end":"","values":"","rules":"","nonce_key":"","nonce_referer":"","sizes":"","messages":"","rules_message":"","script":"","max":"","infotext_1":"","infotext_2":"","choices":"","expanded":"","scope":"","columns":"","googleapikey":"","unit":"","precision":"","scale":"","group_by":""},{"id":"108","table_name":"chg_art","prio":"2","type_id":"validate","type_name":"size_range","db_type":"","list_hidden":"1","search":"0","name":"name","label":"","not_required":"","options":"","multiple":"","default":"","size":"","only_empty":"","message":"error: size max in name is 50","table":"","hashname":"","password_hash":"","no_db":"","password_label":"","field":"","type":"","empty_value":"","empty_option":"","max_size":"","types":"","fields":"","position":"","address":"","width":"","height":"","show_value":"","html":"","notice":"","regex":"","pattern":"","format":"","current_date":"","widget":"","attributes":"","query":"","category":"","year_start":"","year_end":"","values":"","rules":"","nonce_key":"","nonce_referer":"","sizes":"","messages":"","rules_message":"","script":"","max":"50","infotext_1":"","infotext_2":"","choices":"","expanded":"","scope":"","columns":"","googleapikey":"","unit":"","precision":"","scale":"","group_by":""},{"id":"109","table_name":"chg_art","prio":"3","type_id":"value","type_name":"prio","db_type":"int","list_hidden":"1","search":"0","name":"prio","label":"Reiehenfolge","not_required":"","options":"","multiple":"","default":"","size":"","only_empty":"","message":"","table":"","hashname":"","password_hash":"","no_db":"","password_label":"","field":"","type":"","empty_value":"","empty_option":"","max_size":"","types":"","fields":"","position":"","address":"","width":"","height":"","show_value":"","html":"","notice":"","regex":"","pattern":"","format":"","current_date":"","widget":"","attributes":"","query":"","category":"","year_start":"","year_end":"","values":"","rules":"","nonce_key":"","nonce_referer":"","sizes":"","messages":"","rules_message":"","script":"","max":"","infotext_1":"","infotext_2":"","choices":"","expanded":"","scope":"name","columns":"","googleapikey":"","unit":"","precision":"","scale":"","group_by":""}]}}`

**Comment by cedrus86** [comment]
Produkthieracthie am Beispiel von Speisekarten. Nur als Beispiel für die Demo

**Comment by alxndr-w** [comment]
@marcohanke du hast doch noch ein anderes vollständiges Tableset angefertigt, oder? Kannst du das rüberwachsen lassen?

**Comment by dergel** [comment]
Richtig verstanden, dass dies nur als Demo gedacht ist ?

**Comment by dergel** [comment]
ich schliesse mal etwas öfter wie hier auch. Das nimmt mit den Issues überhand ;)

**Comment by marcohanke** [comment]
@dergel  Das war zum Testen von Christoph Gerber ausm Slack. Sorry, war untergeghangen.
