### ISSUE TITLE
upload im Frontend

### ISSUE THREAD

**Issue by cedrus86** [yakamara/redaxo_yform#1029]
In einem YFORM-Formular im Frontend habe ich zwei Felder, ein Textfeld und ein Uploadfeld. Ich kann jederzeit die DAten wieder holen und aktualisieren. Ich erwarte, dass unveränderte Felder auch unverändert bleiben. Insbesondere wenn kein neues File hochgeladen wird, soll das alte seine Gültigkeit behalten. Im Backend funktioniert das problemlos, Im Frontend wird der Filname in der DB gelöscht.

```
	$yform->setValueField('text', ['name','name','','0']);`
	$yform->setValueField('upload', array("logo_file","Upload","",".jpg,.gif,.png,.jpeg"));
```

Mit upload sieht es wie erwartet aus:
![grafik](https://user-images.githubusercontent.com/67410314/116576385-cd5d9d00-a90f-11eb-82e2-a2529433f58e.png)
Ohne upload wird der DB-Wert überschrieben 
![grafik](https://user-images.githubusercontent.com/67410314/116576204-a4d5a300-a90f-11eb-8b11-9c3604d66fde.png)

**Comment by dergel** [comment]
wie nutzt du es ? weil so alleine wird es nicht laufen, da ist sicher noch php drumherum. Das hängt z.T. auch an Sessions etc .. Kann ich deswegen so noch nicht orten. Gerne mal in Slack mich ansprechen und mir direkt zeigen.. bis dahin verschiebe ich es auf 4.1

**Comment by marcohanke** [comment]
Same here.
Ich hab ein Uploadfeld in einem Formular. Das Formular lässt sich speichern und immer wieder neu editieren. Bei jedem neuen editieren wird die Datei mit dem leeren Uploadfeld überschrieben. Erwartet hätte ich, dass Upload nur überschrieben wird, wenn ein neues Dokument ausgewählt wird. Andernfalls sollte der alte Kram bestehen und manuell löschbar sein.

**Comment by IngoWinter** [comment]
Mit main_id (siehe einen weiter oben) wird beim ersten Senden des Formulares der Eintrag in der DB nicht gelöscht. Folgt direkt darauf ein zweites Senden, wird der Eintrag gelöscht. Ursache ist, dass in der postAction Methode die Session Werte für die bereits existierende Datei gelöscht werden: 
https://github.com/yakamara/redaxo_yform/blob/master/lib/yform/value/upload.php#L241-L243
Wenn ich die drei Zeilen lösche, verhält sich das Feld beim Frontend Upload wie erwartet.

**Comment by marcohanke** [comment]
@dergel Getestet im Frontend mit aktueller Redaxo aus dem Installer und YFORM aus github.
Wie oben beschrieben geht das Uploadfeld verloren.
Mit ```$yform->setObjectparams('main_id',rex_ycom_auth::getUser()->getId());``` funktioniert es aber.

**Comment by dergel** [comment]
ich habe es nochmal probiert. ich kann es nicht nachvollziehen. Ich habe diesen Code verwendet

```
<?php

$data_id = 4;

$yform = new rex_yform();
$yform->setDebug();
$yform->setObjectparams('form_showformafterupdate', 1);
$yform->setObjectparams('real_field_names', true);
$yform->setObjectparams('getdata',1);
$yform->setObjectparams('main_where','id='.$data_id);
$yform->setObjectparams('main_table','rex_kv30_dokument');
$yform->setObjectparams('main_id', $data_id);
$yform->setValueField('text', ['meintextfeld','Mein Titel']);
$yform->setValueField('upload', ['myupload','Upload','','*']);

$yform->setActionField('db', ['','main_where']);

echo $yform->getForm();

?>
```

dabei müssen natürlich die Tabelle, die Felder und die eigentlich Datensatz ID geändert werden. Hoffe wir kommen damit besser voran. Gerne mir den Code schicken, bei dem es nicht funktioniert + den UseCase nochmal genauer beschreiben - vielleicht kapiere ich es auch einfach noch nicht.

**Comment by marcohanke** [comment]
Ähh, du setzt doch auch main_id und damit gehts. Ohne main_id gehts nicht. In der Doku hab ich dazu auf die Schnelle nichts gefunden, ich schreibs mal mit auf die ToDoListe

**Comment by dergel** [comment]
Wichtig zu wissen.

- Add und Edit Formulare sind unterschiedlich. D.h. form_showformafterupdate nicht bei add Formularen verwenden
- Wenn Edit, dann muss die main_id/where/table gesetzt werden, damit die richtigen Daten ins Formular kommen, wir auch die db Action muss hier entweder sie identisch die main_where aus den Objecparams sein, wie hier, darauf verweisen, damit die DAten auch wieder richtig gespeichert werden.

Mit diesen Infos schliesse ich das issue, gerne mit konkretem Codebeispiel, Usecase und Fehler ein neues Issue aufmachen.

**Comment by alxndr-w** [comment]
Ein Formular-Upload muss auch ohne main_id möglich sein. Ich verstehe nicht, wie das zur Debatte stehen kann.

**Comment by dergel** [comment]
ok zwei Sachen.

@alxndr-w du meinst, eine main_id mit einer Tabelle sollte ausreichen, sodass man auf main_where verzichten kann, oder? Finde ich gut. Dann muss man halt noch ein Primary field einsetzen. Ich glaube in der Realität braucht man die vorhandene Unterscheidung nicht. Ich habe Fälle in yrewrite gefunden, die man dann anpassen müsste.

@IngoWinter Ich kann es nicht nachbauen. Egal, wie oft ich speichere, ob ich eine Datei vorher oder später hochgeladen habe, initial ein File vorhanden was oder auch nicht, es funktioniert bei mir. Irgendwas verstehe ich nicht. Willst du mich kontaktieren und wir gehen das mal zusammen durch? Slack oder anders?

**Comment by marcohanke** [comment]
@dergel Ich hatte das Verhalten von Ingo auch. Bis zum update auf die aktuellen Github Versionen. Damit läufts.

main_id, main_where.
Ich hab keine Ahnung was die main_id ist und finde auch nichts dazu. Ich kapiers aber auch nicht. Warum findet ein Textfeld seinen Kontent wenn ich main_where auf eine ID setze, ein Upload Feld aber nicht?

**Comment by alxndr-w** [comment]
@dergel wir müssen Mal direkt schnacken, damit wir nicht aneinander vorbei reden. Bin auch nicht mehr auf Slack (so wie @IngoWinter), aber du kannst dir auf meiner Website eine Zeit reservieren für einen Videoanruf.

**Comment by IngoWinter** [comment]
Jupp, in der 4.0.0-beta5 ist das Problem behoben 👍

**Comment by dergel** [comment]
dann close ich mal :)

**Comment by cedrus86** [comment]
Mit 4.0 getestet, tutet

**Comment by alxndr-w** [comment]
Mit 4.0 getestet, tut natürlich wieder nicht. Die hochgeladene Datei bleibt im Server-tmp-Ordner (nicht dem von YForm) und es gibt keine Möglichkeit, mit Bordmitteln YForm dazu zu bewegen, diese ordnungsgemäß zu verschieben.

Nochmal: Der Upload einer Datei in einem neuen Datensatz im Frontend muss möglich sein.
