### ISSUE TITLE
datetime - eigenes Format wird nicht unterstützt

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#103]
Es erscheint nur eine **1**. Selbst die `<select>` sind nicht vorhanden.

Getestet mit der aktuellen GH Version

**Comment by tbaddade** [comment]
Das Ganze passiert, wenn man einen `:` im Format angibt.

**Comment by alexplusde** [comment]
Am Doppelpunkt alleine liegt es nicht. (Relase-Version)

![image](https://cloud.githubusercontent.com/assets/3855487/16727678/7f7ce62c-4762-11e6-8afe-a9c7a94f060a.png)

![image](https://cloud.githubusercontent.com/assets/3855487/16727691/8c3d3312-4762-11e6-9e2d-37115564f15c.png)

@gharlan weißt du da was?

**Comment by dergel** [comment]
Jabbsr du das mit der GH Version testen, da hier schon etwas geändert wurde

**Comment by tbaddade** [comment]
@alexplusde 
> Getestet mit der aktuellen GH Version

vs

> Am Doppelpunkt alleine liegt es nicht. (Release-Version)

Du vergleichst mit 2 unterschiedlichen Versionen. Verwende mal die GH Version

**Comment by dergel** [comment]
in der aktuellen version hier auf gh funktioniert es
