### ISSUE TITLE
Fieldset: Fehlende Felder im Tablemanager?

### ISSUE THREAD

**Issue by christophboecker** [yakamara/redaxo_yform#1038]
Letztens ging es im Slack (?) um die Klassen und Optionen, die man dem Fieldset-Feld beigeben kann. Die kannte ich noch gar nicht, da ich nur mit dem Table-Manager arbeite und nicht mit Pipe- oder PHP-Schreibweise.

Daher ist mir nun aufgefallen, dass den Klassen und Optionen im Table-Manager die Eingabefelder fehlen. Es gibt nur 'name' und 'label', kein 'option' und 'class'.

Absicht oder Zufall? Sind ja nur zwei Zeilen Code.

```php
    public function getDescription()
    {
        return 'fieldset|name|label|[class]|[onlyclose/onlycloseall/onlyopen/closeandopen]';
    }

    public function getDefinitions()
    {
        return [
            'type' => 'value',
            'name' => 'fieldset',
            'values' => [
                'name' => ['type' => 'name',  'label' => rex_i18n::msg('yform_values_defaults_name')],
                'label' => ['type' => 'text',  'label' => rex_i18n::msg('yform_values_defaults_label')],
            ],
            'description' => rex_i18n::msg('yform_values_fieldset_description'),
            'db_type' => ['none'],
            'is_searchable' => false,
            'is_hiddeninlist' => true,
            'multi_edit' => 'always',
        ];
    }
```

**Comment by alxndr-w** [comment]
Soweit ich das für @dergel beantworten kann vermute ich keine Absicht dahinter. Ich wollte auch längst schon einen PR dazu machen.

Jetzt erinnere ich mich auch wieder, warum ich um fieldsets einen Bogen im Table Manager machte.
