### ISSUE TITLE
datetime / date / time - Bootstrap Template fehlt / widget wahl hinzufügen

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#104]
das setzen eines grids wäre sinnvoll.

`#grid:col-md-2,col-md-2,col-md-2,col-md-2`

**Comment by dergel** [comment]
konkreter vorschlag ?

**Comment by dergel** [comment]
und einbindung von 

https://github.com/dangrossman/bootstrap-daterangepicker


http://symfony.com/doc/current/reference/forms/types/date.html#widget
widget
type: string default: choice

* choice: renders three select inputs. The order of the selects is defined in the format option.
* text: renders a three field input of type text (month, day, year).
* single_text: renders a single input of type date. User's input is validated based on the format option.

**Comment by dergel** [comment]
* input mask noch rein 
* date/time validierung

**Comment by dergel** [comment]
- [ ] input mask
- [ ] Datepicker
- [ ] date/time validierung hinzufügen
- [ ] Dokumentation tools Plugin
- [ ] Template widget select bootstrap noch erstellen
- [ ] DateTime Formatierungen allgemein nutzen, Speicherformat immer MySQL [DATE][TIME]
- [ ] Select2 / Bootstrap noch implementieren

**Comment by tbaddade** [comment]
Bootstraptemplate existiert jetzt. Da bei dir @dergel noch paar Checkboxen abgehakt sind, lasse ich das Issue offen.

**Comment by dergel** [comment]
Zeitraumsuche hatte noch gefehlt ..
