### ISSUE TITLE
Werte können nicht vollständig entfernt werden 

### ISSUE THREAD

**Issue by lexplatt** [yakamara/redaxo_yform#1043]
Wenn man im Backend ein be_manager_relation mit den Einstellungen:
- select (multiple)
- mit leer option
- in Kombination mit eine Relationstabelle

kann man das Feld nicht vollständig leer, d.h. wenn man einmal einen Wert eingegeben hat kann man das Feld nicht mehr leeren.

Ich habe das durch-debugged und herausgefunden dass in folgender Zeile immer wieder der letzte Werte eingesetzt wird, da der value === null übergeben wird

https://github.com/yakamara/redaxo_yform/blob/05084f7d0bd52f749a325d6ffef6c354b904eae9/plugins/manager/lib/yform/value/be_manager_relation.php#L48

**Comment by dergel** [comment]
@lexplatt kannst du schauen ob das bei choice auch so ist.. select gibt es in der 4.0 nicht mehr..

**Comment by dergel** [comment]
outdated
