### ISSUE TITLE
"Tabelle leeren" setzt nicht den Autoincrement zurück

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#1044]
Üblicherweise wird beim Leeren einer Tabelle der Autoincrement zurückgesetzt. Das passiert derzeit nicht.

Ich vermute mal, es werden die Datensätze gelöscht und nicht die Tabelle via Truncate geleert. Da finde ich es sinnvoller den Button entsprechend umzubenennen oder doch tatsächlich zu leeren.

**Comment by dergel** [comment]
Es werden alle Datensätze einzekn gelöscht, da sich dahinter ja trigger befinden können, die "irgendetwas" machen. Warum ist es wichtig, dass das autoincrement zurückgesetzt wird ?

**Comment by tbaddade** [comment]
> Warum ist es wichtig, dass das autoincrement zurückgesetzt wird ?

Das ist es nicht. Es eher darum, dass der Button "Tabelle leeren" etwas suggeriert was nicht stattfindet. Leeren setzt normalerweise den Autoincrement zurück und das hatte ich jetzt auch erwartet. :)

Nebenan gibt es auch den Button "Datenergebnis löschen" was momentan genau das gleiche Verhalten hat.

**Comment by dergel** [comment]
Dann müssten wir es textlich ändern, weil es vorkommen kann, dass ein Datensatz nicht gelöscht werden kann.

Datenergebnis löscht auch nur eine Liste von Daten, es können auch welche übrig bleiben. Sofern es ein Problem darstellt, würde ich lieber über eine andere Benennung nachdenken.

**Comment by alxndr-w** [comment]
Leider heißt der Button nur "leeren", man kann das vorangegangene "Tabelle" an der Stelle ja nicht wegübersetzen. Kompromiss-Vorschlag in #1167

**Comment by dergel** [comment]
Danke für den PR. Das erklärt es besser.
