### ISSUE TITLE
Aktuelle Dev-Version: Table Manager: CSRF-Token ungültig wenn Datensatz via Watson aufgerufen wird

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/redaxo_yform#1045]
![image](https://user-images.githubusercontent.com/3855487/118503348-d8476880-b72a-11eb-9601-2d0dfc49ca54.png)

Aufruf über die GUI von Watson

**Comment by christophboecker** [comment]
Den Effekt gibt es auch in anderen Zusammenhängen. Ich gebe z.B. einen "Löschen nicht möglich"-Fehler aus mit dem Hinweis, wo genau der Datensatz noch referenziert ist. Der Hinweis hat einen Link, der direkt das Formular des fehlerauslösenden Datensatzes aufruft. Klappt grundsätzlich gut, aber mit CSFR-Fehler wie von Alexander beschrieben. Ich nutze die Github-Version.

**Comment by dergel** [comment]
Die Debug XXX Meldung ist draussen.

Leider muss das ansonsten so sein. Man könnte zwar diskutieren, warum das auch bei edit ohne sent so sein muss, aber in der YForm passieren je nach Definition auch Dinge beim reinen Aufruf der Editiermaske. Deswegen ist der benötigte CSRF Key nötig.

Aber man kann die Links ja ergänzen, damit es richtig abläuft:

`$_csrf_key = rex_yform_manager_table::get('tabellenname')->getCRSFKey()`

In der URL mit der Edit/Delete Aufruf noch das ergänzen + `rex_csrf_token::factory($_csrf_key)->getUrlParams())`

Sofern ok so, gerne Issue schliessen

**Comment by christophboecker** [comment]
Ah, cool! Was es nicht alles gibt!

**Comment by christophboecker** [comment]
Müsste es nicht `getCSRFKey`heißen und nicht `getCRSFKey` ?

**Comment by alxndr-w** [comment]
Bestimmt hat @dergel gehofft, dass es nie einem auffällt. Und nun das.

https://github.com/yakamara/redaxo_yform/search?q=getCRSFKey&type=

PR mit Alias-Funktion gewünscht?

**Comment by dergel** [comment]
oh mann :) .. Sorry, aber nun passt es ..
