### ISSUE TITLE
Aktuelle Dev-Version: Datenbanktabellen-Rechte - Standard-Verhalten für Rollen

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/redaxo_yform#1046]
Bei dem Update via GitHub-Version wurden keine Rechte zugewiesen.
![image](https://user-images.githubusercontent.com/3855487/118525094-151d5a80-b73f-11eb-91d4-f1050cb6fa89.png)

Standard-Verhalten sollte sein, dass bei einem Update von YForm 2.x/3.x alle Rollen alle Rechte haben und diese abgewählt werden müssen. Ich habe unbedacht das Update in eine Live-Version gepackt, um die realen Auswirkungen zu testen - nun hat die Redakteurin bei 20 Tabellen nur noch Leserechte statt wie vorher Schreibrechte.

Neu angelegte Tabellen können meinetwegen mit abgewählten Rollen starten - ich glaube, sinnvoller wäre umgekehrt, jeder Rolle alle Rechte zu geben.

Beim Anlegen einer neuen Rolle sollte es möglich sein, gleich alle Tabellenrechte zuzuweisen, statt in alle Tabellen zu müssen. Hier hatte ich alle in der Rolle aktiviert - das wird jedoch nicht übernommen: 
![image](https://user-images.githubusercontent.com/3855487/118525614-ac82ad80-b73f-11eb-988d-45081193ecd6.png)

**Comment by dergel** [comment]
Ich habe das zurückgesetzt.. d.h. die Rechte werden wie vorher über die Rollen direkt verwaltet und nun nach View und Edit unterschieden. Beim Update, werden die aktzellen Tabellenrechte auf EDIT Rechte gesetzt, so wie es sein sollte.
