### ISSUE TITLE
Aktuelle Dev-Version: Berechtigungen pro User oder pro Rolle - Feld "be_role"

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/redaxo_yform#1049]
Um die Brücke zu den Rollen richtig zu schaffen wäre es ideal, wenn man neben be_user auch ein be_role-Feld hätte, bei dem ein Datensatz einer oder mehreren Rolle zugewiesen wird. Diese könnte man dann im nächsten Schritt in der Übersicht filtern und den Zugriff zum Bearbeiten/Löschen entfernen.

**Comment by dergel** [comment]
Einzelne Datensätze finde ich nicht gut. Mein PLan ist es, in der 4.1 wahrscheinlich direkt, über SETs zu arbeiten. Man benutzt die Suche um sich ein SET zu filtern auf den jemand dann Zugriff hat. Dann könnte man in diesem Set auch sagen ID=3.. Ich schliesse das Issue hier deswegen

**Comment by alxndr-w** [comment]
Auch gut, erfüllt ja dann denselben Zweck.
