### ISSUE TITLE
Table Manager: unique: Feldnamen kommagetrennt angeben

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#105]
Siehe:
https://github.com/yakamara/redaxo_yform_docs/issues/18#issuecomment-231562687

@dergel dein Vorschlag, das Feld "Tabelle [opt]" zu entfernen würde die Funktionalität entfernen, die man in der Pipe-Schreibweise hat. Stattdessen sollte man die Felder lieber in einem Input-Feld kommagetrennt angeben können, analog zum YForm-Modul.

**Comment by dergel** [comment]
habe ich gemacht .. ist im letzten commit aber als meldung untergegangen..

**Comment by alexplusde** [comment]
Klasse :)
