### ISSUE TITLE
Datenimport in Tabelle - Validierung / EPs abschalten

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/redaxo_yform#1051]
Ich habe eine CSV mit 6000 Einträgen, die vom Server nicht innerhalb der maximalen Skriptlaufzeit verarbeitet werden. Dabei habe ich die YForm EPs in Verdacht, die zu viel Zeit kosten. So bekomme ich die Daten leider nicht importiert.

Kann man diese beim Import überspringen und dann vlt. nochmal final feuern?

**Comment by dergel** [comment]
Ich denke es liegt einfach daran, dass jeder Import den YForm Formularprozess durchläuft, also geprüft wird, ob die Daten passen, unique oder sonstwas sind. Dadurch wird die konsistens der Tabelle gesichert. Wenn du weisst, welche Daten da reinkommen, macht es hier und da durchaus sinn, dass selbst über mysql oder ein eigenes Skript als Rohdaten zu importieren
