### ISSUE TITLE
be_manager_relation: unterschiedliche $fieldkey-Struktur in Subformularen

### ISSUE THREAD

**Issue by christophboecker** [yakamara/redaxo_yform#1053]
Hab mich über das HTML in Feld be_manager_relation / "inline (multiple n-1) gewundert.

https://github.com/yakamara/redaxo_yform/blob/1e2528871fbe7cf68f02e02a73314a7660641c97/plugins/manager/ytemplates/bootstrap/value.be_manager_inline_relation.tpl.php#L20-L27

Zunächst wird ein leeres Prototyp-Formular erzeugt. der Wert von `$fieldkey` ist zu dem Zeitpunkt sowas `rex_kv30_dokument-rex_kv30_historie2-hi_id_dokument`. Anschließend wird der Wert von `$fieldkey` auf einen neuen Wert gesetzt (yae2234f241747c65781183b4b4188ad43a3f9531). Die danach erzeugten Subformulare des Datenbestandes haben dann diesen neuen Wert. 

War das Absicht? Jedenfalls erschließt sich mir der Sinn nicht ganz. Sollen dadurch neue und alte Subformulare leichter erkennbar sein (was muss man beim Speichern einfügen, was muss man updaten)?

**Comment by dergel** [comment]
ohne jetzt in die Tiefe reinzuschauen glaube ich. dass der Grund in den verschachtelten Subformularen besteht. Als Inline in inline in inline relationen z.B.,, Habe gerade nicht die Zeit da tiefer reinzublicken. Weiss nur noch, dass es eine ziemlich komplizierte Geschichte war.
