### ISSUE TITLE
HTML: Überflüssiges Attribut "data-yform-be-relation-add-position"?

### ISSUE THREAD

**Issue by christophboecker** [yakamara/redaxo_yform#1054]
Im Template `value.be_manager_inline_relation_form.tpl.php` bin ich über das HTML-Attribut `data-yform-be-relation-add-position` im **Addme**-Button gestolpert. Das Attribut wird hier zwar in den Button eingebaut, aber an keiner anderen Stelle im YForm-Verzeichnis habe ich `data-yform-be-relation-add-position` gefunden.

https://github.com/yakamara/redaxo_yform/blob/1e2528871fbe7cf68f02e02a73314a7660641c97/plugins/manager/ytemplates/bootstrap/value.be_manager_inline_relation_form.tpl.php#L18-L22

Nur so als Hinweis: das könnte vieleicht mal raus und damit das HTML entschlacken.

**Comment by tbaddade** [comment]
> Das Attribut wird hier zwar in den Button eingebaut, aber an keiner anderen Stelle im YForm-Verzeichnis habe ich data-yform-be-relation-add-position gefunden.

Wird hier verwendet
https://github.com/yakamara/redaxo_yform/blob/master/plugins/manager/assets/manager.js#L148

**Comment by christophboecker** [comment]
Punkt! Da hab ich wohl falsch gesucht.
