### ISSUE TITLE
Table Manager: Prio der definierten Felder durcheinander

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/redaxo_yform#1056]
Ich weiß nicht, unter welchen Umständen, aber gelegentlich sind die Feld-Prios durcheinander. Das Problem wurde in Slack von mehreren bestätigt.

In der Datenbank steht dann bspw. das hier:

![image](https://user-images.githubusercontent.com/3855487/121056944-06b2e380-c7bf-11eb-99e3-d4b5ce15add5.png)

Nachdem ein Feld bearbeitet wird, rutscht dieses ganz nach oben und bekommt prio=1 - sollte aber eigentlich in derselben Reihenfolge bleiben wie vorher - das Feld, das hier prio=1 bekommen hat, hätte prio=7 bekommen müssen und alle anderen eins weniger: 

![image](https://user-images.githubusercontent.com/3855487/121057018-1fbb9480-c7bf-11eb-811c-8689ff4098f1.png)

**Comment by alxndr-w** [comment]
In der Oberfläche zu "Feld bearbeiten" bekommt die Auswahl bereits 

![image](https://user-images.githubusercontent.com/3855487/121057274-63ae9980-c7bf-11eb-8b6b-c8ca92b00ff9.png)

Vermutlich, weil der alte Prio-Wert und damit Index nicht mehr vorhanden ist.

**Comment by dergel** [comment]
Ich kann es leider nicht nachvollziehen bei meinen Tests.. Vielleicht hast du hier auch was parat was du mir live zeigen kannst ? wie auch bei dem anderen Issue

**Comment by alxndr-w** [comment]
Liegt an YForm Usability. Definitiv. @dergel und ich haben es gemeinsam nachgestellt.
