### ISSUE TITLE
Aktuelle Beta: Tabelleneinstellungen Datenansicht beschränken - Probleme bei be_manager_relation 

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/redaxo_yform#1057]
Wenn der Redakteur keine Bearbeitenrechte hat, sondern Werte eines Datensatzes nur ansehen darf, dann werden bei be_manager_relation-Feldern ALLE Werte ausgegeben und nicht nur die tatsächlich ausgewählten.

Ist evtl. auch bei Choice und Co. der Fall oder nur bei bestimmten Relationstypen - das habe ich jetzt nicht überprüft.

**Comment by dergel** [comment]
das stimmt.. ist auch so gewollt. Ich sehe hier noch kein Problem, lass mich aber gerne aufklären :)

**Comment by alxndr-w** [comment]
Es ist gewollt, dass alle Werte ausgegeben werden und nicht nur die, die tatsächlich ausgewählt wurden?!

**Comment by dergel** [comment]
ja, der entsprechende Datensatz soll komplett lesbar sein.

**Comment by alxndr-w** [comment]
@dergel ich glaube, wir reden immer noch aneinander vorbei.

`be_manager_relation` greift z.B. auf `rex_obst` zurück.

`rex_obst` enthält: `Apfel, Birne, Ananas, Aprikose, Banane, Brombeere, Dattel, Feige.`

Ausgewählt wurde im Datensatz nur `Apfel, Banane`.

In der Readonly-Ansicht werden nicht `Apfel, Banane` gezeigt, sondern `Apfel, Birne, Ananas, Aprikose, Banane, Brombeere, Dattel, Feige.`

**Comment by dergel** [comment]
jetzt verstehe ich was du meinst .. ich habe das auf die Felder/Werte im Datensatz bezogen. Das finde ich ok. es werden ja eventuell auch andere Datensätze ausgewählt oder dürfen ausgewählt werden. Ich will nicht ausschliessen, dass irgendwann auch nochmal das Rechtekonzept überarbeitet wird, auch bezüglich der Felder, sehe aber im Moment kein eigenes Issue dazu

**Comment by alxndr-w** [comment]
Das verfälscht die Information, ich will ja wissen, was ausgewählt wurde und im Datensatz enthalten ist - und nicht, was zur Auswahl stand. Ich verstehe deine Perspektive darauf nicht.

**Comment by dergel** [comment]
Dann reden wir aneinander vorbei.. demnach ist es wohl ein Bug den ich nicht nachvollziehen kann. Um es an einem Beispiel klar zu machen. Nehmen wir die YCom mit den Gruppen.

Habe testweise einem REDAXO User nur die Rollen mit Gruppe User mit Editierrechten gegeben. Er kann nun die User bearbeiten und sieht in der YCom User Liste (hab die Relation dort ausgegeben) nur die Gruppen die auch einem User zugewiesen worden sind. Beim Editieren eines Users (was er dann ja darf) sieht er den User und kann dem User eine neue Gruppe zuweisen (und sieht demnach auch andere Gruppen). Ist es das was du meinst, dass da etwas falsch läuft ?

**Comment by alxndr-w** [comment]
Nein. Ich versuche, zeitnah einen Screencast aufzunehmen, dann fällt es wie Schuppen von den Augen, wie es gemeint ist :)

**Comment by dergel** [comment]
Nun verstanden..  In der View Ansicht eines Datensatzes sieht man alle Verknüpfungen statt nur der eigentlich selektierten

**Comment by alxndr-w** [comment]
Gilt auch für Choice #1095

**Comment by dergel** [comment]
sollte nun passen. Gerne prüfen
