### ISSUE TITLE
3.5 ist nicht rückwärtskompatibel - sollte 4.0 sein

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/redaxo_yform#1058]
Durch die Berechtigungen verliert jede Rolle standardmäßig Zugriff auf die Tabellen, die sie früher hatten, wenn sie einfach eine YForm-Berechtigung hatten.

**Comment by dergel** [comment]
Habe auch darüber nachgedacht und muss dir zustimmen..

**Comment by alxndr-w** [comment]
🍫 Schokolade zum Trost.
