### ISSUE TITLE
Attribute für Formularelemente

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#106]
Momentan sind die Attribute `placeholder`, `disabled`etc. fest in den Templates gezurrt.

Notation um eigenen Attribute einzuschleusen
`#attr:placeholder=Platzhalter;data-key=value;class=markitup`

Ob die Trenner so sinnvoll sind, müsste man schauen. Mir geht es um nur darum, dass man die Attribute frei definieren kann. Grad für `data-` wäre das hilfreich.

**Comment by alexplusde** [comment]
https://github.com/yakamara/redaxo_yform/issues/42

**Comment by dergel** [comment]
ansich so machbar .. aber das ganze soll ncoh im manager funktionieren.. da bin ich gerade noch überfragt

**Comment by dergel** [comment]
hätte gern eure meinung .. ist spezieller umgesetzt, da das problem auch speziell ist.

es gibt nun ein feld "attributes" welches man beim manager und oder auch bei pipe notation genutzt werden kann.. aber, die eingabe muss ein json array sein. 

`{"readonly":"readonly","placeholder":"Mein Placeholder", "class":"codemirror"}`

würde vielleicht das Feld in "field-attributes" umbennen wollen (Namensvorschläge sind erwünscht)

**Comment by dergel** [comment]
die bisherigen Möglichkeiten wie |#placeholder:MeinPlatzhalter bleiben.

ImMoment nur bei text und textarea umgesetzt

**Comment by polarpixel** [comment]
Die Eingabe ist lernbar, das ist  nicht das Problem. Klingt, als ob man sehr flexibel wäre.
Und das klappt jetzt also im Formbuilder und im Manager?
Und in der PHP-Schreibweise für Formular-Output ginge es auch?

Dann fände ich das eine feine Lösung, glaube ich.

**Comment by dergel** [comment]
und attributes als benennung findet du ok ? oder doch lieber "fieldattributes" ..

**Comment by tbaddade** [comment]
Das Json ist nur für die Elemente gedacht oder auch für die anderen Möglichkeiten wie in Skype diskutiert?

**Comment by dergel** [comment]
im moment nur für das feld selber.. man könnte das noch ausweiten, sehe ich aber im moment noch als zu mächtig und kompliziert an. Vielleicht in den nächsten Versionen etwas ähnliches
