### ISSUE TITLE
REST API - $paths reindexieren

### ISSUE THREAD

**Issue by xong** [yakamara/redaxo_yform#1061]
array_filter hinterlässt Lücken im $paths-Array: https://github.com/yakamara/redaxo_yform/blob/3be75be0729b63182619f95d24011dc520f8daad/plugins/rest/lib/rest.php#L70

Das führt z. B. beim Löschen von Datensätzen zu einer Notice und der Datensatz kann so nicht gelöscht werden: https://github.com/yakamara/redaxo_yform/blob/3be75be0729b63182619f95d24011dc520f8daad/plugins/rest/lib/rest/route.php#L376

Es sollte ausreichen, das Array mit array_values zu reindexieren.

**Comment by dergel** [comment]
und eine Abfrage darüber war auch falsch.. ist korrigiert, kommt aber erst in Version 4.0

bis dahin, für die die das hier lesen, über filter[id]=xx löschen
