### ISSUE TITLE
ycom und yrewrite Versionsbedingungen anpassen

### ISSUE THREAD

**Issue by dtpop** [yakamara/redaxo_yform#1068]
Aktuell gibt es noch eine Fehlermeldung beim Versuch die 4 beta zu installieren:

`AddOn yform konnte aus folgendem Grund nicht aktualisiert werden:
    AddOn ycom meldet: Das AddOn yform (Version 4.0.0-beta2) entspricht nicht der geforderten Versionsbedingung ^3.3.1!
    AddOn yrewrite meldet: Das AddOn yform (Version 4.0.0-beta2) entspricht nicht der geforderten Versionsbedingung ^3.2!`

**Comment by marcohanke** [comment]
Das selbe bei yrewrite_domain_settings

**Comment by dergel** [comment]
sicherlich auch noch andere addons.. die kann ich aber hier nicht abdecken.. bitte bei den entsprechenden AddOn schreiben.

yrewrite und ycom mache ich

**Comment by dergel** [comment]
ycom ist gemacht

**Comment by gharlan** [comment]
yrewrite 2.8 ist nun auch verfügbar.
