### ISSUE TITLE
mediafile - Datei wird mehrfach in den Medienpool geladen

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#1069]
REDAXO: 5.12.0
YForm: 3.4.1

Nutzt man das Value im Frontend und lässt das Formular validieren, so wird <del>scheinbar</del> <ins>anscheinend</ins> bei jedem Submit die Datei erneut in den Medienpool geladen.

**Comment by dergel** [comment]
Kannst du mir ein Beispiel bauen was ich zum testen nutzen kann?

**Comment by alxndr-w** [comment]
Der ganze Prozess mit Upload von Dateien innerhalb von YForm kränkelt. Aber ich schätze, da kann jetzt keine Zeit mehr reinfließen deinerseits @dergel? Sonst würde ich Mal bündeln und vorbereiten, was alles aktuell kaputt ist bei be_media, mediafile und upload und wie es funktionieren müsste.

Ein Profilbild eines YCom-Logins wäre ein Beispiel, bei dem die Datei im Medienpool (aber geschützt mit entsprechenden Metainfos vom Auth-Plugin) vorliegen sollte und nicht andernorts.

**Comment by dergel** [comment]
Das Beispiel finde ich gut um zu verstehe, dass mediafile doch sinnvoll ist. Bin gerade dabei das zu optimieren. be_media sollte nun passen und ich glaube insgesamt sollte es nun, wenn das hier auch steht, schon ganz sinnvoll sein.

**Comment by marcohanke** [comment]
Gerade mit aktueller Redaxo und YForm Version aus Github getestet. Im Frontend und im Backend landet die Datei beim speichern im Medienpool. Beim erneuten speichern und oder übernehmen wird kein Duplikat erstellt.
Was mir aber noch aufgefallen ist: Beim löschen bleibt die Datei im Medienpool. Ist das gewollt? Falls Datenschutzrechtlich relevante Daten verarbeitet werden müsste man das halt nachträlich noch anders abfangen. Oder macht es Sinn beim Löschen die Datei auch aus dem Medienpool zu löschen (eigentlich hätte ich das erwartet beim Label "Löschen".

**Comment by dergel** [comment]
Ja, schwierig mit dem Löschen. Erwarte ich das? Je nachdem. Deswegen wäre eine entsprechende Option wahrscheinlich gut. Weiterhin wird die Datei schon direkt gespeichert, auch wenn das Formular noch nicht validiert wurde.

**Comment by dergel** [comment]
und Fehlermeldungen in Front und Backend müssten hier unterschieden werden, da aus den mediapool Serviceklassen die Backendwarnungen kommen.

**Comment by tbaddade** [comment]
Ich finde, das mediafile könnte raus und für Frontend sollte das upload Value weiter optimiert werden. Dazu gehört für mich dann aber auch eine Art Medienpool/Dateiablage, wo man alle Dateien auch verwalten und von dort auch in die Datensätze springen kann. So hätten wir Backend und Frotenduploads schön getrennt.

**Comment by dergel** [comment]
Ich habe mich nun dafür entschieden, das Feld zu löschen. Vieles wird sich zu upload doppeln, wenn ich es entsprechend umbauen muss und es gibt auch einiges an Sicherheitsaspekten zu beachten, wenn wir es so belassen würden. Ich sehe keinen gravierenden Vorteil mediafile zu behalten. Konzentrieren mich lieber auf fehlende Features von upload (z.B. wenn der media_manager ein Profilbild ausgeben muss oder ähnliches)

**Comment by alxndr-w** [comment]
@dergel wenn du umbaust, hast du die anderen Issues zu mediafile und upload auf dem Schirm? Da gibt es ein paar, die man vlt gleich mitfixen kann.

**Comment by dergel** [comment]
mediafile fixen muss ich nun nichts mehr :) .. aber, wenn es Issues gibt, die man schließen kann, wäre ich über Hilfe sehr froh. upload funktioniert und habe ich für 4.0 keine Dinge auf dem Schirm. @alxndr-w siehst du da was sehr Relevantes?

**Comment by skerbis** [comment]
huhu ... dass das mediafile Feld weg ist, ist nicht wirklich gut. Ich nutze es sehr häufig und stelle damit so einige Dinge an.

**Comment by alxndr-w** [comment]
> mediafile fixen muss ich nun nichts mehr :) .. aber, wenn es Issues gibt, die man schließen kann, wäre ich über Hilfe sehr froh. upload funktioniert und habe ich für 4.0 keine Dinge auf dem Schirm. @alxndr-w siehst du da was sehr Relevantes?

Ja. 

* Upload/Multiupload 
* aus Frontend/Backend in 
* Medienpool/ohne Medienpool 
* mit/ohne Drag&Drop
* inkl. Validierung

Das sind für mich die 5 Anforderungen, die aktuell nie zufriedenstellend gelöst sind - egal mit welchem Feld, irgendwas ist immer. Ich hatte mit https://github.com/FriendsOfREDAXO/yform_dropzone/ mal begonnen, @skerbis mit https://github.com/FriendsOfREDAXO/uppy - alles irgendwie halbfertig vor sich hin dümpelnd.

**Comment by alxndr-w** [comment]
> mediafile fixen muss ich nun nichts mehr :) .. aber, wenn es Issues gibt, die man schließen kann, wäre ich über Hilfe sehr froh. upload funktioniert und habe ich für 4.0 keine Dinge auf dem Schirm. @alxndr-w siehst du da was sehr Relevantes?

Ja. 

* Upload/Multiupload  https://github.com/yakamara/redaxo_yform/issues/430
* aus Frontend/Backend in 
* Medienpool/ohne Medienpool 
* mit/ohne Drag&Drop
* inkl. Validierung

Das sind für mich die 5 Anforderungen, die aktuell nie zufriedenstellend gelöst sind. Ich hatte mit https://github.com/FriendsOfREDAXO/yform_dropzone/ mal begonnen, @skerbis mit https://github.com/FriendsOfREDAXO/uppy
