### ISSUE TITLE
values: readtable, Leerzeichen for Element(1) fehlt

### ISSUE THREAD

**Issue by Goldfischpeter** [yakamara/redaxo_yform#107]
$gd = rex_sql::factory()->setQuery('SELECT * FROM' . $this->getElement(1) . ' WHERE ' . $this->getElement(2) . '= ?', [$v]);

Sonst muss der Parameter Tabelle mit einem Leerzeichen beginnen.

**Comment by alexplusde** [comment]
Sollte es nicht generell vermieden werden, die Parameter inline zu schreiben?

Also eher:
`$gd = rex_sql::factory()->setQuery('SELECT * FROM :table WHERE :field = :value', array(':table' => $this->getElement(1), ':field' => $this->getElement(2),':value' => $v));`

(Wahrscheinlich müsste man da mal über alle SQL-Befehle drübergehen)

**Comment by dergel** [comment]
das ding ist quatsch.. entferne ich. kann nicht funktioniert haben und ich sehe keinen usecase.

**Comment by alexplusde** [comment]
Auch keine so gute Idee :/

```
"ErrorException" thrown in /kunden/322541_70190/alexplus.de/rex5/redaxo/src/addons/yform/lib/yform.php on line 549
Fatal error: Class 'rex_yform_value_readtable' not found
```

**Comment by dergel** [comment]
das ist ok .. ist nur im cache noch drin gewesen.. passt
