### ISSUE TITLE
Yform4beta2: Problem mit YFORM_DATA_LIST_QUERY - id nicht eindeutig

### ISSUE THREAD

**Issue by christophboecker** [yakamara/redaxo_yform#1070]
YForm 4.0 beta2: bisher habe ich mit dem EP YFORM_DATA_LIST_SQL die Abfrage so erweitert, dass mir zusätzliche Informationen inkl. verdichteter Auswertungen (z.B. Group-Concat, etc. etc.) direkt im Datensatz lagen. Damit konnte ich vermeiden, in teilweise mehreren Feldern einer Zeile wider neue SQL-Abfragen durchzuführen.

Das scheint ja nun anders, da alles YORM-basiert ist. Beim Versuch, einen Join via neuem EP YFORM_DATA_LIST_QUERY in die Yorm-Query einzubauen, kam diese Fehlermeldung:
 
**Error while executing statement "SELECT `id` AS value FROM `rex_kv30_dokument` AS t0 INNER JOIN `rex_kv30_historie` ON `t0`.`id` = `rex_kv30_historie`.`hi_id_dokument` WHERE ( YEAR(do_datum) = 1919 ) AND `do_id_doktyp` = :p1 ORDER BY `do_datum` ASC" using params {"p1":"1"}! SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in field list is ambiguous**

Ist das ein Bug oder ein Feature?

**Comment by alxndr-w** [comment]
Hast du versucht, das Feld mit Tabelle zu spezifizieren? `table.id` statt `id`?

**Comment by christophboecker** [comment]
Das ist vom System so generiert. Keine Ahnung warum. Keine Ahnung wie man eingreifen könnte.

**Comment by tbaddade** [comment]
Kannst du den Code, der zum Query führt, notieren?

**Comment by dergel** [comment]
ohne zu wissen was du genau machen willst, du kannst auch reines SQL in den Query legen

**Comment by christophboecker** [comment]
@tbaddade: ich schraub mal eine Demo zusammen.

@dergel: Das SQL-Ding schaue ich mir auch mal an, Danke für den Hinweis.

**Comment by christophboecker** [comment]
Hallöle,  ich habe einen Testcase als Addon gebaut. https://github.com/christophboecker/YF4b2-Testcase

bei der Installation werden vier Tabellen rex_yf4b_xxx angelegt und befüllt (dataset.sql) und und die zugehörigen YForm-Tabellendefinitionen angelegt (tableset.json). Die Menüpunkte des Addon zeigen 

- die Tabellen (buch, dokumente,historie, scan) als abgestrippte Fassung der Originale 
- Tabelle "Dokumente" wie sie mit YF bis 4-beta1 aussieht, nach dem die Abfrage mit EP YFORM_DATA_LIST_SQL bearbeitet wird
- Tabelle Dokumente bei YF4-beta2 mit YFORM_DATA_LIST_QUERY angegangen. Sobald ich einen Join hinzufüge crasht es. Da der Fehlerstack angezeigt wird, sollte es die nötigen Hinweise geben. 

Mit dem blauen Button kommt man direkt in den jeweiligen Code.

<img width="1334" alt="grafik" src="https://user-images.githubusercontent.com/10065904/123544639-8562c700-d754-11eb-8811-dd59349f3eee.png">

Bitte bei der Installation nicht irritieren lassen: Der Tableset-Import dauert nun mal traditionell sehr lange und bei mir zeigt sich, dass nach dem Import und Verschwinden der pjax-Warteanzeige noch mal ungefähr dieselbe Zeit vergeht, bis sich der Bildschim neu aufbaut mit der Fertig-Meldung. In Summe 21 Sekunden. Strange, too.

Redaxo 5.12.1 | MySQL 8.0.17 | PHP 7.4.16 | YForm 4.0.0-beta1 nach 4.0.0-beta2

**Comment by christophboecker** [comment]
Update: Erfolgreich war ich bisher nur im Ändern der Sortierung (OderBy) und Hinzufügen von Filtern (Where). Das ist ja schon mal gut und einfacher als Umarbeiten eines SQL-Commands.

Sobald ein Join im Spiel ist: crash. Eigene Felder (Select xyz) werden gepflegt ignoriert.

**Comment by tbaddade** [comment]
> Eigene Felder (Select xyz) werden gepflegt ignoriert.

Machst du ein `resetSelect()` vorher?

**Comment by christophboecker** [comment]
Die selbstdefinierten Felder werden zumindest freiwillig eingebaut, wie es bei Änderungen des SQL bisher der Fall war. Wenn ich zusätzlich die Spalte von Hand im EP YFORM_LIST_GET eintrage, kann ich das Feld nutzen (siehe 'monat' im Screenshot) 

Der Screenshot zeigt was passiert, wenn ich vorher resetSelect ausführe. Die regulären Felder sind leer
<img width="1543" alt="grafik" src="https://user-images.githubusercontent.com/10065904/123657609-3c347500-d831-11eb-8c21-51754f7be35b.png">

**Comment by tbaddade** [comment]
Es liegt an dieser Zeile
https://github.com/yakamara/redaxo_yform/blob/master/plugins/manager/lib/list.php#L152

Das selektiert die `id AS value`. Es fehlt für mich dort, dass ein eventuelles notiertes Alias auch genutzt wird.

Ansonsten hatte ich deinen EP versucht so zu notieren

```php
\rex_extension::register('YFORM_DATA_LIST_QUERY', function( \rex_extension_point $ep ) use($tablename) {
    /** @var rex_yform_manager_query $query */
    $query = $ep->getSubject();
    if( $tablename !== $query->getTablename() ) return;

    $query->resetSelect();
    $query->alias('dokument');
    $query->select('dokument.id');
    $query->leftJoinRelation('d_id_historie', 'historie');

    dump(get_defined_vars());
});
```

**Comment by christophboecker** [comment]
Ah, gleich mal getestet. Ich hab die Zeile versuchsweise geändert in
```php
$this->rows = count($this->query->findValues($this->query->getTableAlias().'.id'));
```
Damit war das Problem insgesamt noch nicht weg :-( Jetzt wid die fehlerhalte "ORDER BY id" angemeckert. Auslöser dafür ist `$listName = substr(md5($query->getQuery()), 0, 8);` in 
https://github.com/yakamara/redaxo_yform/blob/a78e07d69592ee1bf403ab573160a750c1174f36/plugins/manager/lib/list.php#L95
Der Auslöser müsste hier die Übernahme der Sort-Order aus der Tabellendefinition sein:
https://github.com/yakamara/redaxo_yform/blob/a78e07d69592ee1bf403ab573160a750c1174f36/plugins/manager/lib/yform/manager/query.php#L594
Mit der zusätzlichen Änderung
```php
$this->orderBy($this->getTableAlias().'.'.$table->getSortFieldName(), $table->getSortOrderName());
```
läuft es ... aber vermutlich auch nur, weil ich bereits in den Tabellen alle Felder außer "id" übergreifend eindeutige Namen haben (d_datum, s_datum, h_datum, b_datum). Das teste ich als nächstes.

**Comment by tbaddade** [comment]
Vermutlich wäre es sinnvoll, dass YForm immer mit Alias für die Tabellen arbeitet.

**Comment by christophboecker** [comment]
Ich hab de Datums-Felder alle in "datum" geändert. In der Haupttabelle werden die automatisch generierten Spalten wohl automatisch mit Alias versehen, es gab jedenfalls keinen Konflikt mit "datum" in den Join-Tabellen. Und wenn man im Query-EP eigene Felder definiert muss der Entwickler halt an den Alias denken (gehört zur Job Description <smile>).

**Comment by tbaddade** [comment]
>  Und wenn man im Query-EP eigene Felder definiert muss der Entwickler halt an den Alias denken (gehört zur Job Description ).

Ich meinte, dass YForm selbst auch für die erste Tabelle einen Alias setzen sollte. 
Dass anstatt `id AS value` eben `alias.id AS value` gesetzt wird.

**Comment by christophboecker** [comment]
Das scheint ja zu passieren. Mit `$query->getTableAlias()` bekommt man entweder den mit `$query->alias('xyz')` gesetzen Alias xyz oder den Tabellennamen als default-Alias. In meiner Dokument-Tabelle habe ich nun eineFeld "datum". in den beiden verlinkten Tabellen ist ebenfalls ein Feld "datum". Die Dokument-Tabelle wird korrekt angezeigt. Also scheint das interne Aliassing zu funktionieren.

**Comment by tbaddade** [comment]
> Das scheint ja zu passieren.

Scheinbar eben nicht. Ich bekam mit meinen Anpassungen von oben immer noch einen Queryfehler obwohl der Alias gesetzt wurde.
https://github.com/yakamara/redaxo_yform/blob/master/plugins/manager/lib/list.php#L152

**Comment by christophboecker** [comment]
Hm, mein Usecase fluppt, aber nur mit beiden Anpassungen
-  [https://github.com/yakamara/redaxo_yform/blob/master/plugins/manager/lib/list.php#L152](https://github.com/yakamara/redaxo_yform/blob/master/plugins/manager/lib/list.php#L152)
- [https://github.com/yakamara/redaxo_yform/blob/master/plugins/manager/lib/yform/manager/query.php#L594](https://github.com/yakamara/redaxo_yform/blob/master/plugins/manager/lib/yform/manager/query.php#L594)

```php
 \rex_extension::register('YFORM_DATA_LIST_QUERY', function( \rex_extension_point $ep ) use($tablename) {
    $query = $ep->getSubject();
    if( $tablename !== $query->getTablename() ) return;

    $alias = $query->getTableAlias();

    $query->selectRaw('COUNT(t1.id)','anzahl_boote');
    $query->leftJoinRelation('d_id_historie','t1');

    $query->selectRaw('(0 < COUNT(t2.id) )','im_jahrbuch');
    $query->joinRaw('LEFT', 'rex_yf4b_buch', 't2', 'FIND_IN_SET('.$alias.'.id, t2.b_id_dokument)');

    $query->groupBy($alias.'.id');
    dump(get_defined_vars());
});


\rex_extension::register('YFORM_DATA_LIST', function( \rex_extension_point $ep ) use($tablename) {
    $table = $ep->getParam('table');
    if( $tablename !== $table->getTablename() ) return;

    $list = $ep->getSubject();

    $list->setRowAttributes(function($list){
        return $list->getValue('im_jahrbuch') ? '' : 'class="text-danger"';
    });

    // Bootshistorie nicht direkt verlinken
    $list->removeColumn('d_id_historie');

    // Titel ausschreiben
    $list->setColumnFormat('d_titel', 'custom', function ($params) { return $params["value"];} );

    // Scans nicht auflisten, nur Statistik (Anzahl Scans, Anzahl verlinkte Boote)
    $list->setColumnLabel('d_id_scan','Scans<br>Boote');
    $list->setColumnFormat('d_id_scan','custom', function ($params) {
        $scans = count(explode(',',$params["value"])) ?: '-';
        $boote = $params['list']->getValue('anzahl_boote') ?: '-';
        return "$scans | $boote";
    } );

    dump(get_defined_vars());
});
```

**Comment by dergel** [comment]
Ich gehe davon aus, dass es damit erledigt ist ? Willst du das issue schliessen wenn das so ist @christophboecker

**Comment by christophboecker** [comment]
Wenn @tbaddade das auch sieht ....

**Comment by christophboecker** [comment]
Und ich habe den Verdacht, dass Thomas gar nicht so Unrecht hat mit seinem Verdacht ....

**Comment by tbaddade** [comment]
Ich denke, dass der Manager intern immer mit einem Alias arbeiten sollte.

**Comment by christophboecker** [comment]
Je nun, dem Statement schließe ich mich vorbehaltlos an. 

Wäre also die Frage, macht wer auch immer ein eigenes Issue auf "Alias im Manager sicherstellen" oder soll dieses als Reminder offen bleiben. Mein Vorschlag ist, dieses hier zu schließen, denn mein Ursprungsproblem ist behoben. Ich möchte aber den von Thomas aufgeworfenen Punkt nicht unberücksichtigt wissen.

**Comment by dergel** [comment]
ich schliesse und gerne ein neues issue aufmachen
