### ISSUE TITLE
YForm (aktuelle Github-Version) Reinstallation nicht möglich:

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/redaxo_yform#1072]
```
Required plugin "yform/docs" does not exist.
```

**Comment by dergel** [comment]
Das muss man leider manuell löschen (über den Installer löschen). Ist wohl eher ein REDAXO Problem, dass man vorhandene Plugins, die ein aktuelles AddOn nicht mehr mitführt, nicht installiert werden kann.

**Comment by gharlan** [comment]
> Required plugin "yform/docs" does not exist.

Die Meldung wundert mich. Kann es sein, dass du irgendwie noch eine alte package.yml hattest, wo das docs-Plugin noch als required gesetzt war?
Wobei es eigentlich schon im Februar 2020 entfernt wurde aus den system_plugins: https://github.com/yakamara/redaxo_yform/commit/150dedea3e98e97e5149a54bb5e929567188fc96#diff-7a613aa05c6e6b153fc1809c490f49216af8dd52bcb31b8ec64489b9730d6865

**Comment by alxndr-w** [comment]
Es gab mal in 5.11/5.12 Probleme mit falsch gecachten Klassen, kann das aus dieser Zeit stammen? Nach einem halben Jahr weiß ich nicht, wann und wie das passiert ist.

War mit Sicherheit auch über den Github-Installer geladen und dann reinstalliert, nicht den offiziellen Weg. Wenns offiziell passt (und das tut es scheinbar), dann kann hier zu.

Während ich hier tippe, frage ich mich, ob der ZIP-Installer drüberbügelt und beim reinstall dann eine gecachte package.yml verwenden kann?
