### ISSUE TITLE
Aktuelle GitHub-Version: Unique in Relationstabelle darf nicht dazu führen, dass Datensatz nicht mehr gespeichert wird.

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/redaxo_yform#1073]
![image](https://user-images.githubusercontent.com/3855487/123543550-61e94d80-d74f-11eb-85ee-70494c594f11.png)

Der Hauptdatensatz wurde bearbeitet - das Speichern wird nun jedoch verhindert.

**Comment by dergel** [comment]
Kannst du mir einen Tablesetexport zuschicken, damit ich das nachbauen kann ?

**Comment by alxndr-w** [comment]
Siehe Slack

**Comment by alxndr-w** [comment]
Perfekt.
