### ISSUE TITLE
Notice: Undefined index: relation_table bei Update yform/ycom

### ISSUE THREAD

**Issue by marcohanke** [yakamara/redaxo_yform#1076]
Nach dem Update von yform mit bestehender ycom bekomme ich:

`Notice: Undefined index: relation_table in redaxo/src/addons/yform/plugins/manager/lib/yform/manager/field.php on line 121`

**Comment by dergel** [comment]
bei normalen aufruf der ycom ? also immer in redaxo ? Egal wie, gerne das issue dann zur ycom .. die muss ja noch entsprechend auf die yform 4 abgestimmt werden
