### ISSUE TITLE
Komisches Feldverhalten nach Update (ycom)

### ISSUE THREAD

**Issue by marcohanke** [yakamara/redaxo_yform#1077]
Nach dem Update ist in der Übersicht das Feld ycom/login verschwunden obwohl "In Liste verstecken" abgehakt ist. Das Feld ycom/status ist zweimal zu sehen, obwohl es laut adminer nur einmal existiert.
Checkbox "In Liste verstecken" aktivieren/deaktivieren bringt keine Änderung.

**Comment by dergel** [comment]
Schau mal bitte in der Datenbank wie diese beiden status Felder sich unterscheiden und kannst du mir diese Information hier ablegen? Ich glaube das Thema ist bereits gelöst, dennoch würde ich gerne sichergehen.

**Comment by marcohanke** [comment]
Geht leider nicht mehr, ich hab das damals manuell gelöst und habe die Instanz nicht mehr.

**Comment by alxndr-w** [comment]
Die Felddefinition war, soweit ich mich erinnere, einmal select und einmal choice.

**Comment by dergel** [comment]
das habe ich mittlerweile mit abgefangen, also dass die select felder automatisch bei der installation oder update auf 4.0 auf choice umgewandelt werden. Wenn das für mich noch jemand testen könnte wäre das eine große Hilfe

**Comment by marcohanke** [comment]
Beim Update von  ycom 3.0-beta4 auf ycom 4.0 bleibt das Feld status in rex_ycom_user weiterhin select.
Beim Update von 4.0 auf 4.0.6 bekomme ich nicht mehr auf die rex_ycom_user sondern den Fehler:
Error while executing statement "SELECT COUNT(*) AS `rows` FROM (select `id`,NULL AS `html1`,`login`,`email`,`password`,`firstname`,`name`,NULL AS `html2`,`status`,`activation_key`,`session_key`,`new_password_required`,`last_action_time`,`last_login_time`,`termination_time`,`login_tries`,NULL AS `html3`,`ycom_groups`,`status`,`termsofuse_accepted` from `rex_ycom_user` t0 ORDER BY `login` DESC) t": SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'status'
#0 /Users//webdev/dev.test/redaxo/src/core/lib/list.php(189): rex_sql->setQuery('SELECT COUNT(*)...')
#1 /Users//webdev/dev.test/redaxo/src/core/lib/list.php(226): rex_list->__construct('select `id`,NUL...', '100', 'f6aa8af8', false, 1)
#2 /Users//webdev/dev.test/redaxo/src/addons/yform/plugins/manager/lib/yform/manager.php(439): rex_list::factory('select `id`,NUL...', '100')
#3 /Users//webdev/dev.test/redaxo/src/addons/yform/plugins/manager/pages/data_edit.php(20): rex_yform_manager->getDataPage()
#4 /Users//webdev/dev.test/redaxo/src/core/lib/packages/package.php(285): include('//...')
#5 /Users//webdev/dev.test/redaxo/src/core/lib/be/controller.php(485): rex_package->includeFile(NULL, NULL)
#6 /Users//webdev/dev.test/redaxo/src/core/lib/util/timer.php(57): rex_be_controller::{closure}()
#7 /Users//webdev/dev.test/redaxo/src/core/lib/be/controller.php(486): rex_timer::measure('Page: addons/yf...', Object(Closure))
#8 /Users//webdev/dev.test/redaxo/src/core/lib/be/controller.php(432): rex_be_controller::includePath('//...', Array)
#9 /Users//webdev/dev.test/redaxo/src/addons/yform/pages/index.php(3): rex_be_controller::includeCurrentPageSubPath()
#10 /Users//webdev/dev.test/redaxo/src/core/lib/packages/package.php(285): include('//...')
#11 /Users//webdev/dev.test/redaxo/src/core/lib/be/controller.php(485): rex_package->includeFile(NULL, NULL)
#12 /Users//webdev/dev.test/redaxo/src/core/lib/util/timer.php(57): rex_be_controller::{closure}()
#13 /Users//webdev/dev.test/redaxo/src/core/lib/be/controller.php(486): rex_timer::measure('Page: addons/yf...', Object(Closure))
#14 /Users//webdev/dev.test/redaxo/src/core/lib/be/controller.php(415): rex_be_controller::includePath('//...')
#15 /Users//webdev/dev.test/redaxo/src/core/backend.php(238): rex_be_controller::includeCurrentPage()
#16 /Users//webdev/dev.test/redaxo/src/core/boot.php(143): require('//...')
#17 /Users//webdev/dev.test/redaxo/index.php(9): require('//...')
#18 {main}

**Comment by dergel** [comment]
und beides ist yform 4, ja?

**Comment by marcohanke** [comment]
Ne, für die ycom 3 hatte ich yform 3 und musste dann für 4 auch die yform auf 4 aktualisieren.

**Comment by dergel** [comment]
und wenn du ein yform reinstall machst, passt es dann?

**Comment by marcohanke** [comment]
Reinstall der geladenen Github Version hat nix gebracht.

**Comment by dergel** [comment]
jetzt ist es noch schwerer das zu testen, weil ycom angepasst werden muss, damit es mit der neuesten yform wieder geht. Deswegen schliesse ich das hier - hier gehts dann damit weiter

https://github.com/yakamara/redaxo_ycom/issues/389
