### ISSUE TITLE
Feautre Request: In Liste verstecken, Als Suchfeld aufnehmen angleichen

### ISSUE THREAD

**Issue by marcohanke** [yakamara/redaxo_yform#1078]
Wenn wir soweiso schon bei Breaking Changes sind würde es sich doch anbieten:
Ich stolpere immer wieder über die zwei Checkboxen. In Liste verstecken ist quasi ein negativ Statsu, Als Suchfeld aufnehmen ein Positiv status. Könnte man das nicht angleichen?
Also in Liste anzeigen, Als Suchfeld aufnehmen?
Das hätte zusätzlich den Vorteil, dass man bei umfangreichen Formularen nicht dauernd "In Liste verstecken" klicken muss.

**Comment by alxndr-w** [comment]
Finde ich absolut unterstützenswert.

Oder, wie es in YForm bisher heißt: Finde ich nicht verwerfungswürdig.
