### ISSUE TITLE
yform (GH-Version) + ycom: rex_yform_action_encrypt_value fehlt

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#108]
Nach der Aktivierung von ycom:
"ErrorException" thrown in /kunden/322541_70190/alexplus.de/rex5/redaxo/src/addons/yform/lib/yform.php on line 590
Fatal error: Class 'rex_yform_action_encrypt_value' not found

**Comment by alexplusde** [comment]
Danach lässt sich ycom zwar irgendwie installieren, aber scheinbar nicht richtig, es werden weitere Fehler und Warnungen ausgegeben.

**Comment by alexplusde** [comment]
Aktuelle GitHub-Version von YForm (und Redaxo 5.1-Version von YCom):
`
"Exception" thrown in /kunden/322541_70190/alexplus.de/rex5/redaxo/src/addons/yform/plugins/manager/lib/yform/manager/table_api.php on line 193
more than one field found for table: rex_ycom_user with Fieldidentifier: value, ycom_auth_password, password

#0 /kunden/322541_70190/alexplus.de/rex5/redaxo/src/addons/yform/plugins/manager/lib/yform/manager/table_api.php(73): rex_yform_manager_table_api::setTableField('rex_ycom_user', Array)
#1 /kunden/322541_70190/alexplus.de/rex5/redaxo/src/addons/yform/plugins/manager/lib/yform/manager/table_api.php(117): rex_yform_manager_table_api::setTable(Array, Array)
#2 /kunden/322541_70190/alexplus.de/rex5/redaxo/src/addons/ycom/install.php(4): rex_yform_manager_table_api::importTablesets('{"rex_ycom_user...')
#3 /kunden/322541_70190/alexplus.de/rex5/redaxo/src/core/lib/packages/package.php(228): include('/kunden/322541_...')
#4 /kunden/322541_70190/alexplus.de/rex5/redaxo/src/core/lib/packages/manager.php(126): rex_package->includeFile('install.php')
#5 /kunden/322541_70190/alexplus.de/rex5/redaxo/src/core/lib/packages/addons/manager.php(25): rex_package_manager->install(true)
#6 /kunden/322541_70190/alexplus.de/rex5/redaxo/src/core/lib/packages/api_package.php(34): rex_addon_manager->install()
#7 /kunden/322541_70190/alexplus.de/rex5/redaxo/src/core/lib/api_function.php(130): rex_api_package->execute()
#8 /kunden/322541_70190/alexplus.de/rex5/redaxo/src/core/backend.php(134): rex_api_function::handleCall()
#9 /kunden/322541_70190/alexplus.de/rex5/redaxo/src/core/boot.php(105): require('/kunden/322541_...')
#10 /kunden/322541_70190/alexplus.de/rex5/redaxo/index.php(9): require('/kunden/322541_...')
#11 {main}

activate safe mode`

**Comment by dergel** [comment]
hmm.. das kann ich nicht nachvollziehen.. Cache gelöscht ?

**Comment by alexplusde** [comment]
Das meinte @gharlan auch in einem anderen Issue dazu, bzw., dass man das Table Manager Plugin auch reinstallieren soll. https://github.com/yakamara/redaxo_yform/issues/110

Grundsätzlich: Sollte beim reinstallieren dann nicht vorher generell der Cache gelöscht werden, damit es nicht zu solchen Fehlern kommt? Oder passiert das automatisch, wenn das ganze später über den Installer geht? So eine Fehlermeldung verunsichert doch sehr...

**Comment by dergel** [comment]
ungeprüft.. das passiert automatisch. Du hast wahrscheinlich rein über github und tower oder ähnlichem aktualisiert und das ist ja nicht der normale weg..

**Comment by dergel** [comment]
lag es am cache ? .. wenn ja, dann gerne schliessen

**Comment by alexplusde** [comment]
Vermutlich dann, kann's ja jetzt nach dem Update erst mal nicht mehr nachvollziehen.
