### ISSUE TITLE
Vorschlag: $query->leftJoinRelation sollte IMMER leftJoin liefern

### ISSUE THREAD

**Issue by christophboecker** [yakamara/redaxo_yform#1082]
Bin etwas irritiert bzgl. rexyform_manager_query und Relationen:

- `$query->joinRelation ($feldname)` baut einen INNER-Join auf
- `$query->leftJoinRelation ($feldname)` baut einen LEFT-Join auf **oder auch nicht** (wenn be_manager_relation vom Typ 4 oder 5 ist)

Das mag harte Funktionalitätsgründe haben, die sich mir nicht erschließen. Oder eine Absicherung die nicht in jedem Context sinnvoll ist. Und man kann die Query ja auch überlisten, indem man einen letftJoin benutzt. 

Nur würde ich es als logischer empfingen, dass wenn ich einen LEFT-Join anfordere der auch geliefert wird. Und wenn das nicht funktioniert halt einen INNER-Join nehmen muss. Man baut ja ausdrücklich **kein** joinRelation, sondern leftJoinRelation. 

Da ich möglicherweise der Einzige sein könnte,der bei einem be_manager_relation vom Typ 5 LeftJoin will, frage ich einfach mal an:

Könntet ihr in Erwägung ziehen, ob man das klarer fassen könnte und immer LeftJoin liefert wenn gefordert?

(Ich kenne nun das Problem und kann mir helfen)

**Comment by gharlan** [comment]
Kann mich nicht erinnern, dass das Absicht war. Deswegen vermute ich im Moment ein Versehen.

Du kannst ja mal testen, ob es funktioniert, wenn du [hier](https://github.com/yakamara/redaxo_yform/blob/7a953ad308ff6016207c5a3aee1ed73eaab7c2ea/plugins/manager/lib/yform/manager/query.php#L191) es änderst in `joinType($type, ...` (siehe paar Zeilen weiter drunter).

**Comment by christophboecker** [comment]
Funktioniert.

**Comment by dergel** [comment]
bekomme ich einen PR ?

**Comment by christophboecker** [comment]
Je, gerne. Heute Abend.

**Comment by christophboecker** [comment]
PR ist fertig
