### ISSUE TITLE
Selectpicker Style

### ISSUE THREAD

**Issue by marcohanke** [yakamara/redaxo_yform#1085]
Wenn ich mit `{"class":"selectpicker","data-live-search":"true"}` aus einem be_relation (oder choice) einen Selectpicker mache müsste `.dropdown {display: block; width:100%}` gesetzt werden um das Layout nicht zu zerschießen.

**Comment by alxndr-w** [comment]
Ich glaube, Jan kann das Problem besser nachvollziehen, wenn du je einen Screenshot mit und ohne fix machst.

**Comment by marcohanke** [comment]
<img width="640" alt="Bildschirmfoto 2021-06-30 um 22 10 28" src="https://user-images.githubusercontent.com/2425981/124025263-844dc600-d9f0-11eb-810e-f13bd0b348fe.png">
<img width="456" alt="Bildschirmfoto 2021-06-30 um 22 10 21" src="https://user-images.githubusercontent.com/2425981/124025264-84e65c80-d9f0-11eb-97d3-dec8d759afb1.png">

**Comment by alxndr-w** [comment]
Es fehlt die Klasse `form-control`

**Comment by marcohanke** [comment]
Bitte Alex. 😕 Auch hier 5 Sekunden mehr investieren und direkt den PR erledigen. Deine Zeit ist wichtig. Die der anderen aber auch!

**Comment by alxndr-w** [comment]
![IMG_20210708_155839](https://user-images.githubusercontent.com/3855487/124934862-6b06d400-e005-11eb-8948-e3f7a383cae0.jpg)

Da hast du dir ja mit deinem von mir kopierten Kommentar selbst ein schönes Ei gelegt. 🤣

**Comment by marcohanke** [comment]
Wichtig ist dass du Spaß hast, da arbeiten wir alle Fieberhaft dran!

**Comment by alxndr-w** [comment]
Kann das hier nicht zu? @dergel - ist schließlich kein Fehler, einfach nur `{"class": "form-control selectpicker","data-live-search": "true"}` machen wie üblich.
