### ISSUE TITLE
YF4beta2: Fehlender Alias bei YOrm-Queries via EP YFORM_DATA_LIST_QUERY

### ISSUE THREAD

**Issue by christophboecker** [yakamara/redaxo_yform#1088]
Aufgefallen erst im Zusammenhang mit Queries, die via EP YFORM_DATA_LIST_QUERY die Listen-Query mit Joins erweitern und dadurch den Feldnamen 'id' doppelt haben. 'id' ist insofern besonders problematisch, da er ein gesetzter Feldname ist, auf dessen Existenz gebaut wird und der an mehreren Stellen systemseitig genutzt wird. 

Das hier ist eine Erinnerung, das Thema im Auge zu behalten. 

Es gibt 
- initiales Issue #1070
- PR zur Lösung des Issues #1083
- PR wegen eines weiteren fehlenden Alias #1087

**Comment by dergel** [comment]
ist nun erledigt, oder ? passt das so, gerne dann schliessen

**Comment by christophboecker** [comment]
Ich zitiere mal aus #1070:

> CB: Wäre also die Frage, macht wer auch immer ein eigenes Issue auf "Alias im Manager sicherstellen" oder soll dieses als Reminder offen bleiben. Mein Vorschlag ist, dieses hier zu schließen, denn mein Ursprungsproblem ist behoben. Ich möchte aber den von Thomas aufgeworfenen Punkt nicht unberücksichtigt wissen.

Antwort:

> JK: ich schliesse und gerne ein neues issue aufmachen

Das hier ist das Reminder-Issue. Dass ich zufällig noch ein Alias-Ding gefunden habe bedeutet ja nicht, dass es nicht noch mehr gibt. Die Entscheidung, das Issue zu schließen, sehe ich eher bei Dir (oder @tbaddade)
