### ISSUE TITLE
4.x Table Manager CSRF für Links

### ISSUE THREAD

**Issue by skerbis** [yakamara/redaxo_yform#1090]
Um Links direkt zum TableManager zu setzen ist es ab 4.x erforderlich CSRF-Token zu übergeben. 
Es wäre nützlich eine Methode / Funktion zu haben, die diesen Link-Parameter für die gewünschte Tabelle direkt erzeugt. 

Siehe QuickNavigation: 

https://github.com/FriendsOfREDAXO/quick_navigation/blob/17a2b592bf2d88db98f48f8bd9f64d6c8543debe/lib/QuickNavigation.php#L481-L482

https://github.com/FriendsOfREDAXO/quick_navigation/blob/17a2b592bf2d88db98f48f8bd9f64d6c8543debe/lib/QuickNavigation.php#L502

**Comment by alxndr-w** [comment]
Gibt es meines Wissens
Schau mal ab dieser Zeile https://github.com/yakamara/redaxo_yform/blob/2a6f6edb54b73fe7f6ae233c45519e1319e141b5/plugins/manager/lib/yform/manager.php

`$this->table->getCSRFKey()`

**Comment by skerbis** [comment]
Wie du an meinem Quellcode von QuickNavigation gesehen hast verwende ich es auch. Aber um den Token zu erhalten muss man dann noch 'rex_csrf_token::factory' ausführen um die Params zu erhalten. 
Dann erhält man ein Array und muss es auslesen.

**Comment by alxndr-w** [comment]
Hatte ich nicht gesehen, danke für den Hinweis. Du brauchst quasi einen Shortcut als Methode, die das abnimmt/übernimmt.

Ich gucke mal, aber verspreche nichts. Vlt. ist @dergel auch schneller.

**Comment by skerbis** [comment]
Würde es definitiv erleichtern. 
Siehe auch https://github.com/tbaddade/redaxo_watson/pull/63

**Comment by skerbis** [comment]
Selbst wenn es einen Shortcut gäbe, müssten die AddOns und Websites die kompatibel zur Vorversion bleiben sollen wie in QuickNavi oder meinem PR für Watson angepasst werden. 
@dergel im RELEASE muss unbedingt eine Warnung dazu her.

**Comment by dergel** [comment]
@skerbis Willst du das in der Doku mit aufnehmen? Das wäre super :)

**Comment by skerbis** [comment]
@dergel https://github.com/yakamara/redaxo_yform/pull/1163/commits/dd4f52bd14d3609496faeb988203607084b6b944
Doku folgt

**Comment by skerbis** [comment]
ich mach mal zu hier.

**Comment by alxndr-w** [comment]
@skerbis Doku https://github.com/yakamara/redaxo_yform/pull/1204

**Comment by skerbis** [comment]
@alxndr-w bereits auch hier: https://github.com/yakamara/redaxo_yform/pull/1201

**Comment by alxndr-w** [comment]
Habe ich gesehen, aber der Aufbau eines Edit-Links erfordert ja nochmal ein paar mehr Parameter. Ich fand das Beispiel zu allgemein und ich glaube, es funktioniert auch nicht so wie beschrieben, weil da ein Array rauskommt. Ich musste den key abfragen: `$token['_csrf_token'];` 

Deswegen habe ich ein eigenes verfassst, das einen kopierfertigen Link enthält einerseits und andererseits auch das Beispiel mit der Verlinkung eines Datensatzes vervollständigt. Ich glaube, das hattest du mal in irgendeinem Repo diskutiert.
