### ISSUE TITLE
Hausputz: Doppelter EP YFORM_MANAGER_DATA_PAGE - Absicht oder Versehen?

### ISSUE THREAD

**Issue by christophboecker** [yakamara/redaxo_yform#1093]
Ist schon lange in YForm, nicht erst seit 4.0. Aber wenn man schon einen BC hat, könnte man hier auch gleich aufräumen :-)

In der `rex_yform_manager.php` wird zwei mal der EP YFORM_MANAGER_DATA_PAGE aufgerufen:
https://github.com/yakamara/redaxo_yform/blob/2a6f6edb54b73fe7f6ae233c45519e1319e141b5/plugins/manager/lib/yform/manager.php#L55-L104
Will man den EP nutzen, wird die Callback-Aktion stets doppelt ausgeführt, es sei denn man baut seinen eigenen Erkennungsmechanismus ein um den zweiten vom ersten Aufruf zu unterscheiden. 

- War das jetzt ein Versehen, den Aufruf zwei mal zu haben? 
- Sollte der zweite Aufruf nicht besser einen eigenen Namen haben?
- Oder lässt man den zweiten einfach weg und verpasst dem unmittelbar danach folgenden EP YFORM_MANAGER_DATA_EDIT_FILTER zusätzlich $this als `param`?

**Comment by dergel** [comment]
Bin mir ziemlich sicher, dass es ein Versehen war. Dinge wie Tabelle oder Ähnliches zu ändern, nachdem man es genutzt hat ist meines Erachtens nicht sinnvoll. Danke für den Hinweis, habe es entfernt
