### ISSUE TITLE
YF4beta2: Frage zu Abfragekomplexität - so nötig oder Performance-Potential

### ISSUE THREAD

**Issue by christophboecker** [yakamara/redaxo_yform#1094]
Mir ist nicht klar, ob diese Code-Stelle so gemeint ist wie sie u.U. wirkt bzw. was wirklich erreicht werden soll.
https://github.com/yakamara/redaxo_yform/blob/2a6f6edb54b73fe7f6ae233c45519e1319e141b5/plugins/manager/lib/yform/manager.php#L155-L167

Ich verwende in der dem Formularaufruf vorhergehenden Liste eine komplexe Query mit Joins via EP YFORM_DATA_LIST_QUERY. Mit einem `dump($data_query);` zwischen Zeile 159 und 160 sehe ich, dass auch hier die komplette Abfrage inkl. aller Joins berücksichtigt wird.
<img width="691" alt="grafik" src="https://user-images.githubusercontent.com/10065904/124232868-814af680-db12-11eb-944d-0ae3c90b3056.png">

Ist das so gemeint oder geht es nur darum, die Existenz des Hauptdatensatzes zu prüfen? Je nach "where" kann ja auch "nicht gefunden" das Ergebnis sein, während es den Satz tatsächlich aber gibt. Sind die Joins, Sorts und Extra-Felder hier nötig oder Bremse?

**Comment by dergel** [comment]
> Ist das so gemeint oder geht es nur darum, die Existenz des Hauptdatensatzes zu prüfen?

Genau darum geht es und ja, es kann auch sein, dass man den Query so ergänzt, dass dieser nicht gefunden werden soll. (dann wurde er aber vorher auch nicht in der Liste angezeigt)

**Comment by christophboecker** [comment]
Na dann ....
