### ISSUE TITLE
Choice in Tabelle mit Leserechten zeigt alle Werte

### ISSUE THREAD

**Issue by marcohanke** [yakamara/redaxo_yform#1095]
Das neue "Nur Lesen" Recht ist Dufte. Leider werden bei Choice Feldern alle Werte angezeigt, nicht die ausgewählten. Das zerschießt mitunter die Formulare ziemlich
![Bildschirmfoto 2021-07-02 um 16 06 04](https://user-images.githubusercontent.com/2425981/124286623-719dd300-db4f-11eb-96d1-ed3101bed4fe.png)
![Bildschirmfoto 2021-07-02 um 16 05 21](https://user-images.githubusercontent.com/2425981/124286630-72366980-db4f-11eb-8ad8-3cdf85b5985e.png)

**Comment by alxndr-w** [comment]
Siehe #1057

**Comment by marcohanke** [comment]
Wäre es nicht möglich / schöner das Formular zu lassen wie es ist, und alle Felder auf readonly zu setzen?

**Comment by alxndr-w** [comment]
Readonly könnte man clientseitig im Browser ändern

**Comment by dergel** [comment]
@marcohanke kannst du mir das tableset schicken, dann kann ich das hier nachbauen und prüfen.

**Comment by dergel** [comment]
gerne prüfen. Sollte nun passen. Wenn nicht, gerne issue wieder öffnen

**Comment by marcohanke** [comment]
Gerade getestet. Schick, danke dir!
