### ISSUE TITLE
Tabellendarstellung zu breit auf kleinen Screens

### ISSUE THREAD

**Issue by skerbis** [yakamara/redaxo_yform#1096]
<img width="1803" alt="Bildschirmfoto 2021-07-03 um 13 57 57" src="https://user-images.githubusercontent.com/791247/124353587-bc7b2180-dc07-11eb-91cb-f2a15ad9a2e6.png">

Die Suche und die Funktionen nehmen sehr viel Platz ein. Gerade bei kleineren Bildschirmen (aber auch selbst bei einem 27") muss man häufig nach rechts scrollen, möchte man die Funktionen erreichen (hier mal mit yform_usability Funktionen) 
Evtl. bietet es sich an, die Columns zu scrollen und die Funktionen zu fixieren. 
Auch die Suche benötigt viel Platz, vielleicht bietet sich an diese nur bei Bedarf einzublenden. Die Suche wird eher selten verwendet und müsste nicht so prominent sein. 

Vielleicht wie hier: 
https://csslayout.io/patterns/sticky-table-column/

**Comment by christophboecker** [comment]
Oder so: https://friendsofredaxo.github.io/tricks/addons/yform/search_toggle

**Comment by dergel** [comment]
Bei den Funktionen stimme ich zu. Vielleicht doch nur Icons? Habe es mal ausprobiert und war ok für mich. Suche hat man oder eben nicht, da finde ich es ok, wenn die immer da ist. 

Ich habe Vorbereitungen, dann man eigene "Layouts" anmelden und verwenden kann. Im Moment kann man nur pauschal über alle Tabellen das Layout ändern. Stichwort: fragment.

**Comment by skerbis** [comment]
Ja nur icons wäre ok. Und da im REX 15.13 jetzt die Tooltips genutzt werden können könnte man diese dort auch aktivieren.

**Comment by tbaddade** [comment]
Nur Icons find ich nicht gut, zumindest sollte ein Tooltip mit dem jetzigen Wort erscheinen.

**Comment by dergel** [comment]
dann Icons mit Tooltip :)

**Comment by tbaddade** [comment]
Eine weitere Alternative wäre noch ein Dropdown mit den 4 Aktionen darin.

Bsp.:
<img width="309" alt="Bildschirmfoto 2021-12-04 um 11 22 40" src="https://user-images.githubusercontent.com/338267/144706036-411d7e0a-863e-487b-a150-b34bb214913c.png">

**Comment by dergel** [comment]
das fände ich gut, weil man dann flexibel erweitern kann und ich wollte auch noch actions später mit unterbringen. Kannst du mir das bauen? oder mir das Markup liefern?

**Comment by christophboecker** [comment]
Ja, das wäre eine gute Lösung. Auch die Erweiterbarkeit! Per EP oder so?

**Comment by tbaddade** [comment]
> oder mir das Markup liefern?

```html
<div class="dropdown">
    <button class="btn btn-default btn-xs dropdown-toggle" type="button" data-toggle="dropdown">
        Aktion
        <span class="caret"></span>
    </button>
    <ul class="dropdown-menu dropdown-menu-right">
        <li><a href="#" class="small"><i class="rex-icon rex-icon-edit"></i> editieren</a></li>
        <li><a href="#" class="small"><i class="rex-icon rex-icon-delete"></i> löschen</a></li>
    </ul>
</div>
```

**Comment by skerbis** [comment]
@tbaddade super das ist eine gute Lösung

**Comment by dergel** [comment]
Heftige Änderung. Aber vielleicht muss man sich nur daran gewöhnen. Die Tabellen sind auf jeden Fall aufgeräumter. Gerne gegentesten

**Comment by marcohanke** [comment]
Getestet, funktioniert. Willst du das auch in der "großen" Desktop Ansicht? Oder kannst du es vielleicht irgendwie nach Anzahl der Spalten einblenden? "Nachteil" an der Geschichte ist, dass es jetzt einen Click mehr braucht. Was irgendwie unnötig ist wenn Platz da ist. Aber grundsätzlich finde ich es super weil mich das gescrolle auch oft nervt.

**Comment by dergel** [comment]
Für mich ist das Issue erledigt. Auch wenn es eine sehr auffällige Änderungen finde ich diese ziemlich hilfreich. Sofern nicht noch zich Einwände kommen bleibt es dann auch so :)

**Comment by skerbis** [comment]
yeeepee 🎉🥳
