### ISSUE TITLE
Warning | Undefined array key "relation_table"

### ISSUE THREAD

**Issue by skerbis** [yakamara/redaxo_yform#1098]
06.07.2021 22:18:01 | Warning | Undefined array key "relation_table" | redaxo/src/addons/yform/plugins/manager/lib/yform/manager/field.php | 121

Ich komme nicht dahinter was das sein kann, ich habe 1 Inline Relation im Einsatz, da ist keine Relationstabelle angegeben. 
Unter PHP 7.3 tritt die Warnung nicht auf. 

<details>
<summary>System report (REDAXO 5.12.0, PHP 8.0.7, MariaDB 10.2.39)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.12.0     |

| PHP           |            |
| ------------: | :--------- |
|       Version | 8.0.7      |
|       OPcache | yes        |
|        Xdebug | no         |

| Database      |                 |
| ------------: | :-------------- |
|       Version | MariaDB 10.2.39 |
| Character set | utf8mb4         |

| Server        |            |
| ------------: | :--------- |
|            OS | Linux      |
|          SAPI | fpm-fcgi   |
|     Webserver | Apache     |

| Request       |               |
| ------------: | :------------ |
|       Browser | Safari/14.1.1 |
|      Protocol | HTTP/1.0      |
|         HTTPS | yes           |

| Packages                    |             |
| --------------------------: | :---------- |
|                     adminer | 1.9.0       |
|               animatedlogin | 0.0.1       |
|                      backup | 2.7.0       |
|                    be_style | 2.12.0      |
|         be_style/customizer | 2.12.0      |
|             be_style/redaxo | 2.12.0      |
|                     bloecks | 3.0.2       |
|            bloecks/cutncopy | 3.0.2       |
|           bloecks/dragndrop | 3.0.2       |
|                        cke5 | 4.2.2       |
|             consent_manager | 3.0.0       |
|                     cronjob | 2.8.0       |
|               fa-iconpicker | 0.3 beta    |
|                      ffmpeg | 1.0.0       |
|                  focuspoint | 3.0.2       |
|                  hyphenator | 1.1.7       |
|                     install | 2.9.0       |
|                klxm_website | 2.0.0       |
|                 maintenance | 2.6.2       |
|                      matomo | 1.2.1       |
|                      mblock | 3.2.0       |
|               media_manager | 2.11.0      |
|                media_srcset | 2.0.5-dev   |
|                   mediapool | 2.10.0      |
|                    metainfo | 2.8.0       |
|                       mform | 6.0.9       |
|                  mform/docs | 1.1         |
|                     minibar | 2.2.3       |
|            navigation_array | 1.1.1       |
|                    osmproxy | 1.5.0       |
|                   phpmailer | 2.10.2      |
|                        plyr | 3.9.0       |
|                     project | dev         |
|            quick_navigation | 5.1.1       |
|                   search_it | 6.7.4       |
|     search_it/documentation | 6.7.3       |
|             search_it/stats | 6.7.3       |
|                  seocheckup | 1.4.6       |
|                       sprog | 1.2.0       |
|                   structure | 2.12.0      |
|           structure/content | 2.12.0      |
|           structure/history | 2.12.0      |
|                    uploader | 2.2.2       |
|                         url | 2.0.0-dev   |
|                       users | 2.8.0       |
|                      watson | 2.2.0       |
|               xoutputfilter | 3.0.0-beta1 |
| xoutputfilter/documentation | 1.0.0       |
|      xoutputfilter/frontend | 3.0.0       |
|                       yform | 4.0.0-beta2 |
|                 yform/email | 4.0.0-beta2 |
|               yform/manager | 4.0.0-beta2 |
|                 yform/tools | 4.0.0-beta2 |
|               yform_geo_osm | 1.2.3       |
|                    yrewrite | 2.7         |
|    yrewrite_domain_settings | 2.0.2       |
|                 zip_install | 1.1         |

</details>

**Comment by alxndr-w** [comment]
#1076
