### ISSUE TITLE
Ausgabe der Fehlermeldungen

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#11]
1/
via Param bestimmen wo die Fehlermeldung erscheinen. Hintergrund: Manchmal schreibt man vor dem Formular noch html, damit es bei der Dankesmeldung nicht mit ausgegeben wird. Die Fehler sollten aber eigentlich zw. html und dem eigentlichen Formular dann erscheinen.

2/
Reihenfolge der einzelnen Meldungen. Aktuell erscheinen die einzelnen Meldungen alphabetisch nach der validate Klasse und dann wie die Values notiert wurden.
Bsp.:

```
text|surname|Nachname|
validate|empty|surname|empty Nachname
validate|preg_match|surname|/regex/|regex Nachname

text|firstname|Vorname|
validate|empty|firstname|empty Vorname
validate|preg_match|firstname|/regex/|regex Vorname
```

Ausgabe:

```
empty Nachname
empty Vorname
regex Nachname
regex Vorname
```

Besser wäre die Ausgabe wie die Validierungen selbst notiert wurden

```
empty Nachname
regex Nachname
empty Vorname
regex Vorname
```

**Comment by alexplusde** [comment]
@tbaddade wenn ich das richtig gesehen habe, löst du das aktuell mit einem php-value, das die Fehlermeldungen zu oberst ausgibt, richtig? Hast du mir den Code nochmal?

**Comment by tbaddade** [comment]
> Hast du mir den Code nochmal?

https://github.com/yakamara/redaxo_ycom/issues/320

**Comment by dergel** [comment]
hier gehts weiter https://github.com/yakamara/redaxo_yform/issues/1380
