### ISSUE TITLE
Table Manager: (GH-Version) Checkbox "Massenlöschung" verhindert anlegen der Tabelle

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#110]
![image](https://cloud.githubusercontent.com/assets/3855487/16758569/a3e070e6-4812-11e6-85a5-fa39cef2b800.png)

(Aber nur bei Reinstall, sauberes de- und installieren hilft. Problem: Dazu muss man erst eine Handvoll anderer Addons deinstallieren, bspw. demo_base, ycom, yrewrite.)

**Comment by gharlan** [comment]
Hattest du das Manager-Plugin reinstalliert, oder nur das yform selbst?

**Comment by alexplusde** [comment]
Nur YForm selbst. Heißt das, dass man bei einem Update immer auch die Plugins mit reinstallieren muss? (Und wo steht sowas? :D)

**Comment by gharlan** [comment]
Beim manuellen Update ja, beim Update über den Installer muss man gar nicht reinstallieren.

**Comment by gharlan** [comment]
Man könnte überlegen, in der install.php vom Addon zu schauen, ob das Manager-Plugin installiert ist, und wenn ja, dieses auch automatisch reinstallieren.

**Comment by alexplusde** [comment]
Also wenn das über den Installer reibungslos geht, dann finde ich, müsste man da auch nichts weiter ändern als den Abschnitt in der GitHub-Readme. Dort könnte man darauf hinweisen, dass eine Reinstallation der Plugins und des Hauptaddons notwendig ist.
