### ISSUE TITLE
3.4.2: PHP8 entpricht nicht der geforderten Versionsbedingung ^7.0

### ISSUE THREAD

**Issue by omphteliba** [yakamara/redaxo_yform#1100]
Ich wollte eben auf einem System mit PHP 8.0.8 yform auf 3.4.2 updaten und bekam folgende Fehlermeldung:

AddOn yform konnte aus folgendem Grund nicht aktualisiert werden:
Die PHP-Version (8.0.8) entspricht nicht der geforderten Versionsbedingung ^7.0!

**Comment by TobiasKrais** [comment]
Ist in der aktuellen Git Version schon behoben. Issue kann geschlossen werden.

**Comment by omphteliba** [comment]
> Ist in der aktuellen Git Version schon behoben. Issue kann geschlossen werden.

Nicht wirklich: ich will ja nicht die Version 4 installieren, sondern die 3.4.2 Und da ist das noch nicht geändert.

**Comment by alxndr-w** [comment]
@omphteliba soweit ich mitbekommen habe, ist auch erst die Version 4 mit PHP 8 kompatibel.

**Comment by TobiasKrais** [comment]
Bei mir funktioniert die 3.4.2 bisher ohne Probleme mit PHP 8

**Comment by alxndr-w** [comment]
https://github.com/yakamara/redaxo_yform/issues/1098
