### ISSUE TITLE
YForm wird fälschlich im Backend Menü angezeigt

### ISSUE THREAD

**Issue by TobiasKrais** [yakamara/redaxo_yform#1102]
Der Benutzer hat keine Rechte für YForm und kann keine Tabellen editieren. Trotzdem hat er den Menüpunkt YForm eingeblendet:
![Bildschirmfoto von 2021-07-08 09-23-08](https://user-images.githubusercontent.com/4131072/124902680-73e6ae00-dfe3-11eb-906a-50f1de745e25.png)

**Comment by dergel** [comment]
Ist mittlerweile korrigiert.

**Comment by TobiasKrais** [comment]
Bitte wieder öffnen. Ist leider nach wie vor in Version 4.0.2 vorhanden. Hier die Systemconfig:
<details>
<summary>System report (REDAXO 5.13.3, PHP 8.0.16, MariaDB 10.5.15)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.13.3     |


| PHP           |            |
| ------------: | :--------- |
|       Version | 8.0.16     |
|       OPcache | no         |
|        Xdebug | no         |


| Database      |                 |
| ------------: | :-------------- |
|       Version | MariaDB 10.5.15 |
| Character set | utf8            |


| Server        |            |
| ------------: | :--------- |
|            OS | Linux      |
|          SAPI | fpm-fcgi   |
|     Webserver | Apache     |


| Request       |              |
| ------------: | :----------- |
|       Browser | Firefox/99.0 |
|      Protocol | HTTP/2.0     |
|         HTTPS | yes          |


| Packages                |             |
| ----------------------: | :---------- |
|                  backup | 2.8.1       |
|             be_branding | 1.7         |
|                be_style | 3.0.2       |
|     be_style/customizer | 3.0.2       |
|         be_style/redaxo | 3.0.2       |
|          cookie_consent | 3.0.0-beta3 |
|                 cronjob | 2.8.2       |
|             d2u_courses | 3.2.3       |
|  d2u_courses/kufer_sync | 3.2.3       |
|   d2u_courses/locations | 3.2.3       |
|              d2u_helper | 1.9.1       |
|                d2u_jobs | 1.2.2       |
|             d2u_linkbox | 1.2.5       |
|                d2u_news | 1.1.4       |
|         emailobfuscator | 3.0.0       |
|                 install | 2.9.3       |
|           media_manager | 2.12.2      |
|               mediapool | 2.11.3      |
|                metainfo | 2.8.5       |
|         multinewsletter | 3.2.8       |
|                osmproxy | 1.6.0       |
|               phpmailer | 2.11.2      |
|                    plyr | 3.15.3      |
|                 project | dev         |
|               search_it | 6.9.0       |
|  search_it/autocomplete | 6.9.0       |
| search_it/documentation | 6.9.0       |
|     search_it/plaintext | 6.9.0       |
|         search_it/stats | 6.9.0       |
|                   sprog | 1.3.0       |
|              statistics | 2.2.0       |
|               structure | 2.13.3      |
|       structure/content | 2.13.3      |
|                tinymce5 | 1.2.11      |
|                uploader | 2.3.0       |
|                     url | 2.0.1       |
|                   users | 2.8.2       |
|                    ycom | 4.0.7       |
|               ycom/auth | 4.0.7       |
|              ycom/group | 4.0.7       |
|         ycom/media_auth | 4.0.7       |
|                   yform | 4.0.2       |
|              yform/docs | 3.3.1       |
|             yform/email | 4.0.2       |
|           yform/manager | 4.0.2       |
|   yform_spam_protection | 1.2.1       |
|                yrewrite | 2.8.3       |

</details>
