### ISSUE TITLE
3.5.0-beta: Integrity constraint violation: 1048 Column --- cannot be nullError

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/redaxo_yform#1104]
* Datensätze,
* die per YOrm erstellt werden
* und dabei be_media-Felder nicht explizit mit `setValue()` gesetzt werden

können nicht gespeichert werden, ohne dass NULL am Feld der Datenbank erlaubt ist.

**Comment by dergel** [comment]
Sollte nun behoben sein + wenn media nicht vorhanden ist, wird leer geschrieben. Echte Überprüfung muss dann über Validierungen getätigt werden
