### ISSUE TITLE
Sprog Label bei Submit Button killt den Value beim Absenden

### ISSUE THREAD

**Issue by godsdog** [yakamara/redaxo_yform#1107]
Wenn ich folgendes nutze, wird der Submit Value des Buttons nicht gesetzt:

`$yform->setValueField('submit', array("pdfcreate","{{antrag_button_1}}","no_db"));`
So geht es:
`$yform->setValueField('submit', array("pdfcreate",sprogcard('antrag_button_1', REX_CLANG_ID),"no_db"));`

Ich nutze einen eigene Action, welche wie folgt checkt, welcher Submit Button gedrückt worden ist:
```
if($this->params['value_pool']['email']['pdfcreate'] != "") {
// ... Erstelle PDF usw...
}
```

**Comment by dergel** [comment]
das lässt sich leider nicht ändern, weil SPROG die Ersetzung im oberen Fall erst bei der Seitenausgabe erstellt und YForm davon nicht weiss und von einem anderen Submitlabel ausgeht. Wenn du dazu  kommst, gerne in der Doku ergänzen.
