### ISSUE TITLE
be_manager_relation: "multiple" i.V.m. "integer" nicht sinnvoll. Kann man das abfangen?

### ISSUE THREAD

**Issue by christophboecker** [yakamara/redaxo_yform#1108]
Mit einem Feld vom Typ `be_manager_relation` wunderte ich mich, warum plötzlich Inhalte verschwunden waren. Es handelt sich um ein Mehrfach-Auswahlfeld mit Popup. Speichert man das Formular mit "Übertragen", also Speichern und neu Anzeigen, sieht alles gut aus. Alle selektierten Elemente sind da, was in trügerischer Sicherheit wiegt. Wird der Satz nach "Speichern" neu angezeigt sieht man das Problem: nur das erste selektierte Element wurde gespeichert. Das Rätsel löst sich ganz einfach. Das Feldtyp war auf `int` eingestellt und nicht auf eine Textfeld-Variante; da kann er nur ein Element speichern. 

Nun mein Ansinnen: kann man irgendwie - evtl. über die geheimnisvollen Einstellungen in `public function getDefinitions()` - abfangen, daß Multiple-Varianten mit dem DB-Typ `int` versehen werden?

**Comment by dergel** [comment]
Da wir so was nicht haben und auch nicht aufbauen, ist es nun wenigstens in der Doku. Danke für den Hinweis.

**Comment by christophboecker** [comment]
Muss der Entwickler halt aufpassen.
