### ISSUE TITLE
Argument 1 passed to rex_yform_email_template::makeSingleLine() must be of the type string

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/redaxo_yform#1111]
Formular-Code

```
                        $dataset = rex_yform_manager_dataset::create('rex_xxx_apply');
                        $yform = $dataset->getForm();
                        $yform->setObjectparams('form_action', rex_getUrl(rex_article::getCurrentId())."?action=sent#apply");
                        $yform->setActionField('showtext', array('','Gespeichert'));
                        $yform->setActionField('tpl2email', array('xxx_apply','mail@example.org'));
                        $yform->setActionField('tpl2email', array('xxx_apply_confirm','email'));

                        echo $dataset->executeForm($yform);
```

Stack

**TypeError:** Argument 1 passed to rex_yform_email_template::makeSingleLine() must be of the type string, null given, called in /home/users/xxx/www/xxx.de/www/redaxo/src/addons/yform/plugins/email/lib/yform_email_template.php on line 57
**File:** redaxo/src/addons/yform/plugins/email/lib/yform_email_template.php
**Line:** 79

<details>
<summary>Stacktrace</summary>

| Function                                     | File                                                                     | Line     |
| -------------------------------------------- | ------------------------------------------------------------------------ | -------- |
| rex_yform_email_template::makeSingleLine     | redaxo/src/addons/yform/plugins/email/lib/yform_email_template.php       | 57       |
| rex_yform_email_template::replaceVars        | redaxo/src/addons/yform/plugins/email/lib/yform_action_tpl2email.php     | 44       |
| rex_yform_action_tpl2email->executeAction    | redaxo/src/addons/yform/lib/yform.php                                    | 461      |
| rex_yform->executeActions                    | redaxo/src/addons/yform/plugins/manager/lib/yform/manager/dataset.php    | 588      |
| rex_yform_manager_dataset->executeForm       | theme/private/fragments/simple/modul.xxx.apply.php                    | 33       |
| require                                      | redaxo/src/core/lib/fragment.php                                         | 121      |
| rex_fragment->{closure}                      | redaxo/src/core/lib/util/timer.php                                       | 57       |
| rex_timer::measure                           | redaxo/src/core/lib/fragment.php                                         | 126      |
| rex_fragment->parse                          | redaxo/src/addons/across/lib/ax_template.php                             | 135      |
| ax_template::getFragment                     | redaxo/src/addons/across/lib/ax_template.php                             | 143      |
| ax_template::showFragment                    | rex:///module/101/output                                                 | 25       |
| require                                      | redaxo/cache/addons/structure/1.1.content                                | 172      |
| require                                      | redaxo/src/addons/structure/plugins/content/lib/article_content.php      | 99       |
| rex_article_content->getArticle              | rex:///template/160                                                      | 3        |
| require                                      | redaxo/src/addons/structure/plugins/content/lib/article_content_base.php | 405      |
| rex_article_content_base->{closure}          | redaxo/src/core/lib/util/timer.php                                       | 57       |
| rex_timer::measure                           | redaxo/src/addons/structure/plugins/content/lib/article_content_base.php | 406      |
| rex_article_content_base->getArticleTemplate | redaxo/src/addons/structure/plugins/content/boot.php                     | 56       |
| rex_package::{closure}                       | redaxo/src/core/lib/extension.php                                        | 51       |
| rex_extension::{closure}                     | redaxo/src/core/lib/util/timer.php                                       | 57       |
| rex_timer::measure                           | redaxo/src/core/lib/extension.php                                        | 62       |
| rex_extension::registerPoint                 | redaxo/src/core/frontend.php                                             | 26       |
| require                                      | redaxo/src/core/boot.php                                                 | 141      |
| require                                      | index.php                                                                | 9        |

</details>
<details>
<summary>System report (REDAXO 5.12.1, PHP 7.4.21, MariaDB 10.3.31)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.12.1     |

| PHP           |            |
| ------------: | :--------- |
|       Version | 7.4.21     |
|       OPcache | yes        |
|        Xdebug | no         |

| Database      |                 |
| ------------: | :-------------- |
|       Version | MariaDB 10.3.31 |
| Character set | utf8mb4         |

| Server        |            |
| ------------: | :--------- |
|            OS | Linux      |
|          SAPI | fpm-fcgi   |
|     Webserver | Apache     |

| Request       |                      |
| ------------: | :------------------- |
|       Browser | Chrome/92.0.4515.159 |
|      Protocol | HTTP/2.0             |
|         HTTPS | yes                  |

| Packages                |             |
| ----------------------: | :---------- |
|            2factor_auth | 1.0.0       |
|            accessdenied | 1.0.6       |
|                  across | 4.0.0-dev1  |
|                 adminer | 1.9.1       |
|                  backup | 2.7.1       |
|             be_password | 2.0.0       |
|                be_style | 2.12.1      |
|     be_style/customizer | 2.12.0      |
|         be_style/redaxo | 2.12.1      |
|         be_style_fluent | 3.0.0       |
|                 bloecks | 3.0.2       |
|        bloecks/cutncopy | 3.0.2       |
|                    cke5 | 4.2.2       |
|         consent_manager | 3.0.0       |
|                 cronjob | 2.8.0       |
|  cronjob/article_status | 2.8.0       |
| cronjob/optimize_tables | 2.7.1       |
|                   debug | 1.1.1       |
|               developer | 3.9.0       |
|                  events | 2.0.0-beta2 |
|                 install | 2.9.1       |
|             maintenance | 2.6.3       |
|                  mblock | 3.2.0       |
|           media_manager | 2.11.1      |
|               mediapool | 2.10.1      |
|                metainfo | 2.8.1       |
|                   mform | 6.0.9       |
|              mform/docs | 1.1         |
|      nv_categorymanager | 1.1.0       |
|               phpmailer | 2.10.2      |
|                 project | dev         |
|                   qanda | 2.0.1       |
|        quick_navigation | 5.1.1       |
|               search_it | 6.7.3       |
|  search_it/autocomplete | 6.7.3       |
| search_it/documentation | 6.7.3       |
|     search_it/plaintext | 6.7.3       |
|         search_it/stats | 6.7.3       |
|                   sprog | 1.2.0       |
|               structure | 2.12.1      |
|       structure/content | 2.12.0      |
|                   theme | 1.3.3       |
|                uploader | 2.2.2       |
|                     url | 2.0.0-dev   |
|                   users | 2.8.0       |
|                  watson | 2.2.0       |
|                    ycom | 4.0.3       |
|               ycom/auth | 4.0.3       |
|               ycom/docs | 4.0.3       |
|              ycom/group | 4.0.3       |
|                   yform | 4.0.0-beta2 |
|             yform/email | 4.0.0-beta2 |
|           yform/manager | 4.0.0-beta2 |
|              yform/rest | 4.0.0-beta2 |
|             yform/tools | 4.0.0-beta2 |
|           yform_geo_osm | 1.2.3       |
|   yform_spam_protection | 1.1.0       |
|         yform_usability | 1.4         |
|                yrewrite | 2.7         |
|             zip_install | 1.1         |

</details>

**Comment by alxndr-w** [comment]
Das Entfernen der als deprecated markierten Zeilen 56/57 hat das Problem im Übrigen für mich gelöst.

`
                /** @deprecated will be removed. use REX_YFORM_DATA[field="name"] */
                $template[$k] = str_replace('+++' . $er_key . '+++', self::makeSingleLine($er_value), $template[$k]);             
`

**Comment by dergel** [comment]
da diese deprecated sind und 4.0 eine neue Major Versioon ist habe ich die entfernt.
