### ISSUE TITLE
Start-Feeling überarbeiten

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/redaxo_yform#1112]
Die Übersichtsseite in YForm empfinde ich als hinfällig, könnte hier nicht der Table Manager zuerst starten und das Modul installieren in einen separaten Reiter Einstellugen/Setup wandern?

![image](https://user-images.githubusercontent.com/3855487/130769765-6308312c-56fe-4da2-854a-522705de6d9e.png)

In gefühlt allen Fällen will ich zu Beginn direkt in den Table Manager. Die Erläuterungen zu Templates und Modulen findet man ja in der Doku bereits.

**Comment by christophboecker** [comment]
Das wär mal ne Idee!

**Comment by tbaddade** [comment]
Die Übersicht der Typen würde ich belassen. Diese gibt eine schnelle Übersicht was alles möglich ist und wie man etwas notieren muss.

**Comment by alxndr-w** [comment]
@tbaddade wie oft benutzt du die Übersichtsseite?

**Comment by tbaddade** [comment]
>  wie oft benutzt du die Übersichtsseite?

Mir geht es nicht um die Seite selbst sondern dass man schnell diese Übersicht der Typen einsehen kann.

**Comment by alxndr-w** [comment]
@tbaddade ok verstehe.

**Comment by dergel** [comment]
Im Prinzip ist die Übersichtsseite nur ein Setup für den Formbuilder. Dementsprechend ist das nun umbenannt und als Startseite den Manager - was ich auch besser für die Nutzung empfinde ( im Moment ;) )
