### ISSUE TITLE
input:date vs Anzeigeformat

### ISSUE THREAD

**Issue by skerbis** [yakamara/redaxo_yform#1113]
Bei input:date sollte das Anzeigeformat immer YYYY-MM-DD sein. (getestet)  
Bzw. sollte die Auswahl dazu deaktiviert werden. 

Andernfalls kommt es zu Problemen bei der Bearbeitung. 
Stellt man z.B.  DD.MM.YYYY ein, wird im Tablemanager bei erneutem Aufruf as aktuelle Datum anstelle des gespeicherten gezeigt. 
Bei YYYY-MM-DD ist alles ok und auch die Darstellung erfolgt nach deutscher Schreibweise (Safari) 

Die Darstellung DD.MM.YYYY sollte sich dann wohl in diesem Fall nur auf die "Listendarstellung" im Tablemanager auswirken. 

Zitat aus Slack:
> Nun muss ich aber feststellen, dass die Einträge zwar richtig in der Datenbank landen. Wenn ich aber dann den Termineintrag ein zweites (oder weiteres) Mal bearbeite, wird das aktuelle Datum (bzw. in Firefox „YYY-MM-DD“) angezeigt. Wenn ich dann auf „Speichern“ oder „Übernehmen“ gehe, wird, oh

**Comment by alxndr-w** [comment]
Könnte mit #976 zusammenhängen.

**Comment by dergel** [comment]
Habe hiier einiges angepasst. Gerne testen. Ich schliesse das hier. Bei Fehlern bitte meldne.

Es werden keinen anderen Formate mehr als die Standardformate vewendet. Majorversion erlaubt das meines Erachtens.

**Comment by ynamite** [comment]
Ich fände es toll, wenn das Eingabe-Select/-Input das gewählte Ausgabe-/Darstellungs-/Anzeige-Format respektieren würde. Finde es für Redakteure in unserem Sprachraum sonst verwirrend.

Ich meine das hätte mal funktioniert, aber offenbar wurde das hiermit rückgängig gemacht. Schade. Gibt's da keine Alternative?

**Comment by dergel** [comment]
Lang ists her, sorry, jetzt erst gelesen.

Das mit dem Datumsformat lasse ich so. Aber es gibt sicherlich JS Bibliotheken, die MySQL Datetime verschicken und in der Eingabe hingegen was Eigenes erlauben.
