### ISSUE TITLE
YForm4-beta: Wenn Schema-Definition überschreiben aus ist, wird kein neues Feld erstellt

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/redaxo_yform#1116]
Beim Erstellen eines Feldes in einer YForm-Tabelle mit abgeschalteter Schema-Definition-überschreiben-Option wird die Felddefinition erstellt, jedoch nicht das zugehörige Feld in der Datenbank.

**Comment by dergel** [comment]
Danke für den Hinweis, kannst du das Gegenprüfen? Bei meinen Tests war alles gut

**Comment by alxndr-w** [comment]
Mache ich und melde mich, wenn's nicht so ist.
