### ISSUE TITLE
package.yml enthält noch alte Versionsnummer

### ISSUE THREAD

**Issue by marcohanke** [yakamara/redaxo_yform#1119]
Ich bekomme über den Installer ein Update auf eine ältere Version weil hier die Versionsnummer noch nicht passt.

**Comment by dergel** [comment]
mittlerweile sollte das alles ok sein. Kann den Stand von damals nicht reproduzieren

**Comment by marcohanke** [comment]
Gerade aus dem Installer die 4.0.0-dev installiert und der Installer bietet mir die 4.0.0-beta3 und beta 2 an.
