### ISSUE TITLE
Notice: undefined index

### ISSUE THREAD

**Issue by marcohanke** [yakamara/redaxo_yform#1121]
Mit der aktuellen Version aus dem Installer bekomme ich im Backend folgenden Notice:
Notice: Undefined index: relation_table in redaxo/src/addons/yform/plugins/manager/lib/yform/manager/field.php on line 121

**Comment by marcohanke** [comment]
Das gleiche gillt für die Version aus Github von heute.

**Comment by dergel** [comment]
das sollte nun mit dem PR passen
