### ISSUE TITLE
 Probleme mit rex_yform_manager_table_api::importTablesets(); #4764 

### ISSUE THREAD

**Issue by marcohanke** [yakamara/redaxo_yform#1127]
Ich habe eine Installation mit einigen yform Tabellen die ich auf utf8_bin stellen Musste (Es gibt CaseSensitive Duplikate in der Tabelle).
Will ich ein AddOn installieren dass rex_yform_manager_table_api::importTablesets(); nutzt, bekomme ich im Installer folgenden Fehler:

SQL error: Error while executing statement "ALTER TABLE `meine_yform_tabelle_die_nichts_mit_dem_addon_zu_tun_hat` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;": SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'Mein_Duplicate_Entry' for key 'activity'```
Getestet mit ycom und yrewrite_domain_settings.
Eigentlich sollte dem Addon doch eine "fremde" Tabelle egal sein oder?

**Comment by marcohanke** [comment]
Rüdi hat sich das mal angesehen und durch die Anpassungen an den PHP Einstellung etwas Besserung verschafft.
Trotzdem braucht ein Structure Aufruf mit yform immernoch 500ms und ohne yfrom nur 50ms.
Zitat Rüdi. Das müsste man mal mit Gregor zusammen besprechen, grundsätzlich kann es noch an PHP als fpm liegen, das ist das in unserem Setup, was unterschiedlich zu anderen Umgebungen ist, wieso das aber dann nur als Admin auftritt, ist auch wieder strange. Es ist definitiv ein Bug vom yform.

**Comment by marcohanke** [comment]
Nach ein paar Tests bin ich zu folgendem Ergebnis gekommen. Immer wenn ein AddOn im Installationsprozess rex_yform_manager_table_api nutzt, werden irgendwie alle yform Tabellen verarbeitet. Im Konkreten Fall habe ich yform Tabellen die auf case sensitive stehen müssen. Dadurch kommt der Fehler. Ich hab sie jetzt aus yform rausgeworfen, damit kann ich wieder installieren, mich würde trotzdemn interessieren warum alle yform Tabellen beackert werden und ob das so gewollt ist.

**Comment by dergel** [comment]
Es sind 2 Aspekte.

* YForm besteht bei tabellen und Feldern auf Kleinschreibung - das müsste man aufbohren
* Bei Updates von Feldern, wird der komplette Cache gelöscht, was dazu führt, dass es lange dauert.

Beides wichtige Themen - aber erst in 4.1

**Comment by dergel** [comment]
das issue geht hier weiter https://github.com/yakamara/redaxo_yform/issues/1286

**Comment by dergel** [comment]
und hier https://github.com/yakamara/redaxo_yform/issues/1383
