### ISSUE TITLE
YForm 4: Globale Styles vermeiden

### ISSUE THREAD

**Issue by schuer** [yakamara/redaxo_yform#1132]
In `assets/yform-docs.css` werden Styles global ausgebracht und überschreiben damit die Core-Styles für Dokumentation. Hier sollte besser der Namespace `#rex-page-yform-docs` verwendet werden, der oben am `<body>` hängt.

Womöglich könnten die Styles auch komplett entfernt werden, das spart zusätzlichen Anpassungsaufwand.

**Comment by tbaddade** [comment]
@dergel Kann das Issue wegen diesem Commit 64af187603b74168219cd4a0ba4553d7bc77f3c1 nicht geschlossen werden?
