### ISSUE TITLE
Weiterleitungen in yrewrite funktionieren nicht

### ISSUE THREAD

**Issue by olien** [yakamara/redaxo_yform#1133]
![image](https://user-images.githubusercontent.com/330516/136745847-6855b93a-b67e-4cfa-beaf-474b1c207454.png)

**Comment by alxndr-w** [comment]
close, das wurde im YRewrite upstream schon gelöst.

**Comment by alxndr-w** [comment]
https://github.com/yakamara/redaxo_yrewrite/pulls 

Sorry, wurde immer noch nicht übernommen. Ärgerlich. Das muss doch nicht sein.

**Comment by alxndr-w** [comment]
Die PRs die selects zu choice machen übernehmen @olien
