### ISSUE TITLE
YForm 4 Testing - Slow

### ISSUE THREAD

**Issue by skerbis** [yakamara/redaxo_yform#1135]
Update in einer Testumgebung führt dazu dass das Backend extrem langsam wird. 
Ich habe auf alte Feldtypen getippt. Bin aber alle durchgegangen und habe nichts gefunden. 

Bin alle Validierenden durchgegangen (z.B. email) und habe auch keine Selects im Einsatz. 

von: 3.4.2
nach: Aktuelle Github Version 

Clockwerk: 

<img width="1131" alt="Bildschirmfoto 2021-10-14 um 10 32 29" src="https://user-images.githubusercontent.com/791247/137281099-541fbe1f-4548-45a5-a9df-db04844d551c.png">

XDEBUG meldet: 

179339.7 ms für 
rex_yform_manager_table->__construct
var/www/vhosts/fvn.de/staging.fvn.de/redaxo/src/addons/yform/plugins/manager/lib/yform/manager/table.php:30

179217.9 ms
rex_yform_manager_field->__construct
/var/www/vhosts/fvn.de/staging.fvn.de/redaxo/src/addons/yform/plugins/manager/lib/yform/manager/field.php:16

**Comment by skerbis** [comment]
Ok es scheint an der aktuellen ycom Beta zu liegen - mir ist noch nicht klar was

**Comment by skerbis** [comment]
Ich glaube in der aktuellen YCOM ist etwas drin was YForm nicht mehr kann. 
Den selben Effekt hatte ich früher schon mal als einige Felder von YForm nicht mehr unterstützt wurden bzw. entfernt wurden. Leider kann ich nicht feststellen was es ist.

**Comment by dergel** [comment]
Konntet ihr mittlerweile genaueres finden. Ich kann das nicht nachvollziehen. Bei jedem Aufruf?

**Comment by marcohanke** [comment]
@dergel Ja, bei jedem Aufruf, ich schick dir Zugangsdaten zu einer Testinstalltion, dann kannst du es selber prüfen.

**Comment by dergel** [comment]
Könnt ihr das mit der den Anpassungen mal testen. Das hat jetzt nichts unmittelbar mit der ycom zu tun, beschleunigt aber einiges und vielleicht auch diesen mir nicht bekannten Aspekt
