### ISSUE TITLE
Die Version  4.0.0-dev2 erzeugt einen Fehler im Uploader Addon (oder umgekehrt)

### ISSUE THREAD

**Issue by olien** [yakamara/redaxo_yform#1140]
https://github.com/FriendsOfREDAXO/uploader/issues/70

**Comment by dergel** [comment]
hmm.. da kann ich gar nichts sagen. Und sehe das nicht hier. Sorry

**Comment by olien** [comment]
habe die Ursache gefunden. wes war ist das Multiglossar addon. ich mache dort weiter. danke!

**Comment by olien** [comment]
UPS. Das war der andere Fehler den das multiglossar verursacht. Egal. Hier ist zu ;-)))
