### ISSUE TITLE
Nicht kompatibel mit dem URL AddOn (oder umgekehrt)

### ISSUE THREAD

**Issue by olien** [yakamara/redaxo_yform#1141]
https://github.com/tbaddade/redaxo_url/issues/229

(Keine Probleme gibt es mit yForm 3.x)

**Comment by dergel** [comment]
@tbaddade weisst du mehr ?

**Comment by tbaddade** [comment]
Nein. Haben sich EPs geändert? @olien Kannst du beschreiben was genau wann, wie, wo nicht funktioniert?

**Comment by olien** [comment]
Ich setze mal alles neu auf und versuche den fehler reproduzierbar zu machen

**Comment by olien** [comment]
habe die Ursache gefunden. wes war ist das Multiglossar addon. ich mache dort weiter. danke!
