### ISSUE TITLE
YOrm - Create erstellt die Datensätze doppelt

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#1144]
Version: Github Version vom 02.11.2021

Beispiel:

```php
$dataset = Dataset::create('rex_yf_dataset');
$dataset->priority = 1;
$dataset->relation_id = 3;
$dataset->name = 'Name';
if ($dataset->save()) {
    dump('Gespeichert!', $dataset->getId());
} else {
    dump(implode('<br>', $$dataset->getMessages()));
}
```

Der Datensatz landet zweimal in der Tabelle.

**Comment by alxndr-w** [comment]
Da mir das in einem Projekt von mir nicht passiert (ältere beta): sicher, dass es nicht im Modul-Kontext mit doppeltem REX_ARTICLE passiert?

**Comment by tbaddade** [comment]
Der Code steht in einer Backend-Page des Project-Addons.

**Comment by tbaddade** [comment]
Wurde in der Zwischenzeit anscheinend behoben.

**Comment by alxndr-w** [comment]
@tbaddade ich würde es gerne dokumentieren. `relation_id` ist die ID eines Datensatzes einer anderen Tabelle. Geht das nicht nur 1:n sondern m:n? Wird das richtig in einer Relationstabelle abgebildet?

**Comment by tbaddade** [comment]
> Wird das richtig in einer Relationstabelle abgebildet?

Das hatte ich nicht getestet. Obiger Fall war nur eine 1:n Tabelle.
