### ISSUE TITLE
YForm4 mit Yorm-Query: nicht alle Feldypen sind umgestellt.  

### ISSUE THREAD

**Issue by christophboecker** [yakamara/redaxo_yform#1149]
In Verbindung mit #1148 wollte ich prüfen, wieviele Value-Klassen man den Alias ergänzen müsste. Dabei fiel auf, dass wohl tw. Value-Typen noch nach der alten Logik arbeiten, also einen Vergleich als String liefern (`return 'feld = wert'`) statt die YOrm-Query zu befüllen (`return $query`).

Betrifft die `value_class::getSearchFilter($params)` in

https://github.com/yakamara/redaxo_yform/blob/037cc51c8d9053a343802ff3e0a352577898a14a/lib/yform/value/datestamp.php#L98-L109

https://github.com/yakamara/redaxo_yform/blob/037cc51c8d9053a343802ff3e0a352577898a14a/lib/yform/value/datetime.php#L265-L316

Hat das einen tieferen Grund?

**Comment by christophboecker** [comment]
Im PR #1152 habe ich datestamp.php nicht angefasst, da dort kein `getSearchField` existiert. Ich kann nicht beurteilen, was hier die Intention ist - Suche grundsätzlich ermöglichen (`getSearchField` einbauen) oder nicht (dann `getSearchFilter` raus)

**Comment by dergel** [comment]
Ist mit diesem Commit gemacht. Danke für den Hinweis:

https://github.com/yakamara/redaxo_yform/commit/f596966ff4a2c01c26791794c3d49a50b26f2e80
