### ISSUE TITLE
value.upload.tpl und upload.php noch anpassen.

### ISSUE THREAD

**Issue by dergel** [yakamara/redaxo_yform#115]
so dass es passt :)

**Comment by tbaddade** [comment]
Könnte man nicht die Values Mediafile und Upload vereinen bzw. das eine sogar löschen.

Mediafile:
> Ein Upload-Feld, mit dem eine Datei in den Medienpool hochgeladen wird.

Upload
> Ein Upload-Feld, mit dem eine Datei in den Medienpool, die Datenbank oder ein Verzeichnis hochgeladen wird.

**Comment by alexplusde** [comment]
Mir war der Unterschied auch für die Doku nicht ganz klar.

https://github.com/yakamara/redaxo_yform_docs/blob/master/de_de/table_manager_feldtypen.md#mediafile
https://github.com/yakamara/redaxo_yform_docs/blob/master/de_de/table_manager_feldtypen.md#upload

**Comment by dergel** [comment]
upload feld muss überarbeitet werden. ist noch fehlerhaft

**Comment by dergel** [comment]
* Download in Übersicht anpassen
* Mediafile mit aufnehmen
* Unlink irgendwie lösen.

**Comment by alexplusde** [comment]
`*hüstel*` kann es sein, dass das Feld immer noch nicht das macht, was es soll?

**Comment by dergel** [comment]
mittlerweile schon :D

**Comment by alexplusde** [comment]
Getestet?

**Comment by dergel** [comment]
die sind nicht zusammengefasst und laufen noch einzeln .. also mediafile und update.. aber jedes für sich ist bei uns erfolgreich im Einsatz.

**Comment by rkemmere** [comment]
Sicher das es geht? 
**Mediafile**
Bei "Speichern" scheint es zu gehen, bei "Übernehmen" wird doppelt gefeuert und dann kein Datensatz in der DB geschrieben.

**Comment by dergel** [comment]
Bitte neues Issue dazu mit der genauen Beschreibung..

**Comment by rkemmere** [comment]
> Bitte neues Issue dazu mit der genauen Beschreibung..

Done: [https://github.com/yakamara/redaxo_yform/issues/741](https://github.com/yakamara/redaxo_yform/issues/741)
