### ISSUE TITLE
Uploadfeld Wildcard = TypeError

### ISSUE THREAD

**Issue by marcohanke** [yakamara/redaxo_yform#1156]
Ich habe als erlaubte Dateien "*" hinterlegt und bekomme bei allen Dateiformaten "type_error"

**Comment by marcohanke** [comment]
Ich bekomme konsequent immer "type_error"
auch wenn ich ".jpg,.jpeg,.gif,.png" hinterlege und versuche eine .jpg hochzuladen.
Aktuelle Github Version, neu installiert.

**Comment by dergel** [comment]
Kann ich nicht nachvollziehen. Klappt bei mir einwandfrei.
