### ISSUE TITLE
4.0-beta4: createdate/updatedate im Formular sichtbar

### ISSUE THREAD

**Issue by christophboecker** [yakamara/redaxo_yform#1158]
Ich habe bei einer Tabelle Felder `createdate` und `updatedate` von Typ `datestamp`. Bisher (vor beta4) wurden die Felder im Formular nicht angezeigt. Nun sind die im Formular sichtbar.

Absicht oder Versehen? Der Code sieht aktuell so aus:

https://github.com/yakamara/redaxo_yform/blob/3abc989aa8bfe98efc23ba12c5f024f60e7142dc/lib/yform/value/datestamp.php#L32-L49

Die hier angesprochenen Templates 
- 'value.datestamp-view.tpl.php'
- 'value.datetime-view.tpl.php'
- 'value.date-view.tpl.php'

habe ich nicht gefunden. Vieleicht löst es sich ja darüber? 

Im alten `datestamp` war gar keine Ausgabe vorgesehen.
```php
public function enterObject()
{
    if ($this->needsOutput() && 1 == $this->getElement('show_value')) {
        if ('' != $this->showValue) {
            $this->params['form_output'][$this->getId()] = $this->parse('value.showvalue.tpl.php', ['showValue' => $this->showValue]);
        } elseif ('' != $this->getValue()) {
            $this->params['form_output'][$this->getId()] = $this->parse('value.hidden.tpl.php');
        }
    }

    $this->params['value_pool']['email'][$this->getName()] = $this->getValue();
    if ($this->getValue() && $this->saveInDb()) {
        $this->params['value_pool']['sql'][$this->getName()] = $this->getValue();
    }
}
```

**Comment by dergel** [comment]
Ist mit Absicht. Ich wollte keine individuellen versteckten Felder mehr haben, eventuell versteckte Felder allgemein mit aufnehmen. Stört es dich, oder war es eher nur ein Hinweis?

**Comment by christophboecker** [comment]
Ich habe nachgefragt, weil die Änderung Absicht sein kann oder Versehen. Wenn Absicht werde ich schon einen Weg finden, sie wieder auszublenden (z.B. Template überschreiben).

Um die direkte Frage zu beantworten: ja, außerdem stört es mich. Das sind imho technische Felder, die muss der Anwender i.d.R. eben nicht sehen. Ein Admin schon eher, aber der normale User nicht. 

Der zweite Aspekt sind die fehlenden (?) Templates. Fehlen die wirklich oder sind das Namen "reserved for future use". Das neue System erschließt sich mir noch nicht ganz. Bei diesem Value-Typ sind vier Templates angegeben. Ist das dann die vierfache Anzahl an Suchzugriffen, bis das letzte greift?

Also insgesamt kein Beinbruch, ich möchte nur sicher sein, dass es kein Versehen ist, bevor ich Energie in die Templateanpassung stecke.

**Comment by dergel** [comment]
Ist kein Versehen. Und ja, das sind mehrere Suchzugriffe nötig, aber sehe ich nicht als Performanceproblem. Die Idee ist genau die, wie du es für dich lösen willst, eigene Templates bauen. In der Basis möchte ich so wenig unterschiedliche Templates haben wie möglich - und die meisten sind auch einfach fast identisch.

**Comment by TobiasKrais** [comment]
Doku sollte noch angepasst werden...

**Comment by alxndr-w** [comment]
@TobiasKrais ich kann das Verhalten gar nicht nachvollziehen und habe datestamp-Felder im Einsatz, die jedoch nicht im Frontend sichtbar sind.

Einen Schalter `sichtbar/unsichtbar` würde ich ebenfalls bevorzugen, wenn dem so sei.

**Comment by TobiasKrais** [comment]
@alxndr-w YForm 4?

**Comment by alxndr-w** [comment]
Ja

**Comment by dpf-dd** [comment]
Ich klink mich mal ein. yForm 4.0.0 und mein Label vom datestamp-Feld wird im Frontend ausgegeben (das Hidden-Input-Feld selbst sehe ich aber nicht). Ich verstehe die Intention von Jan, aber...
Mir fällt irgendwie kein Usecase ein, in dem das datestamp-Feld im Frontend gewünscht ist, deswegen empfinde ich es als logischer, dass ein datestamp-Feld eben per Default NICHT ausgegeben wird.

Wie dem auch sei, hab das jetzt quick & dirty mit CSS auf display-none gestellt und werde mich mittelfristig auf die Lösung von @christophboecker stürzen :)

**Comment by dergel** [comment]
du kannst ein leeres datestamp view Ytemplate aufnehmen Dann taucht es nicht auf. Ich nehme es dann doch als Punkt auf. Das war mir vorher in der Tiefe nicht bewusst, was es mit sich bringt ( ich glaube an das Frontend habe ich ursprünglich gar nicht gedacht )

https://github.com/yakamara/redaxo_yform/issues/1263
