### ISSUE TITLE
4.0-beta4: fehler im date-Value

### ISSUE THREAD

**Issue by christophboecker** [yakamara/redaxo_yform#1159]
Ist ein Datumsfeld im Formular leer (z.B. weil neues undd aher leeres Formular), gibt es eine Fehlermeldung:
<img width="656" alt="grafik" src="https://user-images.githubusercontent.com/10065904/144647226-7080afd0-d2d8-4925-a1ae-e3d88b0fd4a1.png">
Der Fehler kommt aus `preValidateAction`:

https://github.com/yakamara/redaxo_yform/blob/3abc989aa8bfe98efc23ba12c5f024f60e7142dc/lib/yform/value/date.php#L27-L45
Hier mal mit Kontroll-Dump ...
```php
    public function preValidateAction(): void
    {
        $value = $this->getValue();
        dump($value);
        if (1 == $this->getElement('current_date') && '' == $this->getValue() && $this->params['main_id'] < 1) {
            $value = date('Y-m-d');
        }
        if (is_array($value)) {
            $year = (int) $value['year'] ?? 0;
            $month = (int) $value['month'] ?? 0;
            $day = (int) $value['day'] ?? 0;
        } else {
            dump($value);
            $value = explode("-", (string) $value);
            dump($value);
            $year = (int) $value[0] ?? 0;
            $month = (int) $value[1] ?? 0;
            $day = (int) $value[2] ?? 0;
        }
        $value = sprintf("%04d-%02d-%02d", $year, $month, $day);
        $this->setValue($value);
    }
```
... und deren Ergebnis:
<img width="225" alt="grafik" src="https://user-images.githubusercontent.com/10065904/144648078-56e6c63d-c546-41a2-8fe2-2bce1820024c.png">

Ich konnte das Problem lösen, indem `$value[..] ?? 0` eingeklammert wird:

```php
            $year = (int) ($value[0] ?? 0);
            $month = (int) ($value[1] ?? 0);
            $day = (int) ($value[2] ?? 0);
```
Muss das wirklich so sein? Würde auch für den darüber liegenden Block gelten.

**Comment by dergel** [comment]
da dies auch bei time und datetime aufgetaucht ist habe ich das als ein commit umgesetzt. Dann dennoch für den PR closes #1160
