### ISSUE TITLE
Formbuilder Notation auf VARS umstellen

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#116]
Mir kam grad die Idee, dass man die Notation im Formbuilder auf `YFORM_VARS` ändern könnte. Vorteil wäre, dass man hier freier in der Schreibweise wäre, als in der Pipenotation und es einige Probleme beseitigen könnte.

Bsp.

```
YFORM_VALUE[type="text" name="surname" label="{{ surname }}" prefix="" suffix="" attributes='placeholder="" data-trigger="Buh"']

YFORM_VALIDATE[type="empty" name="surname" message="{{ surname.error.empty }}"]

YFORM_ACTION[type="email" from="e@ma.il" to="l@ia.me" template=""]
```

Sozusagen wie die REX_VARS oder DAO_VARS.

**Comment by dergel** [comment]
man könnte es so machen wenn man cniht erwarten würde, dass die Felder entsprechend an den Stellen erscheinen. Im Moment definieren wir das Formular, layouten es aber nicht innerhalb der Notation. Ich weiss im Moment auch keine Lösung wie man das gut verbinden könnte
