### ISSUE TITLE
Major Changes Methoden? ... was ist zu tun? 

### ISSUE THREAD

**Issue by skerbis** [yakamara/redaxo_yform#1161]
https://github.com/FriendsOfREDAXO/yform_geo_osm/blob/1d7285fdc84cb1227f77c6cdd72933881135dfe1/lib/yform_value_osm_geocode.php#L16

> Declaration of rex_yform_value_osm_geocode::getDescription() must be compatible with rex_yform_base_abstract::getDescription(): string

Man man muss die return typen übergeben.

Habe mal einen PR bei dem AddOn gemacht. 
https://github.com/FriendsOfREDAXO/yform_geo_osm/pull/19

**Comment by alxndr-w** [comment]
getDefinition() ist auch davon betroffen.

**Comment by dergel** [comment]
Ich weiß nicht im Einzelnen, was andere AddOns bei YForm nutzen. Aber das sind Anpassungen, die gemacht werden müssen. Ich wollte hier und da eine bessere Basis schaffen und damit müssten die AddOn die Abhängig sind von YForm leider leben und diese Korrekturen durchführen: Ich sehe mich da bei der YCom da auch noch einiges nacharbeiten - bin aber auch schon dabei. Sorry. Richtig dokumentieren kann man es nicht, hier und da kann auch noch etwas passieren

**Comment by dergel** [comment]
Ich würde das hier schließen, ich hoffe, das ist ok - sehe keine Aufgabe für YForm Version 4.0

**Comment by alxndr-w** [comment]
Moment, moment. Es ist ja okay, dass diese Anpassungen erfolgen müssen, aber sollen @skerbis oder ich durch experimentieren rausfinden, was anzupassen ist?

Von mir aus kann das Issue zu bleiben, @skerbis würdest du trotzdem hier mit mir festhalten, was im Zuge dessen whoopst bei eigenen Felddefinitionen etc.?

**Comment by skerbis** [comment]
Danke für die Info. Ich wollte es nur irgendwo notieren und ggf. in das changelog schreiben


Das sind schon mal die beiden Stellen, ich habe diesbezüglich einige Addons aktualisiert oder dort PR eingereicht. 
Lt. Christoph Böcker muss auch bei Nutzung von Datasets nachgearbeitet werden. Habe aber kein Addon bei FOR gefunden wo was nötig wäre.

**Comment by dergel** [comment]
> Nutzung von Datasets nachgearbeitet werden

Wüsste ich jetzt nicht. Weißt du war der meint?

**Comment by christophboecker** [comment]
`class rex_yform_manager_dataset` Wie an vielen anderen Stellen und z.B. den Values-Klassen auch sind hier die Typ-Deklarationen eingeführt. Wer eigene Dataset-Klassen nutzt (was neben Value-Klassen wohl die häuftigste (auf jeden Fall zunehmende) Form eigener YForm-Erweiterungen sein könnte, muss da eben auch anpassen. Je nun, ist schnell gemacht. Es geht Thomas ja auch nur um den Hinweis.

**Comment by alxndr-w** [comment]
Ich nutze die dataset-Klasse, habe aber nie Methoden überschrieben - nur ergänzt. Muss man es dann nicht?

**Comment by christophboecker** [comment]
> Ich nutze die dataset-Klasse, habe aber nie Methoden überschrieben - nur ergänzt. Muss man es dann nicht?

Dann nicht. Bei mir werden schon mal getForm, excecuteForm oder z.B. delete überschrieben; bin daher betroffen.

**Comment by dergel** [comment]
Hast du Lust das zu dokumentieren, oder auch in der CHANGELOG unterzubringen?
