### ISSUE TITLE
Checkbox -> Ausgabewerte eingeben funktioniert nicht

### ISSUE THREAD

**Issue by marcohanke** [yakamara/redaxo_yform#1169]
Ich habe als "Ausgabewerte eingeben" offline,online definiert. Ich vermute dass soll in der DB landen? Da ist nach wie vor 1 oder 0 zu finden.

**Comment by dergel** [comment]
die sind für die Übersicht in der Listendarstellung :)

**Comment by alxndr-w** [comment]
Seit #885
