### ISSUE TITLE
Testen der Classic Views

### ISSUE THREAD

**Issue by dergel** [yakamara/redaxo_yform#117]
- anpassen der Attributwerte
- ...

**Comment by alexplusde** [comment]
mind. value.text.tpl.php hat wohl Probleme

**Comment by alexplusde** [comment]
```"ErrorException" thrown in /home/netsh108145/html/performa/redaxo/src/addons/yform/ytemplates/classic/value.text.tpl.php on line 8
Fatal error: Call to undefined method rex_yform_value_text::getAttributeElement()```

**Comment by alexplusde** [comment]
Muss da nicht überall statt ```getAttributeElement``` ein ```getAttributeElements``` hin?

**Comment by dergel** [comment]
da muss leider wohl wirklich einiges umgebaut werden.. meine motivation ist leider nur sehr gering, da ich diese templates nie benutze.. Freue mich über Hilfe.

**Comment by alexplusde** [comment]
Wenn du die values per Suchen und Ersetzen updaten kannst (es muss statt `getAttributeElement` heißen:  `getAttributeElements`), dann würde ich schauen, wo es sonst noch hakt.

**Comment by tbaddade** [comment]
**Übersicht**

- [ ] /classic/errors.tpl.php
- [ ] /classic/form.tpl.php
- [ ] /classic/value.article.tpl.php
- [ ] /classic/value.captcha.tpl.php
- [ ] /classic/value.captcha_calc.tpl.php
- [ ] /classic/value.checkbox.tpl.php
- [ ] /classic/value.checkbox_sql.tpl.php
- [ ] /classic/value.datetime.tpl.php
- [ ] /classic/value.fieldset.tpl.php
- [ ] /classic/value.hidden.tpl.php
- [ ] /classic/value.mediafile.tpl.php
- [ ] /classic/value.radio.tpl.php
- [ ] /classic/value.resetbutton.tpl.php
- [ ] /classic/value.select.tpl.php
- [ ] /classic/value.showvalue.tpl.php
- [ ] /classic/value.submit.tpl.php
- [ ] /classic/value.submits.tpl.php
- [ ] /classic/value.text.tpl.php
- [ ] /classic/value.textarea.tpl.php
- [ ] /classic/value.upload.tpl.php

**Comment by tbaddade** [comment]
Sollte jetzt soweit passen.

**Comment by alexplusde** [comment]
Danke, @tbaddade
