### ISSUE TITLE
Templates vs. Fragments

### ISSUE THREAD

**Issue by marcohanke** [yakamara/redaxo_yform#1172]
Ist es eigentlich gewünscht / vorgesehen die Ausgabe der Templates irgendwann auch mit Fragmenten zu versehen?
Ich habe jetzt testhalber ein Fragment für eine Bootstrap Alertbox dass ich sowohl bei Fehlern als auch bei Erfolgsmeldungen (mit anderer Farbe) nutze. Ich finde das eigentlich ganz cool weil das Feedback des Formulars dann immer identisch ist und könnte mir das als Standardverhalten vorstellen

**Comment by dergel** [comment]
ich eigentlich auch - aber eben auch nur eigentlich . Ich möchte auf REDAXO warten bis dort eine richte Templateengine drin ist, z.B. TWIG und dann erst umshiften .. danke aber dennoch für den Hinweis.
