### ISSUE TITLE
Problem mit Rückgabetyp ?self bei PHP 7.3

### ISSUE THREAD

**Issue by skerbis** [yakamara/redaxo_yform#1174]
Bitte dieses Issue beachten: 
https://github.com/redaxo/redaxo/issues/4972

**Comment by dergel** [comment]
das gilt dann wohl mehr für andere Nutzer, die YForm erweitern wollen. Ich würde das einfach schliessen und wir behalten das im Kopf + 7.3 ist ja so gut wie durch.
