### ISSUE TITLE
size_range für Frontend

### ISSUE THREAD

**Issue by marcohanke** [yakamara/redaxo_yform#1177]
Moin, bisher hab' ich size_range immer problemlos fürs Frontend eingesetzt. Im aktuellen Fall geht es um eine Bewerbung für eine Auszeichnung. Und hier sind die Eintragenden immer ziemlich hart am Limit und übergeben aus Word genau 999 Zeichen. size_range steht auf 1.000 Zeichen gibt mir aber false zurück.
Problem ist scheinbar, dass die HTML Zeichen gezählt werden also ein ü z. B. als &uuml;
Ist das gewollt? Ich vermute mal ja weil es um die Zeichen in einem DB Feld geht?
Wie bekomme ich hier die Kuh vom Eis? Muss ich das manuell per JS validieren?

**Comment by eaCe** [comment]
@marcohanke das liegt daran das in der Funktion strlen genutzt wird. Dein ü sind dann zwei Zeichen.
https://github.com/yakamara/redaxo_yform/blob/master/lib/yform/validate/size_range.php#L36
Alternativ kannst du da `mb_strlen($Object->getValue(), "utf-8")` rein werfen, aber dann ist es beim Update wieder futsch...

**Comment by marcohanke** [comment]
Ui @eaCe das ging flott und ist einfach ;-) Danke für den Tip, ich könnte ja auch eine eigene Validation daraus machen.
Die frage ist, WARUM ist da strlen drin und macht dass Sinn? Oder sollte man das anpassen.

**Comment by eaCe** [comment]
Ich denke das hat sicher Gründe. Die kenne ich aber nicht

**Comment by dergel** [comment]
Ich denke, das können uns sollten wir überall anpassen, da yform eh mittlerweile davon ausgeht, dass wir utf8mb4 verwenden. Da kommen ja noch mal ganz andere Bytelängen raus ;) ..

**Comment by dergel** [comment]
ist nun drin
