### ISSUE TITLE
Inline CSS Manager Listenansicht vs Dark Mode

### ISSUE THREAD

**Issue by IngoWinter** [yakamara/redaxo_yform#1178]
In https://github.com/yakamara/redaxo_yform/blob/master/plugins/manager/lib/yform/manager.php#L1303-L1309 werden inline Farben/Hintergrundfarben gesetzt, die nicht mit dem Dark Mode Theme harmonieren.

![tm_list_darkmode](https://user-images.githubusercontent.com/7223820/146159966-3d74318d-a616-4090-b9c1-663dfc7e6570.png)

**Comment by dergel** [comment]
@schuer Dirk - jetzt darfst du gerne anfangen :) .. 4.0 ist nun bereit für DarkMode Änderungen

**Comment by eaCe** [comment]
Das issue ist inzwischen resolved.
