### ISSUE TITLE
Wording "Anzeigeformat"

### ISSUE THREAD

**Issue by marcohanke** [yakamara/redaxo_yform#1180]
Hier bin ich auch schon öfter drüber gestolpert.
Anzeigeformat klingt für mich nach der konkreten Anzeige, also auch im Backend. Es meint aber nur die Listendarstellung.
Vielleicht gibt es hier was "besseres" oder noch eine Info dazu in der Art:
Anzeigeformat (In Listendarstellung) oder ähnliches

**Comment by dergel** [comment]
Gilt nicht nur für die Listendarstellunh, auch z.B. für Viewansichten im Backend von Tabellen.

Gerne einen besseren Namen - freue mich über Ideen

**Comment by marcohanke** [comment]
Viewansichten im Backend von Tabellen kenn ich nicht ;-)
In der Doku schreibst du "Tabellen-Übersicht" wäre das okay? Falls ja würde ich auch hier #1179 In "Tabellen-Übersicht anzeigen" schreiben

**Comment by dergel** [comment]
Ich finde `Darstellung` besser.

**Comment by marcohanke** [comment]
Einfach nur "Darstellung" Da könnte ich jetzt genauso viel mit anfangen wie mit "Anzeigeformat" glaub ich

**Comment by dergel** [comment]
`Ausgabeformat`

**Comment by marcohanke** [comment]
Nachdem wir jetzt drüber Diskutiert haben werde ich es eh nicht mehr vergessen ;-) Trotzdem fände ich einen Bezug zur Tabelle bzw. Liste gut. Bei allem anderen gehe ich davon aus, dass die Ausgabe in der Tabelle im Backend und im Frontend gemeint ist.

**Comment by ynamite** [comment]
In dem Bezug, ich fände es toll, wenn auch das Eingabe-Select/-Input das Format respektieren würde.

**Comment by alxndr-w** [comment]
Das Thema kam auf Slack neulich wieder auf, beim besten Willen kann ich nicht verstehen, wie man beim Ausgabeformat auf ein Eingabeformat. Ein Datumsfeld im technischen Sinne muss das Datum standardisiert eingegeben werden.

Für eine optimale Eingabe für den Nutzer gibt es eigene HTML5-Input-Typen (`date`, `time`, `datetime-local` siehe #1230). 

Imho: Wer was anderes benötigt und auf gültige Datumsangaben pfeifen kann, kann ein Textfeld benutzen.

**Comment by alxndr-w** [comment]
Was mir in der ganzen Diskussion dazu immer wieder auffällt: Jegliche Hinweise auf die Verwendung passender HTML-Eingabefelder - mit denen sich das Problem von selbst erübrigt - werden in der Diskussion konsequent ignoriert. Als gäbe es `<input type="date" value="2022-04-12">` bspw. gar nicht.

Damit wird sowohl der Usecase gelöst, die Datumseingabe zu formatieren (bzw. die "Darstellung"/"Anzeige" der Datumseingabe), als auch die Frage geklärt, wofür das Anzeigeformat dann noch gut ist/wäre, nämlich:

1. In der Listenansicht, wo es auch Sinn ergibt, das am Feld einstellen zu können
2. In der Ausgabe im Frontend, wenn man den Wert darstellen will und dabei auf die hinterlegte Konfiguration zurückgreift.

Dazu muss man sich auch Zeit nehmen, zu verstehen, warum die eigenen Erwartungen hier nicht erfüllt werden und nicht die "schnell schnell irgendwas passt nicht ich lade das bei Slack und als Issue ab, sollen sich andere darum kümmern"-Mentalität fahren.

Und dann wird auch klar, dass es weder ein Issue, noch ein Bug, ist. Sondern ein Feature, das man nicht verstanden hat (auch ich zu anfangs).

**Comment by ynamite** [comment]
So kann man's natürlich auch sehen haha. Heute mit dem falschen Fuss aufgestanden? ;) 
Wer sagt denn, dass deine Inputs betreffend HTML5-Input Types ignoriert werden? 

Es geht darum, dass es offenbar Viele trotzdem falsch verstehen (gerade eben im Slack wieder), also ist das Wording schlecht gewählt. Das ist schon alles. Hab ja geschrieben, dass es nicht so sein muss.

Zudem kann man das durchaus anders sehen, selbst wenn es die HTML5 Input Types gibt, könnte das Feld, wie so viele andere Felder von yform, das ganze Prozedere für User vereinfachen, die vielleicht keine Ahnung von HTML haben. Ich dachte der Table-Manager sei dazu da, den Umgang mit Tabellen und Tabellen-Felder zu vereinfachen.

> als auch die Frage geklärt, wofür das Anzeigeformat dann noch gut ist/wäre, nämlich:

Ich finde den Usecase jetzt relativ gering, wenn's nur das ist. Von mir aus kann das dann ganz raus 🤷 

> Dazu muss man sich auch Zeit nehmen, zu verstehen, warum die eigenen Erwartungen hier nicht erfüllt werden und nicht die "schnell schnell irgendwas passt nicht ich lade das bei Slack und als Issue ab, sollen sich andere darum kümmern"-Mentalität fahren.

Ja gut, wenn das deine Ansicht dazu ist, dann könnte man sich imo gleich die Zeit nehmen Tabellen, Relationen, Feld-Typen, MySQL usw. beizubringen und ganz auf den Table-Manager verzichten. Nochmal, offenbar wird das Feld oft missverstanden, das ist doch die Krux am Issue. 

> Und dann wird auch klar, dass es weder ein Issue, noch ein Bug, ist. Sondern ein Feature, das man nicht verstanden hat (auch ich zu anfangs).

Sehe ich anders. Aber du, jeder wie er will.

**Comment by alxndr-w** [comment]
@ynamite da dürfen wir ja gerne unterschiedliche Ansichten haben und uns auch von unterschiedlichen Punkten einem Problem annähern. Womit ich auf jeden Fall mitgehe, ist, dass das Datums-Feld ohne eigene Anpassungen aktuell nicht brauchbar ist. 

> Heute ev. mit dem falschen Fuss aufgestanden? ;)
> Sehe ich anders. Aber du, jeder wie er will.

Mir gehen diese "Befindlichkeiten" manchmal auf den Keks. Das gleich ins Persönliche zu ziehen und Best Practice oder Standards zur "Meinung" zu erklären. Vor allem diskutiere ich hier nicht, um "Meinungen" auszutauschen, sondern Lösungen zu finden. Und da nervt es echt, wenn jeder nur bis zu seinem Tellerrand blickt, statt sich darauf einzulassen, dass es vielleicht einen anderen Lösungsweg gibt, der Vorteile hat gegenüber dem, wie man es bisher gemacht hat oder man etwas Neues dazu lernt. Ist das so verkehrt?

**Comment by alxndr-w** [comment]
Vorschlag: @ynamite @dpf-dd @marcohanke ihr schreibt hier mal die Szenarien runter, wo ihr das Datumsfeld aktuell einsetzt und was davon "nicht funktioniert" (zumindest nicht so wie gedacht / gewünscht) und dann schauen wir, wie man jedes einzelne Phänomen löst - mit Bordmitteln, mit Anpassungen oder PRs und Bugfixes.

**Comment by alxndr-w** [comment]
Also geht's darum, dass ihr mit dem Anzeigeformat die Reihenfolge **bei den select-Feldern** ändern möchtet? Und das aktuell das Format ignoriert und `[YYYY]-[MM]-[DD]` daraus macht?

**Comment by ynamite** [comment]
Kann nur für mich sprechen. Marco's Issue war, wie er oben schreibt, nur dass das Wording unglücklich ist:

> Hier bin ich auch schon öfter drüber gestolpert.
Anzeigeformat klingt für mich nach der konkreten Anzeige, also auch im Backend. Es meint aber nur die Listendarstellung.
Vielleicht gibt es hier was "besseres" oder noch eine Info dazu in der Art:
Anzeigeformat (In Listendarstellung) oder ähnliches

**Comment by alxndr-w** [comment]
Also wenns das ist, dann kam das für mich aus keiner der Diskussionen rüber. Manchmal wären zwei Screenshots soll/ist da hilfreich, um zu verstehen, worum es geht.

Für mich persönlich fällt das Rendern als select mit so Eingabemöglichkeiten wie 31. Februar komplett unten durch. Keine optimierte Tastatur am Tablet/mobil, keine Ansicht nach Wochentagen.

Die Beschränkung auf bestimmte Zeiträume (z.B. Kalenderjahre) könnte man auch mit einem date-Input imho viel besser lösen, weil da wirklich ein min/max datumsgenau geht. Das dynamisch einzustellen fehlt aber glaube ich aktuell im YForm, wenns nicht als select gerendert wird.

@ynamite 

> Weil ich schlechte Erfahrungen mit Kalender-Widgets gemacht habe

Die würden mich echt interessieren, wenn du noch Zeit hast.

**Comment by alxndr-w** [comment]
> komisch ist, dass es sonst alle kapiert haben ... Maybe it's you? ;)

Ich habe mich über das Issue mit jemandem unterhalten, der die Diskussion auch nicht verstanden hat und sehr viel mit REDAXO macht, von daher. Schau doch nochmal nach, wann hier der Begriff "select" fiel ;)

**Comment by ynamite** [comment]
@alxndr-w Ich mach's jetzt kurz und danach enthalte ich mich der weiteren Diskussion, weil so wichtig ist's mir dann auch wieder nicht. Du schreibst ganz viel und ganz fest am Thema vorbei. 

Wenn du lieber immer wieder dieselben Fragen beantworten möchtest, betreffend dem Wording `Anzeigeformat`, obwohl du dich scheinbar über die Fragerei/Diskussion aufregst, dann sei's drum. Ich weiss ja mittlerweile, dass es irreführend beschrieben ist und wie ich damit umzugehen habe. Mir fallen übrigens mindestens 3 Varianten ein, die besser verständlich wären (Hinweis unter dem Feld, dass das Format ausschliesslich auf die Listendarstellung eine Auswirkung hat, z.B. oder man nennt es einfach Listendarstellungs oder Listendarstellungsformat, whatever)

> Da sieht man aber, von was wir alles unterschiedlich ausgehen, wenn man das so aufdröselt (worüber ich froh bin).
> seitdem mir klar ist, worauf @ynamite du dich beziehst.

Du bist allerdings der, der von Unterschiedlichem ausgeht ;) respektive dir ist's noch immer nicht klar. Ich kenne die div. Input Types und Möglichkeiten betreffend locales usw., danke trotzdem. 
Deine Frage war, wieso ich mich damals von Widgets abgewendet hatte. Diese Gründe habe ich dir beschrieben. Der Grund wieso ich auch heute noch auf Selects setze, falls du neugierig bist, ist hauptsächlich, weil ich damit 10x schneller bin ein Datum einzustellen, als über ein Widget (egal ob Browser- oder JS-Widget).

> Das (browsereigene) Widget kann jedenfalls nichts dafür, dass die initiale Eingabe nicht funktioniert, wenn man ihm das Datum nicht standardkonform (imho "falsch") übergibt. Deswegen auch mein PR.

Wo ich denn behauptet, dass das Browser-Widget etwas dafür kann?

> Wegen des Wordings: Mein Ansatz ist halt um die Ecke gedacht, und deswegen war und bin ich da so beharrlich: Das Problem taucht nicht auf, wenn man's anders löst.

Das ist ja schön und gut, zumindest in der Theorie. In der Praxis nützt dir das leider nicht viel. Fakt ist ja, dass immer wieder User drüber stolpern und dieselbe Frage stellen. 
Aber hey, du darfst denen dann gerne jedesmal wieder daselbe erklären ;) Hast ja Übung.

> Warum soll ein Redakteur ein deutsches Format präsentiert bekommen, wenn er gar nicht eine deutsche Eingabe gewöhnt ist?
... Konsistenz
... etc.

Äh, auch wenn ich dir bei vielem beipflichten würde, was hat das mit dieser Diskussion zu tun? Alle haben gecheckt das es ums Wording geht, welches User immer wieder verwirrt. Würde mich schon noch interessieren, wer auf diesen Thread bezogen, nicht nachgekommen ist, ausser dir?

**Comment by ynamite** [comment]
> Schau doch nochmal nach, wann hier der Begriff "select" fiel ;)

> Ich fände es toll, wenn auch das __Eingabe-Select/-Input__ das gewählte __Ausgabe-/Darstellungs-/Anzeige-Format__ respektieren würde.

I don't see your point 🤷 hab doch nur beigefügt, dass ich es "toll fände".

**Comment by marcohanke** [comment]
Ich will jetzt nicht groß in die Diskussion einsteigen nur noch mal klar stellen: Das Issue hier ist einfach entstanden, weil ich, sowie andere Leute im Slack immer mal hier rüber stolpern und etwas anderes Erwarten als es tatsächlich ist. Es geht also nicht um den "richtigen" Weg für Usecase XY, sondern darum dass Dinge Missverstanden werden. Und wenn mehrere Leute etwas Missverstehen, finde ich schon dass man sich Gedanken machen kann, ob es vielleicht eine bessere Beschreibung hierzu gibt.
