### ISSUE TITLE
Wording "Erlaubte Dateien"

### ISSUE THREAD

**Issue by marcohanke** [yakamara/redaxo_yform#1181]
Im Upload-Feld steht "Welche Dateien sollen erlaubt sein, kommaseparierte Liste. ".gif,.png" oder "*"
Bei be_media steht "Types" und als Noitz dazu Format: jpg,gif
Mediafile fliegt sowieso raus, sonst habe ich keine Felder gesehen in denen man Dateien auswählen kann.

Das könnte man angleichen in 
Erlaubte Dateiformate
 + Notiz: Format jpg,gif, ... oder *

Hätte auch den Vorteil dass nicht irgendein Honk "*" ins Feld kopiert und sich wundert dass es nicht funktioniert ;-)

**Comment by tbaddade** [comment]
Eventuell auch angleichen ob mit oder ohne Dot am Anfang.

**Comment by marcohanke** [comment]
@tbaddade Auf jedenfall. Aktuell ist auch das verschieden.

**Comment by alxndr-w** [comment]
Dann auch Mal am Core und den Media-Feldern spicken und schauen, wie es sich richtiger anfühlt.

Ich weiß, dass ich bei einem YForm-Feld Mal eine Anpassung gemacht habe, um die Angabe so zu ermöglichen, wie das passende HTML-Attribut eines file-Inputs. Das fände ich am sinnvollsten, weil Standard.

**Comment by dergel** [comment]
das ist doch mal ein Easy PR, oder  Leute ?

**Comment by marcohanke** [comment]
@dergel Erstmal müsste man wissen, welche Version preferiert wird. Headline und oder Notiz. Mit oder ohne . ???
