### ISSUE TITLE
Wording Validate "Vergleichsart"

### ISSUE THREAD

**Issue by marcohanke** [yakamara/redaxo_yform#1182]
Auch hier stolpere ich gerne mal.
Ich will eine Fehlermeldung wenn der Wert != 00:00:00 ist.
Nutze ich die Vergleichsart != kommt aber kein Fehler, ich muss == nehmen.
Ich weiß aber auch nicht so richtig wie man das löst.
Vielleicht "Vergleichsart (Fehlermeldung ausgeben bei)"
Oder als Notiz: "Fehlermeldung wird ausgegeben, wenn Vergleichsart true ist"
???

**Comment by dergel** [comment]
Darf gerne ein längerer Text sein.

`Bitte Vergleichsart angeben, bei welchem keine Fehlermeldung ausgegeben wird.`

**Comment by alxndr-w** [comment]
Bitte #623 beachten - gilt ja u.U. nicht nur für compare

**Comment by dergel** [comment]
Textvorschläge

Fehlermeldung wird ausgegeben, wenn Vergleichsart true ist

Bitte Vergleichsart angeben, bei welchem keine Fehlermeldung ausgegeben wird.

oder

...

**Comment by marcohanke** [comment]
Bitte Vergleichsart angeben, bei welchem keine Fehlermeldung ausgegeben wird.
Find ich okay.
Oder etwas kürzer
"Bei dieser Vergleichsart wird KEIN Fehler ausgegeben.

**Comment by alxndr-w** [comment]
„Fehlermeldung, wenn...“
