### ISSUE TITLE
YForm 4 Beta 6 - Datestamp-Ausgabe in Formular muss initial `[0000-00-00 00:00:00]` oder leer sein

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/redaxo_yform#1188]
edit: Richtig:

![image](https://user-images.githubusercontent.com/3855487/146968584-8f9856ae-5024-40b0-8d0d-9375dece5d6d.png)

Im Datensatz falsch, weil bisher noch nicht gespeichert:

![image](https://user-images.githubusercontent.com/3855487/146968656-0a3aca6e-97f3-431f-ab74-efdd7a4ac4bb.png)

**Comment by dergel** [comment]
hmm.. kann es sein, dass datestamp eingetragen hat, dass es wenn es leer ist neu gesetzt wird? vielleicht gibt es keine passenden Werte und nur im neuen Formular wird es richtig dargestellt.

Kann es Fehler leider nicht nachvollziehen.

**Comment by alxndr-w** [comment]
In der Datenbank steht tatsächlich `[0000-00-00 00:00:00]` und ja, es soll bei Speichern eingetragen werden.

Dann dürfte hier jedoch keine Zeit angegeben werden (also vor allem nicht die Zeit des Formular-Ladens, denn das Datum wird ja beim Speichern ein anderes sein)
