### ISSUE TITLE
Tools: Datepicker übernimmt kleine Werte mehr

### ISSUE THREAD

**Issue by olien** [yakamara/redaxo_yform#1190]
4.0.0-beta6

![image](https://user-images.githubusercontent.com/330516/147059701-32ba9425-3e83-4cde-98b5-b271f509f84b.png)

**Comment by dergel** [comment]
Da hat sich einiges geändert. Es gibt nur noch das ISO Datumsformat YYYY-MM-DD. Ich denke daran liegt es .. Schau auch mal bitte in die veränderte Doku, das sollte auf dem aktuellen Stand sein.

**Comment by olien** [comment]
Hm. Ich hab des jetzt so:

![image](https://user-images.githubusercontent.com/330516/147085298-d0fa3a05-4c79-41d3-9a36-151a34425539.png)

und das kommt:

![image](https://user-images.githubusercontent.com/330516/147085331-5848aa0d-002f-4bfc-8734-17ab37c725cf.png)

REdaxo ist aktuell aus dem Installer und yform frisch von GitHub

**Comment by dergel** [comment]
Habe die Doku angepasst und inputmask greif nun auch, wenn kein Format gesetzt ist.
