### ISSUE TITLE
YForm Beta 6 - Popup-Link "übernehmen" fehlt

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/redaxo_yform#1193]
Ich kann in einem Poup keine verknüpfte Datensätze bei einem Relationsfeld übernehmen. Die Aktion dazu fehlt - auch nicht in den "Funktionen"

![image](https://user-images.githubusercontent.com/3855487/147104135-88702389-f9d9-4c1d-be0a-46efcabba840.png)

**Comment by dergel** [comment]
hmm .. ist das eine 1-n Verknüpfung auf eine neue Tabelle? .. Dann erscheint oben nur der Filter und es werden nur die passenden Datensätz angezeigt. Das kann also ok sein. Wie ist die Konfiguration dazu?

**Comment by alxndr-w** [comment]
Das ergibt absolut Sinn, es liegt an der Relation. Ich mache noch ggf. einen Textvorschlag. Ich hatte erwartet, man könne noch Verknüpfungen hinzufügen oder auflösen, aber das ist ja in dieser Oberfläche gar nicht sinnvoll umsetzbar.
