### ISSUE TITLE
Tools: Select 2

### ISSUE THREAD

**Issue by olien** [yakamara/redaxo_yform#1194]
Auswahl lässt sich nicht mehr löschen

![image](https://user-images.githubusercontent.com/330516/147119059-2077a308-cf95-47d3-b4bc-6c5eeac8ec92.png)

![image](https://user-images.githubusercontent.com/330516/147119173-6d52ba60-3cbc-4608-8865-c8c851320df0.png)

**Comment by alxndr-w** [comment]
Was passiert, wenn du auf das kleine X drückst?

**Comment by dergel** [comment]
Die Auswahl wird um ein "-" erweitert, welche quasi die Leer Option ist. Sollte demnach passen. Oder was hattest du eher erwartet ?

**Comment by olien** [comment]
Die Leer Option (das -) habe und kenne ich. Trotzdem erwarte ich, dass wenn ich auf das x klicke die Auswahl verschwindet (oder sich da ein Schatz versteckt :-)). 

![image](https://user-images.githubusercontent.com/330516/147202739-2bb4a641-e2f5-492d-b114-77b8758aad96.png)

**Comment by dergel** [comment]
dann hatte ich das issue falsch verstanden.. ok ... leeroption passt, darstellung mit x und co ist seltsam .. habe ein neues Issue dazu erstellt

https://github.com/yakamara/redaxo_yform/issues/1195
