### ISSUE TITLE
Darstellung select2

### ISSUE THREAD

**Issue by dergel** [yakamara/redaxo_yform#1195]
<img width="720" alt="Bildschirmfoto 2021-12-23 um 09 52 43" src="https://user-images.githubusercontent.com/322951/147214720-949b7d2d-4803-4499-a925-8af9b67f9f5c.png">

be_manager

multiple select

`{"class": "form-control selectpicker"}`

Darstellung seltsam

X seltsam

**Comment by tbaddade** [comment]
Wir haben select2 gelöscht. Als Alternative kann der vom Core gelieferte selectpicker verwendet werden.

[Siehe auch Doku](https://github.com/yakamara/redaxo_yform/blob/master/docs/08_tools.md#selects-erweitern)

**Comment by alxndr-w** [comment]
@tbaddade der Selectpicker kann die Tags-Darstellung nicht, oder?

Wäre eine Alternative wieder in YForm gewünscht oder generell in REDAXO?

- https://dbrekalo.github.io/fastselect/
- https://choices-js.github.io/Choices/

**Comment by tbaddade** [comment]
> Wäre eine Alternative wieder in YForm gewünscht oder generell in REDAXO?

Wenn dann gern in den Core, sodass YForm und auch andere AddOns davon profitieren.
