### ISSUE TITLE
datetime Feld zeigt bei Select d.m.Y H:i:s falsche Reihenfolge

### ISSUE THREAD

**Issue by dtpop** [yakamara/redaxo_yform#1196]
yform 4.0.0-beta6 - rex 5.13.1
Wenn im Tablemanager bei der Felddefinition `d.m.Y H:i:s` ausgewählt ist, wird bei der Bearbeitung des Datensatzes auch `Y m d H i s` angezeigt. Gleiches gilt für die Einstellung `d-m-Y H:i:s` und alle anderen Einstellungen auch.
Priority: low

**Comment by dergel** [comment]
Es geht hier um die Ausgabe als Select Felder. Es müsste noch überlegt werden, ob das entsprechend bei der Eingabe dargestellt werden soll.

**Comment by olien** [comment]
Fand ich schon wichtig. Da ich glaube, dass es viele User verwirrt.

**Comment by dergel** [comment]
wird auch gemacht .. in 4.1

**Comment by dergel** [comment]
Habe mich leider umentschieden. Das Feld soll wirklich nur für die Ausgabe sein. Die Verwirrung kommt daher, dass es vorher anders war. Bestimmte Ausgabeformate können auch nicht in die Selectausgaben umgewandelt werden. Sorry. Wenn ihr eine Idee für einen Umweg habt, bei dem etwas ergönzt werden muss, gerne. Im Notfall geht immer auch ein Ytemplate
