### ISSUE TITLE
Problem mit Validation emptyall

### ISSUE THREAD

**Issue by marcohanke** [yakamara/redaxo_yform#1197]
Nach dem Update auf die aktuelle beta-4.0.0.7 bekomme ich.
Declaration of rex_yform_validate_emptyall::getDescription() must be compatible with rex_yform_base_abstract::getDescription(): string
Wenn ich im Frontend die Validierung nutze

**Comment by christophboecker** [comment]
Ist das ein offizieller Validator im YForm-Lieferumfang oder kommt der aus dubiosen Quellen? :-)

**Comment by christophboecker** [comment]
Siehe auch hier: #1161 
In der Klasse `rex_yform_validate_emptyall` muss `function getDescription() {` auf `function getDescription(): string {` geändert werden.

**Comment by marcohanke** [comment]
Gut dass du's sagst, der ist tatsächlich dubios (von mir) ;-)

**Comment by alxndr-w** [comment]
siehe #1161
