### ISSUE TITLE
Problem mit Imagelist

### ISSUE THREAD

**Issue by marcohanke** [yakamara/redaxo_yform#1198]
Nachdem Update auf die 4.0.0-beta-7 bekomme ich beim Editieren von Feldern im Backen:

Declaration of rex_yform_value_imagelist::getDefinitions() must be compatible with rex_yform_base_abstract::getDefinitions(): array

**Comment by eaCe** [comment]
@marcohanke neuste Mform Version installiert?

-> https://github.com/FriendsOfREDAXO/mform/commit/21f0e4e3fb9eb0c5e3eaf939bbdd1e03de3867e5

**Comment by marcohanke** [comment]
Ich hatte imagelist auch zu mform verortet, ging aber bei rey_form_value davon aus dass es ein yform Value ist (hatte mich zwar gewundert aber hey ,-) ).
Tankeschön.

**Comment by alxndr-w** [comment]
Siehe #1161
