### ISSUE TITLE
Datepicker Frage: / Übernahme der Auswahl.

### ISSUE THREAD

**Issue by olien** [yakamara/redaxo_yform#1200]
Geht das nicht mehr?

```
$mform->addTextField(3, array(
    'label' => 'Startdatum',
    'data-yform-tools-datepicker' => 'DD.MM.YYYY',
    'data-yform-tools-inputmask' => 'DD.MM.YYYY'
));
```

Der Datepicker erscheint und es kann ein Datum ausgewählt werden. Es wird aber nichts ins Feld übernommen.

**Comment by dergel** [comment]
ist zwar datepicker - aber eigentlich mform.
Die Änderungen der Datepickeraufrufe sind hier zu sehen.

https://github.com/yakamara/redaxo_yform/blob/master/docs/08_tools.md
