### ISSUE TITLE
Table Manager: Button "Übernehmen" beim Datensatz-Anlegen ausblenden

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#121]
GitHub-Version.

Wenn ich einen neuen Datensatz anlege, sollte der Button "Übernehmen" ausgeblendet werden, da der Datensatz beim erneuten Übernehmen als 2. Datensatz gespeichert wird. Beim 2. Übernehmen landet man wieder in der Tabellenübersicht.

Korrektes Verhalten wäre, bei Übernehmen den gleichen Datensatz weiter zu bearbeiten.

![image](https://cloud.githubusercontent.com/assets/3855487/16901092/43a9b770-4c39-11e6-9fda-e56174a1d195.png)

Alternative Idee: Button "Speichern und nächsten Datensatz hinzufügen", um in der Eingabe-Maske zu bleiben.

**Comment by dergel** [comment]
die alternative idee finde ich sogar ziemlich cool..

wenn es auch eigentlich "nur" ein fehler ist, den man korrigieren sollte.

alternative oder korrigieren .. ich bin fast für die alternative .. was meint ihr @tbaddade @alexplusde @gharlan

**Comment by alexplusde** [comment]
thx :)
