### ISSUE TITLE
4.0.0 Array to String Conversion

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/redaxo_yform#1214]
![image](https://user-images.githubusercontent.com/3855487/147874228-6958299f-f6d9-4c6b-8b79-23a565180a7e.png)

**Comment by alxndr-w** [comment]
Ursache war das URL-Addon - was sich aus dieser Fehlermeldung jedoch nicht ablesbar war. Ein Update auf die aktuelle GitHub-Version löst das Problem.

**Comment by dergel** [comment]
Ich schaue mal, ob man das in YForm abfangen kann

**Comment by dergel** [comment]
Da ich das nicht nachvollziehen und nachbauen kann, kann ich hier doch nichts machen. Und da es eher zum URL AddOn gehört und ich nichts zum Abfangen sehe, schließe ich das Issue.
