### ISSUE TITLE
4.0.0 datetime-Felder: input type="datetime-local" als Eingabeformat unterstützen

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/redaxo_yform#1216]
Um ein input-Feld vom type "datetime-local" als Eingabefeld benutzen zu können, müsste YForm die Option bieten, das Value im Format `2018-06-12T19:30` zu übergeben.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local

**Comment by dergel** [comment]
Finde ich schwierig zu lösen. Weil letztendlich beisst sich das, wenn die Werte auch die Datenbank müssen und dort als datetime abgelegt werden sollen.

Vielleicht aber ein wenig mit Tricks:

Wenn keine Sekunden übergeben werden, könnten wir default 00 setzen. D.h. in der Datenbank wird trotzdem das mysql format genommen

Das T könnte man einfach herausfiltern und mit einem Leerzeichen ersetzen.

Ansonsten könnte man den type input:datetime-local ergänzen und in die Ausgabe des Wertes in diesem Fall fest formatieren.

Klingt nach einem gangbaren Weg, oder ?

@alxndr-w Kannst du schauen ob wir ähnliche Fälle für time oder date haben?

**Comment by alxndr-w** [comment]
Ich schaue es mir nochmal an - irgendwas hat mich daran gehindert, vielleicht hilft ein frischer Kopf...

**Comment by alxndr-w** [comment]
@dergel ich habe jetzt ein wenig besser den Aufbau der Values verstanden und einen PR dazu eingereicht. Ich denke, so ist es auch viel besser als den Lösungsweg, den ich zuerst wählen wollte.

Für time und date würde ich mich auch damit auseinandersetzen. Letztlich ist es ein komplexes Thema, wenn man YForm beibringen will, dass es nicht nur Datums- und Uhrzeitangaben gibt, sondern diese auch noch ortsabhängig sind.

**Comment by alxndr-w** [comment]
Ich möchte noch anmerken, dass aktuell einige Browser das Feld deswegen nicht richtig rendern und die Funktion zur Darstellung eines Kalenders flöten geht.

**Comment by AndiLeni** [comment]
>Finde ich schwierig zu lösen. Weil letztendlich beisst sich das, wenn die Werte auch die Datenbank müssen und dort als datetime abgelegt werden sollen.

Das verstehe ich nicht ganz, man kann ja den Datetime Wert einfach mit dem `T` darin abspeichern.
Also in der Form `YYYY-mm-ddTHH:MM:SS`.
Das normale `datetime` input Feld ist ja deprecated und stattdessen sollte immer datetime-local genutzt werden.
(https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime)

**Comment by alxndr-w** [comment]
https://github.com/alexplusde/yform_field/pull/10
