### ISSUE TITLE
Userberechtigungen

### ISSUE THREAD

**Issue by olien** [yakamara/redaxo_yform#1218]
Wenn ich nur bestimmte Tabellen auswähle sieht der User trotzdem alle Tabellen...

![image](https://user-images.githubusercontent.com/330516/148033508-cd79ed62-36f1-445f-b45f-c436435b4d47.png)

![image](https://user-images.githubusercontent.com/330516/148033539-4616ec2d-355e-48df-8995-64d393f775a6.png)

**Comment by dergel** [comment]
Ja, das liegt daran, dass deine eine Editiertabelle Verknüpfungen zu anderen hat und diese sichtbar sein müssen, damit man diese eine zu editierende Tabelle überhaupt nutzen kann. Stimmt schon so.

**Comment by olien** [comment]
ok. danke für die Erklärung!
