### ISSUE TITLE
Wunsch: YForm-Listen - Aktion-Menü wahlweise

### ISSUE THREAD

**Issue by olien** [yakamara/redaxo_yform#1219]
Wäre es möglich (bzw. viel Aufwand) bei der Taballeneigenschaften anzugeben ob die Tabelle das Aktions Menü erhalten soll oder nicht (= alte Darstellung)? Ich finde es sehr benutzerunfreundlich hier ein DropDown auszugeben und für editieren / löschen einen überflüssigen Klick zu haben... (Ich verstehe, das da noch "Historie" Platz findet und auch noch weitere Aktionen zugefügt werden können - trotzdem ist es mir ein Klick zuviel).

**Comment by alxndr-w** [comment]
Heute erst bin ich auf die Idee gekommen, dass man das vielleicht als YForm-Value löst. 

Du könntest dir also einen Editieren-Button selbst bauen und als Feld hinterlegen, das dann in der Liste ausgegeben wird.

Vielleicht gefällt dir aber auch der Trick aus der Doku, Beispiel 2:
https://github.com/yakamara/redaxo_yform/blob/76ff8e7d84beb26147040bd801bd119f7b80a2f1/docs/03_table_manager.md#table-manager-spalteninhalt-vor-anzeige-in-%C3%BCbersicht-%C3%A4ndern

Es verlinkt ein beliebiges Feld, z.B. Name/Titel mit der Editieransicht und ist damit noch besser zu erreichen, als wenn der Editier-Button ganz rechts ist.

**Comment by eaCe** [comment]
Das hatte ich auch schon angemerkt, darauf hat @tbaddade ein Hover auf dem Dropdown eingefügt.

**Comment by tbaddade** [comment]
@olien Über ein Klick auf das Icon in der ersten Spalte gelangst du auch zur Editansicht.

**Comment by alxndr-w** [comment]
@tbaddade nicht bei aktiviertem yform_usability d&d

**Comment by olien** [comment]
@tbaddade das mit dem Icon in der ersten Spalte ist selbstverständlich bekannt. Das yform_usability das überschreibt ist kein yform Problem :-)

Aber gerade weil es da ein Edit-Link gibt frage ich mich warum das nochmal redundant in ein Dorpdown gepackt wird? 

Ich gucke mr mal das an was @alxndr-w verlinkt hat. vielleicht kann ich mir "was eigenes" basteln...

**Comment by eaCe** [comment]
@olien du kannst das auch über ein eigenes Fragment lösen. Nicht schön, aber funktioniert...:

```php
rex_extension::register('YFORM_DATA_LIST_ACTION_BUTTONS', static function (rex_extension_point $ep) {
    $actionButtons = $ep->getSubject();

    rex_extension::register('YFORM_DATA_LIST', static function (rex_extension_point $ep) use ($actionButtons) {
        $list = $ep->getSubject();

        $list->setColumnFormat(rex_i18n::msg('yform_function') . ' ', 'custom', function( $params ) use ($actionButtons) {
            $fragment = new rex_fragment();
            $fragment->setVar('buttons', $actionButtons, false);
            $buttons = $fragment->parse('action_buttons.php');
            return $buttons;
        });

        $ep->setSubject($list);
    });
});
```

Fragment:

```php
<?php

/**
 * @var rex_fragment $this
 * @psalm-scope-this rex_fragment
 */

?>
<div>
    <ul class="list-inline">
        <?php
        foreach ($this->buttons ?? [] as $button) {
            echo '<li>'.$button.'</li>';
        }
        ?>
    </ul>
</div>
```

**Comment by olien** [comment]
danke

**Comment by olien** [comment]
das mit dem eigenen Fragment klappt prima. danke @eaCe
