### ISSUE TITLE
Table Manager: Feldeigenschaften von be_media/be_medialist vereinheitlichen

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#122]
In be_media fehlt

- Preview
- Medienpool-Kategorie
- Bildtypen

diese sind in be_medialist vorhanden (und auch in mediafile, upload)

in be_medialist fehlt
- Default-Wert

Wobei hier eine Vorbefüllung eher selten ist.

Ähnlich zu `<select>` wäre auch denkbar, beide Felder in eins einzudampfen und "Mehrfachauswahl möglich" als Option zu setzen. @dergel du meintest ja, prinzipiell sind dir das alles eh zu viele Felder.

**Comment by dergel** [comment]
finde ich eine gute idee.. warum 2 wenn es auch in eins geht ..

**Comment by dergel** [comment]
https://github.com/yakamara/redaxo_yform/commit/7395dc98075d28976489633f66fa251021c0f314

ist nun drin .. mit allen nachteilen die das mit sich zieht. Bei Updates muss man be_medialist entfernen und danach neu als be_media multiple anlegen

**Comment by alexplusde** [comment]
das Update kann nicht per SQL nach "be_medialist" suchen und diese DB-Einträge automatisch konvertieren?

**Comment by dergel** [comment]
Theoretisch ja, praktisch sind das, neben diesem Fall, zuviele weitere allgemeine Fälle, die man dann auch entsprechend einbauen müsste. Freue mich über Hilfe (nicht von dir, du machst ja mehr als genug), aber im Moment können wir das nicht leisten.

**Comment by dergel** [comment]
be_medialist wird bei einem update von version 1.0 beim manager gelöscht, d.h. das feld muss man dann neu definieren als be_media
