### ISSUE TITLE
Manager: Der Feldtyp be_media speichert keine Einträge sofern die Mehrfachauswahl ausgewählt wurde

### ISSUE THREAD

**Issue by olien** [yakamara/redaxo_yform#1220]
Vielleicht hilft der Woops der kommt sofern ich das Formular im Frontend ausgeben möchte:

**Error:** Call to a member function getComplexPerm() on null
**File:** redaxo/src/addons/mediapool/lib/var_medialist.php
**Line:** 81

<details>
<summary>Stacktrace</summary>

| Function                                     | File                                                                                | Line     |
| -------------------------------------------- | ----------------------------------------------------------------------------------- | -------- |
| rex_var_medialist::getWidget                 | redaxo/src/addons/yform/plugins/manager/ytemplates/bootstrap/value.be_media.tpl.php | 26       |
| include                                      | redaxo/src/addons/yform/lib/yform/value/abstract.php                                | 136      |
| rex_yform_value_abstract->parse              | redaxo/src/addons/yform/plugins/manager/lib/yform/value/be_media.php                | 38       |
| rex_yform_value_be_media->enterObject        | redaxo/src/addons/yform/lib/yform.php                                               | 354      |
| rex_yform->executeFields                     | redaxo/src/addons/yform/plugins/manager/lib/yform/manager/dataset.php               | 537      |
| rex_yform_manager_dataset->executeForm       | rex:///module/31/output                                                             | 7        |
| require                                      | redaxo/cache/addons/structure/1.1.content                                           | 94       |
| require                                      | redaxo/src/addons/structure/plugins/content/lib/article_content.php                 | 122      |
| rex_article_content->getArticle              | rex:///template/2                                                                   | 21       |
| require                                      | rex:///template/1                                                                   | 1        |
| require                                      | redaxo/src/addons/structure/plugins/content/lib/article_content_base.php            | 482      |
| rex_article_content_base->{closure}          | redaxo/src/core/lib/util/timer.php                                                  | 63       |
| rex_timer::measure                           | redaxo/src/addons/structure/plugins/content/lib/article_content_base.php            | 483      |
| rex_article_content_base->getArticleTemplate | redaxo/src/addons/structure/plugins/content/boot.php                                | 56       |
| rex_package::{closure}                       | redaxo/src/core/lib/extension.php                                                   | 52       |
| rex_extension::{closure}                     | redaxo/src/core/lib/util/timer.php                                                  | 63       |
| rex_timer::measure                           | redaxo/src/core/lib/extension.php                                                   | 63       |
| rex_extension::registerPoint                 | redaxo/src/addons/debug/lib/extensions/extension_debug.php                          | 21       |
| rex_extension_debug::registerPoint           | redaxo/src/core/lib/extension.php                                                   | 37       |
| rex_extension::registerPoint                 | redaxo/src/core/frontend.php                                                        | 26       |
| require                                      | redaxo/src/core/boot.php                                                            | 143      |
| require                                      | index.php                                                                           | 9        |

</details>
<details>
<summary>System report (REDAXO 5.13.1, PHP 7.4.21, MySQL 5.7.34)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.13.1     |

| PHP           |            |
| ------------: | :--------- |
|       Version | 7.4.21     |
|       OPcache | yes        |
|        Xdebug | no         |

| Database      |              |
| ------------: | :----------- |
|       Version | MySQL 5.7.34 |
| Character set | utf8mb4      |

| Server        |               |
| ------------: | :------------ |
|            OS | Darwin        |
|          SAPI | cgi-fcgi      |
|     Webserver | Apache/2.4.48 |

| Request       |             |
| ------------: | :---------- |
|       Browser | Safari/15.2 |
|      Protocol | HTTP/1.1    |
|         HTTPS | yes         |

| Packages                  |            |
| ------------------------: | :--------- |
|                   adminer | 1.9.2      |
|                    backup | 2.8.0      |
|               be_password | 2.0.0      |
|                  be_style | 3.0.0      |
|       be_style/customizer | 3.0.0      |
|           be_style/redaxo | 3.0.0      |
|                   bloecks | 3.1.1      |
|          bloecks/cutncopy | 3.1.1      |
|            bloecks/status | 3.1.1      |
|                cheatsheet | 0.0.1      |
|           consent_manager | 3.0.4      |
|                   cronjob | 2.8.1      |
|                     debug | 1.2.0      |
|                 developer | 3.9.0      |
|                focuspoint | 4.0.0      |
|                 gridblock | 1.0.1      |
| gridblock/contentsettings | 1.1        |
|    gridblock/synchronizer | 1.0        |
|               insert_text | 2.0.0      |
|                   install | 2.9.3      |
|               maintenance | 2.6.4      |
|                    mblock | 3.4.4      |
|             media_manager | 2.12.1     |
|                 mediapool | 2.11.1     |
|                  metainfo | 2.8.3      |
|                     mform | 6.1.2      |
|                mform/docs | 1.1        |
|             modulsammlung | 4.15.2     |
|                 phpmailer | 2.11.1     |
|                   project | dev        |
|           project_manager | 1.3.7      |
|    project_manager/client | 1.1.0      |
|          quick_navigation | 5.2.1      |
|                  redactor | 2.3.0      |
|                 search_it | 6.9.0      |
|    search_it/autocomplete | 6.9.0      |
|   search_it/documentation | 6.9.0      |
|       search_it/plaintext | 6.9.0      |
|           search_it/stats | 6.9.0      |
|                     sprog | 1.3.0      |
|                 structure | 2.13.1     |
|         structure/content | 2.13.1     |
|                     theme | 1.3.3      |
|                  uploader | 2.3.0      |
|                       url | 2.0.0-dev  |
|                     users | 2.8.2      |
|                     yform | 4.0.0      |
|               yform/email | 4.0.0      |
|             yform/manager | 4.0.0      |
|                yform/rest | 4.0.0      |
|               yform/tools | 4.0.0      |
|           yform_usability | 2          |
|                  yrewrite | 2.8.3      |

</details>

**Comment by tbaddade** [comment]
> Vielleicht hilft der Woops der kommt sofern ich das Formular im Frontend ausgeben möchte:

Die `be_` Values sind nicht für das Frontend gedacht. Ich würde hier das `upload` Value verwenden

**Comment by olien** [comment]
ok. Danke. war nur ein Test. Trotzdem Speichert das Feld im Backend keine Values...

**Comment by tbaddade** [comment]
> Trotzdem Speichert das Feld im Backend keine Values

Kann ich bestätigen. Liegt an dieser Zeile
https://github.com/yakamara/redaxo_yform/blob/master/plugins/manager/lib/yform/value/be_media.php#L18

Das Value ist ein kommaseparierter String, sodass `rex_media` hier nichts findet.

**Comment by olien** [comment]
danke!

**Comment by skerbis** [comment]
Getestet und kann ich bestätigen. Sehe keinen Fehler in der Konsole.

**Comment by alxndr-w** [comment]
Das Problem scheint es in den Release von YForm 4 geschafft zu haben, Kunde beschreibt dieses Verhalten. Werte waren kommasepariert vorhanden, bereits beim Öffnen des Datensatzes sind die Daten weg.

**Comment by alxndr-w** [comment]
Tatsächlich funktioniert der fix vom 5. Januar https://github.com/yakamara/redaxo_yform/commit/d252e5cb0f031e5731c063fa818eccca03473b18
