### ISSUE TITLE
Bing back the mediafile value 

### ISSUE THREAD

**Issue by skerbis** [yakamara/redaxo_yform#1225]
**huhu ... dass das mediafile Feld weg ist, ist nicht wirklich gut.** 
Ich nutze es sehr häufig und stelle damit so einige Dinge an. Ich brauche die Medien unbedingt im Medienpool. 

**Verwendungszweck:** 
Externe Fotografen liefern Fotos für die Online Redaktion nach YCOM-Login. 
Die Redakteure müssen mit den Dateien weiterarbeiten. 

Ich passe dabei die Upload-Kategorie dynamisch an, so dass die Redakteure die neuen Fotos an der richtigen Stelle finden. 
@dergel

**Comment by eaCe** [comment]
https://github.com/yakamara/redaxo_yform/issues/1069#event-5756719892

**Comment by skerbis** [comment]
Falls erwünscht kann ich's auch als AddOn neu realisieren.

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/yform_mediafile

**Comment by alxndr-w** [comment]
mediafile ist m.E. für die Tonne. 

Wäre die Energie nicht besser darin aufgehoben, das Thema 

* Upload/Multiupload 
* aus Frontend/Backend in 
* Medienpool/ohne Medienpool 
* mit/ohne Drag&Drop

final zu lösen? Mit uppy und dropzone hatten wir ja schon mal 2 unterschiedliche Ansätze gestartet.

**Comment by skerbis** [comment]
@alxndr-w ich habe das Value als AddOn zurück zu FOR gebracht. Grund dafür ist dass es eben nicht für die Tonne ist und für meine Zwecke genau das bietet was ich brauche. Kontrollierte Einzeluploads. Die Pflichtfeldproblematik habe ich für mich anders gelöst. Kein Bild im Datensatz heißt der Datensatz wird nicht ausgespielt. 
Aber klar es ist nicht optimal, aber das Medium kann weiterhin im Medienpool nach Upload durch die Chef-Redaktion bearbeitet (z.B. Focuspoint) und freigegeben werden. Das Upload-Feld liefert mir diese Möglichkeit eben nicht. 

Dass aus Uppy und dropzone nicht weiterentwickelt wurden liegt daran, dass sich keiner den Projekten angeschlossen hat. 
Der Bedarf scheint wohl nicht vorzuliegen. Schade eigentlich. Uppy z.B. hätte alle Uploads in REDAXO vollständig ersetzen können.

**Comment by tbaddade** [comment]
Ich bin da bei @alxndr-w und finde du handelst hier überstürzt. Du weißt nicht, was alles mit dem upload Value passieren wird. Das es nicht so bleiben wird und auch Handlungsbedarf besteht ist bekannt.

> Das Upload-Feld liefert mir diese Möglichkeit eben nicht.

Ich wünsche mir, dass für die upload-Dateien eine Art separater Medienpool entsteht. Sodass der Redakteur auch die Medien im Backend betrachten kann, ohne erst in den Datensatz gehen und dieses herunterladen zu müssen.

**Comment by skerbis** [comment]
Ich werde die Beschreibung anpassen und darauf hinweisen. Ich bin sicher nicht der Einzige der vor dem Problem steht, dass das Feld plötzlich weg ist und es aktuell keinen Ersatz dafür gibt. So wie du. Die können sich zumindest bis das Problem gelöst ist weiterhin das Value ziehen. Haben wir ja auch mit dem Captcha so gemacht.
