### ISSUE TITLE
E-mail Validierung unzureichend

### ISSUE THREAD

**Issue by abra100pro** [yakamara/redaxo_yform#1226]
Hallo
Die E-Mail-Feldvalidierung im Formbuilder-Modul scheint nur das @ zu prüfen - eine "E-Mail"-Adresse name@domainohnetld ist somit gültig. der Punkt in der Domain sollte IMHO auch geprüft werden.

**Comment by alxndr-w** [comment]
duplicate #920 

Die Validierung ist korrekt und entspricht dem `RFC822`-Standard für E-Mail-Adressen. `example@local` ist eine gültige E-Mail-Adresse.

**Comment by olien** [comment]
Hi @abra100pro vielleicht magst du zu uns in den Slack Channel kommen? Dort gibt es auch fast immer schnell und kompetent Antworten. Gerne können wir auch mal telefonieren und n Screensharing machen. Sind ja recht viele Baustellen die bei dir offen sind. (ich bin zwar nicht der Super-Experte; hab aber schonmal mit REDAXO gearbeitet)

Slack: https://redaxo.org/slack/

**Comment by abra100pro** [comment]
Hi @olien Danke - ich habe Slack reaktiviert - gute Idee!
Ich habe eine Testinstallation auf MAMP, um wieder mal dies und jenes azuszuprobieren - von dem her macht's Spass, ist aber nicht kritisch. :-) danke aber vielmals für dein Angebot.
