### ISSUE TITLE
tpl2email :: Actionnamen überdenken

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#123]
Verwirrt mich grad und sagt nichts aus, was mit den eingegebenen Daten passiert.

**Comment by alexplusde** [comment]
Schnappt sich die Daten aus dem Formular, holt sich ein E-Mail-Template aus dem E-Mail-Templates-Manager und sendet das ganze als E-Mail. Oder nicht? Gibt doch jetzt 'ne Doku :'D

**Comment by dergel** [comment]
ein template (email) wird als email rausgeschickt .. ich denke das ist ok ..

**Comment by tbaddade** [comment]
Dann bräuchten wir noch ne Action inputData2tpl :) … Ich finde den Namen nach wie vor unpassend.

**Comment by alexplusde** [comment]
Was wäre denn dein Vorschlag?
