### ISSUE TITLE
Problem mit Validierung eines date-Feldes

### ISSUE THREAD

**Issue by fietstouring** [yakamara/redaxo_yform#1234]
Habe Probleme damit ein date-Feld als Select zu validieren. Als Ausgabeformat wurde YYYY gewählt. Die Option-Values sind also Jahreszahlen vierstellig. Die erste Option also quasi "keine Auswahl" ist "--" und der Value ist "00".

Size funktioniert nicht und auch mit preg_match validiert es nicht.

Oder habe ich einen Denkfehler?

**Comment by eaCe** [comment]
@fietstouring ich meine das ist korrekt. --/00 steht für keine Auswahl. Wenn du "Aktuelles Datum voreingestellt" wird dir immer das aktuelle Jahr ausgegeben. Wenn du ein date-Feld nutzt wird dir ein Format wie "2022-01-21" erzeugt.

**Comment by fietstouring** [comment]
ok aber wie kann ich validieren dass in dem Select auch was ausgewählt wurde?

**Comment by alxndr-w** [comment]
Aus dem Gedächtnis heraus, ob es nicht den Wert "0000-00-00 00:00:00" hat, über `compare`.

**Comment by fietstouring** [comment]
`compare_value` funktioniert leider nicht mit diesem Wert.

Hier ein Screenshot von dem Auswahlfeld. Ich möchte nicht das aktuelle Jahr voreingestellt haben. Hier sind Jahreszahlen von 1950 bis 2050 drin, es handelt sich um das Entstehungsjahr von Kunstwerken. Ein Jahr muss zwingend ausgewählt werden in dem Formular.  Vielleicht weiß wer was! Danke

![Bildschirmfoto 2022-01-26 um 10 28 38](https://user-images.githubusercontent.com/1846849/151141072-e8810ed6-1063-4573-9df7-860c10463f86.png)

**Comment by eaCe** [comment]
@fietstouring kannst du die Felddefinition deines Date-Feldes mal posten?

**Comment by fietstouring** [comment]
`$yform->setValueField('date', ['purchase_date','translate:aw_purchase_date','1990','2050','YYYY','0','0','select','{"class":"selectpicker"}']);`

**Comment by tbaddade** [comment]
Welche YForm Version nutzt du?


Falls es die 4er sein sollte dann wird derzeit im Backend immer auch der Monat und der Tag ausgegeben.

Siehe Screenshot
<img width="673" alt="Bildschirmfoto 2022-01-26 um 11 07 09" src="https://user-images.githubusercontent.com/338267/151143782-0f355d20-55e9-4609-82a3-021de8d92409.png">

**Comment by fietstouring** [comment]
ist noch die 3.4.2

**Comment by eaCe** [comment]
@fietstouring `compare_value` == 0000-00-00

**Comment by fietstouring** [comment]
@eaCe Danke! You made my day!
