### ISSUE TITLE
Validate - type. Erzeugt ungewollte Ausgabe

### ISSUE THREAD

**Issue by olien** [yakamara/redaxo_yform#1235]
Hi wenn ich das im Formularmodul nutze wird "der Typ"? im frontend ausgegeben:

`validate|email|email|{{ Bitte geben Sie die E-Mail Adresse an. }}`

![image](https://user-images.githubusercontent.com/330516/150519999-15b809e9-77f2-4f5d-84e7-e3fe8e1f6971.png)

Das passiert auch mit anderen Typen 

YFORM 4.0.0
(YCOM 4.0.6)

**Comment by tbaddade** [comment]
Die E-Mail-Validierung gibt es nicht mehr und du willst auch `type` nutzen. Das fehlt nur an zweiter Stelle deines Pipe.

```
validate|type|email|email|{{ Bitte geben Sie die E-Mail Adresse an. }}
```

**Comment by olien** [comment]
Ah. dann habe ich das schlicht falsch verstanden. bin grad an 8 Baustellen... danke
