### ISSUE TITLE
E-Mail Versand von Choice Values mit " und , funktioniert nicht

### ISSUE THREAD

**Issue by marcohanke** [yakamara/redaxo_yform#1236]
Wenn ich Dinge wie , " oder ½ in ein choice packe, wird das im Frontend zwar ordentlichangezeigt, beim E-Mail Versand ist das Value aber leer.

$yform->setValueField('choice', ['repairFlat','{{formClaim.repairFlat}}','{"44,50":"44,50","55,55":"55,55"}','0','0','','','','{{choose}}','','','','','1']);

**Comment by eaCe** [comment]
Siehe -> #865

**Comment by alxndr-w** [comment]
Das hat nichts mit dem E-Mail-Versand zu tun, sondern es geht rein um das Sanitizing der Eingabe. Ich schlage vor, hier zu schließen und in #865 weiterzumachen.
