### ISSUE TITLE
Problem mit Passwort Feld (ycom_auth_password)

### ISSUE THREAD

**Issue by marcohanke** [yakamara/redaxo_yform#124]
Nach dem Update auf die aktuelle Version wird in der Tabelle ycom_user im Feld: ycom_auth_password nicht mehr der Platzhalter (Passwort exisitiert) sondern ein neues langes Passwort (vermutlich der Hash-Wert) angezeigt. Beim editieren eines Benutzers wird das Passwort damit überschrieben und der User kann sich nicht mehr anmelden.
Ich habe verschiedene Versionen durchgetestet. Es liegt definitiv an der aktuellen yform.

**Comment by alexplusde** [comment]
@marcohanke 

Offtopic:
danke, dass du dich beteiligst. Ich verwalte den Bereich "Table Manager" in der YForm-Doku.

Da ich das Community-Addon noch nie aktiv benutzt habe, weiß ich nicht, wie das Feld funktioniert und was man da einstellen kann. Falls du Anregungen zu diesem Abschnitt in der YForm-Doku hast
https://github.com/yakamara/redaxo_yform_docs/blob/master/de_de/table_manager_feldtypen.md#ycom_auth_password, dann würde ich mich sehr über ein Issue in der redaxo_yform_docs-Repo oder einen PR zu diesem Abschnitt freuen.

Ich hoffe, dein Problem wird schnell gelöst sein.

**Comment by marcohanke** [comment]
@alexplusde Ich würde ja gerne helfen, aber ich kämpfe mich gerade selber das erste mal durch die Community ;-)

**Comment by dergel** [comment]
das Feld ycom_auth_password ist ja von ycom .. ich denke das dort die überprüfung nicht richtig läuft, d.h. dass nicht erkannt wird, dass das Passwort bereits eincrypted ist.. kannst du es dort reinlegen.. hat nichts mit yform zu tun ..

**Comment by marcohanke** [comment]
Hallo Jan, der Fehler tritt wie gesagt erst bei einem Update von yform auf. Die gleiche ycom Installation mit der Vorversion von yform funktioniert problemlos.

**Comment by dergel** [comment]
d.h. du hast nicht diese github version hier im Einsatz ? .. Kannst du das damit prüfen ? Also dieses Paket nehmen https://github.com/yakamara/redaxo_yform/archive/master.zip 
entpacken und yform nennen. und dein aktuelles yform im redaxo/src/addons ersetzen. ist es dann immernoch so ?

**Comment by marcohanke** [comment]
Ich habe die Version aus dem Installer, keine Ahnung ob das eine andere ist …

**Comment by dergel** [comment]
es gibt wieder ein update .. version 1.1beta1.. oder du nimmst hier diese version (ist noch kein release) und installierst die wie oben beschrieben. ich brauche einen test immer in der aktuellsten entwicklerversion..

**Comment by marcohanke** [comment]
OK, schau ich mir morgen an.

**Comment by skerbis** [comment]
https://github.com/yakamara/redaxo_ycom/issues/95
