### ISSUE TITLE
yform submit CSS Klassen

### ISSUE THREAD

**Issue by marcohanke** [yakamara/redaxo_yform#1242]
Wenn ich das richtig sehe, sollten die CSS Klassen NICHT kommasepariert sein.
Wenn das jemand nachvollziehen kann mach ich nen PR.
getDescription() in der submit.php
sowie lang Dateien
?

**Comment by dergel** [comment]
kappiere ich leider gar nicht. kannst du die Stellen markieren um welche es sich dreht?

**Comment by tbaddade** [comment]
> kappiere ich leider gar nicht

@dergel Marco meint sicherlich, dass die CSS-Klassen anscheinend nicht kommasepariert angegeben werden müssen und sich das mit der Beschreibung widerspricht.

@marcohanke Das ist aber nicht so. siehe hier
https://github.com/yakamara/redaxo_yform/blob/master/ytemplates/bootstrap/value.submit.tpl.php#L12

Wobei du auch sicherlich die Klassen mit Leerzeichen getrennt angeben kannst.

**Comment by marcohanke** [comment]
Okay, dann Haken dran. Ich hatte irgendwann kommaseparierte klassen und es hatte nicht funktioniert. Kann es aber auch nicht mehr nachvollziehen und der Code oben sieht ja danach aus als müsste es passen.
