### ISSUE TITLE
nicht benötigte Vendor-Assets entfernen

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/redaxo_yform#1245]
Bei langsamen Übertragungswegen wie FTP stören die docs und andere Assets von Vendoren - lassen sich diese bereits hier im Repo wegfiltern? Oder müssen diese immer vollständig mit ausgeliefert werden?

**Comment by dergel** [comment]
diese docs und die vielen unnötigen Dateien der Bibliotheken müssten eigentlich nicht mitgeliefert werden. Wir können das nur nicht rausfiltern und richtiger wäre es, gar nichts zu übertragen und composer dann auf dem server auszuführen und die Pakete zu laden. Deswegen kann ich nur antworten, dass wir das nicht ändern können und wenn redaxo irgendwie schlau mit composer umgeht, dann läuft das auch mit yform besser.

**Comment by alxndr-w** [comment]
Danke für die Erläuterungen! Dann filter ich das zukünftig mittels .gitignore raus.

**Comment by christophboecker** [comment]
Wenn ich das Git-Gedöns richtig verstehe, steuert `.gitignore`, was ins Repository geschoben wird. Man kann, wie ich gelernt habe, auch steuern, was NICHT aus dem Repo in die ZIP bzw. das Release wandert. Hier mal ein Beispiel, das Dateien und Verzeichnisse bei "[Geolocation](https://github.com/FriendsOfREDAXO/geolocation/blob/1c58c100f178f0feaf28576de208c6cf5e0b0979/.gitattributes#L9-L18)" mittels `.gitattributes` rauswirft:

```
# aus vendor/mjaschen/phpgeo nur den notwendigen Teil in das Release übernehmen.
vendor/mjaschen/phpgeo/docs/ export-ignore
vendor/mjaschen/phpgeo/tests/ export-ignore
vendor/mjaschen/phpgeo/Makefile export-ignore
vendor/mjaschen/phpgeo/composer.json export-ignore
vendor/mjaschen/phpgeo/phive.xml export-ignore
vendor/mjaschen/phpgeo/phpcs.xml.dist export-ignore
vendor/mjaschen/phpgeo/phpdox.xml export-ignore
vendor/mjaschen/phpgeo/phpunit.xml export-ignore
vendor/mjaschen/phpgeo/psalm.xml  export-ignore
```
