### ISSUE TITLE
Problem bei Dateiupload aus Backend (mediafile)

### ISSUE THREAD

**Issue by marcohanke** [yakamara/redaxo_yform#125]
Ich habe ein DB Feld für ein UploadFile angelegt:
![db feld](https://cloud.githubusercontent.com/assets/2425981/17183224/e6ca21c0-5426-11e6-8c80-de10ff1ef341.png)

Wenn ich im Backend ein Bild hochladen möchte bekomme ich folgenden Fehler:

Warning: copy(/tmp/phpNR136o): failed to open stream: Datei oder Verzeichnis nicht gefunden in /kunden/362991_36039/webseiten/idwb/www.ida-worldwide.com/redaxo/src/addons/yform/lib/yform/value/mediafile.php on line 194

**Comment by dergel** [comment]
seltsam.. das klingt eher nach einem serverproblem. Der Server versucht die hochgeladene Datei zu finden und kann es nicht .. Kannst Du das auf einem anderen Server nochmal gegenprüfen ?

**Comment by dergel** [comment]
sofern es dort dann klappt - bitte das issue hier schliessen

**Comment by dergel** [comment]
problem erkannst. "Irgendwie" wird das im Backend 2 mal ausgeführt. Wird noch korrigiert

**Comment by dergel** [comment]
mediafile wird in upload integriert werden. https://github.com/yakamara/redaxo_yform/issues/115
