### ISSUE TITLE
Neue Methode `setHtmlField($html)` als Shortcut zu `$yform->setValueField('html', [$field,$label,$html]);`

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/redaxo_yform#1250]
https://github.com/yakamara/redaxo_yform/blob/220c26d0d096514f9a9afd5c25121e3998a82f09/lib/yform.php#L188-L194

Ich würde mir wünschen, dass HTML-Felder kürzer definiert werden können zwischen Value-Feldern. Es braucht auch imho nur einen Parameter - nämlich den HTML-Code.

Gerade bei komplexen Formular-Modulen wäre mehr Übersicht gewahrt zwischen Feldern und Markup.

**Comment by tbaddade** [comment]
Wären dann nicht auch Methoden wie `addChoiceField`, `addTextField` etc. wie bei `rex_form` sinnvoll?

**Comment by alxndr-w** [comment]
@tbaddade ich hätte eher argumentiert, ob es ein "speicherbarer"/dynamischer/anpassbarer Wert (Value) ist - HTML-Felder sind ja rein für die Darstellung/Ausgabe und implizieren, dass niemand bei einem Formularversand die Werte verändert.

**Comment by dergel** [comment]
es wird eher in diese Richtung gehen

`setField(new HtmlField('<mein html code'));`

da ich versuche, von den verschiedensten speziellen Funktionen und Eigenschaften bei YForm wegzukommen, wird es das setHtmlField so nicht geben.
