### ISSUE TITLE
Values werden verkürzt ausgegeben (be_relations)

### ISSUE THREAD

**Issue by olien** [yakamara/redaxo_yform#1259]
![image](https://user-images.githubusercontent.com/330516/159861623-649efd1a-d7e9-4ed5-a899-aa5fde130ee2.png)
(Es liegt nicht am selectpicker)

![image](https://user-images.githubusercontent.com/330516/159861692-67f661ad-3d6d-405c-b3d0-b119d767fe12.png)

**Comment by olien** [comment]
Der Title wird komplett ausgegeben ...

![image](https://user-images.githubusercontent.com/330516/159861991-d0ea5ff8-4af6-4986-a023-aa2c2336d575.png)

**Comment by alxndr-w** [comment]
Dein Code-Screenshot zeigt nicht den Code vom selectpicker oder der Datentabelle.

**Comment by olien** [comment]
![image](https://user-images.githubusercontent.com/330516/159904479-7be92eec-db54-4a93-ab7e-ffdae078b60f.png)

**Comment by olien** [comment]
so ist es in der Übersicht. das ist leider an vielen Stellen

**Comment by alxndr-w** [comment]
Was ist der Use Case, dass man es anders braucht?

**Comment by olien** [comment]
Kannst du im ersten screen ID 5 und 6 unterscheiden?
Wie stelle ich mir das vor? Einfach nicht kürzen bitte…

**Comment by olien** [comment]
Oh. Die sind unterscheidbar ;-).
Es gab aber einige Daten wo das nicht so war… sehr verwirrend. U d das Feedback von Kunden als Bild… (wusste das das kommt)

(![Image](https://i.imgur.com/do0RSl7.jpg))

**Comment by olien** [comment]
> Also im select kann man ja das gewünschte Produkt als Begriff eingeben und das sollte auch den Inhalt komplett, durchsuchen.

Ich glaub das ging eben nicht weshalb ich zu "Multiple (Popup)" gewechselt bin. Hier werden die Values wenigstens nicht abgeschnitten.Auch nicht in dem Popup.

In einer Tabelle dann aber schon. Auch wenn genügend Platz für die Ausgabe vorhanden ist.

Nach meinen Gefühle entfernt sich REDAXO in der letzten Zeit immer weiter weg von **einfach** (die Ausgabe Daten werden vom System nicht geändert) und **flexibel** (mit einer Checkbox am Feld / an der Tabelle kann die Ausgabe beeinflusst werden). Ob das **sinnvoll** ist Daten die erwartet sind einfach zu ändern wurde ja schon entschieden...

> Bei der Datentabelle kannst du über einen EP die Darstellung beeinflussen.

1. Ja. Und wie? 
2. Wäre es nicht mehr REDAXO Like wenn der Entwickler die Daten kürzt (via EP, CSS, JS wie auch immer) als die ungewöhnliche Vorgabe vom System wieder zu fixen?

**Comment by olien** [comment]
@christophboecker Danke. Klar mag das gehen. Trotzdem ist es gefühlt "nicht REDAXO". Normalerweise zeigt REDAXO immer wie man etwas machen kann und macht nicht einfach...

**Comment by christophboecker** [comment]
Bedingte Zustimmung, Oliver. Der "Problembär" ist eher YForm und nicht REDAXO. Das Ding ist sowas von komplex ...

**Comment by olien** [comment]
Ja. Klar. Das yForm nicht "REDAXO" ist ist mir auch bewusst. Trotzdem gibt es gefühlt in der letzten Zeit viele Baustellen die das (Berufs)-Leben nicht leichter machen und frustrieren :-(

**Comment by christophboecker** [comment]
Der Sprung auf R5.13 war schon groß, und der auf YForm 4 war richtig heftig.

**Comment by olien** [comment]
Ja. Lass uns hier schliessen. Danke an alle!

**Comment by tbaddade** [comment]
> Lass uns hier schliessen.

Würde ich nicht machen … Ich finde die Diskussion hilfreich um hier Erwartungen und Erfahrungen einzusammeln.

**Comment by olien** [comment]
Ok. Dann  meine Erwartungen :-)

Es hat mich echt überrascht, dass hier so etwas passiert. Sonst ist der Entwickler ja dafür zuständig wenn etwas "ausserhalb der norm" passieren soll.

Erwartet habe ich : Nichts. Keine Änderung. :-)

Wenn die Kürzung als Feature gewünscht sollte es auch ein "zuschaltbaren" (wie auch immer) Feature sein.
Ansonsten sehe ich es als Aufgabe des Entwicklers eine Kürzung einzubauen... oder nicht? 

Ist doch bei allen anderen Sachen auch so. Du willst eine Extrawurst? Bau Dir eine. REDAXO lässt das zu :-))

So.  Gruß und Kuss
Dein Julius

(Meine Erfahrung: Sofort nachdem der Kunde das gesehen hat hat er gefragt ob das abstellbar ist...)

_Wenn mir jemand sagt wo genau ich was alles anfassen mag kann ich auch gerne mithelfen das zu ändern. falls überhaupt ne Änderung gewünscht ist ..._

**Comment by christophboecker** [comment]
Das Feature ist - zumindest die Datentabelle betreffend - etwas älter. Das gab es schon im 3er-YForm. Für mich war die Lösung wie oben beschrieben. Dort wo es mich störte oder wo ich einen anderen Schwellwert wollte, hab ich einfach die Spalte umkonfiguriert.

**Comment by olien** [comment]
Doof, ich muss das jetzt irgendwie überall abschalten wo es genutzt wird. In einigen Tabellen und in einigen selects… werde gucken ob ich alle stellen in yform finde und dann nie wieder Updaten ;-(

**Comment by alxndr-w** [comment]
@olien oder machs richtig und updatesicher.

**Comment by olien** [comment]
Leider weiß ich nicht wie. Ja. Mit nem EP. Hilft mir grad nicht ;-(

**Comment by olien** [comment]
So. Damit der Kunde jetzt arbeite kann habe ich die Dateien

yform/plugins/manager/lib/var_yform_dataset.php (Zeile 57 u. 70)

und

yform/plugins/manager/lib/value/yform/value/be_manager_relation.php (Zeile 128-130)

Angepasst. Letzteres musste ich sehr suchen :-))

**Comment by olien** [comment]
In der Datei yform/lib/yform/value/text.php hab ich noch Zeile 116 angepasst

**Comment by dergel** [comment]
und die listValues haben auch Einfluss auf die Historie. Dort kann man die Texte dann schlecht vergleichen.

Ich überdenke das noch mal.

**Comment by olien** [comment]
Danke sehr!

**Comment by olien** [comment]
Lösung von Robert:

`\rex_extension::register('YFORM_DATA_LIST', function (\rex_extension_point $ep) {
    /** @var \rex_list $list */
    $list = $ep->getSubject();

    if (rex_get('rex_yform_manager_opener', 'bool')) {
        return $list;
    }

    switch ($ep->getParam('table')->getTableName()) {
        case \rex::getTable('TABLE_NAME'):
            $list->setColumnFormat('COLUMN_NAME', 'custom', function ($params) {
                return $params['value'];
            });
            break;
    }

    return $list;
});`
