### ISSUE TITLE
Table Manager: Notizfeld unter label, aber vor input nehmen.

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#126]
Aktuell:

![image](https://cloud.githubusercontent.com/assets/3855487/17244457/39e4d9e8-5582-11e6-92f8-ec61ef279a35.png)

Wunsch:

![image](https://cloud.githubusercontent.com/assets/3855487/17244482/627fbd28-5582-11e6-91b2-b561b5fc01fa.png)

In meinen Augen wird dann deutlicher, worauf sich die Notiz bezieht - nämlich nicht auf das nachfolgende Feld.

**Comment by tbaddade** [comment]
Du solltest ein besseres Label verwenden. Für mich sieht das jetzt eher nach einer Doppelung von `<label>` aus und du könntest das tatsächliche `<label>` auch entfernen.

**Comment by alexplusde** [comment]
Aber genau für solche Instruktionen wurde doch das neue Notizfeld von Jan eingeführt, oder?

**Comment by tbaddade** [comment]
> das neue Notizfeld

Das Feld gibt es schon recht lang. Und schau mal wo bei bootstrap der `help-block` ausgegeben wird. Daran haben wir uns orientiert. Wenn du das Notizfeld weiter oben haben magst, müsstest du dir ein eigenes Template schreiben.

**Comment by alexplusde** [comment]
17 Tage sind jetzt nicht gerade "recht lang" ;)
https://github.com/yakamara/redaxo_yform/commit/f8b2c4da7085648cf9eb032f009311ed1f03fcb9
https://github.com/yakamara/redaxo_yform/commit/fa42295cb94fbc43f93c8ecb0d65f0ae9d5efefd

In 19 Feldtypen gibt's die erst seit 1.1

Aber du hast recht, in Bootstrap wird das auch von Haus aus so gemacht

![image](https://cloud.githubusercontent.com/assets/3855487/17248540/80ee2600-559b-11e6-9cd9-008894aed5d8.png)

Was bleibt, ist der Eindruck, dass die Zugehörigkeit irgendwie deutlicher sein könnte.

Ein anderes (längeres) Label kommt nicht infrage, weil das in der Übersicht einer Tabelle als Kopfzeile angezeigt würde.

**Comment by tbaddade** [comment]
> 17 Tage sind jetzt nicht gerade "recht lang" ;)
Das ist bereits seit xForm dabei, wurde nur nicht konsequent durchgezogen. Ich schließe das Issue, wenn du es anders benötigst, einfach ein eigenes Template anlegen.
