### ISSUE TITLE
EP YFORM_DATA_LIST_LINKS nicht erreichbar, wenn Benutzer kein Editierrecht besitzt

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#1262]
Habe via EP einen Button für ein ExcelExport dort untergebracht.

Da der Redakteur aber derzeit kein Editierrecht an der Tabelle hat, kann er diesen Export-Button nicht nutzen.

Ideen:
1. Den EP außerhalb der [Abfrage hier](https://github.com/yakamara/redaxo_yform/blob/bb7ff2c691ce83b17c641d3766c6420fdb233e3f/plugins/manager/lib/yform/manager.php#L676) registrieren oder
2. einen weiteren EP registrieren, der die Optionen oben rechts beeinflussen kann.

_Project: 523_

**Comment by dergel** [comment]
hiermit erledigt https://github.com/yakamara/redaxo_yform/commit/3445138b54138b76f9a0b7fb1df4162d039b9a25
