### ISSUE TITLE
Nach Update auf 4.x wird Update wieder angeboten

### ISSUE THREAD

**Issue by TobiasKrais** [yakamara/redaxo_yform#1266]
Das Update kann immer wieder wiederholt werden, bis der Redaxo Cache gelöscht wird. Erst dann zeigt der Installer das Update nicht mehr an.

**Comment by alxndr-w** [comment]
Ist das nicht ein Installer-Thema?

**Comment by TobiasKrais** [comment]
Hab ich auch schon gedacht. Fehler tritt aber nur bei YForm auf. Demnach vermute ich ein Problem im Update Skript des Addons.

**Comment by alxndr-w** [comment]
Ich kann das Problem in keiner meiner Installationen bestätigen.

**Comment by alxndr-w** [comment]
Das hatte ich mit einem anderen Addon jetzt auch. Das ist glaube ich kein YForm-Thema.
