### ISSUE TITLE
showtext - Wenn leerer String übergeben wird, verhält sich das Formular wie bei einem Neuaufruf

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/redaxo_yform#1267]
Wenn `showtext` eingesetzt wird, aber die Meldung leer ist, wird keine Erfolgsmeldung ausgegeben und das Formular wieder angezeigt, als wäre nichts passiert. Es wird aber auch keine Fehlermeldung ausgegeben. Innerhalb von `showtext` müsste man dafür sorgen, dass auf jeden Fall ein leerer String nicht zu einem Abbruch des Formulars führt.

Problem aufgetreten bei:

```php
$yform->setActionField('showtext', array($this->getCurrentSlice()->getValue(1), '<div class="alert alert-success">', '</div>', "1"));
```

übergangsweise gelöst durch

```php
$yform->setActionField('showtext', array($this->getCurrentSlice()->getValue(1) ?? "Vielen Dank!", '<div class="alert alert-success">', '</div>', "1"));
```

**Comment by dergel** [comment]
Ich kann das leider nicht nachvollziehen. Bei mir kommt immer eine Ausgabe. Im Code der showtext Klasse sehe ich auch keine entsprechende Einschränkung. Kannst du mir das noch mal erklären und bei dir schauen?
