### ISSUE TITLE
PHP-Versionsabgleich fehlerhaft -> Update nicht möglich

### ISSUE THREAD

**Issue by schorschy** [yakamara/redaxo_yform#1272]
``AddOn yform konnte aus folgendem Grund nicht aktualisiert werden:
Die PHP-Version (8.1.5) entspricht nicht der geforderten Versionsbedingung ^7.0!``

**Comment by alxndr-w** [comment]
@schorschy was ist daran verkehrt? Wurde evtl. noch nicht für PHP8 getestet / freigegeben

**Comment by schorschy** [comment]
Ah bedeutet das Vergleichssymbol dann quasi Version 7.x sind alle möglich aber eben >6 und <8 ? Ich dachte einfach größer als 7.0 ^^
Und nur aus Interesse: Deine Seiten laufen dann alle noch mit PHP 7.4 oder eben ohne yForm? @alxndr-w

**Comment by alxndr-w** [comment]
Genau, das bedeutet "aufwärts 7.x", deswegen das Dächlein / Pfeil nach oben.

Die laufen allesamt noch auf PHP 7.4 - lokal aber bereits auf 8.1 und bei meinen Projekten auch ohne, dass ich Fehler erkennen könnte, wobei ich natürlich nur Bestandteile von YForm nutze.

Insofern wäre ein Issue "PHP-8-Kompatibilität" natürlich trotzdem passend, nur eben nicht die Annahme, der Versionsabgleich wäre falsch. :)

**Comment by alxndr-w** [comment]
Gerade nochmal nachgesehen - YForm 4.0.2 ist doch PHP8-kompatibel und lässt sich installieren: https://github.com/yakamara/redaxo_yform/blob/b51a3593310b7a3951fb4e578ac3b82292d0dd9f/package.yml#L29
