### ISSUE TITLE
Update läuft nicht durch

### ISSUE THREAD

**Issue by PatrickG** [yakamara/redaxo_yform#1274]
Beim Versuch von Version 4.0.0 auf 4.0.1 oder 4.0.2 zu updaten wird eine Exception geworfen.
```
/[...]/redaxo/src/addons/.new.yform/plugins/manager/install.php
Arguments
"Class "rex_yform_manager_field" not found"```

**Comment by eaCe** [comment]
@PatrickG wenn du es lösen konntest, kannst du die Lösung bitte hier notieren. Das wäre hilfreich für die Zukunft.

**Comment by tyrant88** [comment]
Den Fehler hatte ich eben auch, weil ich yform deaktivert hatte, um das core update machen zu können und die Versionprüfung ^7.0 zu umgehen. 
Ist yform deaktivert, dann wird beim Update eben die Klasse rex_yform_manager_field nicht gefunden.
Also habe ich die package.yml auf >=7.0 geändert, yform aktiviert und dann geht das Update.
