### ISSUE TITLE
neue Methode für rex_yform_value_abstract :: getObjectByName($name)

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#128]
Anstatt ein foreach via `$this->getObjects()` zu durchlaufen, könnte man so schneller auf ein bestimmtes Objekt zugreifen.

**Comment by dergel** [comment]
Was gibt es für Fälle bei denen man das braucht ?

**Comment by tbaddade** [comment]
Man könnte so einen Part vereinfachen.
https://github.com/yakamara/redaxo_yform/blob/master/lib/yform/validate/compare.php#L21-L30

**Comment by dergel** [comment]
das geht so nicht .. Aufruf einer solchen statischen Methode liefert dann leider nichts passendes. Ich denke das ist so auch nicht nötig.
