### ISSUE TITLE
choice-Feld wirft Fehler bei Nur-Ansehen-Variante

### ISSUE THREAD

**Issue by bitshiftersgmbh** [yakamara/redaxo_yform#1283]
Möchte man mit "Nur-Lese"-Rechten auf eine Tabelle enen Datensatz öffnen, der (bestimmte?) Choice-Felder enthält erscheint z.B. folgende Fehlermeldung:

```
Transaktion wurde wegen folgendem Fehler nicht ausgeführt: Call to undefined method rex_yform_choice_group_view::getValue()
```

![Screenshot 2022-07-05 104520](https://user-images.githubusercontent.com/7023022/177296713-95e69695-6bfc-4098-9e58-8a4b9b3812ab.png)

**Comment by dergel** [comment]
schickst du mir per slack einen export der tabellen?

**Comment by dergel** [comment]
sollte nun passen :) ..
