### ISSUE TITLE
"Funktionen" Dropdown in Tabellen nicht nutzbar bei wenig Zeilen / am Ende der Tabelle!?

### ISSUE THREAD

**Issue by olien** [yakamara/redaxo_yform#1284]
![image](https://user-images.githubusercontent.com/330516/177538222-9a9dfb69-a759-4840-9f67-a4a71aab0010.png)
![image](https://user-images.githubusercontent.com/330516/177538247-b25dd856-a608-42ad-b6c8-37f376e34c70.png)

**Comment by eaCe** [comment]
https://friendsofredaxo.slack.com/archives/C1BAXLN2F/p1656676282137169

**Comment by eaCe** [comment]
@madiko @olien ich glaube das hängt an folgender Zeile: https://github.com/FriendsOfREDAXO/yform_usability/blob/d843a1b9a6d34fc544169e983f067e3a6091a3e9/lib/Extensions.php#L214
Das ist kein YForm-Problem. Könnt ihr das mal testen?

**Comment by tbaddade** [comment]
> ich glaube das hängt an folgender Zeile:

Die Buttons werden durch ein Fragment als Dropdown angezeigt.
https://github.com/yakamara/redaxo_yform/blob/e9f43305656936f73fc27a67eab091746da5577c/plugins/manager/lib/yform/manager.php#L638

Eventuell einmal testen, dass Fragment zu "überschreiben".

**Comment by eaCe** [comment]
@madiko ich meinte die Zeile aus yform_usability auskommentieren oder einfach die Klasse `table-responsive` auf der Tabelle entfernen.

**Comment by madiko** [comment]
@tbaddade mittels Theme war es schon möglich, das Dropdown zu "überschreiben".
Was seltsam ist, ist nur, dass das "Duplizieren" aus dem Dropdown nicht als Option angezeigt wird. Hier geht also was verloren.

**Comment by eaCe** [comment]
Das Issue hier bezieht sich ja nicht auf die Inhalte des DD. Das wäre eine andere Sache. Bei mir läuft das allerdings.

**Comment by madiko** [comment]
@eaCe habe YForm Usability deaktiviert.

**Comment by olien** [comment]
@eaCe bei dir funktioniert die nicht drop down Version inkl. duplizieren?

**Comment by eaCe** [comment]
@olien bei mir geht alles ;) Kannst du bitte testen ob du ohne die genannte Zeile das Problem mit dem overflow noch hast?

**Comment by tbaddade** [comment]
> Ich hatte noch die Idee, dass Nutzer:innen das auch aufdröseln könnten – ohne dieses Dropdown-Menü, um es bedienerfreundlicher zu machen.

> Das Issue hier bezieht sich ja nicht auf die Inhalte des DD.

Dann hatte ich das falsch verstanden. Ich dachte es ging im allgemeinen um das Dropdown um ggf. die alte Darstellung der  Buttons wieder umzusetzen.

**Comment by eaCe** [comment]
@tbaddade das wurde auch gewünscht. Das geht auch mit einem eigenen Fragment und etwas Code - siehe unten.
Aber die Screenshots und der Titel beziehen sich, meiner Meinung nach auf das Problem mit dem overflow. Und dies kommt relativ sicher aus YForm Usability.

```php
rex_extension::register('YFORM_DATA_LIST_ACTION_BUTTONS', static function (rex_extension_point $ep) {
    $actionButtons = $ep->getSubject();

    rex_extension::register('YFORM_DATA_LIST', static function (rex_extension_point $ep) use ($actionButtons) {
        $list = $ep->getSubject();

        $list->setColumnFormat(rex_i18n::msg('yform_function') . ' ', 'custom', function( $params ) use ($actionButtons) {
            $fragment = new rex_fragment();
            $fragment->setVar('buttons', $actionButtons, false);
            $buttons = $fragment->parse('action_buttons.php');
            return $buttons;
        });

        $ep->setSubject($list);
    }, rex_extension::LATE);
});
```

```php
<?php

/**
 * @var rex_fragment $this
 * @psalm-scope-this rex_fragment
 */

?>

<div>
    <ul class="list-inline">
        <?php
        foreach ($this->buttons ?? [] as $button) {
            echo '<li>' . $button . '</li>';
        }
        ?>
    </ul>
</div>
```

**Comment by eaCe** [comment]
https://friendsofredaxo.slack.com/archives/C1BAXLN2F/p1657205501072589

**Comment by eaCe** [comment]
@olien ich denke eigentlich das dieses Issue hier geschlossen werden kann. Daniel hat inzwischen meine Annahme von hier https://github.com/yakamara/redaxo_yform/issues/1284#issuecomment-1176276277 bestätigt.

**Comment by olien** [comment]
Ja. Bestätige auch nochmal. Danke
