### ISSUE TITLE
User Rechte - yform 4.0.2 - Fehler? Tabellen mit Bearbeitungsrechten / Tabellen mit Recht zur Ansicht

### ISSUE THREAD

**Issue by steri-rex** [yakamara/redaxo_yform#1288]
Habe 5 yform Tabellen angelegt - eine Redaxo User Rolle hat davon 2 Tabellen mit Bearbeitungsrechten und keine Tabellen mit Recht zur Ansicht. 
Es werden bei dem User mit dieser Rolle aber alle 5 Tabellen angezeigt. 
Die 2 Tabellen mit Bearbeitungsrechten können editiert werden die restliche 3 Tabellen können nur angesehen werden. 
Da aber keine Tabellen mit Recht zur Ansicht ausgewählt wurde sollten nur die 2 Tabellen mit Bearbeitungsrechten in Redaxo angezeigt werden.

**Comment by dergel** [comment]
Jein.. Du wirst in den beiden Tabellen mit Bearbeitungsrechten wahrscheinlich Relationen haben, d.h. die anderen Tabellen sind verknüpft und man benötigt die Leserechte, damit man die eigentlich Tabellen auch bearbeiten kann. Its a feature ;)
