### ISSUE TITLE
VALUE :: html kein <br /> möglich

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#13]
Man muss immer diese verwenden `<br>`

**Comment by dergel** [comment]
kannst du mir das genauer erklären ?

**Comment by tbaddade** [comment]
Verwendet den Typen html und gibt dort ein <br /> ein, wird dieses bei der Ausgabe gelöscht.

**Comment by dergel** [comment]
Hallo,

klappt bei mir .. 
schliesse ich vorerst .. vielleicht alte version ?

![bildschirmfoto 2016-02-15 um 15 12 10](https://cloud.githubusercontent.com/assets/322951/13050891/89ae8cc0-d3f6-11e5-8126-233419429001.png)
![bildschirmfoto 2016-02-15 um 15 12 19](https://cloud.githubusercontent.com/assets/322951/13050890/89adb016-d3f6-11e5-88f8-47553dfe525c.png)

**Comment by tbaddade** [comment]
Ich muss es immer so notieren:

`html||<p>Mein<br>Umbruch</p>`
