### ISSUE TITLE
Dropdown in der Datentabellen Ansicht angeschnitten

### ISSUE THREAD

**Issue by chrisrex** [yakamara/redaxo_yform#1304]
In der Datentabellen Ansicht wird das Dropdown in den letzten beiden Reihen angeschnitten. So gesehen auf dem Ipad. Bei den oberen Datensätze wird das Dropdown korrekt angezeigt.
https://friendsofredaxo.slack.com/archives/C1BAXLN2F/p1663429901466519

**Comment by eaCe** [comment]
https://github.com/FriendsOfREDAXO/yform_usability/issues/106

**Comment by dergel** [comment]
So wie ich das gelesen habe und verstehe, können wir nicht wirklich etwas in yform lösen. Ich schließe das Issue.
