### ISSUE TITLE
Checkbox Unterschied Label zwischen Formbuilder und php

### ISSUE THREAD

**Issue by ritzfritz** [yakamara/redaxo_yform#1319]
In der Ausgabe des Formulars per PHP wird beim Label am Anfang und Ende ein Leerzeichen eingebaut, im Formbuilder nicht.

**Comment by dergel** [comment]
sollte nun passen

**Comment by ritzfritz** [comment]
Dankeschön!

Von: Jan Kristinus ***@***.***>
Gesendet: Donnerstag, 5. Januar 2023 21:45
An: yakamara/redaxo_yform ***@***.***>
Cc: Fritz Ritzinger ***@***.***>; Author ***@***.***>
Betreff: Re: [yakamara/redaxo_yform] Checkbox Unterschied Label zwischen Formbuilder und php (Issue #1319)


sollte nun passen
