### ISSUE TITLE
Datetime im Tabellenmanager gibt 1 aus

### ISSUE THREAD

**Issue by eaCe** [yakamara/redaxo_yform#132]
Ich habe nach dem Update auf die neue Version von yForm keine möglichkeiten mehr datetime zu nutzen.
Ich bekomme im Tabellenmanager auf dem jeweiligen eintrag nur eine 1 ausgegeben...
![yform](https://cloud.githubusercontent.com/assets/2708231/17772741/bf66f6f0-654a-11e6-9622-7a209f2eef38.PNG)

**Comment by tbaddade** [comment]
Das sollte behoben sein
https://github.com/yakamara/redaxo_yform/issues/103
https://github.com/yakamara/redaxo_yform/issues/64

**Comment by eaCe** [comment]
Habe die neuste Version aus dem Installer... Wenn die GH Version sich davon unterscheidet teste ich es noch ein mal...

**Comment by alexplusde** [comment]
ja, unterscheidet sich.

**Comment by eaCe** [comment]
Ok diese Version geht, gibt man aber einen : für die Uhrzeit ein bekommt man wieder die ausgabe 1
