### ISSUE TITLE
In Whooops Pfad zum E-Mail-Template klickbar machen

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/redaxo_yform#1322]
Mit aktiviertem Developer-Addon und im System hinterlegtem Pfad/Editor sollte bei einem Whoops eines E-Mail-Templates dieser Pfad klickbar sein:

![image](https://user-images.githubusercontent.com/3855487/202909723-c42724c9-0588-4e09-b468-265257f91964.png)

**Comment by dergel** [comment]
in YForm ist es nun drin. Link geht im Moment auf auf redaxo selbst. Im Developer muss es noch nachgerüstet werden, dass es auch auf die Datei dann geht

https://github.com/FriendsOfREDAXO/developer/issues/106
