### ISSUE TITLE
`hashvalue` Hash aus mehr als einem Eingabefeld generieren

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/redaxo_yform#1324]
Hashvalue sollte aus mehreren Feldern als Bezugswert einen individuellen Hash generieren können.

**Comment by dergel** [comment]
soweit ich das sehe, macht index genau das. du kannst eine Funktion hinterlegen, der den index dann z.b. sha1 oder so hasht

**Comment by alxndr-w** [comment]
Dann könnte man doch `hashvalue` und `index` zusammenlegen? Ich müsste nachprüfen, ob index auch salt kann.

**Comment by alxndr-w** [comment]
index hat keine Möglichkeit, ein salt zu übergeben.

**Comment by dergel** [comment]
index mit salt ergänzen finde ich gut. Zusammenlegen geht erst in Version 5.0, aber finde ich auch sinnvoll und war auch so geplant.

**Comment by dergel** [comment]
ist nun drin
