### ISSUE TITLE
Massenarbeitung: Validierungen deaktivieren

### ISSUE THREAD

**Issue by skerbis** [yakamara/redaxo_yform#1325]
Bei der Massenbearbeitung greifen die Validierungen so ist es nicht möglich mehrere fehlerhafte Datensätze zu bereinigen: 
ich möchte nur das Feld Vorname korrigieren in allen gefundenen Datensätzen (es wurde nur ein Leerzeichen eingegeben). 
Dennoch werde ich aufgefordert das Feld Kreis auszufüllen. 

Beispiel: 

<img width="636" alt="Bildschirm­foto 2022-11-20 um 18 19 08" src="https://user-images.githubusercontent.com/791247/202916151-9015a8a4-a425-4b6e-abd8-f8ec3929ecdf.png">

**Comment by alxndr-w** [comment]
In diesem Screenshot ist es deaktiviert, es sollte gar nicht befüllt dargestellt werden. Außer du aktivierst es und wählst es damit aus.

**Comment by skerbis** [comment]
ich will es nicht befallen ich will nur in allen Datensätzen Vorname ändern.

**Comment by skerbis** [comment]
nein

**Comment by alxndr-w** [comment]
Befüllt, wenn du reinklickst - oder befüllt in der Datenbank-Tabelle? Hast du da auch nachgesehen?

Anderenfalls siehst du nur den Wert, den es beim Speichern hätte, aber nicht den, der gespeichert ist.

**Comment by dergel** [comment]
ich kann den Fehler so nicht nachvollziehen. Dazu bräuchte ich einen Auszug mit dem Fehler der Datensätze. Kannst du mir den zukommen lassen?

**Comment by alxndr-w** [comment]
@skerbis kannst du mir das Mal per Videochat demonstrierten? Ich bekomme es auch nicht nachgestellt.

**Comment by skerbis** [comment]
Vielleicht lag es an der vorherigen YForm-Version. Aktuell kann ich es mit dem aktuellen YForm nicht reproduzieren. 
Sollte es wieder geschehen, werde ich das issue wieder öffnen.
