### ISSUE TITLE
Tableset-Import optimieren - Addon-Installation schlägt sonst fehl

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/redaxo_yform#1326]
Die Terminverwaltung <https://github.com/alexplusde/events> ist ein tolles Beispiel, wie man mit einem Rutsch in der Praxis richtig viele Tabellen und Felder auf einmal importiert / importieren kann. Hier gibt's beim Installieren ein Tableset <https://github.com/alexplusde/events/blob/main/install/rex_event.tableset.json> das dann leider folgende Meldung:

**ErrorException:** Maximum execution time of 120 seconds exceeded
**File:** redaxo\src\core\lib\sql\sql.php
**Line:** 1233

<details>
<summary>Stacktrace</summary>

| Function                    | File     | Line     |
| --------------------------- | -------- | -------- |
| rex_error_handler::shutdown |          |          |

</details>
<details>
<summary>System report (REDAXO 5.14.1, PHP 8.1.6, MariaDB 10.4.24)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.14.1     |

| PHP           |                                |
| ------------: | :----------------------------- |
|       Version | 8.1.6                          |
|       OPcache | no                             |
|        Xdebug | no                             |
|       Warning | Das Setup wird unverschlüsselt durchgeführt. Frontend und Backend sollten grundsätzlich durch HTTPS verschlüsselt aufgerufen werden, um die Privatsphäre zu schützen und den Datenschutz zu gewährleisten. |

| Database      |                 |
| ------------: | :-------------- |
|       Version | MariaDB 10.4.24 |
| Character set | utf8mb4         |

| Server        |                |
| ------------: | :------------- |
|            OS | WINNT          |
|          SAPI | apache2handler |
|     Webserver | Apache/2.4.53  |

| Request       |                  |
| ------------: | :--------------- |
|       Browser | Chrome/107.0.0.0 |
|      Protocol | HTTP/1.1         |
|         HTTPS | no               |

| Packages                 |            |
| -----------------------: | :--------- |
|                  adminer | 1.9.2      |
|              auto_delete | 1.0-dev    |
|                   backup | 2.8.2      |
|                 be_style | 3.1.0      |
|      be_style/customizer | 3.1.0      |
|          be_style/redaxo | 3.1.0      |
|          be_style_fluent | 4.0.0      |
|                     cke5 | 5.2.0      |
|                  cronjob | 2.9.0      |
|                    debug | 1.2.2      |
|                epcqrcode | 1.0.3      |
|                  install | 2.10.0     |
|           mailer_profile | 1.0        |
|            media_manager | 2.13.0     |
| media_manager_responsive | 1.1.0-dev  |
|                mediapool | 2.12.0     |
|                 metainfo | 2.9.0      |
|             notification | 1.1.0-dev  |
|     notification/be_user | 0.1-dev    |
|   notification/ycom_user | 0.1-dev    |
|                     once | 1.0.0      |
|                phpmailer | 2.11.2     |
|                 plus_bs5 | 0.0.5      |
|                  project | dev        |
|                    qanda | 2.0.12-dev |
|                  rexstan | 1.0.62     |
|                 speed_up | 1.3.1      |
|                    staff | 1.2.1      |
|                structure | 2.14.1     |
|        structure/content | 2.14.1     |
|                    thumb | 1.0-alpha1 |
|                    users | 2.9.0      |
|          wenns_sein_muss | 0.6-dev    |
|               wortpresse | 0.3-dev    |
|                     ycom | 4.0.11     |
|                ycom/auth | 4.0.11     |
|               ycom/group | 4.0.11     |
|                    yform | 4.0.4      |
|              yform/email | 4.0.4      |
|            yform/manager | 4.0.4      |
|              yform_field | 2.0.1      |
|            yform_geo_osm | 1.2.6      |
|          yform_usability | 2.0.6-beta |
|                 yrewrite | 2.9.1      |
|        yrewrite_metainfo | 1.0.5      |

</details>

Im 2. oder 3. Anlauf erhalte ich dann folgenden Fehler:

```
Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 299008 bytes) in C:\xampp816\htdocs\redaxo.local\redaxo\src\core\lib\util\file.php on line 136 Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 32768 bytes) in C:\xampp816\htdocs\redaxo.local\redaxo\src\core\vendor\symfony\var-dumper\Cloner\Data.php on line 337
```

**Comment by tbaddade** [comment]
Duplicate #1286

**Comment by alxndr-w** [comment]
Ich weiß, doch in @tbaddade in #1286 darf ich nur leider nicht kommentieren.

**Comment by alxndr-w** [comment]
Ich habe das Problem weiterhin in meinen Projekten und müsste wissen, wie ich dieses Issue bzw. #1286 in der Bearbeitung beschleunigen kann @dergel

**Comment by dergel** [comment]
ich denke, dass kann man beschleunigen. Im Moment wird nach jeder Tabelle, Feld etc das ganze Paket neu generiert. Da gibtes noch Optimierungsmöglichkeiten

**Comment by alxndr-w** [comment]
Ich meinte auch im Sinne von, was könnte die Bearbeitung dieses Issues beschleunigen. Geld. Blumen. Etwas anderes zum Tausch.

Falls es eine Möglichkeit gibt, hier von meiner Seite aus einzuwirken, würde ich es gerne wissen.

**Comment by dergel** [comment]
Schokolade, Blumen, Geld - in der Reihenfolge wäre schon gut :D .. real .. ich schau mal, dass ich das bald mache.

**Comment by alxndr-w** [comment]
- [ ] Schokolade
- [ ] Blumen
- [ ] Geld

**Comment by dergel** [comment]
@alxndr-w Kannst du beim Testen helfen?

https://github.com/yakamara/redaxo_yform/pull/1382

**Comment by alxndr-w** [comment]
Aber sicher! Bis wann wäre gut? asap?

**Comment by dergel** [comment]
Gerne Asap.

**Comment by dergel** [comment]
Ist übernommen. @alxndr-w Danke, dass du dir es anschaust .. Wenn was nicht passt, gerne ein neues Issue dazu.
