### ISSUE TITLE
Table Manager - `be_media_category`-Feld hinzufügen

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/redaxo_yform#1340]
Szenario: Ich möchte an einem YCom-Benutzer beim Erstellen hinterlegen, in welche Medienpool-Kategorie dieser hochladen darf. Auswählen geht zwar mit einem be_manager_relation-Feld, aber dazu muss die Kategorie bereits existieren.

Besser wäre es, eine REDAXO-/YForm-Auswahlkomponente zu haben, in der ich die Kategorie ad hoc hinzufügen kann, so wie ich auch ad-hoc in be_manager_relation einen Datensatz anlegen kann, wenn dieser fehlt.

**Comment by dergel** [comment]
Verstehe, was du meinst, aber ich sehe das nicht in der YForm. Das ist mir zu spezifisch. Ich habe bereits die Auswahl der Media-Kategorien als Feld entfernt. Sorry.
