### ISSUE TITLE
YForm 4 und Feldtyp Url (aus URl Addon) zeigt nichts an

### ISSUE THREAD

**Issue by fietstouring** [yakamara/redaxo_yform#1359]
Ich verwende dieses Feld in mehreren Installationen mit YForm 3, **mit YForm 4** wird da nichts mehr in der Liste angezeigt. Vielleicht kann das wer bestätigen oder nicht...? Die Url-Addon Version ist 2.0.2 (bei 2.1.0 gibts einen schweren Fehler mit yform_usability)

**Comment by eaCe** [comment]
https://github.com/tbaddade/redaxo_url/issues/265

https://github.com/yakamara/redaxo_yform/issues/1356

**Comment by tbaddade** [comment]
> Der Fehler scheint behoben. Du kannst den Code von Thomas mal testen. 

Nicht wirklich … Url umgeht das nur mit dem DB-Type

> EDIT: oder ist es dieser hier? [FriendsOfREDAXO/yform_usability#130](https://github.com/FriendsOfREDAXO/yform_usability/issues/130)

Das hat nichts mit dem Value zu tun. Der Fehler bezieht sich auf etwas anderes direkt bei `yform_usability`

Close wegen Dublette https://github.com/yakamara/redaxo_yform/issues/1356

**Comment by eaCe** [comment]
@tbaddade bei Usability ging es um den Fehler den @fietstouring noch erwähnte.
