### ISSUE TITLE
Tabelle leeren- JS-Alert erscheint mehrfach.

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#136]
Das JS-Alert erscheint zweimal. Richtig oder falsch?

**Comment by dergel** [comment]
was meinst du ? ;)

**Comment by tbaddade** [comment]
Wenn man in einer Tabelle ist und oben rechts auf "Tabelle leeren" klickt, kommt die Frage "Tabelle wirklich leeren". Klickt man "ja", kommt die Frage nochmals.

**Comment by dergel** [comment]
War keine ernste Frage . bezog sich auf "richtig oder falsch" ;) ..

**Comment by tbaddade** [comment]
Hmm … ich nehme Tor 3 … Lass es dreimal auftauchen … bevor Daten verloren gehen

**Comment by alexplusde** [comment]
![image](https://cloud.githubusercontent.com/assets/3855487/17811564/9b445478-6623-11e6-96a0-88b56b5ef59c.png)

**Comment by dergel** [comment]
https://github.com/yakamara/redaxo_yform/commit/3a0d1a6a14bed2d9a3ee79faaa64877e2a84e05a
