### ISSUE TITLE
Upload - Erlaubte Dateien

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#1367]
> Erlaubte Dateien (deprecated)

ich lasse das Feld leer, da die erlaubten Dateien via Json-Config eingetragen werden. 
Wird das Value editiert, steht wieder `*` in diesem deprecated Feld.

Weiterhin wird das `allowed_extensions` aus der Json-Config nicht an das `accept` Attribute im HTML übergeben. Wenn man beim editieren das `*` nicht löscht, erscheint das `*` am `accept` Attribute.

**Comment by dergel** [comment]
ist umgesetzt.
