### ISSUE TITLE
Validierung - mehrere customfunction auf ein Value -> nur eine Fehlermeldung

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#1369]
Ich habe auf ein Value 2 customfunction. Beide schlagen an, jedoch wird nur die Meldung der Letzten customfunction angezeigt.

**Hier die beiden Methoden**
```php
<?php

namespace Project\YForm;

class Validator
{
    public static function max(string $fieldName, string $values, string $maxValue): bool
    {
        $values = explode(',', $values);
        if (count($values) <= (int)$maxValue) {
            return false;
        }
        return true;
    }

    public static function duplicate(string $fieldName, string $values): bool
    {
        $values = explode(',', $values);
        return count($values) !== count(array_unique($values));
    }
}
```

**Hier die 2 validates**

<img width="573" alt="Bildschirm­foto 2023-02-06 um 12 54 54" src="https://user-images.githubusercontent.com/338267/216965063-39324a6a-2eca-420c-be33-8f2ab396c06b.png">

<img width="429" alt="Bildschirm­foto 2023-02-06 um 12 55 53" src="https://user-images.githubusercontent.com/338267/216965246-479783bb-7cff-461c-982d-6fb7064fa7b7.png">

**Comment by dergel** [comment]
weiter gehts hier #1380
