### ISSUE TITLE
Seiten in einem Popup, sind nicht als Popup im PageObject definiert

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#137]
Damit schlägt eine Überprüfung via `rex_be_controller::getCurrentPageObject()->isPopup()` fehl.

**Comment by dergel** [comment]
welche seiten sollten in einem popup sein ? Meinst du Tabellenverknüpfungen ?

**Comment by tbaddade** [comment]
> Meinst du Tabellenverknüpfungen

Genau. Alle Tabellen die sich in einem Popup öffnen.

**Comment by dergel** [comment]
Tabellen öffnen sich aber in PopUps wenn den Context entsprechend ist, also wenn Sie von einer anderen Tabelle verknüpft wurden. Das heisst, die sind immer auch "normal" erreichbar. Ich sehe das nicht als Problem

**Comment by tbaddade** [comment]
> Ich sehe das nicht als Problem

Ich schon, z.Bsp. wird dadurch die Schnellnavi anzeigt.

**Aufruf**
https://github.com/FriendsOfREDAXO/quick_navigation/blob/master/boot.php#L15

**Wenn Popup, mach nix**
https://github.com/FriendsOfREDAXO/quick_navigation/blob/master/lib/QuickNavigation.php#L17-L19
