### ISSUE TITLE
Value integer erzeugt Deprecated Meldung

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#1370]
Im Integer-Value wird bei nicht vorhanden sein der Wert auf `null` gesetzt.

Als YTemplate wird `value.text.tpl.php` verwendet, was dann diese Meldung erzeugt:

> "htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated"

**Comment by dergel** [comment]
Ich habe in diesem Zuge alle htmlspecialchars auf rex_escape geändert, aber den Fehler konnte ich vorher schoh nciht nachvollziehen.

**Comment by tbaddade** [comment]
Siehe hier: https://github.com/yakamara/redaxo_yform/blob/master/lib/yform/value/integer.php#L19

`rex_escape` kann mit `null` umgehen 👍
