### ISSUE TITLE
Upload-Feld: Fehlermeldung in History-View wenn man Änderungs-Modal sehen will

### ISSUE THREAD

**Issue by bitshiftersgmbh** [yakamara/redaxo_yform#1373]
In der Datensatzhistorie, wenn man "ansehen" drückt, scheint das Upload-Feld die Fehlerursache hierfür zu sein:

![image](https://user-images.githubusercontent.com/7023022/218782943-dc4d5d8a-8300-4454-9818-57d9d18fb36f.png)

**Comment by dergel** [comment]
kannst du das mit der aktuellen github version testen. Ich würde behaupten, dass dies gelöst ist

**Comment by dergel** [comment]
Gerade noch mal in diversen Varianten mit der aktuellen Version getestet. Sollte bereits angepasst sein.
