### ISSUE TITLE
Feld uuid ändert sich bei jedem Speichern eines Datensatzes

### ISSUE THREAD

**Issue by wexstorm** [yakamara/redaxo_yform#1388]
Ein Feld vom Typ UUID/GUID ändert sich leider jedes Mal beim Speichern eines Datensatzes im Backend. Ist dieses Verhalten so gewollt? Kann man das deaktivieren?

**Comment by eaCe** [comment]
@wexstorm das ist bekannt und @christophboecker hat das schon in einem PR gefixed:
https://github.com/yakamara/redaxo_yform/pull/1363

**Comment by dergel** [comment]
Ist im nächsten Release drin
