### ISSUE TITLE
Ids der Felder werden mehrfach vergeben

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#139]
Suche und das Editier-Formular haben dieselben Ids. Einerseits darf das im HTML generell nicht vorkommen, andererseits funktioniert dadurch das GeoPlugin aktuell nicht.

Passt auch zu #133

**Comment by gharlan** [comment]
Und wenn man ein Label im eigentlichen Formular anklickt, wird das Feld im Suchformular fokussiert.
