### ISSUE TITLE
Import der Geolocation-Tablests crasched mit der GH-Version 

### ISSUE THREAD

**Issue by christophboecker** [yakamara/redaxo_yform#1391]
Szenario:
Aktuelles Redaxo 5.15 und YForm aus dem GH-Repo (Zip vom 07.03.2023). Geolocation 2.0-beta aus dem Installer gezogen und installiert. Die Installation crashed mit dem Fehler

>AddOn geolocation konnte aus folgendem Grund nicht installiert werden:
Fehler beim Import der YForm-Formulare: «Error while executing statement "ALTER TABLE `rex_yform_field` ADD `choice_attributes` TEXT NOT NULL" using params []! SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'choice_attributes'»

Die Installation erfolgt mit diesen Code-Zeilen:
https://github.com/FriendsOfREDAXO/geolocation/blob/b8c1d0a9d4deb216f90b75e7f77f4b0a3f32f291/install.php#L167-L172

Gegenprobe:
GH-Yform deinstaliert und gelöscht. YForm 4.0.4 aus dem Installer installiert; Geolocation installiert; löppt. 

Ich vermute, dass es nicht an Geolocation liegt. In YForm 4.0.4. und in YForm-GH wird die Tabelle rex_yform_field indentisch  aufgebaut; die Spalte `choice_attributes` ist also in beiden Versionen vorhanden, wenn der Import läuft. Da es nur beim neuen GH crashed, muss wohl dort etwas anders sein.

**Comment by dergel** [comment]
Komischerweise hat es bei mir geklappt. Es gibt andere Fehler beim Einsatz

**Comment by dergel** [comment]
Ich glaube es geht, bei mir lief das unproblematisch durch. Es gibt aber einen type_error bei den action_buttons .. Der muss als Array übergeben werden, damit, ich glaube das Cache Löschen, funktioniert.

**Comment by christophboecker** [comment]
> Ich glaube es geht, bei mir lief das unproblematisch durch. Es gibt aber einen type_error bei den action_buttons .. Der muss als Array übergeben werden, damit, ich glaube das Cache Löschen, funktioniert.

Jepp, https://github.com/FriendsOfREDAXO/geolocation/pull/135
