### ISSUE TITLE
allgemeine auth Validierung

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#1392]
In einem einfachen Anmeldeformular soll der User diese durch einen Link in der E-Mail bestätigen.

Dazu nutze ich grad `ynewsletter_auth`, weil bereits vorhanden.

Wäre es nicht sinnvoller diese auth-Validierung allgemein in YForm zu haben?

Vielleicht ließe sich diese noch so erweitern, dass auch diese [auth-Validierung](https://github.com/yakamara/redaxo_ycom/blob/master/plugins/auth/lib/yform/validate/ycom_auth.php) von YCom berücksichtigt wird.

**Comment by alxndr-w** [comment]
Die Auth-Validierung würde dann eine Mail bzw. einen Link benötigen und man müsste wissen, wer Authentifiziert: Der User, der Websitebetreiber, beide? + ggf. gewünschte E-Mail-Template-Keys.

**Comment by tbaddade** [comment]
Es geht nicht um E-Mails nur um diese [Validate Klasse](https://github.com/yakamara/redaxo_ynewsletter/blob/master/lib/yform/validate/ynewsletter_auth.php).

Die E-Mails und die zu übergebenen Werte sollte man weiterhin selbst erstellen bzw. festlegen.

**Comment by dergel** [comment]
Finde ich nicht. Validierungen mit Auth sind sehr unterschiedlich. Ich möchte die YForm lieber schlanker machen, das würde dagegen sprechen.

**Comment by tbaddade** [comment]
Andere Auth-Validierungen könnten von der Allgemeinen dann ableiten. Ich finde, hier könnte YForm eine Basis vorgeben.
