### ISSUE TITLE
Table Manager - Übersicht der Tabellen vervollständigen

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#140]
Mit fehlt in der Übersicht die Status der Checkboxen (Suche aktiv, Import, Export etc.).

Könnte ja alles in einer Spalte zusammengefasst werden.

**Comment by tbaddade** [comment]
Hierzu passt auch, das in der Tabelle "Felder bearbeiten" ebenfalls die Status der Checkboxen (Versteckt, Als Suchfeld aufnehmen) erscheinen.

**Comment by dergel** [comment]
Bei den Feldern kann man das nciht pauschal einsetzen, weil die Optionen nicht überall existieren.
