### ISSUE TITLE
CSRF Fehler

### ISSUE THREAD

**Issue by TobiasKrais** [yakamara/redaxo_yform#1403]
Leider erhalte ich mit YForm 4.1 auf R5.15.1 in meinen Formularen nur noch CSRF Fehler. Hier eine Beispielseite: https://test.design-to-use.de/de/modultests-d2u-helper-addon/11-kontakt/.

Der Code des Fomulars ist hier zu finden https://github.com/TobiasKrais/d2u_helper/blob/master/modules/11/1/output.php. Nur eine Kleinigkeit ist auf der Beispielseite angepasst: `$yform->setObjectparams('csrf_protection', false);` wird natürlich zu `$yform->setObjectparams('csrf_protection', true);`

Als Fehlerquellen ausgeschlossen sind:

- 2 Formulare auf einer Seite
- 2-facher Aufruf der Methode`rex_article->getContent()`
- `rex_response::setHeader('Clear-Site-Data',...)` wird nicht verwendet

**Comment by dergel** [comment]
kannst du mir den Code dazu liefern. dann kann ich das testen

**Comment by TobiasKrais** [comment]
Gerne: https://github.com/TobiasKrais/d2u_helper/tree/master/modules/11/1
Im D2U Helper Addon kannst du dir das Modul auch unter Module -> 11-1 Kontaktformular auch installieren. Da muss dann nur noch im Modul wie oben beschrieben die Zeile 71 angepasst werden, damit CSRF auch wieder aktiviert ist.

**Comment by TobiasKrais** [comment]
Fehler gefunden: in der Zeile `$yform->setObjectparams('form_name', 'd2u_helper_module_11_1_'. random_int(1, 100));` hat das Formular einen zufälligen Namen. Da der Name des Senderformulars und Empfängerformulars unterschiedlich ist, funktioniert der CSRF Schutz nicht mehr.
