### ISSUE TITLE
$class must be a subclass of rex_complex_perm!

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#141]
Fehler erscheint in der aktuellen GH-Version. Bin nicht im Backend eingeloggt.

```
"InvalidArgumentException" thrown in /redaxo/src/core/lib/login/complex_perm.php on line 80
$class must be a subclass of rex_complex_perm!
#0 /redaxo/src/addons/yform/plugins/manager/boot.php(12): rex_complex_perm::register('yform_manager_t...', 'rex_yform_manag...')
...
```

**Comment by tbaddade** [comment]
Man muss manuell `autoload.cache` löschen.

**Comment by dergel** [comment]
wie hast du das installiert ? wahrscheinlich einfachb drübergebügelt. Da es dann keine richtige Installation ist, passiert das dann .. im Moment noch überall.. Sofern du das nicht installliert hast, bitte das Issue hier schliessen

**Comment by tbaddade** [comment]
Ich holte die GH Version lokal, damit man am Repo arbeiten konnte.
