### ISSUE TITLE
Upload Value :: Bei E-Mail-Versand sollte ein Downloadlink angeboten werden

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#142]

**Comment by dergel** [comment]
das geht so leide rnicht automatisiert, da ich nicht definieren möchte, wie man uploads handhaben muss. Aber man kann nun Dateien an eine E-Mail anhaengen. Ein Upload wird immer automatisch in den "['value_pool']['files']" gelegt (so wie email_pool oder sql_pool). 

Beim E-Mail-Versand kann man dann diese Dateien zum Versand aufnehmen. z.B. so:

`php|php|<?php if (isset($this->params['value_pool']['files'])) { $this->params['value_pool']['email_attachments'] = $this->params['value_pool']['files']; } ?>`
