### ISSUE TITLE
Captcha wird nicht angezeigt, wenn kein YForm Modul eingefügt ist

### ISSUE THREAD

**Issue by TobiasKrais** [yakamara/redaxo_yform#143]
Ich habe eine Testseite mit einem YForm Kontaktformular erstellt (Benutzername und Passwort sind "test" ohne Anführungszeichen):
http://promitec.design-to-use.de/de/produkte/?machine_id=1#tab_request

Das Problem: der Captcha wird nicht angezeigt. Der Code kann hier eingesehen werden: https://github.com/TobiasKrais/d2u_machinery/blob/master/module/machines_out.php#L399

Interessant ist: füge ich auf dieser Seite ein YForm Modul ein wird das Captcha angezeigt.

**Comment by tbaddade** [comment]
Hatte ich gestern auch grad. Du musst als dritten param die Url übergeben.

```
$url = rex_getUrl('', '', ['machine_id' => rex_request('machine_id', 'int')])
$form->setValueField('captcha', ['Labeltext', 'Fehlertext', $url]);
```

@dergel Sollte das Captcha dennoch geliefert werden, wenn das Formular nicht angezeigt wird?

**Comment by TobiasKrais** [comment]
Danke für den Tipp. Wenn ich das so mache lautet die Link URL: http://promitec.design-to-use.de/de/produkte/?machine_id=1?captcha=show&1472112743. Der Captcha funktioniert dann nicht.

**Comment by tbaddade** [comment]
Entweder du kopierst dir das Captcha Value und passt das mit dem ? an, also prüfst ob die Url bereits ein ? hat. Wenn nicht `?captcha` ansonsten `&captcha` und gern als PR senden oder

Das soll jetzt keine Allgemeinlösung sein, könnte dir aber helfen
```
$form = $form->getForm();
$form = str_replace('?captcha=show', '&captcha=show');
```

**Comment by TobiasKrais** [comment]
Sorry für die späte Antwort. Deine Lösung funktioniert! Könnte der Code von YForm so geändert werden, dass das intern abgefangen wird?

**Comment by TobiasKrais** [comment]
Super! Habs gestestet und es funktioniert super. @dergel: Würdest du den Patch bitte auch auf die Klasse captcha_calc anwenden? Da liegt der selbe Fehler vor. Vielen Dank!

**Comment by dergel** [comment]
habs angepasst, aber nicht getestet, kannst du das machen ?

**Comment by TobiasKrais** [comment]
Sehr gerne. Ist getestet und funktioniert perfekt.
Noch ein Hinweis: in der Doku der Values ist bei captcha_calc der optionale Parameter "|[link]" nicht mit angeführt, aber er funktioniert. Willst du das noch mit aufnehmen?

Vielen, vielen Dank nochmals für alles!

**Comment by dergel** [comment]
kannst du auch gerne anpassen.. direkt in die doku und dort als PullRequest (PR)  ergänzen.. wir freuen uns über Hilfe - gerade auch weil die Doku neu ist, aber jetzt noch ein paar Korrekturen braucht (YForm hat sich doch ein Stück verändert)

**Comment by dergel** [comment]
@TobiasKrais Deine Chance etwas zurück zu geben ;)

**Comment by TobiasKrais** [comment]
OK. Da erwischt du mich auf dem unerfahrenen Fuß. Ich habe das gerade mal probiert. Habe ich es richtig gemacht? Falls nicht, gib Bescheid. Das sollte ich wirklich mal lernen...

**Comment by dergel** [comment]
Genauso ist es richtig !! Danke..
