### ISSUE TITLE
Feldtypen der Meta Infos erweitern

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#144]
Im Vergleich zu YForm bieten die Meta Infos nur eine beschränkte Anzahl an Feldtypen. Prinzipiell wäre es doch wünschenswert, die Feldtypen durch YForm unbeschränkt erweitern zu können, sie teilen sich ja eine recht ähnliche Aufgabe. Denkbar wären auch Validierungen der Meta-Feldern von Artikeln und Medien.

Ich weiß nicht, wie schwierig so ein Vorhaben wäre, aber für YForm 2 vielleicht?

**Comment by dergel** [comment]
man könnte die metainfos auch auf yform basierend entwickeln.. aber, da habe ich mir bsher noch keine Freunde mit gemacht .. Ist halt eine Abhängigkeit mehr, aber ich denke, dass REDAXO Webseiten fast immer die YFORM braucht. Vielleicht baue ich irgendwann "heimlich" metainfo Plugin für YForm ;)

**Comment by dergel** [comment]
diese YMeta hätte wenig hier zu suchen und wird wohl auch vorerst nicht gemacht.. deswegen schliesse das issue
