### ISSUE TITLE
Such-Filter wird nicht beibehalten nach Speichern / zurück zur Übersicht

### ISSUE THREAD

**Issue by skerbis** [yakamara/redaxo_yform#1440]
Wenn man mittels der Suche eine Tabelle gefiltert hat und dann einen Datensatz bearbeitet und speichert. Wird der Filter zurückgesetzt. Das ist schade vor alle wenn mehrere Suchkriterien greifen. Die Suche muss neu ausgeführt werden.

**Comment by christophboecker** [comment]
Hmm. ich hatte mir dazu mal was gebastelt (Suchparameter zwischenspeichern und später wieder in $_REQUEST einfügen). Ist aber auch problematisch. U.a. falle ich auf die Nase, wenn ich gezielt über einen Link eine Edit-Seite ansteuere, die durch den aktuellen Filter nicht ausgeblendet wird. Da ist recht komplex. imho

**Comment by skerbis** [comment]
War ein Fehler von mir. Ich habe eigene Links in die Liste eingeschleust. Daran lag es
