### ISSUE TITLE
Bessere Alternativen für index-Feld Hash-Algorithmen vorschlagen

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/redaxo_yform#1441]
https://github.com/yakamara/redaxo_yform/blob/1fad431332911e8921b3f3c213d382d2125247f1/lang/de_de.lang#L125

Mir ist kein Szenario bekannt, in dem `md5` punkten kann (Kollisionen, nie unique, Rainbow-Tables)
`sha1` gilt mittlerweile auch als unsicher(er). 

Funktionen wie `password_hash()` können jedoch nicht verwendet werden, weil sie eine andere Syntax brauchen. 

Gibt es Alternativen, die ich übersehen habe? Oder müsste man das Feld dazu umbauen?

**Comment by dergel** [comment]
Geht hier auch weniger um Passwörter oder Verschlüsselung. Grundsätzlich ist dieses Feld ein Index Feld, um Daten in einem Pool zu sammeln. Damit man vielleicht Pakete von durchsuchbaren anderen Feldern machen kann. Will man z. B. sehen, ob sich etwas verändert hat, kann man die Funktionen benutzen, um einen Hash abzulegen. Dieser muss nicht kryptografisch sicher sein.
