### ISSUE TITLE
individuelle Attribute können nicht via single quote notiert werden

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#149]

**Comment by dergel** [comment]
gib mir ein beispiel hier rein .. dann prüfe ich das

**Comment by tbaddade** [comment]
value.textarea

`{'class': 'form-control markitupEditor-flow'}`

**Comment by dergel** [comment]
Single quotes sind valides JSON.. 
Ist so definiert, deswegen stimmt es auch, dass es nicht interpretiert wird

**Comment by alexplusde** [comment]
fürs Protokoll:
*sind nicht valides JSON.

**Comment by dergel** [comment]
genau .. sorry... `nicht` - vergessen
