### ISSUE TITLE
action|email|from@email.de|to@email.de|Mailsubject|Mailbody###name###

### ISSUE THREAD

**Issue by olien** [yakamara/redaxo_yform#15]
wie kann ich das E-Mail Feld mit dem Wert aus dem Formular füllen?

text|email|E-Mail|#placeholder:E-Mail

Funktioniert nicht:

action|###email###|to@email.de|Mailsubject|Mailbody###name###
action|+++email+++|to@email.de|Mailsubject|Mailbody###name###

Funktioniert:

action|test@test.de|to@email.de|Mailsubject|Mailbody###name###

**Comment by tbaddade** [comment]
Wenn dann müsste es wie bei r4 sein

Beschreibung
`action|email|from@email.de|to@email.de|Mailsubject|Mailbody###name###`

Code
`action|email]no-replay@oli.de|###email###|Olisubject|Olibody wow`

**Comment by olien** [comment]
hm. Die FROM E-Mail Adresse soll die aus dem Formular und die TO E-Mail Adresse die aus einer REX_VALUE sein... Schnall ich grad nicht :-(

**Comment by tbaddade** [comment]
Die Platzhalter werden nur im body ersetzt.
https://github.com/yakamara/redaxo_yform/blob/master/lib/yform/action/email.php#L18-L23

**Comment by olien** [comment]
Hm. Konnte ich nicht irgendwie die Absender E-Mail Adresse aus dem Formular übernehmen????

**Comment by olien** [comment]
http://www.redaxo.org/de/forum/post104401.html?hilit=absender%20mail#p104401

**Comment by dergel** [comment]
ist nun drin .. muss man aber vorsichtig sein .. E-Mail genau validieren lassen.
