### ISSUE TITLE
Fehlermeldungen via value ausgeben

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#155]
Momentan gibt es diese objparams, die mir aber grad nicht weiterhelfen

`hide_top_warning_messages`
`hide_field_warning_messages`

Mir fehlt grad folgendes:

`objparam|warning_messages_show|false`
`show_warning_messages` als value, um selbst die Position der Fehlermeldung zusetzen

**Comment by dergel** [comment]
das geht nur über die ytemplates. layouten für diese Felder ist leider nicht möglich. Oder verstehe ich was falsch ?

**Comment by tbaddade** [comment]
Layouten meine ich gar nicht sondern nur das Positionieren der Fehlermeldungen innerhalb im Formbuilder.

kleine Beispiele.:

```
objparam|warning_messages_show|false
html||<h1>Kontakt</h1>
show_warning_messages
text|name|Name
```

```
objparam|warning_messages_show|false
html||<h1>Kontakt</h1>
html||<div class="positionier-mich-auf-der-linken-seite-vom-formular">
show_warning_messages
html||</div>
text|name|Name
```

**Comment by dergel** [comment]
das fällt eher in die ytemplates und das man das dann in der form.php anpassen kann.

**Comment by tbaddade** [comment]
> das fällt eher in die ytemplates und das man das dann in der form.php anpassen kann

Da kann man aber auch nicht die Stelle genau definieren. Im Beispiel oben sollte die Meldung nach dem html value auftauchen.
