### ISSUE TITLE
Values select und select_sql zusammenlegen

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#157]
So kann man herausfinden, ob die Optionen via Query kommen
https://github.com/tbaddade/redaxo_dao_var/blob/master/lib/Var/var_dao_select.php#L45-L47

**Comment by alexplusde** [comment]
Analog könnte man das für radio und radio_sql machen.

**Comment by dergel** [comment]
ist bereits mit dem choice feld gemacht ..
