### ISSUE TITLE
Möglichkeit eine Klasse für ein Textfeld zu vergeben

### ISSUE THREAD

**Issue by georgkaser** [yakamara/redaxo_yform#159]
Früher gab es die Möglichkeit eine Klasse für ein Textfeld zu vergeben. Mit Version 1.1 wurde diese Möglichkeit entfernt. Ich habe so immer die benötigten Felder markiert - jetzt fehlt mir diese Möglichkeit und ich muss alle Seiten nachbearbeiten.

Gibt es einen Grund warum diese Möglichkeit enfernt wurde - war ja recht nützlich bisher? Wär cool wenn man das wieder einbauen könnte - oder zumindest optional aktivieren kann.

**Comment by tbaddade** [comment]
Du musst die Klasse bei den Attributen hinterlegen

`{"class": "deine-klasse"}`

**Comment by georgkaser** [comment]
Wo genau? Ich erstelle das Formular mit dem Formbuilder Modul - wo kann ich hier beim Texfeld ein Attribut hinzufügen? text -> Beispiel: text|name|label|defaultwert|[no_db]|

**Comment by tbaddade** [comment]
Im Formbzuuuilder müsste das so notiert werden

`textarea|text|Text|||{"class": "deine-klasse"}|`

**Comment by georgkaser** [comment]
Hmm, okay danke, damit kann ich jetzt wenigstens wieder eine Klasse vergeben. 
Ändert aber leider nichts daran, dass ich die "alten" Formulare ändern muss, weil die Klasse vorher nicht direkt ins INPUT Element sondern in das umschließende DIV geschrieben wurde.

**Comment by georgkaser** [comment]
Beim Email Feld geht das aber nicht - oder mach ich was falsch? email|email||||{"class": "required"}|

**Comment by alexplusde** [comment]
@georgkaser Tipp: Nimm den Table Manager, trag das JSON da ein und schau dir dann den vorgeschlagenen Formular-Code an.

**Comment by georgkaser** [comment]
Guter Tipp @alexplusde - leider gibt es da kein Feld für Attribute:

![bildschirmfoto von 2016-09-20 10-44-45](https://cloud.githubusercontent.com/assets/6472869/18663583/515d09e4-7f1f-11e6-9b74-2acb00f00c33.png)

Ergibt dann folgenden Formularcode: email|email|Email|||required| - leider wird hier keine Klasse ausgegeben. Ich könnte jetzt das Email Feld sowieso im CSS als required definieren - aber sauber ist die Lösung nicht...

**Comment by alexplusde** [comment]
Oh... :D

Was spricht denn dagegen, ein Text-Feld zu nehmen? Du kannst es ja in den Attributen mit `{ "type":"email","required":"required"}` überschreiben.

**Comment by georgkaser** [comment]
Ah, cool - wusste nicht dass das geht. Muss ich mir mal wohl die Doku durchlesen, da hat sich scheinbar viel geändert.

Das mit den Attributen dürfte aber noch nicht überall ganz so wie gewünscht funktionieren - bei Textarea wird folgender Quellcode erzeugt:

![bildschirmfoto von 2016-09-20 11-05-02](https://cloud.githubusercontent.com/assets/6472869/18664307/59022f1e-7f22-11e6-81de-e9f6d2a48b10.png)

Da sollte vielleicht nochmal einer drüberschaun...

**Comment by georgkaser** [comment]
Das E-Mail Feld sollte aber trotzdem funktionieren, nicht?

**Comment by alexplusde** [comment]
> Ah, cool - wusste nicht dass das geht. Muss ich mir mal wohl die Doku durchlesen, da hat sich scheinbar viel geändert.

Exakt. Und wenn dir was fehlt, schreib gerne was dazu :)

**Comment by alexplusde** [comment]
@georgkaser Bei textarea sieht es so aus, als ob nur eine Klasse ausgegeben wrid. Hast du die aktuelle YForm-Beta?

**Comment by georgkaser** [comment]
jahhaa, ich weiß dass wir mithelfen sollen :) Meine Zeit kommt bald, hab noch zu viel um die Ohren im Moment - dann bring ich mich gern mehr ein, hab eh Bock drauf...

Ich hab die aktuelle Version vom Installer.

**Comment by alexplusde** [comment]
Da müsste sich in der GH-Version nochmal was geändert haben zur aktuellen Beta.

**Comment by georgkaser** [comment]
Alles klar, ich machs in der Zwischenzeit ohne die Klassen und gestalte die auszufüllenden Felder vorerst über die id des Feldes. Warte lieber bis das ganze wieder funktioniert.

**Comment by dergel** [comment]
geht nun auch bei emails

https://github.com/yakamara/redaxo_yform/commit/831ba2e21d72aa86e7ece4fba6899deb37ac6849
