### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by Sioweb** [yakamara/redaxo_yform#16]
Die Eingabe wäre sicher benutzerfreundlicher, wenn der User via Drag&Drop die Eingabe-Widgets in ein Area ziehen und Sortieren kann. Mit einem Klick auf das Widget würde sich ein Layer/Overlay oder Accordion öffnen, in dem Optionen definiert werden wie Name, Titel, viele weitere Standard-Parameter und dann pro Widget eben für das Widget wichtige Parameter.

Das ganze würde dann als JSON gespeichert statt mit Pipe getrennt.

Hier wäre ein Beispiel - viel zu übertrieben aber so in etwa eben - http://formoid.com/

Und hier habe ich vor einiger Zeit mal einen Formulargenerator gebaut der mit solchen Daten arbeiten kann: https://github.com/Sioweb/Formulargenerator - als Beispiel wie der PHP-Code aussehen könnte. Der Generator ist enorm flexibel.

**Comment by dergel** [comment]
https://github.com/yakamara/redaxo_yform/issues/39

**Comment by alexplusde** [comment]
close?
