### ISSUE TITLE
Verarbeitung XForm-EP

### ISSUE THREAD

**Issue by alsahh** [yakamara/redaxo_yform#160]
> Hallo zusammen, kann man bei den xform Tabellen vor dem Abspeichern eines Datensatzes noch Berechnungen ausführen? Z.B. gibt der Anwender eine Zahl ein und beim Speichern berechne ich das heutige Datum plus dieser Zahl und speichere das errechnete Datum mit ab?

Hilfestellung anbei.

[xform_ep.zip](https://github.com/yakamara/redaxo_yform/files/485978/xform_ep.zip)

**Comment by dergel** [comment]
Warum nicht den Weg, dass du eine eigene Validierungsklasse machst und die in den entsprechenden Datensaetzen anwendest ? Es geht um den Manager und YForm (nicht XForm), oder ?

**Comment by dergel** [comment]
kannst du soweit ich das gesehen habe auch bei der xform machen ... eigene Klasse und dort entsprechend die Methode setzen. Allgemeine Fragen lieber im Forum oder Slack. Hier sammeln wir neue Dinge oder Ideen/Umsetzungen..
