### ISSUE TITLE
Beim importieren erscheinen Fehlermeldungen ohne genauere Angaben

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#162]
Das passiert z.Bsp. dann, wenn Relationen angelegt aber keine passende relations_id gefunden wird.
![screenshot 2016-09-26 18 07 50](https://cloud.githubusercontent.com/assets/338267/18842103/36b489ba-8414-11e6-96d3-3292af520324.png)

**Comment by gharlan** [comment]
Aber eigentlich nur, wenn in der Relation nicht "Mit Leer-Option" ausgewählt ist.
Daher ist das meiner Meinung nach so korrekt.
Man könnte höchstens eine Default-Message einfügen, falls nichts eingetragen wurde in "Fehlermeldung wenn "Leer-Option" nicht aktiviert ist."

**Comment by tbaddade** [comment]
> Aber eigentlich nur, wenn in der Relation nicht "Mit Leer-Option" ausgewählt ist.

Wichtig wäre überhaupt zu wissen, dass es sich dabei um eine Relationsfeld handelt. Hat man 2 Relationen angelegt kommen schon 2 Dots. Ich wusste zuerst nicht, das der Fehler damit überhaupt zu tun hat.

**Comment by dergel** [comment]
Das fehlt in der be_relation Eintragung. Man muss dort nur die Fehlermeldung eintragen (Im Manager bei den Feldern) dann taucht auch die entsprechend Meldung auf. Ist kein Fehler des Managers.
