### ISSUE TITLE
Warnungen zusammenfassen

### ISSUE THREAD

**Issue by VIEWSION** [yakamara/redaxo_yform#163]
Hallo... ein kleiner Verbesserungsvorschlag:

Wenn man viele ähnliche Felder mit Validierung hat, kommt es unter Umständen schon mal vor dass eine Reihe von Warnungen ausgegeben werden, die man eigentlich zusammenfassen könnte.

Schön wäre es, wenn mehrere zu validierende Felder immer nur eine Warnung erzeugen würden. Man könnte einfach identische Strings in den Meldungen quasi gruppieren indem alle bis auf eine nicht ausgegeben werden.

Das wäre relativ einfach umzusetzen und bräuchte keine zusätzliche Group-ID oder ähnliches. Also z.B.:

validate|empty|vorname|Bitte geben Sie Ihren Vor- und Nachnamen an.
validate|empty|nachname|Bitte geben Sie Ihren Vor- und Nachnamen an.

Gute Idee oder Quatsch?

**Comment by dergel** [comment]
finde ich gut und ist leicht zu implementieren und sinnvoll..  was will man mehr :)

**Comment by VIEWSION** [comment]
Super! Ging ja fix ;)
