### ISSUE TITLE
Tools Plugin

### ISSUE THREAD

**Issue by skerbis** [yakamara/redaxo_yform#166]
Super Plugin, das sich wirklich sehr gut macht. 
Evtl. muss hier und da noch ein Stil angepasst werden. z.B. werden select2-Felder zu kurz dargestellt und Text bricht um. Der Container ist dann nur 100px breit. 

Abhilfe schafft: 
`
.select2-container--bootstrap {
    display: block;
    width: 100% !important;
}
`
Als allgemeines (Core-)Addon wäre es jedoch sinnvoller, vor allem für Leute, die auf YForm verzichten.

**Comment by dergel** [comment]
werde das ergänzen..

ja im Core werden wir noch überlegen was wir das reinsetzen wollen. Weil es wirklich viel ausmacht, wenn man dieses komfort hat - sieht netter aus, macht mehr eindruck und ist praktisch .. 

Wenn Du noch andere CSS Hilfen fürs Tool Plugin hast - her damit.

**Comment by skerbis** [comment]
kommt sicher noch
