### ISSUE TITLE
Table Manager: Funktion "Tabelle anzeigen"

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#168]
Im Moment gibt es innerhalb des Table Managers keine Möglichkeit, auf die Tabellen-Übersicht zu kommen, in der man neue Datensätze anlegen kann. Dafür gibt es 2 Möglichkeiten, die Tabelleneigenschaften zu bearbeiten.

* Dadurch kann nur über die Navi auf die Tabellen zugreifen. 
* Dadurch kann man als Admin nicht auf die Tabelleninhalte zugreifen, wenn die Tabelle nicht in der Navi angezeigt wird.

![keineoption](https://cloud.githubusercontent.com/assets/3855487/18994653/1893b592-8729-11e6-8cfe-4574626133c8.png)

In meinen Augen benötigt es eine zusätzlich  Funktion "Tabelle anzeigen".

**Comment by dergel** [comment]
ich finde den vorschlag aus dem screen gut.. Mich hat das auch regelmäßig genervt, wie man zu den Tabelleninhalten kommt. Am Anfang werde ich mich aber sicher zich mal verklciken - aus gewohnheit.

**Comment by alexplusde** [comment]
Danke :)
