### ISSUE TITLE
Wunsch für Tools-Plugin: Tagging

### ISSUE THREAD

**Issue by skerbis** [yakamara/redaxo_yform#173]
Tokens für's Tagging
http://sliptree.github.io/bootstrap-tokenfield/

**Comment by dergel** [comment]
müsstest du eigentlich auch jetzt mit der aktuellen github version hinbekommen. schau mal hier

https://github.com/yakamara/redaxo_yform_docs/blob/master/de_de/tools_plugin.md#select2

d.h. ein select mit deinen standardfelder anlegen.. und im tagmode kann man dann auch eigene hinzufügen.. meinst du sowas ?

**Comment by skerbis** [comment]
Select2 ist doch nur für Selectfelder - oder nicht? .... Dieses hier wäre für einen Textinput.

**Comment by dergel** [comment]
klar, das tokenfield kann noch mehr.. aber wenn es um tags geht, die man einträgt und per "," trennen will und bestimmte selectfelder schon voreingestellt sind, dann kann das auch select2

in attributes bei einem textfeld folgendes setzen:

`{"data-yform-tools-select2": "tags", "placeholder": "My Placeholder"}`
