### ISSUE TITLE
Formbuilder: Textfeld und/oder objparam für fehlgeschlagenen Mailversand

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#175]
Ich baue yform-Formulare im Moment meistens in PHP und nicht mit dem Formbuilder bzw. einer Mail-Action, weil nur ein entscheidendes Feature fehlt: Das Abfangen eines Fehlers beim Versenden der Mail. Ursachen dafür sind vielfältig:
- Probleme mit dem Mailserver/Postfach des Senders
- Probleme mit dem Mailserver/Postfach des Empfängers
- OSI-Layer-8-Probleme: Der Nutzer gibt seine Mail-Adresse falsch ein (Buchstabendreher, etc., die man nicht mit einer Validierung abfangen kann)

In solchen Fällen sollte der Besucher der Website eine Meldung bekommen, dass es Probleme beim Ausfüllen des Formulares gab und an wen er sich persönlich wenden kann. Dafür wäre es notwendig, eine solche Fehlermeldung im Modul (oder noch besser: als objparam) definieren zu können.

**Comment by dergel** [comment]
das prinzip ist im moment, dass erst values und validierungen durchlaufen werden, also auch nur dort dann fehlermeldungen angezeigt werden, und danach die Aktionen, wie DB, E-Mail etc .. da dort schon die Prozesse losgehen, kann man an der Stelle nicht mehr zurückdrehen. Dennoch könnte man schauen, dass es beim E-Mail-Versand, bessere Infos gibt, die dann aber eigenständig ausgegeben werden.

**Comment by alexplusde** [comment]
Genau. Von meiner Seite aus wäre es auch gar nicht gewünscht, dass der Vorgang abbricht, nur weil der Mail-Versand nicht klappt. 

Eine Anfrage / Bestellung bspw. landet ja dann noch immer über eine entsprechende Action in der Datenbank und kann eingesehen werden. Aber der Nutzer könnte bspw. darauf hingewiesen werden, dass es ein Problem gab und er sein Anliegen sicherheitshalber telefonisch mit dem Händler / Dienstleister / Betreiber mitteilt.
