### ISSUE TITLE
Tablemanager: Historie wird nicht gelöscht

### ISSUE THREAD

**Issue by alexwenz** [yakamara/redaxo_yform#176]
Habe grade die Historie unter "System" komplett gelöscht. Datenbanktabellen "rex_yform_history" und "rex_yform_history_field" sind danach noch gefüllt.

**Comment by dergel** [comment]
Löschen gibt es noch gar nicht - sehe ich gerade.. Du hast wohl die Artikelslicehistorie gelöscht..

**Comment by dergel** [comment]
hier gehts weiter: 

https://github.com/yakamara/redaxo_yform/issues/44
