### ISSUE TITLE
Table Manager / Datensatz hinzufügen: Fieldsets als Tabs

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#178]
![image](https://cloud.githubusercontent.com/assets/3855487/19290822/d570a206-9011-11e6-865f-d02b62800d9d.png)

Ich glaube, ich hatte die Frage schon mal gestellt, kann aber keine Erläuterungen mehr dazu finden. Wenn ich bei "Datensatz hinzufügen" die einzelnen Fieldset-Gruppen als Tabs organisiert sehen möchte, mit den `<legend>` als Reiter-Titel, wie gehe ich dazu am besten vor?

(Wäre es Alternativ möglich, eine JS-Lösung in das Tools-Addon mitaufzunehmen?)

**Comment by tbaddade** [comment]
Am Anfang ein PHP Feld anlegen und dort das hier rein legen
```
<div class="nav rex-page-nav">
    <ul class="nav nav-tabs">
        <li class="active"><a href="#tab-col1" data-toggle="tab">Tab 1</a></li>
        <li><a href="#tab-col2" data-toggle="tab">Tab 2</a></li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane fade in active" id="tab-col1">
```

dort wo der Inhalt gebrochen wird ein weiteres PHP Feld

```
</div>
<div class="tab-pane fade" id="tab-col2">
```

ganz am Ende noch ein PHP Feld

```
</div>

</div>
</div>
```

einfach nur das Html reinpacken . JS brauchst du nix machen

**Comment by alexplusde** [comment]
bzw. HTML-Feld reicht ja dann. Was in meinen Augen etwas stört, ist, dass man so viele HTML/PHP-Felder dafür anlegen muss, die dann in der DB gar keinen Zweck erfüllen.

**Comment by dergel** [comment]
Eventuell die fieldsets automatisiert so ablaufen lassen wäre toll..

**Comment by tbaddade** [comment]
Automatisiert fände ich nicht gut. Innerhalb eines Tabs sollte man mehrere Fieldsets definieren können.

**Comment by alexplusde** [comment]
Wie wäre es, wenn man Tabs in der Tabellen-Definition mit angeben könnte? Felder, ab denen ein neues Tab beginnt?

**Comment by dergel** [comment]
@tbaddade automatisiert meinte ich auch nur mit speziellen class einstellungen.. 
@alexplusde könnte man auch machen, aber dann besser so, dass man selbst sagen kann, welche felder in das tab kommen.

ich überlege mir was..

**Comment by alexplusde** [comment]
Dadurch, dass html-Felder nicht mehr in der Datenbank angelegt werden, kann mit dem Vorschlag von @tbaddade leben. Andere Issues haben da Vorrang.

Bootstrap-HTML-Felder Nutzen wir mittlerweile vermehrt und klappt auch recht gut. Vielleicht stattdessen was für die Doku.

**Comment by dergel** [comment]
ok .. in der doku fände ich diese erklärungen aber dennoch gut

**Comment by alexplusde** [comment]
Bitte Issue in der Doku aufmachen <3
