### ISSUE TITLE
Table Manager: Nach anlegen der Tabelle keine Möglichkeit, Felder hinzuzufügen

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#181]
1. Tabelle anlegen
2. Felder bearbeiten anklicken:

![image](https://cloud.githubusercontent.com/assets/3855487/19306853/e65e9ada-9077-11e6-89c1-3e194f865c22.png)

**Comment by alexplusde** [comment]
Die Tabelle wird auch nur in der rex_yform_table erstellt und nicht als Datenbanktabelle.

**Comment by skerbis** [comment]
Nach dem Cache löschen kommt: 

> "rex_sql_exception" thrown in /var/www/vhosts/redaxodemo.domain.tld/httpdocs/redaxo/src/core/lib/sql/sql.php on line 305
Error while executing statement "SHOW COLUMNS FROM `rex_dfg`"! SQLSTATE[42S02]: Base table or view not found: 1146 Table 'redaxodemo.rex_dfg' doesn't exist

#0 /var/www/vhosts/redaxodemo.domain.tld/httpdocs/redaxo/src/core/lib/sql/sql.php(1256): rex_sql->setQuery('SHOW COLUMNS FR...')
#1 /var/www/vhosts/redaxodemo.domain.tld/httpdocs/redaxo/src/addons/yform/plugins/manager/lib/yform/manager/table.php(441): rex_sql::showColumns('rex_dfg')
#2 /var/www/vhosts/redaxodemo.domain.tld/httpdocs/redaxo/src/addons/yform/plugins/manager/lib/yform/manager/table.php(75): rex_yform_manager_table::getCache()
#3 /var/www/vhosts/redaxodemo.domain.tld/httpdocs/redaxo/src/addons/yform/plugins/manager/boot.php(26): rex_yform_manager_table::getAll()
#4 /var/www/vhosts/redaxodemo.domain.tld/httpdocs/redaxo/src/core/lib/packages/package.php(228): include('/var/www/vhosts...')
#5 /var/www/vhosts/redaxodemo.domain.tld/httpdocs/redaxo/src/core/packages.php(55): rex_package->includeFile('boot.php')
#6 /var/www/vhosts/redaxodemo.domain.tld/httpdocs/redaxo/src/core/backend.php(108): include_once('/var/www/vhosts...')
#7 /var/www/vhosts/redaxodemo.domain.tld/httpdocs/redaxo/src/core/boot.php(105): require('/var/www/vhosts...')
#8 /var/www/vhosts/redaxodemo.domain.tld/httpdocs/redaxo/index.php(9): require('/var/www/vhosts...')
#9 {main}
