### ISSUE TITLE
Geoplugin: Hilfsetxte

### ISSUE THREAD

**Issue by skerbis** [yakamara/redaxo_yform#182]
1. Das Feld Names Positionsfindung sollte beschrieben werden, es ist nich klar, dass Feldnamen kommasepariert eingegeben werden sollen. Evtl. Hilfen als Popover einbauen. 
2. Bei Default wird 0.000,0.000 angezeigt. Wie ist die Reihenfolhe LAT / LNG oder umgekehrt?
3. Link zu einer Hilfeseite  zum Thema API-Key wäre sinnvoll.  (evtl. von Google: https://developers.google.com/maps/documentation/javascript/get-api-key?hl=de)

**Comment by dergel** [comment]
willst du das direkt hier ergänzen ?

https://github.com/yakamara/redaxo_yform_docs/blob/master/de_de/geo_plugin.md

das wäre super

**Comment by dergel** [comment]
vielen dank

https://github.com/yakamara/redaxo_yform_docs/commit/bea155f59e50fac0d66072f21b7aea8dbfa7f1e4

**Comment by alexplusde** [comment]
Danke @skerbis, ich backe dir zum Redaxo-Tag einen Redaxo-Taler :D

**Comment by skerbis** [comment]
hmm, lecker ... Dino-Kuchen ;-)
