### ISSUE TITLE
JSON-Attribute auch für Radio Buttons und Co.

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#185]
brauche bspw. gerade ein Pflichtfeld für Radio Buttons.

Howto:
http://stackoverflow.com/questions/8287779/html5-how-to-use-the-required-attribute-with-a-radio-input-field

**Comment by dergel** [comment]
für radio ist das nun drin - aber nicht dinge wie, nur das erste radiofeld bekommt dieses attribute etc.
