### ISSUE TITLE
submit: Es werden keine in "values" eingetragenen Daten ausgegeben

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#186]
* Tabelle erstellen
* submit-feld anlegen und dabei im value des submit-feldes irgendwas eintragen
* keine weitere Ausgabe dieses Wertes

**Comment by dergel** [comment]
hast du auch labels eingetragen ?
labels = die Werte die zu sehen ist
values = die Werte die in der DB gespeichert werden

**Comment by alexplusde** [comment]
ah... ich hatte das so verstanden, dass diesen auch das value-Attribut beeinflusst. Evtl. sollte man das Label dazu anders benennen.
