### ISSUE TITLE
Sprachabhaengige Felder zusammenfassen können

### ISSUE THREAD

**Issue by dergel** [yakamara/redaxo_yform#187]
Z.B. automatisch als Tab wenn

Feld a: name_1
Feld b: name_2
Feld c: name_3
Feld c: name_4

dabei ist die zahl der ctype

**Comment by alexplusde** [comment]
Wie ist das, wenn eine Sprache gelöscht / hinzugefügt wird? Könnte nicht ein EP sich sogar mit einklinken und YForm legt immer die passenden _id-Felder automatisch mit an?

**Comment by dergel** [comment]
könnte man machen, man müsste die felddefinitionen dann nur sehr viel tiefer in redaxo verankern, als bisher, und das ist vielleicht im moment zuviel aufwand. zunächst fände ich es aber schon gut, wenn die optik entsprechend funktioniert.

**Comment by alexplusde** [comment]
Lösungsansatz, wenn man sich von der `_1`-Notation verabschiedet und sich dem be_manager_relation-Feld widmet mit einer separaten Tabelle für alle mehrsprachigen Eingaben. 

Hier bräuchte man dann für die inline-relations eben eine weitere Darstellungsform, nämlich in Tabs statt untereinander. Alle mehrsprachigen Eingaben werden dann in einer separaten Tabelle verwaltet und lassen sich per JOIN oder per YOrm passend abfragen.

**Comment by dergel** [comment]
Das sehe ich nicht mehr. Das muss man manuell anlegen.
