### ISSUE TITLE
REX_YFORM_DATA allgemein verfügbar machen

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#188]
Scheint aktuell nur in E-Mails zu funktionieren. Bräuchte es grad für Module.

**Comment by dergel** [comment]
an welcher Stelle ? In der Ausgabe ? Es gehen im Prinzip nur Aktions.

**Comment by tbaddade** [comment]
> an welcher Stelle 

Formbuilder bei den E-Mail Angaben.

**Comment by dergel** [comment]
stimmt.. aber ich würde das sowieso lieber aus dem formbuilder entfernen. Sowieso überlege ich, alle Formulare ala Manager zu verwalten und der formbuilder wird dann zum Formselektor

**Comment by dergel** [comment]
hier gehts weiter:

https://github.com/yakamara/redaxo_yform/issues/219

das gehört irgendwie hier dazu.. Leider ist mir noch nciht klar, wie diese Ausgaben aussehen können. Weil wir bräuchten einen Filter und einen eigenen Output .. und das ist wesentlich mehr, als nur ein REX_YFORM_TABLE_DATA Feld.. oder hattest du eine andere Idee @tbaddade
