### ISSUE TITLE
YForm Seite - Tab Reihenfolge

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#189]
Vorschlag:

`Table Manager | E-Mail-Templates | Geo | Doku | Übersicht`

siehe auch https://github.com/yakamara/redaxo_xform/issues/246

**Comment by dergel** [comment]
gerne.. leider bietet das REDAXO selbst noch nicht, oder @gharlan ?

**Comment by dergel** [comment]
schliesse ich. wenn es das gibt, mache ich es gerne wieder auf

**Comment by dergel** [comment]
da es ja PlugIns sind, geht es, glaube ich, alphabetisch. im AddOn selbst ist ja zunächst nur eine page gesetzt.

**Comment by tbaddade** [comment]
Der Manger sollte kein Plugin sein.

**Comment by dergel** [comment]
ich denke auch, dass man das alles in eins packen könnte .. Mach mal ein Issue auf :)
