### ISSUE TITLE
Import von Datensätzen hat keine Funktion / Seite

### ISSUE THREAD

**Issue by skerbis** [yakamara/redaxo_yform#19]
Der Aufruf von "Tabelle importieren" ist nicht möglich. Es kommt kein Dialog dazu. 
Exportieren ist möglich. 

http://irgendeine.tld/redaxo/index.php?&page=yform%2Fmanager%2Fdata_edit&table_name=rex_irgendwas&&func=import

**Comment by dergel** [comment]
hatte .. geht nun ..
