### ISSUE TITLE
Formbuilder: Button zum Hinzufügen von Pipecode einer YForm-Tabelle

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/redaxo_yform#191]
Viele übersehen ja doch die Möglichkeit, den Pipecode aus der Tabelle zu kopieren. Fancy wäre es, per Klick aus dem Formbuilder-Modul heraus den Pipecode einer Table Manager-Tabelle zu laden. Den umgekehrten Weg - Pipecode schreiben -> Tabelle anlegen - gibt's schließlich über die action auch.

**Comment by dergel** [comment]
Ich überlege eigentlich sogar, den Pipecode komplett loszuwerden, so dass man alle Formulare immer über einen Manager aufbaut und dann das entsprechende Formular nur auswählt. Es reichen schon ein paar Formulare jetzt aus, um den Durchblick zu verlieren wo was liegt. Bin mir aber sehr unsicher ob das nicht zuviel des Guten wäre.

**Comment by alexplusde** [comment]
Also manchmal finde ich die Trennung zwischen Table Manager und Modulen schon sehr gut, auch, weil man im Backend als Label andere Begriffe in der Tabelle verwenden kann, als im Frontend.

(Bsp.: "Ihr Name" im Frontend, "Name des Kunden" im Backend)

**Comment by dergel** [comment]
das wäre dann eher eine eigene Verwaltung für Frontendformulare, so dass dort auch andere Features drin wären. Wie z.b. Actions.

**Comment by alexplusde** [comment]
Duplicate #16

**Comment by alxndr-w** [comment]
Ich glaube, das wäre inzwischen vergebene Liebesmühe.
