### ISSUE TITLE
Featurewunsch: be_medialist / mehrer Dateien aus MP wählen

### ISSUE THREAD

**Issue by darwin26** [yakamara/redaxo_yform#197]
Hi,
be_media (einzelnes Bild) ist bereits vorhanden. MediaList Auswahl finde ich leider nicht.
Danke

**Comment by alexplusde** [comment]
be_media besitzt jetzt eine Checkbox `Mehrfachauswahl`

**Comment by dergel** [comment]
https://github.com/yakamara/redaxo_yform/commit/e4efc144864b6cced3cd1188cf36d8ba40bc6100

ist aber nun angepasst - auch in den docs
