### ISSUE TITLE
Tablemanager :: Suche 

### ISSUE THREAD

**Issue by skerbis** [yakamara/redaxo_yform#198]
Die Suche scheint nur nach dem exakten Ausdruck in Text und Textareas zu suchen. 
- Wenn ich nur nach einem Wort in einer Headline suche, passiert nichts. 
- Gebe ich die komplette Überschrift ein erhalte ich ein Ergebnis.

**Comment by dergel** [comment]
MIt Wildcard "*" gehts leichter ;) .. am besten direkt in die Doku..

**Comment by skerbis** [comment]
ah ok
