### ISSUE TITLE
email validierung

### ISSUE THREAD

**Issue by wende60** [yakamara/redaxo_yform#199]
hi,

mir ist folgendes aufgefallen:

foo -> matched nicht
foo@ -> matched nicht
foo@bar -> matched

Sollte das Muster nicht zumindestens foo@bar.ab(. xy) sein? Ohne TLD gehts normal ja net...

Grüsse, Jo

**Comment by alexplusde** [comment]
https://github.com/yakamara/redaxo_yform/issues/97

Die Browser validieren clientseitig nach RFC822 und ich finde es richtig, dass YForm das auch so macht, weil dann keine Diskrepanz zwischen client- und serverseitiger Validierung auftritt. Nicht vorhandene Mail-Adressen muss man eh abfangen, an die nicht zu gestellt werden kann, muss man ja ohnehin abfangen,

(Klassiker sind Postfächer von `web.dr`- und `t-online.dr`-Nutzern :D)

Wenn ich raten müsste, würde ich vermuten, dass email@localhost eine gültige E-Mail-Adresse sein könnte.

**Comment by wende60** [comment]
glaub zwar kaum dass, email@localhost ausserhalb von Entwicklungsumgebungen genutzt wird (ich nutze es im Mamp), aber in der Tat, das ist ein Argument...

Grüsse, Jo

**Comment by dergel** [comment]
auch wenn es etwas komisch wirkt.. denke auch, dass es passt.. dennoch danke für den hinweis.
