### ISSUE TITLE
Tableset import: Fehler "kein JSON / fehlerhafte Datei" trotz .json Datei 

### ISSUE THREAD

**Issue by omphteliba** [yakamara/redaxo_yform#201]
Wenn ich in yForm 2.0 unter Redaxo 5.2 im Table Manager ein Tableset exportiere und das gleiche unverändert dann wieder importieren möchte, bekomme ich folgende Fehlermeldung:

`Es wurde keine .json Datei verwendet, oder die Datei war fehlerhaft.`

Ihr werdet euch denken: wer will das machen? Ich bin darauf gestoßen, als ich die gleiche Fehlermeldung bei einem Import eines unter Redaxo 4.6.2 / xForm 4.14 exportierten Tablesets bekam und versuchte raus zu finden wann der Fehler gezeigt wird.

**Comment by dergel** [comment]
klappt nun wieder.
