### ISSUE TITLE
JSON-Ausgabe in der Formularcode PHP-Variante fehlerhaft

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#204]
Ist:
`$yform->setValueField('text', array("email","E-Mail-Adresse","","","{"type":"email","required":"required"}"));`

soll:
`$yform->setValueField('text', array("email","E-Mail-Adresse","","",'{"type":"email","required":"required"}'));`
(man achte auf die Anführungszeichen)

**Comment by dergel** [comment]
alles ist nun single quote .. damit sollte es auch hier passen.

**Comment by alexplusde** [comment]
einfache Anführungszeichen sollten in der PHP-Notaion noch escaped werden:

Eingabe: `{"onclick":"alert('Hallo Welt')"}`
Ausgabe ist (PHP): `$yform->setValueField('radio', array('testradio','testradio','1,0','0','{"onclick":"alert('Hallo Welt')"}'));`
Ausgabe soll (PHP): `$yform->setValueField('radio', array('testradio','testradio','1,0','0','{"onclick":"alert(\'Hallo Welt\')"}'));`

**Comment by dergel** [comment]
kannst du das prüfen ob ok so ?

**Comment by alexplusde** [comment]
getestet und für gut befunden.
