### ISSUE TITLE
rex_yform_manager_dataset verwenden - wie?

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#205]
Hallo allerseits,

ich habe gesehen, dass sich die Funktionen des Table Managers zum Bearbeiten neuer Datensätze auch direkt ansprechen lassen, bspw.:

```
<?php
 $var = rex_yform_manager_dataset::get(512,"rex_yf_employees");
 $var->setValue('name', "Mustermann");
 $var->save());
?>
```

Gibt es dazu Beispiele oder eine kurze Erklärung, wie man Datensätze sucht, hinzufügt, ändert oder löscht?

Für ein Projekt wäre es gerade wichtig, dass alle Änderungen (auch bspw. im Frontend) über den Table Manager ablaufen - und dann bspw. Felder wie datestamp automatisch aktualisiert werden, oder ein Datensatz in der History-Tabelle landet.

Erläuterungen zum Usecase kann ich gerne noch formulieren, falls notwendig.

**Comment by gharlan** [comment]
Ein bisschen was steht hier schon:
https://github.com/yakamara/redaxo_yform_docs/blob/master/de_de/yorm.md

Insbesondere, wie man eigene Model-Klassen erstellen kann. Dann braucht man die Table nicht mehr angeben, und kann die Klasse um weitere Methoden ergänzen. Sobald man die Klasse registriert hat, bekommt man für die Datensätze der entsprechenden Tabelle immer Objekte der Model-Klasse, statt der Basis-dataset-Klasse.

Dein Beispiel oben wäre ja die Variante, einen Datensatz per ID abrufen, und ändern.
Wichtig zu wissen ist, dass `save()` die Validierungen durchläuft, die im Manager hinterlegt wurden, und bei Fehlern das Speichern ablehnt.

Neue Datensätze erzeugt man mit `rex_yform_manager_dataset::create($table)`, und ab da dann genauso wie beim Ändern von Datensätzen.

Löschen geht per `->delete()`.

Datensätze finden:
`rex_yform_manager_dataset::query($table)` liefert ein Objekt der [Query-Klasse](https://github.com/yakamara/redaxo_yform/blob/master/plugins/manager/lib/yform/manager/query.php), die bietet verschiedene Methoden, um die Abfrage zusammen zu stellen (`where()` etc.).

Mit `findOne()` oder `findId()` bekommt man einen einzelnen Datensatz, mit `find()` eine [Collection](https://github.com/yakamara/redaxo_yform/blob/master/plugins/manager/lib/yform/manager/collection.php). Die kann man wie ein Array mit `foreach` durchlaufen, und sie bietet auch Methoden, um die Collection (alle Datensätze) gemeinsam zu bearbeiten (`setValue`, `save`, `delete`).

Zwei Beispiele zur Nutzung der Query-Klasse sind auch in der Doku.

**Comment by dergel** [comment]
@alexplusde es wäre ein Traum (zumindest für mich ;) ), wenn du das in der Doku ergänzen könntest

**Comment by alexplusde** [comment]
Mein Traum wäre es, wenn ich das alles auf Anhieb verstehen würde @dergel :D

Ich werde also Fragen stellen und dann gerne die Beispiele dazu dokumentieren.
