### ISSUE TITLE
ToolsPlugin: daterangpicker Speicherart 

### ISSUE THREAD

**Issue by olien** [yakamara/redaxo_yform#206]
Kann es sein, dass der daterangpicker die Daten zusammen in einen String speichert?
Ist das sinnvoll für die weitere Bearbeitung?

LG
Oliver

**Comment by dergel** [comment]
Er speichert das in einem String. Ich benutze das nur für Suche im Backend bei Datumsfeldern. Es ist eigentlich gar nicht vorgesehen das auch wirklich bei Speicherungen zu nutzen. Wüsste im MOment auch keine sinnvolle Speicherart @gharlan Wir würde man das sinnvoll speichern ? Hast du eine Idee ?

**Comment by olien** [comment]
Also ich wollte das für von-bis Termine nutzen. Ist dann umständlicher mit den Daten zu arbeiten als mit zwei Date Feldern (zumindest für mich)...

**Comment by dergel** [comment]
dann muss du dasv eher in zwei felder anlegen, dort jeweils nach eine datum abfragen und eine validate rein, so dass das das "bis"-feld nicht kleiner ist. ich denke wir brauen dafür im moment kein neues features..
