### ISSUE TITLE
Yorm - select - Defaultstatus wird nicht übernommen, wenn leer

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#208]
Betrifft bspw. Yorm

Der Default-Status sollte eingetragen werden, wenn ich dem Feld keinen Wert übergebe.

**Comment by dergel** [comment]
weniger ein Yorm Problem, als eins von select selber, wir auch select_sql

Bei Singleselect kein Problem - finde ich auch sinnvoll.

Bei Multipleselect schon schwieriger - weil ja jemand eventuell sagt, dass er nichts auswählen wollte und deswegen eine default-Festsetzung nicht passt.

**Comment by dergel** [comment]
@alexplusde kannst du das testen ? Ich konnte nciht alle Fälle gegenprüfen und auch einen Yorm-Test habe ich nicht gemacht .. sollte aber gehen :)

**Comment by tyrant88** [comment]
geht nicht:
ein select Feld im Tablemanager:
Ja=1,Nein=0
default: 0

ergibt einen Standardwert von "Ja"
