### ISSUE TITLE
Geotagging

### ISSUE THREAD

**Issue by skerbis** [yakamara/redaxo_yform#21]
Wird es das Plugin wieder geben?

**Comment by dergel** [comment]
soll es eigentlich .. hat nur keine Prio im Moment

**Comment by skerbis** [comment]
Könnte es gerade gut gebrauchen. - Schade. Dann lasse ich es Google erledigen.

**Comment by dergel** [comment]
du weisst ja wie es ist - als Auftrag - immer - gerne.. Nur leider gibt es so viele andere freie Sachen, die wir gerade machen, können nicht die ganze Zeit dafür aufwenden.. leider ..

**Comment by skerbis** [comment]
Wenn es nicht all zu viel kostet, packe es in den bestehenden Auftrag oder ruf mich an :-)

**Comment by dergel** [comment]
ist nun drin .. muss noch aufgehübscht werden.

**Comment by dergel** [comment]
ist aufgehübscht - irgendwie ;) ..
