### ISSUE TITLE
index feld erweitern - relationsfelder mit aufnehmen und deren unterfelder

### ISSUE THREAD

**Issue by dergel** [yakamara/redaxo_yform#212]

**Comment by alexplusde** [comment]
Wie wird das funktionieren?

**Comment by gharlan** [comment]
https://github.com/yakamara/redaxo_yform/blob/ab89667898b0570e34b67ce8ed7951bf89c0d370/lang/de_de.lang#L94

**Comment by gharlan** [comment]
Zu beachten ist, dass zurzeit das Feld **nicht** aktualisiert wird, wenn sich die anderen Datensätze ändern, nur wenn man "diesen" Datensatz neu speichert.

**Comment by gharlan** [comment]
Es gehen übrigens auch tiefere Verschachtelungen, wie zum Beispiel: `category_id.tags.name`.
Also die Namen der Tags, die der in dem aktuellen Datensatz ausgewählten Kategorie zugewiesen sind.
