### ISSUE TITLE
be_manager_relation macht sql Fehler

### ISSUE THREAD

**Issue by dtpop** [yakamara/redaxo_yform#215]
Ich bekomm in einer Tabelle, die über eine Tabelle verknüpft ist (http://www.redaxo.org/de/forum/addons-packages-f43/yform-echte-tabellenrelationen-t21497.html) eine Fehlermeldung, wenn ich einen leeren Datensatz hinzufüge:

`Error while executing statement "DELETE FROM `rex_wmv_items_to_categories` WHERE `item_id` =7 AND `category_id` NOT IN ()"! SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1
#0 /www/muster.de/redaxo/src/core/lib/sql/sql.php(790): rex_sql->setQuery('DELETE FROM `re...', Array)
#1 /www/muster.de/redaxo/src/addons/yform/plugins/manager/lib/yform/value/be_manager_relation.php(216): rex_sql->delete()
`

Wenn ich in Zeile 214 der be_manager_relation.php ein

`if ($values) { ... }`

mache, dann funktioniert es. Auch alle anderen Funktionen sind nicht beeinträchtigt.

**Comment by gharlan** [comment]
Ist bereits gefixt: https://github.com/yakamara/redaxo_yform/commit/dc289c1209d337f3b4f8790e1ccdaf81c73ad082
