### ISSUE TITLE
Widget :: REX_YFORM_LINK

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#219]
Arbeitet wie `REX_LINK[id=1 widget=1]` zeigt aber die Datesätze an, so dass man direkt zu einem Datensatz verlinken kann.

**Vorschlag**
`REX_YFORM_LINK[id=1 widget=1 table=rex_yform_table]`

**Comment by skerbis** [comment]
Würde dann die ID zurückliefen?  Cool wäre auch eine Linklist.

**Comment by tbaddade** [comment]
> Würde dann die ID zurückliefen oder gar ein Array des Datensatzes?

In der Modulausgabe könnte es dann so aussehen

`REX_YFORM_LINK[id=1 table=rex_yform_table output=id | dataset]`


> Cool wäre auch eine Linklist.

könnte man dann gleich mit erstellen.

**Comment by dergel** [comment]
habe etwas eingebaut .. kann gerne getestet werden:

REX_YFORM_TABLE_DATA[id=1 output="widget" table="rex_ycom_user" field="email"]
REX_YFORM_TABLE_DATA[id=2 output="listwidget" table="rex_ycom_user" field="email"]

Ausgabe ist im Moment nur die ID/s .. und die Werte werden Quasi in die REX_VALUE gespeichert.

**Comment by dergel** [comment]
REX_YFORM_TABLE_DATA[id=1] für die ausgabe die dann entweder eine id oder eine kommaliste durchgibt. Was für Ausgaben könnte man sich noch vorstellen ? vielleicht auch field, und dann entsprechend eine kommaliste der Feldwerte ?

**Comment by dergel** [comment]
Wenn das abgestimmt ist - müsste das auch in die Doku - sonst wirds schwierig :) @alexplusde @skerbis 
Aber erst durchgehen ob das so passt

**Comment by dergel** [comment]
jemand zeit das zu testen ? @skerbis

**Comment by skerbis** [comment]
Morgen

**Comment by skerbis** [comment]
Hi, gut wäre wenn man bei der Auswahl nicht nur ein Feld sehen würde sondern 2. Bei einer Newsauswahl möchte man ggf. auch das Datum sehen oder nach diesem sortieren. 
**Vielleicht so?**
REX_YFORM_TABLE_DATA[id=1 output="widget" table="news" **view="date,titel"** field="titel"]

Unschön: Das Link-Feld zeigt initial [id=] 

![bildschirmfoto 2017-01-25 um 10 36 48](https://cloud.githubusercontent.com/assets/791247/22285136/bfe3fdf8-e2ea-11e6-9322-e520e5b0a690.png)

Wird es den Picker auch im Tablemanager als Feld geben?

**Comment by dergel** [comment]
war noch ein fehler, deswegen gingen feldkombinationen nicht .. also statt nur einem feld wie in deinem Beispiel titel, kannst du nun auch CONCAT Kombinationen einsetzen .. z.b.

REX_YFORM_TABLE_DATA[id=1 output="widget" table="news" field="titel,'/',email"]

>Wird es den Picker auch im Tablemanager als Feld geben?

das ist exakt was be_relation_manager macht .. also ist bereits da.

gerne nochmal durchtesten.. denke aber, dass wir damit durch sind ..

**Comment by skerbis** [comment]
👍

**Comment by dergel** [comment]
@skerbis also klappt alles und ist gut ?

**Comment by skerbis** [comment]
Danke, perfekt

**Comment by skerbis** [comment]
Kurze Frage, gibt's das auch als multiple also auch als List?
