### ISSUE TITLE
InnoDB / MyISAM

### ISSUE THREAD

**Issue by polarpixel** [yakamara/redaxo_yform#22]
Yform legt Tabellen in MyISAM an. Sollte aber hier wohl in InnoDB sein.

**Comment by dergel** [comment]
Das frage ich mich auch oft - ob wir nicht immer eher InnoDB verwenden sollten. Bin mir aber selbst unsicher .. Was ich leider so gar nicht mag wenn man sich das aussuchen könnte .. das würde nur wahnsinnig machen .. Auch die Frage mit ist wäre - ob man YForm-tabellen dann immer automatisch anpassen müsste. Also wenn vorher InnoDB, dann nachher MyISAM .. 

Wegen InnoDB fallen mir gute Features für die YForm ein - gerade auch wegen der Transaktionsmöglichkeit...

@gharlan @staabm @tbaddade was meint ihr ?

**Comment by gharlan** [comment]
Der Core und alle System-Addons nutzen seit R5 InnoDB.

**Comment by gharlan** [comment]
Dementsprechend sollten das auch alle anderen Addons machen, wenn sie keine tatsächlichen Gründe für MyISAM haben.

**Comment by staabm** [comment]
ich würde auf keinen fall zulassen, dass das der user ändern kann. 99% der user wüssten sowieso nicht warum sie das eine oder das andere nehmen sollten.

**Comment by tbaddade** [comment]
Ich bin da bei euch. Wenn einer MyISAM haben will, muss er das für sich ändern. Ansonsten sollte das verwendet werden, was der Core vorgibt bzw. empfiehlt.

**Comment by dergel** [comment]
ok InnoDB kllingt gut .. was meint Ihr mit vorhandenen Tabellen - z.B. wenn YForm Tabellen migriert ? Gleich in InnoDB umwandeln ?

**Comment by staabm** [comment]
@dergel  von myisam nach innodb geht das, umgekehrt nicht.

**Comment by dergel** [comment]
dann würde das ja passen..

**Comment by dergel** [comment]
allgemeine einstellungen sind auf innodb gesetzt.. updte muss noch beachten werden und auch das vorhandene tabellen, wenn sie von der yform genutzt werden, adaptiert werden.

**Comment by dergel** [comment]
ich bin mir nun doch unsicher ob man das festlegen sollte oder nicht optional halten sollte. Wir hatten ein paar mal das Problem, dass zu viele Felder in einer Tabelle mit der innodb nicht funktionierte sondern ausschliesslich mit myisam.. das machts irgendwie nicht leichter.. hmm

**Comment by dergel** [comment]
ist bereits alles auf innodb

**Comment by tbaddade** [comment]
Gab es hier nicht mal Probleme, sodass wir für einzelne Tabellen von innodb manuell wieder auf myisam gewechselt sind?
