### ISSUE TITLE
Blättern / Pager im Manager

### ISSUE THREAD

**Issue by dergel** [yakamara/redaxo_yform#220]
Semigeil ;) ..

![bildschirmfoto 2016-11-30 um 18 38 13](https://cloud.githubusercontent.com/assets/322951/20763875/2f364e1c-b72c-11e6-8ccb-8f17875a04ba.png)

**Comment by gharlan** [comment]
Das schlage ich aber locker:

![screenshot 2016-12-02 17 08 48](https://cloud.githubusercontent.com/assets/330436/20840877/07c999d8-b8b2-11e6-9967-ba2d7b7ed9c5.png)

**Comment by tbaddade** [comment]
Das reicht nicht ganz @gharlan 

![screenshot 2016-12-02 17 34 21](https://cloud.githubusercontent.com/assets/338267/20841837/8ed9857a-b8b5-11e6-9b19-b6d5eb7b86b5.png)

**Comment by skerbis** [comment]
Haut das ganze in ein select2

**Comment by skerbis** [comment]
oder das hier: http://flaviusmatis.github.io/simplePagination.js/

**Comment by tbaddade** [comment]
Ich würde da eher das Fragment anpassen. Das müsste m.E. auch die Strukturartikel betreffen.

**Comment by alexplusde** [comment]
Was für ein Penisvergleich hier...

**Comment by skerbis** [comment]
Na na na

**Comment by gharlan** [comment]
Was haltet ihr von dem Ding: http://auxiliary.github.io/rpage/
Dann muss man sich nicht auf eine Anzahl von angezeigten Pages festlegen, sondern es reduziert sich automatisch je nach Breite.

@tbaddade Und ja, ist eigentlich ein Redaxo-Issue, wird also im Core gefixt.

**Comment by gharlan** [comment]
Mit Jan besprochen, nehmen das Teil nicht, sondern doch eine fixe Anzahl von Seiten.

**Comment by skerbis** [comment]
@gharlan was meinst du mit fixe Anzahl?

**Comment by gharlan** [comment]
Zum Beispiel immer 5 Seiten anzeigen in der Pagination.

**Comment by skerbis** [comment]
Ok. aber eine Direktwahl zu einer bestimmten Seite (per Select oder Eingabefeld)  würde ich als nützlich empfinden.

**Comment by gharlan** [comment]
Braucht man das wirklich? Kann mich nicht wirklich erinnern, dass ich sowas mal irgendwo selbst genutzt hätte.
Es ist jedenfalls eigentlich nicht geplant.

**Comment by skerbis** [comment]
Na ja, wenn ich mir Eure Zahlenkolonnen so ansehe....

**Comment by gharlan** [comment]
Unserer Meinung wird da keiner gezielt Seite 712 ansteuern wollen, sondern man wird mittels Suche arbeiten.

**Comment by gharlan** [comment]
https://github.com/redaxo/redaxo/commit/d290d22f625fbe77172d888fb93459a7a5fd070e
