### ISSUE TITLE
Manager :: Leserecht für Tabellen und Datensätze

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#221]
Aktuell hat man immer Schreibrechte. Reines Leserecht der Tabellen oder der Datensätze existiert nicht.

Bsp.
- Es existieren **Tabelle A** und **Tabelle B**
- **B** hat ein `be_relation` auf **A**
- Redakteur besitzt nur das Recht für **B**.
- In der Suche erscheint das Widget für die Relation. Klick auf das **+** öffnet sich das Popup mit einer weißen Seite

Das passiert deshalb, da der Redakteur kein Recht für **A** besitzt.

Aktuell hilft nur, aus dem `be_relation` ein `select_sql` zu machen

**Comment by dergel** [comment]
Reines Leserecht existiert bereits. Datensätze lesend machen. den anderen Part versuche ich mit diesem Issue anzugehen

https://github.com/yakamara/redaxo_yform/issues/1162
