### ISSUE TITLE
YForm E-Mailtemplates kann keinen XML Inhalt erstellen wenn PHP Short Tag erlaubt ist

### ISSUE THREAD

**Issue by TobiasKrais** [yakamara/redaxo_yform#223]
Wenn der Body eines YForm E-Mailtemplates mit xml anfängt, z.B. `<?xml version="1.0" encoding="UTF-8"?>` gibt es beim Absenden des Formulars einen Fatal error. Grund ist das öffnende `<?` wenn in den PHP Einstellungen der Short Tag erlaubt ist.

**Comment by alexplusde** [comment]
Das ist doch dann ein Problem, das losgelöst von YForm ist?

**Comment by TobiasKrais** [comment]
Ja. Kann aber YForm damit umgehen lernen?

**Comment by gharlan** [comment]
Schwierig.
Falls du Short-Tags nicht deaktivieren möchtest, kann du das Problem so umgehen:
```php
<?= '<?xml version="1.0" encoding="UTF-8"?>' ?>
```

**Comment by TobiasKrais** [comment]
Ich hab sie Short Tags jetzt deaktiviert und es funktioniert. Dein Vorschlag ist auch eine sehr gute Idee. Vielleicht könnte man in der Doku darauf hinweisen, dass PHP Code erlaubt ist.

**Comment by tbaddade** [comment]
> Vielleicht könnte man in der Doku darauf hinweisen, dass PHP Code erlaubt ist.

steht sogar direkt bei den E-Mail-Templates im blauen Infokasten. `Grundsätzlich ist auch PHP erlaubt`

**Comment by TobiasKrais** [comment]
Oh man, das steht da sogar dick unterstrichen. Wenn man dann noch den Schluss daraus zieht, dass ein XML Start Tag genauso anfängt wie ein PHP Short Tag ist man echt im Vorteil. Sorry, dass ich eure Zeit in Anspruch genommen habe. Danke für eure Geduld!
