### ISSUE TITLE
E-Mailtemplate: Absender REX_YFORM_DATA[field="email"] nicht setzbar

### ISSUE THREAD

**Issue by TobiasKrais** [yakamara/redaxo_yform#224]
In einem E-Mailtemplate lässt sich der Absender nicht mit Werten aus dem Formular bestücken, z.B. REX_YFORM_DATA[field="email"]

**Comment by tbaddade** [comment]
Richtig. Daten aus dem Formular sollten nur im Body und nicht im Header einer E-Mail gesetzt werden.

**Comment by TobiasKrais** [comment]
Im XForm ging das noch. Toll wäre es, wenn als Absender die Kontakt E-mailadresse gesetzt werden könnte. Grund: mein Kunde möchte beim Kontaktformular auf Antworten klicken um dem Kunden zu antworten.

**Comment by alexplusde** [comment]
Eine gute Idee ist das meines Wissens nicht, weil eine Absender-Adresse, die vom Versand-Postfach abweicht, ein eindeutiger Indikator für Spam-Mails ist.

Wenn, dann müsste man einen Wert für reply-to übergeben können.

**Comment by TobiasKrais** [comment]
Wenn im PHPMailer als Versandart mail oder sendmail eingestellt ist, wird sowieso irgendeine Adresse gesetzt, die ich definiere. Ob es sie gibt oder nicht. Empfänger ist normalerweise eine E-Mailadresse meiner Domain. Die Nachricht von YForm wird also nicht als SPAM deklariert, weil sie vom selben System stammt.

Zentral ist aber der Kundenwunsch: er möchte auf Antworten klicken und nicht erst per copy&paste die E-Mailadresse setzen. Gibt es denn wenigstens die Möglichkeit eine "Antwort An:" Zeile bei E-Mailtemplates zu setzen?

**Comment by alexplusde** [comment]
müsste eigentlich als PR relativ einfach umzusetzen sein:

Hier Feld "subject" duplizieren und in replyto umbenennen: 
https://github.com/yakamara/redaxo_yform/blob/407b85f7d95e010d4568f04e7aea51381ba40f61/plugins/email/pages/index.php#L31

Da Feld dann hier berücksichtigen:
https://github.com/yakamara/redaxo_yform/blob/75ef108a262e70560c442535e17c4079b0a96b52/plugins/email/lib/yform_email_template.php#L48 und 
https://github.com/yakamara/redaxo_yform/blob/75ef108a262e70560c442535e17c4079b0a96b52/plugins/email/lib/yform_email_template.php#L60

Da den Wert abfragen
https://github.com/yakamara/redaxo_yform/blob/75ef108a262e70560c442535e17c4079b0a96b52/plugins/email/lib/yform_email_template.php#L98

**Comment by TobiasKrais** [comment]
Würde das YForm Team die Umsetzung des Vorschlags unterstützen?

**Comment by dergel** [comment]
Auch wenn ich das etwas kritisch finde, könnte man das einbauen. Verantwortung hat ja jeder selbst das sinnvoll einzusetzen und nicht "Komisches" einzusetzen.

**Comment by tbaddade** [comment]
> Auch wenn ich das etwas kritisch finde

Wäre es nicht sinnvoller es so zu belassen wie es ist und dadurch die Leute auch ein wenig vor Fehlern zu schützen?

**Comment by TobiasKrais** [comment]
Unsere Frage sollten nicht unsere Wünsche sein, sondern das, was der Kunde wünscht.
Und: was ist benutzerfreundlich?
Andere CMS können bei Formularen den Absender einstellen, oder zumindest die Antwort-An Adresse. Wollen wir mit Redaxo da hinten dran bleiben?

**Comment by alexplusde** [comment]
Also, wer was komisches damit machen will, der bekommt das auch ohne YForm hin. 

Das Feld mit einer zusätzlichen Description auszustatten, würde nicht nur die Leute vor Fehlern schützen, sondern ihnen gleichzeitig auch erklären, wie das sinnvoll eingesetzt werden sollte und wie nicht.

**Comment by TobiasKrais** [comment]
Danke! Vielen Dank!

**Comment by alexplusde** [comment]
Das Issue ist in meinen Augen unzureichend gelöst, da replyto nicht verwendet wird. Darum ging's ja eigentlich.

**Comment by TobiasKrais** [comment]
Es wird direkt der Absender gesetzt der automatisch der replyto ist.
