### ISSUE TITLE
Email Validierungs Fehler

### ISSUE THREAD

**Issue by lexplatt** [yakamara/redaxo_yform#225]
Wir haben bemerkt dass es mit der aktuellen Validierung möglich ist eine Email mit folgenden Pattern zu verwenden: `email@domain`

@dergel weshalb verwendet ihr für die Validierung nicht die Methode filter_var von PHP?

> **Datei**: redaxo_yform/lib/yform/validate/email.php 
> **Zeile**: 24

PHP filter_var wäre:
`if (!filter_var($Object->getValue(), FILTER_VALIDATE_EMAIL))`

**Comment by gharlan** [comment]
Soweit ich weiß, unterstützt `filter_var` keine UTF8-Email-Adressen.

**Comment by lexplatt** [comment]
wie es aussieht unterstützt das der reguläre Ausdruck aber auch nicht

**Comment by alexplusde** [comment]
Duplikat
https://github.com/yakamara/redaxo_yform/issues/199
