### ISSUE TITLE
Gleicher Sprunganker bei 2 oder mehr Formularen in einem Artikel

### ISSUE THREAD

**Issue by bega011** [yakamara/redaxo_yform#226]
Wenn man 2 oder mehr Formulare in einem Artikel hat und bei jedem einen anderen/unterscheidlichen Sprunganker mit $yform->setObjectparams('form_anchor', 'anker-xy') definiert, wird bei Submit immer der erste Sprunganker angesprungen, egal welche Form man submited hat. Die Fromulare sind in den unterschiedlichen Slices.
redaxo 5.2.0 yform 2.0

**Comment by dergel** [comment]
das ist wohl eher ein verständnisproblem

mit dem form_anchor setzt man den anker in der aktion. Ob der Anker wirklich vorhanden ist, ist eine andere Frage,

Du kannst, und solltest auch bei mehreren Formularen auf einer Seite, eine Kennung mit "form_name" hinterlegen. Dieser form_name wird dann auch direkt als id im form tag gesetzt.

**Comment by alexplusde** [comment]
@olien

**Comment by alexplusde** [comment]
@bega011 gibt's hier Erklärungsbedarf? Wie findest du den Abschnitt in der Doku dazu? Sollte es ggf. ein kleines Howto geben?

**Comment by bega011** [comment]
eigentlich habe ich alles richtig gemacht und die (unterschiedlichen) Anker waren bei jedem Formular gesetzt ($yform->setObjectparams('form_name','anker-xy')) und als Action richtig definiert ($yform->setObjectparams('form_anchor', 'anker-xy')), also kein Verständnisproblem. Ich hatte 3 Formulare auf einer Seite und das ganze mit Community am laufen. Wie gesagt der Sprung hat schon funktioniert aber immer zum letzten Anker auf der Seite. Wenn ich das letzte Formular auf offline gestellt habe, ging dann zum Vorletzten. Ich kann da Problem leider nicht mehr rekonstruieren, da die Webseite online gehen musste und ist ja eine geschlossene Community, musste ich es halt anderweitig lösen. 
@alexplusde Die Doku finde ich richtig Klasse, das hat mir extrem viel geholfen. Obwohl du schon großen Lob in Wackershofen bekommen hast, an dieser Stelle noch mal herzlichen Dank ;)

**Comment by alexplusde** [comment]
Kannst du es vlt. trotzdem nochmal austesten, weil Oliver auch ein ähnliches Problem hatte? Entweder es ist ein Bug, oder vlt. auch nicht, dann müsste man es besser erklären.

**Comment by bega011** [comment]
Jup, kann nächste Woche eine Kopie von der Seite erstellen und austesten, dann können wir uns das anschauen.

**Comment by dergel** [comment]
bei meinen tests ging es ... gerne ein kopie erstellen und ich schaue es mir an.

**Comment by bega011** [comment]
Ok, habs bei der Kopie getestet, hats auch gut funktioniert. Sowohl beim Sprung zum Anker im Formular als auch zum anderen in Div-Container. Vielleicht lag es an der Konstellation zum Zeitpunkt. Was allerdings nicht funktioniert ist wenn man 2 redirects mit 2 Anker auf der selben Seite hat, dann wird immer der letzte genommen, aber das wäre ne andere Geschichte. 
Kann also geschlossen werden, sorry.
