### ISSUE TITLE
be_manager_relation: Zuordnung nicht möglich, wenn Feld befüllt

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#227]
Ein spezieller Randfall, den ich hier protokollieren und zur Diskussion stellen will:

Ein Feld `color_ids` war bereits vorbefüllt mit Werten, bspw. `1,2,5,8`. Es wurde nachträglich gelöscht und dann ein `be_manager_relation`-Feld mit Relationstabelle daraus gemacht.

Das Problem ist dann, dass das Relations-Feld nicht gespeichert werden kann, wenn sich im Tabellen-Feld noch Werte befinden. Erwartet hätte ich, dass diese Werte eigentlich gar nicht mehr berücksichtigt werden, oder, dass diese beim Abspeichern geleert werden.

Problemlösung war dann ein `UPDATE tabellenname SET color_ids = ""`.

**Comment by tbaddade** [comment]
Hattest du vor dem Speichern im Select auch Optionen ausgewählt?

**Comment by alexplusde** [comment]
ja.

**Comment by gharlan** [comment]
Das scheint mir inzwischen gelöst worden zu sein, wahrscheinlich durch https://github.com/yakamara/redaxo_yform/commit/e2b07d335460f2df5fac189948dd87f85e24825e#diff-989ec6ace7bc55ab3aaf7fdd97c6e970
