### ISSUE TITLE
be_manager_relation mit relation table auf eine Tabelle

### ISSUE THREAD

**Issue by dtpop** [yakamara/redaxo_yform#228]
Ich habe versucht über eine Verknüpfungstabelle auf die gleiche Tabelle zu referenzieren, um eine "Siehe-auch"-Funktion zu implementieren.
Dabei wird aber das Relationsfeld in der Verknüpfungstabelle nicht gefüllt. Der Wert für die Verknüpfung wurde ins Feld für den Datensatz geschrieben, das Relationsfeld blieb leer.
$relationTableField['source'] und $relationTableField['target'] in be_manager_relation->postAction haben den gleichen Wert.

**Comment by alexplusde** [comment]
Kannst du mir die Feldkonfiguration als Screenshot posten?

**Comment by dtpop** [comment]
1. Konfiguration für Items
![bildschirmfoto 2016-12-28 um 10 14 33](https://cloud.githubusercontent.com/assets/1282121/21518458/e37a30c6-cce6-11e6-887f-7275c04c4c81.png)
2. Konfiguration für Item->Id
![bildschirmfoto 2016-12-28 um 10 15 28](https://cloud.githubusercontent.com/assets/1282121/21518457/e3798310-cce6-11e6-9160-823e57ff4ac1.png)
3. Konfiguration für Item->Relation
![bildschirmfoto 2016-12-28 um 10 15 53](https://cloud.githubusercontent.com/assets/1282121/21518459/e37a5c5e-cce6-11e6-97de-313ac4d0f596.png)
Ich habe es auch mit einem Patch hin bekommen, dass es funktioniert, stecke aber nicht tief genug im relation manager, als dass ich behaupte könnte, dass das die Lösung ist (bitte nicht nachmachen!).
Zeile 450 ff:
            if (reset($source)->getName() == reset($target)->getName()) {
               return array('source' => reset($source)->getName(), 'target' => next($target)->getName());
            }

**Comment by alexplusde** [comment]
Verstehe. Es hätte vermutlich nur funktioniert, wenn du keine Relationstabelle verwendet hättest, sondern die IDs nur in das `rex_wmv_items.see_also`-Feld geschrieben hättest. Das hatte ich schon mal so benutzt.

Scheint also wirklich ein Bug zu sein.

Als Quick-and-Dirty-Lösung hättest du evtl. an der Datenbank eine `VIEW` zu `rex_wmv_items` erstellen können. Dann hättest du in der Relations-Tabelle zwei verschiedene Tabellen angeben können, statt 2x die gleiche zu verknüpfen. Dabei bliebe der Code von YForm unverändert und updatefähig.
