### ISSUE TITLE
kein no_db bei radio - yform Version 2.0

### ISSUE THREAD

**Issue by brandes-webdesign** [yakamara/redaxo_yform#229]
Es gibt beim radio kein no_db.
radio|name|label|Frau=w,Herr=m|[defaultwert]|

Kann man das noch mit aufnehmen, bzw. gibt es ein Möglichkeit das selbst einzubauen.

**Comment by alexplusde** [comment]
In den Value-Klassen hierzu müsste man sich sehr leicht an anderen Feldern orientierten können. Willst du es selbst versuchen?

**Comment by brandes-webdesign** [comment]
Hallo Alex,
danke für den Hinweis.
Im Code habe ich gesehen, dass es beim radio noch mehr Felder gibt.
Lag also an Fehlbenutzung durch mich, bzw. der Kommentar ist nicht ganz vollständig.

Der Kommentar müßte so aussehen. 
radio|name|label|Frau=w,Herr=m|[defaultwert]|[attributes]|[notice]|[no_db]

Vielleicht kann das ja jemand fürs nächste Update aufnehmen und das den Issue hier schließen.

Nochmal Danke für Deine Hilfe und bis in einer Woche zum Redaxo-Tag
