### ISSUE TITLE
Multi-Upload für be_media im Table Manager

### ISSUE THREAD

**Issue by chip75** [yakamara/redaxo_yform#231]
Folgende Funktion hätte ich gern

1. Upload von Bildern in den Medienpool direkt über TableManager/Dataedit 
2. als Multiupload mit Drag & Drop
3. Automatische Anlage von Ordnern im Medienpool mit der ID des Datensatz (Problematisch wenn noch keiner angelegt worden ist)
4. (optional) Übernahme des Titels aus Dateiname.

Das Value Feld muss demnach gar keine direkte Verknüpfungsmöglichkeit mit dem Medienpool für den Nutzer anbieten. D.h. es werden pro Datensatz eigentlich alle Dateien aus diesem in Schritt 3 angelegten Ordner genutzt. Die Handhabung könnte aber ähnlich dem Widget für den Medienpool Upload sein.

**Comment by alexplusde** [comment]
@dergel kannst mich assignen. Ich bin an einer Umsetzung.

**Comment by dergel** [comment]
das sehe ich da nicht, mit ein Grund weswegen ich auch mediafile gelöscht habe. Upload in den Medienpool, immer darüber, Multiupload müsste dann dort verwendet werden
