### ISSUE TITLE
fehlende Übersetzung yForm

### ISSUE THREAD

**Issue by polarpixel** [yakamara/redaxo_yform#233]
Der Screenshot zeigt die Ansicht, wenn die Backendsprache auf englisch gestellt ist.

![2017-01-14_16-42-42](https://cloud.githubusercontent.com/assets/330160/21956076/a4facb0e-da78-11e6-90e7-ff488e89b45b.png)

**Comment by dergel** [comment]
diesen Fall habe ich bereinigt . aber es fehlen noch viele Übersetzungen. Freue mich über PRs :)

**Comment by alexplusde** [comment]
hat hier jemand "@schuer" gesagt?
