### ISSUE TITLE
rex_yform_history_field – Problem wg. Fremdschlüssel

### ISSUE THREAD

**Issue by telonios** [yakamara/redaxo_yform#234]
Es existiert ein Problem mit dem Export und Import der DB unter Redaxo Backend. Das Problem entsteht bei der Tabelle rex_yform_history_field mit Fremdschlüssel. Wenn die beiden yform_history Tabellen beim Export weglassen werden, lässt sich die Datenbank problemlos wieder importieren.

![bildschirmfoto 2017-01-17 um 11 14 14](https://cloud.githubusercontent.com/assets/20573559/22018557/a9c6313a-dcaf-11e6-8dac-84574a761ca0.png)

**Comment by telonios** [comment]
Das Problem lässt sich lösen, wenn man z.B. im Adminer Addon in der Tabelle rex_yform_history_field den Fremdschlüssen löscht. Es fehlt jedoch eine generelle Lösung des Problems.

**Comment by gharlan** [comment]
> Es fehlt jedoch eine generelle Lösung des Problems.

Also der Stand ist ja so: yform legt die Fremdschlüssel nicht mehr an, da Redaxo damit noch nicht richtig umgehen kann.
Das Problem haben also nur Leute, die von irgendeiner Beta-Version von yform kommen. Meine ich zumindest, müsste man nochmal genauer schauen, von wann bis wann die Fremdschlüssel drin waren.

Und allgemein die Unterstützung für Fremdschlüssel kommt mit https://github.com/redaxo/redaxo/issues/832.

**Comment by dergel** [comment]
für mich ist mit der redaxo unterstützung das thema hier erstmal durch.

**Comment by skerbis** [comment]
wie sieht der Workaround dafür aus. Was muss ich tun. Habe den Fehler nun hier auch.
