### ISSUE TITLE
import von CSV mit umlauten schlägt fehl

### ISSUE THREAD

**Issue by cukabeka** [yakamara/redaxo_yform#237]
Habe beim import von CSV-Dateien, die einen umlaut in einer spalte enthalten, probleme: alles in der Zelle ab dem Umlaut wird abgeschnitten. Gilt bei einer aus Excel 2016 / Mac exportierten CSV Datei.

**Comment by dergel** [comment]
alle zeichen utf8 ? kannst du das mal entsprechend konvertieren. Es kommt mal vor, dass ein anderer Zeichensatz verwendet wird und dann kommt es zu problemen bei der interpretation.

**Comment by dergel** [comment]
ich schau mal, ob man eine zeichensatz erkennung einbauen kann und das dann on the fly umwandelt

**Comment by dergel** [comment]
@cukabeka schickst du mir das beispiel ? dann kann ich es testen

**Comment by alexplusde** [comment]
bei mir gab's generell einen Import-Fehler. Kann nur leider aufgrund sensibler Daten die Tabelle nicht zur Verfügung stellen.

**Comment by dergel** [comment]
ein genereller Fehler ist mir nicht bekannt.. deswegen wäre es schon interessant was das ist.

**Comment by dergel** [comment]
Wegen Import von Dateien die nicht UTF8 entsprechend habe ich nur einen Hinweis gesetzt. Es gibt zu viele Unterschiede. Deswegen am Besten vorher die Datei im Editor öffnen und nach UTF8 konvertieren.

**Comment by cukabeka** [comment]
Was für ein encoding war denn meine beispieldatei?

**Comment by dergel** [comment]
Wester Mac Roman .. In einem Editor musst du das entsprechend konvertieren, dann klappt das auch mit uft8
