### ISSUE TITLE
REDAXO Min Version ist 5.2.0

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#238]
Abhängigkeit wegen `rex_markdown` Class

**Comment by dergel** [comment]
soweit ich das sehe ist das schon ziemlich lange so.. nur eine Info, oder Fehler gehabt ?

**Comment by tbaddade** [comment]
Gehört noch in die package.yml

**Comment by dergel** [comment]
ist es doch .. 
https://github.com/yakamara/redaxo_yform/blob/master/package.yml#L20

**Comment by tbaddade** [comment]
Ich hatte in der Doku-PlugIn yml nachgesehen. Sorry.
