### ISSUE TITLE
Reply Adresse

### ISSUE THREAD

**Issue by georgkaser** [yakamara/redaxo_yform#239]
Hallo!

Eine Frage die von Kunden immer wieder kommt: Warum kann man nicht einfach auf "Antworten" drücken, wenn ich eine Mail vom Formular erhalte. Klar, ich kann im Mailtemplate einfach die E-Mail Adresse des Ausfüllers bereitstellen, allerdings landet die Mail dann meistens im SPAM Folder wenn das Formular und Mailserver nicht identisch sind.

Meine Frage: Kriegt man es irgendwie hin im Formbuilder eine Reply-Adresse zu definieren? Oder kann man das irgendwie implementieren?

**Comment by dergel** [comment]
geht das so überhaupt .. wie du schon schreibst - wenn absendeemail und server sich unterscheiden, kann es probleme geben. Unabhaengig davon kannst du in der github version die Absender mit einem Platzhalter versehen, der dann aus dem Formular kommt.. Aber - gut gegenprüfen - ob das dann auch wirklich eine E-Mail ist ..

**Comment by dergel** [comment]
wenn ausreichend info - dann bitte issue schliessen

**Comment by alexplusde** [comment]
https://github.com/yakamara/redaxo_yform/issues/224

**Comment by georgkaser** [comment]
Wie meinst du das? Es gibt ja bei Mails die Möglichkeit eine Reply-To Adresse anzugeben (https://de.wikipedia.org/wiki/Header_(E-Mail)#Reply-To:_Antwortadresse). Damit kann die Mail von irgendeinem Server mit irgendeiner Adresse kommen - sobald ich aber auf "Antworten" drücke, nimmt der Mailclient die Reply-To Adresse. Sowas bräuchte ich.

Mit den Platzhaltern - meinst du das:

<img width="1110" alt="bildschirmfoto 2017-01-24 um 11 04 21" src="https://cloud.githubusercontent.com/assets/6472869/22242824/144ce128-e225-11e6-9c8b-ec4a5b37bcae.png">

Wenn ich da die Email vom Versender eintrage, kommt die beim Kunden nie an. Hab ich schon probiert - der hat einen ziemlich strengen Mailserver ;)

**Comment by alexplusde** [comment]
@georgkaser wie @dergel sagte, schau dir die aktuelle GitHub-Version von YForm an und mein verlinktes Issue. Das Feature wurde bereits umgesetzt.

Siehe: 
* https://github.com/yakamara/redaxo_yform/issues/224 
* https://github.com/yakamara/redaxo_yform/commit/f8caf0aa73a7a61f65e9d29a683a05e69caeea03

**Comment by dergel** [comment]
Die kannst beim Absender eben diesen Wert eintragen REX_YFORM_DATA["field"="email"] z.b. ..

Aber der Versand läuft über phpmailer und je nachdem was dort konfiguriert ist, kann es mehr oder weniger Probleme geben.

Wenn Du Deine eigene E-Mail einträgst und über einen festen Account (login,server, psw...) verschickst, sollte es immer ankommen.

**Comment by tyrant88** [comment]
Ihr habt den Georg nicht richtig verstanden: das Reply-To Feld ist ja für genau solche Fälle erfunden worden. Die Absender-Adresse wird von Mail-Servern eventuell genau geprüft (z.B. per SPF), die Reply-To nicht. Sie ging von der Website also problem los raus...
Wenn dann der Website-Betreiber in seinem Mail-Client antwortet, wird die Reply-To verwendet.
Die Frage ist: gibt der PHPMailer das her...

**Comment by tbaddade** [comment]
> Die Frage ist: gibt der PHPMailer das her...

Sollte, [siehe hier](https://github.com/redaxo/redaxo/blob/master/redaxo/src/addons/phpmailer/vendor/phpmailer/phpmailer/class.phpmailer.php#L852)

**Comment by alexplusde** [comment]
Ok, mist, ich hatte mir den PR nicht angeschaut. Ich hatte Georg schon verstanden, aber war mal wieder zu voreilig. 

PHPMailer gibt das her. Ich habe das auch schon verwendet in irgendeinem Projekt, aber eben nicht in Kombination mit den E-Mail-Templates http://stackoverflow.com/a/10432807/2135713

**Comment by dergel** [comment]
hab ich in der tag nicht verstanden.. jetzt aber :) lässt sich machen.

**Comment by georgkaser** [comment]
Yeah, is ja geil! Dank dir!

**Comment by skerbis** [comment]
Kann mir jemand sagen, wie ich nun ein reply-to setzen? Oder geht das noch nicht?

**Comment by alexplusde** [comment]
![image](https://user-images.githubusercontent.com/3855487/29537833-79490276-86c3-11e7-96e3-a84f024f7200.png)

@skerbis Wo brauchst du es? YForm? mit oder ohne YForm E-Mail-Template? Was hast du im PHP-Mailer stehen?

**Comment by skerbis** [comment]
ich benötige die E-Mail-Adresse der Person, die das Formular ausfüllt als REPLY-TO. Der reguläre Absender soll sich nicht ändern. Man muss auf das Formular sofort antworten können. PHPMailer kann das, wie kann ich es in die Templates einschleusen?

**Comment by alexplusde** [comment]
Am besten die Action dahingehend verbessern / abwandeln, so, wie ich das mit den Dateianhängen gemacht habe.

**Comment by skerbis** [comment]
@alexplusde das ist eine Grundfunktion eines Mailers, da sollte man nicht dran rumbasteln, es muss da sein.

**Comment by tyrant88** [comment]
Ja, das müsste in die yform E-Mail-Templates eingebaut werden. Und dann in die actions. Denn der PHP-Mailer kann es ja.

**Comment by alexplusde** [comment]
@skerbis eben, damit meine ich, dass diese Funktion auch in der tpl2mail-action einstellbar ist und bei den YForm-E-Mail-Templates.

**Comment by skerbis** [comment]
PING

**Comment by skerbis** [comment]
Ich habe mir anders geholfen. Da in den Templates PHP möglich ist, frage ich dort den Absender ab und sende dort per phpmailer die Antwort-Mail

**Comment by NGWNGW** [comment]
Ist das Feature weiterhin für 3.0 angedacht?

**Comment by dergel** [comment]
ist nun drin .. ich habe es anders eingebaut als bei dir vorgesehen. und zwar wird im Tempates das reply to defiiert und nicht in der action. Deswegen muss ich leider deinen PR schliessen, weil es meines erachtens anders sinnvoller ist. hoffe es passt so . dennoch vielen dank für die mühe und hinweise

**Comment by alexplusde** [comment]
Es funktioniert nicht, die Angabe im E-Mail-Template wird in 3.0 komplett ignoriert.

**Comment by georgkaser** [comment]
Kann ich bestätigen. Bei mir ebenso - grad nochmal getestet.

**Comment by alexplusde** [comment]
Gerade nochmal ausgiebiger getestet: 
- Weder von 
- noch reply-to
sowie
- weder statisch
- noch mittels YForm-Platzhaltern

**Comment by royalemotions** [comment]
Hallo Jungs, also ich habe jetzt auch von Kunden von etliches Gemecker bekommen wegen dieser Sache ... es wäre echt gut, wenn das endlich gefixt wird. :) Manche regen sich regelrecht auf darüber. Danke schon jetzt!

Evtl. auch ein Kurztutorial dazu schreiben, weil das ja eigentlich der Standard sein sollte ... ;)

**Comment by dergel** [comment]
Als Platzhalter ist es ergänzt, beim versand sollte es eigentlich bereits gehen, hatte das getestet.

Bitte mit der Github-Version nochmal testen. 

Hier die Stelle wo das ReplyTo gesetzt wird.
https://github.com/yakamara/redaxo_yform/blob/master/plugins/email/lib/yform_email_template.php#L116

**Comment by alexplusde** [comment]
getestet. geht.
