### ISSUE TITLE
Value: answertext defekt - answertext überflüssig?

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#242]
Dieses Issue dient zum klären, ob es überhaupt repariert werden soll oder nicht.

Siehe auch https://github.com/yakamara/redaxo_yform_docs/issues/59

**Comment by olien** [comment]
brauch ich nicht da es showtext gibt

**Comment by dergel** [comment]
ich msus mir das noch anschauen.. kam noch nicht dazu. Eigentlich macht der Formbuilder nur ein. Sofern du einen Antworttext eingibst, wird eine Action showtext verwendet und der TExt eingesetzt. Auf schon vorhandenen Actions, selbst bei doppeltem Showtext, sollte es "eigentlich" keine Probleme geben.

**Comment by dergel** [comment]
das ist mittlerweile mehrfach angefasst worden.. falls etwas nicht passen einfachnochmal melden..

**Comment by ynamite** [comment]
@dergel was heisst das? Hab's eben nochmal getestet. Folgendes gibt rein gar nichts aus:
```
$yform->setObjectparams('answertext','<p>Danke für die Anmeldung.</p>');
```

**Comment by dergel** [comment]
showtext nutzt answertext wenn kein eigener Text gesetzt ist .. irgendwie verwirrend

**Comment by ynamite** [comment]
Ich würde answertext restlos entfernen 🤷🏽‍♂️

**Comment by dergel** [comment]
jetzt ich auch so .. werde mir das aber nochmal ansehen, BC und so
