### ISSUE TITLE
table manager time value fehler

### ISSUE THREAD

**Issue by steri-rex** [yakamara/redaxo_yform#245]
bei eingabe (drop down) einer uhrzeit mittels im table manager erstelltem time value feld wird zwar die uhrzeit gespeichert - aber im backend bleibt im drop down 00:00:00 - verwende die aktuelle 2.1 yform version

**Comment by dergel** [comment]
kannst du mir einen screenshot der einstellungen geben ?

**Comment by steri-rex** [comment]
hier kommen 2 screenshots zu "time" und ein problem hab ich noch in 
be_manager_relation.tpl.php festgestellt - siehe 3ten screenshot.

danke!




Am 30.01.17 um 12:01 schrieb Jan Kristinus:

**Comment by dergel** [comment]
seh leider kein screenshot .. wenn noch ein problem besteht - bitte eigenes issue dazu

**Comment by steri-rex** [comment]
![time_manager](https://cloud.githubusercontent.com/assets/3844106/22457932/776a7f66-e79a-11e6-964b-0192f6df7988.png)
![time_tabelle](https://cloud.githubusercontent.com/assets/3844106/22457937/7b340f5e-e79a-11e6-9ea8-af3f75cd234e.png)

**Comment by alexplusde** [comment]
Kann ich bestätigen.

**Comment by tyrant88** [comment]
Ich jetzt auch.

**Comment by tyrant88** [comment]
PR ist drin.
