### ISSUE TITLE
be_manager_relation - warning htmlspecialchars

### ISSUE THREAD

**Issue by steri-rex** [yakamara/redaxo_yform#249]
![be_relation](https://cloud.githubusercontent.com/assets/3844106/22458008/de73990e-e79a-11e6-9b45-f78ff4517ef5.png)

**Comment by dergel** [comment]
Gerne noch die Konfiguration des Feldes als Screenshot.

**Comment by steri-rex** [comment]
![be_relation_manager](https://cloud.githubusercontent.com/assets/3844106/22459834/75ec4f72-e7a2-11e6-9435-3c14e99293ea.png)

**Comment by dergel** [comment]
müsste mittlerweile behoben sein .. be_relations ist an vielen Stellen umgebaut
