### ISSUE TITLE
suche: be_relation feld aus der yform-auswahl wirft error

### ISSUE THREAD

**Issue by cukabeka** [yakamara/redaxo_yform#250]
hab hier evtl nen bug, nachdem ich ein be_relation feld aus der yform-auswahl mit "+" geholt habe. hat effektiv zwar keine auswirkung, scheint funktional also ok, aber die error message irritiert.
![screenshot](https://cloud.githubusercontent.com/assets/688274/22470332/3545a84c-e7cf-11e6-99a0-31fb381528b3.png)

**Comment by tbaddade** [comment]
scheint das hier zu sein? https://github.com/yakamara/redaxo_yform/issues/249

**Comment by dergel** [comment]
wahrscheinlich
