### ISSUE TITLE
validation type "url" als eigenen type definieren, regex überarbeiten

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#253]
wir sind heute darüber gestolpert und wollten eine eigene Validierung für URLs implementieren, bis uns aufgefallen ist, dass es mit der Validierung `type` schon eine Validierung gibt, die float, int, etc. und url(!) überprüft.

Da es eine extra Validierung für `email` gibt, fände ich es sinnvoll, auch `url` davon abzutrennen.

In dem Zuge könnte die Validierung von Typ url erweitert werden und einen Parameter unterstützen, der sagt, wie frei/eingeschränkt validiert werden soll. Fälle, dir mir einfallen, sind:

* mit / ohne https: / http: / Protokoll (`//`)
* mit / ohne `//` 
* mit / ohne `www.`
* mit / ohne Umlaut-Domains
* mit / ohne Unterverzeichnissen
* mit / ohne URL-Parameter
* mit / ohne Hash
* mit / ohne Präfix, bspw. nur Youtube-URLs, nur Twitter-URLs

Eine kurze Recherche hat ergeben, dass regex für URLs in diversen Foren (Stackoverflow) oft ungetestet und buggy sind, deswegen liefere ich hier keine mit.

**Comment by dergel** [comment]
sehr gerne als PR .. finde ich gut

**Comment by dergel** [comment]
Nochmal darüber nachgedacht (nach 1.5 Jahren ;) ) ...
diese ganzen speziellen Varianten sollte jeder für sich über regex prüfen und nicht in einer validate url klasse.. im Gegenteil, ich finde sogar, dass email alleine als Validierung nicht sinnvoll ist, sondern deprecated sein sollte, da es ja in type vorhanden ist.

**Comment by alexplusde** [comment]
Einverstanden
