### ISSUE TITLE
validation type `preg_match`

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#254]
Vorschlag: Eine Validierung, die eine Regex als Parameter entgegennimmt.

Falls gewünscht, würde ich dazu einen PR machen.

**Comment by tbaddade** [comment]
Meinst du sowas wie das validate preg_match?

**Comment by alexplusde** [comment]
ja.

**Comment by dergel** [comment]
sowas ?

https://github.com/yakamara/redaxo_yform/blob/master/lib/yform/validate/preg_match.php

**Comment by alexplusde** [comment]
diese Validierungsmöglichkeit taucht bei mir im Table Manager nicht auf...

**Comment by dergel** [comment]
ah ok .. jetzt hab ichs kapiert .. ist nun drin

**Comment by alexplusde** [comment]
und ich hab kapiert, dass es das schon gibt. Ich nutze ja nie die Pipe-Schreibweise :D
