### ISSUE TITLE
YFORM Data Widget umbauen

### ISSUE THREAD

**Issue by dergel** [yakamara/redaxo_yform#259]
in widget=1
und datalist

so, dass es einheitlich zu den anderen rex_vars ist ?

**Comment by tbaddade** [comment]
Single
```
REX_YFORM_DATASET[id=1 table=rex_news widget=1]
```

Multiple
```
REX_YFORM_DATASET[id=2 table=rex_news field=title widget=1 multiple=1]
```

**Comment by dergel** [comment]
https://github.com/yakamara/redaxo_yform/commit/c4808f3d9000fa879e9c641f198cc27fdfc75ef6

danke thomas.
