### ISSUE TITLE
Feld Typen Float oder Boolen != Text

### ISSUE THREAD

**Issue by joachimdoerr** [yakamara/redaxo_yform#261]
Warum legt die table_api float und boolean Feldern mit dem Feld-Type Text statt mit den korrekten DB Feldtypen "float" und "boolean" an? Es werden auch noch andere Feld-Type als Text gespeichert. 

Es wäre wünschenswert wenn die default Datenbank-Feld-Typen genutzt würden.

**Comment by skerbis** [comment]
Ja, bitte ermöglicht uns die Nutzung der arithmetischen Operatoren in MySQL. Dafür müssen jedoch die Feldtypen stimmen.

**Comment by alexplusde** [comment]
nervt auch, wenn man `ORDER BY floatfield` macht:
```
1
10
100
2
3
4
usw.
```

**Comment by alexplusde** [comment]
Vielleicht könnte man grundsätzlich beim Erstellen eines Feldes den Typ festlegen - und beim migrieren anpassen / das aktuelle Original vorgeschlagen bekommen. Zumindest für Typen, die klar sind. Wer mehr einstellen möchte, kann das ja auch weiterhin über ein DBMS tun.

**Comment by dergel** [comment]
das wird nicht mehr gehen. Die Feldtypen werden ab Version 3 von YForm fest eingebrannt und entsprechend zurückgesetzt. Deswegen werden jetzt die DB Typen optimiert, so dass dieses Issue dann hoffentlich auch bald mit gutem Gefühlt geschlossen werden kann :)

**Comment by alexplusde** [comment]
Gibt es eine Warnung vor der Typ-Änderung? Ggf droht Datenverlust.

**Comment by dergel** [comment]
Es gibt nur die Updatewarnung. Da es Version 3 ist, wird nicht alles abwärtskompatibel sein. Datenverlust kann sein. Ich weiss nicht wie Einzelne ihre Datenbank umgeändert haben. Aber das wird in der Updateinfo stehen

**Comment by alexplusde** [comment]
Da muss auf jeden Fall explizit gewarnt werden oder automatisch ein Backup der betroffenen Tabellen stattfinden, sonst gibt es da sicher Tränen.

**Comment by dergel** [comment]
Hier gehts weiter 

https://github.com/yakamara/redaxo_yform/issues/494
