### ISSUE TITLE
table manager: tableset-import übernimmt die ID

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#262]
ist evtl. nicht gewünscht, normalerweise sollte er doch die ID ignorieren und ganz normal hochzählen?

**Comment by dergel** [comment]
eigentlich nicht .. wenn die id identisch ist, dann wird dieser Datensatz ersetzt.

**Comment by alexplusde** [comment]
Dann sollte man optional die id ignorieren können, da man ja manchmal ein Schema von Installation a nach b kopieren will, ohne versehentlich eine vorhandene Tabelle zu überschreiben. Stattdessen sollte hier eher der Tabellenname herangezogen werden, um festzustellen, ob man eine bestehende Tabelle überschreiben will.
