### ISSUE TITLE
YForm Tools :: inputmask - speichert Zeichen in die DB

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#263]
Feld anlegen

Typ: `text`
Individuelle Attribute: `{"class":"form-control","data-yform-tools-inputmask":"yyyy"}`

In der Dateneingabe erscheint das Feld mit einigen `_`. Man kann zwar nur ein Jahr eingeben, aber die restlichen `_` werden mit gespeichert.

**Comment by dergel** [comment]
meinst du das date feld ? und dort auf input:text gesetzt ? Beim normalen Textfeld ist es normal und richtig, dass es so reagiert.

Dann muss man auch das Format entsprechend anpassen. Aber ich glaube die Beschreibung in der Doku ist auch nicht ganz eindeutig.

**Comment by dergel** [comment]
es geht um inputmask allgmein.. Besser in der Doku erklären, dass man zum Beispiel auch digits statt datum verwenden kann etc.

https://github.com/RobinHerbots/Inputmask#via-data-inputmask-attribute

besser in der DOku beschreiben.

**Comment by dergel** [comment]
hier gehts weiter.

https://github.com/yakamara/redaxo_yform/issues/537
