### ISSUE TITLE
lang_textarea - no longer available?

### ISSUE THREAD

**Issue by sbarbe** [yakamara/redaxo_yform#266]
Hello,

is the lang_textarea field no longer available in yform?
Can I contribute in any way to speed up the development of a general solution for multiple languages?

Thanks,
Sebastian

**Comment by dergel** [comment]
sorry to say, that lang_textarea is not available anymore.. But we are developing a solution for multiple languages. But then not only for textareas.

**Comment by sbarbe** [comment]
Thank you for the immediate reply. That sounds great and is exactly what we
require.

Is there any plan, when this solution will be available? Can I support this
in any way?

2017-02-13 9:30 GMT+01:00 Jan Kristinus <notifications@github.com>:

**Comment by dergel** [comment]
Long time no comment - sorry.
For the moment you have to divide the field on your own. We do it normally with html fields (tabs) between the languages
