### ISSUE TITLE
Sprachunterscheidung einbauen.

### ISSUE THREAD

**Issue by dergel** [yakamara/redaxo_yform#267]
Option einbauen, dass man verschiedene Sprachfelder als Tabs verwenden kann,

**Comment by alexplusde** [comment]
wie wird das abgespeichert? als JSON oder als unterschiedliche Felder? 
Was passiert, wenn nachträglich Sprachen hinzugefügt/entfernt werden?

Sind nur textarea-Felder davon betroffen oder auch mind. normale Textfelder? (was wünschenswert wäre)

**Comment by dergel** [comment]
mir gehts um alle Felder und in etwa so:

Der Tabelle wird erlaubt, die Felder als sprachabhängig zu interpretierten.
D.h. beim Aufbau der Tabelle werden passende Felder zusammengeführt zu Tabs.

name_1 / name_3 / name_14

Werden dann als tabs angezeigt. Logik dahinter - sobald `[feldname]_[clang_id]` existiert, werden diese zusammengeführt.

**Comment by alexplusde** [comment]
sollte da vlt. noch ein Suffix dazu? sowas wie name_clang1, name_clang2 - ich könnte mir vorstellen, dass es durchaus gewollt sein kann, sowas wie price_1, price_2, price_3 zu verwenden, ohne, dass die Erkennung anspringt.

**Comment by dergel** [comment]
Der Erkennung würde nur anspringen wenn diese Option aktiviert wird. ich weiss noch nicht ob ich das Feld selbst als Sprachfeld markieren kann oder allgemein die Tabelle.

**Comment by tbaddade** [comment]
> ich könnte mir vorstellen, dass es durchaus gewollt sein kann, sowas wie price_1, price_2, price_3 zu verwenden, ohne, dass die Erkennung anspringt.

Das notieren wir aktuell dann so: `price1, price2, price3`

[Sprog](https://github.com/tbaddade/redaxo_sprog/blob/master/boot.php#L39-L97) hat bereits kleine Helferfunktionen für mehrsprachige Felder.

Felder: `name_1`, `name_2`
`$name = $item->getValue(sprogfield('name'))`;

**Comment by dergel** [comment]
Eine Sprachunterscheidung sehe ich nicht mehr. Das muss man manuell anlegen.
