### ISSUE TITLE
Formbuilder anpassen - Sammelthread

### ISSUE THREAD

**Issue by dergel** [yakamara/redaxo_yform#27]
Darstellung der E-Mail-Versand-Vorlage:
https://github.com/yakamara/redaxo_yform/issues/24

$REX entfernen und passend ersetzen
https://github.com/yakamara/redaxo_yform/issues/23

**Comment by tbaddade** [comment]
Wurde hier behoben https://github.com/yakamara/redaxo_yform/commit/5d6da9b2f43dbf68091cb369df1116316a5637e1
