### ISSUE TITLE
Darstellung der Feldübersicht im Manager

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#270]
- Das `label` des Feldes sollte erscheinen
- Unnütze Felder, wie html, php, fieldset etc. könnten in der Liste initial ausgeblendet und wie toggle-Button angezeigt werden
- Aktuell werden nur 30 Felder angezeigt, ggf. via Eingabefeld erhöhen? (Blättern nervt)
- Alles ein wenig übersichtlicher gestalten

**Comment by dergel** [comment]
label feld ist nun drin
unnütze felder werden weiterhin angezeigt . neues issue wenn wirklich relevant
nun werden 100 felder angezeigt
