### ISSUE TITLE
Table Manager : rex_yform_manager_field - Methoden getDbType, getDefinitions erstellen

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#271]
Der Watson kann YForm durchsuchen, braucht aber dafür den DbType um auf "none" zu filtern.

Aktuell ginge es nur auf `isSearchable()` zu prüfen, funktioniert aber nicht mit älteren YForm. Da konnte man noch `<fieldsets>` für die Suche erlauben.

**Comment by dergel** [comment]
den gibts ja.. vielleicht damals noch nciht :)
