### ISSUE TITLE
Email-Template-Manager: Feld "HTML" mit WYSIWYG-Option

### ISSUE THREAD

**Issue by cukabeka** [yakamara/redaxo_yform#272]
Habe ich schon mehrfach manuell eingebaut: Eine Klasse, mit der ich das HTML-Feld mit einem WYSIWYG Editor ausstatten kann. Gerade bei den Mail-Definitionen finde ich das extrem nützlich, nicht manuell einen HTML-Code reindübeln zu müssen, sondern komfortabel direkt in einem Editor meine Kommunikation erstellen kann.
Aktuell ist das einzige, an dem ich mich wirklich festhalten kann, die ID yform-formular-field-6 - aber die gibt es auch auf anderen Seiten und ich kann sie mit den Editor-Einstellungen nicht so gut anfassen.
Ich habe bisher immer im Code ein *class="redactorEditor"" in das Formular gehängt, aber mit den neuen R5 updates geht das schnell kaputt. Vielleicht gibt es ja einen eleganten Weg, in YFORM an das HTML-Textarea eine Editor-Klasse zu hängen?

**Comment by alexplusde** [comment]
Das würde sich aber ggf. mit anderen Workflows beißen, nicht zuletzt, wenn man PHP-Code verwendet.

Wieso gehst du nicht zusätzlich nach der Browser-URL? Dann weißt du ja, ob du dich im E-Mail-Template-Editor befindest oder anderswo.

**Comment by cukabeka** [comment]
Hm, wie sollte ich das zB in den Redactor-einstellungen aktivieren? Oder auch in TinyMCE? Wie kann ich dann denn die Browser-URL als trigger einstellen. Hatte es zB mit 
```
{
selector: '#rex-yform #yform-formular-field-6',
...
```
versucht, aber ohne Erfolg. Ich wüsste nicht, wie ich das YForm Mail HTML Feld mit einem Editor ausstatten könnte.. 
Außer eben: Yform bietet das irgendwie an ;) Oder habe ich was übersehen?

**Comment by dergel** [comment]
sobald in redaxo eine seite nachgeladen wird, wird 'rex:ready' getriggert, d.h. da kann man sich dranhängen und entsprechend mit seinem js reagieren. Das Formular habe ich nun zusätzlich zur Identifikation noch benamt. (yform-email-template)
