### ISSUE TITLE
Suche in Tabelle mit like statt exakt

### ISSUE THREAD

**Issue by steri-rex** [yakamara/redaxo_yform#273]
hab eine Tabelle mit vielen Veranstaltungen und in der Spalte "title" sind die Veranstaltungsnamen hinterlegt. um in der tabelle z.b. nach Veranstaltung "Das ist eine tolle Veranstaltung" zu suchen muss im Suchfeld exakt "Das ist eine tolle Veranstaltung" eingeben werden damit diese gefunden wird. z.b. Suche nach "tolle" liefert kein ergebnis.

**Comment by tbaddade** [comment]
Eingabe: `*tolle*` sollte die Veranstaltung finden

**Comment by steri-rex** [comment]
leider nicht - sind 146 veranstaltungen - hab schon verschiedenste wörter versucht - immer kein ergebnis

**Comment by tbaddade** [comment]
Du musst die Sternchen einsetzen.

**Comment by alexplusde** [comment]
@steri-rex ich hatte das Phänomen auch schon... hast du zufällig ein `select` oder `select_sql`-Feld in Verwendung?

**Comment by steri-rex** [comment]
ja 2 select sind in verwendung

**Comment by steri-rex** [comment]
ah ok mit sternchen gehts

**Comment by steri-rex** [comment]
hatte es mit % probiert aber auf * wär ich nicht gekommen - danke für die hilfe!

**Comment by dergel** [comment]
Suchhinweise sind ergänzt. Diese Missverständnisse sollten nicht mehr so schnell geschehen.
