### ISSUE TITLE
Pipe-Notation entfernen

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#274]
@dergel war am überlegen, die Pipe-Notation aus YForm zu entfernen, dieses Issue dient als Sammelbecken für pro/contra.

Contra:
- Mittlerweile sehr angewachsen in der Menge an Parametern, die man übergeben kann
- Problematisch, wenn bspw. Regex-Syntax kollidiert mit der Pipe-Notation (Slack-Beispiel: `validate|preg_match|email|/(?i:^.*(.com|.work|.science|.ru|.jp|ua)>?$)/i|Sorry, E-Mail-Adresse nicht erlaubt`)
- Eine funktionierende Alternative mit PHP-Schreibweise ist vorhanden
- Separat zu dokumentieren (und wer hat schon die Zeit)

Pro:
- Einfacher Einstieg (allerdings könnte man hier auch die PHP-Schreibweise nachbessern)
- Selbstinstallierendes Modul (könnte man ersetzen durch selbst installierende Beispiele)

**Comment by Hirbod** [comment]
Komplett entfernen ist ggf. der falsche Weg. Aber will mich da nicht unbedingt komplett darauf festlegen. Ich nutze tatsächlich die PIPE Notation oft in Verbindung mit php (setFormData()).

Es würde aber schon helfen, wenn man | escapen könnte (\|). Dadurch wären zumindest Regular Expressions möglich.

**Comment by IngoWinter** [comment]
Pro: sehr kompakt
```
$f->setFormData('html||<h2>Anzeigedaten ANZ-'.$id.'</h2>');
$f->setFormData('text|name|Titel der Anzeige');
$f->setFormData('html||<div class="grid-33-33-33">');
$f->setFormData('text|custom_client_name|abweichender Firmenname');
$f->setFormData('text|custom_client_other_ads|abweichender Suchbegriff');
$f->setFormData('text|custom_client_website|abweichender Homepage Link');
$f->setFormData('html||</div>');
$f->setFormData('html||<div class="grid-50-50">');
$f->setFormData('email|reminder_email|E-Mail Adresse Reminder-E-Mail');
$f->setFormData('text|reminder_contact|Anrede &amp; Name Reminder-E-Mail');
$f->setFormData('html||</div>');
```

Pro: einzige Möglichkeit im Backend Formulare zu pflegen. Ich habe mehrere Kunden, die einmal angelegte Formulare selbst erweitern/ ändern.

**Comment by 8i11y** [comment]
kann man das Pipe escapen ? (für RegEx) ?

**Comment by alexplusde** [comment]
Ich zieh das Issue zurück
