### ISSUE TITLE
Table Manager: Suche: leeren Eintrag nicht vorselektieren

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#275]
In der Suche wird mir, falls vorhanden, ein leerer Eintrag vorselektiert. Damit wird aber verhindert, dass ich einfach in ein anderes Feld einen Begriff eingeben und suchen kann.

![image](https://cloud.githubusercontent.com/assets/3855487/23261825/70172b2e-f9d8-11e6-99c1-b86ba8ce01b1.png)

Das korrekte Verhalten wäre, nichts zu selektieren.

**Comment by alexplusde** [comment]
(Wenn nichts selektiert wird, wird allerdings auch nichts gefunden. Eigentlich sollte alles gefunden werden)

**Comment by dergel** [comment]
Bei der Suche wird der Leerstring nun einfach einfernt, da es mit (empty) und !(empty) schon passende Varianten gibt.
