### ISSUE TITLE
Tablemanager:  bei deaktivierter Suche wird "Datenergebnis editieren" angezeigt

### ISSUE THREAD

**Issue by isospin** [yakamara/redaxo_yform#277]
Ein einfacher Redakteur hat im Tabellenmanager bei deaktivierter Suche die Möglichkeit alle Datensätze über 'Datenergebnis editieren' gleichzeitig zu bearbeiten.
Das birgt Gefahren...

**Comment by alexplusde** [comment]
Es gibt eine extra Option an der Tabelle „Massenbearbeitung“, die deaktiviert werden kann.
