### ISSUE TITLE
Hinweis unter der Suche

### ISSUE THREAD

**Issue by Hirbod** [yakamara/redaxo_yform#279]
Das man mit Sternchen Teilstrings suchen kann.
```*text*```
Gerade erst im Slack erfahren.

**Comment by gharlan** [comment]
Ich bin immer noch dafür, die Suche so zu ändern, dass Teilstrings immer funktionieren.
Finde *text* recht unüblich, vor allem für Nicht-Programmierer-Redakteure.

**Comment by Hirbod** [comment]
Wäre ich absolut mit einverstanden. Hab eben auch schon gemeckert, dass ich das nicht Kundenfreundlich finde

**Comment by Hirbod** [comment]
#273

**Comment by dergel** [comment]
Suchhinweise habe ich hinzugefügt. Es gibt nämlich noch so einiges mehr was man nicht wissen konnte, aber jetzt deutlicher wird.

Ich will kein große Suchmaske. Gerade auch wenn man Massenbearbeitungen macht, ist etwas freier schwieriger.. aber ich glaube mit diesen Erklärungen ist schon einiges getan..
