### ISSUE TITLE
Darstellung bei date, datetime

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#280]
Zahlen (1-9) werden einstellig angezeigt und nicht mit führenden Null obwohl das Format "DD" oder "MM" ist.

**Comment by alexplusde** [comment]
bei time auch?

**Comment by dergel** [comment]
es geht nur um die Darstellung / kein funktionales Problem:

Datetime:

![image](https://user-images.githubusercontent.com/322951/46875982-70776580-ce3d-11e8-8fdd-ae0d56a3bb67.png)


<img width="291" alt="bildschirmfoto 2018-10-12 um 16 42 30" src="https://user-images.githubusercontent.com/322951/46876146-dc59ce00-ce3d-11e8-912f-19e0d1aeb1e2.png">
<img width="269" alt="bildschirmfoto 2018-10-12 um 16 42 26" src="https://user-images.githubusercontent.com/322951/46876147-dc59ce00-ce3d-11e8-8d30-8dcaaee36c48.png">

**Comment by dergel** [comment]
datetimepicker macht das nicht richtig. in dein eigenen Fällen bei select time/date .. ist das nun drin
