### ISSUE TITLE
Showtext

### ISSUE THREAD

**Issue by olien** [yakamara/redaxo_yform#281]
Bei der Verwendung von Textile gibt es einen Fehler ("Class 'rex_textile' not found")

**Comment by tbaddade** [comment]
Die Option müsste man entweder komplett löschen oder zumindest auf Markdown ändern, da Markdown seitens Core zur Verfügung steht. Alternative wäre noch, wenn jemand Textile wählt, sollte er wissen das er das Markitup-AddOn installieren muss.

**Comment by alexplusde** [comment]
Wenn man showtext und answertext hat, kann man eins von beidem streichen.
https://github.com/yakamara/redaxo_yform/issues/242

**Comment by dergel** [comment]
textile ist komplett entfernt worden

**Comment by dergel** [comment]
sollte soweit passen

**Comment by alexplusde** [comment]
was ist jetzt dann der unterschied zu showtext und answertext?

**Comment by dergel** [comment]
keiner .. showtext ist die action und answertext war die bezeichnung beim yform builder
