### ISSUE TITLE
Warning bei Suche in einer be_manager_relation

### ISSUE THREAD

**Issue by Hirbod** [yakamara/redaxo_yform#282]
Warning: htmlspecialchars() expects parameter 1 to be string, array given in /redaxo/src/addons/yform/plugins/manager/ytemplates/bootstrap/value.be_manager_relation.tpl.php on line 78

**Comment by tbaddade** [comment]
Wurde hier behoben
https://github.com/yakamara/redaxo_yform/commit/1b7d5cf63d0d9e169a066fba24ceffc2d2b86535

**Comment by alexplusde** [comment]
Ist ein neuer Patch-Release absehbar?

**Comment by dergel** [comment]
ich hänge bei ycom und yform mit den releases hinterher.. komme wohl nicht in den nächste 2 Wochen dazu .. aber danach wird es sicher zeitnah passieren. sorry, schneller gehts gerade nicht
