### ISSUE TITLE
Tabellen-Cache löschen

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#285]
Wenn man bspw. Änderungen in Adminer macht, die nicht direkt übernommen werden.

Siehe auch:
https://github.com/redaxo/redaxo/issues/1071#issuecomment-283061689

**Comment by Hirbod** [comment]
Oder eigene Classen für xForm bereitstellt. (hatte da auch ein Issue hinzugefügt)

**Comment by dergel** [comment]
Mir ist das leider nicht ganz klar. Adminer Änderungen sind keine YForm-Schemaänderungen. D.h. die können gar nicht übernommen werden. Oder verstehe ich das nur nicht richtig.

Klassen die nicht bereitgestellt werden weil der Cache sie noch nicht führt, sollte es so eigentlich nicht mehr geben, seit den neuesten REDAXO Versionen.

**Comment by alexplusde** [comment]
Im Moment muss man den kompletten Cache von REDAXO löschen. Gäbe es nicht die Möglichkeit, YForm-Cache von Tabellen oder insgesamt getrennt davon zu löschen?

**Comment by dergel** [comment]
leider nein. YForm schaut im Cache von REDAXO nach und die Klassennamen werden dort ausgelesen.

**Comment by alexplusde** [comment]
Okay, aber den Bildercache deswegen mitlöschen ist doch murks. Geht das nicht anders?

**Comment by dergel** [comment]
im moment nicht. wenn ich redaxo einzelne cache bereiche (addon->deleteCache) Zeugs drin wären, dann könnte man das sicherlich besser machen.
