### ISSUE TITLE
Validierungsbeispiele - "name" anstatt "label"?

### ISSUE THREAD

**Issue by sbarbe** [yakamara/redaxo_yform#287]
Hallo,

bei den Validierungsbeispielen wird immer "label" angegeben. Ist das nicht "name" was hier gebraucht wird? Denn nur "name" ist ja auch eindeutig.

Falsch:
validate|empty|label|warning_message

Richtig:
validate|empty|name|warning_message

Viele Grüße.

**Comment by skerbis** [comment]
label ist ein Platzhalter für jedes beliebige Feld

**Comment by alexplusde** [comment]
Das wurde schätzungsweise "label" genannt, damit der Validierung hier nicht ein Name vergeben wird, sondern der Name eines anderen Feldes verwendet wird und auch nicht verwechselt wird.

**Comment by skerbis** [comment]
label in Formularen, name (column Name) in Tabellen , die Pipe-Definition bezieht sich historisch auf das Formular-Label, denke ich

**Comment by dergel** [comment]
das finde ich auch nicht so richtig gut.. sollte man überall auf name ändern.. auch in den actions etc.. gerne als PR :)

**Comment by alexplusde** [comment]
label = Beschreibung
name = Feldname, daher vielleicht field / column?

**Comment by dergel** [comment]
nicht immer muss name ein field sein.. es gibt z.b. auch name ohne field. php, html, ...

**Comment by alexplusde** [comment]
stimmt. ich bin da zu sehr bei Eingabe- und Datenbankfeldern.
