### ISSUE TITLE
be_manager_relation - Problem mit Apostroph-Zeichen

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#288]
Wenn ich einen Popup-Datensatz verknüpfen will, der ein Apostroph im Namen hat, dann kann dieser Datensatz nicht übernommen werden. Das Popup schließt sich, aber der Wert wird nicht übernommen.

**Comment by dergel** [comment]
auch in der aktuellen githubversion ?

**Comment by alexplusde** [comment]
Kann ich weder ausschließen noch bestätigen...

**Comment by alexplusde** [comment]
Ja. Das Popup schließt sich allerdings nicht mehr. Es passiert einfach nichts, wenn man auf übernehmen klickt.

**Comment by dergel** [comment]
Problem ist nict mehr vorhanden
