### ISSUE TITLE
Geo-Plugin: Abstand im Table Manager

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#290]
![image](https://cloud.githubusercontent.com/assets/3855487/23856606/8054d09c-07fa-11e7-905e-5561a9673fc3.png)

Hier gehört unter die Karte noch ein Abstand zum nächsten Feld.

Das erste Mal jetzt in all der langen Zeit die Geolocation-Funktion benutzt. Ist. Das. Geil.

**Comment by dergel** [comment]
das geo plugin ist nicht mehr bestandteil vom yform

**Comment by olien** [comment]
Warum eigentlich nicht? Funktioniert doch nich - oder? Wäre es bei FOR gut aufgehoben?

**Comment by dergel** [comment]
ja, dort wäre es gut aufgehoben.

**Comment by tbaddade** [comment]
Als Hinweis
https://github.com/FriendsOfREDAXO/yform_geo_osm

ergänzend zum PlugIn
https://github.com/FriendsOfREDAXO/osmproxy

**Comment by olien** [comment]
https://github.com/FriendsOfREDAXO/yform_geo
