### ISSUE TITLE
Upload-Feld: Validierung abtrennen, Validierung überprüfen

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#292]
Wäre es nicht konsequent, wenn die Validierung eines Upload-Feldes mit einem Validierungs-Feld gemacht wird? Zumindest ob Pflichtfeld (empty) - scheinbar gibt es da ohnehin gerade Probleme, dass die restliche Validierung nicht durchgeführt wird, wenn das Feld nicht als Pflichtfeld markiert wird.

/cc @brandes-webdesign

**Comment by dergel** [comment]
finde ich nicht so sinnvoll zu implementieren. Weil FILES eine andere Form haben, wie man sie verwendet und das extrem viel Overhead sorgen würde. Weiterhin, und das wird gerade gebaut, kann es ja auch serverseitige Fehler geben, die auch ohne Valdierungsfeld immer zum abbruch führen müssen. (Serverseitige Uploadgröße, Speichern fehlgeschlagen) .. dazu gehts hier weiter

https://github.com/yakamara/redaxo_yform/issues/new

**Comment by alexplusde** [comment]
Nachvollziehbar
