### ISSUE TITLE
Table Manager: Select-Felder standardmäßig in den Bootstrap-Style bringen

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#294]
Die Höhe der Select-Boxen sollte immer gleich sein, statt im Browser-Look. Die hier sollten bspw. nebeneinander stehen:

![image](https://cloud.githubusercontent.com/assets/3855487/24310807/9f6ef036-10d1-11e7-9fb5-b3f49e9b8ee7.png)

**Comment by skerbis** [comment]
da einfach die selectpicker class drauf setzen ... das geht

**Comment by alexplusde** [comment]
Nope, geht nicht.

**Comment by skerbis** [comment]
Welches Feld ist das?

**Comment by skerbis** [comment]
<img width="600" alt="Bildschirmfoto 2020-05-21 um 12 39 23" src="https://user-images.githubusercontent.com/791247/82551237-1e8dda00-9b60-11ea-9d9a-015dfd22e97e.png">
@alexplusde das sieht bei mir so aus?
