### ISSUE TITLE
phpmailer-Profil per Objparam übergeben

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/redaxo_yform#297]
Es sollte möglich sein, verschiedene PHP-Mailer-Profile hinterlegen zu können, wenn man YRewrite nutzt und bspw. YForm-Formulare von unterschiedlichen Absender-Domains / -Postfächern gesendet werden.

Das Profil sollte man als Objparam hinterlegen können und nicht am E-Mail-Template, um dasselbe Template in verschiedenen Domains hinterlegen zu können.

Diskussion vgl. https://github.com/redaxo/redaxo/issues/1193

**Comment by alexplusde** [comment]
https://github.com/redaxo/redaxo/issues/1309

**Comment by alxndr-w** [comment]
Per EP möglich, bspw: https://github.com/alexplusde/mailer_profile
