### ISSUE TITLE
rex_yform_manager_dataset::get() vs be_manager_relation

### ISSUE THREAD

**Issue by IngoWinter** [yakamara/redaxo_yform#298]
```
$f  = rex_yform_manager_dataset::get($id, $table);
$f->save();
```
Schlägt fehl, wenn $table ein Feld vom Typ `be_manager_relation` enthält. Anscheinend werden keine Werte aus der Relationstabelle geholt und beim Speichern wirft die `be_manager_relation` Klasse dann einen Fehler.

**Comment by gharlan** [comment]
Was für ein Relationsfeld genau ist es? (eventuell mal ein Screenshot von der Definition?)

**Comment by IngoWinter** [comment]
![unbenannt-1](https://cloud.githubusercontent.com/assets/7223820/24616526/ab7f806c-1891-11e7-8317-8dfc08abaca8.png)

**Comment by gharlan** [comment]
Und du bist sicher, dass in dem betreffenden Datensatz auch Stichworte ausgewählt sind?
Denn die "Leer-Option" ist ja deaktiviert, somit klappt das Speichern nur, wenn Stichworte drin sind.

**Comment by gharlan** [comment]
Eventuell mal bei "Fehlermeldung wenn Leer-Option nicht aktiviert ist" was eintragen, und dir dann nach deinem `save()`-Aufruf `$f->getMessages()` ausgeben lassen.
Dann wissen wir erst mal, ob es überhaupt wirklich an dem Feld liegt.

**Comment by IngoWinter** [comment]
Es liegt an dem Feld, ich habe mir hier: https://github.com/yakamara/redaxo_yform/blob/master/plugins/manager/lib/yform/value/be_manager_relation.php#L101-L104 ein error_log reingehauen...

**Comment by IngoWinter** [comment]
Ach so, Kontext :)
der Fehler kommt, wenn das Addon yform_usability den Status online/offline wechseln möchte - es geht also um bereits angelegte Datensätze, bei denen nur der Wert Status geändert werden soll.

**Comment by gharlan** [comment]
Ok, muss ich mal testen.

**Comment by gharlan** [comment]
Habe jetzt mal yform_usability installiert und getestet. Bei mir klappt es mit dem Status.
Habe dann mal in den Code geschaut. Da wird aber doch auch gar nicht die dataset-Api genutzt, sondern direkt rex_sql?
https://github.com/FriendsOfREDAXO/yform_usability/blob/master/lib/Api.php#L37-L46

**Comment by gharlan** [comment]
Habe nun aber mal explizit selbst die Api genutzt, genauso wie du oben. Und auch ich hab ein Select-Multiple-Feld ohne Leeroption.
Bei mir klappt das Speichern über `save()`.

Hast du die Release-Version, oder die aktuelle von GitHub?
Bin mir gerade nicht mehr sicher, ob es eine Fix gab, der damit zu tun haben könnte.

**Comment by IngoWinter** [comment]
Ich habe die 2.1 aus dem Installer. Morgen ziehe ich mir die aktuelle und guck mal. Es hat sich ja doch einiges getan... https://github.com/yakamara/redaxo_yform/compare/2.1...master?diff=unified&name=master#diff-1cacf4cf0e29c2a88b70e4021b22faaa

**Comment by IngoWinter** [comment]
Nachdem ich manuell den aktuellen GH Stand geladen habe funktionierts, anscheinend hats innerhalb der letzten 2 Monate einen Fix gegeben. Und anscheinend habe ich eine yform_usability Version aus dem Installer, die nicht dem aktuellen GH Stand entspricht - vielleicht deswegen: https://github.com/FriendsOfREDAXO/yform_usability/issues/11
Danke fürs Gucken :)
