### ISSUE TITLE
Installer Version veraltet

### ISSUE THREAD

**Issue by IngoWinter** [yakamara/redaxo_yform#299]
Es wäre schön, wenn die Version im Installer in kürzeren Intervallen aktualisiert würde. Das hier: https://github.com/yakamara/redaxo_yform/compare/2.1...master?diff=unified&name=master rechtfertigt auf jeden Fall eine neue Installerversion weil auch Bugfixes dabei sind.

**Comment by dergel** [comment]
das stimmt. da ich gerade im urlaub bin, werde ich das wohl erst nächste Woche schaffen. aber, ja, müsste öfter passieren

**Comment by alexplusde** [comment]
wenn's einen beta-Release gibt, würde ich über Ostern testen...

**Comment by dergel** [comment]
habe nun direkt released.. einfach so ;) ..
