### ISSUE TITLE
be_manager_relation

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#3]
- Javascripts funktionieren nicht
- Wird als Typ ein "select" ausgewählt, kommt in der Datentabelle folgende Meldung: `Die Tabelle wurde nicht gefunden`

**Comment by olien** [comment]
Bestätige...

**Comment by olien** [comment]
Hier hat noch jemand Probleme mit dem Feld...

http://www.redaxo.org/de/forum/addons-packages-f43/yform-manager-relation-t20843.html

**Comment by olien** [comment]
Bei der Auswahl "popup" kommt folgende Fehlermeldung nach Klick auf das +:

ReferenceError: Can't find variable: yform_manager_openDatalist

**Comment by dergel** [comment]
noch offen:

- Beim Übernehmen wird der Bezeichner nicht übernommen
- Bei Lookupfeldern werden Felder mit gleichem Werte nicht mehrfach aufgenommen
- Mehrere Relations in Folge (Fenster übereinander) gehen noch nicht

**Comment by dergel** [comment]
@gharlan kannst du die verschiedenen relationsvarianten noch prüfen und wenn möglich, minimal dokumentieren ;) ..

**Comment by gharlan** [comment]
Habe nun nochmal viele Varianten durchprobiert, eine Kleinigkeit korrigiert, aber ansonsten scheint alles zu funktionieren.
Falls doch noch was klemmt, bitte neue Issues aufmachen.
