### ISSUE TITLE
Tabellen mehrfach migrieren / Trick für unterschiedliche Berechtigungen

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/redaxo_yform#300]
Wenn es möglich wäre, dass man eine Tabelle mehrfach in YForm migrieren kann, könnte man unterschiedliche Ansichten und Formulare für die gleiche Tabelle umsetzen. So könnte man eine einfache Eingabe für Benutzer A haben und eine erweiterte Eingabe für Nutzer B.

Alternativ sollte es möglich sein, Feldern eine Rolle zuzuweisen.

**Comment by skerbis** [comment]
Unterschiedliche Views / Formulare - je Rolle - finde ich gut.

**Comment by dergel** [comment]
Finde das gut. Und dann dieses 2. Schema mit Lese/Schreib/Editierrechten versehen können. Und eventuell einen Filter drübersetzen können und eben eine eigene Felddefinition.
Nicht leicht, würde aber viele Schwierigkeiten lösen können.

**Comment by alexplusde** [comment]
\o/ - prinzipiell habe ich das schon mal mit YForm 2 so gemacht und es schien keine Konflikte damit zu geben. Allerdings nutze ich das ganze immer recht oberflächlich und bspw. ohne YOrm - ich weiß also nicht, ob es Fälle geben kann, in denen YForm-Tabellendefinitionen pro Datenbanktabelle einzigartig sein müssen.

**Comment by dergel** [comment]
ich habe das in ein neues Issue transferiert. https://github.com/yakamara/redaxo_yform/issues/1162
