### ISSUE TITLE
Beschreibung fehlerhaft value datestamp formbuilder (auch Doku) 

### ISSUE THREAD

**Issue by ynamite** [yakamara/redaxo_yform#302]
Die Beschreibung für das Value datestamp ist falsch.

In der Doku steht:
`datestamp|datestamp|Datestamp|||0|`

Im Modul steht:
`datestamp|name| [YmdHis/U/dmy/mysql] | [no_db] | [0-wird immer neu gesetzt,1-nur wenn leer,2-nie],`

Zum einen ist die Beschreibung in der Doku momentan nicht sehr vielsagend und im Modul stimmt sie imo nicht. Korrekter wäre wahrscheinlich:

`datestamp|feldname|label|[YmdHis/U/dmy/mysql] | [no_db] | [0-wird immer neu gesetzt,1-nur wenn leer,2-nie]`

Hat mich eben den Morgen gekostet :/

Wichtig: grundsätzlich würde ich in den Beschreibungen/Doku jeweils immer diesselben Begriffe anwenden und ganz klar zwischen LABEL und NAME/FELDNAME unterscheiden. Zur Zeit steht manchmal `name`, manchmal `label`, manchmal `Bezeichnung:` dann wieder `emaillabel` etc.

Zusätzlich wäre es evtl sinnvoll bei der Validierung für `email` zu erwähnen, dass mit diesem Validierungstyp NICHT geprüft wird, ob das Feld leer ist und man dafür separat validieren muss.

**Comment by alexplusde** [comment]
@ynamite Dass man bei `email` ggf. auch auf `empty` überprüfen muss, wenn es ein Pflichtfeld ist, steht bereits in der Doku.

Mit Label/Feldname/etc. stimme ich absolut zu.

Zum eigentlichen Thema "datestamp" hier der Ausschnitt der Klasse: 

```

    public function getDescription()
    {
        return 'datestamp|name| [YmdHis/U/dmy/mysql] | [no_db] | [0-wird immer neu gesetzt,1-nur wenn leer,2-nie],';
    }

    public function getDefinitions()
    {
        return [
            'type' => 'value',
            'name' => 'datestamp',
            'values' => [
                'name' => ['type' => 'name',   'label' => rex_i18n::msg('yform_values_defaults_name')],
                'label' => ['type' => 'text',    'label' => rex_i18n::msg('yform_values_defaults_label')],
                'format' => ['type' => 'text',    'label' => rex_i18n::msg('yform_values_datestamp_format')],
                'no_db' => ['type' => 'no_db',   'label' => rex_i18n::msg('yform_values_defaults_table'),  'default' => 0],
                'only_empty' => ['type' => 'select',  'label' => rex_i18n::msg('yform_values_datestamp_only_empty'), 'default' => '0', 'options' => 'immer=0,nur wenn leer=1, nie=2'],
                'show_value' => ['type' => 'checkbox',  'label' => rex_i18n::msg('yform_values_defaults_showvalue'), 'default' => '0', 'options' => '0,1'],
            ],
            'description' => rex_i18n::msg('yform_values_datestamp_description'),
            'dbtype' => 'varchar(255)',
            'multi_edit' => 'always',
        ];
    }
}
```
demzufolge muss es `name,label,format,no_db,only_empty,show_value` sein - da fehlt selbst in der Beschreibung noch show_value.
