### ISSUE TITLE
Feldbeschreibungen in yrewrite-backendpage beginnen mit "<small>"

### ISSUE THREAD

**Issue by tyrant88** [yakamara/redaxo_yform#303]
Denn z.B. hier:
https://github.com/yakamara/redaxo_yform/blob/master/ytemplates/bootstrap/value.text.tpl.php#L11

müsste es `rex_i18n::translate($this->getElement('notice'),false);` heißen, dann wird nicht htmlspecialchars angewendet.
Zieht sich durch alle ytemplates Felder mit Notice

![zwischenablage-2](https://cloud.githubusercontent.com/assets/1277494/25533047/969b75e6-2c2f-11e7-9e4f-bded138237f6.jpg)
(Im Screenshot hab ich das text-Feld schon gefixed)...

**Comment by dergel** [comment]
heisst es mittlerweile auch :) ..
