### ISSUE TITLE
Upload-Feld - Fehlerausgabe nach z.B. falschem Dateityp kommt nur beim Pflichtfeld

### ISSUE THREAD

**Issue by brandes-webdesign** [yakamara/redaxo_yform#304]
Beim Upload-Feld kommt die Fehlerausgabe nur beim Pflichtfeld !!!

Feld in yForm ist z.B. so angelegt:
upload|upload_1|Datei 1|10000|.pdf,.doc,.docx,.jpg,.zip||Minimale Dateigrösse 1 KB,Maximale Dateigrösse 10 MB,Erlaubte Dateiendungen .pdf .doc .docx .jpg .zip,Bitte eine Datei hochladen,Datei gelöscht

Lade ich nun z.B. eine xls oder gif Datei hoch, wird diese Datei zwar korrekt gelöscht, es kommt aber keine Fehlermeldung.
Wenn ich das Feld als Pflichtfeld anlege klappt die Fehlermeldung nach dem flaschen Dateityp.

Das Problem liegt also meines Erachtens nach lediglich in der Fehlerausgabe, ich kann es nur nicht weiter eingrenzen oder im Quellcode finden.

Ohne Fehlermeldung ist es besonders beim finalen Abschicken natürlich nicht ideal, weil die Datei dann einfach gelöscht wird, ohne das der Bewerber davon was mitbekommt. Der Empfänger des Formulars weiß von der Datei ja dann auch nichts, kann also auch nicht nachfragen.

Bei Fragen / Unklarheiten gerne direkt an mich wenden.

Danke für Eure Hilfe
Mirco Brandes

**Comment by alexplusde** [comment]
siehe auch
https://github.com/yakamara/redaxo_yform/issues/292

**Comment by dergel** [comment]
@brandes-webdesign kannst du das nochmal testen. Ich kann das nicht mit der aktuellen github Version reproduzieren. Bei mit funktioniert die Fehlermeldung. Sobald eine Datei die falsche Dateieindung hat, kommt immer eine Fehlermeldung. Bitte nochmal prüfen.

**Comment by brandes-webdesign** [comment]
Problem gelöst am 17.10.2017
DANKE !!!!!!
