### ISSUE TITLE
Feature-Request: be_relation_manager auch zu rex_article und rex_media

### ISSUE THREAD

**Issue by christophboecker** [yakamara/redaxo_yform#305]
Hallo zusammen

hoffentlich ist die Überschrift nicht zu kryptisch. yform hat mich sehr überrascht mit seinen vielfältigen Möglichkeiten. Bin dennoch rasch an Grenzen gekommen. Ich habe zwei Tabellen angelegt (rex_meins_segler und rex_meins_boote). Darüber habe ich die m:n-Relation gebaut (wem gehört welches Boot; ein Eigner und mehrere Boote vs. Eignergemeinschaft). Klappt prima. 

Nun falle ich aber auch den Bauch: wollte ich doch tatsächlich auch Bilder und Artikel mit den Booten m:n verknüpfen. Klappt aber bestenfalls mit Einschränkungen durch die Hintertür (rex_media in yform migrieren) - etwas risky, per saldo, denn dann muss ich Medien und Artikel an zwei Stellen verwalten. Jaaaa, ich kann auch einfach mit einem Select-Metafeld eine 1:n-Liste der Boote bei Artikeln und Medien einfügen, aber das ist halt nicht m:n.

Die elegente Lösung wäre wohl über Meta-Infos: Man legt ein Meta-Feld vom Typ be_manager_relation an und hat dann auch die Eingabefelder bzw. Auswahlfelder in den originären Masken.

Ist evtl etwas in Vorbereitung oder wäre es mal eine Idee? Dass sich yform sozusagen in metainfos einhängt? 

Oder gibt es da schon etwas und ich habe es übersehen?

Danke vorab und viele Grüße
Chris

**Comment by alexplusde** [comment]
https://github.com/yakamara/redaxo_yform/issues/144

**Comment by dergel** [comment]
geht bei #144 weiter
