### ISSUE TITLE
Feature-Request: feldtyp be_media_category

### ISSUE THREAD

**Issue by christophboecker** [yakamara/redaxo_yform#306]
Hallo zusammen

wäre es möglich, dem yform ein kleines plugin be_media_category zu spendieren. Technisch sollte es kein Problem sein. Ich hab das mal ausprobiert, indem ich die Datei yform/plugins/manager/lib/yform/value/be_category.php in ... be_media_category.php kopiert habe. Da hab ich dann alle rex_category gegen rex_media_category ausgetauscht. Funktioniert.

Warscheinlich muss noch (etwas) mehr geändert werde (ich blicke den Teil mit den Permissions nicht, die Referenzen auf lang_xx sind auch zu ändern. Aber es klappt.

Wäre schön, wenn ihr das perspektivisch einbauen könntet.

Danke und viele Grüße
Chris

**Comment by dergel** [comment]
sicher .. willst du des fertigstellen und einen Pull Request machen ? 
lg

**Comment by christophboecker** [comment]
Hallo Jan

ich kann es ja mal versuchen:-) Anbei drei Dateien:

be_media_category.php
be_select_category.php
de_de.lang
en_gb.lang




Was geändert ist:

In den .lang-Dateien habe ich neue Felder eingefügt. Im Grunde sind das die Form_values_be_select_category_xxxx. Eigentlich passen die Texte auch für media_category, aber „homepage“ ist als Root-Begriff im Medienpool eher ungeeignet. Daher geändert in top-level bzw. root. Der Vollständigkeit halber habe ich alle kopiert und umbenannt.



be_media_category.php ist eine Kopie von be_select_category.php. Eigentlich habe ich nur an allen Stellen rex_category durch rex_media_category ersetzt. Außerdem in Zeile 105ff die obigen Translate-Codes genommen. 

Was ich nicht verstanden habe und folglich auch nicht angepackt habe, sind 
Zeile 18-21
Alles,  was mit Permissions zu tun hat: Zeilen 35, 40, 44 usw. 
Mit meinen Admin-Rechten klappt alles. Ob auch User mit eingeschränkten Rechten Spaß hätten weiß ich nicht und konnte es auch mangels Umgebung nicht testen.

Außerdem habe ich Zeile 31 in beiden php-Dateien geändert. Dort steht in be_select_category im Code und nicht in der .lang des Wort "Homepage“. Ich hab das mal aus dem Code herausgenommen und in die .lang-Dateien verlagert.


Entsprechend sind die Zeilen 256 und 254 in den .lang-Dateien neu

Sie kann es dann aussehen:
.

So, mehr kann ich an der Sache nicht tun. Hoffe, damit sind zumindest 80% erledigt.


Viele Grüße
Chris

**Comment by dergel** [comment]
https://github.com/yakamara/redaxo_yform/pull/308
