### ISSUE TITLE
Upload :: Wie mit Dateien umgehen

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#307]
1. Nutzt man das Value im Front- und im Backend, landen die Dateien in unterschiedliche Ordner
1. Löscht man einen Datensatz, bleiben die Dateien auf dem Server als Leichen erhalten

**Comment by alexplusde** [comment]
Vorschläge:
1. Pfade immer relativ zur index.php definieren
2. Optional löschen aktivieren - kann ja auch Sinn machen, diese Daten zu behalten.

**Comment by alexplusde** [comment]
Die Dateileichen stoßen mir gerade auch negativ auf. Ein Cronjob zum Aufräumen könnte mitgeliefert werden. Hätte unser Praktikant nicht gesehen, dass die Dateien in den Data-Ordner geschoben werden, wäre ich davon ausgegangen, dass die gar nicht explizit auf dem Server gespeichert werden.

Für die nächste Minor-YForm-Version wünsche ich mir, dass die ganzen Issues zum Upload-Feld behoben werden. Fühlt sich einfach nicht rund an, das Feld zu benutzen.

**Comment by dergel** [comment]
diese Fall ist in der Tat schwierig. Man könnte aber wirklich einen Cronjob dazu anlegen lassen, der sich um YForm bereinigungen kümmert. Vielleicht sogar so, dass sich einzelnen Value/Validate/Actions dort reinhängen können (auch wenn ich gerade nicht weiss wie man das machen könnte)

**Comment by alexplusde** [comment]
Cronjob registrieren, Frontend/Backend-Verzeichnisse als Auswahl-Parameter anbieten, Löschregel definieren (täglich, wöchentlich, monatlich).

**Comment by dergel** [comment]
das ist klar.. ich meine wie man einen weg findet, dass eine yform klasse sich eigenständig da reinklemmen kann, so dass die upload klasse was eigenes automatisch anbieten kann.

**Comment by dergel** [comment]
hier gehts weiter #723
