### ISSUE TITLE
Table-Manager:: Tabelle lässt sich nicht nach datestamp sortieren

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#309]
Wenn ich die Tabelleneigenschaften so bearbeite, dass nach einem Zeitstempel sortiert wird (bei uns ein datestamp/createdate-Feld), so werden die Datensätze dennoch weiter nach ID sortiert.

**Comment by dergel** [comment]
Beim testen des issues sind mir andere Fehler aufgefallen die nun korrigiert sind.. Ansonsten gehts das sortieren nach datestamp mittlerweile unproblematisch.
