### ISSUE TITLE
Yorm : where mit Funktionen

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#310]
**funktioniert**
`->whereRaw('datetime >= CURDATE()')`

**funktioniert nicht**
`->where('datetime', 'CURDATE()', '>=')`

**Comment by gharlan** [comment]
Das soll auch nicht funktionieren, `where` ist gerade dafür gedacht, dass der Vergleichswert escaped wird.

**Comment by alexplusde** [comment]
Offtopic: Es sollte ein Beispiel geben, das den Operator als 3. Parameter zeigt. Hätte man sich denken können, sehe ich allerdings gerade zum ersten Mal.

**Comment by gharlan** [comment]
Hier schließe ich jedenfalls, da eben `where` bewusst escapen soll.

**Comment by alexplusde** [comment]
PS: *funktioniert in diesem Beispiel alternativ*
`->where('datetime',date("Y-m-d"),'>')`
