### ISSUE TITLE
YForm Table Manager Formularcode: form_name standardmäßig ausgeben

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#311]
Im Formular-Code-Generator vom Table Manager sollte immer 

```
$this->objparams['form_name'] = '%name_der_tabelle%';
```

mit ausgegeben. In Slack wurde häufiger gefragt, wie man YForm so kompatibel macht, dass man mehrere Formulare auf einer Seite hat. Mit der Änderung würde man dafür sorgen, dass man das Formular von Haus aus immer kompatibel rauskopiert.

/cc @olien @tgoellner

**Comment by alexplusde** [comment]
Das scheint in YForm 3.0 wieder Probleme zu machen. Es wird kein name-Attribut ausgegeben, nur die ID. Mehrere YForm-Formulare auf der selben Webseite/Artikel scheinen so allerdings wieder nicht einsetzbar.

**Comment by tbaddade** [comment]
das name Attribute kannst du via `objparams` setzen. Was macht yform, wenn es keinen Bezug zu einer Tabelle gibt? Dann erscheint das Problem irgendwann wieder.
