### ISSUE TITLE
Sortierung der Tabelle nach Feld "prio"

### ISSUE THREAD

**Issue by Hirbod** [yakamara/redaxo_yform#316]
Hat man Prio als Sort-Spalte gewählt und auch die Tabelle danach sortiert, erhalte ich z.B 

1
10
11
1..
19
2
20
21

Das muss noch etwas optimiert werden.

**Comment by alexplusde** [comment]
das wäre mir noch nie passiert. Was für ein Feldtyp ist das Prio-Feld denn bei dir in der DB? Hast du das Feld nachträglich aufgeschalten oder mit dem Table Manager angelegt?

**Comment by tbaddade** [comment]
@Hirbod hast du als Value `text` genommen oder das `prio` Value?

**Comment by Hirbod** [comment]
War eine migrierte Tabelle. Per default text oder textarea, hab es nicht mehr im Kopf. Hab das Feld dann im Tablemanager gelöscht und anschließend als prio Typ angelegt, vermutlich wird es jetzt ein String Datentyp sein (bin gerade am Handy)

**Comment by alexplusde** [comment]
Ist damit das Problem gelöst?

**Comment by dergel** [comment]
ist denke das wird es gewesen sein
