### ISSUE TITLE
Table Manager: index-Feld: Schlüssel auf Basis von datestamp

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#319]
Im Moment können nur Formular-Eingabefelder im Frontend verwendet werden, um einen Index zu erzeugen. Ich benötige jedoch einen Index-Wert auf Basis eines eindeutigen/einmaligen Wertes / Wertkombination, bspw. createdate.

**Comment by alexplusde** [comment]
Ich habe gerade einen Blick in die Klasse geworfen und entdeckt, dass bei Index jede beliebige (ggf. auch selbst geschriebene) PHP-Funktion verfügbar ist. In meinem Fall genügte crypt(), um einen eindeutigen Hash zu erzeugen. 

Hier würde ich vorschlagen, die Beschreibung genauer zu formulieren (PR kommt)

**Comment by dergel** [comment]
das sollte gut passen.. es werden als beispiele funktionien wie md5 und sha1 angeführt.. wenn verbesserungswünsche.. gerne her damit
