### ISSUE TITLE
Beispielmodul "YForm Formbuilder"

### ISSUE THREAD

**Issue by olien** [yakamara/redaxo_yform#32]
Im "Backend Modul-Output" werden die Formulare gerendert. Hier sollte vielleicht nur eine Übersicht der gewählten Einstellungen dargestellt werden. (Oder irgendein Text "Ausgebe im Frontend").

LG
Oliver

**Comment by dergel** [comment]
bin mir unsicher ob ich das gut fände.. Auch wenn es natürlich irgendwie logisch ist, finde ich die Darstellung im Backend schon eine Motivation und Überprüfung, ob das erstellte Formular denn einigermaßen passt.

**Comment by olien** [comment]
Motivation?? Hehe. Find ich gut!
