### ISSUE TITLE
utf8mb4 support

### ISSUE THREAD

**Issue by Hirbod** [yakamara/redaxo_yform#323]
Bei Textarea und Text sollte man entscheiden können, ob utf8 oder utf8mb4
https://github.com/redaxo/redaxo/issues/1231

**Comment by alexplusde** [comment]
spricht per se etwas gegen utf8mb4?

**Comment by dergel** [comment]
wird auf utf8md4 umgestellt

https://github.com/yakamara/redaxo_yform/issues/235
