### ISSUE TITLE
be_manager_relation führt postAction IMMER aus

### ISSUE THREAD

**Issue by tgoellner** [yakamara/redaxo_yform#326]
...dadurch werden Zuordnungen des aktuellen NUtzers immer entfernt, wenn dieser sich einloggt.

(Fälschlicherweise zuerst bei #[YCOM](https://github.com/yakamara/redaxo_ycom/issues/127#issuecomment-308425003) eingetragen ).

**Comment by dergel** [comment]
Leider lange nicht angefasst, aber es hat sich viel getan, allein die Abfragen an diesen Stellen sind viel differenzierter. Ich kann das Problem leider nicht nachvollziehen und vielleicht ist es mittlerweile auch behoben. Ansonsten gerne ein Beispiel reinlegen, damit ich das nachprüfen kann.
