### ISSUE TITLE
Table Manager: Tabelle reparieren

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#328]
Hin und wieder, aus unerfindlichen Gründen, passiert's mal, dass Redaxo-User von SQL-Fehlern berichten, die auf eine inkonsistente Tabellenstruktur zurückzuführen sind. Soll heißen: Im Table Manager sind mehr Felder hinterlegt, als in der Datenbanktabelle o.ä.

Das Problem lässt sich, sofern noch keine Daten in der Tabelle liegen, eigentlich sehr einfach lösen: Wenn man die Felddefinition nimmt, in das YForm-Modul kopiert und die create_db-Action hinzu nimmt.

Diese Aktion könnte man, finde ich, auch als Button im Table Manager hinterlegen, als `Tabelle reparieren`. Wenn dieser Button aufgerufen wird, wird die Tabelle wieder auf den Stand aus dem Table Manager gebracht.

**Comment by tbaddade** [comment]
> Wenn dieser Button aufgerufen wird, wird die Tabelle wieder auf den Stand aus dem Table Manager gebracht.

Es kommt noch eine andere Variante ins Spiel:
Es gab bereits den Fall, dass in der Definition zwei Felder gleich hießen und somit ein reparieren der Tabelle nichts gebracht hat.

**Comment by dergel** [comment]
finde ich gut .. 

der 2. Fall vom Thomas ist ein Fehler.. D.h. ab dann kann man nichts mehr reparieren sondern muss manuell dran. Sowas darf nicht passieren und haben wir an den Stellen eigentlich schon behoben.

**Comment by dergel** [comment]
das haben wir nun eigentlich mit den festen Feldern bereits gemacht .. d.h. im Fehlerfall bei Tabelle mt Schemaanpassung auswählen und es sollte angepasst sein.
