### ISSUE TITLE
selects - in E-Mails den Optionnamen ausgeben und nicht die id

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#334]
Bsp.:
```
select_sql|label|name|SELECT name AS id, name FROM table ORDER BY name|||1|Bitte wählen Sie|
```

Damit wird der Optionnamen in den E-Mails korrekt angezeigt, aber die Zuordnung geht beim Verwalten der Tabelle im Backend verloren.

**Comment by tbaddade** [comment]
Einfache selects gingen bereits, indem man in den E-Mail-Templates dem name ein `_NAME` anhängt. Damit wurde die übergebene Id mit dem tatsächlichen Namen ersetzt.
`REX_YFORM_DATA[field="einsatzorte_NAME" prefix="Einsatzorte: "]`

Damit das auch bei multiple funktioniert, müssten man diese Zeile https://github.com/yakamara/redaxo_yform/blob/master/lib/yform/value/select_sql.php#L96 mit nachfolgenden Code ersetzen.

```
        $_NAME_VALUES = explode(',', $this->getValue());
        $_NAME_LABELS = [];
        if (count($_NAME_VALUES)) {
            foreach ($_NAME_VALUES AS $_NAME_VALUE) {
                if(isset($options[$_NAME_VALUE])) {
                    $_NAME_LABELS[] = $options[$_NAME_VALUE];
                }
            }
        }
        $this->params['value_pool']['email'][$this->getName() . '_NAME'] = count($_NAME_LABELS) ? implode(', ', $_NAME_LABELS) : null;
```

**Comment by dergel** [comment]
hattest du das im choicefeld bereits angepasst ?

**Comment by tbaddade** [comment]
> hattest du das im choicefeld bereits angepasst ?

Prüfe ich nochmal

**Comment by dergel** [comment]
ping

**Comment by alexplusde** [comment]
In Choice hatten wir diskutiert, ob man values oder labels in Emails benötigt. Da ist also auf jeden Fall was gemacht.
