### ISSUE TITLE
Fehlermeldung ab PHP 7.1: A non-numeric value encountered

### ISSUE THREAD

**Issue by brandes-webdesign** [yakamara/redaxo_yform#338]
Folgende Fehlermeldung bekomme ich nach dem Absenden:
Warning: A non-numeric value encountered in /kunden/239804_7260/rp-hosting/2050/5050/redaxo/src/core/lib/var/var.php on line 36
Warning: A non-numeric value encountered in /kunden/239804_7260/rp-hosting/2050/5050/redaxo/src/core/lib/var/var.php on line 37

Das ganze so oft, wie angelegte Felder.
Sind alles Textfelder

Das muss mit der PHP Version 7.1 zusammen hängen.
Bei 7.0.13 gibt es diese Fehler nicht.

Ist das Problem bekannt ?

**Comment by dergel** [comment]
Nein.. ist mir bisher nicht untergekommen.. ich benutze fast nur php 7.1 .. ich schliesse das mal .. wenn es noch passiert und auch bei der github version, gerne wieder öffnen

**Comment by gharlan** [comment]
Das ist im Core gefixt: https://github.com/redaxo/redaxo/commit/de8fd5f7d86ca31aaaa5e55f05f671b50107e472

Da wir zurzeit in unseren Projekten die 5.4-dev nutzen (wegen ydeploy), tritt bei uns der Fehler nicht auf.
