### ISSUE TITLE
Tablemanager "Datenergebnis editieren" ausblendbar machen

### ISSUE THREAD

**Issue by IngoWinter** [yakamara/redaxo_yform#340]
Es gibt keine Möglichkeit, den Button "Datenergebnis editieren" oberhalb der Listenansicht einer Tabelle für Redakteure auszublenden. Ich hatte gerade den Fall, dass ein Redakteur den gesamten Datenbestand geschreddert hat. Ich fände eine Checkbox gut, die den Button an/ausschaltet - Default aus.

**Comment by alexplusde** [comment]
Feature Massenbearbeitung an der Tabelle deaktivieren müsste reichen, oder nicht? (Hatten es doch schon in Slack davon). Vielleicht sollte man den Button "Datenergebnis editieren" auch anders bezeichnen, denn ein Kunde von mir hat auch schon aus 100 Personen in einer Tabelle 100 Müllers gemacht ;)

**Comment by alexplusde** [comment]
An der Tabelle im Table Manager, dort, wo du auch Import/Export und Suchfunktion anhaken kannst.

**Comment by IngoWinter** [comment]
Wo?
![wo](https://user-images.githubusercontent.com/7223820/28861356-d615dbcc-7760-11e7-9258-dea9ac0a0e20.png)

**Comment by alexplusde** [comment]
Du hast recht, ich habe mich getäuscht. Massenlöschung blendet nur den Button "löschen" am Datenergebnis aus. Bearbeiten ist aber genauso gefährlich...

Dann schließ ich mich mal deinem Issue an.

**Comment by tyrant88** [comment]
Ich auch! Kunde hat 5000 Datensätze zersägt!
