### ISSUE TITLE
Massenbearbeitung und mit Relationstabellen nicht möglich

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#341]
1. Die Auswahlfelder werden bei der Massenbearbeitung nicht angezeigt.
2. Datensätze können nicht gespeichert werden.

**Comment by tbaddade** [comment]
https://github.com/yakamara/redaxo_yform/blob/master/plugins/manager/lib/yform/value/be_manager_relation.php#L240-L242

Type 4 und Relationstabellen werden in multi-edit zurzeit nicht unterstützt. Es ist zurzeit bewusst so, dass die Felder nicht zum bearbeiten erscheinen. Das Speichern der Datensätze ist dadurch auch nicht möglich.

Vorschlag: Entweder den Bug zeitnah beseitigen oder wenn zu aufwändig, die Massenbearbeitung erst gar nicht ermöglichen (Wenn obige Felder in der Tabelle angelegt sind).

**Comment by DavidBruchmann** [comment]
Bei einer Debug-Ausgabe bekomme ich das Feld `mass_description` angezeigt, das Feld `mass_edit` fehlt aber.  
Geht momentan rein um die angezeigten Felder, unabhängig von Funktionalität.

**Comment by gharlan** [comment]
https://github.com/yakamara/redaxo_yform/commit/e2b07d335460f2df5fac189948dd87f85e24825e#diff-989ec6ace7bc55ab3aaf7fdd97c6e970

Seit diesem Commit sollte es so sein, wie zurzeit gedacht. Die Felder werden nicht unterstützt zum Ändern während einer Massenbearbeitung, daher tauchen sie bewusst nicht auf. 
Speichern geht aber, die Felder bleiben dabei so belegt wie zuvor.

Oder anders gesagt: Aus dem ersten Comment Punkt 2 (Bug) ist gelöst, Punkt 1 nicht, was aber kein Bug ist, sondern ein fehlendes Feature. ;)

**Comment by tbaddade** [comment]
> kannst du das gegenprüfen ?

funktioniert
