### ISSUE TITLE
Import klappt nicht

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#342]
angezeigter Fehler: `Es fehlen folgende Felder: ﻿name`

Das Feld existiert aber. Das csv ist auch korrekt formatiert. Einzig das die Anzahl der Felder im csv nicht mit denen in yform übereinstimmen. Wenn das der Auslöser für den Fehler ist, sollte man html values und be_manager_relation mit Relationstabellen herausnehmen.

**Comment by alexplusde** [comment]
Bei mir hat das mit den Anzahl der Feldern kein Problem gegeben, wenn man beim Import sagt, dass unbekannte Felder als TEXT hinzugefügt werden sollen.

**Comment by tbaddade** [comment]
> Bei mir hat das mit den Anzahl der Feldern kein Problem gegeben, wenn man beim Import sagt, dass unbekannte Felder als TEXT hinzugefügt werden sollen.

Das hatte damit nichts zu tun. Wenn es wieder auftritt öffne ich das Issue wieder und erkläre noch mal das genaue Vorgehen.
