### ISSUE TITLE
Table Manager: be_media Feld "default-Wert" hinzufügen

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#343]
Es sollte die Möglichkeit geben, einen Dateinamen für ein Bild zu hinterlegen, der eingetragen wird,  wenn das Feld nicht ausgefüllt wird.

**Comment by tbaddade** [comment]
Du meinst `be_media`? Ich sehe sowas eher im Modal, da man dadurch flexibler auch bei anderen Values wäre.

```php

class myTable extends \rex_yform_manager_dataset
{
    public function getImage()
    {
        return ($this->image != '') ? $this->image : 'default_image.jpg';
    }
}
```

**Comment by alexplusde** [comment]
Ja, `be_media` natürlich. 

Wenn ich das halt auch in der Datenbank stehen haben will, wäre es schon besser. Bei Checkboxen und Radio-Buttons bspw. gibt's ja auch die Möglichkeit, einen default-Wert zu hinterlegen. Die Meta-Infos bieten die Möglichkeit ja auch. Dann wäre das Verhalten zwischen Meta Infos und YForm konsistent.

**Comment by dergel** [comment]
Habe auch nochmal darüber nachgedacht .. leider sehe ich das auch nicht in der Db.. vor allem, weil ich in dem Moment nihct prüfe ob die Defaultdatei vorhanden ist ..
