### ISSUE TITLE
Yorm : Mysql Funktionen in where ermöglichen

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#345]
```
$query->where('date_from', 'CURDATE()', '>=')
```

Fände ich gut, da man sonst möglicherweise einfach nur noch das `whereRaw` nutzt.

**Comment by gharlan** [comment]
Woher soll die Funktion dann wissen, ob der Wert escaped werden muss?
Darum geht es ja, dass man in where in sicherer Weise einfach einen Wert, bzw. eine Variable reinwerfen kann.
Daher wird sich hier nichts ändern.
