### ISSUE TITLE
bei Geocode müssen zusätzliche Felder gelöscht werden

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#346]
In dieser Zeile
https://github.com/yakamara/redaxo_yform/blob/master/update.php#L25-L28

müssen die 2 Felder, die beim `google_geocode` unter `position`angegeben wurden, ebenfalls gelöscht werden.

Besser als löschen, wäre aber konvertieren :)

**Comment by dergel** [comment]
ich habe nachgesehen und nein .. das passt alles. weil das Feld vorher schon existiert und genauso funktioniert. Es wurde nur aus dem geoplugin verschoben und mit api key (etc) direkt im value feld erweitern
