### ISSUE TITLE
Auf Formulareingaben reagieren (Prosa für die Doku folgt / Ist nur ein Merkzettel hier)

### ISSUE THREAD

**Issue by olien** [yakamara/redaxo_yform#349]
$yf->setValueField('html',['','']);
if (rex_request('iamavalidator','int',0)) {
$yf->setValidateField('empty',['deinzuvalidierendesfeld','{{Bitte füllen Sie alle Felder aus}}']);
}

**Comment by alexplusde** [comment]
Kann man hier schließen
