### ISSUE TITLE
Table Manager: Nach csv-Import in bestehende Tabelle Probleme mit Autoincrement

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#351]
Habe eine CSV-Daten in eine bestehende Tabelle importiert, dabei wurden 6 Datensätze aktualisiert und 4 neue hinzugefügt. Nach dem Hinzufügen eines weiteren Datensatzes erhielt ich eine Fehlermeldung, dass der Primary Key bereits vorhanden war.

Eine Aktualisierung der Tabellenstruktur via Adminer an der Datenbank selbst hat das Problem gelöst.

**Comment by dergel** [comment]
Kannst Du mir das Tableset exportieren und den Datensatzpool ?

**Comment by dergel** [comment]
da ist viel passier.. sollte mittlerweile passen.. ist komplett umgebaut
