### ISSUE TITLE
Formular-Code: SQL-Abfrage und YOrm-Ausgabe hinzufügen

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/redaxo_yform#352]
Wenn schon Pipe-Schreibweise, PHP-Schreibweise und E-Mail-Templates aufgeführt werden, könnte man auch eine Beispiel-rex_sql-Abfrage und ein Beispiel als yorm-Objekt mit Hinweis zur Doku ausgeben, um das ganze den Entwicklern näher zu bringen und den Einstieg zu erleichtern.

**Comment by alxndr-w** [comment]
https://github.com/yakamara/redaxo_yform/blob/2a6f6edb54b73fe7f6ae233c45519e1319e141b5/plugins/manager/lib/yform/manager.php#L1181-L1268

@dergel PR gewünscht?

**Comment by dergel** [comment]
Ich würde das so belassen. Sehe das mehr in der Doku
