### ISSUE TITLE
be_manager_relation popup (single) trägt ID des Datensatzes doppelt ein

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#353]
Die ID wird bei popup_single in bestimmten Fällen doppelt eingetragen. In der Datenbank steht dann, trotz einfacher Auswahl, bspw. `2,2`, wenn ich Datensatz 2 auswähle.

Es passiert nur, wenn ich über eine gefilterte Draufsicht (be_manager_relation popup (1:n)) auf die Tabelle schaue und dort einen Datensatz hinzufüge, nicht jedoch, wenn ich die Tabelle direkt öffne.

Zugang zur betroffenen Installation per Slack.

**Comment by alexplusde** [comment]
Das Problem besteht nach wie vor. :/ Gibt's da evtl. schon einen fix zu?
![image](https://user-images.githubusercontent.com/3855487/30059231-84eee2c2-923e-11e7-9029-4206b16f6b1b.png)

**Comment by alexplusde** [comment]
Wir konnten es eingrenzen: Das passiert nur, wenn der Datensatz, der eingefügt wird, ein popup-Feld hat. Bei einem Select-Feld wird - hier in meinem Fall die building_id - regulär eingetragen.

**Comment by alexplusde** [comment]
Der Bug ist weiterhin bestehend und ich kann zumindest konkretisieren, dass die ID nicht doppelt eingetragen wird, sondern einfach bei jedem Speichern immer wieder angehängt wird. Habe jetzt bei einer anderen Website dasselbe Problem.

Im Feld steht dann bspw.: `32,32,32,32`, obwohl es `32` lautet.

**Comment by dergel** [comment]
Ich kann das leider nicht nachvollziehen. Bei meinen Tests mit Popup Single passiert das nicht. Kannst du nochmal frisch prüfen. Also nicht in Deiner Instanz sondern für mich reproduzierbar ? Aktuelle github Version ?

**Comment by alexplusde** [comment]
Zugang müsstest du bekommen haben...

**Comment by alexplusde** [comment]
Da ich das nicht mehr reproduzieren kann - vermutlich, weil ich das jetzt anderweitig löse, mache ich hier mal zu.
