### ISSUE TITLE
Value-Sortierung: Bezeichnung ausgeben statt Feldname

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#359]
![image](https://user-images.githubusercontent.com/3855487/30199945-34af8ec2-9475-11e7-8601-33f94a0b5065.png)

Hier könnte stehen statt `|name|value|text` bspw. Firmenname (value, text) etc.

**Comment by alexplusde** [comment]
@dergel ich habe da keinen Einfluss auf den Text, oder? Also `Firmenname (value, text)` ist nicht möglich, nur `feld 1|feld 2|feld 3`?

**Comment by dergel** [comment]
geht leider nur mit den Feldern.. Label habe ich aufgenommen. Reihenfolge habe entsprechend der Feldtabelle angepasst. `'type_id', 'type_name', 'name', 'label'` Also etwas anders aber ich hoffe für dich auch ok ..

**Comment by alexplusde** [comment]
Ist auf jeden Fall eine Verbesserung.
