### ISSUE TITLE
Table Manager: html + php-Value zusammenführen

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#360]
in puncto Aufräumarbeiten
- beide Felder sind strukturell gleich aufgebaut
- beide Felder landen nicht in der Datenbank
- php-value kann bereits einfach html ausgeben

Es gäbe somit keine Notwendigkeit mehr für das html-Feld.

**Comment by alexplusde** [comment]
@dergel du bist doch am Vereinfachen der Feldtypen für 3.0 - wäre das nicht noch was sinnvolles? html vorerst als deprecated markieren, da man alles auch mit PHP machen kann?

**Comment by dergel** [comment]
ich bin mir unsicher .. ich finde es inhaltlich schon gut, dass man das unterscheiden kann, auch wenn es im Prinzip mit einem Feld abdecken kann.. Deswegen hatte ich auch nicht darauf geantwortet.

Ich würde es eher so belassen wollen.

**Comment by alexplusde** [comment]
Ich ziehe das Issue zurück.
