### ISSUE TITLE
Alexa-Skill funktioniert nicht mehr

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#361]
Ich kann in der aktuellen Version keine neuen Datensätze per Alexa-Skill hinzufügen. Gibt's da einen fix?

**Comment by bdiekert** [comment]
Mein Google Home kann das auch nicht mehr. Bitte fixen.

**Comment by nilsology** [comment]
In YForm gabs das schon? Wäre doch direkt was für den Core...

**Comment by phoebusryan** [comment]
Stimmt, wäre schön wenn auch Siri Tabellen für mich anlegen könnte... würde einiges an Arbeit sparen.

**Comment by dergel** [comment]
ist das auch beim aktuellen Release so ? Bitte immer bei Testen die aktuelle Github Version nutzen.

**Comment by skerbis** [comment]
Die Apple Watch übersetzt es immer mit Why a form?!!$ Bitte fixen.

**Comment by alexwenz** [comment]
Wollte ich grade schreiben. Nicht dass ich eine Apple Watch hätte, aber einer dieser Apfel-Jünger hier hat mich grade angemeckert. Ts.

Und!!! : @nilsology "gab's" selbstverständlich mit Apostroph ("Auslassungszeichen")!!! Soviel Zeit muss sein. ;-)

**Comment by dergel** [comment]
@phoebusryan wegen Siri bitte ein extra issue.. wollten erst die keynote heute abend abwarten..

Bitte bei Alexa genau Beschreibungen .. Was wurde gesagt, Zeitpunkt, für welche REDAXO Instanz .. am liebsten hätte ich auch immer einen Testzugang, sonst lässt sich das leider wirklich schlecht nachvollziehen.

@nilsology für den Core wäre das auch cool.. stimmt

**Comment by Hirbod** [comment]
Kann mich bitte jemand aufklären? :D Siri? Alexa? Google Home?

**Comment by bdiekert** [comment]
@Hirbod Dies ist mehr oder weniger ein Witz-Issue um @dergel zu ärgern. Jedoch probiert @nilsology mittlerweile an einem Alexa Skill für Redaxo.

**Comment by Hirbod** [comment]
:D... spätchecker. Danke! Und ein Alexa Skill wäre cool, hab hier auch eine rumstehen :D
