### ISSUE TITLE
Email-Templates

### ISSUE THREAD

**Issue by renmlp** [yakamara/redaxo_yform#362]
Hallo,
ich habe Festgestellt, dass die E-Mail-Templates nur für einzelne E-Mails gedacht sind, wäre es möglich eine Funktionalität für einen Multiplen Versand zu machen?

Beispielsweise, hab ich eine Schleife, in dieser werden X Kunden durchgegangen, an diese soll jeweils eine Information mit Personalisierter Anrede sein, der Rest wie Datum usw. soll per Platzhalter austauschbar sein:
`Hallo |Anrede|,

Am {datum} findet {veranstaltungsname} statt.

Mfg,
{gruss}`
Hier soll zuerst {} Platzhalter ausgetauscht werden (bevor die schleife Startet) und danach ||, weil dadurch spare ich mir 3 mal ein replace pro versandter Mail. Außerdem sollte es möglich sein, dass das PHP Mailer Object nur einmal Instanziiert wird

**Comment by alexplusde** [comment]
Du meinst quasi eine Newsletter-Funktion? Da gibt's meines Wissens ein Addon dafür.

**Comment by dergel** [comment]
das sehe ich auch eher beim Newsletter oder eigener Entwicklung
