### ISSUE TITLE
Yform speichert Records doppelt 

### ISSUE THREAD

**Issue by geraldurbas** [yakamara/redaxo_yform#363]
Es werden immer 2 Records mit unterschiedlcihen Timestamps in der Tabelle gespeichert... schlimm weil die Übersicht ist dahin.

**Comment by skerbis** [comment]
Wann tritt das Problem auf?

**Comment by geraldurbas** [comment]
Yform V: 2.3b2
Einfaches Testform mit 2 Feldern in eine Tabelle mit 2 entsprechenden Feldern, Email wird einmal verschickt. DB Eintrag kommt doppelt.

Test mit einem generate_key|timestamp|timestamp Feld ergibt das offensichtlich irgendwie das ganze doppelt ausgeführt wird intern.

**Comment by tyrant88** [comment]
Du hast aber nicht eine action im formular und die des Moduls aktiv?

**Comment by alexplusde** [comment]
https://github.com/yakamara/redaxo_yform/issues/353

**Comment by geraldurbas** [comment]
da wurde 2mal getArticle im template aufgerufen... das kann man schließen.

**Comment by alexplusde** [comment]
Ich würde das gerne wieder aufmachen und Lösungsalternativen diskutieren. 

2x `getArticle()` in einem Template können grundsätzlich ein Problem sein - sollten aber nicht zwangsweise dazu führen, dass dieses Problem auftritt.

Kann YForm zur Laufzeit beim Absenden des Formulars evtl. eine Property setzen, z.B. `rex::setProperty('yform_sent',FORM-ID)` und beim zweiten Aufruf gegenprüfen?

**Comment by dergel** [comment]
Lösungsansatz ist ein anderes, hat dann aber nichts mit YForm zu tun.

Im REDAXO Core abfangen und den bereits gecachten Inhalt ausgeben. Dann wäre dieses Thema wohl durch :) ..
