### ISSUE TITLE
Keine Suchspalte ausgeben und optimieren

### ISSUE THREAD

**Issue by Hirbod** [yakamara/redaxo_yform#368]
Die Suchspalte sollte nicht ausgegeben werden, wenn man einen Datensatz editieren oder neu anlegen möchte. Das ist verschwendeter Platz. Des Weiteren reicht ein 2-Spaltiges Suchcol wirklich nicht. Ich hab so viel negatives Feedback von den Kunden bekommen, dass es "scheisse aussehen würde" so eine gequetschte Suchspalte zu haben.

**Comment by tbaddade** [comment]
> Des Weiteren reicht ein 2-Spaltiges Suchcol wirklich nicht. Ich hab so viel negatives Feedback von den Kunden bekommen, dass es "scheisse aussehen würde" so eine gequetschte Suchspalte zu haben.

Und wie sehen deine Vorschläge und Ideen dazu aus?

**Comment by alexplusde** [comment]
Die Suche war meines Wissens mal über der Tabelle aller Datensätze, statt seitlich. Und aus-/einklappbar? Ob das jetzt ein Gewinn wäre, kann man drüber streiten.

Die Suchspalte in der Editieransicht anzuzeigen, halte ich aber auch für überflüssig.

**Comment by gharlan** [comment]
Mal als Idee zur Diskussion:

* Ein allgemeines Suchfeld oben drüber, was so gut es geht, alle Felder durchsucht. Dabei auch #273 und #279 beachten.
* Den Kasten, wo das Suchfeld drin ist, aufklappbar machen, wo dann die Einzelfelder der jetzigen Suche erscheinen
* Wobei man diskutieren könnte, ob es für die Textfelder überhaupt Einzelsuchfelder braucht, oder nur für die Felder, die mit einer Textsuche nicht so gut funktionieren (Datumsfelder, Select, Checkboxes, be_relation etc.)
* Eventuell eine weitere Einstellung anbieten, sodass man manche dieser Einzelsuchen dauerhaft neben dem Hauptsuchfeld anzeigen lassen kann. Quasi als Filter, für Dinge, nach denen man häufig filtern möchte

**Comment by Hirbod** [comment]
Ich finde alle Ideen von dir gut, @gharlan 
So ein globales Suchfeld wäre natürlich super fein. 

@tbaddade ich denke mir, der Platz in der Tabelle geht vor. D.h. Suche entweder on-click über der Tabelle öffnen (verursacht aber "herumgeschiebe"), oder besser, die Suche öffnet im Modal (mit Colbreite 4-6). Dann könnte man schnell seine Suche eingeben und abschicken.

**Comment by dergel** [comment]
1. Kann man diskutieren, wäre für mich ein Zusatz zur spezifischen Maske
2. Finde ich gut (Bei der Editiermaske könnte man es auch noch rausnehmen)
3. Finde es schon wichtig. Es geht ja nicht nur um das schnelle Finden, sondern eben auch um Massenbearbeitung/Löschung .. also eher auch um größere Tabellen und spezifische Suchen
4. Wäre eine Idee.. Damit kommen wir langsam der View und Filter Geschichte näher :)

Vielleicht erstmal mit dem 2. Punkt anfangen.

**Comment by tbaddade** [comment]
zu 3.

Fände es gut, wenn Texfelder zusammengelegt werden können. Habe eben Tabellen für Mehrsprachigkeit angepasst und da wird die Suche schon recht lang und unübersichtlich.
Da im Datensatz die Sprachen via Tabs dargestellt werden, sind die Labels der Felder alle gleich benannt. Ein Ausschnitt der Suche sieht dann aktuell so aus:


![screenshot 2018-03-13 14 41 01](https://user-images.githubusercontent.com/338267/37345185-a5729cb4-26cc-11e8-846a-d9d20df6d14f.png)

**Comment by dergel** [comment]
Suche über mehrere Felder hinweg am besten mit einem index feld lösen. Dort dann die entsprechenden Felder rein indexen und über die Suche dann nutzen.

Irgendwas mit der Suche fest einzubrennen finde ich nicht gut, aber ein allgemeines Layout in der Tabelle auswählen zu können, wäre vielleicht sinnvoll, mache ein neues Issue dazu auf.
