### ISSUE TITLE
YForm übergibt zu viel Information an die Action

### ISSUE THREAD

**Issue by Sioweb** [yakamara/redaxo_yform#37]
Ho!

Wenn ich eine Action definiere in YForm und die ausführe, hat der Parameter viel zu viel Information doppelt und dreifach.

```
action|callback|MeineKlasse::methode
```

Das ist ein RAM-Killer und relativ umständlich zu nutzen. Der Output von nur einem Objekt ist mehrere tausend Zeilen lang wenn man ein paar Input-Felder definiert hat.

**Comment by dergel** [comment]
hmm .. eigentlich sollt das kein ramkiller sein.. die Objekte werden ja in PHP5 nur noch als Zeiger weitergegeben .. Nur wenn man das über z.B. vardump ausgibt kann das eventuell zum memorylimit führen.... Wir übergeben an diversen stellen das yrewrite hauptobjekt und das immer wieder.. Bei Ausgaben nicht immer gut überschaubar..

Oder meinest du was anderes ?

**Comment by dergel** [comment]
ich schliesse das mal.. wenn wirklich noch ein problem - dann öffne das issue einfach wieder.
