### ISSUE TITLE
YOrm: korrektes Abrufen von getForm()?

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#370]
Ich habe es folgendermaßen verwendet:

in der boot.php 
```
rex_yform_manager_dataset::setModelClass('rex_yf_dance_filter', DanceCourseFilter::class);

class DanceCourseFilter extends \rex_yform_manager_dataset
{
}
```

im Modul
```
dump($filter = DanceCourseFilter::getForm());
```

Fehlermeldung:
```
Using $this when not in object context

Error 
…/redaxo/src/addons/yform/plugins/manager/lib/yform/manager/dataset.php522

rex_yform_manager_dataset getForm
rex:///module/5/output17
```

**Comment by gharlan** [comment]
`getForm` ist keine statische Methode, sondern, muss für einen bestimmten Datensatz aufgerufen werden (kann auch ein neuer sein).
Der ganz grobe Ablauf ist so: (Kopie aus meinem YOrm-Vortrags-PDF):

```
$post = rex_blog_post::get($id);

$yform = $post->getForm();

// $yform->setHiddenField();
// $yform->setObjparams();

echo $post->executeForm($yform);
```

Statt `rex_blog_post::get($id)` könnte man also auch `rex_blog_post::create()` verwenden.

**Comment by alexplusde** [comment]
@gharlan Danke fürs Erklären. Dann komme ich in meinem Fall besser ohne YOrm damit aus.
