### ISSUE TITLE
Action createdb : -> create_table ändern

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#379]
Sollte die Action von Haus aus das Prefix voranstellen?

| Action | erstellte Tabelle |
| - | - |
| `action\|createdb\|project_table`| `rex_project_table` |
| `action\|createdb\|rex_project_table`| `rex_project_table` |

Und müsste die Action nicht in `create_table` umbenannt werden?

**Comment by alexplusde** [comment]
create_table wäre korrekt. - Einen Parameter, der sagt, ob auch fehlende Table Manager Felder mit angelegt werden, wäre in dem Zuge ganz nett.

**Comment by dergel** [comment]
aehh.. also nur das mit dem create_table meine ich

**Comment by dergel** [comment]
Prefix würde ich nicht so machen ..

**Comment by tbaddade** [comment]
> Prefix würde ich nicht so machen

Eventuell via Platzhalter wie in den install.sql Dateien?
`action|createdb|%TABLE_PREFIX%project_table`

**Comment by dergel** [comment]
klingt nach einer sinnvollen einfachen Lösung :)
