### ISSUE TITLE
Action createdb : TablePrefix unterstützen

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#380]
siehe #379 

Eventuell via Platzhalter wie in den install.sql Dateien?
`action|createdb|%TABLE_PREFIX%project_table`

dergels Kommentar:
> klingt nach einer sinnvollen einfachen Lösung :)

**Comment by dergel** [comment]
ist gemacht

https://github.com/yakamara/redaxo_yform/commit/ea360b5224a5f103520a7dde68d4ecb1db630c43
