### ISSUE TITLE
rex_yform_validate_labelexist -> rex_yform_validate_nameexist

### ISSUE THREAD

**Issue by dergel** [yakamara/redaxo_yform#381]

**Comment by alexplusde** [comment]
oder fieldexist?

**Comment by dergel** [comment]
vielleicht wäre das hier auch passend, aber name ist die entsprechend verwendete Bezeichnung. Sobald es ein Field ist, ist es ein Datenbankfeld, was nur so ist, falls es auch dort gespeichert wird.

**Comment by alexplusde** [comment]
stimmt, das vergesse ich immer.

**Comment by tbaddade** [comment]
> rex_yform_validate_nameexist

`rex_yform_validate_name_exists` (Unterstrich und zusätzliches **s**) abgeleitet von der Funktion `file_exists`

**Comment by dergel** [comment]
Update noch einbauen von .. 

// labelexist -> name_exists
// existintable -> exists_in_table

**Comment by dergel** [comment]
Infos an docs

**Comment by dergel** [comment]
sollte nun passen. gerne auch mal austesten

**Comment by erraiva** [comment]
`Class does not exist "rex_yform_validate_labelexist" `
Habt ihr das auch? Wenn das geändert wurde muss es noch in der Doku geändert werden.
LG Heinz

**Comment by erraiva** [comment]
Das hört sich aber so an, als könnte ich bei der Pipe-Schreibweise einfach ...|nameexist|... einsetzen.
Stimmt aber nicht. Class does not exist "rex_yform_validate_nameexist". Wie gehts denn?

**Comment by erraiva** [comment]
ist das jetzt in_names?

**Comment by tbaddade** [comment]
Im verlinkten Issue steht es doch

> Anpassungen: 
> labelexist -> name_exists
> existintable -> exists_in_table

Ich weiß nicht was du genau validieren willst, aber entweder musst du `name_exists` oder  `exists_in_table` nutzen

**Comment by erraiva** [comment]
Class does not exist "rex_yform_validate_name_exists". in_names funktioniert.

**Comment by erraiva** [comment]
Aha:
hier stehts:
https://github.com/yakamara/redaxo_yform/blob/master/README.md#last-changes
weiter unten:
... umbenannt und werden initial aus der YForm Definition entfernt
    labelexist -> in_names
    existintable -> in_table

Bitte noch in die Doku übernehmen, dort steht noch "labelexists".
labelexists führt jetzt zu im Frontend sichtbaren Fehlermeldungen. Da darf ich jetzt auf einigen Webseiten korrigieren, na denn ...

**Comment by dergel** [comment]
Nehmen gerne Doku PRs entgegen :)

**Comment by erraiva** [comment]
ich meinte die yform - Doku ;-)

**Comment by dergel** [comment]
und genau die meine ich auch :)

https://github.com/yakamara/redaxo_yform_docs/issues/102

dort kann man auch PRs hinterlassen..

**Comment by erraiva** [comment]
Hmm, da hab ich mich noch nicht mit beschäftigt. Ich eröffne einen neuen Pull Request? Und wie kommt die Änderung dann in die yform-Dokumentation?

**Comment by dergel** [comment]
Das ist leider zu viel für dieses Issue. Müsstest du googeln.

**Comment by alexplusde** [comment]
@erraiva melde dich bei mir in Slack. wenn du uns da unterstützen möchtest, gebe ich dir gerne Starthilfe.

**Comment by alexplusde** [comment]
Bitte um Hilfe für die Doku: https://github.com/yakamara/redaxo_yform_docs/pull/152
