### ISSUE TITLE
Zeitstempel nicht ausgeben, wenn Wert leer

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#383]
Szenario: Eine Table Manager Tabelle hat ein createdate-Feld, ein Formular füllt dieses nicht aus. Im Table Manager wird bei der Datensatz-Ansicht dann das aktuelle Datum ausgegeben.

Richtig wäre, dass ein nicht ausgefülltes Feld auch keinen Zeitstempel anzeigt.

**Comment by dergel** [comment]
@alexplusde prüf mal bitte wie das Feld innerhalb der YForm definiert ist. es gibt die Möglichkeit das entsprechend einzustellen.

**Comment by alexplusde** [comment]
Da brauche ich nichts weiter prüfen: Wenn das Feld in der Datenbank leer ist, darf YForm in der Editieransicht nicht einfach angeben, der Datensatz sei von gerade eben, sondern eben noch ohne Zeitstempel.

**Comment by dergel** [comment]
ach so.. jetzt hab ichs verstanden .. ok ..

**Comment by dergel** [comment]
kannst du es gegenprüfen ?

**Comment by alexplusde** [comment]
getestet. Passt.
