### ISSUE TITLE
Feld in DB speichern scheitert wegen "-" im Feld- / Spaltennamen

### ISSUE THREAD

**Issue by TobiasKrais** [yakamara/redaxo_yform#384]
YForm: 2.3-b4
Im Standardmodul gebe ich folgendes Feld ein:
`checkbox|abendprogramm_2017-05-16|16.05.2017|Nein, Ja|0|db`

Beim Speichern in die Datenbank kommt folgender Fehler
> Error while executing statement "INSERT INTO `blabla` SET ... `abendprogramm_2017-05-16` = :abendprogramm_2017-05-16" using params { ...,"abendprogramm_2017-05-16":" Ja"}! SQLSTATE[HY093]: Invalid parameter number: parameter was not defined

Dieser Fehler kommt immer, wenn ich ein Checkbox Feld unter den Felddefinitionen habe, entferne ich sie wird das Formular korrekt gespeichert.

**Comment by alexplusde** [comment]
sicher, dass da ein `db` dahinter kommt?

**Comment by TobiasKrais** [comment]
In XForm war das so. Ist das in YForm nicht mehr der Fall? Die Doku ist noch genau gleich wie in XForm:
`checkbox|name|label|Values(0,1)|default clicked (0/1)|[no_db]`

**Comment by alexplusde** [comment]
der letzte Parameter ist optional und benötigt nur ein `no_db` oder nichts. Aber ob das den Fehler verursacht, kann ich nicht sagen. Das Leerzeichen vor `Ja` ist auch zu viel (sollte aber kein Problem geben)

Es wäre hilfreich, den kompletten SQL-Befehl samt Fehlermeldung zu bekommen. Die Fehlermeldung zur unterschiedlichen Anzahl an Parametern lässt ja viel Spielraum. 

Das Feld existiert auch wirklich in der Datenbanktabelle? Würde außerdem noch versuchen, die Minuszeichen wegzulassen. (Ins blaue geraten)

**Comment by TobiasKrais** [comment]
Danke für deinen Tipp. Das Minuszeichen im Feldnamen ist die Ursache und killt das INSERT. Nachdem ich die Spalten der Tabelle umbenannt habe funktioniert alles wieder korrekt. Danke!!!

**Comment by tbaddade** [comment]
https://github.com/yakamara/redaxo_yform/issues/386

**Comment by dergel** [comment]
schliesse ich, geht bei #386 weiter
