### ISSUE TITLE
Bug in overview.php - Table Prefix fehlt.

### ISSUE THREAD

**Issue by martinm79** [yakamara/redaxo_yform#389]
Bug in:
`\redaxo\src\addons\yform\pages\overview.php`

Dort steht:
`$gm->setQuery('select * from rex_module where output LIKE "%' . $searchtext . '%"');`
Das gibt dann aber ein Fehler bei Installationen, wo der Tabellen Preix von rex_ geändert wurde.

Folgendes löst das Problem:
`$gm->setQuery('select * from ' . rex::getTable("module") . ' where output LIKE "%' . $searchtext . '%"');`

Zudem gab ein Problem beim Update. 
Aber es kann sein, das es mit dem Fehler zusammen hängt. Ansonsten sollte man das gleiche bei der Installatione oder Update routine nochmal kontrollieren, ob dort der selbe Fehler vorliegt.

Labels kann hier nicht jeder definieren?

Viele Grüße 
Martin M bzw. MMO

**Comment by dergel** [comment]
ich habe nur das mit den Modulen und dem Prefix geändert. Sollte noch etwas sein, bitte als neues Issue. lg
