### ISSUE TITLE
ExtensionPoint YFORM_DATA_UPDATED: Wert „data“ leer

### ISSUE THREAD

**Issue by shauste** [yakamara/redaxo_yform#391]
Mir ist aufgefallen, dass am Extension Point `YFORM_DATA_UPDATED` der Wert `data` leer ist. Statt `$this` sollte `$this->getData()` eingetragen werden.

https://github.com/yakamara/redaxo_yform/blob/3a2d2170203ae1bf4c2f5873097bcc22e7d5551c/plugins/manager/lib/yform/manager/dataset.php#L595

**Comment by alexplusde** [comment]
Ist es nicht korrekt, dass an der Stelle $this übergeben wird? Dürfte auch nicht leer sein, eigentlich sollte das ganze Objekt übergeben worden sein.

**Comment by shauste** [comment]
Das komplette data-array ist leer. Habe es mit `$this->getData()` getestet, dann waren die Daten da.

**Comment by dergel** [comment]
auch wenn es vielleicht besser wäre, nur die Werte von getData auszugeben, ist das hier nicht mehr zu ändern. Da dieser EP bereits von anderen AddOns verwendet wird.

**Comment by alxndr-w** [comment]
Ich würde das gerne noch als fix für 5.0 sehen

**Comment by dergel** [comment]
Bei mir ist das Objekt in $this .. sollte also mittlerweile passen
