### ISSUE TITLE
Action : tpl2email - Label und E-Mail-Adresse an selber Position

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#396]
Da man actions mehrfach notieren kann und es mit den Pipes immer wieder Probleme gibt, folgende Idee

**Vorher**
`action|tpl2email|emailtemplate|emaillabel|[email@domain.de]|`

**Nachher**
`action|tpl2email|emailtemplate|emaillabel oder email@domain.de|`

**Im Formbuilder würde man es so notieren**
`action|tpl2email|template|email`
`action|tpl2email|template|info@meineemail.de`

Innerhalb der Action wird geprüft, ob das label in den values existiert oder ob es sich um eine E-mail-Adresse handelt und versendet dann entsprechend die E-Mail.

**tl;dr**
Position 3 und 4 zusammenlegen

**Comment by alexplusde** [comment]
Ist zwar (in der aktuellen Fassung) ein super Stolperstein, um Leute in den Slack-Channel zu bekommen. So 1x/Monat kommt jemand mit genau diesem Problem, dass man den Parameter verkehrt notiert hat.

Sollte man trotzdem verbessern.

**Comment by dergel** [comment]
ja, zusammenlegen finde ich gut

**Comment by alexplusde** [comment]
Bitte um Feedback zu meinem PR
