### ISSUE TITLE
be_manager_relation: Daten aus Relationstabelle werden nicht gespeichert

### ISSUE THREAD

**Issue by dzinedev** [yakamara/redaxo_yform#398]
Ich habe eine Tabelle STELLEN und eine Tabelle PLANER. Einer Stelle können mehrere Planer zugeordnet werden. Dafür habe ich eine Relationstabelle STELLEN-PLANER.

Für die Relationstabelle STELLEN-PLANER habe ich zwei Felder vom Typ be_manager_relation angelegt: id_stelle (mit Zieltabelle STELLEN) und id_planer (mit Zieltabelle PLANER)

Für die STELLEN-Tabelle habe ich ein Feld planer angelegt mit Zieltabelle PLANER und Relationstabelle STELLEN-PLANER.

Über die Relationstabelle kann ich direkt einen Eintrag mit einem Planer und einer Stelle anlegen. Diese Zuordnung sehe ich dann auch in der Stelle. Wenn ich über die Stelle allerdings einen weiteren Planer hinzufüge, wird dieser nicht übernommen. Auch wenn noch gar keine Zuordnung für diese Stelle besteht und ich dieser Stelle einen oder mehrere Planer zuordnen will, wird dies nicht übernommen.

Ich frage mich zudem woher denn klar sein soll, dass wenn ich über die Stelle einen Planer hinzufüge, dass dieser im Feld id_planer gespeichert werden soll. Das Feld kann ich ja bei der be_manager_relation Eingabemaske gar nicht angeben. Ich hatte erst gedacht, dass das Feld "**Ziel Tabellenfeld(er) zur Anzeige oder Feld, das die Relations-ID enthält.**" dafür da ist. Aber das bestimmt ja nur die Ausgabe. Wenn ich dort id_planer angebe, wird diese natürlich in der Stellen Tabelle nicht gefunden und ich bekomme einen Fehler.

**Comment by gharlan** [comment]
So wie du es hier beschreibst, hast du es eigentlich richtig konfiguriert!

> Ich frage mich zudem woher denn klar sein soll, dass wenn ich über die Stelle einen Planer hinzufüge, dass dieser im Feld id_planer gespeichert werden soll.

Da wird so vorgegangen: Es werden alle be_manager_relation-Felder in der Relationstabelle (bei dir STELLEN-PLANER) betrachtet und das erste Feld davon genommen, das als Zieltabelle die richtige Tabelle hat.

Eigentlich sollte es so funktionieren, wie du es eingerichtet hast, und ist bei vielen so im Einsatz.
Gibt es vielleicht die Möglichkeit, mir einen Redaxo-Zugang zukommen zu lassen, damit ich es mir mal anschauen kann?

**Comment by alexplusde** [comment]
Die Beschriftung der Felder ist nicht ideal.

@dzinedev hast du auch einen Blick in die YForm-Doku dazu geworfen? Da wird auf das Feld und die Relationen näher eingegangen.

**Comment by dzinedev** [comment]
@alexplusde Ich habe mich bei der Beschriftung der Felder an das Beispiel aus der YForm-Doku gehalten. Was genau meinst du damit, dass die Beschriftung nicht ideal ist? Du meinst die Felder id_spalte und id_planer?

**Comment by dzinedev** [comment]
Das Problem liegt in der Mehrfachauswahl. Mit "select (multiple)" funktioniert es, mit "popup (multiple)" werden die Änderungen nicht übernommen. Ideen warum das so ist?

**Comment by alexplusde** [comment]
Ne, ich meinte `Ziel Tabellenfeld(er) zur Anzeige oder Feld, das die Relations-ID enthält` ist nicht so ideal. von deiner Seite aus ist alles richtig.

Ah, Mehrfachauswahl... da war doch was...

**Comment by gharlan** [comment]
Ich kann das bestätigen, mit "popup (multiple)" funktioniert es nicht. Ich schaue mir das an.
