### ISSUE TITLE
db-action: EPs (z.B. yform_data_added) aufrufen

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/redaxo_yform#399]
Wenn man aus dem Frontend einen neuen Datensatz mit der action `db` anlegt, sollte konsequenterweise auch der EP aufgerufen werden... oder?

**Comment by alexplusde** [comment]
Gerade gesehen, dass es einen EP `REX_YFORM_SAVED` gibt, der sich aber vom Syntax her von `YFORM_DATA_ADDED` unterscheided, also nicht dieselben Parameter / Objekttypen mitliefert. M.E. gehört das vereinheitlicht, indem bspw. analog zu YFORM_DATA_ADDED ein passendes dataset mitgeliefert wird.

**Comment by dergel** [comment]
ich denke eigentlich auch .. aber ich bin mir nicht sicher, ob sich das so machen lässt. In DB Action sind eventuell gar keine Tabellen entsprechend definiert etc. Da aufwändiger, verschiebe ich das.

**Comment by dergel** [comment]
ansich wird der EP bereits aufgerufen.. aber leider im moment immer - d.h. ich müsste noch unterscheiden, ob ein Datensatz überhaupt gespeichert/erstellt/geupdated wurden.

**Comment by dergel** [comment]
REX_YFORM_SAVED heisst nun YFORM_SAVED und wir mittlerweile nicht immer ausgeführt, sondern nur wenn auch wirklich ein Datensatz erstellt oder aktualisiert wurde.

die anderen YFORM_DATA* EPs funktionieren nur im Manager. Wunsch verstehe ich, aber ich schliesse dennoch das issue, weil es ein langer Weg dahin ist und wir dann eher einen kompletten Umbau gemacht haben
