### ISSUE TITLE
Idee: Tabelle in Dashboard anzeigen

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#4]
Außer RexSearch benutzt ja kein nennenswertes Addon aktuell das Dashboard so richtig. Aber wäre das Dashboard nicht ein klasse Shortcut für yform-Tabellen?

Ich stelle mir das so vor: Jede Tabelle bekommt in yform zusätzlich noch eine Checkbox "im Dashboard anzeigen", jedes Feld ein "im Dashboard anzeigen". So könnte man die Dashboard-Ansicht aufwerten, in dem man z.B. die letzten registrierten User, die letzten Mitteilungen, oder was auch immer Kunden oder Nutzer der Website gerade in eine Tabelle eingetragen haben.

(Dies ist auch ein Vorschlag im Hinblick auf das Thema beim Redaxo-Tag, sich mehr gute Funktionen von anderen CMS abzuschauen. Wordpress z. B. ist ja da ziemlich umfangreich in seinem Dashboard)

**Comment by dergel** [comment]
absolut.. eventuell noch sowas wie eine historie, welche dten zuletzt bearbeitet wurden etc .. 

was aktuell schwierig ist, ist das dashboard addon. Im moment nochnicht im core und daher sind die abhaengigkeiten schwierig - also was yform tun muss um da aufzutauchen.. ist auch die frage, ob das dashboard nicht selbst als plugin anbieten könnte.. 

gleiches problem ist auch beim watson addon .. die tabelleninfos sollten auch auffindbar sein.

deswegen muss ich im moment die idee erstmal vertagen.. gibt auch noch zuviele bugs in yform .. das muss erstmal ordentlich wieder laufen..

**Comment by alexplusde** [comment]
Klar. Ich schmeiß hier nur Ideen rein <ironie> für den Tag X, an dem euch langweilig wird </ironie> oder einer aus der Community sagt: Klasse, das setze ich um. So lange bleibt's halt mal offen...

**Comment by dergel** [comment]
kein dashboard bisher in unmittelbarer planung für redaxo 5 ..
