### ISSUE TITLE
Zuordnung von CSS-Klassen auf Felder

### ISSUE THREAD

**Issue by skerbis** [yakamara/redaxo_yform#40]
Wenn eine Class ausgewählt wird, wird diese dem Wrapper, z.B. form-group zugeordnet. Wenn man z.B. Redactor einsetzen will ist das nicht möglich. redactorEditor-full wird nicht dem Textfeld zugeordnet sondern dem Wrapper.

**Comment by dergel** [comment]
https://github.com/yakamara/redaxo_yform/issues/106
