### ISSUE TITLE
TableManager: Gelöschte Tabellen werden in der DB nicht gelöscht

### ISSUE THREAD

**Issue by olien** [yakamara/redaxo_yform#400]

**Comment by alexplusde** [comment]
Ist, glaube ich, ein Feature - auch gelöschte Felder bleiben erstmal erhalten, um ein unbeabsichtigtes Löschen aus Versehen zu verhindern.

**Comment by dergel** [comment]
genau .. es ist nicht gewollt, dass man tabellen löscht .. aber eine funktion könnte man dazu noch erweitern, ähnlich wie bei den feldern .. da gibt es ja sowas wie "mit Feldlöschung"..

**Comment by alexplusde** [comment]
Eine einfache Meldung nach dem Löschen der Tabelle würde ja vorerst genügen.
