### ISSUE TITLE
yform css class namen werden nicht ausgegeben

### ISSUE THREAD

**Issue by gseilheimer** [yakamara/redaxo_yform#401]
Hallo zusammen,

in der letzten Version von diesen coolen Tool werden bei den Text-Elementen die CSS-Klassennamen nicht berücksichtigt bzw. ausgegeben...

**Beispiel.**
 text|tel|{{ form_tel }}||[no_db]|col-xs-6 col-sm-4
_Ausgabe der CSS-Klasse "col-xs-6 col-sm-4" fehlt aktuell._

**Comment by alexplusde** [comment]
@gseilheimer du hast aber schon gesehen, dass seit YForm 2.0 das Feld für Attribute vorgesehen ist und im JSON notiert wird? Siehe Doku. 

Ich glaube das kann man hier schließen.
