### ISSUE TITLE
PHP Warning - Not a number in yform_email_template

### ISSUE THREAD

**Issue by black-msb** [yakamara/redaxo_yform#405]
https://github.com/yakamara/redaxo_yform/blob/137d829b4c76e7c9f8b2c38ef359e723fd06157c/plugins/email/lib/yform_email_template.php#L58

Der zweite Parameter müsste ein NULL sein, da sonst in der Funktion parse der var.php aus dem Core eine Warning wirft.

Danke und Gruß, Markus

**Comment by gharlan** [comment]
Kann es sein, dass du REDAXO <= 5.3 verwendest? Denn seit 5.4 sollte die Warnung nicht mehr kommen.

**Comment by black-msb** [comment]
Das ist so richtig. Danke für den Hinweis.
Da jetzt ja dann auf int geparsed wird, wird das dann auch tun. Danke nochmals.
