### ISSUE TITLE
Update schlägt fehl: 2.3-beta3 -> 2.3-b5

### ISSUE THREAD

**Issue by BjoernLindner** [yakamara/redaxo_yform#407]
AddOn "yform" konnte aus folgendem Grund nicht aktualisiert werden:
SQL error: Error while executing statement "ALTER TABLE `rex_yform_history` CHANGE `id` `id` int(10) unsigned NOT NULL auto_increment;"! SQLSTATE[HY000]: General error: 1833 Cannot change column 'id': used in a foreign key constraint 'rex_yform_history_field_ibfk_1' of table 'rex_yform_history_field'

was kann ich tun?

Version

REDAXO 5.5.0
PHP 7.0.25 
MySQL 5.6.37-log

**Comment by tbaddade** [comment]
Lösung erfährst du hier
https://github.com/yakamara/redaxo_yform/issues/234

Ist eein Problem des Cores und nicht von Yform.
