### ISSUE TITLE
CSV Export unvollständig

### ISSUE THREAD

**Issue by IngoWinter** [yakamara/redaxo_yform#408]
Beim Export von Datensätzen als CSV per Table Manager fehlen am Ende einige Zeichen. Liegt daran, dass [hier](https://github.com/yakamara/redaxo_yform/blob/master/plugins/manager/lib/yform/manager.php#L292) `header('Content-Length: ' . $fileSize);` die Ausgabe direkt danach (BOM für Excel?) nicht berücksichtigt. 

PHP 7.1 FPM

Edit: diese paar fehlenden Zeichen führen beim Import in OpenOffice dazu, dass die komplette Zeile fehlt - was ziemlich bitter ist ^^

**Comment by dergel** [comment]
@IngoWinter kannst du diese Änderung testen ?

**Comment by IngoWinter** [comment]
Läuft astrein 👍
