### ISSUE TITLE
Neues Feld hinzufügen - Prio Standardmäßig auf "Am Ende" stellen

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#409]
Wenn man eine Reihe von neuen Feldern hinzufügt, indem man bspw alle Felder bei der Feldauswahl in neuen Tabs öffnet, werden diese "rückwärts" hinzugefügt, weil zu jenem Zeitpunkt nur "Am Anfang" voreingestellt ist.

Umgekehrt würde es mehr Sinn ergeben, weil man die Felder dann in einem Rutsch hintereinander hinzufügen kann.

**Comment by dergel** [comment]
ich hatte das leider zuerst falsch verstanden, deswegen hier entsprechend aufgenommen. Ich denke, "Am Ende" ist unpraktisch weil es meist auch einen letzten Datensatz gibt, der das Ende ist. Einen zusätzlichen Punkt finde ich nicht sinnvoll.. also sowas wie den letzten Datensatz + "Am Ende", weil das meines Erachtens noch mehr verwirrt. Ich würde es gerne so belassen.'

Beim Erstellen eines Feldes, wählt er automatisch den letzten Datensatz aus, d.h. dieses Problem taucht mehr oder minder nur auf, wenn man neue Fenster aufmacht. Ich hoffe es ist ok, wenn ich das issue schliesse

**Comment by alexplusde** [comment]
Schade.
