### ISSUE TITLE
REX_YFORM_TABLE_DATA - LIST - Popup schließt sich nach jedem "übernehmen"

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#410]

**Comment by dergel** [comment]
was bei single select ja ok wäre, aber bei multiple eben nicht. kann das nachvollziehen und ist ein bug

**Comment by tbaddade** [comment]
> hier klappt es.

Hier auch

**Comment by tbaddade** [comment]
Klappt doch noch nicht. Popup schließt sich nach Klick auf "übernehmen".

@gharlan meint dazu
> vom code, so wie ich ihn da jetzt sehe, würde ich sagen: "Logisch, dass es schließt".

**Comment by tbaddade** [comment]
https://github.com/yakamara/redaxo_yform/blob/master/plugins/manager/assets/manager.js#L63

Wenn in der Zeile das `!`entfernt wird, dann scheint es in der Sliceumgebung zu passen.
Single > schließt das Popup
Multiple > Popup bleibt offen

Weiß nur nicht, ob das JS noch woanders aufgerufen wird.

**Comment by tbaddade** [comment]
Ich habe obige Zeilen in ein aktuelles Projekt eingefügt. Scheint jetzt auch in der YForm-Umgebung (Datensätze) zu passen.

**Comment by tbaddade** [comment]
Die markierten Zeile haben sich durch Commits verschoben. 

Diese wäre jetzt hier
https://github.com/yakamara/redaxo_yform/blob/master/plugins/manager/assets/manager.js#L32-L34
