### ISSUE TITLE
validate type.php / url erkennt keine .bayern (tld)

### ISSUE THREAD

**Issue by darwin26** [yakamara/redaxo_yform#413]
hi,
selten, aber wird nicht validiert: .bayern
/yform/validate/type.php (Zeile 49): case 'url'

wir haben es testweise mit dieser RegEx ausprobiert und lief damit:
`$xsRegEx_url = '/^((([A-Za-z]{3,9}:(?:\/\/)?)(?:[\-;:&=\+\$,\w]+@)?[A-Za-z0-9\.\-]+|(?:www\.|[\-;:&=\+\$,\w]+@)[A-Za-z0-9\.\-]+)((?:\/[\+~%\/\.\w\-_]*)?\??(?:[\-\+=&;%@\.\w_]*)#?(?:[\.\!\/\\\w]*))?)' . '/';
`

Gruß Christian

**Comment by alexplusde** [comment]
Sollte wenn, dann nach RFC3986-Standard validiert werden, analog zum E-Mail-Feld und HTML5-Validierung im Browser? Wobei damit auch `data://`-URIs möglich wären.
http://jmrware.com/articles/2009/uri_regexp/URI_regex.html
