### ISSUE TITLE
upload Value - Dateigröße auch ohne Range ermöglichen

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#414]
> Maximale Größe in Kb oder Range 100,500

Das suggeriert aktuell, dass man eine Zahl eintragen kann die dann die max. Größe wäre. Ist so aktuell nicht möglich, es muss zwingend ein Range (0,1000) eingetragen werden.

**A/**
Beschreibung anpassen, dass immer ein Range eingegeben werden muss

**B/**
Value so anpassen, dass bei der Eingabe einer Zahl diese als max-Wert genommen wird und der min-Wert automatisch auf 0 gesetzt wird.

Ich wäre für **B**

**Comment by dergel** [comment]
ich habe es mir nochmal angesehen.. und eigentlich funktioniert es so wie gewünscht.. Einzig die Platzhalter für die Fehlermeldungen könnten missverständlich sein. (min_error und max_error) .. Bitte prüf das nochmal nach.

**Comment by dergel** [comment]
einfach hier klicken:  https://github.com/yakamara/redaxo_yform/commit/9ae74c48bc739499d0a7d00fcf8fdb2b1cfaf274

**Comment by alexplusde** [comment]
Ah, die Reihenfolge der Fehlermeldungen war verkehrt? Da sollte man im Changelog auf jeden Fall darauf hinweisen, denn mit dem Update würden ja in bestehenden Installationen die Meldungen vertauscht.
