### ISSUE TITLE
Kritische Änderungen als Transaktionen vornehmen

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#417]
Wenn es in einem Import- oder Massenbearbeitungsprozess zu einem Fehler kommt, sind ein Teil der Datensätze aktualisiert / importiert, ein Teil jedoch nicht. Dem könnte man durch Transaktionen mit einem anschließenden Rollback Abhilfe leisten.

**Comment by alexplusde** [comment]
Sollte evtl. mit https://github.com/redaxo/redaxo/pull/1599 ja nun ganz einfach möglich sein? (Ich kenn mich nur in der Theorie halbwegs damit aus, sonst würde ich einen PR machen)

**Comment by dergel** [comment]
@gharlan Hast du ein Beispiel wie man Transaktionen bei REDAXO verwendet ?

Würde das dann als Option beim Import einbauen wollen.

**Comment by dergel** [comment]
Beim Import ist nun eine Transaktion drin.. Bei Massenedit fehlt es noch

**Comment by alexplusde** [comment]
Klasse!

**Comment by dergel** [comment]
Jetzt auch bei Massenbearbeitung und eigentlich immer bei Datensätzen Edit im Manager

**Comment by alexplusde** [comment]
Bestes Qualitätsupdate für mich. :)

Sieht man auch, welcher Datensatz im Zweifel den Import verhindert?

**Comment by dergel** [comment]
man sieht dann nur die SQL-Fehlermeldung
