### ISSUE TITLE
Attribute für Inputfelder

### ISSUE THREAD

**Issue by bega011** [yakamara/redaxo_yform#42]
Es wäre super, wenn es eine Möglichkeit gäbe, die Attribute (z.B. required, disabled, data usw.) und Klassen  mit letztem Parameter für alle Inputfelder (auch Checkboxen und Radios) zu vergeben. Zur Zeit geht das nur mit "required" und "placeholder".

**Comment by dergel** [comment]
fände ich auch gut .. noch weiss ich nicht wie man das am besten implentieren könnte, also, dass man relativ frei seine attribute wählen kann und diese auch an der richtigen stelle auftauchen. Nehme gerne Ideen entgegen ..

**Comment by bega011** [comment]
Genau, dann könnte man wirklich jedes Feld mit CSS und JavaScript manipulieren.
Das wäre (css)Klasse :)

**Comment by IngoWinter** [comment]
Naja, einfach noch ne Pipe hinzufügen und die Eingabe da ausgeben, wo jetzt schon die Attribute ausgegeben werden. Für xform mach ich das schon länger über eigene Klassen so, weil clientseitige Validierung zb über Parsley sonst übelstes Gewürge ist.

**Comment by dergel** [comment]
es geht eher um den allgemeinen ansatz für alle felder .. im Moment gibt es ja schon die "eigenen" Felder, die man, je nach Klasse setzen kann.. z.b. |#placeholder:Mein Platzhalter .. Aber z.b. schon disabled funktioniert anders, oder ich will z.B. ein Attribut im div drumherum aufnehmen. Habe noch keine richtige allgemeine Idee wie man das machen könnte.

**Comment by dergel** [comment]
https://github.com/yakamara/redaxo_yform/issues/106
