### ISSUE TITLE
Im Tablemanager wird das datestamp Feld nicht in der Übersicht angezeigt

### ISSUE THREAD

**Issue by dtpop** [yakamara/redaxo_yform#421]
Egal welche Einstellungen ich wähle, das Feld wird nicht angezeigt (2.3b6). Die Spalte wird zwar erstellt und angezeigt, bei den Einträgen wird nichts angezeigt. In der Detailansicht kann ich den Wert sehen.

**Comment by dergel** [comment]
du meinst in der listenansicht ? kannst du einen screenshot hier reinlegen ?

**Comment by alexplusde** [comment]
Als Zeitstempelformat `mysql` eingetragen?

**Comment by dergel** [comment]
kann ich leider nicht nachvollziehen
<img width="834" alt="bildschirmfoto 2018-01-24 um 16 57 59" src="https://user-images.githubusercontent.com/322951/35342208-ca47baf8-0127-11e8-8cad-cdf92d171d18.png">
<img width="348" alt="bildschirmfoto 2018-01-24 um 16 58 06" src="https://user-images.githubusercontent.com/322951/35342212-cb4b6e18-0127-11e8-9305-c5ee82c29997.png">
<img width="387" alt="bildschirmfoto 2018-01-24 um 16 58 13" src="https://user-images.githubusercontent.com/322951/35342213-cbd171ac-0127-11e8-8914-e83378e5ab02.png">


Es hat sich geändert, dass nicht der Wert angezeigt wird, der in die DB geschrieben wird, sondern nur der, der wirklich im Datensatz vorhanden ist .. D.h. beim Erstellen eines Datensatzes, taucht keine Info auf.. Was so auch richtig ist.

**Comment by alexplusde** [comment]
@dergel er meint glaube ich, in der Übersicht aller Datensätze, wenn man nur die Tabelle anklickt und nicht eins tiefer beim Erstellen / Bearbeiten.

**Comment by dergel** [comment]
ist doch mein erster screenshot.. ist eine tabelle mit nur dem datestamp feld

**Comment by alexplusde** [comment]
> ist doch mein erster screenshot.. ist eine tabelle mit nur dem datestamp feld

übersehen.

**Comment by dtpop** [comment]
Erledigt - Problem taucht nicht mehr auf in neuer Version.
