### ISSUE TITLE
Datepicker zeigt nur NaN

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#423]
Legt man ein neues Datumsfeld, bei vorhandenen Datensätzen, wie im Screenshot A an, sieht der Picker wie Screenshot B aus.

Screenshot A
![screenshot 2018-01-24 17 47 58](https://user-images.githubusercontent.com/338267/35344994-bf7a41ca-012e-11e8-9c21-4aef282d8d43.png)

Screenshot B
![screenshot 2018-01-24 17 44 55](https://user-images.githubusercontent.com/338267/35345007-c8fe9a48-012e-11e8-8225-130c65ddbc18.png)

**Comment by dergel** [comment]
da bin ich mir auch unsicher was man tun kann.. das problem ist, dass der datepicker dieses 00.00.0000 Datum bekommt und damit nicht klarkommt..

**Comment by tbaddade** [comment]
> das problem ist, dass der datepicker dieses 00.00.0000 Datum bekommt und damit nicht klarkommt

Eventuell das Datum mit dem "heutigen" dann vorbelegen?

**Comment by alexplusde** [comment]
> Eventuell das Datum mit dem "heutigen" dann vorbelegen?

Sollte es nicht auch möglich sein, kein Datum einzugeben?

**Comment by alexplusde** [comment]
@dergel der Datepicker müsste nur im Value den richtigen Wert bekommen.

![image](https://user-images.githubusercontent.com/3855487/35561651-4dd49dcc-05b1-11e8-99ba-5e41f669e509.png)

**Comment by alexplusde** [comment]
Übrigens: würde man ein "input:date"-Template zur Auswahl stellen und mit YYYY-MM-DD befüllen, dann wäre das Feld HTML5-Konform und würde nebenbei noch das Problem @tbaddade lösen. Deswegen nicht als eigenes Issue.

**Comment by eaCe** [comment]
Ich bin nun auf flatpickr umgestiegen. In meinem Fall muss ich auch einen leeren wert haben können.
Ich entferne dann einfach die value, wenn 00:00:00 00:00 ist...

**Comment by dergel** [comment]
beim datepicker geht das mit dem leeren Wert auch. Der wird nun auch geleert wenn es ein 0000-00 ... Wert hat und dann klappt auch

**Comment by DanielWeitenauer** [comment]
Das Problem scheint dadurch zu entstehen, dass beim Initialisieren kein Wert für die Option `startDate` angegeben wird. Beim anzugebenden Wert scheint es wichtig zu sein, dass Monat und Tag einen realen Wert erhalten.
