### ISSUE TITLE
Änderung eines Feldes von date auf datetime passt nicht den DB-Typen an

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#427]
bleibt auf Typ `date`. Aktuell muss man direkt in die DB rein und das anpassen.

**Comment by tbaddade** [comment]
Die Values müssten ebenfalls angepasst werden, da es sonst zu einem Fehler seitens MySQL kommt.

**Comment by alexplusde** [comment]
Ist das nicht grundsätzlich bei allen values so, bei denen man den Typ wechselt? War für mich bisher kein Bug

**Comment by tbaddade** [comment]
> War für mich bisher kein Bug

Wenn du ein Date Value hast und änderst das auf Datetime, dann wird die Uhrzeit aktuell nicht gespeichert. (Beim Testen nicht den Button "Übernehmen" verwenden, da der Wert korrekt aus dem $_POST angezeigt wird.)

**Comment by dergel** [comment]
Ich finde es auch richtig, dass das Datenbankfeld sich entsprechend der Definition des eigentlichen Feldes anpasst. Ich frage mich nur, warum wir das nicht bereits eingebaut haben. Wird aber noch gemacht.
