### ISSUE TITLE
REX_YFORM_TABLE_DATA / listwidget: PopUp schliesst sich nach Übernahme von nur einem Datensatz

### ISSUE THREAD

**Issue by olien** [yakamara/redaxo_yform#432]
`REX_YFORM_TABLE_DATA[id=1 output="listwidget" table="rex_personen" field="vorname,' => ',nachname"]`

Hier sollte das PopUp doch geöffnet bleiben und "von Hand" geschlossen werden müssen - oder?

LG
Oliver

**Comment by dergel** [comment]
in der aktuellen version sollte das eigentlich behoben sein .. die hast du genutzt, oder ?

**Comment by olien** [comment]
Die aktuelle Version aus dem Installer habe ich (2.3)

**Comment by darwin26** [comment]
kann den bug bestätigen.
weder Installer version noch gitHub version behben das Problem.
Das Pop up schließt nach einer Übernahme / klick auf "übernehmen"

**Comment by tbaddade** [comment]
Habe das Issue hier zu spät gesehen und das alte dafür wieder eröffnet. Hier geht es weiter https://github.com/yakamara/redaxo_yform/issues/410 da auch hoffentlich die Lösung jetzt mit drin ist ;)
