### ISSUE TITLE
Tablemanager: Migration schlägt fehl, wenn Länge der DB-Spalte nicht default

### ISSUE THREAD

**Issue by netzproductions** [yakamara/redaxo_yform#435]
Beim Versuch, eine Tabelle per Tablemanager zu migrieren, kam diese Fehlermeldung:
`Migration für 'rex_xyz' ist fehlgeschlagen. Fehler: Error while executing statement "SELECT * FROM 'rex_xyz' WHERE 'active' NOT IN (0, 1) LIMIT 1"! SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db12345.'rex_xyz' doesn't exist`

Es stellte sich dann heraus, daß das Feld als tinyint(1) unsigned angelegt war. Ändert man das auf tinyint(4) unsigned (Standard, wenn keine Länge eingegeben), funktioniert der Import.

**Comment by tema-web** [comment]
Kann ich bestätigen, bei mir kam auch genau diese Fehlermeldung beim Versuch, ein tinyint(1)-Feld zu migrieren (yform 3.0)

**Comment by dergel** [comment]
alles schon lange her .. sorry, dass ich erst jetzt frage.. was muss ich genau machen um den fehler zu reproduzieren ?

**Comment by tema-web** [comment]
leg im Adminer eine Tabelle an mit id, name (varchar 191), online (tinyint 1) und versuche die mal im TableManager zu migrieren. Dann bekommst du die Fehlermeldung.
`Migration für `test` ist fehlgeschlagen. Fehler: Error while executing statement "SELECT * FROM `'test'` WHERE `'online'` NOT IN (0, 1) LIMIT 1"! SQLSTATE[42S02]: Base table or view not found: 1146 Table 'masterRex.'test'' doesn't exist`
