### ISSUE TITLE
be_media Darstellung der Vorschau defekt

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#436]
![image](https://user-images.githubusercontent.com/3855487/36080125-b9c37f24-0f8b-11e8-972d-5a96d3d7e5bb.png)

Würde stattdessen empfehlen, das Element per hover absolut zu positionieren oder über ein Tooltip
https://getbootstrap.com/docs/3.3/javascript/#tooltips

**Comment by dergel** [comment]
<img width="418" alt="Bildschirmfoto 2020-05-21 um 14 28 00" src="https://user-images.githubusercontent.com/322951/82559120-55b7b780-9b6f-11ea-992d-2f7f36879810.png">

das passt bereits

**Comment by alexplusde** [comment]
Thx
