### ISSUE TITLE
select - Defaultwert wird nicht vorausgewählt

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#437]
Bei der Eingabe im Table Manager wird der Defaultwert nicht im Select-Feld vorausgewählt.

**Comment by dergel** [comment]
Leider nicht so ohne zu machen. Bei nicht multiselect Feldern geht es. Muss ich vorerst einen Milestone nach hinter verschieben

**Comment by dergel** [comment]
select ist deprecated.. bei choice auch so ? gerne dort nochmal testen und im Fall ein neues Issue aufmachen
