### ISSUE TITLE
historie mit aufnehmen

### ISSUE THREAD

**Issue by dergel** [yakamara/redaxo_yform#44]
so dass man datensaetze zurücksetzen kann oder änderungen zurückverfolgen kann, optional aktivierbar.

**Comment by skerbis** [comment]
:+1:

**Comment by dergel** [comment]
das issue haben wir schonmal :) ..Gibts noch andere die Interesse haben ? ..

**Comment by skerbis** [comment]
Das sollte man in Forum posten

**Comment by dergel** [comment]
* History aktivierbar (checkbox) über die Tabelleneinstellung
* In Datenansicht (editieren) ein Historylink mit Fenster ala "history"-Plugin.

Frage ist noch .. eine 2. History-Tabelle pro einzelne Tabelle - oder eine Tabelle in der alle Veränderungen von verschiedenen Tabellen gespeichert wird - z.B. über json

**Comment by tbaddade** [comment]
Wäre es nicht hübsch ein History AddOn zu entwickeln, wo sich dann structure, yform und andere Addons einklinken können?

**Comment by staabm** [comment]
> Wäre es nicht hübsch ein History AddOn zu entwickeln, wo sich dann structure, yform und andere Addons einklinken können?

Ich glaube dass das "history" problem und dessen "lösung" von den daten abhängig ist, die man historisieren will/muss. 

Ausserdem denke ich dass ein user eine history ggf. nur in manchen teilen will/brauch und nicht in allen oben genannten.

Ausserdem kann es je addon unterschiedlich sein was man mit den history daten macht (wiederherstellbarkeit notwendig? Nur protokollierung? Ggf. Protokollierung aller aber nur sichtbar für admins,...)

Daher sehe ich es eher in jedem addon statt in einem separaten.

**Comment by staabm** [comment]
> Frage ist noch .. eine 2. History-Tabelle pro einzelne Tabelle - oder eine Tabelle in der alle Veränderungen von verschiedenen Tabellen gespeichert wird - z.B. über json

Ich halte von blobs/json in so einem use-case für wenig geeignet, da man keinen zugriff mehr auf die einzelnen felder hat, welche sich von A nach B zum zeitpunkt X geändert haben.

Ob man eine historien tabelle pro yform tabelle oder eine historien tabelle für alle macht hängt auch wieder ein wenig mit den use-cases zusammen. Wenn möglich würde ich versuchen mit einer/ein paar wenigen tabellen die historie aller yform tabellen zu realisieren.
Ist denke ich bequemer wenn man yform tabellen übergreifend logiken bauen will oder analysen durchführen muss.

**Comment by gharlan** [comment]
Hmm, das verstehe ich dann aber noch nicht. Einerseits keine Blobs/json, andererseits aber auch nicht pro Tabelle, wo es eine Historie geben soll, eine History-Table. 
Wie würdest du denn dann die Werte ablegen?

**Comment by staabm** [comment]
Man kann z.b. Eine tabelle so aufspannen dass sie pro zeile nur ein property eines objektes repräsentiert.

D.h. Eine Änderung an einem objekt wird repräsentiert durch mehrere datensätze

**Comment by gharlan** [comment]
Stimmt, die Variante hatte ich gar nicht bedacht. Das wäre quasi deine bevorzugte Variante?

Hatte mit Jan auch über Thomas Idee geredet. Würden es aber nicht so allgemein angehen, sondern schon in yform. Man soll dann pro Tabelle auswählen können, ob es eine Historie geben soll, oder nicht.

**Comment by staabm** [comment]
> Stimmt, die Variante hatte ich gar nicht bedacht. Das wäre quasi deine bevorzugte Variannte

Ja, insofern es mit den use-cases passt

**Comment by gharlan** [comment]
Und wie würdest du da mit den unterschiedlichen Feldtypen umgehen? Die Spalte, in denen die Werte landen, müsste dann ja vermutlich `longtext` oder so sein, um alles abzudecken? Da dann einfach reinschmeißen, egal was für ein Typ die Ursprungsspalte hat, oder wie?

**Comment by staabm** [comment]
Was ist die max. Größe die man einem feld via yform zuordnen kann?

**Comment by gharlan** [comment]
> Was ist die max. Größe die man einem feld via yform zuordnen kann?

yform selbst legt maximal `TEXT` an, wenn ich es gerade richtig weiß.
Allerdings kann man die Spalte ja auch nachträglich vergrößern, oder vorhandene Spalten mit anderen Feldtypen nachträglich als yform-Feld hinzufügen.

Jedenfalls siehst du kein Problem darin, alle möglichen Feldtypen (int, float, decimal, date etc.) in einem Textfeld abzulegen? Mir fällt jetzt auch nicht wirklich was problematisches dabei ein, aber bin mir auch nicht so sicher.

**Comment by staabm** [comment]
> Jedenfalls siehst du kein Problem darin, alle möglichen Feldtypen (int, float, decimal, date etc.) in einem Textfeld abzulegen? Mir fällt jetzt auch nicht wirklich was problematisches dabei ein, aber bin mir auch nicht so sicher.

wenn die daten rein informativ sind und man nicht ein "wiederherstellen" eines alten zustandes unterstützten muss, sehe ich kein problem der einfachheit halber immer mit TEXT zu arbeiten.

**Comment by gharlan** [comment]
Doch, Wiederherstellen soll es schon geben (vielleicht nicht sofort).
Aber auch das müsste ja eigentlich funktionieren. Zumindest bei int, decimal und datetime-Feldern sehe ich kein Problem. Höchstens vielleicht bei float irgendwelche Rundungsprobleme.

**Comment by staabm** [comment]
> Höchstens vielleicht bei float irgendwelche Rundungsprobleme.

exakt.

**Comment by dergel** [comment]
Die Zurücksetzenfunktion über eine Importmethode laufen lassen wäre super.. Dann können wir sicher sein, dass die Tabelle immer konsistent ist.

**Comment by gharlan** [comment]
Was hier jetzt eventuell noch fehlt:

- Versionen anzeigen (zurzeit sieht man nur die ID und die Aktion (erstellt, bearbeiten, gelöscht), kann aber noch gar nicht die alten Felddaten sehen
- Einzelhistorie pro Datensatz (zurzeit gibt es nur die Historie pro Tabelle) ?
- Versionen vergleichen ?
- Automatisches Aufräumen um zu viele Versionen zu vermeiden ?

**Comment by dergel** [comment]
habe für den letzten Punkt ein neues Issue gemacht. Historie ist ja soweit erstmal gut
