### ISSUE TITLE
yform-formular-body_html für WYSIWYG Editoren vorbereiten

### ISSUE THREAD

**Issue by cukabeka** [yakamara/redaxo_yform#440]
Habe schon einmal in XFORM den Code hart aufgebohrt und eine redactor-kompatible Klasse ans Tag drangehängt. Mit einem Update war dann alles dahin.

Möchte das HTML in Email-Formularen gerne auch komfortabel editieren können. Toll wäre, wenn der Code so gestaltet ist, dass ich einfach ein Addon wie Redactor darauf anspitzen kann. Leider akzeptiert dieses wiederum nur Klassen. Schön fände ich, wenn yform-formular-body_html also nicht nur die ID ist, sondern es für dieses Feld auch eine eindeutige Klasse gäbe.

**Comment by alexplusde** [comment]
Das ergibt wenig Sinn, wenn man bedenkt, dass man PHP-Code ausführen kann und HTML in E-Mails schwer für alle Clients kompatibel zu halten ist, ohne eine Menge zu beachten:

https://www.campaignmonitor.com/css/ (das "caniuse.com" für E-Mail-CSS)

**Comment by alexplusde** [comment]
Alternativ kannst du bspw. ein Slice oder ein Textfeld in den globalen Einstellungen verwenden, das du dann via PHP im E-Mail-Template referenzierst. Ich würde dir aber empfehlen, drunter und drüber einen DOCTYPE, das `html` und `body`-Element zu setzen, um standardkonformes HTML zu versenden.

**Comment by cukabeka** [comment]
Puh, das sieht mir alles nach üblem Hack aus. Natürlich gibt es auch Fälle, in denen ich PHP benötige, aber das Standard-Szenario ist doch, dass ich eine simple Mail verschicken möchte. Um diese irgendwie sinnvoll zu administrieren, halte ich einen WYSIWYG-Editor für ein Muss im produktiven Einsatz von Redaxo. 
Die Sorge, dass Clients die Mail nicht richtig rendern, teile ich nicht: Wenn ich nur die Basic Funktionen des Editors benutze, ohne ein spezielles Layout zu benötigen, kommen Mails mit Überschriften, Links und Text-Formatierungen sauber an.

Das Einzige, was ich mir alternativ vorstellen könnte, wäre die Möglichkeit, einen Artikel aus der Struktur zu verschicken, dort könnte ich dann Template und Inhalt komfortabel und sauber verwalten.

**Comment by skerbis** [comment]
Nun, das Template in yForm ist als Quellcode-Eingabe zu verstehen. Vor allem weil man da PHP und die Platzhalter einsetzen kann werden die Templates dynamisch. Man kann auf die Eingaben / Values  reagieren, was bei reinem HTML nicht möglich ist.

**Comment by alexplusde** [comment]
> aber das Standard-Szenario ist doch, dass ich eine simple Mail verschicken möchte.

Nicht bei uns.

**Comment by cukabeka** [comment]
Bei uns schon. :P

Wenn ich mir die YForm/Ycom-Demos anschaue, ist das auch der Standard: Es werden Mails verschickt, in denen die Variablen aus den Forms eingesetzt werden. Dass auch PHP-Quellcode möglich ist, ist wunderbar, allerdings sehe ich nicht, dass es das Hauptszenario für den Einsatz wäre, sondern etwa genauso häufig wie das reine Verschicken von Texten. 
Insofern: Das Ziel ist ja, Redaxo möglichst einfach und flexibel zu machen. WYSIWYG in YForm trägt dazu bei.

@skerbis: Ich meinte tatsächlich die "richtigen" Redaxo-Templates für die Verwendung in Artikeln. Wenn es eine Möglichkeit gäbe, auch E-Mails redaktionell sinnvoll zu editieren, wäre das ein großer Fortschritt. 
Ich dachte an eine Lösung wie zB im MultiNewsletter oder yNewsletter: Dort kann ich einen Artikel definieren, der dann verschickt wird. In YForm würden dann die Variablen OPF-mäßig eingesetzt werden.

Oder halt: Eine Option, um das HTML-Textarea mit einem WYSIWYG-Editor adressierbar zu machen ;)

**Comment by tbaddade** [comment]
Wenn ich es richtig verstehe, geht es um das Textarea `Html (Body)` unter "YForm > E-Mail Templates"

Da kann man HTML notieren muss man aber nicht. Es ist eher anzusehen wie die normalen Textareas der Templates/Modulen, wo man Code eingibt. Deshalb ist es auch für `codemirror` vorbereitet [1]. Einen wysiwyg Editor sehe ich an der Stelle nicht.

Wenn du an der Stelle tatsächlich einen Editor brauchst, dann kannst du die "redactor"-Class über den `OUTPUT_FILTER` einschleusen.

[1] https://github.com/yakamara/redaxo_yform/blob/master/plugins/email/pages/index.php#L43

**Comment by cukabeka** [comment]
Aha OK, das sieht beides interessant aus. 
1. Wie geht das mit dem Einschleusen? OPF und dann Suchen nach "yform_email_body_html"? Dann bekomme ich aber nur die ID abgefangen, oder?
2. Und wie wäre das mit dem Einbinden des Artikels grob zu lösen? Irgendwie so in der Richtung **REX_ARTICLE[45]** - Dann ist doch das HTML-Template des Artikels nicht dabei.. Hm.

Ich sehe es eben nicht als reine Code-Eingabestelle, sondern ich brauche einen Ort, wo ich Mail-Templates redaktionell verwalten kann, inklusive Formatierungen. Ich kann ja dem Redakteur schlecht sagen: "Lernen Sie etwas HTML und machen Sie Ihre 15 Standard-Mails fürs System dann selbst hardcoded + Plaintext. Wie sie sehen, ist Redaxo einfach, flexibel und sinnvoll!" ;)

**Comment by skerbis** [comment]
zu 2. Du kannst Templates auch in Modulen nutzen :-)

**Comment by cukabeka** [comment]
Hm, aber mit einem reinen REX_TEMPLATE[5] kann ich ja nicht direkt auch den Artikel einbinden. Ich bräuchte quasi sowas wie
***REX_TEMPLATE[5,REX_ARTICLE[45],array(email=>"///email//")]*** o.ä. 🤔 
Das scheint mir nicht wirklich zu funktionieren, um die Stärken von YForm auszuspielen, oder?

**Comment by cukabeka** [comment]
Also, probiere den Ansatz 1) gerade aus. Selbst das ist nicht machbar mit dem aktuellen YForm Markup:

`
<div class="form-group" id="yform-formular-body_html">
<label class="control-label" for="yform-formular-field-6">Body (Html)</label>
<textarea class="form-control codemirror" name="FORM[formular][6]" id="yform-formular-field-6" rows="10"></textarea>

`

Das Einzige, was eindeutig ist, ist die ID **yform-formular-body_html** - mit **form-control codemirror** erwische ich auch das Plaintext-Feld. Da komme ich auch mit OPF nicht weit.

Was spricht denn dagegen, wenigstens in die Klasse auch "yform-formular-body_html" reinzuschreiben? Oder meinetwegen in die ID?
`
<textarea class="form-control codemirror yform-formular-body_html" name="FORM[formular][6]" id="yform-formular-field-6" rows="10"></textarea>
`
Das ließe sich wenigstens mit OPF "anfassen".

**Comment by skerbis** [comment]
Hier eine Lösung: 

1) Importiere im TableManager. die Tabelle  rex_yform_email_template und definiere diese wie du sie brauchst. 
2) Stelle dem Kunden die Tabelle zur Verfügung

Fertig

**Comment by tbaddade** [comment]
Dann kann das Issue geschlossen werden?
