### ISSUE TITLE
Feldtyp DATE: Widget input:date implementieren?

### ISSUE THREAD

**Issue by christophboecker** [yakamara/redaxo_yform#441]
Ok, etwas kryptische Überschrift. Ich wollte ausprobieren, ob wie sich der eingebaute Date-Picker des HTML5-Input in einem YFORM-Formular verhält. Funktioniniert nur halb, aber woran liegt es?

DB: 
Feld "start_date" vom Typ "date"

Feldinhalt: 
2018-10-03

YFORM: 
Formular im Backend. Dem Tabellenfeld "start_date" ist ein YForm-Feldtyp "date" zugewiesen. 
Widget: input:text
Individuelle Attribute: {"type":"date"}

Test 1:
Aufruf des Formulars für den fraglichen Datensatz mit vorhandemem Feldwert.
Anzeige im Eingabefeld: "TT. MM. JJJ" statt des Datums
Speichern: in der Tabelle ist  "start_date" ist auf 000-00-00  geändert.

Test 2:
Aufruf des Formulars für den fraglichen Datensatz mit vorhandemem Feldwert.
Anzeige im Eingabefeld: "TT. MM. JJJ" statt des Datums
Ändern des Feldes per Datumseingabe bzw. Picker klappt gut. Gebe wieder 3.11.2018 ein.
Speichern: in der Tabelle ist  "start_date" ist auf 2018-11-03  geändert.

Der generierte HTML-Code sieht so aus:
```
<input class="form-control" name="FORM[data_edit-rex_kv30_event][5]" id="yform-data_edit-rex_kv30_event-field-5" value="2018/10/03" type="date">
```
Das Eingabefeld ist im `VALUE_DATE_DEFAULT` formatiert. 
Darauf ausprobiert: Format in der Feld-Konfiguration auf `YYY-MM-DD`geändert. Und siehe da. es funktioniert.

Im Grunde ist der Code ja schon für input:date vorbereitet, nur auskommentiert - und so ganu funktioniert es auch so nicht.

Soll ist das mal ändern und den Widget-Typ "input:date" ans Fliegen bringen? Dann wüde ich in den nächsten Tagen einen PR einstellen.

Grüße
Chris

**Comment by alexplusde** [comment]
Workaround: normales Inputfeld nehmen, date-Attribut mitgeben.

**Comment by christophboecker** [comment]
Alex, das war jetzt aber 'nen Schnellschuss von Dir <grins> 

Genau den Workaround habe ich ja ausprobiert und schlage jetzt vor, statt Workaround ne feste Lösung zu erzeugen. 

Grüße
Chris

**Comment by alexplusde** [comment]
Nicht ganz. Ich meinte nicht input:text sondern ein reguläres YForm-Textfeld. Dann hat man das Problem nicht, dass der Wert aus der Datenbank und das Schema für das Feld evtl. nicht zusammenpasst.

Ich bin da eher bestrebt, die Anzahl der verschiedenen Feldtypen zu reduzieren. Braucht ja bspw. auch kein type="email" usw.

**Comment by christophboecker** [comment]
Ok, viele Wege führen nach Rom. Ichschlage keinen zusätzlichen Datentyp vor. Da solle man in der Tag sparsam sein. Ich schlage vor den Datentyp DATE minimal zu erweitern:



Grüße
Chris
