### ISSUE TITLE
Uneinheitliche Nutzung von class="yform-element" Absicht oder Fehler? 

### ISSUE THREAD

**Issue by christophboecker** [yakamara/redaxo_yform#443]
Hallöle

ich bin auf was gestoßen bei dem Versuch, mir die YForm-Formulare im Backend etwas umzugestalten. Die einzelnen Felder haben pi mal Daumen so einen HTML-Code:

```
<div class="form-group yform-element" id="xxx">
    <label class="control-label" for="yyy">lorem ipsum</label>
    <input class="form-control" name="zzz" id="yyy" value="" type="text">
</div>
```
Also die Idee, über `.yform-element` in der eigenen CSS das Layout von label und input etwas anders zu verteilen. Aber seltsam: es traf längst nicht alle Felder. 

Eine kleine Inventur der value.feldtyp.tpl.php im Bootstrap-Verzeichnis ergab:

*mit yform-element*
* article
* checkbox
* checkbox_group
* datetime
* mediafile
* showvalue
* text
* (osm_geocode im Addon yform_geo_osm)

*ohne yform-element*
* select
* radio
* google_geocode
* captcha
* textarea

Is it a bug, is it a feature?

Aus meiner Froschperspektive kann ich nicht beurteilen, ob es nicht sogar ausgesprochen wichtig und sinnvoll ist, bei den genannten Elementen auf die Klasse yform-element zu verzichten. Ich würde natürlich eine einheitliche Ausstattung sehr begrüßen, also entweder für alle oder raus oder für alle rein. Ich bevorzuge: rein.

Ich kann gerne unterstützen und einen PR aufzumachen, der entweder die Klasse für alle Felder einfügt. Aber nur wenn auch gewünscht, nicht einfach so.  Sollte ein Feld in der Ohne-Liste fehlen, bitte sagen.

Grüße
Chris

(Ja, man kann den "Bug" auch über händisch eingefügte Attribute mitigieren - es bleibt aber ein Workaround und keine solide Lösung für den "Bug")

**Comment by dergel** [comment]
Auf jeden Fall sollte das einheitlicher sein.. Und gerne nehmen wir PRs entgegen.. Also - hau rein :) ..

**Comment by dergel** [comment]
ist das mit dem dem aktuellen PR behoben  und können wir das issue schliessen ?

**Comment by christophboecker** [comment]
"Aktueller PR" ist gut! Das war im März. Für mich ist das Thema durch. Ich hab aber auch nicht nachgeprüft, ob zwischenzeitlich erneut Felder ohne `.yform-element` aufgetaucht sind.

**Comment by christophboecker** [comment]
OK, hier die Auswertung:

linke Spalte: die im jeweiligen Verzeichnis gefundenen Klassen-Dateien "value.xyz.tpl.php", rechte Spalte die mit Klasse `yform-element`. In der linken Spalte fett/italic markiert die Elemente aus `...../bootstrap`, die keine Entsprechung in `...../classic` haben.


gesamt | mit yform-element
-- | --
  |  
`ytemplates/bootstrap` |  
  |  
value.article.tpl.php | value.article.tpl.php
value.captcha.tpl.php |  
value.checkbox_group.tpl.php | value.checkbox_group.tpl.php
value.checkbox.tpl.php | value.checkbox.tpl.php
**_value.choice.check.tpl.php_** |  
**_value.choice.select.tpl.php_** |  
value.datetime.tpl.php | value.datetime.tpl.php
value.fieldset.tpl.php |  
**_value.google_geocode.tpl.php_** | value.google_geocode.tpl.php
value.hidden.tpl.php |  
value.mediafile.tpl.php | value.mediafile.tpl.php
value.radio.tpl.php | value.radio.tpl.php
value.recaptcha.tpl.php |  
value.resetbutton.tpl.php |  
value.select.tpl.php |  
value.showvalue.tpl.php | value.select.tpl.php
value.submit.tpl.php | value.showvalue.tpl.php
value.text.tpl.php | value.text.tpl.php
value.textarea.tpl.php | value.textarea.tpl.php
value.upload.tpl.php | value.upload.tpl.php
  |  
  |  
`ytemplates/classic` |  
  |  
value.article.tpl.php |  
value.captcha.tpl.php |  
value.checkbox_group.tpl.php |  
value.checkbox.tpl.php |  
value.datetime.tpl.php |  
value.fieldset.tpl.php |  
value.hidden.tpl.php |  
value.mediafile.tpl.php |  
value.radio.tpl.php |  
value.recaptcha.tpl.php |  
value.resetbutton.tpl.php |  
value.select.tpl.php |  
value.showvalue.tpl.php |  
value.submit.tpl.php |  
value.text.tpl.php |  
value.textarea.tpl.php |  
value.upload.tpl.php |  
  |  
  |  
`plugins/manager/ytemplates/bootstrap` |  
  |  
value.be_link.tpl.php | value.be_link.tpl.php
**_value.be_manager_inline_relation_form.tpl.php_** |  
**_value.be_manager_inline_relation.tpl.php_** | value.be_manager_inline_relation.tpl.php
value.be_manager_relation.tpl.php | value.be_manager_relation.tpl.php
**_value.be_media.tpl.php_** | value.be_media.tpl.php
value.be_table.tpl.php | value.be_table.tpl.php
  |  
  |  
`plugins/manager/ytemplates/classic` |  
  |  
value.be_link.tpl.php | value.be_link.tpl.php
value.be_manager_relation.tpl.php | value.be_manager_relation.tpl.php
value.be_table.tpl.php | value.be_table.tpl.php

**Comment by dergel** [comment]
kannst du einen PR mit den Änderungen machen ?

**Comment by tbaddade** [comment]
> kannst du einen PR mit den Änderungen machen ?

du meinst, dass überall das `yform-element` entfernt wird?
