### ISSUE TITLE
Tabellenübersicht - Link "Definitionen löschen" - Löscht die Tabelle und nicht die Felddefinitionen

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#449]
https://github.com/yakamara/redaxo_yform/blob/master/plugins/manager/pages/table_edit.php#L193

**Comment by dergel** [comment]
?? .. regelmäßig benutzt.. bei mir werden nur die Definitionen gelöscht.

**Comment by tbaddade** [comment]
Als Hinweis kommt

> Tabellendefinitionen wurden gelöscht [Tabelle wurde nicht gelöscht]

Die Tabelle taucht in der Übersicht nicht mehr auf. Felddefinitionen scheinen gelöscht zu sein.
Kann auch sein, dass ich das Wort "Definitionen" anders interpretiere. Meinst du damit die Daten die  in `rex_yform_table` und `rex_yform_field` gespeichert sind?

**Comment by dergel** [comment]
Genau.. diese Daten werden dann gelöscht. Also nur die YForm Festlegungen die für die Eigaben zuständig sind. Was erwartest du ? Anderen Textvorschlag ?

**Comment by tbaddade** [comment]
In der Umgebung wird immer von Tabellen geschrieben. (Tabellen bearbeiten, Tabellenübersicht, Tabelle editieren). Wie wäre es mit dieser Variante?

![screenshot 2018-09-04 13 29 03](https://user-images.githubusercontent.com/338267/45028788-ace9c180-b046-11e8-8ea3-b0f9e8936e90.png)

**Comment by alexplusde** [comment]
Was ist eine Datentabelle? Noch nie gehört.

**Comment by dergel** [comment]
Die Frage ist wie man diese beiden Dinge bezeichnet, damit klar ist worum es geht.

1. Die eigentliche Tabelle innerhalb der Datenbank, mit Daten und Struktur. (Datentabelle)
2. Die YForm Definitionen, in denen festgelegt wird, wie diese Tabelle verwaltet wird. (YForm Definitionen)

Ideen ?
