### ISSUE TITLE
Check für MEDIA_IS_IN_USE / ARTICLE_IS_IN_USE

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#450]
Prüft ob Artikel oder Medien mit den REX_WIDGETs verknüpft wurden.
https://github.com/yakamara/yakme/blob/master/lib/Yakme/Extension/YForm.php

Die Checks bringen 2 Extension Points mit, so dass man selber Tabellenfelder prüfen kann.
Mehr Infos dazu unter
https://github.com/yakamara/yakme/blob/master/README.md#yform

**Comment by alexplusde** [comment]
> https://github.com/yakamara/yakme/blob/master/lib/Yakme/Extension/YForm.php 

Kann man diese Erweiterung problemlos in YForm oder ins Project Addon übernehmen? Braucht es dafür nur einen PR hier?

**Comment by tbaddade** [comment]
Diese zwei Zeilen gehören noch in die boot.php

https://github.com/yakamara/yakme/blob/master/boot.php#L47-L48

Ich habe das nur im Yakme-AddOn, da es Code ist, der über mehrere Instanzen mitgenommen wird.

**Comment by alexplusde** [comment]
@brandes-webdesign kannst du einen PR im plugin Table Manager dafür machen?

**Comment by dergel** [comment]
ist nun übernommen
