### ISSUE TITLE
mass_edit auch für Felddefinitionen

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#451]
**Use case**

Einige Felder sollen 
- aus der Suche verschwinden
- in der Liste versteckt werden
- etc.

**Comment by dergel** [comment]
Sehe ich hier nicht. Dazu müsste eine Suche rein und die Fälle sind, meines Erachtens, zu speziell und selten. Wenn Bedarf ist, dann leider über SQL und Cache löschen.
