### ISSUE TITLE
Captcha wird nicht angezeigt, wenn ich die Formular-Ausgabe mit einer IF-Abfrage steuere

### ISSUE THREAD

**Issue by brandes-webdesign** [yakamara/redaxo_yform#453]
Hallo,
ich hab ein ganz seltsames Problem mit yForm und dem Captcha.
Sobald ich einen Übergabeparamert aus der URL berücksichtige wird das Captcha nicht mehr angezeigt.

(Alles neues Versionen vom System und den Addons).

Es geht um eine Reise-Webseite, wo in in der URL die Reise-ID mitgeben und im Formular dann Daten davon mit ausgebe.

Beispiel-Url: www.domain.de/online-reservieren.html?reise_id=3

Der Code sieht so aus:

`<?php 
$reise_id = rex_request('reise_id', 'int');

if( $reise_id > 0 )
{
	... Hole alle Daten aus der Datenbank und zeige das Formular an ...
}
else
{
	... Fehlermeldung ...
}
?>`

Dank Thomas Blum bin ich auf diese "Notlösung" gekommen.

'<?php 
$reise_id = rex_request('reise_id', 'int');
$captcha_calc = rex_request('captcha_calc', 'string');

if( $reise_id > 0 || $captcha_calc=='show' )
{
	... Hole alle Daten aus der Datenbank und zeige das Formular an ...
}
else
{
	... Fehlermeldung ...
}
?>'

Damit klappt es nun, aber früher war das nicht notwendig.

Ist da in irgendeinem Update ein "Fehler" reingekommen, der die Darstellung des Captcha unterbindet ?

Bei Fragen / Unklarheiten mich gerne anschreiben.

**Comment by alexplusde** [comment]
Probleme mit Formularen gabs zuletzt hin und wieder durch den CSRF-Token. Den mal versuchen, im Formular abzuschalten.

**Comment by alexplusde** [comment]
Konnte dein Problem gelöst werden?

**Comment by dergel** [comment]
Die Captchas müssen immer zum Formular selber durchgeschleift werden. Da da Formular nicht wissen kann wie es aufgerufen worden ist, muss in diesen "Spezialfällen" durchgeschleift werden, z.B. so wie du es gemacht hast ..

captcha|Beschreibungstext|Fehlertext|[link]

Sofern es ein fester Link ist, kann man diesen auch Manuell eintrage, siehe Captchabeschreibung
