### ISSUE TITLE
BUG: "Spezielle Attribute" killen bestimmte Eingaben mit "# :"-Syntax

### ISSUE THREAD

**Issue by bitshiftersgmbh** [yakamara/redaxo_yform#456]
Bezogen auf
https://github.com/yakamara/redaxo_xform/commit/b74343386d1c03f07ec58701408e37f1dbabe36b

analysiert zusammen mit @gharlan 

zeigte sich, dass auch bei Eingabe übers Backend der o.g. Code greift. Will man z.B. einen CSS-Selektor als Value in ein Text-Feld eingeben mit ID-Referenz (#) und Pseudo-Selektoren danach (:) greift o.g. Code und zerlegt ungewollt die Struktur des betroffenen Eingabefeldes/Elements. Alle nachfolgenden Elemente sind dadurch auch betroffen, da zwar die Values stimmen, aber die Keys dann um 1 verrutschen.

Idee von @gharlan : Drin lassen, aber nur für Pipe-Notation.

**Comment by tbaddade** [comment]
Wäre eher dafür dann das Zeichen "#" anzupassen.

**Comment by alexplusde** [comment]
Wenn Redaxo volles utf8 unterstützen würde, könnte man auch ein 🧙 als Zeichen benutzen. Ich bin dafür, dass das utf8 Issue angegangen wird ;)

**Comment by alexplusde** [comment]
@dergel das letzte Issue für diesen Monat von mir, versprochen ;)

@tbaddade was würdest du vorschlagen:

* ein bestimmtes utf8-Zeichen, z.B. 🔑
* `##`
* `###`
* `~`
* `\`
* Einklammern `{key}`

und als 2. Trennzeichen dann 

* `:` den Doppelpunkt behalten oder
* `::`
* dieselben Zeichen wie oben?
* Kein Trennzeichen?

Ich würde dann einen PR für die 4.0 beisteuern - rückwärtskompatibel ist das ja mit Sicherheit nicht.

**Comment by tbaddade** [comment]
Ich vermute mal, man müsste die `#` dann escapen, also `\#` notieren. Ist halt wie das Komma ein Sonderzeichen in YForm. Knallt halt eben.

**Comment by dergel** [comment]
puhh .. das ist die xform. würde das jetzt einfach mal schliessen, da man ja auch php varianten verwenden kann.
