### ISSUE TITLE
E-Mail Template Anhang

### ISSUE THREAD

**Issue by clicksports** [yakamara/redaxo_yform#458]
Hallo,

ich hab festgestellt, dass wenn ich die Klasse "rex_yform_email_template" verwende und über diese Klasse E-Mails versende dass die Anhänge, die ich vorher in dem Template definiert habe nicht mit angehangen werden.

Die Attachments werden nämlich als String angehangen und nicht wie erwartet als Array. Dies sieht dann wie folgt aus: ["attachments"]=> (33) "sftbr-04.pdf,placeholder-blue.jpg". Um hierfür ein Workaround zu schaffen hab ich folgende Funktion geschrieben. Wäre super, wenn Ihr das im nächsten Update mit rein nehmen könnt!

`private function attachmentToPath($template)
{
if (isset($template['attachments']) && !is_array($template['attachments'])) {
    $media_path = rex_path::base().'media/';
    $arr = explode(',', $template['attachments']);
    foreach ($arr as $index => $item) {
        $rtn[$index]['path'] = $media_path.$item;
        $rtn[$index]['name'] = $item;
    }
    
    $template['attachments'] = $rtn;
}
return $template;
}
`

**Comment by clicksports** [comment]
`    
    private function attachmentToPath($template)
    {
        if (isset($template['attachments']) && !is_array($template['attachments'])) {
            $media_path = rex_path::base().'media/';
            $arr = explode(',', $template['attachments']);
            foreach ($arr as $index => $item) {
                $rtn[$index]['path'] = $media_path.$item;
                $rtn[$index]['name'] = $item;
            }
            $template['attachments'] = $rtn;
        }

        return $template;
    }
`

**Comment by tbaddade** [comment]
Könntest du dafür einen PR erstellen @clicksports ?

**Comment by clicksports** [comment]
@tbaddade leider kann ich keinen erstellen...
aber hier wäre das Projekt..
 
[redaxo_yform.zip](https://github.com/yakamara/redaxo_yform/files/1920255/redaxo_yform.zip)

**Comment by dergel** [comment]
kannst du dir den Fall nochmal ansehen .. hat sich mittlerweile bei v3 vielleicht entsprechend was geändert ? bei v2 werden ich dahingehend nichts mehr ändern

**Comment by dergel** [comment]
freue mich wenn es nochmal überprüft wird. ich räume gerade mit den issues auf .. wenn noch was sein sollte .. einfach wieder öffnen
