### ISSUE TITLE
geo plugin: "Übernehmen" klappt nicht

### ISSUE THREAD

**Issue by phoebusryan** [yakamara/redaxo_yform#46]
Ich habe gerade für Thomas Skerbis die Anbindung des Redactors im Tabellenmanager debugged und festgestellt, dass wenn man beim Bearbeiten eines Datensatzes auf "übernehmen" klickt die Karte nicht mehr funktioniert:

> Uncaught ReferenceError: google is not defined

Dies liegt daran, dass die Google Maps (http://maps.google.com/maps/api/js?sensor=true) in dem Case nicht eingebunden wird. Übrigens wird der Parameter "sensor" nicht mehr benötigt.

**Comment by dergel** [comment]
sollte mit der aktuellen version nicht mehr so sein, da pjax (welches für das ajax laden aktiviert war) deaktiviert ist, so dass die google bibliothek geladen wird. kannst du schauen ob du die aktuellste version am laufen hast, oder mal den aktuellen stand hier von github nehmen ?

**Comment by phoebusryan** [comment]
@skerbis Das geht an dich.

**Comment by skerbis** [comment]
Nein, ich habe die aktuelle Version installiert. Bei "übernehmen" verschwindet die Google Map und auch  redactor

**Comment by phoebusryan** [comment]
Das mit dem Redactor hängt von Google Maps ab.. Gmap schmeisst ein Error und redactor wird deshalb nicht ausgeführt.

**Comment by skerbis** [comment]
jupp! Nach "übernehmen" ist die Maps API nicht mehr eingebunden

**Comment by dergel** [comment]
hier gehts weiter:

https://github.com/yakamara/redaxo_yform/issues/46

**Comment by phoebusryan** [comment]
Eine Selbstreferenz, Jan ? :-D

**Comment by dergel** [comment]
https://github.com/yakamara/redaxo_yform/issues/91

hehe.. das war anders geplant ;) ..
