### ISSUE TITLE
REX_YFORM_DATA :: output Arg

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#460]
siehe https://github.com/yakamara/redaxo_yform/blob/master/plugins/email/lib/var_yform_data.php#L26-L28

Das `elseif` wird nie greifen.

**Comment by dergel** [comment]
war fehlerhaft. in email heisst html natürlich html code und muss daher escaped und nl2br werden. standardausgabe ist nun `plain`. gerne prüfen.
