### ISSUE TITLE
yform_validate_timer() erhält eine leere microtime übergeben

### ISSUE THREAD

**Issue by TobiasKrais** [yakamara/redaxo_yform#462]
Redaxo 5.5.1
YForm 2.3
PHP 7.1

Ich möchte den Spamschutz via Zeitstempel nutzen und zwar so, wie es in der Doku beschrieben ist. Hier der Code von mir: https://github.com/TobiasKrais/d2u_helper/blob/master/modules/11/1/output.php
Mein Problem: die Funktion  yform_validate_timer() erhält keine microtime übergeben.

**Comment by alexplusde** [comment]
Soweit ich mich erinnere, hatten mehrere bereits den Fehler und es handelt sich hierbei um einen Fehler in der Doku. Vielleicht kannst du im Slack-Channel mal fragen, wer den Fehler noch hatte, ich kann mich heute nicht darum kümmern.

**Comment by alexplusde** [comment]
> Wenn es ein Fehler in der Doku ist, dann war es Zeit, dass hier mal ein Issue erstellt wurde. So ist auch die Öffentlichkeit informiert.

Man kann viel darüber diskutieren, oder einen Fix liefern. Dieses Beispiel stammt von mir und ist in meiner Freizeit entstanden. Ich bitte um Verständnis, mich nicht um jede Kleinigkeit sofort selbst kümmern zu können. Das ist eine Community mit Nehmen UND Geben.

**Comment by TobiasKrais** [comment]
Ganz deiner Meinung. Wenn ich die Lösung finde bekommst du einen Pull Request von mir.

**Comment by IngoWinter** [comment]
```
    $yform->setValidateField('customfunction', [
        'validate_timer',
        'iw_yforms::yform_validate_timer',
        '5',
        'Spamschutz: Sie haben das Kontaktformular in unter 5 Sekunden abgeschickt - bitte lassen Sie sich etwas mehr Zeit'
    ]);
```
```
    public static function yform_validate_timer($label, $microtime, $seconds)
    {
        if (($microtime + $seconds) > microtime(true))
        {
            return true;
        }
        else
        {
            return false;
        }
    }
```
So läuft das bei mir...

**Comment by alexplusde** [comment]
@ingowinter, kannst du das auch in der Doku kurz fixen?

**Comment by IngoWinter** [comment]
Hab vor längerer Zeit schon einen PR dazu gemacht.

**Comment by alexplusde** [comment]
Stimmt, jetzt, wo du es sagst...

@dergel kannst du einen neuen Release machen mit aktualisierter Doku?

**Comment by dergel** [comment]
ist beim nächsten Release dran. Aktuellen Stand habe ich gerade aufgenommen

**Comment by alexplusde** [comment]
Danke
