### ISSUE TITLE
yform - be_manager_relation - cache - self::$yform_list_values

### ISSUE THREAD

**Issue by dergel** [yakamara/redaxo_yform#463]
werden mehrere Datensätze hintereinander geschrieben oder verändert, kann es sein, dass die Caches noch greifen und daher falsche Informationen bei der Überprüfung verwendet werden.

https://github.com/yakamara/redaxo_yform/blob/master/plugins/manager/lib/yform/value/be_manager_relation.php#L274

das müsste schlauer geregelt werden. Im Moment hilft nur das auskommentieren der Zeile, so das kein Cache verwendet wird.

**Comment by gharlan** [comment]
Die verlinkte Zeile oben ist wahrscheinlich nicht mehr die ursprünglich verlinkte. Deswegen bin ich mir nicht 100% sicher, aber vermutlich ist hier das gleiche gemeint wie in https://github.com/yakamara/redaxo_yform/issues/439, was ich gerade gefixt habe.

**Comment by dergel** [comment]
ich denke auch
