### ISSUE TITLE
Checkbox "Nur Speichern bei Änderungen" an den Tables

### ISSUE THREAD

**Issue by bitshiftersgmbh** [yakamara/redaxo_yform#466]
Es gibt einige Fallbeispiele, wo ich mir eine Standard-Implementierung eines Speichern (Update) nur bei tatsächlicher Änderung mindestens 1 Feldes gewünscht hätte. Einige Dinge müssten dabei berücksichtigt werden, wie z.B. das Ignorieren von datestamp-Feldern mit Auto-Update (falls das überhaupt eine Rolle spielt wegen des Timings).

Falls man also einen Datensatz öffnet und ohne echte Änderung wieder speichert und die Option gesetzt ist, könnte eine *Warnung* aufploppen a lá: "Es wurden keinen Änderungen festgestellt. Das Speichern wurde abgebrochen." oder so...

**Comment by alexplusde** [comment]
Dir fehlt ein Abbrechen-Button, oder? #739 Dann könnte man "Speichern" so lassen, wie es ist.
