### ISSUE TITLE
DB-Table-Name als Klasse in der Listenausgabe einfügen (für custom CSS/JS)

### ISSUE THREAD

**Issue by bitshiftersgmbh** [yakamara/redaxo_yform#467]
Ich hab öfter das Thema, dass Kunden mehrere Tabellen haben. Ebenso oft wünsche ich mir, per CSS oder JS an den Tables, speziell der Listenausgabe, kleinere Modifikationen vornehmen zu können. Die sollen natürlich nur bei bestimmten Tabellen greifen.

Soweit ich es überblicke, gibt es aktuell keine Möglichkeit, das sauber zu lösen, da ein Identifier in Form eines HTML-Attributs oder einer Klasse fehlt. Eigentlich sollte das recht leicht zu machen sein, die DB-Table, auf die sich die aktuelle Ansicht bezieht, als CSS_Klasse zu verwursten.

Z.B. hier:
`<section class="rex-page-section">`
zu
`<section class="rex-page-section table-rex_news">`
erweitern.

**Comment by tbaddade** [comment]
👍 für die Idee . 
Die Class würde ich jedoch eher so bezeichnen `yform-table-rex-news`

**Comment by alexplusde** [comment]
Der Datenbank-Tabellenname sollte aber den Unterstrich behalten, oder nicht?

**Comment by elpschulzo** [comment]
@alexplusde : Jopp. Wär schon besser, wenn der Table Name 1:1 abgebildet ist.

**Comment by dergel** [comment]
geht leider so nicht .. muss zunächst in REDAXO in Fragment ermöglich werden.

**Comment by elpschulzo** [comment]
**/push**

Ich brauche das gerade dringendst weil ich mir sonst mit EPs und XOF (unnötig) die Finger breche.
Evtl. könnte man es im nächsten Minor Release zumindest an die Tabelle selbst tackern.

Meine aktuelle Version der `manager.php`, die genau das macht hat in dem betroffenen Bereich:

```
if ($show_list) {
	$sql = $this->getDataListQuery($rex_yform_filter, $searchObject, $this->table);

	/** @var rex_list $list */
	$list = rex_list::factory($sql, $this->table->getListAmount());
	$list->addTableAttribute('class', 'table-striped table-hover yform-table-'.$this->table->getTableName());
...
```

Das ist zwar ein paar Etagen tiefer als es mir lieb wäre aber so kann ich zumindest mit deutlich weniger Code Anpassungen machen, komme mit JS und CSS viel besser als die Table.
