### ISSUE TITLE
Table Manager: Feldtyp für "Datensätze pro Seite" (list_amount) ändern

### ISSUE THREAD

**Issue by IngoWinter** [yakamara/redaxo_yform#470]
Aktuell wird das Feld als tinyint(3) unsigned angelegt. Dadurch kann ich in der Listenansicht des Table Managers nur 255 Datensätze auf einmal anzeigen lassen. Ich habe öfter den Fall, dass in einer Tabelle  mehr als 255 Datensätze drinstehen. Performancetechnisch ist es kein Problem, zb. 1000 Datensätze auf einen Rutsch ausgeben zu lassen und einige Redakteure (und ich selbst auch) benutzen gerne die Browsersuchfunktion oder scrollen eben zum passenden Eintrag. Die Beschränkung auf 255 Datensätze macht das mühsam. Imho sollte der Admin/ Entwickler selbst entscheiden können, wieviele Datensätze auf einmal ausgegeben werden.

**Comment by elpschulzo** [comment]
Tatsächlich fällt mir das gerade auch gerade auf die Füße.
Bitte ändern.
