### ISSUE TITLE
Validate: JSON

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#474]
Ein validate-Feld für JSON könnte yform intern gut gebrauchen bei der Eingabe von JSON sowie allgemein nutzbar.

**Comment by dergel** [comment]
Validierung ist nun drin .. type wurde ergänzt

**Comment by alexplusde** [comment]
Danke. Nun gilt es, diese Validierung auch zu nutzen. Bspw. beim Attribute-Feld in der Feld-Definition.
