### ISSUE TITLE
manager: felddefinitionen erweitern

### ISSUE THREAD

**Issue by dergel** [yakamara/redaxo_yform#476]
so dass man vollständiger definieren kann. default wert, null, format ..

**Comment by dergel** [comment]
vs nur optionale Pflichtänderung der Felder

**Comment by alexplusde** [comment]
Zu beachten wäre, was beim Löschen und erneutem Anlegen einer Felddefinition passiert. Ob der neue Typ dann angewendet wird (könnte aber zu Datenverlust führen), oder ob die bestehenden Einstellungen am Datenbanktabellenfeld erhalten bleiben, wodurch Fehler evtl. nicht auffallen. Bspw ein int-Feld, das durch die neue Felddefinition Text benötigt.

Oder, alternativ: Nutzer warnen/fragen: „Feld stimmt nicht mit Felddefintion überein. Löschen und neu anlegen oder weiternutzen?“

**Comment by alexplusde** [comment]
Nachtrag/Spezialfall: be_relation kann ja je nach Einstellung null, id oder ein set enthalten. Ist aber bisher Text. Da müsste man auch Einfluss nehmen können.

**Comment by dergel** [comment]
das wird hier gemacht:

https://github.com/yakamara/redaxo_yform/issues/494
