### ISSUE TITLE
Docs - Zeilen, wie man sich die aktuelle Version holen kann

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#479]
Verwendet man die YForm-GithubH-Version ist die Doku nicht dabei und es kommen im Backend paar Warnings. 

Gut fände ich, wenn ein paar Zeilen beschreiben könnten, wie man die Docs-GH-Version in YForm hinein bekommt.

**Comment by tbaddade** [comment]
Was war denn der Gedanke dabei, dies über 2 Repos laufen zu lassen?

**Comment by alexplusde** [comment]
(Das weiß ich nicht)

**Comment by dergel** [comment]
sollte wir die docu am besten direkt hier reinnehmen ? . Wollte wohl das trennen, damit diese Issues einen nicht total wahnsinnig machen .. 
Was meint ihr ?

@tbaddade @alexplusde

**Comment by alexplusde** [comment]
Mittlerweile hat die Doku Substanz, es kommen nicht so viele Issues mehr dazu. Finde, man könnte das zusammenlegen, wenn es euch nicht stört.

**Comment by dergel** [comment]
Ich fände es auch gut.. Da ich nicht soo viel an der Doku mache - müssten wir die ganzen Issues mit übernehmen, oder könnten wir (du ;) ) das was wegrocken ? Vielleicht gibt nich 2-3 Leute die mithelfen könnten. Slack ?

**Comment by alexplusde** [comment]
Ich hätte gerne noch Feedback von @tbaddade und dann kann ich mal schauen, ob ich im Januar dazu komme... Hilfe wäre natürlich super.

**Comment by tbaddade** [comment]
Ich würde es zusammenlegen, nur die Logik der Doku sollte der core bringen. Es gibt m.E bereits einige Addons die das von sich aus mitbringen.

**Comment by alexplusde** [comment]
erledigt in https://github.com/yakamara/redaxo_yform/pull/837
