### ISSUE TITLE
Methode setHiddenField() ersetzen durch setValue()

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#480]
und setHiddenField() auf deprecated setzen. Es sorgte/sorgt immer mal wieder für Verwirrung, dass ein hidden-Feld kein `<input type="hidden" />`-Feld ist. Eine Umbenennung würde dem Umstand Rechnung tragen und den Unterschied klar machen.

Siehe https://github.com/yakamara/redaxo_yform_docs/issues/82

**Comment by gharlan** [comment]
Es gibt drei Variante:
- `setHiddenField`: einfach nur ein `<input type="hidden"/>`, was aber nicht wie ein Value weiter behandelt wird
- `setValue('hidden', ...)` ohne `REQUEST`-Param: Ein hidden-Value, welches nur php-seitig arbeitet, ohne `<input type=hidden/>`
- `setValue('hidden', ...)` mit `REQUEST`-Param: Ein hidden-value mit `<input type="hidden"/>`, der Wert kommt also über den Request mit

(Hoffe mein Gedächtnis stimmt soweit, habe es jetzt nicht nochmal nachgeschaut..)

Bin mir nicht sicher, ob man wirklich auf eine Variante davon verzichten kann, oder ob alle ihre Daseinsberechtigung haben.

**Comment by elpschulzo** [comment]
Ich brauche aktuell mehrfach tatsächlich alle 3.
Den Unterschied könnte man dennoch irgendwie besser handhaben bzw. alle 3 Varianten mit 1 Methode verarzten.

**Comment by tbaddade** [comment]
@gharlan Heißt die Methode nicht `setValueField`?
Vielleicht will @alexplusde mit `setValue()` auf etwas anderes hinaus. Müsste er dann noch einmal genauer erklären.

**Comment by alexplusde** [comment]
Ehh... Es gibt drei Möglichkeiten? Das war mir selbst nicht bewusst.

Ich wollte vorschlagen, dass man nicht von `hidden` spricht, wenn nicht ein Input-Feld ausgegeben wird, um so Verwirrung zu vermeiden und stattdessen ein YForm-Feld, das von YForm ausgefüllt wird, eine andere Methoden-Bezeichnung bekommt, um den Begriff `hidden` besser abzugrenzen.

Dass setValue ja auch belegt ist, habe ich nicht bedacht. 

Damit ist die Verwirrung wohl komplett.

**Comment by ynamite** [comment]
Ich bin auch total verwirrt. 

Kann mir jemand klipp und klar sagen wie ich ein <input type="hidden" name="key" value="sefsdfsfd" /> mit yform anlege? :) Ich schnalls nicht und finde in der Doku kein Beispiel. 

Wenn ich ein Text-Feld erstelle und das dann als Hidden-Feld missbrauche, baut yform unnützes HTML um das Feld herum. 

Danke :)

**Comment by alexplusde** [comment]
@ynamite kannst das HTML value dazu nehmen.

**Comment by dergel** [comment]
Gregor hat das gut erklärt. Gerne in der Doku aufnehmen. PRs sind willkommen.
die 4. Variante hat alexplusde erklärt

von YForm aus ein html Feld verwenden und dort einfach seinen HTML-Code reinlegen. hier wäre es eben dieses hidden input Feld.

**Comment by alexplusde** [comment]
Ich bin da bei @ynamite. Ich kenn mich mit genau 3 Feldtypen aus, mit denen man Hidden-Fields erzeugt:
* ein YForm-Feldtyp "text", dem ich type="hidden" als Attribut übergebe, das clientseitig ausgegeben wird und serverseitig von YForm verwendet werden kann.
* ein YForm-html-"Feld", über das ich selbst geschrieben ein `<input type="hidden">`-Feld ausgebe, aber von Haus aus nicht mit YForm verwendet werden kann (wie oben, nur schlechter, weil nur clientseitig verwendbar)
* ein YForm-Feldtyp "hidden", das clientseitig nichts ausgibt, aber für YForm sichtbar ist, bspw. Session-Infos, die aber nicht clientseitig manipuliert werden sollen / dürfen, außer, man übergibt den REQEUST-Parameter. Das das ist das, was Gregor doch mit seinem Codebeispiel meinte, oder?

Was ist also nun
* `setValueField()`?
* `setHiddenField()`?

Ich bin da auch verwirrt.

> Wenn ich ein Text-Feld erstelle und das dann als Hidden-Feld missbrauche, baut yform unnützes HTML um das Feld herum.

Das ist imho kein ernsthaftes Problem.

**Comment by dergel** [comment]
Wollen wir das dann auf die Doku schieben ?

Zur Erklärung .. Grundsätzlich - egal wie die Felder heissen, geht es um hidden Felder welche die YForm beachtet und welche die sie nicht beachtet.

Ein hidden Feld in via setValueField(hidden sorgt dafür, dass dieser Wert auch in der DB gespeichert werden kann oder in einer E-Mail verwendbar ist.

Ein setHiddenField, gibt einem die Möglichkeit, ein hidden Feld im Formular zu verwenden, was keinerleit weitere Bedeutung für die YForm hat, also dort auch nicht auftaucht. Z.B. wenn man eigene Logiken hat in der Programmierung...

der Rest sind Varianten davon

**Comment by alexplusde** [comment]
Um es in die Doku zu schreiben, müssen wir es alle kapieren und sowohl die Pipe-Notation, als auch die PHP-Notation, als auch die YOrm-Notation auf die Kette bekommen für die Fälle
* darf / soll in die Datenbank
* darf / soll in PHP verarbeitet werden
* darf / darf nicht clientseitig sichtbar sein
* darf / darf nicht clientseitig veränderbar sein.

> Ein setHiddenField, gibt einem die Möglichkeit, ein hidden Feld im Formular zu verwenden, was keinerleit weitere Bedeutung für die YForm hat, also dort auch nicht auftaucht. Z.B. wenn man eigene Logiken hat in der Programmierung...

Im Formular, aber nicht im HTML-form, richtig?

**Comment by dergel** [comment]
setHiddenField sorgt dafür, dass im Formular Felde abgelegt werden, welche nicht in der YFormDefinition genutzt werden, also, nur Werte die für das drumherum nötig sind .. Z.B. im Frontend könnten dort article id und clang angelegt sein und im Backend die Pageinfos wo man sich befindet etc. (dieses setHiddenField gibt es nicht in der pipe Notation und auch nicht in YOrm, da es dort eigentich nicht nötig sein sollte). Man könnte dieses Feld auch über setValueField(html.. <input type hidden .. setzen.. ist im Prinzip identisch. 

setValueField sind immer Felder die direkt Einfluss auf das eigentlich Formular haben, was verarbeitet wird. ( daher dann auch in YOrm und Pipe möglich)

 irgendwie besser kann ich es nicht erklären.

**Comment by alexplusde** [comment]
Das urspr. Issue ist nicht sinnvoll. Es bleibt dabei, die Doku dahingehend zu verbessern, um die Verwendung und den jeweiligen Einsatzzweck sowie dessen Konsequenzen besser zu erläutern.

Bis dahin bleibt es so, wie es ist.
