### ISSUE TITLE
Bessere Fehlermeldung, wenn validiertes Feld nicht existiert

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#482]
Löscht man ein Feld, auf dem noch eine Validierung liegt, bekommt man beim Speichern eines Datensatzes ein Whoops-Fehler, `...getValue() on null`. Eine genauere Fehlermeldung (oder zumindest die Fehlermeldung der Validierung) würde helfen, das Problem nachzuvollziehen.

**Comment by dergel** [comment]
ist drin . gerne mal gegenprüfen und issue schliessen

**Comment by dergel** [comment]
ich schliesse doch.. wenn noch was sein sollte - sag bescheid
