### ISSUE TITLE
Icon für Tabellen im Menü: Tabelle statt Datenbank

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#483]
Das Icon für Datenbanken ist bereits durch Module belegt:
![image](https://user-images.githubusercontent.com/3855487/43391350-c439df0e-93f0-11e8-94c7-838dc4a77098.png)

Die Tabellen werden alle mit demselben Icon ausgestattet:

![image](https://user-images.githubusercontent.com/3855487/43391406-e26f45ae-93f0-11e8-9a83-e199cd0618f1.png)

FontAwesome bietet aber auch ein Table-Icon:

![yform](https://user-images.githubusercontent.com/3855487/43391422-ebe755e0-93f0-11e8-9490-a535839d479d.png)

(Dieses Issue benötigt keine Beachtung, wenn https://github.com/yakamara/redaxo_yform/issues/235 umgesetzt würde)

**Comment by dergel** [comment]
dann würde ich sagen wir machen #235
