### ISSUE TITLE
Tableset Import funktioniert nicht mehr

### ISSUE THREAD

**Issue by lexplatt** [yakamara/redaxo_yform#489]
Wenn man ein Tableset importiert erhält man die Fehlermeldung dass die erste Spalte der Tabelle bereits existiert.

Ich konnte herausfinden dass es mit folgendem Commit zu tun hat: https://github.com/yakamara/redaxo_yform/commit/2bcd37f94059e5ee93644634cd1720ca676cd385

**Comment by dergel** [comment]
sollte wieder passen.. kannst du es prüfen ?
