### ISSUE TITLE
Wunsch: Tablemanager: Datensatz duplizieren

### ISSUE THREAD

**Issue by skerbis** [yakamara/redaxo_yform#49]
Gerade bei der Einpflege ähnlicher Datensätze wäre das sehr nützlich.

**Comment by alexplusde** [comment]
Gibt's mit yform_usability, könnte geschlossen werden.

**Comment by skerbis** [comment]
Ich sehe es schon eher im eigentlichen AddOn.

**Comment by tbaddade** [comment]
Den Trick kennt ihr?

https://friendsofredaxo.github.io/tricks/addons/yform/copy_dataset

> Ich sehe es schon eher im eigentlichen AddOn.

Fände es auch gut, wenn man bei den Tabelleneinstellungen definieren kann, dass neben dem `löschen` Link ein `duplizieren` Link angezeigt werden kann.

**Comment by dergel** [comment]
Das Thema ist komplexer wenn wir über Relationen sprechen. Inlinerelationen, Zwischentabelle oder auch  1-n Verknüpfungen müsste man entsprechend beachten.

**Comment by alexplusde** [comment]
Man müsste sogar Optionen bieten, vielleicht will man den Datensatz ja - aber ohne Relationen

**Comment by tbaddade** [comment]
Mir würde schon die Editmaske mit den vorbelegten Daten reichen, da zumeist der duplizierte Datensatz auch angepasst werden muss und somit wieder gespeichert wird.

**Comment by alxndr-w** [comment]
unique müsste auch Berücksichtigung finden, das würde für die Variante von @tbaddade sprechen.

**Comment by skerbis** [comment]
Eine Super-Lösung gibt es hier von @christophboecker 
https://github.com/FriendsOfREDAXO/tricks/issues/309#issuecomment-1373366416
