### ISSUE TITLE
be_relation: inline relation - anhand der id updaten

### ISSUE THREAD

**Issue by dergel** [yakamara/redaxo_yform#490]
im moment werden alle datensätze gelöscht und neu angelegt.

**Comment by alexplusde** [comment]
Lässt sich die Reihenfolge sinnvoll bearbeiten nachträglich?

**Comment by dergel** [comment]
ja.. wichtig ist, dass in der relation ein Priofeld angelegt wurde. weil ansonsten wird die Defaultsortierung der Tabellen genommen (falls du Yorm verwendest)..

**Comment by alexplusde** [comment]
Klasse, lässt sich das auch mit anderen Relationstypen umsetzen, diese Priorisierung?

**Comment by dergel** [comment]
es kommt natürlich drauf an was du machen willst.. aber das ist nicht das thema dieses issues.. hier geht es darum, dass nicht bei jedem update eines datensatzes, die zugehörigen 1-n relation komplett neu anlegen, sondern die alten, sofern schon vorhanden, aktualisiert werden.
