### ISSUE TITLE
choice feld opitimieren

### ISSUE THREAD

**Issue by dergel** [yakamara/redaxo_yform#493]
für update vorbereiten, dass die umwandlung von diesen feldern klappt:

yform_values_deprecated_checkbox_sql = Deprecated; Verwende das Choice value
yform_values_deprecated_radio = Deprecated; Verwende das Choice value
yform_values_deprecated_radio_sql = Deprecated; Verwende das Choice value
yform_values_deprecated_select = Deprecated; Verwende das Choice value
yform_values_deprecated_select_sql = Deprecated; Verwende das Choice value

**Comment by dergel** [comment]
bitte noch alte feld texte entfernen und choicetext anpassen

**Comment by dergel** [comment]
und wenn alles klappt - diese Felder entfernen

**Comment by tbaddade** [comment]
Prüfen #334

**Comment by dergel** [comment]
Problem ist noch, was machen wir mit den ganzen anderen Feldern aus anderen AddOns und Formbuildergeschichten..

**Comment by tbaddade** [comment]
andere AddOns die `YForm` und nicht `rex_form` nutzen (dort müssten die Values angepasst werden), wären zum Bsp.

- [YCom](https://github.com/yakamara/redaxo_ycom)
- [YForm](https://github.com/yakamara/redaxo_yform) selbst
- [YRewrite](https://github.com/yakamara/redaxo_yrewrite)
- [Poll](https://github.com/FriendsOfREDAXO/poll/)
- ...

**weitere gern ergänzen**

**Comment by dergel** [comment]
wir machen nun ja kein Update mehr und markieren die alten Felder als deprecated.. macht es um einiges leichter ;)
