### ISSUE TITLE
Fields und Datenbankfelder abgeleichen

### ISSUE THREAD

**Issue by dergel** [yakamara/redaxo_yform#494]
so dass die richtigen Datenbankfelder gesetzt werden.

**Comment by dergel** [comment]
nach langem hin und her, wollen wir das nun doch nicht mehr erzwingen. d.h. beim anlegen wird das entsprechend vorgegebene Feld gesetzt. Danach kann das jeder für sich selbst abändern und YForm passt nichts an.

**Comment by dergel** [comment]
datetime, datestamp, float, decimal, bool/enum, dbtype callable machen

**Comment by dergel** [comment]
checkbox, .. felder mal komplett durchgehen

https://github.com/yakamara/redaxo_yform/issues/261

**Comment by dergel** [comment]
float - deprecated
number ersetzt float und decimal
dbtype ist nicht callable aber über hooks änderbar

offen:
datestamp
datetime
checkbox bool/enum
was fehlt noch ?

**Comment by alexplusde** [comment]
Ein Checkbox-Feld ist nicht zwingend ein db-bool-Feld.

**Comment by dergel** [comment]
ich habe das so neu interpretiert und mich an anderen Systemen orientiert. Es gibt an und aus.. was man daraus dann macht ist dann ein technischer Hintergrund, unabhängig von der Eingabe. Eventuell könnte man dennoch Ausgabewerte mit aufnehmen, die dann in der Übersicht erscheinen. hmm..
