### ISSUE TITLE
choice: Ausgabe von groupattributes und attributes

### ISSUE THREAD

**Issue by dtpop** [yakamara/redaxo_yform#498]
Bei diesem Pipestring wird zwar die Klasse `choiceattribute` ausgegeben, nicht aber `groupclass` und `groupitem`.

`choice|artikel|Artikel|SELECT name label, id value, catname FROM rex_article ORDER BY catname|1|1||catname|8,5|---bitte auswählen---|{"class":"groupclass"}|{"class":"groupitem"}|{"class":"choiceattribute"}`

Betrifft 3.0.dev

**Comment by tbaddade** [comment]
Kannst du das ggf. Tabellarisch hier erfassen? Als ob man ein Feld via Manager anlegt. Du verstehst?

**Comment by dtpop** [comment]
Ich habe das Feld nicht über den Tablemanager angelegt sondern in diesem Falle im neuesten Modul YForm Formbuilder. Wobei dort bei der Erklärung auch die Angabe vom placeholder fehlt:
`choice|name|label|choices|[expanded type: boolean; default: false]|[multiple type: boolean; default: false]|[default]|[group_by]|[preferred_choices]|[group_attributes]|[choice_attributes]|[attributes]|[notice]|[no_db]`
Der funktioniert allerdings.

**Comment by tbaddade** [comment]
@dtpop Kannst du das gegenprüfen?
