### ISSUE TITLE
E-Mail Validierung

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#5]
match nicht, obwohl richtige Adresse.

`name@sub.domain.de`

**Comment by dergel** [comment]
kann ich leider nicht nachvollziehen.. Ist das eine Typüberprüfung (type), ein E-Mail feld (value: email) oder ist das die reine Email Validierung (validate: email) .. klappt bei mir immer.

**Comment by tbaddade** [comment]
War ein Problem mit doppelten Formularen auf einer Seite.
