### ISSUE TITLE
decimal-Feld ergänzen

### ISSUE THREAD

**Issue by gharlan** [yakamara/redaxo_yform#501]
Das Feld sollte in der Db dann `DECIMAL(X,Y)` nutzen, nicht `FLOAT`.
Sinnvoll zum Beispiel bei Preisen.

**Comment by alexplusde** [comment]
Es wäre m.E. sinnvoller, ein Number-value zu machen und darin den Typ festzulegen... float, int, decimal, ...

**Comment by tbaddade** [comment]
> Es wäre m.E. sinnvoller, ein Number-value zu machen und darin den Typ festzulegen... float, int, decimal, ...

Finde ich gut. Betrifft dann die aktuellen Values `float`und `integer`

Folgende Typen könnte ich mir vorstellen
- Decimal
- Float
- Integer
- Money
- Percent
- Range

**Comment by dergel** [comment]
range gehört für mich nicht dazu.. und so richtig den unterschied zwischen decimal, float kann ich nicht erkennen, geht ja um formularfelder. das gleiche gilt für mich für money und percent (würde ich eher als Zeichen erlauben).

float raus dafür decimal rein / mit eigener Feldeingabe für Art (z-B. € % $)
integer

@gharlan was denkst du wegen float und decimal ?

**Comment by dergel** [comment]
es geht um die Datenbank. Der Umbau sieht nun so aus (ich muss es noch bauen)

- float deprecated
- number rein (precision und scale, also wieviele Stellen etc) -> in Datenbank DECIMAL(x,y) -> Sortierung passt dann natürlich auch
- number und integer bekommen für die Feldeingabe für Art (z-B. € % $ ...)

**Comment by dergel** [comment]
ist nun drin :)
