### ISSUE TITLE
YForm 3 / Text-Felder: Zwangsformate vs. importierte Core-Tabellen

### ISSUE THREAD

**Issue by christophboecker** [yakamara/redaxo_yform#508]
Im YForm-3 wird z.B. bei Text-Feldern das Datenbank-interne Format entweder auf `text`oder auf `varchar(191)` gesetzt. Das ist ja ok bei Tabellen, die komplett per YForm-Table-Manager angelegt werden (nennen wir sie mal originäre YForm-Tabellen).

Was ist mit migrierten Tabellen? Da werden die Text-Felder auch umgestellt, sogar die Reihenfolge der Felder in der Tabelle ändert sich. Das wäre mir evtl auch noch egal (also tolerabel, egal nicht wirklich). 

An einer Stelle wird es aber haarig. Wenn ich mit dem Feldtyp `be_relation` arbeite müssen alle beteiligten Tabellen unter YForm-Kontrolle stehen. Zumindest bieten mit die YForm-Dropdown-Felder für Zieltabelle und Relationen-Tabelle nur solche Tabellen an. Und was ist, wenn die Relation zu einer Tabelle geht, die zum REX-System gehört (Artikel, Medien) oder in anderen AddOns liegen. Die müsste ich zuerst in YForm migrieren, damit sie für `be_relation` zugänglich sind. Dabei werden sie aber ggf. umgebaut. Das kann harmlos sein (`media/createuser` ist `varchar(255)`; `varchar(191)` reicht wohl auch), kann aber auch schiefgehen (gut gefülltes `varchar(255)`verliert Daten). Wer sich etwas dabei gedacht hat, dass ein Feld varchar(50) ist und es nun als varchar(191) oder `text` wiederfindet, wird sich ärgern. Kann ja auch technische Konsequenzen haben bis hin zur Problemen in der Grndfunktionalität von Redaxo, eventuell, womöglich, Risiko?

Mir wäre es sympatischer, wenn das Originalformat beibehalten werden würde - solange es nicht im eklatanten Wiederspruch zum YForm-Eingabefeld steht. Und entsprechend mit in der Formatauswahl auftaucht. Oder for Formatauswahl auch Freitext in gewissen Grenzen (`varchar(xyz)`) zulässt.

**Comment by alexplusde** [comment]
Das betrifft auch migrierte Tabellen

**Comment by christophboecker** [comment]
Zweiter Absatz, 1. Satz :-). Das Problem betrfft m.E. NUR migrierte Tabellen.

**Comment by tbaddade** [comment]
> Das betrifft auch migrierte Tabellen

Darum geht es @christophboecker 

>> Die müsste ich zuerst in YForm migrieren, damit sie für be_relation zugänglich sind.

M.E. sollten importierte Tablesets dagegen die neuen Formate akzeptieren.

**Comment by alexplusde** [comment]
> Zweiter Absatz, 1. Satz :-).

tl;dr ;D

**Comment by dergel** [comment]
Ich sehe das auch als Problem und denke, dass eine Checkbox mit `Bitte keine Feldtypen in der Datenbank ändern und nur fehlende ergänzen` lösen sollte

**Comment by alexplusde** [comment]
Desweiteren müsste man Mal schauen, ob die forcierte Konvertierung auch Probleme mit Views macht. Ist nämlich ziemlich genial, wenn man eine View migrieren kann.

**Comment by dergel** [comment]
sollte nun passen und gerne testen. beta2 schicke ich gleich raus
