### ISSUE TITLE
Datensatz wird nicht ins Widget übernommen, wenn ein einfaches Anführungszeichen im Feldnamen

### ISSUE THREAD

**Issue by polarpixel** [yakamara/redaxo_yform#514]
In der Moduleingabe steht Folgendes:
```
REX_YFORM_TABLE_DATA[id=1 output="listwidget" table="rex_artist" field="name"]
````

Wenn im Feld "name" ein Apostroph / einfaches Anführungszeichen vorkommt, wird der gewählte Datensatz nicht ins Widget übernommen.

**Comment by dergel** [comment]
auch in der aktuellen Version ? `Gefühlt` haben wir das bereits behoben.

**Comment by polarpixel** [comment]
Ja, das klappt jetzt mit der aktuellen Beta-Version. Danke!
