### ISSUE TITLE
choice: Komplexität vermindern

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#516]
Vorschläge kommen hier die Tage rein - grundsätzliches Feedback: Ich hätte es gerne einfacher. Ein/Ausblenden von unbenötigten Eingaben scheint mir zwingend notwendig.

Desweiteren Felder mit SQL/JSON-Eingabe zu Textarea machen, um alles sehen zu können

**Comment by alexplusde** [comment]
Beispiel: Das ist die Konfiguration, um eine einzelne Checkbox zu bekommen:
![image](https://user-images.githubusercontent.com/3855487/46006390-b8656100-c0b7-11e8-9bbe-638d16a02936.png)

Vielleicht sollte man stattdessen hier einfach auswählen können, wie man rendern möchte.

**Comment by alexplusde** [comment]
Vorschlag: Diese Eingabefelder nur in Abhängigkeit der gewählten Konfiguration per Javascript ein/ausblenden (und ggf. leeren, wenn nicht benötigt)

![image](https://user-images.githubusercontent.com/3855487/46006589-2873e700-c0b8-11e8-9bc0-b779bf3c41ea.png)

**Comment by tbaddade** [comment]
> Das ist die Konfiguration, um eine einzelne (!) Checkbox zu bekommen:

Das ist falsch. Dafür gibt es das Value `checkbox`. Choice verwendet man, wenn man mehrere Optionen zur Auswahl stellen möchte.

**Comment by alexplusde** [comment]
> Das ist falsch. 

Nein.

> Dafür gibt es das Value checkbox. Choice verwendet man, wenn man mehrere Optionen zur Auswahl stellen möchte.

@tbaddade warum sind dann Values für einzelne Wertpaare wie `select` oder `radio` deprecated? Je nach Kontext will ich ein `select` oder ein `radio` mit nur `ja/nein` oder `on/off` haben. 

Stichwort Usability: Eine Checkbox kann man immer nur mit einem Label beschriften z.B. `nein / nicht nein`, `links / nicht links` - besser ist es jedoch, beide Auswahlmöglichkeiten zu benennen `nein / ja`, `links / rechts`

Oder es müsste einen neuen Value-Typ `bool` geben, der wie `choice` auch `select`,`radio`,`checkbox` rendern kann... dann kann man die Funktionalität aber eben gleich auch in `choice` mit reinnehmen, finde ich.

**Comment by dergel** [comment]
will das Thema hier erstmal abschliessen - auch wenn es vielleicht nicht ideal ist. Wolfgang und Peter sind es nochmal durchgegangen und haben minimale Änderungen gemacht und diese sind bereits eingespielt. Auf dieser Basis das Ganze neu angehen

**Comment by alexplusde** [comment]
neu angehen heißt doch, das issue offen zu lassen, oder?

**Comment by gharlan** [comment]
Dieses Kombi aus expanded und multiple haben wir uns vom Choice-Feld bei Symfony abgeschaut. Ich fand das da immer recht schlüssig, was bei welcher Kombi rauskommt.
Aber wenn das viele zu verwirrend finden, könnte man natürlich schon überlegen, stattdessen nur ein Select-Feld zu machen mit den Optionen
- select (single)
- select (multiple)
- radios
- checkboxes

**Comment by alexplusde** [comment]
Mein Vorschlag:
![image](https://user-images.githubusercontent.com/3855487/48138707-2c914800-e2a5-11e8-9219-e3c219d6c947.png)

```
<table class="table"><colgroup><col width="69%"><col width="16%"><col width="16%"></colgroup><thead valign="bottom"><tr><th>Element</th><th>Erweitert</th></tr></thead><tbody valign="top"><tr><td>select tag</td><td><label><input type="checkbox" disabled="" >Erweitert</label><br><label><input type="checkbox" disabled="" >Mehrfachauswahl</label></td></tr><tr><td>select tag (with <code>multiple</code> attribute)</td><td><label><input type="checkbox" disabled="" >Erweitert</label><br><label><input type="checkbox"   disabled="">Mehrfachauswahl</label></td></tr><tr><td>radio buttons</td><td><label><input type="checkbox"  disabled="">Erweitert</label><br><label><input type="checkbox" disabled="" >Mehrfachauswahl</label></td></tr><tr><td>checkboxes</td><td><label><input type="checkbox"   disabled="">Erweitert</label><br><label><input type="checkbox"   disabled="">Mehrfachauswahl</label></td></tr></tbody></table>
```

**Comment by alexplusde** [comment]
Vorschlag für Labels:

`Erweitert` ändern durch "Alle Optionen sichtbar"
`Mehrfachauswahl` ändern durch "Mehrere Optionen wählbar"

**Comment by gharlan** [comment]
Den Vorschlag mit den angedeuteten Checkboxen finde ich ganz gut!

Die Umbenennungsvorschläge hingegen nicht so.

"Alle Optionen sichtbar" -> das würde ich eher so verstehen, dass wenn ich das nicht anhake, manche Optionen ausgeblendet werden (aus welchem Grund auch immer).
"Erweitert" finde ich aber auch noch nicht optimal, das englische "expanded" ist da klarer.

"Mehrfachauswahl" hingegen finde ich gängig und griffig, besser als "Mehrere Optionen wählbar"

**Comment by alexplusde** [comment]
@gharlan danke fürs Feedback

`Erweitert` kann alles mögliche heißen imho, es gibt auch kein Attribut namens "expanded". Aus der Sicht des Nutzers könnte man das auch `Alle Auswahlmöglichkeiten darstellen` nennen.
`Mehrfachauswahl` gehört mindestens ein Adjektiv (möglich,erlaubt) oder ein Verb (ermöglichen,erlauben).

Generell ist es best practice im Textdesign, das Motiv des Nutzers oder seine Handlung zu beschreiben, statt die Funktionalität. Aus der Motivation heraus sind meine Vorschläge.

**Comment by tbaddade** [comment]
Ich würde diese Diskussion verstehen, wenn die Notizen nicht wären. Wenn man sich diese aber ein- zweimal durchgelesen hat, dann sollte m.E. einiges klarer und verständlicher sein.

**Comment by alexplusde** [comment]
@tbaddade meine Skepsis gegenüber dem choice-Feld ist ja auch einer prinzipiellen Begeisterung gewichen. Ich erlaube mir, die Vorschläge zu machen, die aus persönlicher Sicht einerseits und aus fachmännischer Sicht andererseits helfen, das ganze beim 1. Lesen zu verstehen.

Zumindest meine Kollegen bestätigen, dass o.g. für sie verständlicher gewesen wäre, weil man dann weniger um die Ecke denken muss. Dran aufhängen möchte ich mich natürlich nicht.

**Comment by dergel** [comment]
ich schliesse das einfach wieder.. sofern ein neuer vorschlag kommt, können wir den wieder besprechen. für version 3.0 wohl aber nicht mehr
