### ISSUE TITLE
Datenbank-Fledtyp: Auswahl erlauben

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#517]
Im Moment kann man per select nur einen Typ erlauben. Wieso werden hier nicht mehr passende Typen zur Auswahl gestellt?

![image](https://user-images.githubusercontent.com/3855487/45960163-dd0bfb00-c01b-11e8-8ab9-ae4402f9765c.png)

(und wenn man das nicht können soll: Wieso ist es dann ein Select-Feld?)

**Comment by dergel** [comment]
der Einfachheit halber ist es immer identisch, weil verschiedene Felder auch mal mehrere Typen akzeptieren. Bei einem Feld ist es unschön das über ein select zu machen, aber für mich wegen der Einheitlichkeit ok..
