### ISSUE TITLE
Choice Feld - Wert oder Label in den Daten

### ISSUE THREAD

**Issue by dtpop** [yakamara/redaxo_yform#522]
Derzeit (aktueller Stand) wird bei folgender Notation
`$yf->setValueField('choice',["payment_type","{{ Payment Type }}",'Vorauskasse=prepayment,Rechnung=invoice,Paypal=paypal',1,0]);`
das Label in den Daten gespeichert.
![unbenannt](https://user-images.githubusercontent.com/1282121/46011135-3da34280-c0c5-11e8-858a-2df07b5a7895.JPG)
Wenn ich von choice auf radio wechsle, wird der Value in die Daten übernommen.
Da sich das Label z.B. von Sprache zu Sprache ändern kann, man aber in den Daten möglicherweise auf einen einheitlichen Wert reagieren will, wäre mir das alte Verhalten (Value in den Daten) lieber als das Label.

**Comment by tbaddade** [comment]
Ich habe eben mit deiner Notation ein Choice value via Manager angelegt. Der Wert in der DB ist der das `value` nicht das `label`. An welcher Stelle machst du den `dump`.

**Comment by dtpop** [comment]
Ergänzung: das Verhalten betrifft die email-Params, also beispielsweise über eine callback Action erhaltene Werte `$params->params['value_pool']['email']`. Bei sql kommen die Values `$params->params['value_pool']['sql']`

**Comment by tbaddade** [comment]
Es geht um diese Zeilen

https://github.com/yakamara/redaxo_yform/blob/master/lib/yform/value/choice.php#L93-L94

An die E-Mail werden aktuell die (ausgewählten) Labels weitergereicht. Die Values sollten vielleicht doch mit durchgeschleust werden.

@dergel Wollen wir die Keys allg. für YForm festlegen, so dass auch andere Values sich daran orientieren können?

Es geht um das hier: `$this->params['value_pool']['email'][$this->getName()]`

| Key | enthält | 
| ---- | ---- |
| `...['email'][$this->getName()]` | value(s) | 
| `...['email'][$this->getName().'_LABEL']` |  kommasepariert die ausgewählten Labels | 
| `...['email'][$this->getName().'_LABEL_LIST']` | enthält alle Labels, wobei die ausgewählten mit `[ x ]` gekennzeichnet sind (siehe obigen Screen von dtpop) |

**Comment by dergel** [comment]
ja gerne

**Comment by tbaddade** [comment]
> ja gerne

erledigt. siehe
https://github.com/yakamara/redaxo_yform/blob/master/lib/yform/value/choice.php#L103-L105

**Comment by dergel** [comment]
gerne hier dann schliessen :)
