### ISSUE TITLE
manager: "Tabellenbeschreibung" fehlt in 3.0-beta2

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#525]
War früher hier

![image](https://user-images.githubusercontent.com/3855487/46025092-6b4db300-c0e8-11e8-9362-0a5748c22fe8.png)

**Comment by dergel** [comment]
Die wurde nie irgendwo angezeigt, deswegen habe ich sie entfernt.

**Comment by alexplusde** [comment]
Ich hatte mir den umgekehrten Weg gewünscht und die Beschreibung an der Tabelle gezeigt, z.B. Instruktionen für den Redakteur oberhalb der Datensatz-Übersicht.

**Comment by dergel** [comment]
im Moment bin ich mir unsicher, ob das nicht doch reinsollte.. 
@tbaddade was meinst du ?

**Comment by tbaddade** [comment]
Wenn es da Bedarf gibt warum nicht wieder mit reinnehmen. Soweit ich mich aber erinnern kann, haben wir die selbst nie genutzt. Die Bezeichnung reichte da zumeist aus.

**Comment by dergel** [comment]
so eine kurze Beschreibung ist dann vielleicht doch gut.. ja, dann wieder alles zurück :)

**Comment by alexplusde** [comment]
Danke :)
