### ISSUE TITLE
Manager: Mögliche SQL-Injektion

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#526]
Infos via Slack an @dergel

**Comment by alexplusde** [comment]
Das Prio-Feld auf bspw. das Feld "name" beschränken. Der Name landet 1:1 im Query unter "WHERE". Fällt auf, wenn man Anführungszeichen im Namen hat.

Ein Redakteur kann somit einen Datensatz anlegen, der dann hinterher als Query ausgeführt wird.

Davon abgesehen sollte es bei Datensätzen mit `"` nicht zu einem SQL-Fehler kommen.

**Comment by dergel** [comment]
wenn ich das richtig im Kopf habe, sind es Änderungen im Backend, wenn der Admin die entsprechenden Felder anlegt. Das ist normal, dass dieser theoretisch Dinge machen kann, mit der man etwas kaputt machen kann. Oder habe ich das falsch verstanden ?

**Comment by alexplusde** [comment]
Falsch verstanden. Ein admin führt eine fehlerhafte Konfiguration aus - ein Redakteur ohne besondere Rechte kann dann beliebiges SQL ausführen.

**Comment by dergel** [comment]
ah ok .. jetzt aber :)

**Comment by dergel** [comment]
sollte nun passen

**Comment by alexplusde** [comment]
Einen Rextaler zum Dank!
