### ISSUE TITLE
choice: JSON-Parameter validieren

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#529]
siehe #474, #528

**Comment by tbaddade** [comment]
Inwiefern betrifft es das Choice Value?

**Comment by tbaddade** [comment]
Ja, beim anlegen eines Values, nicht beim ausfüllen in einem Formular.

**Comment by alexplusde** [comment]
Korrekt. Ich rede davon, die Eingabe im Table Manager zu validieren, wenn JSON eingegeben wurde.

**Comment by tbaddade** [comment]
Ich frage deshalb, da du dieses Issue mit deinem PR verknüpft hast. Validiert der PR nicht nur Formulareingaben?
https://github.com/yakamara/redaxo_yform/pull/528

**Comment by dergel** [comment]
nicht wirklich, weil gerade bei choices die Möglichkeit auch besteht verschiedene Formen einzugeben.. Aber es würde helfen bei den ganzen anderen Feldern, z.b. "attributes" eine solche Überprüfung einzubauen..

**Comment by dergel** [comment]
json validierung ist nun in der type validierung drin. hier in choice lässt sich das leider nicht so einbauen. wir müssen davon ausgehen, dass der entwickler das richtig macht
