### ISSUE TITLE
#disabled:disabled -> submit = value leer

### ISSUE THREAD

**Issue by olien** [yakamara/redaxo_yform#53]
Sofern ich disabled nutze wie z.B.:

text|OfferingTyp|Typ|Hallo||#disabled:disabled

erhalte ich nach dem senden des Formulars: 

<input class="form-control" type="text" name="OfferingTyp" id="yform-formular-field-7" value="" disabled="disabled">

sprich das value ist leer..

Wenn ich das disabled weg lasse funktioniert alles wie gewünscht.

**Comment by dergel** [comment]
bei disabled eine normale reaktion des formulars. deswegen keine Problem der YForm.
