### ISSUE TITLE
Tabellen immer inaktiv (3.0-beta2)

### ISSUE THREAD

**Issue by olien** [yakamara/redaxo_yform#531]
Nach dem Anlegen einer Tabelle werden anscheinend die Stati der Chekcboxen ignoriert...
Ausserdem bleibt die Tabelle "inaktiv".

Test:

1. Tabelle anlegen

![image](https://user-images.githubusercontent.com/330516/46463314-ef2c2d00-c7c3-11e8-96ec-2b42a640c18d.png)

![image](https://user-images.githubusercontent.com/330516/46463328-f5baa480-c7c3-11e8-9e46-6ab6438a3e8c.png)

2. Tabelle editieren / Alle Checkboxen deaktivieren

![image](https://user-images.githubusercontent.com/330516/46463397-171b9080-c7c4-11e8-9335-0b4e19b35617.png)

3. Tabelle aktualisieren

Ergebnis: 

![image](https://user-images.githubusercontent.com/330516/46463430-2995ca00-c7c4-11e8-9090-eb3493afdd90.png)

**Comment by dergel** [comment]
sollte alles wieder passen
