### ISSUE TITLE
Überflüssiges Zeichen in ID des Formulars (3.0-beta)

### ISSUE THREAD

**Issue by dunnodun** [yakamara/redaxo_yform#532]
In der Beta-Version scheint ein kleiner Fehler beim Erstellen der ID des Formulars zu existieren, der dafür sorgt, dass ein Größer-als-Zeichen der ID hinzugefügt wird. 

## Version 2.3
![](https://i.imgur.com/sC2xw8K.png)
## Version 3.0-beta2
![](https://i.imgur.com/dP67yB0.png)

**Comment by dergel** [comment]
ist bereits gemacht.
