### ISSUE TITLE
YCom füllt YForm-Felder `name`, `email` usw. aus.

### ISSUE THREAD

**Issue by dergel** [yakamara/redaxo_yform#536]
das liegt daran, dass in der YCom ein YForm verwendet wird, welches dann bestimmte REQUEST Parameter befüllt und das wiederrum beeinflusst dann Formulare etc ..

D.h. bei YFORM die REQUEST Variablen ignorieren,

**Comment by alexplusde** [comment]
Ist das auch der Grund, warum weiterhin bei 2 Formularen das 2. validiert, wenn das erste absendet?

**Comment by dergel** [comment]
nein .. das sollte bei Formularen nicht passieren, wenn diese beide nicht real_names haben
