### ISSUE TITLE
YORM - be_media vs. Frontend 

### ISSUE THREAD

**Issue by skerbis** [yakamara/redaxo_yform#538]
Ich habe den Fall dass spezielle User Formulare im Frontend einpflegen aber die Hauptredakteure dies im Backend machen.

Für die Backenduser nutze ich be_media um Medien zu pflegen, da sie ja auf den Medienpool zugreifen können. Lese ich das Formular per YORM für das Frontend aus funktioniert be_media natürlich nicht.
Eine Umwandlung in mediafile wäre für diesen Fall sehr nützlich.

Meine Aktuelle Lösung sieht so aus:

in boot.php

```php
rex_yform_manager_dataset::setModelClass('news', 'rex_data_kreisnews');
```

Eigene Model-Class
```php 
 class rex_data_kreisnews extends rex_yform_manager_dataset { 

 public function getFields(array $filter = [])
	    {
	        $fields = $this->getTable()->getFields($filter);

	        if (rex::isBackend()) {
	            return $fields;
	        }
	        foreach ($fields as $i => $field) {
	  
	        	if ('media' == $field->getName()) {
	                unset($fields[$i]);           
	            }
	        }
	        return $fields;
	    }
    }
```

Anschließend füge ich das Medienfeld  bei der Ausgabe über YORM als mediafile wieder ein.

```php 
// verkürzter Auszug
$dataset = rex_yform_manager_dataset::create(news);
$yform = $dataset->getForm();
$yform->setValueField('mediafile', array('media','Bild zur Nachricht','2000','.gif,.png,.jpg','0','Das Bild entspricht nicht den Vorgaben','','52','','Das Bild wird nach Prüfung durch einen Chefredakteur freigegeben. '));
echo $dataset->executeForm($yform);
```

Was zur Folge hat dass das Feld nicht mehr an der ursprünglichen Position (Reihenfolge) des Formulars ist.
Kann man den Typ evtl. auch schon in der model class ändern so dass die Postion erhalten bleibt?

**Comment by skerbis** [comment]
@gharlan hast Du nen Tipp?

**Comment by dergel** [comment]
so eine richtig gute Lösung gibt es dafür nicht.. und ist ja eigentlich auch klar. aber du kannst na ..create(news) schauen ob du die objparams direkt änderst und dort dann das Feld ersetzt. Sorry, einen besseren Weg gibt es leider nicht..

**Comment by skerbis** [comment]
Danke 🙏 - habe in diesem Fall auf YORM verzichtet

**Comment by alexplusde** [comment]
Könnte man einen besseren Weg etablieren? Dass be_media im Frontend als Multiupload-Feld gerendert wird?

**Comment by alxndr-w** [comment]
Ich würde das gerne nochmal thematisieren, eine `unsetField('fieldname)`-Methode würde helfen, hier nochmal gezielt aufs Formular einzuwirken. In meinem Fall will ich im Table Manager einen Artikel auswählen können (be_link), an anderer Stelle jedoch diesen immer vorbefüllt haben und durch ein Hidden Field ersetzen.

**Comment by skerbis** [comment]
@alxndr-w das macht doch meine Model-Class bereits oben. Bzw. das hidden field musst du dann in deinem Modul hinzufügen.

**Comment by alxndr-w** [comment]
Verstehe ich nicht. Reden wir von YOrm?
