### ISSUE TITLE
hidden field / REQUEST

### ISSUE THREAD

**Issue by olien** [yakamara/redaxo_yform#54]
Komischerweise wird ein "hidden" Field ohne "REQUEST" nicht im Quellcode ausgegeben:

Funktioniert nicht:     **hidden|hallo|welt||**
Funktioniert:            **hidden|hallo|welt|REQUEST|**

LG
O.

**Comment by tbaddade** [comment]
Das war bereits in XForm schon so. Hidden Felder tauchen im Quellcode nicht auf.

**Comment by olien** [comment]
Ups. Wusste ich nicht. Hatte nie nachgeguckt :-). Danke!
