### ISSUE TITLE
date Feld voreinstellung von Default: YYYY/MM/DD -> YYYY-MM-DD ändern

### ISSUE THREAD

**Issue by dergel** [yakamara/redaxo_yform#543]
und andere datetime felder und ähnliches auch prüfen. (weiss der Teufel wo das herkommt ;) )

**Comment by alexplusde** [comment]
in beta6 bekomme ich bei einem date-Feld in der Anzeige nichts raus, wenn ich nicht zwingend `DD`,`MM`und`YYYY` verwende

![image](https://user-images.githubusercontent.com/3855487/50568427-f7a7eb80-0d51-11e9-9590-968ffa205787.png)

**Comment by alexplusde** [comment]
Damit verbunden sollte die Einstellung übrigens dort ignoriert werden, wo die Eingabe stattfindet. Ein Input type=date verlangt immer das o.g. Schema und kein eigenes.

**Comment by dergel** [comment]
ich habe nun feste Formate eingebaut. Es gibt im Prinzip ja eh nur ein paar sinnvolle Varianten. Wenn du type=date verwendest, solltest du natürlich das Standardformat nehmen. Aber gerade bei den type=text und anbindung an js kalender, sollte man diese Formate auch dort verwenden können.
