### ISSUE TITLE
Newlines in YForm Template werden als Zeichen ausgegeben

### ISSUE THREAD

**Issue by LAnnika** [yakamara/redaxo_yform#546]
Wählt man im yform AddOn den Reiter "E-mail Templates" und legt dort ein neues Template an, wird in dem Hilfsblock über den Eingabefeldern u.a. folgende Schreibweise vorgeschlagen:

`REX_YFORM_DATA[field="name" prefix="\nMein Name:" suffix=""]`

Bei Eingabe von 'Horst' erzeugt diese Schreibweise (sowohl im body als auch im body(html)) die Emailausgabe:

`\nMeinName:Horst`

Aus
`REX_YFORM_DATA[field="name" prefix="\nMein Name:" suffix="\n"]
wird
`\nMeinName:Horst\n`

Eigentlich reicht es, das "\n" aus der Hilfe zu entfernen, da im body-Teil die Absätze "mitgenommen" werden und im HTML-Teil das <br> verwendet werden kann.

Getestet mit
Yform: 2.3
REDAXO: 5.6.2
PHP: 5.6.38

**Comment by alexplusde** [comment]
Die Möglichkeit, Zeilenumbrüche per Präfix/Suffix mitzugeben, ist allerdings schon charmant, weil im HTML sonst leere Lücken entstehen könnten.

**Comment by dergel** [comment]
Leider gehts das mit den REX_Vars in dieser Form nicht, also nicht nur hier. Ein Umweg ist:

```
REX_YFORM_DATA[field="name" prefix="
Mein Name:" suffix="
"]
```
