### ISSUE TITLE
be_relation value: "select (multiple)" kann nicht mehr leer sein

### ISSUE THREAD

**Issue by ynamite** [yakamara/redaxo_yform#554]
Bei einem "select (multiple)" kann die Auswahl nicht mehr ganz gelöscht werden, wenn einmal gesetzt.
Sobald man alle Einträge im Multiple-Select deselektiert hat und den Datensatz speichert, wird in der Datenbank die Relation nicht aufgelöst (gelöscht).

**Comment by dergel** [comment]
Alles durchgetestet, konnte das leider nicht nachvollziehen. Kannst du das nochmal genauer beschreiben, eventuell screenshots + version angeben ? auch redaxo version

**Comment by ynamite** [comment]
Kein Problem.

Redaxo 5.6.4
yform 3.0-beta2

Folgende yform Tabellen:
`news`
`tags`
`tags_to_news`

Tabelle `news` Feld:
`tag` = `be_manager_relation` verknüpft mit `rex_tags` über Relationstabelle `tags_to_news` und wird angezeigt als `select (multiple)`

![grafik](https://user-images.githubusercontent.com/1733051/48497290-21559380-e834-11e8-82bc-a564f13b6e5f.png)

Wenn ich nun den Eintrag `Zürich` deselektiere und speichere, wird die Änderung am Feld nicht gespeichert und die entsprechenden Relationen nicht aus der Relationstabelle gelöscht. 

Ändere ich das `be_manager_relation`-Feld zu `popup (multiple)` funktioniert es wie gewünscht.

Hoffe das hilft!

**Comment by dergel** [comment]
ich habe das mit der aktuellen github version getestet und da geht das.. ich denke auch dass es bei deiner version gehen sollte ... sicherlich eher etwas mit der konfiguration.. die relatonstabelle muss auch die entsprechenden relationen zu tags und news haben, damit es richtig geht

**Comment by ynamite** [comment]
Dann muss es in der Tat an meiner Konfiguration liegen. Trotzdem komisch.

Kann es sein, dass wenn man ein Tableset mit Relations-Felder exportiert und importiert, irgendetwas wichtiges verloren geht in Zusammenhang mit Relationen? Nur am laut denken.

**Comment by dergel** [comment]
kann natürlich sein.. Wenn du das prüfen könntest - super
