### ISSUE TITLE
yForm 3.0: Schema-Definition schrottet die Datenbanktabellen

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#555]
Them: Datenbankfelder IMMER mit Schemadefinition überschreiben

ich habe hier zwei Tabellen, die den Haken drin hatten und hatte aber an der Datenbanktabelle manuell was an der Schema-Definition geändert. Ich brauchte `varchar`, wo `text` ist, um ein unique-Feld direkt an der Datenbanktabelle zu setzen.

Wenn man dann eine neue(!) Tabelle in YForm anlegt, gibt's einen Whoops - da ja bereits die Schemendefinition fehlerhaft ist. Die neue Tabelle wird zwar in rex_yform_table angelegt, nicht jedoch in der Datenbank.

**Comment by dergel** [comment]
Kannst du mir dazu das Beispiel als PM schicken ? .. Also welche Tabelle existierte bereits und was soll darauf gesetzt werden,,

**Comment by alexplusde** [comment]
Also, ich hab mich noch mal in mein Ich vom 2. November zurückversetzt: 

Ich brauchte an einer Datenbanktabelle, die in YForm verwendet wurde, eine UNIQUE-Prüfung direkt an der Datenbank. Diese Prüfung kann ich bei einem Feld, das auch in YForm als Textfeld angelegt ist, gar nicht erst (via PHPMyAdmin oder Adminer) anlegen, da dazu der Typ des Datenbankfelds `varchar` sein muss, YForm dieses allerdings versucht mit `text` zu überschreiben.

Reproduzierbar wie folgt:
1. Tabelle in YForm anlegen, Felddefinitionen müssen überschrieben werden
2. Text-Value, z.B. `name` in YForm anlegen
3. An der Datenbank via Adminer das Feld in `varchar` konvertieren und UNIQUE machen
4. Crash im YForm Backend beim Erstellen eines neuen Datensatzes.

**Comment by alexplusde** [comment]
Nein, in dem Szenario können auch Daten außerhalb von yform manipuliert werden. (ich sehe im erweiterten Sinne auch keinen Vorteil, wenn man Funktionen durch YForm an der Eh inkompatibel macht und dann simuliert.)

**Comment by dergel** [comment]
Das ist ein allgemein nicht so zu lösender Fall.. Wir gehen bei der YForm davon aus, dass die Verwaltung der Daten ausschliesslich darüber läuft und gerade auch bei Validierung das davon abhängt.

Meines Erachtens sollte es bei einem solchen Fall so laufen, dass die Daten über einen Schnittstelle (z.B. REST) und dann YORM eingebunden werden, oder eben auch nicht wenn die Validierung greift. .. die Uniqueprüfung geht dann bei TEXT Feldern, obwohl das natürlich nicht so performant ist ( Sinnvoller Umweg ist, sich einen YForm-Index Feld mit z.B. sha1 codierung anzulegen über welches man dann unique prüft).
