### ISSUE TITLE
yForm 3.0: In Schemadefinition varchar grundsätzlich als Alternative zu text ermgölichen

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#556]
Datenbank-Feldtyp "be_relation" kann nur text sein - ich benötige jedoch, um an der Datenbank (nicht YForm) auf `unique` zu prüfen, ein varchar()-Feld.

Prinzipiell sollte überall varchar möglich sein, wo aktuell nur text möglich ist.

**Comment by dergel** [comment]
unique kann man immer dadurch erreichen, indem man eine yform index feld nimmt, und den Wert eines anderen Feldes dort hasht und dieses Feld dann auf unique prüft. Ich baue es dennoch in be_relation mit rein .. ich gehe davon aus, dass jeder der das Default ändert weiss was er tut :)

**Comment by dergel** [comment]
https://github.com/yakamara/redaxo_yform/commit/7e0c73e825fcee7b26e3ee1b6c9be32eff078112

**Comment by alexplusde** [comment]
> ich gehe davon aus, dass jeder der das Default ändert weiss was er tut :)

👍
