### ISSUE TITLE
choice: Übergabe eines Arras ermöglichen (PHP-Schreibweise)

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#559]
Alternative / Ergänzung zu #558, um im Vorfeld ein Wertepaar per rex_sql mit prepared statements auszulesen und als array zu übergeben. Multidimensionalität beachten.

**Comment by alexplusde** [comment]
Der Punkt geht an dich.

**Comment by alexplusde** [comment]
(Ein paar Beispiele wären hilfreich, wie man das auch multidimensional machen kann. Ich bin da wirklich nicht sehr fit, was Arrays transformieren angeht.)

**Comment by tbaddade** [comment]
Diese Funktion sollte dir helfen.
http://php.net/manual/de/function.json-encode.php

**Comment by alexplusde** [comment]
Die kenne ich. Ich meine jetzt diese choice-Funktion aus der Gruppierung. Wie man aus einem flachen SQL-Ergebnis-Array das wieder multidimensional bekommt, ohne foreach. Da gibt's doch sicher Funktionen in PHP dafür zum transformieren...
