### ISSUE TITLE
Dokumentation: Hinweis für php Value im Formbuilder

### ISSUE THREAD

**Issue by claudihey** [yakamara/redaxo_yform#560]
Im PHP-Value ist keine Programmierlogik erlaubt (z.B. if/else). Dieser Hinweis fehlt zurzeit noch.

**Comment by alexplusde** [comment]
Issues für die YForm-Doku bitte immer hier https://github.com/yakamara/redaxo_yform_docs/ - bitte meine Nachricht in Slack beachten.

close
