### ISSUE TITLE
choice: Im E-Mail-Template wird das Label ausgeben, nicht der Value

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#561]
Datenbank-Eintragung ist korrekt, jedoch nicht die Ausgabe im E-Mail-Template.

Wie lautet die Schreibweise, um auf den Value statt das Label zuzugreifen oder ist das ein Bug?
Falls Bug: Wie kann man anschließend auf das Label zugreifen innerhalb eines E-Mail-Templates?

~Workaround ist, ein hidden-Feld anzulegen und per copy_value den Wert aus dem Formular mit zu übegeben.~ funktioniert ebenfalls nicht.

**Comment by alexplusde** [comment]
M.E. müsste hier das Value ausgegeben werden:

https://github.com/yakamara/redaxo_yform/blob/master/lib/yform/value/choice.php#L93

Wenn du die Labels unbedingt mit dabei haben willst, vlt. so?

```
        $this->params['value_pool']['email'][$this->getName()] = $this->getValue();
        $this->params['value_pool']['email'][$this->getName().'_LABELS'] = implode(', ', $choiceList->getSelectedListForEmail($values));
        $this->params['value_pool']['email'][$this->getName().'_LIST'] = implode("\n", $choiceList->getCompleteListForEmail($values));
```

**Comment by tbaddade** [comment]
Kannst du erklären, warum man die values in einer E-Mail haben mag? Möchte man nicht genau den Wert angezeigt bekommen, den man auch im Formular gesehen hat?

**Comment by alexplusde** [comment]
Ein Termin-Tool, bei dem man aus Radio Buttons einen Termin wählen kann. Die Labels enthalten nur die Uhrzeit, die Gruppe den Tag.

Das value enthält beides. Es ist nicht mehr möglich, anhand der Uhrzeit den richtigen Datensatz oder das richtige Datum zu finden. Die value hingegen ist eindeutig.

Außerdem ist es gegen die Praxis in YForm, dass dort plötzlich Labels statt values ausgegeben werden.

**Comment by tbaddade** [comment]
Danke für die Erklärung. Kannst gern einen PR erstellen, so dass zusätzlich auch die Values erscheinen.

**Comment by alexplusde** [comment]
@tbaddade dass es nicht untergeht: PR wurde angenommen. Nur falls du das bereits in E-Mail-Templates im Einsatz hast.

**Comment by tbaddade** [comment]
Danke für die Infp.
