### ISSUE TITLE
Spamschutz: Timer als Validate fest aufnehmen

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#565]
Ist es gewünscht, dass YForm in Zukunft alternativ oder ergänzend zum Captcha die in der Doku geschilderte Timer-Funktion als validate-Feld mitaufnimmt? Sie scheint laut Slack ja durchaus Anklang zu finden und wäre dann auch in YOrm bspw. verfügbar.

Siehe:
https://github.com/yakamara/redaxo_yform_docs/blob/master/de_de/demo_kontakt-spamschutz.md

**Comment by dergel** [comment]
Möchte nochmal schauen ob das so nötig ist und eher sogar schauen, dinge wie captcha captcha_calc und dieses hier zusammenzufassen.. Sonst bläht das die Geschichte hier so auf .. deswegen erstmal auf 3.1

**Comment by dergel** [comment]
https://github.com/yakamara/redaxo_yform/issues/595
