### ISSUE TITLE
Ausgewählte Daten werden nicht übernommen bei be_manager_relation und "Popup multiple"

### ISSUE THREAD

**Issue by polarpixel** [yakamara/redaxo_yform#566]
Das Problem entstand erst nach dem Update auf yform 3 Beta.
Mit "Select multiple" klappt es, aber nicht mit "Popup multiple".

**Comment by dergel** [comment]
ist hiermit wieder ok..
https://github.com/yakamara/redaxo_yform/commit/6b71e958c63dab7b09e97202ad9143f37a2cb8d1

**Comment by tbaddade** [comment]
Danke für das zuweisen des Commits @dergel

**Comment by polarpixel** [comment]
Vielen Dank, ich kann bestätigen, dass es klappt.
