### ISSUE TITLE
Title auf Unterseiten korrigieren

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#569]
Auf diversen Unterseiten kommt als Titel „Übersicht“ selbst wenn man sich in keiner Übersicht befindet.

Es geht um den Titel im Browser-Tab

**Comment by dergel** [comment]
war wohl nur bei email templates.. gerne konkrete andere fehlerhafte Texte melden.. Danke

**Comment by alexplusde** [comment]
Wurde der Titel im HTML geändert oder im title-Tag?
