### ISSUE TITLE
relationstabellen werfen fehler

### ISSUE THREAD

**Issue by rokitole** [yakamara/redaxo_yform#57]
habe einen bug bei relationstabellen entdeckt. ich lege zwei normale tabellen (A,B) an und zusätzlich eine relationstabelle (C). in der relationstabelle (C) lege ich zwei be_manager_relation felder an, gebe als namen den tabellennamen inkl prefix der zu verknüpfenden normalen tabellen (A,B) an. ich lege in den normalen tabellen (A,B) jeweils ein be_manager_relation feld an, dort gebe ich als relationstabelle die dritte tabelle (C) an. beim hinzufügen von einträgen in einer der normalen tabellen (A,B) wird eine fehlermeldung ausgegeben (anbei), die relationstabelle wird nicht beschrieben. in rex4 mit XForm funktioniert es prima, in rex5 mit YForm gibt es das beschriebene problem. in der fehlermeldung steht noch etwas von "table rex_relation does not exist", sie existiert aber definitiv :)

![bildschirmfoto 2016-04-23 um 16 32 01](https://cloud.githubusercontent.com/assets/11247158/14762144/96d21a22-0973-11e6-9801-59f220ad39ad.png)

**Comment by alexplusde** [comment]
Kann ich bestätigen:

![image](https://cloud.githubusercontent.com/assets/3855487/16153296/01089efe-34a6-11e6-9f87-6869f8bb1cf4.png)

Zugang zur Testinstallation könnte ich via #Slack bereitstellen.

**Comment by alexplusde** [comment]
Wollte es mit select_sql umgehen, gibt aber dsa gleiche Problem.

![image](https://cloud.githubusercontent.com/assets/3855487/16187039/5059ab22-36ce-11e6-8e7a-e9d19720a1f7.png)

**Comment by alexplusde** [comment]
Ist wohl ein Duplikat von https://github.com/yakamara/redaxo_yform/issues/3
