### ISSUE TITLE
choice: div-Element form-check-group, form-radio-group um id-Attribut erweitern

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#571]
Um im Frontend die Gruppe aller Checkboxen und Radiobuttons im CSS ansteuern zu können, muss noch der Feldname als id ausgegeben werden. Andernfalls lässt sich im CSS das Container-Element nicht ansprechen. 

Dies ist bei anderen Feldtypen Gang und Gebe:

![image](https://user-images.githubusercontent.com/3855487/48477186-349b3b80-e801-11e8-853c-4ae67a42b23a.png)

edit: man benötigt ein unterscheidbares Container-Element in CSS, JS (sonst muss man sich mit der JQuery-Methode parent() nach oben durchhangeln), oder PHP regex_replace oder str_replace.

**Comment by tbaddade** [comment]
das habe ich bewusst an diesen Stellen weggelassen. Mich störte das aufgeblähte Html durch YForm. Initial ist die Ausgabe so einfach wie möglich. Wer mehr Daten im Quelltext benötig, kann sich das Template auch kopieren und entsprechend anassen.

**Comment by alexplusde** [comment]
Gegenvorschlag: Wer weniger Quelltext benötigt, kann sich das Template kopieren und entsprechend anpassen.

**Comment by christophboecker** [comment]
Bisher konnte ich an der id, die mit "yform-data_edit" begann erkennen, dass es eine Formgroup auf oberer Ebene (Eingabefeld) war und mittels css Label und Feld nebeneinander setzen (dass dämmt die Platzverschwendung etwas ein). Da Formgroup auch innerhab von Feldern vorkommen (z.B. bei be_table) ist eine globale Anpassung auf dem Selektor ".form-group" nicht hilfreich. X Ausnahmen zu definieren ist auch nicht lustig, bläht nämlich das CSS auf. Lösung derzeit: dem choice-Feld ein Group-Attribut verpassen und darüber ne ID setzen, die mit "yform-data_edit" beginnt. Hier geht so was zum Glück noch.

**Comment by alexplusde** [comment]
@christophboecker hat recht, placeholder gibt's in select-Feldern nicht.

Das andere Problem mit dem fehlenden Selektor habe ich bereits hier gemeldet: https://github.com/yakamara/redaxo_yform/issues/571

**Comment by alexplusde** [comment]
Ich bin müde ob solcher Issues und finde es schade, dass hier Befindlichkeiten über Nützlichkeit und Standardverhalten stehen.
