### ISSUE TITLE
3.0-beta3: datestamp Datumsformat `mysql` überflüssig

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#573]
Bisher war es so: Um das Datum in der Übersicht zu formatieren, sollte man `mysql` als Datumsparameter angeben. Mit 3.0 ist diese Einstellung scheinbar obsolet geworden.

Wie kann bei einem YForm-Update erreicht werden, dass das Datum wieder korrekt in der Übersicht einer Datentabelle dargstellt wird? Jetzt ist es durch den String `mysql` so:

(Monat, Jahr, Sekunde = mys, dann q, dann l der Wochentag)

![image](https://user-images.githubusercontent.com/3855487/48487957-eb0e1900-e81f-11e8-8f7e-703d8e1f32c6.png)
![image](https://user-images.githubusercontent.com/3855487/48487972-f2cdbd80-e81f-11e8-8c0a-660242f0f2ee.png)

**Comment by alexplusde** [comment]
Das war einfach.

Sollte das nicht bei einem Update von 2.3 auf 3.0 automatisch passieren? (So wurden in vergangenen Versionen Felddefnitionen geupdatet, um einem neuen Schema zu entsprechen)

**Comment by dergel** [comment]
sollte, ja .. gerne als PR..
