### ISSUE TITLE
redirect-Action: Exit-Verhalten überdenken

### ISSUE THREAD

**Issue by gharlan** [yakamara/redaxo_yform#574]
Aus gutem Grund, macht die redirect-Action aktuell kein `exit()` am Ende:
https://github.com/yakamara/redaxo_yform/blob/master/lib/yform/action/redirect.php#L46

Andererseits ist das aber problematisch, dass der Code weiter ausgeführt wird. Zum Beispiel führt es hier zu doppelt ausgeführten Formularen (Beispiel von @alexplusde):

```php
$rex_article_content = new rex_article_content($rex_article->getId());
    $content = $rex_article_content->getArticle();

    if(!$content) {
        
        $rex_article_content = new rex_article_content($rex_article->getId(), 1);
        $content = $rex_article_content->getArticle();
    }
    
    echo $content;
```

Ggf. wäre es gut, wenn die Action der YForm mitteilen würde, dass diese am Ende ein `exit()` machen soll.

**Comment by alexplusde** [comment]
Könnte hier einen PR beisteuern, falls gewünscht, indem man bewusst der redirect-Action einen Parameter übergibt.

@gharlan dein Lösungsansatz hingegen wäre, dass das Form-Objekt erkennt, dass es bereits ausgeführt wurde.

**Comment by gharlan** [comment]
> @gharlan dein Lösungsansatz hingegen wäre, dass das Form-Objekt erkennt, dass es bereits ausgeführt wurde.

Nee, ich meine, dass die redirect-Action irgendeine neue objparam setzt (`exit = true` oder so), und die yform-basis-klasse die beachtet, und dann nach dem ausführten aller Actions ein `exit;` ausführt.
So hat man nicht das Problem, dass die redirect-Action zu früh abbricht, vor noch anderen auszuführenden Actions. Aber man hat trotzdem das exit;, was bei einem redirect sinnvoll ist.

**Comment by alexplusde** [comment]
Dann kann ich mich leider nicht daran beteiligen.

**Comment by alexplusde** [comment]
@gharlan könntest du einen PR dazu beisteuern, um das Problem noch in 3.0 zu beheben?

Ansonsten würde ich jetzt eine Kopie der redirect-Action machen, damit das updatesicher ist.

**Comment by gharlan** [comment]
Heute ist in Slack noch ein weiteres Problem mit der Stelle aufgefallen:

> Cannot modify header information - headers already sent by (output started at rex:///template/3:15)

YForm beendet alle Output-Buffer, setzt den Header, und lässt es dann aber weiter laufen. Es läuft dann also auch nicht mehr der Haupt-Output-Buffer von Redaxo.
Also kommt dann das Template irgendwann wieder und macht weitere Ausgaben.
Ganz am Ende versucht Redaxo Header zu setzen. Normalerweise klappt das, weil der gesamte Output gebuffert wurde. Jetzt kommt es aber zum Fehler, weil yform den Output-Buffer beendet hat, und dann aber nicht insgesamt abgebrochen hat.

Also: Output-Buffer nur leeren, wenn man kurz danach die Response auch wirklich beendet.

**Comment by dergel** [comment]
oder sich an den EP OUTPUT FILTER reinhängen und wieder alles löschen.. Aber das ist irgendwie sehr rumgehackt.

**Comment by gharlan** [comment]
> oder sich an den EP OUTPUT FILTER reinhängen und wieder alles löschen

Im OUTPUT_FILTER wird man keinen Content bekommen, und kann daher auch keinen löschen, da yform ja den Buffer beendet hat, und alle Ausgaben seitdem somit direkt ausgegeben wurden. Deswegen ja auch der Fehler, dass keine Header mehr gesetzt werden können.

**Comment by dergel** [comment]
Oder Buffer wieder starten und wieder alles löschen, oder den Redirect in den EP hängen oder oder ;) ..

**Comment by gharlan** [comment]
Um den Redirect-Header zu setzen, müsste yform gar nicht erst den Buffer leeren/beenden.

Also mein Vorschlag wäre:
- An der Stelle in der Action nur den `Location`-Header setzen, nichts am Outputbuffer ändern, und auch kein `exit()`
- Aber dazu noch dieses Verhalten: https://github.com/yakamara/redaxo_yform/issues/574#issuecomment-438698447
- Und wenn yform dort dann den exit nach allen Actions ausführt, sollten dort alle Output-Buffer geleert und gelöscht werden.

**Comment by dergel** [comment]
yform ist im ein param "form_exit" reicher/schwerer.. D.h.. wenn Formexit gesetzt ist, und das wird beim redirect gesetzt, beendet sich das formular nach den actions und postactions und löscht den cache. Header werden dann entsprechend ausgeführt.

**Comment by alexplusde** [comment]
Ok. Im Endeffekt muss man sich also um nichts kümmern, oder?

**Comment by dergel** [comment]
genau
