### ISSUE TITLE
REX_YFORM_TABLE_DATA um Filter für Datensätze erweitern

### ISSUE THREAD

**Issue by darwin26** [yakamara/redaxo_yform#576]
HI,
wäre es möglich die `REX_YFORM_TABLE_DATA` zu erweitern, damit auch das filtern der Datensätz möglich wäre. Bespiel  WHERE value = "foo"...

'REX_YFORM_TABLE_DATA[id=3 output="listwidget" table="rex_foo" field="title" filter="WHERE type = Blubb]'

Danke

**Comment by dergel** [comment]
das wird es leider so nicht geben - Müsste man dann über YOrm lösen. Hätte ich eigentlich locker auch schon mal früher schreiben können - sorry

**Comment by darwin26** [comment]
lieber zu spät als nie. Danke Jan ...
