### ISSUE TITLE
Checkbox gibt falsches HTML aus

### ISSUE THREAD

**Issue by marcohanke** [yakamara/redaxo_yform#578]
Mit der Notation checkbox|invoice_difference|Abweichende Rechnungsanschrift|0|| aus dem TableManager ist die HTML Ausgabe nicht korrekt.
Das Select ist innerhalb des Labels platziert.

**Comment by alexplusde** [comment]
Das Input ist korrekterweise nach Bootstrap-Standard im Label platziert. Hindert es dich?

**Comment by marcohanke** [comment]
OK, kannte/wusste ich so nicht. Dann schau ich mal wie ich das style. Danke
