### ISSUE TITLE
choice: Ist key/value vertauscht?

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#579]
Der Aufbau ist aktuell:
```
$array["LABEL"] = $value;
json_encode($array);
```
bzw.
```
$array["GRUPPEN-LABEL"]["LABEL"] = $value;
json_encode($array);
```

Müsste nicht $value der key sein und "LABEL" das Label? Ist das so eine gute Idee, da UTF8-Text in die Keys zu schreiben oder ist das mittlerweile ungefährlich?

Falls das so passt, bitte direkt schließen ;)

**Comment by tbaddade** [comment]
> Falls das so passt, bitte direkt schließen
