### ISSUE TITLE
Ein Punkt zu viel im Dateinamen bei mediafile

### ISSUE THREAD

**Issue by polarpixel** [yakamara/redaxo_yform#58]
Der Feldtyp mediafile erzeugt beim Upload einen zusätzlichen Punkt vor der Datei-Extension.
Der Name lautet also:
foto..jpg

**Comment by polarpixel** [comment]
Noch ein zweites Problem beim Mediafile-Feld:
Der Link zum Bild (wenn eines hochgeladen wurde) unter dem Feld führt noch zum Ordner "files".

**Comment by dergel** [comment]
sollte behoben sein
