### ISSUE TITLE
validate-Felder: Abfrage nach send-Parameter entfernen

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#582]
https://github.com/yakamara/redaxo_yform/blob/ebe2213f06a19e5735908974ee3a61d450cd873a/lib/yform/validate/compare.php#L14

Diese Zeile kommt in jedem Validate-Feld vor, nach meiner Ansicht überflüssig, da kein Code ausgeführt wird, wenn das Formular nicht abgesendet wurde (z.B. initial beim Aufruf). 

Scheint ein Artefakt vergangener Zeiten zu sein, als es vielleicht noch keine separaten Validates gab? 

Ist im Zuge mit #565 aufgefallen.

**Comment by dergel** [comment]
vielen dank für den hinweis
