### ISSUE TITLE
Wunsch: mediafile, vor upload bestehendes löschen

### ISSUE THREAD

**Issue by skerbis** [yakamara/redaxo_yform#583]
Wenn ein User im folgenden Beispiel einen Datensatz bearbeitet, wäre es hier nützlich, wenn man den User zwingen könnte das vorhandene zu löschen bevor ein neues Medium hochgeladen werden kann.

![bildschirmfoto 2018-11-20 um 17 31 30](https://user-images.githubusercontent.com/791247/48788302-d41d6a00-ecea-11e8-8293-8105d71bc407.png)

**Comment by skerbis** [comment]
Hat sich erledigt ✅ 
Mit eigenem theme gelöst

**Comment by alexplusde** [comment]
@skerbis möchtest du trotzdem andere an der Lösung teilhaben lassen?

Ist es nicht ohnehin so, dass hier gar kein bootstrap3-Upload eingesetzt wird, das etwas schöner aussehen würde?

**Comment by skerbis** [comment]
Ich habe in dem Template nur ne Abfrage eingebaut ob ein Bild bereits hochgeladen wurde. In diesem Fall zeige ich das Upload Feld nicht. Ich sammle das für die Tricks und zeige wie es geht zu einem späteren Zeitpunkt.
