### ISSUE TITLE
yform 3 :: be_relation :: popup keine Übergabe an widget

### ISSUE THREAD

**Issue by skerbis** [yakamara/redaxo_yform#584]
be_relation widget erhält keine Daten vom Popup nach "übernehmen" 
Safari 12
Egal ob bei multiple oder single, Fehlermeldung im Popup:

> TypeError: null is not an object (evaluating 'opener.document.getElementById(data_field_name).value = data_name')

![bildschirmfoto 2018-11-27 um 11 11 35](https://user-images.githubusercontent.com/791247/49074597-433c1680-f235-11e8-9357-f84518aa08c6.png)

**Comment by dergel** [comment]
kannst du das mit der aktuellen github version probieren ? .. ich glaube das sollte hier behoben sein ..

**Comment by skerbis** [comment]
check ;-)
