### ISSUE TITLE
YForm 3 REX_YFORM_TABLE_DATA

### ISSUE THREAD

**Issue by skerbis** [yakamara/redaxo_yform#585]
Hat sich hier was geändert?
——————————————
folgendes liefert mir kein Widget mehr egal ob widget oder listwidget

Aktuelle GitHub-Version

REX_YFORM_TABLE_DATA[id="1" table="rex_produkt" output="listwidget"]

**Comment by dergel** [comment]
genau .. andere benennung, anderes prinzip .. 

https://github.com/yakamara/redaxo_yform/blob/master/plugins/manager/lib/var_yform_dataset.php#L7

**Comment by skerbis** [comment]
Danke ;-)
