### ISSUE TITLE
YForm 3: Javascript Fehler in Chrome (cross-origin frame)

### ISSUE THREAD

**Issue by tema-web** [yakamara/redaxo_yform#586]
In Chrome bekomme ich folgende Javascript-Meldungen:

`Uncaught DOMException: Blocked a frame with origin "https://rmydomain.org" from accessing a cross-origin frame.
    at rex_retain_popup_event_handlers (https://rmydomain.org/assets/core/standard.js?buster=1543315785:143:28)
    at https://rmydomain.org/assets/addons/yform/plugins/manager/manager.js?buster=1543316385:26:1
rex_retain_popup_event_handlers @ standard.js?buster=1543315785:143
(anonymous) @ manager.js?buster=1543316385:26`

und

`Uncaught DOMException: Blocked a frame with origin "https://rmydomain.org" from accessing a cross-origin frame.
    at rex_retain_popup_event_handlers (https://rmydomain.org/assets/core/standard.js?buster=1543315785:143:28)
    at https://rmydomain.org/assets/addons/yform/plugins/manager/widget.js?buster=1543316385:31:1
rex_retain_popup_event_handlers	@	standard.js?buster=1543315785:143
(anonymous)	@	widget.js?buster=1543316385:31`

Das hat anscheinend zur Folge, dass die Option der Mehrfachauswahl popup(single) zwar geöffnet wird, aber bei klick auf "übernehmen" nichts passiert.
Habe auch die aktuelle github-version gerade erst eingeladen, aber keine Änderung. Im Safari läuft alles glatt ohne Fehlermeldung. Da funktioniert auch der Klick.

**Comment by alexplusde** [comment]
Ändert es evtl. etwas daran, ob du das Backend mit oder ohne www. aufrufst?

**Comment by tema-web** [comment]
Kann ich leider nicht sagen, die Domain ist eine Subdomain (references.mydomain.org) und wird immer ohne www aufgerufen. 
Serverseitig ist eine Umleitung von http auf https eingestellt, die Seite kann also nur mit https aufgerufen werden.

**Comment by alexplusde** [comment]
Da müsste wohl @dergel was dazu sagen...

**Comment by tema-web** [comment]
Hm, vieleicht hat sich Chrome mal wieder etwas zu stark gecached ... die Fehlermeldung gibt es heute nicht mehr. Anscheinend klappt das mit der aktuellen github-version.
