### ISSUE TITLE
showtext

### ISSUE THREAD

**Issue by polarpixel** [yakamara/redaxo_yform#59]
Die action "showtext" scheint nicht zu funktionieren.

**Comment by olien** [comment]
Hm. Bitte nochmals prüfen... 

Bei der Verwendung von Textile gibt es einen Fehler ("Class 'rex_textile' not found")

**Comment by dergel** [comment]
@olien das ist ein neues issue .. kannst du es reinlegen ?

**Comment by olien** [comment]
https://github.com/yakamara/redaxo_yform/issues/281
