### ISSUE TITLE
yform Dateiupload -> Eigener Uploadordner und Dateiprefix funktionieren nicht

### ISSUE THREAD

**Issue by kochundsimon** [yakamara/redaxo_yform#590]
Redaxo 5.6.4

Ich will über yform eine Datei uploaden mit dem Code:

###

upload|dateiupload|Dateiupload (bei mehreren Dateien empfehlen wir, diese in einen ZIP-Ordner zu packen)|1,500000|.gif,.jpeg,.png,.pdf,.zip,.doc,.docx,.xls,.xlsx,.ppt,.pptx||Die Datei ist zu klein!,Die Datei ist zu gross.,Der Dateityp ist nicht erlaubt.,Sie haben keine Datei ausgewählt.|upload|dateiupload|rex5/media/uploads|gfsupload_|

###

Die Datei wird nicht ins angegebene Verzeichnis (Berechtigung 0775) gespeichert, sondern in:

rex5/redaxo/data/addons/yform/plugins/manager/upload/rex_gfs_factoringanfrage/dateiupload

Der Dateiname wird zwar ergänzt, aber mit einer 2stelligen Zahl davor und nicht mit dem oben angegeben Präfix. In der Datenbank wird der Original-Dateiname ohne Präfix gespeichert. In der Vorversion 4.6 wurde der Dateiname korrekt in die DB und ins Verzeichnis gespeichert, z.B.      50c9611cf70a0d9e51f80c6768af6c5d_gfsupload__dateiname.pdf

**Comment by christophboecker** [comment]
Hi, Ich beziehe mich auf YForm 2.3. 

Wird der Wert für das Verzeichnis überhaupt  berücksichtigt? Ich denke: nein. 

Dazu habe ich hab testweise eine Tabelle mit Upload-Feld im Tablemanager interaktiv angelegt: man hat kein Eingebefeld und damit keine Möglichkeit, ein Präfix oder einen Pfad einzugeben. Blick in den Code für den Feldtyp bestätigt das. Und lt. "getDescription()"-Rückgabe ist das ebenfalls nicht vorgesehen. Insofern bezogen auf YForm 2.3: works as designed. Dateien werden immer im Verzeichnis 'redaxo/data/addons/yform/plugins/manager/upload/name_der_tabelle/' abgelegt. Die Nummer am Anfang des Dateinamens ist die ID des Upload-Feldes gem. Tabellendefinition. Sieht man gut im Tablemanager.

**Comment by christophboecker** [comment]
Ach ja: Die Möglichkeit zur Angabe eines selbstgewählten Verzeichnisses und Präfix würde ich sehr begrüßen.

**Comment by dergel** [comment]
Wäre ein neues Issue und ich finde ich solchen Fällen einen eigenen Symlink besser, der ist dann unabhängig von der eigenen Struktur

**Comment by alexplusde** [comment]
Auf shared hosting Paketen lassen sich symlinks nicht erstellen meines Wissens
