### ISSUE TITLE
Data slices : REX_MEDIA nicht eindeutig

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#594]
Die Id von REX_MEDIA ist mehrfach vorhanden, sodass das Medium des zweiten Slices dem ersten Slice zugewiesen wird

Hier `REX_MEDIA_40`

![screenshot 2018-12-07 13 44 02](https://user-images.githubusercontent.com/338267/49648453-2d450780-fa26-11e8-94e7-db4e80bc389a.png)

**Comment by dergel** [comment]
ist nun korrigiert:

https://github.com/yakamara/redaxo_yform/commit/5d6463c5bc910910c0d6f7bdef260050c3b51d49
