### ISSUE TITLE
Spamschutz einbauen, bestehende Felder evaluieren

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/redaxo_yform#595]
@dergel zu #565
> Möchte nochmal schauen ob das so nötig ist und eher sogar schauen, dinge wie captcha captcha_calc und dieses hier zusammenzufassen.. Sonst bläht das die Geschichte hier so auf .. deswegen erstmal auf 3.1

Ich wäre auch dafür, ein Feld zu nutzen, das viele Techniken berücksichtigt oder optional aktivierbar macht. 

Methoden siehe: https://github.com/yakamara/redaxo_yform_docs/blob/master/de_de/demo_kontakt-spamschutz.md

**Comment by dergel** [comment]
das mit beachten

https://github.com/yakamara/redaxo_yform/pull/581

**Comment by dergel** [comment]
ich finde die sollte alle zusammengefasst werden

captcha
captcha_calc
spamtimer

könnte: nospam oder so heissen.. @alexplusde was meinst du ?

**Comment by alexplusde** [comment]
spamblock
blockspam
spamfilter (mein Favorit)

**Comment by dergel** [comment]
spamfilter finde ich gut.

**Comment by dergel** [comment]
Weil deprecated Klasse wegfallen müssten erst ab 4.0

**Comment by alexplusde** [comment]
Fürs Protokoll: Wenn sich ein Sponsor findet, mache ich einen passenden PR auf Basis von https://github.com/alexplusde/yform_spam_protection mit den dort versprochenen Features, die leider dort nur zum Teil umgesetzt sind.

**Comment by alxndr-w** [comment]
Ich finde, wir haben das mit dem FOR-Addon hier gelöst.
