### ISSUE TITLE
Logout bei rex_article_content() / Redaxo 5.6.5 / yform 3.0 Beta3 

### ISSUE THREAD

**Issue by ynamite** [yakamara/redaxo_yform#596]
Bei einer One-Page Seite hole ich mir den Inhalt aller Artikel über
```
$article = new rex_article_content(1);
$content = $article->getArticle(1);
echo $content;
```
wobei der Artikel mit ID = 1 ein yform Formular beinhaltet:
```
$form->new rex_yform();
$form->setValueField('text',  array("name","Name"));
echo $form->getForm();
```

Wenn ich in Redaxo BE angemeldet bin und das Frontend aufrufe, bin ich anschliessend abgemeldet. Bin mir nicht sicher ob das ein Bug am Core ist oder an yform, dachte aber ich poste es hier.

**Comment by dergel** [comment]
ja das kann sein.. vielleicht hast du irgendwo ein Logout Formular was ausgeführt wird, oder eine Session wir gelöscht .. das müsstest du zunächst an deinen Artikeln prüfen.

kannst du das bei dir genauer debuggen ?

**Comment by ynamite** [comment]
@dergel Nein, eben geprüft, gibt nichts derartiges (ist auch eine frische Installation).

Kann das gerne genauer anschauen, müsste aber wissen wo ich anfangen soll zu suchen (yForm, Core?). Hast du denn einen Verdacht woran das liegen könnte, angenommen der Fehler liegt am Core bzw. yForm?

**Comment by alexplusde** [comment]
Das hatten wir neulich doch Mal im Slack, warst du das @ynamite oder jemand anderes?

**Comment by ynamite** [comment]
@alexplusde glaube nicht, hatte zwar mal was ähnliches vor einer ganzen Weile (mind. ein halbes Jahr her).

Wie auch immer, das Problem tritt in diesem Fall in einer frischen Install auf, ohne Session-Kram im Frontend und nur wenn `yform->getForm()` ausgeführt wird.

**Comment by dergel** [comment]
ich habe was in dieser github version verändert, was zumindest ein problem mit der session anpasst.. ob das dieses Problem löst weiss ich nicht .. kannst du es ausprobieren ?

**Comment by ynamite** [comment]
@dergel sehe keine Änderungen ... welche Datei hast du angepasst?

**Comment by dergel** [comment]
Csrf bei yorm ist nun deaktiviert und es wird keine session einfach so mehr aufgemacht

**Comment by ynamite** [comment]
@dergel Ah OK, dachte du hättest das just angepasst, quasi Minuten vor deinem Kommentar.

Hab den CSRF Fix seit heute morgen am laufen und bis jetzt gab's keine ungewollten Logouts mehr. Scheint gewirkt zu haben. Danke dir. 

Soll ich schliessen?
