### ISSUE TITLE
SQL error beim update von 3.0-beta3 auf 3.0-beta4

### ISSUE THREAD

**Issue by isospin** [yakamara/redaxo_yform#597]
`AddOn "yform" konnte aus folgendem Grund nicht aktualisiert werden:
SQL error: Error while executing statement "UPDATE `rex_yform_field` SET `format` = '' WHERE `type_name` = 'datestamp' AND `format` = 'mysql'"! SQLSTATE[42S22]: Column not found: 1054 Unknown column 'format' in 'where clause'`

**Comment by dergel** [comment]
Bestimmte automatische Korrekturen von v2 auf v3 treffen nicht überall zu. Das wird nun abgefangen. inkl. minimalen Umbau der update uns install aufrufe
