### ISSUE TITLE
Neues Tabellen-Feld hinzufügen > prio geht nicht!!!

### ISSUE THREAD

**Issue by Geri2017** [yakamara/redaxo_yform#598]
Im Table Manager > Tabellen bearbeiten > Felder editieren > hinzufügen > "prio" werden div. Fehlermeldungen ausgegeben:

> Error while executing statement "select"! SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1
#0 /kunden/XXXXXX/redaxo/src/core/lib/sql/sql.php(1065): rex_sql->setQuery('select', Array)
#1 /kunden/XXXXXX/redaxo/src/addons/yform/lib/yform/value/choice.php(302): rex_sql->getArray('select')
#2 /kunden/XXXXXX/redaxo/src/addons/yform/lib/yform/value/choice.php(22): rex_yform_value_choice::createChoiceList(Array)
#3 /kunden/XXXXXX/redaxo/src/addons/yform/lib/yform.php(283): rex_yform_value_choice->enterObject()
#4 /kunden/XXXXXX/redaxo/src/addons/yform/lib/yform.php(201): rex_yform->executeFields()
#5 /kunden/XXXXXX/redaxo/src/addons/yform/plugins/manager/lib/yform/manager.php(1181): rex_yform->getForm()
#6 /kunden/XXXXXX/redaxo/src/addons/yform/plugins/manager/pages/table_field.php(20): rex_yform_manager->getFieldPage()
#7 /kunden/XXXXXX/redaxo/src/core/lib/packages/package.php(228): include('/kunden/XXXXXX...')
#8 /kunden/XXXXXX/redaxo/src/core/lib/be/controller.php(456): rex_package->includeFile('pages/table_fie...', Array)
#9 /kunden/XXXXXX/redaxo/src/core/lib/be/controller.php(420): rex_be_controller::includePath('/kunden/XXXXXX...', Array)
#10 /kunden/XXXXXX/redaxo/src/addons/yform/pages/index.php(3): rex_be_controller::includeCurrentPageSubPath()
#11 /kunden/XXXXXX/redaxo/src/core/lib/packages/package.php(228): include('/kunden/XXXXXX...')
#12 /kunden/XXXXXX/redaxo/src/core/lib/be/controller.php(456): rex_package->includeFile('pages/index.php', Array)
#13 /kunden/XXXXXX/redaxo/src/core/lib/be/controller.php(403): rex_be_controller::includePath('/kunden/XXXXXX...')
#14 /kunden/XXXXXX/redaxo/src/core/backend.php(155): rex_be_controller::includeCurrentPage()
#15 /kunden/XXXXXX/redaxo/src/core/boot.php(136): require('/kunden/XXXXXX...')
#16 /kunden/XXXXXX/redaxo/index.php(9): require('/kunden/XXXXXX...')
#17 {main}

Hat jemand eine Idee?
Danke :-)

++++++++++++++++++++++++
REDAXO: 5.6.5
PHP: 7.2.11
yform | 3.0-beta2

**Comment by dergel** [comment]
Welche Version ? Hast du es mit der aktuellen Version hier auf github probiert. Sollte meines Erachtens damit gehen. Leider hilft mir diese Fehlermeldung so nicht weiter.. Ich müsste wissen wir der Aufruf war und was für ein Query rausgekommen ist .. das sieht man meistens rechts in der Fehlermeldung,

Aber wie gesagt .. die aktuelle Version sollte gehen. gerne Feedback hier reinlegen

**Comment by alexplusde** [comment]
Sieht eher aus, als wäre das SQL im Choice-Feld falsch

**Comment by dergel** [comment]
oja.. ein ganz anderes Problem und sehr wahrscheinlich YForm Problem
