### ISSUE TITLE
Table Manager: Tabellenschema überschreiben: NULL erlauben

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#599]
Wenn ich `Datenbankfelder IMMER mit Schemadefinition überschreiben` aktiviere, darf ich nicht mehr NULL in die Datenbank schreiben, weil dies von der Schemadefinition verweigert wird.

NULL wird allerdings vom SQL-Objekt versucht zu schreiben, wenn ich einen leeren String übergeben möchte:

```
        $sql = rex_sql::factory()->setDebug(0);
            $sql->setTable('rex_test');
            $sql->setValue('name', $name);
            $sql->setValue('name2',""); // wird zu NULL, statt leerem String
            $sql->insert();
``` 

Hier sollte ein leerer Wert und nicht null eingetragen werden oder alternativ NULL erlaubt werden.

**Comment by dergel** [comment]
ich habe das getestet und kann es nicht nachvollziehen. muss irgendeine andere Problematik sein, oder eine andere Konstellation. ich schliesse mal bis das klarer ist .. ich teste immer mit aktueller github yform und auch github redaxo (im moemnt 5.7)

**Comment by alxndr-w** [comment]
https://github.com/yakamara/redaxo_yrewrite/issues/364 hier war / ist ein weiteres Problem, dass man NULL nicht gezielt für Felder/Tabellen erlauben kann, ich bin heute erst wieder darübergestolpert.
