### ISSUE TITLE
Plugin: Setup: Fehlermeldung: Die package.yml fehlt!

### ISSUE THREAD

**Issue by olien** [yakamara/redaxo_yform#6]
PlugIn setup konnte aus folgendem Grund nicht installiert werden:
Die package.yml fehlt!

--
Aktuelle Version von github

**Comment by gharlan** [comment]
Scheinbar Überreste, denn das Plugin existiert nicht mehr: https://github.com/yakamara/redaxo_yform/tree/master/plugins

**Comment by olien** [comment]
Danke
