### ISSUE TITLE
ycom_auth_password / ycom_auth_password_hash

### ISSUE THREAD

**Issue by polarpixel** [yakamara/redaxo_yform#60]
Links steht das eine, rechts das andere, siehe Screenshot. Welches ist korrekt?
![2016-04-30_15-33-00](https://cloud.githubusercontent.com/assets/330160/14936154/eeaf569a-0ee8-11e6-840c-7bcc32021c17.png)

**Comment by dergel** [comment]
gehört zu ycom und ist dort mittlerweile behoben. ycom_auth_password ist richtig
