### ISSUE TITLE
3.0beta: Checkbox ist nicht rückwärts kompatibel

### ISSUE THREAD

**Issue by dtpop** [yakamara/redaxo_yform#601]
Die Checkbox v2 hatte `name|label|values|default|no_db`
Die Checkbox v3 hat  `name|label|default|no_db|attributes`

**Comment by alexplusde** [comment]
wenn rückwärtskompatibel, dann vlt gleich so beschreiben:
`name|label|1|default|no_db|attributes`

**Comment by tbaddade** [comment]
Beim Value `checkbox` braucht man keine `values` mehr zu notieren und die Position entfällt. Daher muss man m.E. die Pipenotation zwingend anpassen.

> Checkbox ist nicht rückwärts kompatibel

muss es denn das?

**Comment by dergel** [comment]
muss nicht, aber was man in der install oder update anpassen kann, sollte man anpassen

**Comment by dergel** [comment]
die veränderung ist da und im manager muss man das nicht anpassen, Feld fehlt dann ja einfach.. In den Formulare muss man das leider selbst machen.

Würde mich freuen wenn jemand die Zeit findet, diese Infos zu sammeln und in der Changelog als Extra Punkt aufzunehmen.
