### ISSUE TITLE
Table Manager: Feldlöschung wird auf alle YForm-Tabellen angewendet

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#603]
Sollte aber aus dem Dialog heraus eigentlich nur die aktuell gewählte Tabelle aktualisieren, nicht alle YForm-Tabelle.

So kann es passieren, dass Felder in anderen YForm-Tabellen gelöscht werden, die aber evtl. gar nicht gelöscht werden sollten.

**Comment by dergel** [comment]
sollte nun passen.. vorher wurde immer alle Tabellen auf einen Schlag verarbeitet - bei alle Aktionen..  das ist nun korrigiert.. gerne gegentesten
