### ISSUE TITLE
Problem mit dem Autoloader

### ISSUE THREAD

**Issue by christophboecker** [yakamara/redaxo_yform#608]
Bin grade - mal wieder - an den Punkt gekommen, dass sowohl FE als auch BE nichts mehr zur Anzeige brachten. Also nichts. Gar nichts. 

Im System-Log war keine Meldung, aber das PHP-Log vom Server brachte mich auf die Spur des Autoloaders. autoload.cache von Hand gelöscht und die Kiste lief wieder.

Ist das ein bekannter Effekt? Gibt es ein Hilfsmittel, könnte es ein Bug sein?

**Comment by alexplusde** [comment]
Cache gelöscht?

**Comment by christophboecker** [comment]
siehe oben :-)

**Comment by alexplusde** [comment]
Beim Querlesen sehe ich `autoload.cache` nicht. :D 

Du kannst auch nicht eingrenzen, wann das passiert? Änderst du dort evtl. gerade etwas in einer Klasse in einem Addon oder im Theme-Verzeichnis?

**Comment by christophboecker** [comment]
Zweiter Absatz, zweiter Satz: _"autoload.cache von Hand gelöscht und die Kiste lief wieder."_.

Und ja, das war natürlich beim Coden. Es lief ungefähr so ab:
- Code geändert, Ctrl-R im Browser, Whoops 
- Code geändert, Ctrl-R im Browser, Whoops 
- Code geändert, Ctrl-R im Browser, leere Seite
- Das kennst Du doch .... zuletzt vor x Monaten?
- Im anderem Tab und in anderem Browser FE und BE geprüft, aber da wurde auch nichts angezeigt, also kein Browser-Thema.
- Redaxo-Log prüfen; keine Meldung
- PHP-Log prüfen: _"PHP Fatal error:  Uncaught Error: Class 'rex' not found in ... autoload.php"_; Beginnt des Trace mit "/redaxo/src/core/boot.php(66): spl_autoload_call('rex_url')"
- autoload.cache gelöscht, Ctrl-R im Browser, Seite ist wieder da.

In den letzten 1,5 Jahren ca. vier mal passiert.

**Comment by alexplusde** [comment]
Und weshalb ist das ein yform-Problem?

**Comment by alexplusde** [comment]
https://github.com/redaxo/redaxo/pull/2201

**Comment by christophboecker** [comment]
Guter Punkt: weil ich in meiner Linkliste den falschen Link ausgewählt habe; Redaxo und YForm stehen direkt untereinander. Kann man Issues verschieben. Sonst mache ich hier zu und ein neues Issuue unter redaxo auf.

**Comment by tbaddade** [comment]
> Kann man Issues verschieben?

Ja, aber nur von Repo zu Repo und nicht von Orga/user zu einem anderen.

**Comment by dergel** [comment]
woher weisst du das es mit yform zu tun hat ? .. Gingen alle anderen Seiten die ohne Formular waren ?
Warst du im Backend eingeloggt aber hast auch keine Fehlermeldung (Whoops) im Frontend bekommen ?

**Comment by christophboecker** [comment]
Hallo Jan, siehe oben. Fälschlich in yform geöffnet. Alex hat das hier schon in ein geeignetes redaxo-Issue verlinkt. Ich mache dieses Issue jetzt zu; der Link bleibt ja bestehen.
