### ISSUE TITLE
checkbox default wird ignoriert? (3.0-beta6)

### ISSUE THREAD

**Issue by elektromanager** [yakamara/redaxo_yform#609]
Bin grad am verzweifeln... Seit dem Update auf die beta6 bekomme ich die Checkbox im Formular nicht mehr ans laufen. Egal was ich als Defaultwert eingebe, die Box ist immer angehakt.

Felddefiniton:
checkbox|checkme|Lorem ipsum sit amet|0|[no_db]|[notice]

Ergebnis:
Checkbox ist angehakt.

Felddefiniton:
checkbox|checkme|Lorem ipsum sit amet|1|[no_db]|[notice]

Ergebnis:
Checkbox ist angehakt.

Versteh ich da was an der Syntax falsch?

**Comment by alexplusde** [comment]
Siehe https://github.com/yakamara/redaxo_yform/issues/601,

**Comment by dergel** [comment]
#601 erklärt eigentlich nur das Format, was hier aber richtig ist.

ich habe exakt die obere Definition genommen und es klappt bei mir ..

**Comment by dergel** [comment]
ich schliess das mal .. wenn das bei noch jemandem passiert, bitte unbedingt melden.

**Comment by alexplusde** [comment]
@elektromanager melde dich gerne im REDAXO Slack-Channel bei mir, wenn du Unterstützung brauchst. Du weißt, wo/wie?
