### ISSUE TITLE
YForm 3.0beta6: datetime-Feld - "mysql" entfernen

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#613]
Durch das Update ändert sich laut Changelog:

> datestamp: wird nun als datetime gespeichert. format nun für Anzeige, nicht mehr als Speicherformat

Dann bitte "mysql" im Table Manager (und ggf. auch sonstwo) ersatzlos löschen, wenn in der Felddefinition das Format "mysql" auftaucht. Sonst wird ein vollkommen verrücktes Datum ausgegeben (m für Monat, y als Jahreszahl, s für Sekunden, q als Buchstabe, l für den Wochentag), macht `121841qWednesday`

Anregung: In der Notice auf http://php.net/manual/de/function.date.php verlinken, damit die Parameter klar sind.

**Comment by dergel** [comment]
mit mysql passiert hier: https://github.com/yakamara/redaxo_yform/blob/master/update.php#L39
Wegen Date und Notice finde ich gut .. haeb ich entsprechend ergänzt: https://github.com/yakamara/redaxo_yform/commit/d52aaed1959e52ce0a2eb488a13a86e73181374d
