### ISSUE TITLE
DX: Zwischen Felddefinition, Datensätzen und Co. springen

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#614]
Aktuell gibt es keine direkte Möglichkeit, in der Felddefinition wieder auf die Datensätze zu springen.

![image](https://user-images.githubusercontent.com/3855487/50383062-df2e3600-06ac-11e9-96c6-af0b440157ab.png)

Potenziell hätte es hier Platz dafür.

**Comment by dergel** [comment]
ich finde das auch nervig.. man sollte zwischen:
Felddefinitionen, Datensätzen und Tabelle springen können

Habe noch keinen Ansatz wie das am besten aussehen könnte. In der Datensatzansicht ist das bereits ok.. lässt sich nur nicht so adaptieren.

**Comment by alexplusde** [comment]
Da hätte ich Vorschläge, Entwurf gewünscht?

**Comment by dergel** [comment]
gerne.. am liebsten bei Tabellenedit und Felderedit gleich - irgendwie :)

**Comment by dergel** [comment]
ist nun nicht wunderschön gelöst, aber schonmal sinnvoller.. Gerne in einzelnen Issues/PR dann Anpassungen
