### ISSUE TITLE
Table Manager: Suche und Funktionen nehmen zu viel Platz weg

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/redaxo_yform#615]
![image](https://user-images.githubusercontent.com/3855487/50383086-2ae0df80-06ad-11e9-8427-ce66510c2824.png)

Mit Menü, aktivierter Suche und allen Features werden mehr als die Hälfte der Ansicht an andere Dinge verschwendet als den eigentlichen Datensätzen. Manchmal ist es jedoch notwendig, möglichst viele Daten in der Übersicht anzuzeigen.

Könnte man editieren, löschen, Historie und duplizieren (yform_usability) sowie Status (yform_usability) sinnvoller unterbringen und die Suche togglen? (ich habe jetzt auch keine Idee, wie)

**Comment by christophboecker** [comment]
My 2 cent: Die Funktion "editieren" ist m.E. überflüssig weil doppelt zur 1. Spalte. Ich werfe stets  "editieren" und ID per EP YFORM_DATA_LIST sofort raus. Wenn es irgendwo eine Wahlmöglichkeit gäbe - auch beim Text (nur Symbol oder Symbol und Text) wäre das auch schon hilfreich. Evtl ließe sich das per CSS regeln?

**Comment by dergel** [comment]
irgendwas müssen wir da machen .. ich finde auch, dass der overhead zuviel PLatz wegnimmt.

**Comment by christophboecker** [comment]
<img width="441" alt="grafik" src="https://user-images.githubusercontent.com/10065904/50925158-c4501580-1451-11e9-9075-1a74e4248d78.png">

und 

<img width="314" alt="grafik" src="https://user-images.githubusercontent.com/10065904/50925177-d467f500-1451-11e9-99af-27cb7b780e06.png">

**Comment by dergel** [comment]
an sich gut, ich dachte aber eher an sowas wie "Layout" welches man sich bei jeder Tabelle entsprechend aussuchen kann..

**Comment by dergel** [comment]
im ersten Schritt ist das erstmal als yform/manager fragement grid extrahiert und nun veränderbar über den EP YFORM_DATA_LIST

**Comment by tbaddade** [comment]
**Alternative** https://wikiki.github.io/components/quickview/
Klick auf  `Show quickview`

**Comment by dergel** [comment]
Ich würde behaupten, dass man mit den nun vorhandenen Änderungen das locker selbst einbauen kann.

**Comment by dergel** [comment]
ich würde das gerne hier weiter abwickeln. https://github.com/yakamara/redaxo_yform/issues/1096
