### ISSUE TITLE
no_db umbenennen und anpassen

### ISSUE THREAD

**Issue by dergel** [yakamara/redaxo_yform#617]

**Comment by dergel** [comment]
nur wie soll ich das nennen .. ignoreField, ignoreSave, no_save.

**Comment by alexplusde** [comment]
`invisibleForDb` (my 2 cents)

**Comment by DanielWeitenauer** [comment]
transient, dont_store?

**Comment by dergel** [comment]
ignoreField 
ignoreSave
no_save
transient
dont_store
invisibleForDb
hiddenForDb
no_db

puhh.. oder einfach lassen.. mich stört nur sehr, dass es no_db = no_db ist und das alles dadurch so verwirrend ist.. geschweige denn, dass kaum jemand das nutzt (glaube ich)

**Comment by alexplusde** [comment]
hat sich da was verändert? in der aktuellen beta wird der Parameter no_db ignoriert.

**Comment by dergel** [comment]
ich denke nicht .. aber prüfe ich eh nochmal ..

**Comment by tbaddade** [comment]
Vorschlag wegen Umbenennung

`save=true` - `save=1` wäre default
`save=false` - `save=0`

via PHP sehe es so aus
```
$form->setValueField('text', ['title', 'Titel', 'save' => false]);
```

**Comment by dergel** [comment]
"save" ich glaube das finde ich gut .. trotzdem als letzte Überlegung.. Im Prinzip wird ja nichts gesaved, sondern nur der Wert in den sql pool geschmissen.. vielleicht findet sich da eine gute Idee.. Ansonsten dann "save" :)

**Comment by dergel** [comment]
das thema ist leider zu umständlich und dann nicht mehr BC.. deswegen habe ich mich bei der 3.0 dazu entschieden, dass zu lassen, aber zu vereinfachen. Jetzt geht es wieder und no_db reagiert nun auf "no_db",1,"1",true ..

**Comment by IngoWinter** [comment]
saugeil. ich bin jedesmal darüber gestolpert, dass ich `no_db` statt `1` schreiben musste :thumbsup:
