### ISSUE TITLE
showvalue - Value formatieren können

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#618]
Bsp. Datumsfelder die lesbar sind, werden aktuell YYYY-MM-DD ausgegeben.

**Comment by alexplusde** [comment]
@tbaddade die Ausgabe-Anforderungen können so unterschiedlich sein. Wäre es nicht einfacher, dafür sein eigenes value-Feld zu erstellen? Oder genügt es vielleicht, das show_value-Fragment überschreiben zu können?

**Comment by tbaddade** [comment]
Ich schließe, da es vermutlich niemand anderes als Jan machen wird. Zudem hat @alexplusde eine Alternative aufgezeigt.
