### ISSUE TITLE
Tabellenfelder als Gruppe kopieren

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#62]
Hab grad aktuell den Fall das der Aufbau sich sehr ähnelt

```
feld_a_text_1
feld_a_bilder_1
feld_a_raster_1
feld_a_text_2
feld_a_bilder_2
feld_a_raster_2
...
feld_n_text_1
feld_n_bilder_1
feld_n_raster_1
feld_n_text_2
feld_n_bilder_2
feld_n_raster_2
```

**Comment by tbaddade** [comment]
Kopieren eines einzelnes Feldes würde auch schon helfen.

**Comment by dergel** [comment]
denke ist nicht nötig. wären eher seltenere einzelne Fälle, denke ich

**Comment by tbaddade** [comment]
Ein Feld zu kopieren fänd ich gut, allein bei Mehrsprachig würde das helfen.

**Comment by dergel** [comment]
kopieren ansich - ja .. issue
