### ISSUE TITLE
Debug-Modus erweitern

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#621]
der Debug-Modus kann meines Wissens im Moment nur Infos zu SQL-Befehlen ausgeben. Vielleicht wäre es möglich, zusätzliche Infos (Post-Parameter, etc.) hier auszugeben.

**Comment by alexplusde** [comment]
Wird der beschriebene Anwendungsfall durch das debug-Addon gelöst? @bloep

**Comment by bloep** [comment]
> Wird der beschriebene Anwendungsfall durch das debug-Addon gelöst? @bloep 

Das Debug-AddOn zeigt dir alle SQL Queries und auch POST und GET Parameter an. Oder brauchst du hierfür mehr?

**Comment by alexplusde** [comment]
Gute Frage. Ich denke, das kann ich nur beantworten, wenn ich es akut brauche. Glaube aber, dass man mit dem Debug-Addon da generell weiter kommt und nichts Eigenes in YForm benötigt.
