### ISSUE TITLE
YForm 3.0beta7: upload-Feld defekt?

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#622]
Das Upload-Feld scheint in der aktuellen beta nicht ordnungsgemäß zu funktionieren, in beta3 tat es das noch.

edit: Als Fehlermeldung wird dann "Die Datei wurde nicht angehängt." ausgegeben.

**Comment by tbaddade** [comment]
Wie sieht es mit der 3.0beta7 aus?

**Comment by alexplusde** [comment]
Mein Fehler, Kollege hatte bereits auf 3.0beta7 geupdatet. gleiches Problem.

evtl. hat es was mit diesem Commit zu tun?
https://github.com/yakamara/redaxo_yform/commit/1bf34bf36dbb82e03205ac5a3dfa06d5084629a9

**Comment by alexplusde** [comment]
https://github.com/yakamara/redaxo_yform/commit/1bf34bf36dbb82e03205ac5a3dfa06d5084629a9#diff-bf54cdf5fabd5561ad7238f9b39ce4e0R72

Die Zeile war schon mal keine gute Idee. Hier kommt für delete immer true raus, da als Rückgabewert 
`$this->params['this']->getFieldValue($this->getName(), ['delete', $this->getId()])` hier die ID drin steht und nicht der Wert der Checkbox, ob die Datei gelöscht werden soll oder nicht.

Kommentiere ich sich aus, kommt der nächste Fehler: `Unzulässigen Dateityp gewählt.`

**Comment by alexplusde** [comment]
Es gibt auch weitere Fehler, z.B. die Darstellung des Dateinamens:

![image](https://user-images.githubusercontent.com/3855487/50837568-40683180-135c-11e9-9c7f-90751b014f0f.png)

oder

![image](https://user-images.githubusercontent.com/3855487/50837579-465e1280-135c-11e9-8a83-67384b75775d.png)

Hier werden nicht die richtigen Dateinamen, sondern manchmal der unique-Wert oder eine 1 ausgegeben.

**Comment by steri-rex** [comment]
hänge mich hier dran - bei funktioniert der upload auch nicht

**Comment by alexplusde** [comment]
@steri-rex hast du den Patch von @lexplatt getestet?

**Comment by steri-rex** [comment]
@alexplusde - nein wo finde ich den patch?

**Comment by alexplusde** [comment]
#629

**Comment by steri-rex** [comment]
@alexplusde danke - ja der patch funktioniert; d.h. der Upload funktioniert nun. Lediglich die Fehler der Darstellung des Dateinamens (was du oben beschrieben hast) ist noch da

**Comment by dergel** [comment]
sollte nun wieder passen.

**Comment by steri-rex** [comment]
leider funktioniert der upload im frontend nach update auf yform beta8 wieder nicht.
das file wird ignoriert - feld bleibt leer und es passiert kein upload
(mit yform beta 7 und Patch von @lexplatt hatte zumindest der upload des files funktioniert)

**Comment by steri-rex** [comment]
momentan hab ich noch gar keine DB - möchte das per E-Mail senden. Bzw. sollte der Upload ja in redaxo/data/addons/yform/plugins/manager/upload/frontend/ gespeichert werden.
Meine PHP Notation sieht so aus:
```
<?php
$yform = new rex_yform();

$yform->setDebug(TRUE);

$yform->setObjectparams('real_field_names', true);

$yform->setObjectparams('form_name', 'application_form');
$yform->setObjectparams('form_action',rex_getUrl('REX_ARTICLE_ID'));
$yform->setObjectparams('form_ytemplate', 'bootstrap');
$yform->setObjectparams('form_showformafterupdate', 0);

$yform->setObjectparams('form_wrap_id','veranstaltung_anmeldung');
$yform->setObjectparams('form_anchor','veranstaltung_anmeldung');

$yform->setValueField('text', array('name_org','Organisation','','','{"placeholder":"Organisation"}'));
$yform->setValidateField('empty', array("name_org","Organisation leer"));

$yform->setValueField('upload', array('trainer_cv','Upload CV','1,50000','.pdf,.doc,.docx','0','','','',''));

$yform->setActionField('tpl2email', array('application_form', '', 'mail@doamin.de'));

$yform->setValueField('php', array('php_attach','Datei anhängen','<?php if (isset($this->params[\'value_pool\'][\'files\'])) { $this->params[\'value_pool\'][\'email_attachments\'] = $this->params[\'value_pool\'][\'files\']; } ?>'));

echo $yform->getForm();
?>
```
Im E-mail Template "application_form" steht nur Organistion: REX_YFORM_DATA[field="name_org"] im Body

**Comment by dergel** [comment]
von @steri-rex bestätigt das es läuft
