### ISSUE TITLE
validate customfunction - Rückgabewerte sind verwirrend

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#623]
Hier ein Beispiel

```php
class Validator
{
    public static function isEighteen($label, $value, $parameter, $_this)
    {
        $birthday = new \DateTimeImmutable($value);
        if ($birthday->diff(new \DateTimeImmutable())->y >= 18) {
            // ist 18, false zurückgeben damit das Datum als richtig gewertet wird.
            return false;
        }

        // true, da keine 18
        return true;
    }
}
```

siehe auch die [Doku](https://github.com/yakamara/redaxo_yform_docs/blob/b8ec5bdcc8d83cac25564231aad24cd12d946bb8/de_de/table_manager_validierungen.md#beispiel-für-customfunction)

**Comment by alexplusde** [comment]
Du meinst, dass true bedeutet, den Fehler auszugeben und false bedeutet, dass alles ok ist?

**Comment by tbaddade** [comment]
Genau. Aktuell bedeutet `true` > gebe die Fehlermeldung aus
Da aber der Wert validiert wird, fände ich es sinnvoll zu sagen, der Wert ist ok also > true

**Comment by gharlan** [comment]
Sehe ich genauso. Allerdings würde ich glaube ich nicht die vorhandene Validierung so ändern, sondern wenn die als deprecated markieren, und eine neue einführen, die sich andersrum verhält. zum beispiel "callback".

**Comment by alexplusde** [comment]
Das ist bei allen Validierungen so, nicht nur in der `customfunction`.

**Comment by alexplusde** [comment]
(Und ich bin da ganz bei euch, dass das eigentlich anders gehört. Ich war derjenige, der das Beispiel in der Doku geschrieben hat und die Kommentare dazu notiert hat, weil ich es super verwirrend finde :D)

**Comment by tbaddade** [comment]
> zum beispiel "callback".

Finde ich gut und passt zu den REX-Vars

**Comment by gharlan** [comment]
> Das ist bei allen Validierungen so, nicht nur in der `customfunction`.

In den Validierungsklassen hat man doch diese Logik:

```php
if (isNotValid()) {
    $this->params['warning_messages'][$Object->getId()] = 'message';
}
```

Das finde ich logisch, und wüsste auch nicht wie man es dort ändern könnte.
Aus meiner Sicht betrifft es also nur die customfunction.

**Comment by alexplusde** [comment]
Besteht Interesse, die Erklärung noch für 3.1 auszubauen? Hier zur Erinnerung ein Beispiel, wie es richtig ist:

Wenn Bedingung erfüllt, dann Fehlermeldung:

![image](https://user-images.githubusercontent.com/3855487/56034408-85b74900-5d27-11e9-894a-5042cc2666de.png)

**Comment by dergel** [comment]
weiter gehts hier #1380
