### ISSUE TITLE
3.0beta7 - Tablemanager umbenennen einer Tabelle gibt Fehler

### ISSUE THREAD

**Issue by dtpop** [yakamara/redaxo_yform#624]
Umgebung: Redaxo 5.6
Yform über Installer upgedated
Tabelle wurde migriert
Beim Umbenennen gibt es einen wiederholbaren nachvollziehbaren Fehler:

Vielen Dank fuer die Eintragung
ErrorCode - InsertQueryError

Error while executing statement "UPDATE `rex_yform_table` SET `status` = :status, `prio` = :prio, `name` = :name, `description` = :description, `search` = :search, `hidden` = :hidden, `history` = :history, `schema_overwrite` = :schema_overwrite, `export` = :export, `import` = :import, `mass_deletion` = :mass_deletion, `mass_edit` = :mass_edit, `list_amount` = :list_amount, `list_sortfield` = :list_sortfield, `list_sortorder` = :list_sortorder WHERE id=1" using params {"status":"1","prio":"1","name":"Neuer Name","description":"","search":0,"hidden":0,"history":0,"schema_overwrite":"1","export":0,"import":0,"mass_deletion":0,"mass_edit":0,"list_amount":"50","list_sortfield":"id","list_sortorder":"ASC"}! SQLSTATE[42S22]: Column not found: 1054 Unknown column 'schema_overwrite' in 'field list'

**Comment by dtpop** [comment]
Das Feld schema_overwrite hat in der rex_yform_table gefehlt. Nachdem ich das Plugin reinstalliert habe, war das Feld dann da.

**Comment by christophboecker** [comment]
Kann ich bestätigen. Table-Manager aufgerufen, Tabelle editieren, Speichern. Rumms. Plugin "manager" reinstalliert und es lief.

Das Problem ist in "update.php" des managers. Dort wird die "install.php" mit dem Befehl 
```
include $this->getPath('install.php');
```
aufgerufen. Damit landet man aber bei der schon installierten Vorversion. Wahrscheinlich muss es so ähnlich richtig sein: 
```
include (__DIR__ . '/install.php');
```

**Comment by dergel** [comment]
sollte behoben sein .. gerne bei beta8 nochmal testen
