### ISSUE TITLE
eingabe bei value feld date und time wird im backend nicht übernommen

### ISSUE THREAD

**Issue by steri-rex** [yakamara/redaxo_yform#630]
Verwende das aktuelle yform3 beta7 bzw. hab die aktuelleste version von github am 08.01.19 gezogen.
Bei mir werden Eingaben im Backend beim value feld date und time nicht übernommen. Nach dem Speichern bleibts immer auf 00:00 bwz. beim Datum auf -- -- ----

![time_date](https://user-images.githubusercontent.com/3844106/51190352-59379080-18e2-11e9-8acf-70a02cee2956.png)

**Comment by alexplusde** [comment]
kann ich bestätigen, gibt auch im Frontend mit dem date-Feld deshalb Probleme.

**Comment by tbaddade** [comment]
Ich vermute, dass ist der dazugehörige Commit https://github.com/yakamara/redaxo_yform/commit/1926eef58094f84ea68c4bd5c499fad24ad69fad

Gerne schließen, wenn es mit der GH Version oder der nächsten beta funktioniert

**Comment by steri-rex** [comment]
bei der Uhrzeit gibt es doch noch ein Problem - es wird nicht richitg gespeichert
z.b. 16:45 wird als 06:00 gespeichert
oder 17:45 wird als 17:05 gespeichert

**Comment by dergel** [comment]
Kann ich leider nicht nachvollziehen. Habe es genauso getestet.. ich mache sowieso gleich eine neue beta.. beta8 .. damit dann onchmal testen bitte

**Comment by steri-rex** [comment]
nun mit beta8 getestet - selbes Problem - allerdins macht es einen unterschied ob man HH:ii:ss oder HH:ii als Format verwendet - nur bei Format HH:ii tritt das Problem auf

**Comment by tbaddade** [comment]
Kannst du einen Screenshot von der Editmaske des Feldes machen. Dann erkennt man ob du noch anderes eingestellt hast (Formate, Widget etc.).

**Comment by steri-rex** [comment]
![format](https://user-images.githubusercontent.com/3844106/51621383-b1027700-1f34-11e9-87a1-509333c9af1b.jpg)

**Comment by steri-rex** [comment]
könntet ihr bitte mal testen ob sich dies so für euch nachvollziehen lässt und ggfs. issue wieder öffnen  - danke

**Comment by tbaddade** [comment]
> könntet ihr bitte mal testen ob sich dies so für euch nachvollziehen lässt und ggfs. issue wieder öffnen 

Ich habs eben getestet und konnte keinen Fehler nachstellen.
`16:45` landet in der Datenbank als `16:45:00`

Hat das DB-Feld `TIME` als Typ?

**Comment by steri-rex** [comment]
ja ist time

**Comment by steri-rex** [comment]
das problem dürfte erst beim bearbeiten - nicht bei einem neu eintrag entstehen

**Comment by tbaddade** [comment]
> das problem dürfte erst beim bearbeiten - nicht bei einem neu eintrag entstehen

Ich kann nichts nachstellen. Bei mir wird die Uhrzeit immer korrekt gespeichert.

Wo gibst du die Uhrzeit ein? (Frontend, via PHP oder YForm-Tabelle)
Welche PHP, REDAXO und YForm Version nutzt du?
