### ISSUE TITLE
upload value - über frontend in manager/upload/tabelle/spalte ordner speichern

### ISSUE THREAD

**Issue by steri-rex** [yakamara/redaxo_yform#634]
moment ist es so dass wenn man upload value im frontend einsetzt die datei im ordner 
manager/upload/frontend
und
wenn man upload value im backend einsetzt die datei im ordner 
manager/upload/tabellen_name/spalte_name
gespeichert wird.

soweit so gut.
nun wäre es total genial wenn man den upload im frontend nutzt und das formular in eine DB/tabelle speichert der upload auch in manager/upload/tabellen_name/spalte_name
landet und nicht mehr im frontend.
Weil dann hätte man im Backend in der Tabellen Übersicht auch die Möglichkeit das File runter zu laden.

getestet mit yform 3 beta9

**Comment by alexplusde** [comment]
Generell könnte es wünschenswert sein, mehr Kontrolle über den Zielpfad zu bekommen.

**Comment by dergel** [comment]
@steri-rex war das vorher so, dass die Dateien im backend Ordner gespeichert wurden, wenn im Frontend ein Eintrag in eine Tabelle gemacht wurde ?

**Comment by steri-rex** [comment]
@dergel man konnte den Ordner angeben wo die Dateien gespeichert werden sollen

**Comment by steri-rex** [comment]
für mich persönlich muss es nicht möglich sein den Ordner wählen bzw. angeben zu können wohin das File gespeichert wird. Das war nur bis jetzt so in yform 2.

Aber was meinst Du zu dem das wenn im Frontend in eine Tabelle gespeichert wird der Zielordner des Files nicht manager/upload/frontend (das sollte nur der Zielordner sein wenn in keine Tabelle gespeichert wird) sein sollte sondern der Zielordner manager/upload/tabellen_name/spalte_name sein sollte - das wäre schon sinnvoll oder? Dann würde auch der Download im Backend klappen - 
zur besseren Erklärung:
![upload_pfad](https://user-images.githubusercontent.com/3844106/51899484-63ae5b80-23b3-11e9-8f15-b02266bca88a.png)

**Comment by dergel** [comment]
genau .. das ist dieses issue und muss noch gelöst werden :)

**Comment by dergel** [comment]
hmm.. eigentlich müsste es bereits funktinieren.. sobald objparams main_table gesetzt ist, und der datensatz angelegt wird und dadurch die main_id gesetzt wird, ist die datein im richtigen ordner.

@steri-rex kannst du das nochmal gegentesten ?

**Comment by alexplusde** [comment]
@steri-rex kannst du das hier in die Doku zum Upload-Feld übernehmen:

> sobald objparams main_table gesetzt ist, und der datensatz angelegt wird und dadurch die main_id gesetzt wird, ist die datein im richtigen ordner.

(falls noch nicht drin)

**Comment by dergel** [comment]
issue ist dann durch, oder ?
