### ISSUE TITLE
REST API fertigstellen

### ISSUE THREAD

**Issue by dergel** [yakamara/redaxo_yform#635]
daran orientieren:

https://jsonapi.org/format/
https://demo.api-platform.com

**Comment by dergel** [comment]
GET sollte gut klappen.

POST, PUT, PATCH, DELETE noch überarbeiten

**Comment by alexplusde** [comment]
Kannst du minimale Beispiele für eine Tabelle aufführen?

**Comment by dergel** [comment]
Was meinst du ? .. in der Doku habe ich den Init erklärt.. ein Aufruf mit GET bekommt man hin, indem man einfach die URL/den Endpoint aufruft.. Für die anderen Varianten am besten Postman nutzen

**Comment by dergel** [comment]
das wird nun nach und nach erweitert werden. Zunächst war der Schwerpunkt beim Auslesen der Daten. Das sollte passen. Der Rest kommt bei 3.1

**Comment by dergel** [comment]
post und delete nun verbessert drin.

diverse Optimierungen wegen relations und post noch nötig. update/post angleichen und entsprechend variieren

**Comment by dergel** [comment]
swagger-ui
Schnittstelle anzeigen ?

**Comment by olien** [comment]
Hier wäre ein einfaches Beispiel schön...

**Comment by dergel** [comment]
Am liebsten sowas in der Art: https://swagger.io/tools/swagger-ui/

**Comment by dergel** [comment]
Einschränkenden Zugriff noch definieren können. Im Moment kann jeder mit API auf alle Endpoints zugreifen, entsprechend einschränken

**Comment by eaCe** [comment]
Können wir die return-Values der API irgendwie beeinflussen? 
Leider sieht es nicht danach aus. Ich würde gerne bei gewissen Post-Requests nicht nur die ID sondern auch das Update-Ergebnis zurück erhalten. 
Wäre ein EP an dieser Stelle angebracht oder sollte man das auf eine andere Art angehen? 
Ich werde es für mich nun erst mal via EP hotfixen.

**Comment by eaCe** [comment]
Hierzu zwei Vorschläge: 

EP (https://github.com/yakamara/redaxo_yform/blob/master/plugins/rest/lib/rest/route.php#L349):
```php
$returnValues = rex_extension::registerPoint(new rex_extension_point('YFORM_POST_RESULT', [
    'id' => $dataset->getId(),
    'table_name' => $table->getTableName(),
]));

rex_yform_rest::sendContent($status, $returnValues);
```

Callback:
In der Route

```
'post' => [
    'fields' => [
        'Class' => [
            'fieldnamea',
            'fieldnameb',
        ],
    ],
    'callback' => '\Class::resultCallback'
],
```

In `rex_yform_rest_route`:
```php
/**
 * @return string|false
 * @throws rex_api_exception
 */
public function getCallback(string $type = 'get')
{
    if (!isset($this->config[$type]['callback'])) {
        return false;
    }

    if (!is_callable($this->config[$type]['callback'])) {
        throw new rex_api_exception('Problem with Config: Provided callback is not callable');
    }

    return $this->config[$type]['callback'];
}
```

https://github.com/yakamara/redaxo_yform/blob/master/plugins/rest/lib/rest/route.php#L289:
```php
$callback = $this->getCallback('post');
```

https://github.com/yakamara/redaxo_yform/blob/master/plugins/rest/lib/rest/route.php#L349:
```php
if($callback) {
    $returnValues = call_user_func($callback, $dataset);
}
```

**Comment by eaCe** [comment]
Können wir vielleicht die Meta noch erweiter um anzuzeigen ob es next oder prev gibt? Wenn ja würde ich das mal in einen PR packen.

```php
if (($currentPage - 1) > 0) {
    $links['prev'] = rex_yform_rest::getLinkByPath($this, array_merge(
        $linkParams,
        ['page' => ($currentPage - 1)]
    ));
    **$meta['prev'] = true;**
}
**else {
    $meta['prev'] = false;
}**
if (($currentPage * $per_page) < $itemsAll) {
    $links['next'] = rex_yform_rest::getLinkByPath($this, array_merge(
        $linkParams,
        ['page' => ($currentPage + 1)]
    ));
    $meta['next'] = true;
}
**else {
    $meta['next'] = false;
}**
```

**Comment by dergel** [comment]
swagger ui -> https://github.com/yakamara/redaxo_yform/issues/1301
callback API -> kannst du dazu ein Issue schreibeb @eaCe 
next und prev Krams bekommt du über links .. wenn kein next vorhanden, gehts nicht mehr weiter. D.h. dort kannst du es auslesen ob vorhanden oder nicht.

**Comment by eaCe** [comment]
@dergel ich kann auch einen PR bereitstellen, wenn gewünscht

**Comment by dergel** [comment]
@eaCe erstmal ein Issue.. Ich denke der obige Weg ist noch nicht ideal. Würde gerne eine Lösung finden, die auch die Liste und Detaildarstellung im Manager mit abdeckt. vielleicht entsteht sogar ein Feld welches nur ein Callback hat oder Ähnliches.
