### ISSUE TITLE
YForm3-beta9: choice - default-Wert wird nicht übernommen

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#636]
```
$styler_id = 47; // kommt vom URL-Addon
         $yform->setValueField('choice', array('selected_styler_ids','###Anfrage-Text###','SELECT id AS value, name label FROM rex_yf_styler' ORDER BY prio','1','1', (string)$styler_id,'','','','','','','','0'));
```

hat in YForm3-beta3 noch 1:1 funktioniert.

**Comment by dergel** [comment]
kannst du das auch in der pipe notation und im manager testen ? taucht das nur hier auf ?

**Comment by tbaddade** [comment]
Könnte in deiner Zeile ein Schreibfehler sein und das default rutscht damit eine Stelle weiter?

ˋname label FROM rex_yf_styler' ORDER BY prioˋ das Singlequote meine ich

**Comment by Pixeldaniel** [comment]
Auch im Table Manager wird default nicht ausgewählt.
(mit Gruß von @alexplusde)

**Comment by tbaddade** [comment]
Könnte es an dieser Änderung hier liegen?
https://github.com/yakamara/redaxo_yform/commit/da76311bb9d7bd49030bec077d5a547e5206fcd0#diff-7e692d4181a2da11e1b58f6771428c4c

**Comment by dergel** [comment]
sollte nun wieder passen.. aber ich denke ich muss sicherheitshalber noch eine beta rausgeben

**Comment by alexplusde** [comment]
rudimentär getestet. funktioniert.
