### ISSUE TITLE
Relationstabellen funktionieren nicht

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#640]
YForm-Version: `3.0-beta10`

Tabellen wurden wie in der Doku angelegt

https://github.com/yakamara/redaxo_yform_docs/blob/f892d29c9482d5ce4398823a70ba47c6d0322220/de_de/table_manager_feldtypen_be-manager-relation.md#many-to-many

Will man jetzt den Datensatz speichern kommt dann folgendes

```
Warning: no values given to buildPreparedValues for update(), insert() or replace() in src/core/lib/sql/sql.php on line 793
Error while executing statement "INSERT INTO `rex_table` SET "! SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1
```

> Datensatz wurde eingetragen.`
> Datensatz editieren [id: -1]
> ErrorCode - EntryNotFound

Ich vermute, dass die Id des neu anzulegenden Datensatz nicht gefunden wird. Die steht auf `-1`

**Comment by tbaddade** [comment]
Der Fehler passiert nur, wenn zuvor kein anderes Feld angelegt wurde und das Widget zur Auswahl allein vorhanden ist.

**Comment by dergel** [comment]
habs nun nachvollzogen und Fehler gefunden. Ist nicht in der YForm sondern in der rex_sql.. Issue ist bereits angelegt.

https://github.com/redaxo/redaxo/issues/2487
