### ISSUE TITLE
falsches Datum wird gespeichert und mal nicht

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#641]
YForm-Version: `3.0-beta10`

`date` als `select`

Das Datum `31-02-2019` wird nicht in der DB gespeichert, verständlich. sollte YForm hier direkt validieren und eine Info ausgeben oder es anpassen auf `03-03-2019`?

Das Datum `00-02-2019` wird gespeichert. Auswahl `--` - `2` - `2019`

**Comment by dergel** [comment]
finde ich richtig .. aber, dass die Formate immer dd mm yy haben muss eigentlich nicht sein, wenn man z.b. nur monat und jahr oder tag und monat haben möchte..

Ist aber ein neues issue und wäre dann version 3.1
