### ISSUE TITLE
date Value - leeres Startjahr kann Probleme machen

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#643]
Lässt man das Startjahr leer, wird als Startjahr das aktuelle Jahr genommen.
Wurden  Datensätze in einem vergangenen Jahr erstellt, werden diese bei Edit nicht mehr korrekt gespeichert, da das Startjahr das aktuelle Jahr ist.

Beispiel.
Ein Datensatz wurde 2018 angelegt. 2019 wird der Datensatz editiert. Zur Auswahl stehen jetzt die Jahre 2019 bis x zur Auswahl. 2018 wird nicht mehr angezeigt und der Datensatz wird falsch gespeichert.

**Comment by dergel** [comment]
Logik verbessert. Dennoch wird empfohlen immer ein Start und Enddatum zu setzen.

**Comment by tbaddade** [comment]
> Dennoch wird empfohlen immer ein Start und Enddatum zu setzen.

Könnte als Notiz unter dem Feld erscheinen.
