### ISSUE TITLE
Date und Datetime feld einschränken können, auf z.b. nur MM-YY

### ISSUE THREAD

**Issue by dergel** [yakamara/redaxo_yform#644]
Anzeigeformat erweitern um:

MM-YYYY
YYYY-MM
DD-MM
MM-DD

und entsprechend dann bei select diese Felder wegblenden können. Speicherformat wäre dann dennoch als komplettes Date. bei MM-YYYY z.B. 00-12-2010

**Comment by dergel** [comment]
neue Formate sind nun möglich

**Comment by ynamite** [comment]
@dergel Was war denn die Idee dahinter?
Aktuell ist es nämlich nicht mehr möglich ein deutsches Datumsformat auszugeben: 
`15.02.2018`
