### ISSUE TITLE
Tippfehler schmeißt Fehler in yform

### ISSUE THREAD

**Issue by Marschl** [yakamara/redaxo_yform#645]
Hi, 
in /lib/yform.php Zeile 475 hat sich ein Tippfehler eingeschlichen:
`return $label ?? current($params);` 
Lg
Marcel

**Comment by dergel** [comment]
ist kein Tippfehler .. 
-> null coalesce operator

**Comment by alexplusde** [comment]
@Marschl was kommt denn für eine Fehlermeldung?

**Comment by dergel** [comment]
ich habe das dennoch angepasst, so dass es auch ohne php7 geht :)

**Comment by alexplusde** [comment]
ist PHP7 bei yform nicht eh inzwischen Pflicht? (scheinbar nicht)
