### ISSUE TITLE
time value - Anzeigeformat als Auswahl umsetzen

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#646]
Wie bereits im date value geschehen

**Comment by dergel** [comment]
was gibt es da für Varianten. Kannst du ein paar sammeln ?

**Comment by tbaddade** [comment]
- `G:i` (`5:09`, `13:09`)
- `G:i:s` 
- `H:i` (`05:09`, `13:09`)
- `H:i:s` 
- `g:i a` (`5:09 am`, `1:09 pm`) 
- `g:i:s a` 
- `h:i a` (`05:09 am`, `01:09 pm`) 
- `h:i:s a`

`u` und `v` habe ich mal rausgelassen. Wäre aber sicherlich auch interessant wenn man denn Zeiten mit Mikrosekunden erfassen will.

Mir wäre es lieb, wenn die Zahlen wieder mit führender Null erscheinen.

**Comment by dergel** [comment]
Jetzt ist format nur noch für die Ausgabe zuständig. Die Eingabe braucht keine spezielle Auswahl und ist nun fest (input:text oder select mit fester Reihenfolge)

**Comment by tbaddade** [comment]
> Die Eingabe braucht keine spezielle Auswahl und ist nun fest 

Was bedeutet das?

Anzeigeformat: `H:i`
Widget: `select`

Ausgabe im Datensatz: 3 Selectfelder für Stunde, Minute und Sekunde

Fehler @dergel ?

**Comment by tbaddade** [comment]
Ebenso wenn man das Format `G:i` auswählt.

**Comment by alxndr-w** [comment]
> Jetzt ist format nur noch für die Ausgabe zuständig.

**Comment by tbaddade** [comment]
> Ausgabe im Datensatz: 3 Selectfelder für Stunde, Minute und Sekunde

**Comment by dergel** [comment]
das ist schon richtig. die Zeitauswahl - Eingabe hat nichts mit dem Anzeigeformat zu tun. Hatte es mal.

**Comment by tbaddade** [comment]
> das ist schon richtig. die Zeitauswahl - Eingabe hat nichts mit dem Anzeigeformat zu tun. Hatte es mal.

Dann ist das verwirrend. 

Ich finde man sollte wieder darauf Einfluss haben ob Sekunden angezeigt werden oder aber auch wie die Ausgabe in welchen Format (Bsp.: G:i) dargestellt wird.

**Comment by dergel** [comment]
Kannst du - über JS und timepickern. Aber am Ende sollte immer das richtige Format gesetzt werden. Also H:i:s ..
