### ISSUE TITLE
yform 3.0 update schlägt fehl

### ISSUE THREAD

**Issue by ynamite** [yakamara/redaxo_yform#648]
Evtl. schon gekannt, aber für den Fall:

AddOn "yform" konnte aus folgendem Grund nicht aktualisiert werden:
yform_usability: Das PlugIn yform/manager (Version 3.0) entspricht nicht der geforderten Versionsbedingung ^2.0!
yrewrite: Das PlugIn yform/manager (Version 3.0) entspricht nicht der geforderten Versionsbedingung ^2.0!

Installiert ist:
yrewrite 2.4
yform_usability 1.4-dev 

von yform_usability gibt's soweit ich erkennen kann keine neue im Installer

**Comment by dergel** [comment]
ist nun kein wirklich yform fehler, sondern eine abhängigkeit die bei yrewrite gelöst werden muss. Deswegen schliesse ich das hier .. geht dann in yrewrite weiter

**Comment by ynamite** [comment]
@dergel das weisst du besser ;) wollte es nur melden,

**Comment by dergel** [comment]
Ja. Ich mach das die Tage
