### ISSUE TITLE
Massenberarbeitung / Datenergebnis editieren funktioniert nicht bei Choice-Feld

### ISSUE THREAD

**Issue by isospin** [yakamara/redaxo_yform#654]
Wenn ich mit im Tabellenmanager über die Suche Datensätze selektiere und dann auf 'Datenergebnis editieren' klicke ist die Datenselektion dahin und es werden alle Datensätze der Tabelle editiert.

REDAXO 5.6.5
PHP 7.2
YFORM 3.0

**Comment by isospin** [comment]
... wenn das Suchfeld vom Typ Choice war

**Comment by dergel** [comment]
sollte wieder.. bitte githubversion testen
