### ISSUE TITLE
YForm3: Fehler mit MariaDB beim Anlegen eines Datensatzes

### ISSUE THREAD

**Issue by schuer** [yakamara/redaxo_yform#655]
Komponente|Version
---|---
YForm|3.0
REDAXO|5.7.0-beta2
Datenbank|5.5.5-10.4.1-MariaDB-1:10.4.1+maria~bionic

Fehlermeldung:
> Error while executing statement "INSERT INTO `rex_test` SET "! SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1

![screenshot 2019-02-10 at 14 32 50](https://user-images.githubusercontent.com/1297466/52534354-e256b180-2d40-11e9-9ff7-48b721be8b9f.png)

**Comment by schuer** [comment]
Update: Fehler fliegt nicht mehr, wenn man das Ding nicht leer abschickt, sondern vorher Felder anlegt. ;)

**Comment by dergel** [comment]
ist ein redaxo Fehler - der aber ab 5.7 behoben sein sollte. rex_sql erlaubt kein insert wenn kein feld gesetzt wurde.
