### ISSUE TITLE
Table Manager: Feld be_user gibt Login-Namen aus, besser Name?

### ISSUE THREAD

**Issue by tema-web** [yakamara/redaxo_yform#657]
Wenn man ein Feld be_user einer Tabelle hinzufügt, wird der Login-Name gespeichert/ausgegeben. Ich denke, es wäre besser, wenn stattdessen der Name verwendet werden würde und als Fallback der Login-Name. Könnte so aussehen (be_user.php Zeile 22):
`$user_login = $user->getLogin();`
ändern in
`$user_login = $user->getName() ?: $user->getLogin();`

Oder gibt es einen besonderen Grund, das so zu handhaben?

**Comment by alexplusde** [comment]
Aber nur bei der Ausgabe, oder? Deine Änderung bezieht sich auf den Wert, der abgespeichert wird?

**Comment by tema-web** [comment]
Das stimmt, der angezeigte und der abgespeicherte Wert ist bei dieser Lösung der Selbe, war ein Schnellschuss. Der Name kann sich ja ändern und somit besteht die Möglichkeit, dass man später nicht mehr nachvollziehen kann, wer eine Änderung vorgenommen hat. Besser wäre es, nur den Anzeige-Namen zu ändern.

**Comment by alexplusde** [comment]
@tema-web wenn du die passende Stelle im Code findest, kann ich dir zeigen, wie du hier einen PR machst.

**Comment by tema-web** [comment]
@alexplusde tema-web = Tito ;-)
Ich habe mir das gerade noch einmal angeschaut und habe ein kleines Problem: ich weiß nicht, wie ich den Namen eines Users anhand seines Logins aus der DB lesen kann. Hast du da eine Idee?
Und auf das Angebot mit dem zeigen wie ich einen PR mache komme ich gerne zurück :-)

**Comment by alexplusde** [comment]
ungetestet:

`rex_login::getUser($id)->getName();`

**Comment by tema-web** [comment]
Ne, das funktioniert nicht (Woops-Error "Using $this when not in object context"). Alles, was ich ich in den Login-Klassen gefunden habe, bezieht sich auch den aktuell eingeloggten user. Ich glaube, so langsam kann ich nachvollziehen, warum Jan (oder wer auch immer) den Login hier verwendet: kann nicht geändert werden und ist aussagekräftiger als die Id.
Für mich sieht das alles mittlerweile nach einem größeren Umbau aus, von daher denke ich, dass es erst einmal zurückgestellt werden kann. Für die meisten ist das eh nicht relevant und es ist auch nicht soo ein großes Problem, das der Login-Name sichtbar ist.

**Comment by dergel** [comment]
ich hatte mir das angesehen und denke, dass das login eindeutig ist und besser als die ID. Die Komforfunktion, dass der Name direkt auch zu lesen ist, finde ich nicht so wichtig. Ich hoffe es ist ok wenn ich hier schließe
