### ISSUE TITLE
yform 3.0 / tools 3.0 datetimepicker & inputmask funktioniert nicht

### ISSUE THREAD

**Issue by ynamite** [yakamara/redaxo_yform#658]
datetimepicker und inputmask harmonieren irgendwie nicht, keine Ahnung was hier geschieht.

Mit `datepicker` funktioniert zBsp: 
`{"data-yform-tools-inputmask":"DD.MM.YYYY", "data-yform-tools-datepicker":"DD-MM-YYYY"}`

Mit `datetimepicker` funktioniert folgendes nicht: 
`{"data-yform-tools-inputmask":"DD.MM.YYYY", "data-yform-tools-datetimepicker":"DD-MM-YYYY HH:ii:ss"}` <- zumindest das hier müsste eigentlich problemlos gehen, ausser ich hab was falsch verstanden
`{"data-yform-tools-inputmask":"DD.MM.YYYY HH:ii:ss", "data-yform-tools-datetimepicker":"DD-MM-YYYY HH:ii:ss"}`
`{"data-yform-tools-inputmask":"DD.MM.YYYY HH:mm:ss", "data-yform-tools-datetimepicker":"DD-MM-YYYY HH:ii:ss"}`
`{"data-yform-tools-inputmask":"DD.MM.YYYY HH:mm:ss", "data-yform-tools-datetimepicker":"DD-MM-YYYY HH:ii:ss"}`
`{"data-yform-tools-inputmask":"DD.MM.YYYY H:m:s", "data-yform-tools-datetimepicker":"DD-MM-YYYY HH:ii:ss"}`
`{"data-yform-tools-inputmask":"D.M.Y H:m:s", "data-yform-tools-datetimepicker":"DD-MM-YYYY HH:ii:ss"}`

**Comment by ynamite** [comment]
https://github.com/yakamara/redaxo_yform/issues/647

**Comment by ynamite** [comment]
Hab's hinbekommen, ganz schön knifflig:
`{"data-yform-tools-datetimepicker":"DD.MM.YYYY HH:ii:ss", "data-yform-tools-inputmask":"datetime", "data-inputmask-mask":"1.2.y h:s:s", "data-inputmask-alias":"dd.mm.yyyy", "data-inputmask-placeholder":"dd.mm.yyyy hh:mm:ss", "data-inputmask-separator":"."}`

**Comment by alexplusde** [comment]
Danke für den PR in der Doku!
