### ISSUE TITLE
upload-value: reset() value

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/redaxo_yform#659]
Wird eine Datei ausgewählt, sollte man diese vor Abschicken des Formulars auch nachträglich "abwählen" können.

Abgucken hier:
https://stackoverflow.com/a/48263180

**Comment by alxndr-w** [comment]
@dergel kommt das für die 4.0?

**Comment by dergel** [comment]
Danke Thomas.. das haben wir dann schonmal :)
