### ISSUE TITLE
be_table - Helferklasse fehlt, um die Tabelle im Frontend auszugeben

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#66]
https://github.com/yakamara/redaxo_yform/blob/master/plugins/manager/lib/yform/value/be_table.php

**Comment by dergel** [comment]
ist nicht fürs frontend gedacht .. deswegen der be_ zusatz. erstmal deswegen nicht.. gleiche gilt für medialiste und relation etc.
