### ISSUE TITLE
Manager: Spalten einer Tabelle verlieren beim editieren der Spalte die Position/Prio

### ISSUE THREAD

**Issue by ynamite** [yakamara/redaxo_yform#661]
Die Prio von yform Manager Tabellen Spalten geht beim Editieren verloren. 

Editiert man die letzte Spalte einer Tabelle wird die Spalte an den Anfang der Tabelle verschoben.

yform/manager 3.0

**Comment by alexplusde** [comment]
Vermutlich ein falsch konfiguriertes Prio-Feld und kein Bug. Kannst du die Konfiguration als Screenshot reinstellen?

**Comment by ynamite** [comment]
@alexplusde es ist kein konfigurierbares Feld, es geht um die yform manager Tabellen *Spalten*.

**Comment by alexplusde** [comment]
Ah, verstehe. Muss ich mir mal anschauen, bisher konnte ich da keine Probleme feststellen.

**Comment by dergel** [comment]
habs probiert, konnte ich aber mit der aktuellen github version nicht nachvollziehen. 
Habe in der Tabellen-Feldübersicht verschiedene, auch die letzten Felder, bearbeitet - und Prio bleibt.

**Comment by ynamite** [comment]
@dergel Evtl. wurde das Problem mittlerweile gelöst.

Hattest du das Prio-Feld als erstes definieret und danach die restlichen Felder? Ich bin mir nicht mehr sicher, schon über einen Monat her, aber könnte mir vorstellen das ich das Prio-Feld erst im Nachhinein hinzugefügt hatte.

**Comment by dergel** [comment]
Ich dachte es geht nicht um das priofeld selbst, sondern um die Pflege der Spalten, bei denen dann das Priofeld falsch reagiert, oder ? ... hast du screenshots und kannst du versuchen ob es noch der fehler bei der aktuellen github evrsion noch existiert ?

**Comment by ynamite** [comment]
> Ich dachte es geht nicht um das priofeld selbst, sondern um die Pflege der Spalten, bei denen dann das Priofeld falsch reagiert, oder ?

genau, darum geht's.

Dachte nur, dass es evtl. darauf ankommt ob man das Prio-Feld von Anfang an oder erst später hinzufügt, damit das Problem sich zeigt. Hatte das Problem schon ein paar mal in div. Installationen. Wenn es nochmal auftritt, melde ich mich.

**Comment by alexplusde** [comment]
Also irgendwie verstehe ich es immer noch nicht. Kannst du dann einen Screencast aufnehmen?

**Comment by ynamite** [comment]
> Ah, verstehe. Muss ich mir mal anschauen, bisher konnte ich da keine Probleme feststellen.

@alexplusde Ich verstehe nicht, was du daran nicht verstehst. Zumal du's scheinbar mal verstanden hast und nun wieder nicht. Nochmal: https://github.com/yakamara/redaxo_yform/issues/661#issuecomment-464879872

Und nochmal: https://github.com/yakamara/redaxo_yform/issues/661#issuecomment-478646032

**Comment by alexplusde** [comment]
Deine Ausführungen sind missverständlich. Deswegen bin ich mir auch nicht mehr sicher, dich richtig zu verstehen.

**Comment by ynamite** [comment]
> Deine Ausführungen sind missverständlich. Deswegen bin ich mir auch nicht mehr sicher, dich richtig zu verstehen.

@alexplusde Stimmt, entschuldige, hab tatsächlich selbst ein durcheinander gemacht (ist mir erst jetzt aufgefallen, war ein langer Tag). 

**Nochmals von vorn und hoffentlich dieses mal unmissverständlich:** es geht **NICHT** um ein Prio-Feld, sondern um die yform eigene Sortierung der Spalten innerhalb einer yform Tabelle. 

Hier ein konkretes Beispiel (wo der Fehler aktuell auftritt).

<img width="907" alt="grafik" src="https://user-images.githubusercontent.com/1733051/55360063-9ec42c80-54d3-11e9-8157-e19566abe282.png">

Wenn ich hier beispielsweise beim Feld `url_beruf` auf editieren klicke, erscheint folgendes:

<img width="910" alt="grafik" src="https://user-images.githubusercontent.com/1733051/55360329-52c5b780-54d4-11e9-9e83-b03f0fbe85e4.png">

Wie man sieht, wird das Select-Feld `Priorität` ohne mein Zutun auf "Am Anfang" gesetzt. Wenn man nun speichert, ohne es zu bemerken, stimmt die Feld-Reihenfolge nicht mehr. Der Fehler bleibt solange bestehen, bis man im Select-Feld irgendeine andere Reihenfolge wählt als "Am Anfang". Danach werden die Prios korrekt neu gesetzt:

<img width="903" alt="grafik" src="https://user-images.githubusercontent.com/1733051/55361596-fc5a7800-54d7-11e9-87a2-769dd2bcb364.png">

Die Tabelle im Screenshot wurde übrigens in yform 3.0 erstellt. Im aktuellen Release ist der Bug also noch präsent. 

**Wichtig:** das Problem tritt nicht bei jeder Tabelle auf; ich kann momentan noch keinen Zusammenhang erkennen wann/wieso es passiert, nur das es geschieht. Evtl. liegt's am Drag&Drop oder am organisieren der Prios selbst. Hab's aber auch nicht genauer untersucht. 
Aufgefallen ist's mir indes schon öfter, nicht nur in dieser Installation; falls der Bug in der neusten Git-Version eliminiert ist, super. 

Hoffe das hilft.

**Comment by alexplusde** [comment]
Danke für die Klarstellung. :)

Interessant wäre ja, herauszufinden, warum Prios vormals “Lücken“ hatten... Das andere wäre wohl ein Folgefehler davon

**Comment by ynamite** [comment]
Seh ich genauso. Werde versuchen zu eruieren wann/wieso die Prios lückenhaft werden.

**Comment by tbaddade** [comment]
@ynamite Hat deine Tabelle nur diese 4 Felder? Wenn ja, kannst du das Verhalten ohne das D&D nachvollziehen? Mir ist das so noch nie aufgefallen.

**Comment by ynamite** [comment]
@tbaddade ja, nur diese 4 Felder. Nicht konstant, hat während der Entwicklung evtl. etwas variiert. 
Möglicherweise stammt der Fehler auch vom löschen und wiederhinzufügen eines Feldes. 

Erstaunt mich das niemand dieses Verhalten kennt, hab das echt schon öfter erlebt.

**Comment by dergel** [comment]
Welche D&D Variante ? Ein AddOn zusätzlich drin ?

**Comment by ynamite** [comment]
@dergel in den screenshots oben hat's doch bei jedem Eintrag ganz links ein Hamburger-Icon. Über dieses kann man die Zeile per Drag&Drop verschieben.
Wahrscheinlich das yform usability addon?

**Comment by dergel** [comment]
ah ich sehs. deswegen gibts auch die Probleme. Bitte dort nochmal nachfragen.. Ein solche Prioveränderung darf eigentlich schon gar nicht vorkommen. Bitte erstmal dort in Ordnung bringen lassen.
