### ISSUE TITLE
YForm 2.3 Chrome Windows "Seite funktioniert nicht"

### ISSUE THREAD

**Issue by simonsinus** [yakamara/redaxo_yform#663]
Hallo,

ich habe bei einem Bestellformular mit E-Mail-Versand Probleme mit Chrome (Windows 7 und 10).

Die YForm verschickt 2 E-Mails, eine an den Besteller und einen an die Organisation.

Diese Seite funktioniert nicht Chrome hat auf dieser Seite ungewöhnlichen Code erfasst und diese Seite daher blockiert, um Ihre personenbezogenen Daten wie Passwörter, Telefonnummern oder Kreditkarteninformationen zu schützen.
Versuchen Sie, die Startseite aufzurufen.
ERR_BLOCKED_BY_XSS_AUDITOR

**Comment by simonsinus** [comment]
Chrome hat anscheinend Probleme damit, wenn man HTML-Text in einem Value mitschickt.

Ich habe jetzt das HTML in normalen Text umgewandelt.

**Comment by alexplusde** [comment]
Das stimmt, das sollte man so nicht machen. Close?
