### ISSUE TITLE
Problem zwischen Pipe-Formular und PHP-Formular mit objparam send=1

### ISSUE THREAD

**Issue by Pixeldaniel** [yakamara/redaxo_yform#664]
Dieses Formular im YForm Formbuilder

```
hidden|status|1
objparams|submit_btn_show|0
objparams|send|1
objparams|csrf_protection|0
```

wird ausgeführt.

Dieses hier analog dazu

```
        $yform = new rex_yform();
        $yform->setValueField('hidden', array('status','label', "1"));

        $yform->setObjectparams('submit_btn_show', "0");
        $yform->setObjectparams('form_action',rex_getUrl('REX_ARTICLE_ID'));
        $yform->setObjectparams('send', '1');
        $yform->setObjectparams('csrf_protection',"0");


        echo $yform->getForm();

```

wird nicht ausgeführt. send=1 wird ignoriert bzw. mittels debug-Tests in der yform.php stellt sich heraus, dass nicht alle objparams/actions/values an der entscheidenden Stelle da sind. Genauer konnten wir es jedoch nicht eingrenzen.

Das Problem äußert sich, wenn man ein Registrierungs-Bestätigungs-Formular nicht via Formbuilder, sondern via PHP-Schreibweise schreiben will, wird aber sicher an anderer Stelle auch für Probleme sorgen.

**Comment by alexplusde** [comment]
@dergel wäre super, wenn du mal drüber schauen kannst. Wir wollen das auch wieder in die YCom-Doku zurück einpflegen.

**Comment by alexplusde** [comment]
Ergänzend dazu:
https://friendsofredaxo.github.io/tricks/addons/yform/send_hidden_mail

```
[...]
$yf->getForm();
$yf->setObjectparams('send',1);
$yf->executeActions();
```

Hat es etwas damit zu tun? Müssten die Actions nicht schon durch send ausgeführt werden?

Analog zum Formbuilder müsste bereits das hier genügen

```
[...]
$yf->setObjectparams('send',1);
$yf->getForm();
```

**Comment by dergel** [comment]
gerne mit der github version testen. sollte wieder gehen
