### ISSUE TITLE
Aus dem Forum: yform be_table speichert nur eine reihe

### ISSUE THREAD

**Issue by skerbis** [yakamara/redaxo_yform#673]
yform be_table speichert nur eine reihe

https://redaxo.org/forum/addons-packages-r5-f43/yform-be_table-speichert-nur-eine-reihe-t22728.html

hallo an alle - ich habe fuer einen kunden mit yform ein verwaltungstool gebaut. soweit funktioniert alles, ausser die be_table-geschichte. wann immer ich neue reihen hinzufüge und abspeichere wird immer nur EINE übernommen. d.h, sobald ich mehrere anlege, befülle, speichere und mich wieder einlogge, sind alles neuen reihen weg, bis auf die zuerst angelegte.

allgemein: rex 5.6.5, yform 3.0-beta9

hatte das problem schoneinmal jemand?
danke für feedback/rat - ben

—

muss mich korregieren - es wird immer nur die zuletzt hinzugefügte übernommen, alle vorab eingebundenen reihen sind weg…

—
noch ein nachtrag:

ich habe 2 be_table in meiner vorlage. ich kann bei beiden einen neueintrag machen, die uebernimmt er dann auch bei beiden tables. nur mehrere reihen bei einer be_table hinzufuegen funzt nicht...
ben

**Comment by alexplusde** [comment]
Kann das nicht bestätigen. YForm updaten auf 3.0 und dann nochmal überprüfen

**Comment by beyben** [comment]
hei alex - habe ich gemacht. habe die sache noch auf einer subdomain laufen:
REDAXO 5.6.5, PHP 7.2.14, yForm 3.0 alles frisch updgraded...
test wegen einer weiterentwicklung eh daran rum... was kann schiefgelaufen sein?
dank dir - ben

**Comment by tbaddade** [comment]
@beyben greifen irgendwelche Javascripte rein?

Sinnvoll wäre es zu wissen, was er System report sagt
`/redaxo/index.php?page=system/report/markdown`

**Comment by beyben** [comment]
keine javascripte, die ich dazugefügt hätte, nur die redaxo internen... im systemlog (redaxo/index.php?page=system/log) steht nichts. wie installiere ich den report?

**Comment by tbaddade** [comment]
> wie installiere ich den report?

Mein Fehler … das kommt erst mit der 5.7er Version

Welche AddOns hast du installiert. Haben irgendwelche Einfluss darauf?
Nutzt du eigenes HTML / Javascript direkt in den Values `php` oder `html`?

**Comment by beyben** [comment]
habe zusaetzlich api_docs, bloecks, cutncopy, dragndrop, status, iconpicker , multiupload, quick_navigation, content, tinymce4, ycom, auth, docs, group, media_auth, yform, email,  yform_usability, yrewrite installiert. in sachen eigenes html/js habe ich die sache ganz normal via yform->table manager angelegt. würde dir ein login helfen? dank dir - ben

**Comment by tbaddade** [comment]
ich würde die AddOns nach und nach deaktivieren

- api_docs, 
- bloecks, 
  - cutncopy, 
  - dragndrop, 
  - status, 
- iconpicker, 
- tinymce4, 
- yform_usability

Verwendest du den Tiny in deinen Tabellen?

**Comment by beyben** [comment]
nein, den tiny nicht. gebe x felder vor und formatiere bei der ausgabe... ich deaktiviere mal...

**Comment by alexplusde** [comment]
Kann ich noch die Felddefiniton dazu sehen? Danke!

**Comment by beyben** [comment]
habe nun nach und nach alle deaktivert, keine veränderung. @alex, meinst du das:
6 | value | be_table | etagenpfad | Pfadangaben je Etage ODER je Haus für das !Projektbild
? oder von allen anderen auch?

**Comment by alexplusde** [comment]
Versuchst du, be_table im Frontend zu verwenden? Das geht nämlich nicht, be steht für Backend.

**Comment by beyben** [comment]
nein, sind die eingabefelder im backend bei den yform tabellen. ausgabe mache ich dann via modul...
wie gesagt, ich habe von allemein update gemacht, der fehler besteht aber trotzdem. ich habe das system selbst auch schon auf den liveserver gestellt, auch hier alles neu installiert, die datenbank eingepflegt, aber auch hier habe ich das gleiche problem....
dank euch - ben

**Comment by alexplusde** [comment]
@beyben kannst du hier bitte einen Screenshot der Felddefinition einfügen? Also im Table Manager auf die Tabelle gehen, das Feld bearbeiten und dann die Konfiguration posten? Das meinte ich mit Felddefinition. Sonst kann ich es nicht richtig nachstellen, wo das Problem liegt

**Comment by beyben** [comment]
ok, anbei - hab dank - ben
![be_table](https://user-images.githubusercontent.com/47885281/53565749-8bcbde80-3b5a-11e9-8017-6278a0f82be0.jpg)

**Comment by beyben** [comment]
na hei - ich habe es nun in der zweitinstallation mal so versucht:
"Bezeichnung der Spalten (Menge,Preis,Irgendwas)"
Nummer der Etage,Pfade kommagetrennt,Bild der Etage
soll heissen, ohne klammern und co... hat einer nen tip, wo zu schauen sinn macht? z.b. datenbank?
dank euch - ben

**Comment by alexplusde** [comment]
Ich kann das Problem bestätigen. @dergel das ist sehr merkwürdig. Es scheint, sobald in den Eingabefeldern Zahlen verwendet werden, gibt es Probleme. Auch Spalten, die ich eingegeben habe, wurden nicht alle beim Komma getrennt sondern blieben irgendwie zusammen.

**Comment by beyben** [comment]
was auch auffaellt, aber nicht wild ist, wenn eine 0 eingegeben wird, wird diese geloescht. fange ich ab, aber eigentuemlich ist es schon...

**Comment by joachimdoerr** [comment]
Ich kann das merkwürdige verhalten bestätigen. Es tritt nicht nur mit eingegebenen Zahlen auf.

**Comment by dergel** [comment]
@lexplatt kannst du mal schauen ?

**Comment by lexplatt** [comment]
ich schau mal nach

**Comment by dergel** [comment]
@lexplatt konntest du schon schauen ?

**Comment by lexplatt** [comment]
Ja nur kurz und konnt es aber auf unserem Branch nicht reproduzieren. Muss jetzt rausfinden wo der unterschied liegt

**Comment by beyben** [comment]
na hi - kann ich dich da irgendwie unterstützen? z.b. mit nem zugang zur seite?  habe die betreffende seite auf nem testserver noch liegen, hab das problem aber auf beiden seiten und installationen...
ben & dank euch

**Comment by alexplusde** [comment]
Ich kann's reproduzieren...

**Comment by dergel** [comment]
@lexplatt ping

**Comment by lexplatt** [comment]
hab gerade meine lokalen Änderungen in meinen Fork gepushed. Kann jemand den testen: 
https://github.com/lexplatt/redaxo_yform

**Comment by beyben** [comment]
YES - hab dank, habs via ftp gelöscht, neu eingespielt und reinstalliert. nun speichert er auch x reihen ab...
ben

**Comment by lexplatt** [comment]
@dergel wollt ihr das auch noch testen, dann würd ich anschließend einen PR machen

**Comment by lexplatt** [comment]
@alexplusde du bist doch der Beta-Tester in Person ;)

**Comment by dergel** [comment]
danke schonmal .. mach gerne einen PR .. Ich gehe davon aus, dass es klappt.. Wenn nicht, würde ich mich danach melden :)

**Comment by alexplusde** [comment]
@lexplatt ich finde Bugs auch in Nicht-Betas ;) Aber leider bin ich gerade einfach zu beschäftigt und finde, dass solche Tests auch von anderen vorgenommen werden könnten - nicht nur von dir, Jan oder mir.

**Comment by dergel** [comment]
PR ist gemerged. Kann das jemand noch gegenprüfen ?

**Comment by alexplusde** [comment]
@beyben kannst du das evtl. mit der aktuellen YForm-Version 3.1 gegenprüfen, ob nun wieder alles funktioniert wie gedacht?

**Comment by alexplusde** [comment]
Ah, sehe gerade, du hattest das schon getestet und hier reingeschrieben. Dann ist ja alles gut.
