### ISSUE TITLE
Table-Manager: choice: Datenergebnis exportieren exportiert alle Datensätze...

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#677]
... wenn ein Choice-Feld gefiltert wurde.

Fehlermeldung bei der Filterung:

```
Warning: urlencode() expects parameter 1 to be string, array given in /home/.../www/redaxo/src/addons/yform/plugins/manager/lib/yform/manager.php on line 133
```

Dort werden allerdings noch alle wie gewünscht ausgeblendet, abgesehen von der Warning.

Beim Datenergebnis exportieren sind dann auch welche mit anderem Status mit drin.

**Comment by alexplusde** [comment]
Siehe auch: #654

**Comment by tdaeschner** [comment]
Selbes Problem hier mit Form 3 - Konfiguration:

REDAXO	5.7.0
PHP	7.1.15 
MySQL 5.6.19

**Comment by dergel** [comment]
geht nun wieder ..
