### ISSUE TITLE
automatisierte Tests

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/redaxo_yform#678]
Gerade bin ich etwas frustriert, dass trotz vieler Tests immer noch Fehler in YForm 3.0 auftauchen, die elementar sind. Das soll keine Beschwerde sein, allerdings wollte ich fragen, wie man YForm zuverlässig einem unit test unterziehen kann.

Gerne bin ich bei der Definition von Tests behilflich - ich habe jedoch keine Ahnung, wie man so etwas umsetzt und dann auch die Ergebnisse vergleichbar macht.

@staabm hast du vlt. eine Idee?

**Comment by dergel** [comment]
unit tests könnten wir auch machen .. aber z.B. würden die ersten und einfachsten Tests schonmal mit fertigen und komplexen frontend Formularen als pipe und als php notation gut sein. Also quasi mit einem erwarteten Ergebnis.

Und das Gleiche mit BE Tabellen, Relationen und Co.

Ansonsten natürlich UnitTests, wobei die für YOrm und Co geeigneter sind.

**Comment by alexplusde** [comment]
Vielleicht kannst du mir am REDAXO-Tag näher zeigen, wo und wie? Ich bin in dem Thema neu.

Ich sehe bspw. Bedarf bei dem Testen jedes Feldnamens, jeder Action und jeder Value in Kombination mit unterschiedlichen Konfigurationen: z.B. bei Choice (mit SQL, ohne SQL, ...). Sowohl in der Ausgabe, als auch bei der Eingabe. Das wären dann vermutlich schon 80-120 isolierte Tests.

**Comment by alxndr-w** [comment]
Hier hatte @marcohanke ja mal was gemacht, wenn ich mich recht erinnere.
