### ISSUE TITLE
yForm in verbindung mit Umlautdomain wirft ErrorException

### ISSUE THREAD

**Issue by f5alex** [yakamara/redaxo_yform#679]
ErrorException bei yForm und Umlautdomain.

getestet mit:
Redaxo 5.6.5
PHP 7.2.15
yForm 3.0
(kein weiteres Addon und nur REX_ARTICLE[] im Template)

Aufruf des Formulars über "normale" Domain funktioniert,
Aufruf über "umlautdomain" nicht.
Bsp:
"oe":
http://weingut-am-oelspiel.de/20190225/index.php?article_id=1
"ö":
http://xn--weingut-am-lspiel-9zb.de/20190225/index.php?article_id=1

---
ErrorException (E_RECOVERABLE_ERROR)
Argument 1 passed to rex_yform::getFieldName() must be an instance of string, string given, called in [...] /redaxo/src/addons/yform/lib/yform/value/abstract.php on line 54 and defined
---

**Comment by f5alex** [comment]
Sorry - war ein Fehlalarm...
Kann Mann das issue auch löschen... ;-)

**Comment by alexplusde** [comment]
Was war die eigentliche Ursache für den Fehler?

**Comment by f5alex** [comment]
Der Kunden hat „im Hintergrund“ an den PHP Einstellungen gespielt und die umlautdomain lief mit PHP 5.6 :-/
gharlan aus dem Slack-Channel hat mich auf die richtige Spur gebracht.
