### ISSUE TITLE
 REX_YFORM_TABLE_DATA Feld nach Speichern leer

### ISSUE THREAD

**Issue by skerbis** [yakamara/redaxo_yform#681]
Ich verwende eine Tabelle ohne prefix
Nach Speichern  der REX_YFORM_TABLE_DATA und Aufruf des Moduls ist das Feld wieder leer. 

REX_YFORM_TABLE_DATA[id="1" table="newskategorie" widget="1" field="cat"]

REDAXO 5.7 Beta 2

**Comment by skerbis** [comment]
Liegt evtl. an der Beta von REDAXO 5.7. Scheint ein Caching-Problem zu sein. Beim Click auf Editieren sehe ich plötzlich slices die nicht mehr existieren sollten, weil gelöscht. … Also kein yform-Problem

**Comment by alexplusde** [comment]
@skerbis das Phänomen mit Slices, die nicht mehr existieren sollten, habe ich auch in R5.6.5 bereits erlebt. Allerdings im Frontend. Kannst du es genauer eingrenzen?

**Comment by skerbis** [comment]
@alexplusde leider nein. Nach mehrfachem Cache-Löschen geht es jetzt.

**Comment by tbaddade** [comment]
Wo siehst du die Skices FE oder BE. Waren diese tatsächlich gelöscht oder nur offline (Blöcks). Würde die Tabelle migrieren?

**Comment by skerbis** [comment]
Dies slices sah ich nur im backend, wenn ich einen Block zum bearbeiten geöffnet habe.
