### ISSUE TITLE
Featurewunsch: PRIO-Feld Attribute übergeben

### ISSUE THREAD

**Issue by skerbis** [yakamara/redaxo_yform#682]
Im Backend bitte bootstrap-select mit livesearch verwenden. **Alternativ bitte ermöglichen das Attribut selbst setzen zu können.**

**Comment by alexplusde** [comment]
Siehe auch: https://github.com/yakamara/redaxo_yform/issues/294

**Comment by tbaddade** [comment]
> Im Backend bitte bootstrap-select mit livesearch verwenden. 

Via Attribute setzen gern aber bitte nicht initial einfach ausliefern.

**Comment by skerbis** [comment]
@tbaddade  ja, aas Prio-Feld nimmt aktuell keine attribute an, daher kann man es nicht stylen.

**Comment by skerbis** [comment]
Siehe PR: https://github.com/yakamara/redaxo_yform/pull/897
