### ISSUE TITLE
Date-Felder: Ausgabe der Monats-Select-Optionen festlegen (Zahl oder String)

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/redaxo_yform#684]
Sodass man hier bspw. "März" auswählen kann statt "3"

![image](https://user-images.githubusercontent.com/3855487/53696830-2e8a9400-3dcb-11e9-844a-49d15149f30a.png)

**Comment by dergel** [comment]
Über YTemplates lösbar. Ein eigenes Template erstellen und entsrpechende Ausgaben anpassen
