### ISSUE TITLE
yform 3 + theme-addon mit ytemplates: Einstellungen/Checkboxes werden nicht übernommen

### ISSUE THREAD

**Issue by anveno** [yakamara/redaxo_yform#693]
Kein Bug; eher ein Hinweis um anderen das Suchen zu ersparen :)

**Fehlerbeschreibung**:

Beim Anlegen einer neuen Tabelle sind alle Checkboxen in den Einstellungen aktiv und Änderungen daran werden nicht gespeichert.

![bug](https://user-images.githubusercontent.com/30634971/54477281-c85c3300-4806-11e9-9ee7-0bedf78a16a8.png)

**Ursache/Lösung**:

Es wurden veraltete ytemplates (yform 2) via theme-addon verwendet (theme/private/ytemplates). Diese müssen gelöscht/aktualisiert werden.

**Comment by alexplusde** [comment]
Der Fehler war vermutlich, dass diese bei dir auch bootstrap hießen?

**Comment by anveno** [comment]
Ja, genau. "bootstrap" und "classic" hatte ich mit in den theme-Ordner kopiert.
Hatte nicht bedacht, dass diese auch im Backend verwendet werden... und man sie besser umbenennen sollte :)
