### ISSUE TITLE
Date [Enddatum] in der Vergangenheit

### ISSUE THREAD

**Issue by marcohanke** [yakamara/redaxo_yform#699]
Ein Enddatum 0 oder -18 wäre cool für zum Beispiel Geburtsdaten. Bei der Abfrages des Geburtstages sieht es eigenartig aus wenn ein Datum in der Zukunft wählbar ist und bei Anfragen für mindestens 14/16/18-jährige wäre ein -x auch ganz nett

**Comment by alexplusde** [comment]
da würde ich ein text-input type date wählen an deiner Stelle. Das wird im Browser schön gerendert und verhindert auch Fehleingaben wie den 30. Februar

**Comment by alexplusde** [comment]
Ich glaube, das wurde gelöst. Spätestens hier: https://github.com/yakamara/redaxo_yform/pull/861
