### ISSUE TITLE
yform 2.3 / 3.0 übernehmen bei neuen E-Mail Templates zeigt CSRF-Token error an

### ISSUE THREAD

**Issue by LAnnika** [yakamara/redaxo_yform#704]
Erstellt man unter Yform ein neues E-Mail Template und klickt statt "speichern" auf "übernehmen" erscheint unter der Erfolgsmeldung ein CSRF-Token Error. Das Template wird aber korrekt angelegt.

Getestet mit redaxo 5.7.0 unter php 5.6.40 und 5.6.2 unter php 7.2.16

Übernehmen scheint generell ein Problem zu sein, denn der Fehler tritt auch beim "normalen" Speichern häufig, nicht nachproduzierbar, auf

**Comment by alexplusde** [comment]
YForm 2.3 ist hier nicht mehr Gegenstand der Entwicklung. Gibt es das Problem auch mit YForm 3.0?

**Comment by LAnnika** [comment]
Ja das Problem besteht immernoch. Außerdem funktioniert das Update von 2.3 auf 3.0 nicht richtig.

**Comment by tbaddade** [comment]
>  Außerdem funktioniert das Update von 2.3 auf 3.0 nicht richtig.

Könntest du das in einem neuen Issue genauer erklären

**Comment by dergel** [comment]
Update ist im neuen Issue geklärt. In YForm 3 habe ich das "übernehmen" bei E-mail Templates getestet und konnte keinen Fehler entdecken.

Wenn in YForm 2.3 etwas sein sollte, nehme ich gerne PullRequests an, werde aber sonst nur Sicherheitsrelevante Dinge anpassen

**Comment by LAnnika** [comment]
Ich bekomme die Meldung immer (auch nachdem ich yform gelöscht und neu installiert habe) 

Vorgehen: Neues Template erstellen (+) anklicken ->key eingeben -> übernehmen drücken -> "Fehler: CSRF-Token ungültig"
Template wird aber trotzdem gespeichert.

**Comment by alexplusde** [comment]
Also wenn es in 3.0 funktioniert und in 2.3 nur einen Fehler anzeigt, aber alles ordnungsgemäß abläuft, wird hier nichts mehr passieren, denke ich. Ein Lösungsweg, nämlich YForm updaten, wurde ja genannt. Wenn es da Probleme gibt, vielleicht direkt in Slack melden.

**Comment by LAnnika** [comment]
Es funktioniert in 3.0 NICHT

**Comment by dergel** [comment]
aus Zeitgründen erstmal nur einfach gelöst (übernehmen bei add entfernt)

**Comment by dergel** [comment]
Werde ich nicht mehr angehen. Sorry
