### ISSUE TITLE
Update 2.3 auf 3.0: "Unknown Column 'mail_reply_to' in 'field list' " beim Speichern von E-Mail Templates 

### ISSUE THREAD

**Issue by LAnnika** [yakamara/redaxo_yform#706]
Nach dem Update von 2.3 auf 3.0 können E-Mail Templates Templates nicht mehr bearbeitet werden, beim Speichern erscheint eine Erfolgsmeldung, die Fehlermeldung 
"ErrorCode - EntryNotFound" 
und der Hinweis 
"Error while executing statement ...
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'mail_reply_to' in 'field list'"
(und es wird nicht gespeichert)

Getestet mit redaxo 5.7.1 und php 7.3.3

![CRSF_3](https://user-images.githubusercontent.com/42063454/55464407-5c960a80-55fb-11e9-9ec9-eaf9254766fd.PNG)

**Comment by tbaddade** [comment]
Bei YForm <= 3.0 müsste das Plugin re-installiert werden.
