### ISSUE TITLE
Update von 3.0 auf 3.1

### ISSUE THREAD

**Issue by olien** [yakamara/redaxo_yform#707]
![image](https://user-images.githubusercontent.com/330516/55550712-36469c80-56d9-11e9-9d16-b479083f9ecc.png)

Beim zweiten Versuch ging es dann...

**Comment by dergel** [comment]
Ich kanns leider nicht sagen was da passiert ist, ich bräuchte quasi den Stand von davor, der ja so nciht mehr vorliegt. Kannst du den Fehler reproduzieren ? Wenn nein, dann würde ich das gerne entspannt ignorieren. ;) ..

**Comment by olien** [comment]
ignorieren :-)
