### ISSUE TITLE
be_table: leere Zeile nicht als Datensatz speichern

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#711]
leere Zeilen werden als Datensatz gespeichert.

**Comment by dergel** [comment]
ist das falsch ?

**Comment by alexplusde** [comment]
Ja schon. Zumindest, wenn das Feld nicht ausgefüllt wurde, entsteht so trotzdem ein Wert in der Datenbank. Man kann dann nicht mehr ohne weiteres auf `where field != ““` prüfen.

**Comment by alexplusde** [comment]
Szenario ist: man legt einen Datensatz frisch an und möchte ins be_table Feld nichts eintragen. Die GUI zeigt bereits eine leere Zeile (was ich auch gut finde), wird eben dann auch als Wert gespeichert.

**Comment by dergel** [comment]
@lexplatt wenn leeres Feld, dann keine Speicherung ?

**Comment by lexplatt** [comment]
@alexplusde hats sich dann erledigt?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by alexplusde** [comment]
Ich weiß jetzt glaube ich, wie das zustande kam:

R4 auf R5 portiert, Daten waren noch in uraltem xform-Format angelegt und das konnte be_table nicht verarbeiten - daher von Beginn an die leere Zeile. So muss es gewesen sein.

An sich wäre ich dafür, dass gleich eine leere Zeile hinzugefügt ist und man mit der Eingabe starten kann, aber das eigentliche Problem hier existiert so nicht.
