### ISSUE TITLE
Table Manager - XLSX-Export

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#712]
Für einen Kunden hatten wir die Anforderung, Daten aus dem Table Manager als XLSX exportieren zu können. Wir haben das jetzt selbst gelöst auf spezielle Weise, aber bin dabei auf einen nobrainer gestoßen:

https://github.com/shivarajnaidu/php-sql-to-xlsx 

Wäre vielleicht interessant als zusätzliche Export-Möglichkeit, weil auch beim Import in ein Tabellenkalkulationsprogramm weniger die Gefahr besteht, dass etwas mit dem Encoding oder der Formatierung nicht stimmt.

**Comment by dergel** [comment]
für weitere Exportmöglichkeite dieser Art würde ich auf umfangreichere Bibliotheken zugreifen.

Die ganzen PHPOffice Bibliotheken z.B.
https://github.com/PHPOffice/PhpSpreadsheet

Werde das zunächst aber nicht angehen
