### ISSUE TITLE
Table Manager: Warning: urlencode() expects parameter 1 to be string

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#713]
Warning: urlencode() expects parameter 1 to be string, array given in redaxo/src/addons/yform/plugins/manager/lib/yform/manager.php on line 133

Wenn man in der Suche beim Choice-Feld mehr als eine Auswahl trifft.

**Comment by dergel** [comment]
kann ich nicht nachvollziehen.. schickst du mir das tableset ?

**Comment by alexplusde** [comment]
siehe Slack

**Comment by dergel** [comment]
in der aktuellen github version auch ?

**Comment by dergel** [comment]
problem wurde bereits gelöst. habe ich auch mit deinem tableset geprüft

**Comment by alexplusde** [comment]
Danke!
