### ISSUE TITLE
REST API - URLs sollen auch ohne / am Ende gehen

### ISSUE THREAD

**Issue by dergel** [yakamara/redaxo_yform#714]
Beide Varianten erlauben

**Comment by dergel** [comment]
passtz nun

**Comment by Chernitsov** [comment]
@dergel kann man irgendwo die trailing slashes konfigurieren oder ist es ein Bug?

![Bildschirmfoto 2019-08-28 um 12 45 53](https://user-images.githubusercontent.com/43566674/63849254-fe930680-c991-11e9-9409-2e38e2e72002.png)

**Comment by dergel** [comment]
ist korrigiert. gerne mal kontrollieren.
