### ISSUE TITLE
Fehler in tpl2email Parameter führt zu Mail an verkehrte Adresse

### ISSUE THREAD

**Issue by Pixeldaniel** [yakamara/redaxo_yform#715]
```
$yform4->setActionField('tpl2email', ['template1', 'abc@y.de']);
$yform4->setActionField('tpl2email', ['template2','','def@y.de']);
```

In diesem Beispiel ist die erste Action fehlerhaft - die Mailadresse ist nicht als 3. Parameter angegeben. Dies hat zur Folge, dass die Mail mit template1 an die Adresse von template2 gesendet wird.

Lösungsidee:
Zukünftig auf den 3. Parameter verzichten und stattdessen E-Mail als 2. Parameter verwenden - wenn keine gültige E-Mail, dann Feldname auslesen. Stolpern auch auf Slack immer wieder Leute drüber.

**Comment by tyrant88** [comment]
Eigentlich müsste eine Mail mit template1 an `rex::getErrorEmail();` versendet werden.

**Comment by alexplusde** [comment]
siehe #396, duplicate?

**Comment by dergel** [comment]
ja ist doppelt.. ich schliesse das hier und weise das anderes issue einen konkreteren milestone zu
