### ISSUE TITLE
Table Manager - Spaltenbeschriftung für datestamp,php, index

### ISSUE THREAD

**Issue by georgkaser** [yakamara/redaxo_yform#72]
Könnte man bei dem genialen Tablemanager vielleicht auch eine Möglichkeit einbauen das datestamp Feld zu beschriften? Hier ein kleiner Screenshot, dann wird klar was ich meine:

![bildschirmfoto vom 2016-06-10 12-46-27](https://cloud.githubusercontent.com/assets/6472869/15962230/e12e10ce-2f09-11e6-83f9-07a838aea1be.png)

Wär cool um ein Erstellungsdatum (z.B. für eine Kommentartabelle) anzuzeigen - so ist das für den DAU verwirrend...

**Comment by alexplusde** [comment]
Der springende Punkt ist ja, dass in https://github.com/yakamara/redaxo_yform/blob/master/lib/yform/value/datestamp.php#L52 das Feld "label" nicht für die Beschriftung, sondern für das Format verwendet wird. Das müsste man auflösen und wahrscheinlich auch an vielen weiteren Stellen ändern. (Pipe-Schreibweise im Modul, etc.)

Ich meine, da gibt's noch 1-2 Feldtypen, die ein ähnliches Problem haben.

**Comment by alexplusde** [comment]
+ Außerdem sollte man die Auswahl der Formate als SELECT-Feld angeben und nicht als Freifeld, denn diese sind meines Wissens eh vordefiniert (z.B. mysql).

IN 1.1 wurde nämlich das Label dafür entfernt.

**Comment by dergel** [comment]
das feld datestamp geht gerade grundsaetzlich nicht ..

**Comment by dergel** [comment]
war ein anderes problem mit dem bug.. ist behoben

**Comment by dergel** [comment]
>Ich meine, da gibt's noch 1-2 Feldtypen, die ein ähnliches Problem haben.
@alexplusde wenn du die parat hast - her damit.. ich will das angleichen - auch wenn es ein paar BC Probleme geben wird.

**Comment by alexplusde** [comment]
ich muss nochmal suchen, welche das waren...

**Comment by alexplusde** [comment]
php, timestamp

**Comment by dergel** [comment]
timestamp ?

**Comment by alexplusde** [comment]
da hab ich nicht genau genug hingeschaut, es war ein index-Feld, das bei mir einen Zeitstempel beinhaltet hatte.
