### ISSUE TITLE
html in choice checkbox label erlauben

### ISSUE THREAD

**Issue by IngoWinter** [yakamara/redaxo_yform#722]
Aktuell wird grundsätzlich jedes html geschreddert: 
https://github.com/yakamara/redaxo_yform/blob/master/ytemplates/bootstrap/value.choice.check.tpl.php#L51
https://github.com/yakamara/redaxo_yform/blob/master/ytemplates/bootstrap/value.choice.check.tpl.php#L60
https://github.com/yakamara/redaxo_yform/blob/master/ytemplates/bootstrap/value.choice.check.tpl.php#L71

Für label ist allerdings html Inhalt erlaubt:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label#Technical_summary

Deshalb würde ich das rex_escape für die label entfernen. Wenns keine Einwände gibt, mache ich auch gerne den PR dazu fertig :)

**Comment by alexplusde** [comment]
Das würde ich wenn, dann als objparam sehen (BC) und dann auch global für alle Labels, nicht nur Choice.

Ich unterstütze auf jeden Fall einen PR, da ich es auch im Choice-Feld schon benötigt habe und dann mit der Brechstange das ganze Formular durch html_entity_encode gejagd habe.

**Comment by tbaddade** [comment]
Für das Choice wäre das m.E. keine gute Idee. Das Label wird nicht nur in der Checkbox/Radio verwendet sondern wird auch als [`<option>`](https://github.com/yakamara/redaxo_yform/blob/99a918a798ff6214e6011f2e30cb0e69dd8d16aa/ytemplates/bootstrap/value.choice.select.tpl.php#L52) bzw. im [`<optgroup>`](https://github.com/yakamara/redaxo_yform/blob/99a918a798ff6214e6011f2e30cb0e69dd8d16aa/ytemplates/bootstrap/value.choice.select.tpl.php#L59) ausgegeben. Ein schnelles wechseln zwischen den 4 verschiedenen Ansicht wäre dann nicht mehr gegeben.

**Comment by alexplusde** [comment]
Spricht denn etwas dagegen, in den Templates dort dann html zu verweigern? Ingo und ich reden hier sicher von `<label>`-Tags und nicht von Labels im YForm-Kontext, die auch als optgroup vorkommen.

Und selbst wenn wäre es Aufgabe des Admins, sicherzustellen, kein kaputtes HTML zu liefern.

**Comment by tbaddade** [comment]
@IngoWinter sprach beide Label Varianten an. 
Das was man als Bezeichnung beim Value aber angibt, betrifft diese Zeilen
https://github.com/yakamara/redaxo_yform/blob/99a918a798ff6214e6011f2e30cb0e69dd8d16aa/ytemplates/bootstrap/value.choice.check.tpl.php#L71
https://github.com/yakamara/redaxo_yform/blob/99a918a798ff6214e6011f2e30cb0e69dd8d16aa/ytemplates/bootstrap/value.choice.select.tpl.php#L70

Und da könnte man vermutlich auf das escapen verzichten.

**Comment by IngoWinter** [comment]
@tbaddade inwiefern betreffen Änderung in der `value.choice.check.tpl.php` denn irgendwelche select Geschichten? Mir geht es nur um die label von checkbox und radio.

**Comment by tbaddade** [comment]
Die einheitliche Eingabe bzw. das Verwenden des Choice. Ich sehe das Choice als ein Value an, was eben nur unterschiedliche Ansichten generieren kann.

Das HTML, für die Labels die du ansprichst, müsste im Feld `Auswahlmöglichkeiten (choices)` übergeben werden. Und das empfinde ich etwas problematisch.

**Comment by IngoWinter** [comment]
> Das HTML, für die Labels die du ansprichst, müsste im Feld Auswahlmöglichkeiten (choices) übergeben werden. Und das empfinde ich etwas problematisch.
Warum? Für selects wird es ja weiterhin escaped. Sprich an der Eingabe würde sich exakt gar nichts ändern, nur die Ausgabe würde flexibler/ entwicklerfreundlicher. Immerhin tummeln sich hier schon 2 Entwickler, die das gerne hätten :)

**Comment by alexplusde** [comment]
Live-Seite mit Anwendungsbeispiel auf Anfrage im Slack, falls gewünscht.

**Comment by alxndr-w** [comment]
https://github.com/alexplusde/yform_field/blob/main/lib/yform/value/choice_html.php
