### ISSUE TITLE
generate_key Falsche Beschreibung

### ISSUE THREAD

**Issue by marcohanke** [yakamara/redaxo_yform#727]
Bei der Beschreibung von generate_key steht das gleiche wie bei datestamp
"Ein unsichtbares Feld, in das ein Zeitstempel gespeichert wird, wenn der Datensatz hinzugefügt oder bearbeitet wird."

In der Doku heißt es richtig:
"Generiert ein nicht sichtbares Feld mit zufälligem 32-stelligem Schlüssel, bestehend aus Zahlen und Kleinbuchstaben."

**Comment by tbaddade** [comment]
@marcohanke Kannst du einen PR erstellen? Danke dir.

**Comment by marcohanke** [comment]
Wollte ich gerne,
weiß aber nich an welcher Stelle das überall zu finden ist?

**Comment by tbaddade** [comment]
> weiß aber nich an welcher Stelle das überall zu finden ist?
https://github.com/yakamara/redaxo_yform/blob/master/lib/yform/value/generate_key.php#L56

hier steht auch noch was `datestamp`
https://github.com/yakamara/redaxo_yform/blob/master/lib/yform/value/generate_key.php#L53

**Comment by dergel** [comment]
ist mit dem PR von marco https://github.com/yakamara/redaxo_yform/pull/728 wohl erledigt
