### ISSUE TITLE
data-yform-tools-datepicker (Yform 3.1.1)

### ISSUE THREAD

**Issue by mbodon** [yakamara/redaxo_yform#729]
Hallo, seit dem YForm-Update von Version 3.1 auf 3.1.1. funktioniert das Autoupdate des Inputfeldes durch den Datepicker nicht mehr. Hat eindeutig mit den Änderungen https://github.com/yakamara/redaxo_yform/commit/a31b64899ab84d9b5cbb16c5855144bb5d4d1883 zu tun. Denn wenn ich diese wieder auf "true" stelle funktioniert es wieder (aber dann eventuell die Suche nicht mehr).

**Comment by isospin** [comment]
+1 (kann ich bestätigen)

**Comment by dtpop** [comment]
Danke fürs Issue. Hier identischer Effekt.

**Comment by fietstouring** [comment]
ebenfalls.

**Comment by polarpixel** [comment]
Ich gebe dem hier nochmal einen kleinen Push ... falls das Problem schnell lösbar ist, wäre es super, zumindest ein Quickfix-Lösung zu bekommen. Ich verwende den Datepicker bei ziemlich vielen Projekten, und im Moment halte ich entweder überall yform-Updates zurück oder spiele nach dem alten Update die alte Version der o.a. Datei zurück.
Ich würde auch eine Tafel Schokolade dafür stiften. :-)

**Comment by skerbis** [comment]
Gleicher Fehler hier

**Comment by olien** [comment]
arg....

**Comment by skerbis** [comment]
@dergel ... bitte fixen

**Comment by dergel** [comment]
>Ich würde auch eine Tafel Schokolade dafür stiften. :-)

nehme ich gerne .. hier die Anpassungen. Bei Timepickern geht das nicht, weil die Uhrzeit mehrere Schritte braucht und daher nicht direkt übernommen werden kann.
