### ISSUE TITLE
Tablemanager vs. Redactor vs. Markitup

### ISSUE THREAD

**Issue by skerbis** [yakamara/redaxo_yform#73]
yform erstellt die Textareas wie folgt: 
```
<div class="form-group redactorEditor2-full" id="yform-formular-test">
    <label class="control-label" for="yform-formular-field-2">test</label>
    <textarea class="form-control" name="FORM[formular][2]" id="yform-formular-field-2" rows="10" >test</textarea>
    </div>
```
Das hat zur Folge, dass der komplette Wrapper in den Editor gezogen wird und nicht die Textarea. 
Mit dieser Modifikation https://github.com/yakamara/redaxo_yform/pull/63 ließe sich das ändern und der Textarea eine CSS Klasse zuweisen.

**Comment by skerbis** [comment]
@alexplusde Ja, ist das gleiche Problem

**Comment by alexplusde** [comment]
Eigentlich eine eigene Dublette von https://github.com/yakamara/redaxo_yform/issues/40, oder?
und ich verlinke mal deinen PR hier rein. https://github.com/yakamara/redaxo_yform/pull/63

**Comment by dergel** [comment]
denke ich auch .
