### ISSUE TITLE
be_manager_relation: Choice integrieren

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/redaxo_yform#730]
Man könnte be_manager_relation so umbauen, dass nicht nur selects, sondern auch Radio-Buttons oder Checkboxen möglich wären.

**Comment by dergel** [comment]
Könnte man, aber sehe ich gerade keinen wirklichen Vorteil.

**Comment by alexplusde** [comment]
Ausgabe im Frontend wäre so ein Anwendungsfall

**Comment by alexplusde** [comment]
Ein weiterer Fall wäre eben, Checkboxen und Radio Buttons verwenden zu können und dennoch dabei dennoch Relationen erstellt werden.

**Comment by tbaddade** [comment]
Die Anpassung würde für `select (single)` und `select (multiple)` gelten sowie zwei neue zusätzliche Optionen `checkbox` und `radio`.

**Comment by alexplusde** [comment]
Ähnlich zu #412

**Comment by tbaddade** [comment]
> Könnte man, aber sehe ich gerade keinen wirklichen Vorteil.

Der Vorteil wäre, dass man sich den Kommentar bei Mehrfachauswahl via Tastatur sparen könnte.

**Comment by alxndr-w** [comment]
#412
