### ISSUE TITLE
Notice unter PHP 7.2.18

### ISSUE THREAD

**Issue by marcohanke** [yakamara/redaxo_yform#732]
Unter PHP 7.2.18 bekomme ich bei der Verwendung von datestamp ein Notice
```Notice: Undefined index: format in redaxo/src/addons/yform/lib/yform/value/datestamp.php on line 77```

**Comment by alexplusde** [comment]
Was hast du denn bei Format drin stehen in der Felddefinition?

**Comment by marcohanke** [comment]
Nichts, Ich hab Name und Bezeichnung hinterlegt, Wert soll immer gesetzt werden, das wars.

**Comment by dergel** [comment]
irgendwas im Anzeigeformat ausgewählt sein. Oder ist das vielleicht aus einer alten Version importiert, bei der es noch keine Formatauswahl gab ? Ich sehe im Moment keinen Fehler.
