### ISSUE TITLE
Choice: Warning, wenn Label ein Sprog-Platzhalter ist.

### ISSUE THREAD

**Issue by Pixeldaniel** [yakamara/redaxo_yform#733]
```
Warning: Invalid argument supplied for foreach() in redaxo/src/addons/yform/lib/yform/value/Choice/rex_yform_choice_list.php on line 32
```

```
$yform->setValueField('choice', array('salutation','{{form.label.salutation}}','{{form.option.male}}=Herr,{{form.option.female}}=Frau','1','0','','','','-','','','','','0'));
```

**Comment by dergel** [comment]
Taucht bei mir so nicht auf .. wenn in den Werten eventuell " oder ähnliches drin ist, kann es sein, dass die, je nach Typ ( select und co) zu problemen führt .. Kannst du das nochmal prüfen. Bis dahin schliesse ich das issue

**Comment by alexplusde** [comment]
@dergel ich war live dabei und konnte auch keine Fehleingabe feststellen. Es war wirklich das beschriebene Verhalten wie oben. Es ging, wenn ich mich nicht täusche, um die Labels der Values `{{form.option.male}}=Herr,{{form.option.female}}=Frau`
