### ISSUE TITLE
Validate size

### ISSUE THREAD

**Issue by fietstouring** [yakamara/redaxo_yform#735]
Ich wollte ein Feld über **size** validieren. Bei **300** Zeichen wird keine Eingabe akzeptiert. Habe mehrere Werte probiert: 5, 10, 100, 200. Diese funktionieren alle. 300 aber nicht.

Redaxo 5.7.1
YForm 3.1.1

**Comment by alexplusde** [comment]
Kannst du die genaue Definition deines Validates und des zugehörigen Textfeldes, auf das es sich bezog, hier schreiben? Kann das Problem gerade nicht nachstellen.

Screenshot der Felddefinition geht auch.

**Comment by fietstouring** [comment]
![Bildschirmfoto 2019-05-16 um 10 57 26](https://user-images.githubusercontent.com/1846849/57840703-6b123d00-77c9-11e9-898a-33a434c6992b.png)

**Comment by tbaddade** [comment]
Suchst du vielleicht `size_range` ?

**Comment by fietstouring** [comment]
oh sorry, das hab ich wohl übersehen!

**Comment by alexplusde** [comment]
@tbaddade guter Hinweis! Ich habe das gleich in der Doku angepasst.

**Comment by fietstouring** [comment]
Sorry nochmal, bin wohl ziemlich überarbeitet das ich das nicht genau lese ... :persevere:

**Comment by alexplusde** [comment]
@fietstouring kein Problem! Ich finde schon, dass man das klarer beschreiben kann und das habe ich direkt versucht.

Ansonsten komm gerne Mal im Slack-Channel von REDAXO vorbei, da kann man besser diskutieren und oft auch schneller helfen als hier auf GitHub. Hier sollten Probleme gemeldet werden, Fragen sind eher was für den Slack-Channel. 

https://www.redaxo.org/slack/
