### ISSUE TITLE
Upload Dateien standardmäßig via Email mitsenden

### ISSUE THREAD

**Issue by godsdog** [yakamara/redaxo_yform#737]
Es wäre super wenn Dateien via upload Action standardmäßig via Email mitgesendet werden.
Auch in der normalen email Action.

Mein Workaround bisher:
Hatte mir eine eigene Klasse dazu ergänzt und diese dann im YForm Modul statt "email" -> "email_anhang" verwendet.
```
       // Für 1 Upload Feld im Formular
        $attachements = $this->params['value_pool']['files'];
        
        if (!empty($attachements['upload'])) $attachements = $attachements['upload'];

        if (is_array($attachements)) {
                $mail->AddAttachment($attachements[1], $attachements[0]);
        }
```

**Comment by alexplusde** [comment]
Man müsste auf jeden Fall die Feldnamen übergeben können und dass diese dann ggf zu vorhandenen Anhängen im Mail-Template addiert werden.

Da gab's schon Mal Diskussionen dazu, aber eine Stimme mehr zeigt, dass da Bedarf besteht

**Comment by alexplusde** [comment]
@dergel hier kann zu, einen entsprechenden PR von mir hattest du abgelehnt.

@godsdog melde dich Mal im Slack bei mir, wenn du das brauchst
