### ISSUE TITLE
Datensatz editieren: Abbrechen

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/redaxo_yform#739]
Hatte gerade den Fall, dass ein Redakteur den Datensatz "speichern musste", um zurück in die Übersicht zu gelangen - wobei dann Daten überschrieben wurden. Der Link "Zurück zur Übersicht" war dem Redakteur einfach nicht aufgefallen, hat jedoch nach einem "Abbrechen"-Button gesucht. 

So, wie Blöcke auch mit abbrechen verworfen werden können, sollte das für YForm-Datensätze auch gelten.

**Comment by alexplusde** [comment]
Heute nochmal nen Kunden gehabt. Workaround: Validierung, die niemals eintritt, zum Verhindern des Speicherns. Abbrechen wäre definitiv besser!

**Comment by alexplusde** [comment]
Hier noch ergänzend der Workaround mit einer Validierung
![image](https://user-images.githubusercontent.com/3855487/60582311-d79cc780-9d88-11e9-8b18-6a87c26d77b6.png)

Weiterer Gedanke: Es wäre super, wenn es zusätzlich oben auch noch eine Möglichkeit gäbe, zurück zur Übersicht zu kommen.

**Comment by alxndr-w** [comment]
readonly wird das Problem lösen.
