### ISSUE TITLE
YForm in Addon-Liste bei Usern ohne Rechte

### ISSUE THREAD

**Issue by fietstouring** [yakamara/redaxo_yform#740]
Der Eintrag erscheint auch wenn keine Rechte für YForm vergeben wurden.

![Bildschirmfoto 2019-05-22 um 10 53 36](https://user-images.githubusercontent.com/1846849/58176343-5d195c00-7ca2-11e9-8f2f-8ca315d05caa.png)

**Comment by dergel** [comment]
Ich kann das leider nicht nachvollziehen und habe einige Varianten probiert. Wo taucht das auf und was muss es alles für Vorraussetzungen geben ?

**Comment by fietstouring** [comment]
Hier mein System Bericht... was würdest Du sonst noch brauchen?

<details>
<summary>System report (REDAXO 5.7.1, PHP 7.2.21)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.7.1      |


| PHP           |            |
| ------------: | :--------- |
|       Version | 7.2.21     |
|       OPcache | yes        |
|        Xdebug | no         |


| Database      |                        |
| ------------: | :--------------------- |
|       Version | 5.5.55                 |
| Character set | utf8 (utf8_general_ci) |


| Server        |            |
| ------------: | :--------- |
|            OS | Linux      |
|          SAPI | cgi-fcgi   |
|     Webserver | Apache     |


| Request       |                      |
| ------------: | :------------------- |
|       Browser | Chrome/76.0.3809.132 |
|      Protocol | HTTP/1.0             |
|         HTTPS | yes                  |


| Packages                   |              |
| -------------------------: | :----------- |
|                     backup | 2.3.0        |
|                   be_style | 2.7.1        |
|        be_style/customizer | 2.7.0        |
|            be_style/redaxo | 2.7.0        |
|                    bloecks | 1.4.0        |
|           bloecks/cutncopy | 1.4.0        |
|             bloecks/status | 1.4.0        |
|               cache_warmup | 3.6.0        |
|                   ckeditor | 4.11.3.1     |
|                    cronjob | 2.4.1        |
|                  developer | 3.8.0        |
|           email_obfuscator | 2.0.0        |
|            global_settings | 2.1.0        |
|                    install | 2.5.0        |
|                maintenance | 2.0.0        |
|              massif_minify | 1.2.4-Hotifx |
|                     mblock | 3.1.0        |
|              media_manager | 2.6.0        |
|                  mediapool | 2.5.0        |
|                   metainfo | 2.4.0        |
|                      mform | 5.3.1        |
|                 mform/docs | 1.0          |
|                multiupload | 2.1.3        |
|         navigation_factory | 2.0.1        |
|                  phpmailer | 2.5.1        |
|                    project | dev          |
|           quick_navigation | 3.5.8        |
|                  search_it | 6.6.5        |
|    search_it/documentation | 6.6.5        |
|                      sprog | 1.2.0        |
|                  structure | 2.7.0        |
|          structure/content | 2.7.0        |
|           structure_tweaks | 1.1.1        |
|                      theme | 1.1.1        |
|                   ui_tools | 1.0.0        |
| ui_tools/jquery-minicolors | 2.2.7        |
|                        url | 2.0.0-beta3  |
|                      users | 2.5.2        |
|                      xcore | 1.1.3        |
|                      yform | 3.1.1        |
|                 yform/docs | 3.1.1        |
|                yform/email | 3.1.1        |
|              yform/manager | 3.1.1        |
|                 yform/rest | 3.1.1        |
|                yform/tools | 3.1.1        |
|            yform_usability | 1.4          |
|                   yrewrite | 2.5          |

</details>

**Comment by dergel** [comment]
hier bräucht ich eher die info was klickst du an, was hat der user an rechten an welchen yform tabellem oder teilbereichen.

**Comment by fietstouring** [comment]
![Bildschirmfoto 2019-09-11 um 14 36 49](https://user-images.githubusercontent.com/1846849/64697688-ab48aa00-d4a1-11e9-820d-678aa25866fc.png)
![Bildschirmfoto 2019-09-11 um 14 36 59](https://user-images.githubusercontent.com/1846849/64697689-ab48aa00-d4a1-11e9-9ccf-f8573a6bebee.png)

**Comment by dergel** [comment]
und wie kommst du nun auf den Fehler ? .. Taucht YForm nun links auf, oder nicht ?

**Comment by fietstouring** [comment]
Ja wie in dem Screenshot ganz oben: YForm taucht unter den Addons auf. Klickt man drauf, kommt "Die Tabelle wurde nicht gefunden"

**Comment by dergel** [comment]
bei mir nicht.. Vielleicht ist das bereits gelöst .. Kannst du dir mal die github Version ziehen und drüberspielen ? Ist deine Version aktuell ?

**Comment by fietstouring** [comment]
ok, schaffe es heute nicht mehr, melde mich aber morgen wieder...

**Comment by fietstouring** [comment]
sorry hat länger gedauert. Mit Version 3.2 hat sich das erledigt!
