### ISSUE TITLE
value.mediafile.tpl wirft Fehler beim Datensatz "Übernehmen"

### ISSUE THREAD

**Issue by rkemmere** [yakamara/redaxo_yform#741]
Beim Upload per Mediafile in einer YForm Tabelle wird beim Klick auf "Übernehmen" folgender Fehler geworfen:

> Warning: copy(/tmp/php1A65yY) [failed to open stream: Datei oder Verzeichnis nicht gefunden in redaxo/src/addons/yform/lib/yform/value/mediafile.php on line 190

Bei "Speichern" scheint es zu gehen, bei "Übernehmen" wird das Formular nämlich doppelt gefeuert und wegen dem Fehler kein Datensatz in die DB geschrieben.

Im Medienpool wird die Datei aber angelegt und auch nach /media verschoben.

**Comment by alxndr-w** [comment]
Close wg #1069
