### ISSUE TITLE
Mediafile > PHP-Warning: non-numeric value, wenn keine maximale Größe angegeben

### ISSUE THREAD

**Issue by anveno** [yakamara/redaxo_yform#744]
Moin,

PHP: 7.2.18
Redaxo: 5.7.1

wenn man beim Mediafile keine maximale Größe definiert, taucht bei mir beim Anlegen eines neuen Eintrags die Warning auf: 
Warning: A non-numeric value encountered in redaxo/src/addons/yform/lib/yform/value/mediafile.php on line 37

Ist nicht gravierend, da man ja einfach einen Wert bei der Felddefinition eintragen kann :)

**Comment by alxndr-w** [comment]
@dergel close, mediafile wird es nicht mehr geben #1069
