### ISSUE TITLE
checkbox value ist nicht änderbar - ist immer 1

### ISSUE THREAD

**Issue by iceman-fx** [yakamara/redaxo_yform#745]
Hi,

ich musste nach dem Update auf die aktuellste 3er Version von yForm feststellen, dass alle meine Checkboxen jetzt nur noch eine "1" als Wert übermitteln.

Ist das ein Bug bzw. wie bekomme ich meine alten Value-Werte wieder übermittelt?

**Comment by alexplusde** [comment]
It's a feature, not a bug. Das wurde so entschieden und steht auch im Changelog.

Wenn du das alte Verhalten benötigst, kannst du es mit dem choice-Feld erreichen.

**Comment by iceman-fx** [comment]
OK, danke für die Info.

Das heißt also, alle Formulare anpassen ;-(
Abwärtskompatibel wäre besser.

**Comment by alexplusde** [comment]
(ich war auch kein Fan der Entscheidung, es ist ja auch ein Parameter weggefallen.)

**Comment by alexplusde** [comment]
Kannst du das Issue direkt schließen?
