### ISSUE TITLE
datestamp Feld Anzeige

### ISSUE THREAD

**Issue by DanielWeitenauer** [yakamara/redaxo_yform#750]
Die Ausgabe des datestamp-Feldes zeigt bei Einstellung "0=wird immer neu gesetzt" im Formular stets das Datum des aktuellen Aufrufs, nicht jedoch das Datum der letzten Änderung, da es bereits vor der Ausgabe neu gesetzt wird. 
Sinnvoll wäre jedoch, dass es im Formular wie in der Übersicht das Datum der letzten Änderung zeigt.

**Comment by alexplusde** [comment]
Der Fehler kommt mir bekannt vor, ist es wirklich die aktuelle YForm-Version?

**Comment by DanielWeitenauer** [comment]
Nein, ist es nicht. - Weil ich noch kein Update machen kann, habe ich einfach den betreffenden Commit übernommen: 20dd29d6ff70da009cb11f764abb48271e3ea105
@alexplusde Danke für den Tipp!

**Comment by alexplusde** [comment]
Perfekt. Habe ich mich richtig erinnert. :)
