### ISSUE TITLE
Textarea Feld als Defaultwert für Textarea Felder

### ISSUE THREAD

**Issue by Pixeldaniel** [yakamara/redaxo_yform#752]
Es wäre gut wenn das Defaultwert Feld bei Textareas selbst ein Textarea Feld wäre.
Mein Defaulttext hat im Textfeld alle Zeichenumbrüche verloren. 
Natürlich kann man die wieder im HTML Code eingeben von dem her sicher kein dringliches Issue. 
Wäre halt praktisch.

**Comment by alexplusde** [comment]
Ich finde es essentiell, es sollte ja auch im Table Manager in der Editieransicht direkt möglich sein, eine Textarea mit einem Wert vorzubelegen.

**Comment by dergel** [comment]
ist drin

**Comment by alexplusde** [comment]
Danke @dergel, @pixeldaniel
