### ISSUE TITLE
be_table genauer definieren

### ISSUE THREAD

**Issue by Thoni** [yakamara/redaxo_yform#757]
Hallo,

ich benötigt ein be_table-Feld, welches "be_manager_relation" und "date" enthält.

Kann man das irgendwie definieren oder sind das immer nur reine Textfelder?

Danke Thoni

**Comment by alexplusde** [comment]
Hallo Thoni,

melde dich doch mal im Slack-Channel von REDAXO, denn ich hätte da ein paar Rückfragen - viele Wege führen zum Ziel.

Du kannst dich hier anmelden: https://redaxo.org/slack/

Seit einiger Zeit kann man be_table auch mit anderen Felddefinitionen verknüpfen, prinzipiell ist dein Vorgehen also nicht verkehrt. Wahrscheinlich wäre es jedoch besser, wenn du mit inline-relationen arbeitest - die sind neu in YForm 3.
