### ISSUE TITLE
radio_sql in yform Tabelle nutzen

### ISSUE THREAD

**Issue by dtpop** [yakamara/redaxo_yform#76]
Hammer Addon!!!

In yform/value/radio_sql.php fehlt noch ...

```
    function getDefinitions()
    {
        return array(
            'type' => 'value',
            'name' => 'radio_sql',
            'values' => array(
                'name'  => array( 'type' => 'name',    'label' => 'Name' ),
                'label' => array( 'type' => 'text',    'label' => 'Bezeichnung'),
                'query' => array( 'type' => 'text',    'label' => 'Query mit "select id, name from .."')
            ),
            'description' => 'Hiermit kann man SQL Abfragen als Radioliste nutzen',
            'dbtype' => 'text'
        );
    }

```
Dann taucht das radio_sql Feld auch in der Feldauswahl bei den Tabellenfeldern auf.
Ich glaube es sind noch ein paar andere Feldtypen betroffen. Wenn es sinnvoll ist, kann ich die gerne mal durchgehen.

Lg Wolfgang

**Comment by alexplusde** [comment]
Hi @dtpop,

das ist bestimmt sinnvoll... ich würde dann ein PR einreichen, falls du es nicht selbst in github machen kannst / willst.

**Comment by dergel** [comment]
hat @alexplusde bereits im PR drin.. habe den eben gemerged
