### ISSUE TITLE
index-Value defekt

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#760]
Ich habe ein YForm-Upgrade von 2.3 auf 3.1 vorgenommen. Danach funktionierte das index-Value nicht mehr ordnungsgemäß - es enthielt nur noch `NULL` als Wert an die Datenbank. Ich konnte es in meinem Fall durch hashvalue ersetzen.

**Comment by dergel** [comment]
Funktioniert das Feld ganz allgemein einfach nicht bei Dir ? Oder wurde was beim Update durcheinander gebracht ?

**Comment by dergel** [comment]
@alexplusde

**Comment by alexplusde** [comment]
Ohje, ich weiß nicht mal, was ich vor 18 Tagen gemacht habe. Das müsste ich jetzt auch komplett neu testen und ausprobieren mit verschiedenen Szenarien.

**Comment by dergel** [comment]
ich würde das hier einfach schliessen. Habe das nochmal durchgetestet und sehe keinen Fehler. Wenn der wieder auftaucht - gerne melden.
