### ISSUE TITLE
Validate empty auf mehrere Felder

### ISSUE THREAD

**Issue by 191977** [yakamara/redaxo_yform#764]
Hi, wie in slack besprochen sollte das empty feld so erweitert werden, dass mehrere Felder darauf geprüft werden können, dass mindestens eines davon nicht empty ist. 

Workaround in slack war custom function mit Mehrfachauswahl und...
```function custom_validate($labels, $values, $params)
{
    //true == error
    $isEmpty = true;

    foreach ($values as $value)
    {
        $isEmpty = empty($value);

        if(!$isEmpty)
        {
            break;
        }
    }

    return $isEmpty;
}
```

Danke!

**Comment by dergel** [comment]
Man kann nun mehrere Namen kommasepariert angeben, oder im Manager auswählen, dann wird eine ODER Prüfung verwendet

**Comment by alexplusde** [comment]
oder-Prüfung heißt: Nur eins der Felder muss ausgefüllt werden, aber nie keins?

**Comment by dergel** [comment]
mindestens ein Feld muss ausgefüllt sein. könnte man auch noch mit einer Auswahl ergänzen.
* mindestens eins
* alle
* mindestens x
..

**Comment by 191977** [comment]
Cool, danke schonmal. Klar die weitere Auswahl wäre praktisch

**Comment by dergel** [comment]
gerne als neues issue

**Comment by 191977** [comment]
Allright, kommt nachher
