### ISSUE TITLE
Feldtyp "Checkbox" mit Labels für die Übersichts-Tabelle

### ISSUE THREAD

**Issue by bitshiftersgmbh** [yakamara/redaxo_yform#771]
Das normale Checkbox-Feld (nicht Choice) eignet sich toll, um v.a. auch interne Stati wie "gelesen", "bearbeitet", oder "bezahlt" zu markieren.
Leider gibt es keine Möglichkeit, das vorgeschriebene TINYINT (und damit Value 0 oder 1) für die Übersichtsseiten aufzumotzen.

![issue_yform_checkbox_listlabels](https://user-images.githubusercontent.com/7023022/64539874-8d533c00-d31f-11e9-9e96-e2a78cdfd523.PNG)

Ich wünsche mir für diesen Feld-Typ eine weitere Zeile in der Konfiguration, in der man genau das einstellen kann - ein Label jeweils für 0 und eines für nein. Evtl. mit einem einfach Syntax wie `nein,ja`.

Für Redakteure die oft in den Tables arbeiten (bei uns ist das fast jeder CMS-Kunde) wäre das allemal eine große Verbesserung. Das 0 und 1 verstehen die auch, aber das ist dann doch eher etwas für uns Entwickler.

**Comment by alexplusde** [comment]
Notfalls kannst du choice dafür benutzen

**Comment by tbaddade** [comment]
Ich würde da eher ein Callable für die Labels bevorzugen.

```
function($checkbox) {
    return $checkbox === 0 ? 'Null' : 'Eins';
}
```

**Comment by elpschulzo** [comment]
> Notfalls kannst du choice dafür benutzen
Wozu? Für genau so ein einfaches Haken-Feld wie ich es brauche gibt's den Check-Box-Typ doch oder? Sonst hätte man den ja auch auf deprecated setzen mit Einführung von Choice.

> Ich würde da eher ein Callable für die Labels bevorzugen.
Damit wär ich auch fein.

**Comment by alexplusde** [comment]
Ich würde das weiterhin in der Felddefinition sehen, damit auch das Suchfeld damit ausgestattet wird. Auf Deutsch aktuell:

![image](https://user-images.githubusercontent.com/3855487/66508219-e7871e80-ead0-11e9-91d8-7a73f67f1aff.png)

Das tolle war mal, dass man hier wirklich sagen konnte: heißt es offline/online, nein/ja, deaktiviert/aktiviert, frei/gebucht, ... 

Man kann ja auch in der Felddefinition machen und Callable überschreiben lassen.

**Comment by alxndr-w** [comment]
Ist erledigt: #885
