### ISSUE TITLE
YORM :: Instanz beenden nach/in ->delete()

### ISSUE THREAD

**Issue by skerbis** [yakamara/redaxo_yform#772]
Nach dem Löschen eines Datensatzes sollte man

`rex_yform_manager_dataset::clearInstance(['tabelle', $id]);`
@gharlan  danke. 

ausführen um anschließend weiter arbeiten zu können. 

Ich wollte im Anschluss eine Datei aus dem Medienpool löschen die mit dem Datensatz verknüpft war. Als Zwischencheck benutze ich die Lösung aus Yakme um sicherzustellen, dass die Datei nicht wo anders in Verwendung ist. 

Anscheinend greift da noch ein Cache, so dass die Datei immer noch in Verwendung erscheint. 

Gregor meint clearInstance sollte in der delete-Methode angewendet werden. 
https://friendsofredaxo.slack.com/archives/C1BAXLN2F/p1567939956334000

**Comment by alexplusde** [comment]
Ein Danke für @gharlan sollte man auf jeden Fall unabhängig von YOrm ausführen ;)

**Comment by dergel** [comment]
Ist nun drin .. bitte testen
