### ISSUE TITLE
FR: Signaturen oder Mail/Vorlagen Templates

### ISSUE THREAD

**Issue by Hirbod** [yakamara/redaxo_yform#773]
Hi, also Feature Request würde ich mir gerne Signaturen für E-Mail Templates wünschen - ggf auch Templates, welche z.B einen %CONTENT% haben und nur der Inhalt geändert wird.

Beim Thema Footer könnte ich mir Vorstellen, das man einfache eine weitere Tabelle hat und Signaturen hinterlegen kann, welche ggf über REX_FORM_SIGNATURE[id=1...2...3] hinzugefügt werden können. Sicherlich ist sowas in der Art mit "Sprog" und bisschen PHP Code möglich, aber es wäre ein nettes Feature ab Werk.

**Comment by tbaddade** [comment]
Was spricht dagegen das mit Spross zu machen?

Mit

```
{{ signature|markdown }}
```

erhälst du auch HTML

**Comment by Hirbod** [comment]
Werden diese Platzhalter überhaupt in den Mailtemplates ersetzt?

**Comment by tbaddade** [comment]
> Werden diese Platzhalter überhaupt in den Mailtemplates ersetzt?

Ich meine, dass ich es schon mal so gelöst hatte. Bin mir nur grad nicht sicher, ob ich den OUTPUT_FILTER selber aufrufen musste oder ob das schon initial passiert.

**Comment by alexplusde** [comment]
Geht auch mit dem Addon Globale Einstellungen sehr gut, da ja PHP erlaubt ist.

**Comment by alexplusde** [comment]
Für Sprog sowas wie:

`<?= sprogdown("{{ signature|markdown }}") ?>`

**Comment by tbaddade** [comment]
Hinweis: `sprogdown` eher dann aufrufen, wenn der Text mehrere Platzhalter beinhaltet. Hier dann am besten die komplette E-Mail vielleicht Parsen lassen.

**Comment by alexplusde** [comment]
Ok, in seinem Fall wäre das dann?

**Comment by alexplusde** [comment]
@dergel siehst du hier konkreten Nutzen? Sonst würde ich lieber ne Anleitung schreiben, wie man das Thema anders löst.

**Comment by dergel** [comment]
ich sehe Signaturen nicht hier als Platzhalter im YForm. Die E-Mails haben die Signaturen entweder bereits bei sich, oder per Platzhalter über Sprog, PHP oder Co.

Solche Dinge: `REX_FORM_SIGNATURE[]` lassen sich einfach auch außerhalb von YForm bauen
