### ISSUE TITLE
Wunsch:: BE_Relation :: Frontend-Fallback

### ISSUE THREAD

**Issue by skerbis** [yakamara/redaxo_yform#775]
Ich habe ein Formular, welches im Backend und im Frontend (via Yorm) bearbeitet wird. 
Im Backend ist es sehr nützlich via Popup auch neue Datensätze anlegen zu können. 
Darauf muss ich leider verzichten wenn ich dieses Feld auch im Frontend einsetzen möchte. 
Hier wünsche ich mir, dass das Feld sich im Frontend zu einem normalen Select oder Multiselect wandelt. 

Mir ist klar, dass ich das Feld aus dem Dataset entfernen kann und durch ein anderes ersetzen kann. Leider ändert sich dadurch natürlich die Position in der Ausgabe.

**Comment by skerbis** [comment]
Choice hat ein Fallback? Ja dann ok

**Comment by skerbis** [comment]
Es geht mir ja um einen Ersatz für das yform Widget im Frontend

**Comment by alexplusde** [comment]
duplicate #412
