### ISSUE TITLE
Datetime Feld funktioniert nicht

### ISSUE THREAD

**Issue by pschuchmann** [yakamara/redaxo_yform#778]
Hey,

ich habe eben versucht ein datetime Feld inklusive yform Tools (datetimepicker und input mask) anzulegen. Die Werte werden allerdings nicht sauber gezogen, bzw. habe ich den Eindruck, dass Ausgabeformat und das zu speichernde Format für die Tabelle irgendwie nicht zusammen passen. YForm Version ist die 3.2.

Im Slack hatte ich Hilfe und in Version 3.1 schien das alles noch zu funktionieren, Fehler wurde dann bestätigt in 3.2

**Comment by godsdog** [comment]
In der 3.1.1 funktionierte es noch. Problem liegt in : `/src/addons/yform/lib/yform/value/datetime.php`

**Comment by pschuchmann** [comment]
#779 sollte das Problem lösen. Es sieht so aus als wurde das im Backend definierte Format nie verwendet, sondern stets der Default aus der Value Klasse.

**Comment by dergel** [comment]
> DB-Wert:
> 2019-09-17 09:37:36
> Angezeigter Wert in yForm Tabelle:
> 20.01.2092 06:12:00

ist bei mir nicht so .. kannst du mir den yform export des schemas schicken ? .. und vielleicht noch einen Datenexport. dann kann ich mir das anschauen.

**Comment by pschuchmann** [comment]
Ich hab dir die Sachen per Direktnachricht im Slack geschickt. Falls du irgendwo ein eigenes Projekt hast mit datetime Feldern und dort auf 3.2 geupdated hast, funktioniert es dort auch noch?

**Comment by tbaddade** [comment]
@pschuchmann Schau mal in die Tabelle `rex_yform_field` was dort für das value als Format gesichert wurde.

**Comment by pschuchmann** [comment]
@tbaddade `DD.MM.YYYY HH:ii:ss` steht drin. Sobald ich aber in der Version aus 3.2 das Format im Value dumpe, bekomme ich die `CONST` aus der Klasse zurück.

**Comment by tbaddade** [comment]
> DD.MM.YYYY HH:ii:ss steht drin.

Das ist der Fehler. Dieses Format existiert nicht in der Auswahl für das Anzeigeformat.

**Comment by pschuchmann** [comment]
@tbaddade Habe ich mehrfach getestet und es ging nicht. So auch jetzt wieder, trotz Korrektur. Mit Klasse aus 3.1.1 alles korrekt, in 3.2 falsche Werte.

Dumpe ich in der Funktion `enterObject` das Format erhalte ich unterschiedliche Werte. Sollten hier nicht die gleichen Werte heraus kommen?

**Comment by tbaddade** [comment]
@dergel Hier gibt es tatsächlich einen Bug. Ich konnte das Verhalten nachstellen.

Es liegt wohl hier dran
```
{"data-yform-tools-datetimepicker":"DD.MM.YYYY HH:ii"}
```

Eine Änderung auf 
```
{"data-yform-tools-datetimepicker":"YYYY-MM-DD HH:ii"}
```
speichert dann die Werte korrekt. Die Werte aus dem Picker scheinen nicht in das mysql Format umgewandelt zu werden.

**Comment by pschuchmann** [comment]
Dadurch steht das Format auch auf dem Default der Value Klasse, daher ging es vermutlich auch bei dir @dergel.

Was passiert bei dir, wenn du das Format in deiner Testumgebung umstellst?

Das Gefährliche daran ist ja, wenn man das Formular mit einem anderen Format ausgegeben hat, das Update macht und dann einen Datensatz speichert, ist der Datensatz, bzw. das datetime Feld, futsch.

**Comment by dergel** [comment]
Sollte nun passen. Dennoch würde ich mich über einen test von euch freuen.

**Comment by pschuchmann** [comment]
Hab gerade etwas getestet damit. Das Anzeigeformat kann ich bei allen drei Typen ändern und es wird sauber ausgespielt.

Bei `datetime` habe ich dennoch ein Problem mit der Uhrzeit. Wenn das Datum voreingestellt werden soll, klappt das problemlos, Uhrzeit ist allerdings immer 00:00:00. War das früher nicht auch mit der aktuellen Zeit? Ändere ich das von Hand und speichere den Datensatz, steht es korrekt in der Datenbank, aber beim erneuten Öffnen des Datensatzes ist es wieder 00:00:00.

**Comment by dergel** [comment]
oja.. sehr gut, dass du das getestet hast. ist nun korrigiert, kannst du date und time auch mittesten ?

**Comment by pschuchmann** [comment]
Sieht gut aus. Uhrzeit ist nun auch voreingestellt. Auch wenn andere Formate als das SQL Format gewählt sein sollten. Und bereits vorhandene Datensätze funktionieren auch!

**Comment by pschuchmann** [comment]
Wenn ich bei `time` das Format umstelle, kriege ich es im korrekten Format angezeigt, bearbeite ich den Datensatz erscheint wieder der Standard sehe ich gerade.

**Comment by dergel** [comment]
wegen time. das ist auch richtig so. Die Eingabe unterscheidet sich nicht in den Ländern (so viel ich weiß). Deswegen ist nur die Ansicht in der Liste mit dem Format
