### ISSUE TITLE
select_sql: Angabe in Höhe der Auswahlbox wird ignoriert

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#78]
Es fehlt in der Ausgabe multiple=multiple 

Table Manager:
![image](https://cloud.githubusercontent.com/assets/3855487/16187194/2fe359be-36cf-11e6-94fd-8905be039146.png)

Datensatz eintragen:
![image](https://cloud.githubusercontent.com/assets/3855487/16187200/3796ed24-36cf-11e6-933e-151e2db96f68.png)

**Comment by DanielWeitenauer** [comment]
Die Höhe wird nur übernommen, wenn die Checkbox "mehrere Felder möglich aktiviert" ist, damit wird die "multiple" Option gesetzt.

**Comment by alexplusde** [comment]
Dann hat mich wohl mein Gedächtnis getäuscht. Ich meinte, dass das in R4 auch ohne multiple möglich war, um direkt eine Auswahl zu treffen.
(Eigentlich war das nur eine Krücke, weil radio_sql in yform noch nicht verfügbar ist)
