### ISSUE TITLE
Action redirect abbrechen

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#781]
Sobald das Formular Fehler wirft, sollte die action redirect nicht ausgeführt. Ansonsten bleiben Fehler unentdeckt.

- csrf error
- insert query error
- ...

**Comment by alexplusde** [comment]
An welcher Position wurde redirect bei dir verwendet? Vor oder nach der Validierung? (soll: nach)

**Comment by tbaddade** [comment]
Vordefinierte Aktionen

> An welcher Position wurde redirect bei dir verwendet? Vor oder nach der Validierung? (soll: nach)

Steht an letzter Stelle im Builder. Keine Validierung lieferte false. Die Fehler `csrf error` bzw. `insert query error` haben auch nichts mit der Validierung zu tun. 

`insert query error` kann passieren, wenn ein Key/Label Sonderzeichen enthält.

**Comment by alexplusde** [comment]
Ok, logisch. Danke für die Erläuterung

**Comment by dergel** [comment]
Leider verstehe ich das ncnt . redirect ist eine action und wird erst ausgeführt, wenn das formular richtig durchläuft, also auch wenn csrf nicht auftaucht. Kannst du es mir nochmal erklären ?
