### ISSUE TITLE
HTML-IDs sind mehrfach vergeben 

### ISSUE THREAD

**Issue by christophboecker** [yakamara/redaxo_yform#783]
Da stimmt was nicht mit den HTML-IDs.

Ich habe ich folgende Situation: Das Formular ist für die Tabelle 'rex_kv30_dokument'. Es gibt ein Feld 'datum'. Die ID für dieses Feld lautet also 'yform-data_edit-rex_kv30_dokument-datum'.

Über ein Relationen-Feld ('be_manager_relation') binde ich eine weitere Tabelle 'rex_kv30_historie' im Verfahren 'inline (multiple -1)' ein. Auch in der gibt es ein Feld 'datum'. Damit müsste das entsprechende Feld im Formular eigentlich die ID 'yform-data_edit-rex_kv30_historie-datum' haben. Da es ein eingebundenes Inline-Formular ist, vergibt YForm die IDs nach einem anderen Schema beruhend auf dem Namen des Hautformulars. 

Und deshalb hat das Feld im Inline-Formular ebenfalls die ID 'yform-data_edit-rex_kv30_dokument-datum'.

Und wenn man weitere Inline-Formulare hinzufügt, haben die ebenfalls diesselbe ID. 

Muss das so sein? Ich habe mal gelernt, es darf eine ID nur einmal geben im Dokument. 

Hier mal das HTML als Kopie aus dem Entwicklertool des Browsers. Alle Komponenten sind auf dem aktuellen Stand (Core 5.8, YForm 3.2). 

![grafik](https://user-images.githubusercontent.com/10065904/66598303-0ead2100-eba1-11e9-8d1f-bd02ae29aac4.png)

**Comment by dergel** [comment]
kannst du mir das Tableset exportieren ? irgendwie bekomme ich das hier nicht nachgebaut

**Comment by christophboecker** [comment]
Ich hoffe es funktioniert. Hab es runtergestripped auf 2 Tabellen. rex_kv30_dokument ist die Haupttabelle, rex_kv30_historie wird inline eingebunden

[Archiv.zip](https://github.com/yakamara/redaxo_yform/files/3768644/Archiv.zip)

Ungefähr so sieht der Screen aus:
<img width="600" alt="grafik" src="https://user-images.githubusercontent.com/10065904/67507907-31a2ff00-f690-11e9-9fc9-514bc2c55ecf.png">

Und das hier ist ein Auszug aus dem HTML:
<img width="662" alt="grafik" src="https://user-images.githubusercontent.com/10065904/67508037-7890f480-f690-11e9-8681-134f572d004b.png">

**Comment by dergel** [comment]
Lange her - sorry. aber nun angegangen.. Die IDs sollten nun unique sein. Gerne testen und bei Probleme melden .. bis dahin schliesse ich

**Comment by christophboecker** [comment]
Sieht gut aus. Danke.
