### ISSUE TITLE
Bug: be_manager-relation mit "popup (multiple n-1)" 

### ISSUE THREAD

**Issue by christophboecker** [yakamara/redaxo_yform#784]
Da ist wohl ein Bug in der Vergabe der ID, wodurch Popups bei geschachtelten relationen auf die Bretter gehen.

**Das Testumfeld:**

Tabellen
* 'rex_kv30_verein' mit einer Vereinsliste (Kürzel, Name)
* 'rex_kv30_historie' mit Bootsinformationen (Referenzdatum, Name, Eigner, Verein)
* 'rex_kv30_dokument' mit alten Dokumenten. 

Über be_manager_relation wird aus `rex_kv30_dokument` auf `rex_kv30_historie` verlinkt. 
Der Link ist 1:n; zu einem Dokument gibt es einen oder mehrere Einträge in Historie. Die Darstellung im Formular von `rex_kv30_dokument` ist **inline (multiple n-1)**. 

Über be_manager_relation wird aus `rex_kv30_historie` auf `rex_kv30_verein` verlinkt. 
Der Link ist 1:n, denn zu einem Eintrag können mehrere Vereine zugeordnet sein
(Multimitgliedschaften waren damals nicht selten). Die Darstellung
im Formular von `rex_kv30_historie` ist **popup (multiple n-1)**.

Das Problem entsteht in Formular zu `rex_kv30_dokument`. Der Problembär ist das Popup-Fenster von `rex_kv30_historie` zu `rex_kv30_verein`.

**Szenario 1: es gibt schon einen oder mehrere Einträge in `rex_kv30_historie`.**

Die Formulare werden untereinander angezeigt. Sie können problemlos bearbeitet werden. Auch ist es problemlos möglich, Einträge in `rex_kv30_verein` auszuwählen und dem gewünschten Subformular ('rex_kv30_historie') zuzuweisen.

Super, alles bestens!

**Szenario 2: Einen neuen Sub-Datensatz `rex_kv30_historie` einfügen.**

Egal ob als erster überhaupt oder als zusätzlicher Datensatz: es wird planmäßig ein leeres Formular geöffnet. Daten können problemlos erfasst werden. Auch ist es problemlos
möglich, Einträge in `rex_kv30_verein` auszuwählen und dem Subformular (`rex_kv30_historie`) zuzuweisen. 

Super, alles bestens!

**Szenario 3: Einen weiteren Sub-Datensatz `rex_kv30_historie` einfügen.**

Der Datensatz wird angelegt und kann in bezug auf "Eingabefelder" normal befüllt werden. Aber jede Auswahl aus dem Popup für `rex_kv30_verein` landet im zuvor erfassten ersten neuen Datensatz.

Crash.

**Analyse**
Die Bestandsdaten werden beim Aufbau der Seite in DIVs gepackt, deren ID von einer Basiskennung (Zufallswert?) hochgezählt wird und damit eindeutig sein. Auffällig ist hier schon, dass die neuen Datensätze eine formal andere ID aufweisen, die aber auch eindeutig ist
```html
<!-- Bestand -->
<div class="row" id="y4fcc2f1ef32397efad998360ca7475fe4ffc5695-1" data-yform-be-relation-item="y4fcc2f1ef32397efad998360ca7475fe4ffc5695-1">
    ...
</div>
<div class="row" id="y4fcc2f1ef32397efad998360ca7475fe4ffc5695-2" data-yform-be-relation-item="y4fcc2f1ef32397efad998360ca7475fe4ffc5695-2">
    ...
</div>
...
<!-- neu -->
<div class="row" id="rex_kv30_dokument-rex_kv30_historie-id_dokument-6" data-yform-be-relation-item="rex_kv30_dokument-rex_kv30_historie-id_dokument-6">
    ...
</div>
<div class="row" id="rex_kv30_dokument-rex_kv30_historie-id_dokument-7" data-yform-be-relation-item="rex_kv30_dokument-rex_kv30_historie-id_dokument-7">
    ...
</div>
```

Etwas tiefer analysiert hier die DIVs für die Relationen-Felder, deren Popups scheitern:
```html
<!-- Bestand -->
<div class="row" id="y4fcc2f1ef32397efad998360ca7475fe4ffc5695-1" data-yform-be-relation-item="y4fcc2f1ef32397efad998360ca7475fe4ffc5695-1">
    ...
    <div class="form-group formbe_manager_relation" id="yform-data_edit-rex_kv30_dokument-verein">
        <label ... for="yform-data_edit-rex_kv30_dokument-field-4">Verein</label>
        <div class="input-group">
            <select name="YFORM_DATASETLIST_SELECT_252032311624694" ... id="YFORM_DATASETLIST_SELECT_252032311624694">
                ...
            </select>
            <input type="hidden" name="FORM[data_edit-rex_kv30_dokument][7][0][4]" id="YFORM_DATASETLIST_252032311624694" value="...">
            ...
        </div>            
    </div>
    ...
</div>
<div class="row" id="y4fcc2f1ef32397efad998360ca7475fe4ffc5695-2" data-yform-be-relation-item="y4fcc2f1ef32397efad998360ca7475fe4ffc5695-2">
    ...
    <div class="form-group formbe_manager_relation" id="yform-data_edit-rex_kv30_dokument-verein">
        <label ... for="yform-data_edit-rex_kv30_dokument-field-4">Verein</label>
        <div class="input-group">
            <select name="YFORM_DATASETLIST_SELECT_252032311690504" ... id="YFORM_DATASETLIST_SELECT_252032311690504">
                ...
            </select>
            <input type="hidden" name="FORM[data_edit-rex_kv30_dokument][7][2][4]" id="YFORM_DATASETLIST_252032311690504" value="...">
        </div>            
    </div>
    ...
</div>
...
<!-- neu -->
<div class="row" id="rex_kv30_dokument-rex_kv30_historie-id_dokument-6" data-yform-be-relation-item="rex_kv30_dokument-rex_kv30_historie-id_dokument-6">
    ...
    <div class="form-group formbe_manager_relation" id="yform-data_edit-rex_kv30_dokument-verein">
        <label ... for="yform-data_edit-rex_kv30_dokument-field-4">Verein</label>
        <div class="input-group">
            <select name="YFORM_DATASETLIST_SELECT_252032311690274" ... id="YFORM_DATASETLIST_SELECT_252032311690274">
            </select>
            <input type="hidden" name="FORM[data_edit-rex_kv30_dokument][7][6][4]" id="YFORM_DATASETLIST_252032311690274" value="">
            ...
        </div>
    </div>
    ...
</div>
<div class="row" id="rex_kv30_dokument-rex_kv30_historie-id_dokument-7" data-yform-be-relation-item="rex_kv30_dokument-rex_kv30_historie-id_dokument-7">
    ...
    <div class="form-group formbe_manager_relation" id="yform-data_edit-rex_kv30_dokument-verein">
        <label ... for="yform-data_edit-rex_kv30_dokument-field-4">Verein</label>
        <div class="input-group">
            <select name="YFORM_DATASETLIST_SELECT_252032311690274" ... id="YFORM_DATASETLIST_SELECT_252032311690274">
            </select>
            <input type="hidden" name="FORM[data_edit-rex_kv30_dokument][7][7][4]" id="YFORM_DATASETLIST_252032311690274" value="">
            ...
        </div>
    </div>
    ...
</div>
```
Wie man unschwer erkennt, haben viele Elemente identische IDs `<div class="form-group formbe_manager_relation" id="yform-data_edit-rex_kv30_dokument-verein">` oder verweisen auf nicht existente IDs `<label ... for="yform-data_edit-rex_kv30_dokument-field-4">`.

Im Select- bzw. Input-Tag sind offensichtlich wieder Zufallszahl-IDs zu finden. In den Bestandsdaten sind diese Nummern jeweils eindeutig. Anders bei den neuen Datensätzen. Sie haben stets dieselbe ID. Das kann nicht gut gehen und tut es auch nicht.

**Gegenprobe**

Über die Entwicklertools im Browser für den zweiten neuen Datensatz die Nummern geändert und auch die JS-Aufrufe hinter den Buttons angepasst - voila, es klappt

**Fazit:**
Die JS-Routine hinter dem Plus-Button für neue Sub-Datensätze erwischt nicht alle zu ändernden IDs.

**Comment by christophboecker** [comment]
Hängt irgendwie auch hiermit #783 zusammen

**Comment by christophboecker** [comment]
Hier mal eine Lösungs-Idee: 

Der Code zum Einbau des neuen Datensatzes holt as HTML-Template aus einem Attribut im Header des Container. Bevor es in den DOM gehängt wird, ändert das Script schon IDs, indem der laufende Index eingebaut wird.  Also müsste dort noch etwas Code rein, der auch die relevanten Nummern bei Popup-Relationen um den Index verlängert. 
```php
  container.find('[data-yform-be-relation-add]').each(function() {
    $(this).on('click', function() {
      ...      
      var $wrapper = $(this).closest('[data-yform-be-relation-form]');
      ...      
      var prototypeForm = $wrapper.attr('data-yform-be-relation-form');
      var index = $wrapper.attr('data-yform-be-relation-index');
      ...      
      ++index;
      ...      
      var rep = new RegExp(relationKey, "g");
      prototypeForm = prototypeForm.replace(rep, index);
      // hier die Keys für Popup-Relationen anpassen...      
      prototypeForm = prototypeForm.replace(/onclick="(move|open|delete)YFormDataset(List|)\(\d*/g, '$&'+index);
      prototypeForm = prototypeForm.replace(/="YFORM_DATASET(.*?\d)\d*/g, '$&'+index);
      //--
      ...
    });
  });
```
Ich hab mal das hier getestet: in meinem Umfeld hat es funktioniert, aber ich weiß nicht, ob die beiden Zeilen alle Varianten erwischen.

Das Original ist hier: https://github.com/yakamara/redaxo_yform/blob/1928b0b5bd9254f4674713b109baaad30d54f9e6/plugins/manager/assets/manager.js#L130-L166

**Comment by christophboecker** [comment]
Obige zwei zusätzlichen Zeilen ändern wie es aussieht zuverlässig das HTML. Das bedeutet leider nicht, dass damit das Problem gelöst wäre. Nachwievor gibt es falsche Popup-Aufruf:
![grafik](https://user-images.githubusercontent.com/10065904/66844542-beeaa300-ef6e-11e9-8375-590aac96d74d.png)
Rechts im Inspektor die um den Index 19 ergänzte Nummer. Links in der Url des Popups eine andere Nummer - die nirgens vorkommt.

**Comment by dergel** [comment]
Welche Version hast du verwendet ? Kannst du die github Version benutzen und dann nochmal prüfen ?

**Comment by christophboecker** [comment]
Ich nutze die aktuellen Versionen aus dem Installer. Hab´s eben auch mir der Github-Version probiert, ohne meine ganzen Workarounds. Klappt nicht; beim Einfügen von Inline-Formularen bekommen die dieselbe Nummer. Evtl muss man ganz anders denken und den Aufruf anders gestalten: die onclick-Attribute in den Links nicht direkt mit den Parametern versehen, sondern nur  'this' übergeben. Und die Parameter dann in der aufgerufenen Funktion aus data-attributen des mit 'this' erreichbaren Tags auszulesen.

**Comment by dergel** [comment]
gibst du mir noch ein ok ?

**Comment by christophboecker** [comment]
sieht noch immer gut aus.
