### ISSUE TITLE
Bug: Table Manager Upload-Feld: Datei lässt sich nicht mehr ansehen

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#785]
Ist
* in der Listenübersicht führt ein Klick zum Datensatz.
* in der Datensatz-Ansicht kann man die Datei nur löschen

Soll
* in der Listenansicht soll ein Klick die Datei öffnen
* in der Datensatz-Ansicht soll man die Datei ebenfalls öffnen können

![image](https://user-images.githubusercontent.com/3855487/66672366-6c537300-ec5e-11e9-8efb-b61fe281b2fd.png)

**Comment by dergel** [comment]
Bei mir wird die Datei in der Listenansicht geöffnet.
Nun kann man die Datei im Backend, wenn der Datensatz angelegt ist, auch abrufen.

**Comment by alexplusde** [comment]
Nun. Bei mir halt nicht 🤷‍♂️. Wie debuggen?

**Comment by alexplusde** [comment]
> Hast du die aktuelle github version ? .. Kann ich mir das bei dir mal ansehen ? .. iszt das live ? PM ?

> woanders getestet und testen lassen.. passt soweit

Nein. Ja. Ja. Ja. 

Ok,

**Comment by alexplusde** [comment]
Scheint aktuell immer noch nicht zu funktionieren...

**Comment by dergel** [comment]
aktuell heisst, mit der aktuellen github version ? schick mal eine Info durch wo ich das testen kann
