### ISSUE TITLE
Upload-Feld: Datei selben Namens erhält keinen Suffix

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#786]
Ich lade Datei X hoch, anschließend Datei Y mit gleichem Dateinamen. Diese ersetzt Datei X. Soll: Suffix erhalten und nicht X überschreiben.

Grund: Datensatz von X ist dann verkehrterweise mit Y verknüpft, die ehemalige Datei zu X ist überschrieben.

**Comment by dergel** [comment]
Hmm.. gerade verschiedene Kombinationen probiert und kann den Fehler nicht nachvollziehen und weiss gerade auch nicht genau was du meinst. Geht es um zwei Upload Felder innerhalb eines Datensatzes ? Und was für ein Suffix ? .. Kannst du das mit echten Namen nochmal beschreiben ?

**Comment by tbaddade** [comment]
Ich denke, dass es zwei unterschiedliche Datensätze sind die ein Uploadfeld haben. Datensatz Y bekommt dieselbe Datei eingespielt die zuvor bereits bei X geladen wurde.

**Comment by alexplusde** [comment]
Genau, was @tbaddade sagt.

fiktives Szenario (nur zum Verständnis): Jens Mayer lädt in einem Bewerbungsformular `lebenslauf_mayer.pdf` hoch. Einen Tag später lädt Sabine Mayer ebenfalls ein `lebenslauf_mayer.pdf` hoch. 

Erwartetes Verhalten: Das Upload-Feld legt die Datei als `lebenslauf_mayer_1.pdf` ab.

Tatsächliches Verhalten: Die Datei von Jens Mayer wird überschrieben.

Im Table Manager zeigen beide Datensätze dann auf die zuletzt hochgeladene Datei.

**Comment by dergel** [comment]
Ich habs geprüft. Passiert bei mir nicht .. Hast du auch wirklich die Datei heruntergeladen. Die Datei wird im Manager mit ID_filename abgelegt und entsprechend des Feldenamens in diesen Ordner. Es muss keine Namensänderungen passieren. Im Link muss die id mit übergeben werden, damit es klappt. Kannst du das nochmal prüfen ?

**Comment by alexplusde** [comment]
Ich habe das jetzt getestet und kann das Problem eingrenzen.

Im besagten Formular werden mehrere Teilnehmer aufgenommen und dazu eine eigene Action programmiert, die aus dem SQL Value Pool den Dateinamen nimmt (ohne Hash-Präfix), sodass die Zuordnung zur Datei auf dem Dateisystem verloren geht.

Die Frage müsste also lauten: Wie kann ich in den Datensatz den Dateinamen MIT Präfix, so wie im Dateisystem, auch in die Datenbank schreiben mit meiner eigenen Action.

**Comment by alexplusde** [comment]
Siehe auch #725 

@dergel wenn du mal eine freie Minute hast - du kannst es mir sicher leicht beantworten und ich kümmere mich dann um einen fix oder den Doku-Eintrag oder schließe hier mind. 3 Issues zu dem Thema ;)

**Comment by brandes-webdesign** [comment]
Ich kann das von Alex bestätigen.
Mit dem value | mediafile

Wenn ich eine Datei mit exakt gleichem Namen hochladen, wird diese im Medienpool überschrieben, anstatt eine Kopie anzulegen, wie es ja üblicher Weise im Medienpool der Fall ist.

Wenn die Datei allerdings **geschütz ist per media_auth**, dann wird nichts überschrieben.

Es kommt in beiden Fällen folgender Fehlertext:

> Falls Sie die Datei mehrmals hochladen, wird es automatisch überschrieben!
> Die Datei kann nicht gelöscht werden.
> Sollten Sie Änderungen vorgenommen haben, bitten wir Sie die Datei/File als Version 2 (zwei) im Dateinamen zu vermerken!

**Comment by dergel** [comment]
ich habe es gerade nachgesehen:

```
$this->params['value_pool']['email'][$this->getName()] = $this->getValue();
$this->params['value_pool']['email'][$this->getName().'_folder'] = $this->getValue();
```

so wirds abgelegt.- also müssten die Informationen doch verfügbar sein, oder ? .. Leider ist mir das Problem noch nicht klar. Willst du mit anSlacken ? ;) Ich schliesse das hier. sofern es ein Bug oder Featurewunsch ist, können wir ja was neues aufmachen.

**Comment by brandes-webdesign** [comment]
Hallo Jan,
SORYY. Die Anmerkung von mir hat sich erledigt.
Ich habe da komplett falsch getestet und der Fehlertext war auch von mir selbst.

Wenn ich mit dem value | mediafile Dateien hochlade, dann wird die Datei bei mir mit einem suffix ergänzt und korrekt hochgeladen in dem Medienpool.
