### ISSUE TITLE
Action : create_table : Tabelle wird nicht im Manager angezeigt

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#790]
Ich meine es war bei der alten action `create_db` so, dass die Tabelle sofort als YForm-Tabelle registriert wurde. Jetzt muss man diese erst migrieren. Absicht?

**Comment by alexplusde** [comment]
Die action müsste eigentlich auch create_table heißen.

Meines Wissens musste schon immer manuell migriert werden.

**Comment by tbaddade** [comment]
> Die action müsste eigentlich auch create_table heißen.

Da wären wir wieder beim Thema, welches du letztens im Slack ansprachst. Lese dir noch einmal den Titel und den Kommentar genauer durch. ;)

**Comment by alexplusde** [comment]
Punkt geht an dich! Sie heißt ja auch schon so, ich hatte sie nur schon sehr lange nicht mehr in Benutzung... wegen o.g. Hürde. Wenn man migriert, muss man alle Felder neu definieren.

Finde den Vorschlag jedenfalls gut!

**Comment by dergel** [comment]
Das ist Absicht, ich sehe nicht, dass man durch ein Formular eine Tabelle generiert.
