### ISSUE TITLE
Darstellung "be_manager_relation" im Backend in der Listenansicht falsch

### ISSUE THREAD

**Issue by MC-PMOE** [yakamara/redaxo_yform#791]
In der Liste werden alle Datensätze der verknüpften Tabelle angezeigt anstatt nur der ausgewählten. Gespeichert wird aber richtigerweise nur der ausgewählte Datensatz.
Tritt scheinbar nur auf wenn für "Mehrfachauswahl" -> "popup (multiple )" ausgewählt wird.

**Comment by skerbis** [comment]
Kann ich bestätigen

**Comment by dergel** [comment]
@MC-PMOE @skerbis ist gemacht. Könnt ihr bestätigen, dass es nun klappt ?

**Comment by MC-PMOE** [comment]
Wird wieder richtig angezeigt 👍

**Comment by skerbis** [comment]
Bestätigt

**Comment by skerbis** [comment]
Die Daten werden jetzt nicht mehr gespeichert @dergel

**Comment by skerbis** [comment]
Ich habe die aktuelle Github-Version gezogen. Getestet mit popup multiple. Nach dem Speichern ist der Eintrag leer.

**Comment by skerbis** [comment]
Das war's danke @dergel @MC-PMOE

**Comment by dergel** [comment]
fast ;) .. musste noch die ansicht korrigieren. Bei dieser Relation mit Relationstabelle war die Ansicht noch falsch .. gerne nochmal testen. Aber ich schliesse dennoch schonmal ;)

**Comment by ynamite** [comment]
Bei einem m:n be_manager_relation Feld wo man aber trotz m:n nur `select (single)` unter Mehrfachauswahl wählt, bleibt die Listenansicht leer, da `getListValue` in diesem Fall die Values nicht korrekt holt.

Wenn man folgende Zeile https://github.com/yakamara/redaxo_yform/blob/167a8ba5f132ade342e878c208051abb175c46dd/plugins/manager/lib/yform/value/be_manager_relation.php#L508
wie folgt anpasst, klappt's auch mit `select (single)`:
`if (3 == $field['type'] || 0 == $field['type']) {`

Der Grund für m:n und `select (single)`: soll ausbaufähig sein, evtl. will der Kunde doch mehere Datensätze auswählen können.

**Comment by ynamite** [comment]
@dergel Danke für die Ergänzung. Multiple Select funktioniert auch nicht, mit folgender Ergänzung klappt's dann auch damit:
`if (3 == $field['type'] || 0 == $field['type'] || 1 == $field['type'])`

**Comment by MC-PMOE** [comment]
Die Popups lassen sich scheinbar nicht mehr übernehmen, bekomme in der Konsole folgendes angezeigt:
`TypeError: opener.document.getElementById(...) is null (widget.js:56:25)`

**Comment by MC-PMOE** [comment]
Ich hab das mal weiter untersucht, in den Popups in denen es nicht funktioniert wird im übernehmen Link in der javascript:setYFormDataset() Funktion als erster Parameter (id) ein negativer Wert angegeben. Z.B. -33284000. Das input Feld im Datensatzformular welches editiert werden soll sieht dann folgendermaßen aus:
```
<div class="input-group">
     <input class="form-control" type="text" name="YFORM_DATASET_NAME[-33284000]" value="" id="YFORM_DATASET_SELECT_-33284000106" readonly="readonly">
     <input type="hidden" name="FORM[data_edit-rex_jobs][5]" id="YFORM_DATASET_FIELD_-33284000106" value="">
     <span class="input-group-btn">
          <a href="javascript:void(0);" class="btn btn-popup" onclick="openYFormDataset(-33284000, 'rex_jobs.assigned_contact_person_id', 'index.php?page=yform/manager/data_edit&amp;table_name=rex_ycom_user','0');return false;" title="Datensatz auswählen"><i class="rex-icon rex-icon-add"></i></a>
          <a href="javascript:void(0);" class="btn btn-popup" onclick="deleteYFormDataset(-33284000,'0');return false;" title="Ausgewählten Datensatz löschen"><i class="rex-icon rex-icon-remove"></i></a>
     </span>
</div>
```
Hängt es vllt. damit zusammen? Momentan hilft es nur die betroffenen Felder auf ein Selectfeld umzustellen, das ist aber bei sehr großen Listen recht unübersichtlich. Gibt es da vllt. noch einen anderen Workaround?

**Comment by dergel** [comment]
Danke für die Fehlersuchen.. das hilft. Wir nächste Woche gelöst.

**Comment by DanielWeitenauer** [comment]
siehe #810

**Comment by dergel** [comment]
sollte alles klappen.. schliesse das issue hier.. falls einer der oberen Sachen eventuell oder bestimmten Umständen nicht geht . bitte neues Issues. Hier blicke ich kaum noch durch :)
