### ISSUE TITLE
Table Manager: Massenbearbeitung verändert createdate

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#792]
Die Massenbearbeitung verändert das createdate eines Datensatzes. Das darf nicht sein. Es gibt dafür keine Option, dies zu erlauben oder abzuschalten, da es kein Eingabefeld gibt.

**Comment by dergel** [comment]
wenn das createdate auf "immer neu erstellen" steht, ist das richtig. Massenbearbeitung soll simulieren, dass man einen DS ausmacht und diesen berarbeitet und speichert.

**Comment by alexplusde** [comment]
Es steht jedoch auf "wenn leer"

**Comment by dergel** [comment]
Bitte gegenprüfen. lg

**Comment by alexplusde** [comment]
thx
