### ISSUE TITLE
Dokumentation ergänzen: in_table fehlt

### ISSUE THREAD

**Issue by georgkaser** [yakamara/redaxo_yform#793]

**Comment by alexplusde** [comment]
?

**Comment by georgkaser** [comment]
Hab gesehen, dass es für die Dokumentation ein eigenes Repo gibt. Außerdem war jemand schneller ;)

**Comment by alexplusde** [comment]
@georgkaser magst du uns da unterstützen?

**Comment by georgkaser** [comment]
inwiefern?

**Comment by alexplusde** [comment]
@georgkaser mit geforderten und gewünschten Änderungen und Ergänzungen in der Doku natürlich.

**Comment by georgkaser** [comment]
Phu, weiß nicht ob du das willst :D Könnte wirres Zeug dabei rauskommen... Die Leute verstehn ja nicht mal was ich bei meinem Addon dazugeschrieben hab... Aber klar, ich kann gerne helfen sobald ich privat Luft habe (im Moment bau ich noch um, dauert noch ein paar Monate, dann hab ich mehr Zeit und werde mich auch mehr hier einbringen).
