### ISSUE TITLE
3.3 breaks selectpicker

### ISSUE THREAD

**Issue by skerbis** [yakamara/redaxo_yform#794]
Multiple: 

![Bildschirmfoto 2019-10-25 um 16 56 31](https://user-images.githubusercontent.com/791247/67582707-87d47880-f74a-11e9-9b65-0c63b205d2a9.png)

Single 

<img width="629" alt="Bildschirmfoto 2019-10-25 um 16 52 15" src="https://user-images.githubusercontent.com/791247/67582711-8905a580-f74a-11e9-8dcf-62c56e46e277.png">

Bei be_relationen multiple und single werden die Selects gedoppelt. 

Verwendeter Code für die Gestaltung: 

`{"class": "form-control selectpicker","data-live-search": "true"}`

**Comment by skerbis** [comment]
Die Ausgaben von 3.2 und 3.3 unterscheiden sich

**3.2**
```php
            <div class="form-group formbe_manager_relation" id="yform-data_edit-rex_feed_selects-content">
        <label class="control-label" for="yform-data_edit-rex_feed_selects-field-0">content</label>
        
<select name="FORM[data_edit-rex_feed_selects][0][]" size="10" multiple="multiple" class="form-control selectpicker" id="yform-data_edit-rex_feed_selects-field-0" data-live-search="true">
        <option value="1" selected="selected">erwehr [id=1]</option>
        <option value="2" selected="selected">ghfghfghfgh [id=2]</option>
        <option value="3">aaaaaaaa [id=3]</option>
</select>
            </div>
            
```

**3.3**

```php

            <div data-be-relation-wrapper="FORM[data_edit-rex_feed_selects][0]" class="form-group formbe_manager_relation" id="yform-data_edit-rex_feed_selects-content">
        <label class="control-label" for="yform-data_edit-rex_feed_selects-field-0">content</label>
        
<select name="FORM[data_edit-rex_feed_selects][0][]" size="10" multiple="multiple" class="form-control selectpicker" id="yform-data_edit-rex_feed_selects-field-0" data-live-search="true">
        <option value="1" selected="selected">erwehr [id=1]</option>
        <option value="2" selected="selected">ghfghfghfgh [id=2]</option>
        <option value="3">aaaaaaaa [id=3]</option>
</select>
            </div>

```

**Comment by dergel** [comment]
Leider ist das nicht so leicht zu lösen. Folgendes hilft.

https://github.com/redaxo/redaxo/issues/2662


https://github.com/redaxo/redaxo/blob/master/redaxo/src/addons/be_style/assets/javascripts/main.js#L2`

`container.find('.selectpicker').selectpicker();`

mit dem hier ersetzen. Gerne selbst nochmal Gegenprüfen.

`$(window).trigger('load.bs.select.data-api');`
