### ISSUE TITLE
ModSecurity: Access denied with code 403 (Aktuellse Plesk Version)

### ISSUE THREAD

**Issue by olien** [yakamara/redaxo_yform#796]
`Thu Oct 31 15:13:38.214020 2019] [:error] [pid 19130] [client 87.138.195.68:51606] [client 87.138.195.68] ModSecurity: Access denied with code 403 (phase 2). Pattern match "(?i:\\\\b(?:t(?:able_name\\\\b|extpos[^a-zA-Z0-9_]{1,}\\\\()|(?:a(?:ll_objects|tt(?:rel|typ)id)|column_(?:id|name)|mb_users|object_(?:id|(?:nam|typ)e)|pg_(?:attribute|class)|rownum|s(?:ubstr(?:ing){0,1}|ys(?:c(?:at|o(?:lumn|nstraint)s)|dba|ibm|(?:filegroup|o ..." at ARGS_NAMES:table_name. [file "/etc/apache2/modsecurity.d/rules/comodo_free/22_SQL_SQLi.conf"] [line "17"] [id "211540"] [rev "12"] [msg "COMODO WAF: Blind SQL Injection Attack||abc.de|F|2"] [data "Matched Data: table_name found within ARGS_NAMES:table_name: table_name"] [severity "CRITICAL"] [tag "CWAF"] [tag "SQLi"] [hostname "abc.de"] [uri "/redaxo/index.php"] [unique_id "XbrsElOpBlUAAEq67nYAAAAO"], referer: https://abc.de/redaxo/index.php?page=structure`

Wenn die "Web Application Firewall" ausgeschaltet ist geht es problemlos.

**Comment by alexplusde** [comment]
duplicate #358
