### ISSUE TITLE
Edit-Link auf Spalte 0(Add) bei Popup-Listen

### ISSUE THREAD

**Issue by christophboecker** [yakamara/redaxo_yform#799]
Hi, mir erschließt sich höhere Logik nicht bei diesem Code-Abschnitt im `rex_yform_manager`. Hier wird die Liste aufgebaut. Falls die ADD-Funktion angefordert ist, wird die entsprechende Spalte vorne (Index 0) eingebaut mit einen "Add"-Link auf dem Header und dem "Edit"-Link auf dem Icon in der Zeile. Später im Code wird die Spalte 'ID' eingebaut, die je Zeile den "Edit"-Link bringt. Insgesamt also drei mal "Edit", wenn man die Funktionsspalte rechts einbezieht.

Aber es gibt eine Ausnahme: bei einem Popup-Fenster wird die Add-Spalte nicht mit dem Edit-Link versehen, doch nachwievor die ID-Spalte.

siehe Code:

```php
if ($this->hasDataPageFunction('add')) {
    $tdIcon = '<i class="rex-icon rex-icon-table"></i>';
    $thIcon = '<a href="index.php?' . http_build_query(array_merge(['func' => 'add'], $rex_link_vars)) . '"' . rex::getAccesskey(rex_i18n::msg('add'), 'add') . '><i class="rex-icon rex-icon-add"></i></a>';
    $list->addColumn($thIcon, $tdIcon, 0, ['<th class="rex-table-icon">###VALUE###</th>', '<td class="rex-table-icon">###VALUE###</td>']);

    if (!isset($rex_yform_manager_opener['id'])) {
        $list->setColumnParams($thIcon, array_merge(['data_id' => '###id###', 'func' => 'edit'], $rex_yform_list));
    }
}

... ausgblendet, hat keinen Einfluß bzgl der Frage ...

$list->setColumnLabel('id', rex_i18n::msg('yform_id'));
$list->setColumnLayout('id', ['<th class="rex-table-id">###VALUE###</th>', '<td class="rex-table-id" data-title="' . rex_i18n::msg('id') . '">###VALUE###</td>']);
$list->setColumnParams('id', ['data_id' => '###id###', 'func' => 'edit']);
$list->setColumnSortable('id');
```
Ich könnte ja verstehen, dass Edit in machen Popup-Situationen fatal ist, aber Edit ist ja weiterhin über die ID-Spalte aktiv. Warum dann bei Popups auf der Add-Spalte Edit i nden Zeilen deaktivieren, denn Edit ist so oder so verfügbar. Dann kann man auch im oberen IF die Einschränkung rausnehmen und immer Edit drauflegen. 

Oder hab ich was übersehen?

**Comment by alexplusde** [comment]
Sehen Nicht-Admins die id-Spalte? Ansonsten erklärt sich mir das auch nicht, außer halt Optik.

**Comment by dergel** [comment]
Fand das auch komisch und habe es angepasst.
