### ISSUE TITLE
be_table - REX_LINK klappt nicht beim initialen Aufruf

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#801]
Value `be_table` anlegen

**Name**
links

**Bezeichnung**
Links

**Bezeichnung der Spalten**
`text|label|Label,be_link|article_id|interner Artikel,text|url|externe Url`

Man öffnet jetzt einen Datensatz und klickt zweimal `Reihe hinzufügen`!
In der **zweiten Zeile** die Linkmap öffnen und einen Artikel übernehmen. Der übernommene Artikel landet in der **ersten Reihe**.

Die Werte für `REX_LINK_1_` bleiben in allen Reihen gleich. Die Zahl wird erst bei einem erneuten Aufruf richtig fortlaufend angehangen. `REX_LINK_4_`, `REX_LINK_5_`, `REX_LINK_6_` etc.

**Comment by dergel** [comment]
@lexplatt Kannst du das prüfen ?
