### ISSUE TITLE
choice-Feld interpretiert Kommas im Label und Wert falsch

### ISSUE THREAD

**Issue by iceman-fx** [yakamara/redaxo_yform#804]
Hallo,

wenn ich eine Checkbox mittels choice-Feld anlege, so werden Kommas im Label und Wert falsch interpretiert und ausgegeben.

choice|preis_25|2.500,- Euro|2.500,- Euro|1|1|

wird zu

```
<div class="form-check-group" id="yform-formular-preis_25">
<label class="control-label" for="yform-formular-field-18">2.500,- Euro</label>
<div class="checkbox">
<label><input value="2.500" id="yform-formular-field-18-2-500" name="FORM[formular][18][]" type="checkbox" /><i class="form-helper"></i>2.500</label>
</div>
<div class="checkbox">
<label><input value="- Euro" id="yform-formular-field-18-euro" name="FORM[formular][18][]" type="checkbox" /><i class="form-helper"></i>- Euro</label>
</div>
</div>
```

Redaxo: 5.8.1
YForm: 3.3.1

**Comment by tbaddade** [comment]
Das ist Standardverhalten in YForm

**Comment by alexplusde** [comment]
Die Antwort finde ich nicht hilfreich.

Probier Mal `2500,2.500,- Euro` und ansonsten steht auch in der Doku, wie man die Parameter korrekt schreibt, schon angeschaut?

**Comment by tbaddade** [comment]
Du must das Komma escapen

**Comment by iceman-fx** [comment]
Der Trenner der Parameter ist doch ein "|".
Wieso wird denn dann bei einer Checkbox (nicht bei einem Select-Feld) noch das Komma geprüft? Macht doch eigentlich keinen Sinn, da man bei einer CB doch nur einen Wert im HTML angeben kann.

**Comment by alexplusde** [comment]
Steht alles im Add-on und in der Doku

**Comment by tbaddade** [comment]
Ich schließe, da laut @alexplusde alles in der Doku zu finden ist.

**Comment by alexplusde** [comment]
@iceman-fx melde dich ggf. im Slack-Channel mal, wenn da noch Fragen bestehen.
