### ISSUE TITLE
Tabellendaten importieren - Tabellenfelder haben verkehrte Namen

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#806]
Nach dem Import neuer Datensätze, bei denen die Felder angelegt werden sollen, heißen die alle `TEXT \`feldname\``

Zudem werden Umlaute / ß / durch`_` ersetzt - ich hätte erwartet, dass diese normalisiert werden.

**Comment by alexplusde** [comment]
![image](https://user-images.githubusercontent.com/3855487/69918398-b2180500-1471-11ea-9739-57160dcf3c49.png)

**Comment by dergel** [comment]
Das mit dem TEXT ist richtig. Damit man weiß, dass das Label noch richtig gesetzt werden muss. Die Feldnamen werden mittlerweile normalisiert.

**Comment by alexplusde** [comment]
> Das mit dem TEXT ist richtig. Damit man weiß, dass das Label noch richtig gesetzt werden muss. Die Feldnamen werden mittlerweile normalisiert.

Finde ich diskussionswürdig. Wenn die Felder korrekte Namen haben, warum diese nicht auch so nennen? Denn die Korrektur von Hand gestaltet sich aufwendig.
