### ISSUE TITLE
yform Table Manager: choice Feld SQL Möglichkeit main_id zu übergeben

### ISSUE THREAD

**Issue by ynamite** [yakamara/redaxo_yform#808]
Ich würde gerne bei einem Choice-Feld die Choices per SQL definieren, möchte im SQL Statement aber nach dem aktuellen Datensatz filtern können, sprich ich würde gerne im SQL Satetement einen Platzhalter wie `###main_id###`setzen können. Wäre toll wenn dieser dann durch die aktuelle `data_id` ersetzt werden würde.

**Comment by dergel** [comment]
ich sehe das nicht im Choice selber, sondern in be_relations oder in einer eigenen Klasse

**Comment by ynamite** [comment]
Schade, wäre in gewissen Situationen nützlich.
