### ISSUE TITLE
"be_manager_relation" mit Mehrfachauswahl "popup (mulitple)"

### ISSUE THREAD

**Issue by brandes-webdesign** [yakamara/redaxo_yform#812]
Das Auswahlfeld "be_manager_relation" mit Mehrfachauswahl "popup (mulitple)" geht nicht mehr, bei neu angelegten Produkten oder bei solchen, wo bisher keine Auswahl gemacht wurde.
Das PopUp-Fenster geht richtig auf, aber ein Klick auf "übernehmen" fügt keine Produkte in die Auswahl hinzu.

Bei Produkten, wo bereits etwas ausgewählt wurde, kann man ohne Probleme weitere Proudkte hinzufügen oder löschen. Wenn man allerdings dort auch alles rauslöscht tritt der Fehler wie oben beschrieben auf.

Vermutlich hängt es mit dem letzten yForm Updates zusammen.
Im Einsatz ist die aktuellste Version 3.3.1

**Comment by DanielWeitenauer** [comment]
ich nehme an, das es an diesem Problem liegt: #810, siehe dazu auch #791.

**Comment by brandes-webdesign** [comment]
Hallo Daniel,
ich hab mit von GitHub den aktuellen Stand von yForm heruntergeladen und installiert.
Nun klappt es wieder.

Vielen Dank und Dir einen guten Start ins Jahr 2020.
Mirco

**Comment by alexplusde** [comment]
@brandes-webdesign also hier schließen?

**Comment by brandes-webdesign** [comment]
Eigentlich ja. 
Im nächste Update wird das da ja so drinnen sein.
