### ISSUE TITLE
Attribute Eingabe ermöglichen und übergeben: fieldset, number 

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/redaxo_yform#814]
An einem fieldset benötige ich hin und wieder Klassen und weitere Attribute, da sie auch zu layoutzwecken benutzt werden können.

**Comment by tbaddade** [comment]
> hin und wieder Klassen und weitere Attribute

nur zu Info: Klassen sind bereits möglich

**Comment by alexplusde** [comment]
https://github.com/yakamara/redaxo_yform/blob/ab5c7a6621f06ad39063a3e0ffcd46d22bace257/lib/yform/value/fieldset.php#L65-L68

Hier sieht es so aus, als ob dafür keine Eingabefelder zur Verfügung stehen.

**Comment by alxndr-w** [comment]
Auch beim Number-Feld möchte ich bspw. min/max-Values übergeben. 

Stark wäre, statt händisch JSON einzugeben die Attribute über eine be_table pflegen zu können.

**Comment by dergel** [comment]
number ist umgesetzt. da ich das komplette layouting im allgemeinen nicht gut finde und auch die fieldset ausgaben eigensinnig umgesetzt sind, habe ich fieldset nicht angepasst. musst du leider per html field machen ..
