### ISSUE TITLE
E-Mail-Templates: textarea "Body (HTML)" mit CodeMirror auszeichnen

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#82]
Es fehlt `class="codemirror"`

das müsste man doch hier in die Pipe-Notation notieren?

https://github.com/yakamara/redaxo_yform/blob/master/plugins/email/pages/index.php#L33

**Comment by dergel** [comment]
ist nun möglch und eingesetzt weil attribute individuell gesetzt werden können

https://github.com/yakamara/redaxo_yform/issues/106
