### ISSUE TITLE
be_table in inline be_manager_relation

### ISSUE THREAD

**Issue by DanielWeitenauer** [yakamara/redaxo_yform#820]
In einem Backend-Formular habe ich zwei Inline-Formulare eingebunden. Jedes Formular enthält ein Feld vom Typ be_table. Da die Inline-Tabelle ähnlich strukturiert sind, liegen die Formulare an der gleichen Prio-Position.

Durch diese Zeilen
https://github.com/yakamara/redaxo_yform/blob/master/plugins/manager/lib/yform/value/be_table.php#L28
https://github.com/yakamara/redaxo_yform/blob/master/plugins/manager/ytemplates/bootstrap/value.be_table.tpl.php#L41
https://github.com/yakamara/redaxo_yform/blob/master/plugins/manager/ytemplates/bootstrap/value.be_table.tpl.php#L95
werden als Kennung Zahlenwerte vergeben. 
Dadurch kann es passieren, dass die Feldbezeichnungen der beiden Formulare identisch sind und sich beim POST gegenseitig überschreiben. 

Es wirkt auf mich, als wäre der Zahlenwert keine eindeutige ID, sondern dass er mit der Position der Felder im Formular zusammenhängt, da er sich beim Verschieben des Feldes ändert.

Ich habe versucht, `getId` mit `getName` zu ersetzen. Dies scheint das Problem zu beheben.

**Comment by dergel** [comment]
scheint mir auch so .. Die einzelnen Felder wie z.B. auch be_table müssen auf die inline Variation vorbereitet werden. Da ich be_table nicht selbst nutze, sondern immer lieber auch da inline in inline variante nutze, ist es mir nicht aufgefallen. Willst du einen PR dazu machen. Wäre eine große Hilfe.

**Comment by DanielWeitenauer** [comment]
Ich habe die oben genannten Änderungen eingefügt. 
Wie kann ich eigentlich das Classic-Template im Backend testen?

**Comment by alexplusde** [comment]
@DanielWeitenauer da das Classic-Theme eig. für die Ausgabe behalten wurde und be_table ein reines Backend-Feld ist, würde ich sagen, kann man das vernachlässigen. Oder @dergel ?

**Comment by DanielWeitenauer** [comment]
Könnte es dann sein, dass das entsprechende Template gelöscht werden kann?

**Comment by tbaddade** [comment]
> Könnte es dann sein, dass das entsprechende Template gelöscht werden kann?

Hier siehst du alls Templates
https://github.com/yakamara/redaxo_yform/tree/master/ytemplates/classic
https://github.com/yakamara/redaxo_yform/tree/master/plugins/manager/ytemplates/classic

Und hier erkennst du, dass erst nach bootstrap gesucht wird und falls dort das Template nicht vorhanden ist im classic gesucht wird.
https://github.com/yakamara/redaxo_yform/blob/master/lib/yform.php#L49

Ich meine aber das man das classic vernachlässigen ggf. sogar komplett herausnehmen sollte.

**Comment by DanielWeitenauer** [comment]
Soll ich es mit diesem PR löschen? Oder besser einen weiteren, da das ja eigentlich auch die übrigen be-field-templates betrifft?

**Comment by dergel** [comment]
ich habe bei den be ytemplates classic komplett entfernt, da nicht sinnvoll.
