### ISSUE TITLE
datetime: Wunsch: Option Uhrzeit auf 0 bei Aktuelles Datum voreingestellt

### ISSUE THREAD

**Issue by skerbis** [yakamara/redaxo_yform#822]
Das datetime-Feld erlaubt es das aktuelle Datum zu übernehmen. 
Eine Option dennoch die Uhrzeit initial auf 00:00 zu belassen wäre jedoch sinnvoll, gerade bei der Einpflege von News und vor allem wenn man auf ein späteres Datum datieren möchte. Da vergisst man schnell die Uhrzeit anzupassen. 

<img width="729" alt="Bildschirmfoto 2020-01-28 um 09 42 14" src="https://user-images.githubusercontent.com/791247/73248053-859f1180-41b2-11ea-8afa-6ce8a73142d0.png">

**Comment by dergel** [comment]
Sehe ich erst mal nicht. Das würde das Feld zu weit aufbohren. Dann lieber 2 Felder, Date und Time :)

**Comment by skerbis** [comment]
Es ging mir nur darum die Uhrzeit zu Nullen, aber weiter das Feld datetime Feld zu verwenden. Weil einfacher zu handhaben als getrennte date und time Felder.
