### ISSUE TITLE
event rex:YForm_selectData wird doppelt ausgelöst

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#831]
Das Event wird zweimal registriert. Kommentiere ich eines aus, wird das Event nur einmal abgefeuert. Das scheint somit zumindest der Fehler zu sein. Es kann aber auch sein, dass beide Registrierungen ihre Berechtigungen haben.

https://github.com/yakamara/redaxo_yform/blob/master/plugins/manager/assets/manager.js#L26
https://github.com/yakamara/redaxo_yform/blob/master/plugins/manager/assets/widget.js#L31

Aufgefallen um YForm Datensätze im Redactor zu verlinken.

**Comment by dergel** [comment]
Wie kann man den Fehler erkennen ? Was passiert falsches ?

**Comment by tbaddade** [comment]
Aktuell wird das im Redactor [hier abgefangen](https://github.com/FriendsOfREDAXO/redactor/blob/dcdbb0dea8d40817715ee1881e954322eacb0073/assets/plugins/linkYForm.js#L65)

**Zum Nachvollziehen**
1. [Diese Zeile](https://github.com/FriendsOfREDAXO/redactor/blob/dcdbb0dea8d40817715ee1881e954322eacb0073/assets/plugins/linkYForm.js#L72) in der Datei `/assets/addons/redactor/plugins/linkYForm.js` in Kommentar setzen.
1.  Ein Modul anlegen mit dieser Eingabe
`<textarea name="REX_INPUT_VALUE[1]" class="form-control redactor-editor--full">REX_VALUE[1]</textarea>`
1. Redactor Profil mit Namen `full` anlegen und unter Plugins das notieren
`linkYForm[rex_yf_test=title],`
1. Eine YForm-Tabelle `rex_yf_test` mit einem Feld `title` anlegen.
1. Einen Datensatz in der Tabelle `rex_yf_test` anlegen.
1. Artikel aufrufen und im Modul den Button YForm anklicken und die Tabelle auswählen. Es öffnet sich das Popup und den Datensatz übernehmen

**Jetzt wird der Datensatz doppelt im Textfeld des Moduls eingefügt.** Grund: Das Event wird doppelt getriggert.
