### ISSUE TITLE
choice: Freitext-Option

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#834]
Ist es möglich, zu choice noch eine Freitext-Option zu aktivieren, der dann als Wert in der DB gespeichert wird und im Formular als Textfeld gerendert wird? Wäre super praktisch.

**Comment by tbaddade** [comment]
Warum nicht das Text Value verwenden?

**Comment by alexplusde** [comment]
Am Beispiel Google Forms:
![image](https://user-images.githubusercontent.com/3855487/75017144-bd853600-548c-11ea-8e47-f503b48aa132.png)

**Comment by tbaddade** [comment]
Kannst du noch den Screen mit der `select` Variante hier reinlegen?

**Comment by alexplusde** [comment]
Ist in Google Forms nicht vorgesehen

![image](https://user-images.githubusercontent.com/3855487/75027180-69834d00-549e-11ea-83d7-25a4be32f1af.png)

**Comment by tbaddade** [comment]
Ich bin da eher der Meinung, dass man dieses Freifeld selbst via Textvalue anbringen sollte. Auch bei Symfony, wo die Idee zum Choice herkommt, ist dieses Verhalten so momentan nicht vorgesehen. 

Falls man diese Idee aufnimmt, sollte das auch für `select` funktionieren da die gespeicherten Daten aktuell unabhängig der Ausgabe vorliegen.

**Comment by alexplusde** [comment]
Ich würde es mir deshalb in choice wünschen, da man sonst das Eingabefeld nicht in die Liste der radio-inputs oder checkbox-inputs gerendert bekommt.

Für das SELECT könnte man sich ja ebenso überlegen, das Textfeld zu liefern - der Entwickler muss in diesem Fall, der sich aber genauso gut mit radio buttons abdecken ließe - das Eingabefeld ein/ausblenden und ggf. auch leeren.

Gut wäre eben, wenn Choice dafür vorbereitet ist, eine zusätzliche Option auch zu verarbeiten.

**Comment by alexplusde** [comment]
@tbaddade mir wurde gerade sehr viel Geld dafür bezahlt, damit ich dieses Issue wieder schließe ;)

Hätte ja sein können, dass es einen cleveren Weg gibt, das zu integrieren.
