### ISSUE TITLE
GEO Plugin: Google Maps nur noch mit API Key

### ISSUE THREAD

**Issue by olien** [yakamara/redaxo_yform#84]
https://developers.google.com/maps/pricing-and-plans/standard-plan-2016-update

Wäre eine Umstellung auf OpenStreetMaps sinnvoll?

**Comment by alexplusde** [comment]
Eigentlich ist das Beziehen eines API-Keys so simpel, dass man mit einem Verweis auf https://developers.google.com/maps/documentation/javascript/get-api-key?hl=de als Entwickler schon weiterkommen müsste.

**Comment by olien** [comment]
Na dann erstelle ich mal viele Keys für "meine" Seiten....

**Comment by alexplusde** [comment]
Okay, unter dem Aspekt, das für ganz viele Seiten nachzureichen... bin schon still ;)

**Comment by olien** [comment]
Naja. Bestehende Seiten laufen ja noch. ich mach das mal wieder zu hier wobei OSM ne nette Alternative wäre....
