### ISSUE TITLE
Docs nun in yform - aber leider noch sehr unsexy

### ISSUE THREAD

**Issue by dergel** [yakamara/redaxo_yform#840]
Und ein paar Übersetzungen fehlen noch. Würde das gerne nochmal angehen, weil ich die Darstellung leider noch gar nicht gelungen finde

**Comment by alexplusde** [comment]
Huch, an welchen Stellen fehlte was? Screenshots?

**Comment by alexplusde** [comment]
Das CSS könnte man vlt. von YCom übernehmen, da sieht die Doku ja ganz passabel aus. Müsste dann eben auf jeden Fall in den Core. @dergel kannst du dich darum kümmern?

**Comment by alexplusde** [comment]
Das CSS könnte man vlt. von YCom übernehmen, da sieht die Doku ja ganz passabel aus. Müsste dann eben auf jeden Fall in den Core. @dergel kannst du dich darum kümmern?

**Comment by dergel** [comment]
das wäre dann doch eher ein core Thema. Besser doch nichts eigenes hier.

**Comment by alexplusde** [comment]
@dergel dann würdest du das CSS von ycom docs in den core nachziehen?
