### ISSUE TITLE
Whoops - wenn eine migrierte Tabelle unter YForm gespeichert wird

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#842]
Hier wurde die rex_feed_item Tabelle vom Feed Addon migriert.

Ich vermute, dass YForm beim Migirieren falsche Feldtypen verwendet hat. 

```
CHANGE `stream_id` `stream_id` varchar(191)  NOT NULL ,
```

stream_id wurde vom Feed Addon mit int angelegt.
Siehe https://github.com/FriendsOfREDAXO/feeds/blob/master/install.php#L33

**rex_sql_exception:** Error while executing statement "ALTER TABLE `rex_feeds_item`
    CHANGE `stream_id` `stream_id` varchar(191)  NOT NULL ,
    CHANGE `uid` `uid` varchar(191)  NOT NULL ,
    CHANGE `type` `type` varchar(191)  NOT NULL ,
    CHANGE `title` `title` text  NOT NULL ,
    CHANGE `content` `content` text  NOT NULL ,
    CHANGE `content_raw` `content_raw` text  NOT NULL ,
    CHANGE `url` `url` varchar(191)  NOT NULL ,
    CHANGE `author` `author` varchar(191)  NOT NULL ,
    CHANGE `username` `username` varchar(191)  NOT NULL ,
    CHANGE `language` `language` varchar(191)  NOT NULL ,
    CHANGE `media` `media` text  NOT NULL ,
    CHANGE `mediasource` `mediasource` text  NOT NULL ,
    CHANGE `raw` `raw` text  NOT NULL ,
    CHANGE `changed_by_user` `changed_by_user` tinyint(1)  NOT NULL ,
    CHANGE `createuser` `createuser` varchar(191)  NOT NULL ,
    CHANGE `updateuser` `updateuser` varchar(191)  NOT NULL ;"! SQLSTATE[HY000]: General error: 1832 Cannot change column 'stream_id': used in a foreign key constraint 'rex_feeds_item_ibfk_1'
**File:** src/core/lib/sql/sql.php
**Line:** 386

<details>
<summary>Stacktrace</summary>

| Function                                            | File                                                             | Line     |
| --------------------------------------------------- | ---------------------------------------------------------------- | -------- |
| rex_sql->setQuery                                   | src/core/lib/sql/table.php                                       | 860      |
| rex_sql_table->alter                                | src/core/lib/sql/table.php                                       | 664      |
| rex_sql_table->ensure                               | src/addons/yform/plugins/manager/lib/yform/manager/table_api.php | 609      |
| rex_yform_manager_table_api::generateTableAndFields | src/addons/yform/plugins/manager/pages/table_edit.php            | 223      |
| include                                             | src/core/lib/packages/package.php                                | 228      |
| rex_package->includeFile                            | src/core/lib/be/controller.php                                   | 462      |
| rex_be_controller::includePath                      | src/core/lib/be/controller.php                                   | 419      |
| rex_be_controller::includeCurrentPageSubPath        | src/addons/yform/pages/index.php                                 | 3        |
| include                                             | src/core/lib/packages/package.php                                | 228      |
| rex_package->includeFile                            | src/core/lib/be/controller.php                                   | 462      |
| rex_be_controller::includePath                      | src/core/lib/be/controller.php                                   | 404      |
| rex_be_controller::includeCurrentPage               | src/core/backend.php                                             | 215      |
| require                                             | src/core/boot.php                                                | 137      |
| require                                             | public/redaxo/index.php                                          | 12       |

</details>
<details>
<summary>System report (REDAXO 5.9.0, PHP 7.4.1)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.9.0      |

| PHP           |            |
| ------------: | :--------- |
|       Version | 7.4.1      |
|       OPcache | yes        |
|        Xdebug | yes        |

| Packages          |            |
| ----------------: | :--------- |
|             feeds | 3.1        |
|             yform | 3.3.1      |
|        yform/docs | 3.3.1      |
|       yform/email | 3.3.1      |
|     yform/manager | 3.3.1      |

</details>

**Comment by tbaddade** [comment]
mediumtext sollte auch überprüft werden.

Aktuell wird für angelegte mediumtext Felder der Type text angewendet

**Comment by alexplusde** [comment]
Es würde schon genügen, beim migrieren nicht die Einstellung zu haben, dass die Tabelle das Schema vorgibt/überschreibt.

**Comment by alexplusde** [comment]
Dies sollte eigentlich mit https://github.com/yakamara/redaxo_yform/issues/508 nicht mehr passieren wegen https://github.com/yakamara/redaxo_yform/blob/8664333853af5c6253bf71508d9bb281de18215c/plugins/manager/lib/yform/manager/table_api.php#L237 `'schema_overwrite' => 0`

Zumindest, wenn das die Ursache gewesen ist. Ansonsten kann es sein, dass YForm das Feld trotzdem anfasst und dadurch ein Whoops entstanden ist.

**Comment by dergel** [comment]
daraus folgt .. 

* stream_id hätte int bleiben müssen
* aus media wurde text hätte longtext bleiben müssen
* option - schema nicht schreiben.

**Comment by dergel** [comment]
> Es würde schon genügen, beim migrieren nicht die Einstellung zu haben, dass die Tabelle das Schema vorgibt/überschreibt.

da stimme ich zu.. Dementsprechend habe ich nochmal nachgesehen und Anpassungen gemacht. das "id-komvertieren" habe ich herausgenommen, das sollte jemand manuell machen. Ist zwar nicht BC, aber damit kann man leben, denke ich.
