### ISSUE TITLE
Formbuilder-Modul anhand Modul-Key updaten

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#845]
Ab R5.10 kann das Modul direkt per Modul-Key geupdatet werden ohne Umweg über einen HTML-Kommentar.

**Comment by tbaddade** [comment]
Dann wäre es gut, wenn der Module Key readonly ist und nicht geändert werden kann.

**Comment by alexplusde** [comment]
Sorry, da sind wir wieder unterschiedlicher Meinung. Wer den Formbuilder modifizieren will, darf das ruhig tun und sollte eher dahingehend animiert werden, den key gleich mit zu ändern, da sonst im Falle eines Updates die Änderungen ja überschrieben werden.
