### ISSUE TITLE
3.3.1 hidden-Feld erzeugt Ausgabe

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#847]
Gemeldet via @rotzek 

Es darf dazu aber keine Ausgabe geben, das war ja der Sinn des Hidden-Felds, bestimmten zu können, welche Werte ggf. serverseitig drin sein dürfen.

**Comment by dergel** [comment]
sollte auch so sein ... Ausser wenn beim hidden Feld ein REQUEST, oder POST übergeben wird, dann wird dieser Wert übernommen und ausgegeben, damit er wieder verwendet werden kann, z.B. wenn das Formular Fehler hat und der übergebene Wert noch benötigt wird.
Bei "festen" Werten im hidden Feld, wird nichts ausgegeben und dieser Wert gesetzt.

gerade lokal getestet. Oder ist es ein anderer Fall ?

**Comment by alexplusde** [comment]
Ich hätte ein anderes Verhalten erwartet. Das hidden-Feld nimmt die Eingabe entgegen, erzeugt aber keine Ausgabe.

Bisher hat es auch nie eine Ausgabe erzeugt nach meinem Kenntnisstand und entsprechend ist es auch in der Doku festgehalten.

Das Verhalten muss sich auch seit 3.2 geändert haben nach meiner Beobachtung.

Können wir das zur Klärung noch kurz offen halten bitte...

**Comment by dergel** [comment]
Ausgabe ist nur in den Fällen, in denen ein Wert von außen in das FOrmular übergeben wurde. Nicht wenn ich einen festen Wert im hidden setze.

`hidden|meinfeld|meinWert`

erzeugt keine Ausgabe

**Comment by dergel** [comment]
nun geht auch GET und yform action wurde erweitert um den param: form_action_query_params mit dem man eigene weitere GET Felder hinzufügen kann. Ich hoffe es findet jemand Zeit es zu testen.. erstmal ist das issue durch

**Comment by alexplusde** [comment]
`form_action_query_params` ist ein objparam? Zwecks Doku

**Comment by dergel** [comment]
genau
