### ISSUE TITLE
Tools-Plugin: Keine Funktion mehr in Input Feldern

### ISSUE THREAD

**Issue by danspringer** [yakamara/redaxo_yform#849]
Aus dem Slack heute:

1.)
yForm 3.3.1 in R5.9 mit installiertem Tools-Plugin.
Select2 für Tags funktioniert nicht mehr. Habe in den Attributen für ein select (multiple) folgendes drin: `{"data-yform-tools-select2": "tags", "placeholder": "Hier klicken, um auszuwählen", "required":"required"}`. Das Input-Filed wird korrekt gerendert, aber sonst passiert nichts. Keine Fehler in der Konsole.
`<select name="FORM[data_edit-rex_standorte][7][]" size="10" multiple="multiple" class="form-control" id="yform-data_edit-rex_tandorte-field-7" data-yform-tools-select2="tags" placeholder="Hier klicken, um auszuwählen" required="required">`

2.) Habe ein Table Manager Feld angelegt und mit dem individuellen Attribut
`{"data-yform-tools-datetimepicker":"YYYY-MM-DD HH:ii"}`
versehen. Leider erscheint kein Picker (mehr). Konsole wirft auch keinen Fehler, "tools" ist auch installiert und aktiviert...
[yform Version 3.3.1]

**Comment by alexwenz** [comment]
Ping ;-)

**Comment by isospin** [comment]
#830

**Comment by alexplusde** [comment]
@isospin ich deute das so, als ob das in der GitHub-Fassung gefixt ist.

**Comment by alexwenz** [comment]
Sehr gut gedeutet @alexplusde!! Die neue tools.js löst das Problem (@danspringer)

**Comment by alexplusde** [comment]
Kannst du das Issue schließen :) @danspringer
