### ISSUE TITLE
Layout verrutscht auf Popup-Seiten - YForm oder be_style?

### ISSUE THREAD

**Issue by christophboecker** [yakamara/redaxo_yform#855]
Hallo, ich mache hier auch mal ein Issue auf, weil mir nicht klar ist, in welchem Addon man sich kümmern müsste.
https://github.com/redaxo/redaxo/issues/3466
Kurzfassung, ich öffne eine YForm-Tabelle mit einer url, die eine Seite im Popup-Layout anfordert (rex_yform_manager_popup=1). Dabei wird das Layout zerschossen, wenn die Tabelle eine Description hat. Details im anderen Issue. (Edit: da hab ich in der falschen Tabelle getestet, gestrichen: _Bei einem Aufruf via Widget (be_manager_relation) passiert das übrigens nicht_.)

Frage wäre erstmal:
Ist hier an YForm bei rex_yform_manager_popup=1 zu auskunftsfreudig und müsste bei Popups den Header etwas schlanker halten, damit das Popup-Layout von be_style korrekt greift oder ist das eher bei be_style zu adressieren?

Für mich persönlich besteht kein akuter Handlungsbedarf, ich blende mir jetzt Teile des YForm-Headers (<small...) auf Seiten im Popup-Layout per CSS aus.

**Comment by tbaddade** [comment]
>  Bei einem Aufruf via Widget (be_manager_relation) passiert das übrigens nicht.

Bei einem Aufruf über das Widget `REX_YFORM_TABLE_DATA` hingegen schon.

**Comment by christophboecker** [comment]
> Bei einem Aufruf via Widget (be_manager_relation) passiert das übrigens nicht.

Den Satz ziehe ich zurück. Hatte beim Test versehentlich auf die Prüftabelle ohne Description zugegriffen. Das Problem müsste also überall sein. Kann aber nicht wirklich so sein, denn dann wäre es (auch mir) längst mal aufgefallen. Myteriös!

**Comment by dergel** [comment]
Danke Christop. PR ist übernommen. Description wird nun im Popup einfach ausgeblendet
