### ISSUE TITLE
YOrm und Url2 Wechselwirkung

### ISSUE THREAD

**Issue by pschuchmann** [yakamara/redaxo_yform#856]
Hey,

ich hatte gerade ein wenig mit @tbaddade bzgl. Datensatz holen mit Url2 Addon geschrieben. Folgendes Problem habe ich aktuell. Bisher haben wir mit dem Url Addon immer die Id des Datensatzes ausgelesen und damit per Modelklasse das Objekt geholt.

Was habe ich gemacht? Ich habe eine Tabelle `rex_project` mit entsprechender Modelklasse angelegt. Nun gibt es drei Wege den Datensatz aufzurufen, nur mein Bevorzugter funktioniert leider nicht, da erhalte ich Daten aus Url zurück.

```php
<?php

class rex_project extends \rex_yform_manager_dataset
{
...
}
```

```php
use Url\Url;

$manager = Url::resolveCurrent();
if ($manager) {
    $project= $manager->getDataset(); //funktioniert
}
```
```php
use Url\Url;

$manager = Url::resolveCurrent();
if ($manager) {
    $item_id = $manager->getDatasetId();
}
$project = rex_yform_manager_table::get(rex::getTable('project'))->query()->findId($item_id); //funktioniert
$project = rex_project::get($item_id); //funktioniert nicht
```

Der Dump, wenn es nicht funktioniert:

![image](https://user-images.githubusercontent.com/35096518/76838989-04b8d980-6835-11ea-8d5d-50b9406dca0a.png)

Der Dump, wenn es funktioniert:

![image](https://user-images.githubusercontent.com/35096518/76839209-6711da00-6835-11ea-9f58-0f30ccfa5711.png)

**Comment by pschuchmann** [comment]
Problem ist im Url Addon zu finden.

**Comment by tbaddade** [comment]
> Problem ist im Url Addon zu finden.

Was sollte das Addon anders machen?
