### ISSUE TITLE
EP REX_YFORM_ADD an falscher Stelle ausgeführt?

### ISSUE THREAD

**Issue by christophboecker** [yakamara/redaxo_yform#857]
Hier mal wieder was Merkwürdiges ....

(YForm 3.3.1 auf REX 5.10)

**Ausgangslage:**

Ich wollte über den EP YFORM_DATA_ADD zwei Felder eines Formulars gezielt mit Werten füllen, die aus dem letzten gespeicherten Datensatz stammen und in der Session abgelegt sind. Mit dem EP YFORM_DATA_ADDED werden die Daten in die Session geschrieben. Leider sind die Ergebnisse nicht wie erwartet, was auf die Abfolge der EPs zurückzuführen war:

**Fehlerbild:**

Beim Test habe ich festgestellt, das die EP-Abfolge etwas seltsam war. Klick auf das Plus-Symbol öffnet das Formular und führt vorher (wie erwartet) YFORM_DATA_ADD aus. Beim Speichern wird zwar der erwartete YFORM_DATA_ADDED ausgeführt, aber **vorher** noch einmal YFORM_DATA_ADD. Und das ist doch ein sehr unerwartetes Verhalten. Imho.

**Dokumentation / Testszenario**

Hier mal Screenshots mit einem ganz simplen Testszenario mit einer 1-Feld-Tabelle. In der boot.php des Projekt-Addons steht nur zwei simple Aufrufe:
```
rex_extension::register('YFORM_DATA_ADD', function( $ep ){ dump($ep); } );
rex_extension::register('YFORM_DATA_ADDED', function( $ep ){ dump($ep); } );
```
Nach Klick auf den Plus-Button kriege ich das erwartete Szenario:

<img width="306" alt="grafik" src="https://user-images.githubusercontent.com/10065904/77294332-63260200-6ce4-11ea-9e66-18d8fbd8d117.png">

Nachdem ich auf den Button "Hinzufügen" klicke kommt das hier:

<img width="325" alt="grafik" src="https://user-images.githubusercontent.com/10065904/77294533-be57f480-6ce4-11ea-946f-27e759b77721.png">

Klick auf "Übernehmen" statt "Hinzufügen" führt zu einem analogen Ergebnis:

<img width="307" alt="grafik" src="https://user-images.githubusercontent.com/10065904/77294695-01b26300-6ce5-11ea-8405-6aacd534404f.png">

Klicke ich noch mal auf "Übernehmen", wird der Satz normal gespeichert, und keiner der EP angezogen.

<img width="272" alt="grafik" src="https://user-images.githubusercontent.com/10065904/77295013-784f6080-6ce5-11ea-9526-ddf25927f045.png">

**Comment by dergel** [comment]
sollte mit der github Version funktionieren. BItte testen. Ich schliesse aber trotzdem.
