### ISSUE TITLE
BE_MANAGER_RELATION: Listenansicht bei "popup (multiple)" falsch?

### ISSUE THREAD

**Issue by christophboecker** [yakamara/redaxo_yform#858]
Hier mal wieder was Merkwürdiges .... oder habe ich die falsche Erwartungshaltung?
be_manager_relation gab es ja schon öfter was :-)

(yform 3.3.1 auf REX 5.10)

Ich habe zwei Tabellen, in der einen (rex_kv30_dokument) sind einzelne Dokumente enthalten. In der anderen (rex_kv30_buch) werden zusammenhängende Dokumente zu einem größeren Artikel zusammengefasst.

Der Link erfolgt über ein Feld in der Tabelle rex_kv30_buch vom Typ "be_manager_relation" in dieser Konfiguration:
<img width="516" alt="grafik" src="https://user-images.githubusercontent.com/10065904/77431980-c3e53580-6ddd-11ea-8b23-e536cf0bc176.png">

Im Formular sieht es so aus, was mir korrekt erscheint:
<img width="885" alt="grafik" src="https://user-images.githubusercontent.com/10065904/77432326-335b2500-6dde-11ea-882e-694a5d95f3c5.png">

In der Liste erscheint statt der drei Einträge der komplette Datenbestand aus rex_kv30_dokument!
<img width="989" alt="grafik" src="https://user-images.githubusercontent.com/10065904/77432483-68677780-6dde-11ea-8fc3-b90d4dbccefc.png">

Nehme ich für die Mehrfachauswahl statt "popup (multiple)" die Variante "select (multiple)" sieht die Listenausgabe so aus, wie ich es auch im anderen Fall erwarten würde:
<img width="1076" alt="grafik" src="https://user-images.githubusercontent.com/10065904/77432804-d4e27680-6dde-11ea-8222-0fcb9f863140.png">

Nur leider ist "select (multiple)" keine Lösung, denn am Ende wäre das ein Select mit über 1000 Einträgen, komplett unhandlich, noch unhandlicher als das Popup, dass man ja hilreicher weise filtern kann.

**Comment by dergel** [comment]
Kannst du die aktuelle github Version testen. Ich kann den Fehler leider nicht nachvollziehen.

**Comment by christophboecker** [comment]
Auf jeden Fall wird die Popup-Liste jetzt so angezeigt wie ich es erwarten würde. Vielen Dank.
