### ISSUE TITLE
Typ DATE: falsche Eingaben führen zu SQL-Fehler

### ISSUE THREAD

**Issue by christophboecker** [yakamara/redaxo_yform#860]
Hier mal wieder was Merkwürdiges .... oder gar ein Bug?

(yform 3.3.1 auf REX 5.10)

Die Testtabelle hat nur ein Datenfeld vom Typ "date", darauf die Suchfunktion aktiviert. Die Suche klappt auch solange man sich an das Eingabeformat hält. Macht man das nicht und gibt z.B. nur eine Jahreszahl als Suchkriterium ein, gibt es eine SQL-Exception:

<img width="843" alt="grafik" src="https://user-images.githubusercontent.com/10065904/77854161-d77f0a80-71e8-11ea-952f-5fc6f55c3445.png">

Hier die Felddefinition:
<img width="445" alt="grafik" src="https://user-images.githubusercontent.com/10065904/77854122-9555c900-71e8-11ea-8caf-802cd3f5df99.png">

Hier die Eingabe des ungeeigneten Wertes
<img width="413" alt="grafik" src="https://user-images.githubusercontent.com/10065904/77854068-2ed0ab00-71e8-11ea-86e2-881e71abcba5.png">

Das Problem liegt ganz am Ende der Methode `getSearchFilter`. Wenn alle anderen Eingabevarianten ausgeschöpft sind, wird einfach der `$value` (also hier "2020") für die Where-Klausel herangezogen. Und ist der kein korrektes DATE-Format (YYYY-MM-DD) meckert SQL.

**Comment by christophboecker** [comment]
Was man machen könnte: 

Wenn zum Schluß `$value` noch mal durch `date_getFromFormattedDate` gescchickt wird, müsste sowas herauskommen wie

- `2020-01` wird zu `2020-01-00`
- `2020` wird zu `2020-00-00`

Das würde z.B. ermöglichen aus der Eingabe noch mal eine Bereichssuche zu machen:

- `2020-01` wird zu `2020-01-01 - 2020-01-31`
- `2020` wird zu `2020-01-01 - 2020-12-31`

Könnte so aussehen:
```
        // nur ein Datum angegeben. Falls es unvollständig ist (YYYY oder YYYY-MM)
        // zu einem Suchbereich ergänzen (YYYY-01-01 - YYYY-12-31 bzw. YYYY-MM-01 - YYYY-MM-ultimo)
        $value = self::date_getFromFormattedDate($value, $format, 'YYYY-MM-DD');
        $date = explode( '-', $value );

        if( '0000' == $date[0] ) {
            // ungültiges Datum; Filter ignorieren
            return '';
        }

        if( '00' == $date[1] ) {
            // zu einem Suchbereich ergänzen => YYYY-01-01 - YYYY-12-31
            $date_from = $date[0].'-01-01';
            $date_to = $date[0].'-12-31';
            return ' (
            ' . $sql->escapeIdentifier($field) . '>= ' . $sql->escape($date_from) . ' and
            ' . $sql->escapeIdentifier($field) . '<= ' . $sql->escape($date_to) . '
            ) ';
        }

        if( '00' == $date[2] ) {
            // zu einem Suchbereich ergänzen => YYYY-MM-01 - YYYY-MM-ultimo
            if( $date[1] < '01' || $date[1] > '12' ) {
                // ungültiges Datum; Filter ignorieren
                return '';
            }
            $date_from = $date[0].'-'.$date[1].'-01';
            $date_to = mktime( 0,0,0,$date[1]+1,1,$date[0] ) - 1;
            $date_to = date( 'Y-m-d',$date_to );
            return ' (
            ' . $sql->escapeIdentifier($field) . '>= ' . $sql->escape($date_from) . ' and
            ' . $sql->escapeIdentifier($field) . '<= ' . $sql->escape($date_to) . '
            ) ';
        }

        // also konkretes Datum
        return '(' . $sql->escapeIdentifier($field) . ' = ' . $sql->escape($value) . ')';
```

Leider gibt es noch einen weiteren Haken, und das liegt in `date_getFromFormattedDate`. Beim Eingabeformat `YYYY-MM-DD` wird aus `2020` ein `2020-00-00`; beim Eingabeformat `DD.MM.YYYY' ergibt sich `0000-00-20`.

Was spricht denn gegen eine Dekodierung der Eingabe per Regex? Also ein spezifisches Regex je Formatvariante?

Der obige Code setzt voraus, dass `date_getFromFormattedDate` auch angepasst wird. Ich könnte bei Gelegenheit einen PR für das Gesamtpaket einstellen.

**Comment by christophboecker** [comment]
OK, ich geh das mal an.

**Comment by christophboecker** [comment]
PR eingestellt (#864). Wäre nett, wenn das außer mir noch jemand testen würde; ich trau mir nicht.

**Comment by dergel** [comment]
ist gemerged .. sollte also alles wieder passen.. Danke @christophboecker :)
