### ISSUE TITLE
Whoops wird nicht bei Fehlern in Values gestartet

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#862]
0. debug-Modus und throw_always_exception aktivieren
1. YForm installieren
2. YCom installieren
3. yform_usability installieren
4. Benutzer anlegen

Es erscheint eine notice 
![image](https://user-images.githubusercontent.com/3855487/78336563-db67af80-758f-11ea-9a63-73aa09018b05.png)

stattdessen müsste der Whooops kommen.

**Comment by dergel** [comment]
kann gut sein .. Abhängigkeiten so anderen AddOns will ich hier ungern lösen. Wenn du einen Fehlercase meldest, der ausschliesslich in YForm vorkommt gerne.. Habe gerade ein paar Tests gemacht und bekam immer die passende Whoopsmeldung .. gerne als neues issue dann..
