### ISSUE TITLE
DATE: flexiblere Eingabe und Valierung mit Fehlermeldung 

### ISSUE THREAD

**Issue by christophboecker** [yakamara/redaxo_yform#866]
Ich bin über ein paar Punkte beim Datentyp date (`rex_yform_value_date`) gestolpert. Ausgangspunkt war, dass ich in der Variante "input:text" immer mal wieder für Tag oder Monat einstelige Werte auch nur einstellig eingegeben habe und mich anschließend wunderte, wo die Datensätze sind. (Ja, selbst schuld, wenn man sich nicht an da Eingabeformat hält.). Das ungültige Eingaben - anders als bei den Feldtypen für `email` oder `url` zugelassen werden, hat mich halt doch gewundert. 

# Mein Vorschlag ist ...
... - und ich kann gerne einem PR dazu bauen - die Überarbeitung von `rex_yform_value_date` mit den Zielen:

- **input:text** erlaubt flexiblere Eingabe (Bsp: 1.1.20 statt 01.01.2020) und vermeidet somit Flüchtigkeitsfehler.
- Identisches Verhalten von **input:text** und **select** 
- ungültige Eingaben nicht stillschweigend verändern bzw. geändert speichern, sondern eine Fehlermeldung auslösen. 

Das würde ich aber erst angehen, nachdem PR #864 durch ist.

# Hier mal meine Beobachtungen

## Keine Rückmeldung für ungültige Eingaben

Wähle ich im Widget **select** den 31.02.2020 aus bzw. gebe den Wert im Widget **input:text** direkt ein, wird in der DB `0000-00-00`  gespeichert. Und zwar ohne jeden Hinweis auf die Veränderung der Eingaben. 

Hat man das Formular mit "Übernehmen" gesichert, werden die falsch eingegebenen Werte erneut angezeigt. Wieder ohne jeden Hinweis auf den Eingabefehler. Hier entsteht der fatale Eindruck, dass die Werte so gespeichert sind. Flüchtigkeitsfehler werden eher nicht bemerkt.

![grafik](https://user-images.githubusercontent.com/10065904/78471351-fc1b3b00-7730-11ea-9c34-80872dd25ea7.png)

Zumindest arbeiten hier beide Widgets in gleicher Art und Weise.

## Verfälschung verkürzter Eingaben (input:text)

Ein kleiner Eingabefehler wie "3" statt "03" hat ganz andere Auswirkungen. Wenn nach Eingabe die Einzelteile tatsächlich ein gültiges Datum ergeben, werden sie auch gespeichert. Nur halt bei input:text etwas anders:
<img width="537" alt="grafik" src="https://user-images.githubusercontent.com/10065904/78471439-91b6ca80-7731-11ea-9275-56abc4a46f17.png">

# Lösungsidee

Es wäre möglich, bereits im Browser mittels HTML-Pattern eine Basisüberprüfung durchzuführen; jedoch nicht auf "inhaltlich korrektes Datum", nur Ziffern/Trennzeichen.  

Die finale Auswertung müsste nachgelagert erfolgen (in preValid und/oder einen Validator)

**Comment by dergel** [comment]
Ich glaube dein PR + die festgelegten Darstellungs/Ausgabeformen beheben das oder ? .. Bis dahin schliesse ich das hier.

**Comment by christophboecker** [comment]
Nee, der PR betraf nur die Suche.

**Comment by dergel** [comment]
plugin Tools mit inputmask kennst du ? das hilft ja schon viel.

**Comment by christophboecker** [comment]
Ja, kenne ich, finde ich aber nicht so toll weil nur im Browser laufend. Vor dem Speichern müsste eh nochmal geprüft werden; das ist die eigentliche Crux.

**Comment by dergel** [comment]
Lange ists her .. und leider erst jetzt wieder auf dem Schirm. Das Problem haben wir eigentlich an mehreren Stellen, dass bestimmte Dinge nicht geprüft werden, wie es ja auch in der Datenbank ist, wenn sie nicht auf strict eingestellt ist. Wir haben das bei Textfeldern die zu lange sind, oder bei integer/number wenn die Zahlen zu hoch sind oder auch Float und co.

Deswegen würde ich das in YForm gerne über Validates lösen. D.h. wenn du da was bauen möchtest, sehr gerne. Datumsüberprüfung fehlt definitiv.

**Comment by dergel** [comment]
* Man kann nun verkürzte Angaben machen
* Validierungen gehen über validate type time/date/datetime
* Zusätzlich bin ich weg von den eigenen Formaten, d.h. es werden nur noch Standardeingaben erlaubt.

**Comment by dergel** [comment]
ich schliesse mal. wenn ein Teilaspekt nicht ok ist, gerne als einzelnes einfaches issue - hier blicke ich kaum noch durch ;)

**Comment by christophboecker** [comment]
Danke.
