### ISSUE TITLE
MySQL-Mindestanforderung kommunizieren

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#869]
In Slack gab es jetzt einen Fall, bei dem der CSV-Import des Table Managers aufgrund einer zu alten MySQL-Version (5.5) fehlschlug. 

Hier wäre es hilfreich gewesen, wenn YForm eine zu niedrige MySQL-Version erkennt und davor warnt, die Installation verweigert o.ä. passiert, das einen Entwickler davor bewahrt, diese Kombination einzusetzen.

Laut redaxo.org ist die Anforderung von REDAXO selbst noch 5.5 oder höher.

**Comment by dergel** [comment]
ich konnte es nur simulieren. Wenn du jemanden hast, der diesen Fehler hatte und nun prüfen könnte, wäre das super.
