### ISSUE TITLE
GeoPlugin:: MissingKeyMapError

### ISSUE THREAD

**Issue by skerbis** [yakamara/redaxo_yform#87]
Anscheinend zieht Google die Daumenschrauben an. Es muss wohl jetzt ein API-Key hinterlegt werden.

**Comment by dergel** [comment]
auch gelesen.. muss natürlich hier dann noch ergänzt werden.

**Comment by dergel** [comment]
das ist irgendwie Schrott.. das ist ja abhängig von der Domain, bei mehreren Domains kommen wir also immer zu Problemen. Vielleicht ergänze ich das Feld nur um den API Key und den Rest muss der User selbst klären. (Falsche Domain beim Einloggen etc. Problem)

**Comment by skerbis** [comment]
Google vs. API ist definitiv Schrott. Bei der letzten Seite hat es 2 Tage gedauert bis die den Key akzeptiert haben.
