### ISSUE TITLE
bug: decimal-Feld (und ggf. andere Zahlenfelder) brauchen Default-Parameter

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#871]
Ein dezimal-Feld hatte keinen Wert für min/max und die Option `Felddefinition überschreiben` aktiv. YForm macht daraus: `CHANGE `land_area` `land_area` DECIMAL(,),`, was zu einem Whoops führt.

**Comment by dergel** [comment]
Ich habe nicht ganz verstanden wann ein solcher Fall auftritt. Bei der Felddefinition wird das abgefragt, dennoch habe ich einen Defaultwert gesetzt. Gerne gegentesten

**Comment by alexplusde** [comment]
Ich kann dir auch nicht mehr sagen, wie es passiert ist, aber es ging.
