### ISSUE TITLE
YForm ändert scheinbar die Kollation

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#872]
Erstes Schema von YDeploy

```
rex_yform_relation_table:
    charset: utf8mb4
    collation: utf8mb4_unicode_ci
```

Redakteur pflegt ein paar Daten … via AddOn "Backup" die Tabelle nach ein paar Tagen für mich exportiert. Sieht dann so aus:

```
CREATE TABLE `rex_yform_relation_table ` (
  ...
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
```

Das betrifft nur die Relationstabelle. Die zwei dazugehörigen Datentabellen blieben auf **utf8mb4**

Aufgefallen ist mir das erst durch die geänderte `schema.yml` von YDeploy.

**Comment by dergel** [comment]
Und das passiert einfach so, wenn man Daten pflegt ? Ohne reinstall oder ähnlichem ? Kannst du mir ein yform tableset zusammenstellen bei dem das passiert ?

**Comment by dergel** [comment]
Kann ich leider nicht nachvollziehen.

@tbaddade beobachtet

**Comment by staabm** [comment]
ich könnte mir vorstellen dass der umgekehrte fall eintreten kann als urspr. gemeldet, da normales utf8 nach utf8mb4 konvertiert wird bei migration der tabelle:

https://github.com/yakamara/redaxo_yform/blob/c409ff3125316a9cae16ab0feadda30fac62e13a/plugins/manager/lib/yform/manager/table_api.php#L536-L539

**Comment by dergel** [comment]
ja, das kann sein und ist in diesem Fall auch so gewollt. Ich schliesse mal, falls es klarer wird, @tbaddade , gerne melden.
