### ISSUE TITLE
be_manager_relation :: Listenansicht bei select[multiple] mit Relationstabelle falsch

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#875]
Hat man eine Relationstabelle dabei und `select[multiple]` ausgewählt, dann erscheint nichts in der Listenansicht.

Das value ist dann `null` und kann [hier](https://github.com/yakamara/redaxo_yform/blob/master/plugins/manager/lib/yform/value/be_manager_relation.php#L543) nicht via explode aus einander genommen werden.

**Comment by dergel** [comment]
habe es gerade getestet und hat funktioniert. 
<img width="132" alt="Bildschirmfoto 2020-05-13 um 22 38 24" src="https://user-images.githubusercontent.com/322951/81862807-8e9dce00-956a-11ea-9025-305d24650460.png">
<img width="196" alt="Bildschirmfoto 2020-05-13 um 22 38 39" src="https://user-images.githubusercontent.com/322951/81862810-8f366480-956a-11ea-8fcc-5bc0a6995d33.png">
<img width="250" alt="Bildschirmfoto 2020-05-13 um 22 38 52" src="https://user-images.githubusercontent.com/322951/81862813-8fcefb00-956a-11ea-89dc-6f1aa8e7b159.png">

**Comment by tbaddade** [comment]
Hast du es mit Relationstabelle probiert? Geht aus deinem Screenshot nicht hervor.
