### ISSUE TITLE
Fehler in Doku: Anführungszeichen falsch bei E-Mailplugin PHP Schreibweise

### ISSUE THREAD

**Issue by ritzfritz** [yakamara/redaxo_yform#876]
In der Doku bei  E-Mail-Plugin in PHP Schreibweise steht
if ("REX_YFORM_DATA[field="anrede"]" == "w") echo "Frau";
sollte aber
if ("REX_YFORM_DATA[field='anrede']" == "w") echo "Frau";
(Anführungszeichen)
heißen.

**Comment by dergel** [comment]
wurden bereits geändert. danke
