### ISSUE TITLE
Table Manager: Überflüssige Feld-Optionen eliminieren

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#88]
In Feldern wie bspw. "fieldset" oder "html" finden sich die Optionen
* in der Liste verstecken	und
*als Suchfeld aufnehmen.

Sehe ich das richtig, dass diese Optionen an dieser Stelle einfach keinen Sinn ergeben? Könnte man die evtl. eliminieren?

**Comment by dergel** [comment]
da in "liste verstecken" und "als suchfeld aufnehmen" standardeinstellungen sind, laesst sich das nicht so leicht umsetzen.. aber ja, die sind hier eigentlich unnötig und sollte man steuern können
