### ISSUE TITLE
choice/checkbox/select/radio: null erlauben

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#883]
es sollte eine Möglichkeit geben, eine Checkbox als Select zu rendern und *NULL* als Feld zu erlauben. Also nicht nur ja/nein, sondern auch ja/nein/unbekannt, eben: 1/0/NULL

**Comment by tbaddade** [comment]
> eine Checkbox als Select zu rendern

?

> Also nicht nur ja/nein, sondern auch ja/nein/unbekannt

Versteh ich nicht. Wenn eine Checkbox nicht angeklickt wird bekommt sie den Wert 0, klickt man diese an wird der Wert 1 gespeichert. Wo genau magst du jetzt NULL unterbringen? 

Vielleicht könntest du ein Praxisbeispiel anbringen um es verstehen zu können.

**Comment by alexplusde** [comment]
Es wird von einem Makler eine Immobilie erfasst. Ihm ist nicht bekannt, ob das WC im Badezimmer ist, oder extra. Er sollte bei `mit WC` weder ja noch nein auswählen, in der Datenbank sollte korrekterweise `NULL` für keine Angabe stehen.

Es geht nicht nur um dieses eine Attribut (WC im Badezimmer), sondern um schätzungsweise 40 solcher Möglichkeiten.

**Comment by tbaddade** [comment]
Wäre dann nicht ein `select` mit Platzhalter richtig? Alternativ ginge auch ein `select` und `radio` mit einer dritten Option `unklar/weiß ich nicht`.

**Comment by alexplusde** [comment]
Ein Platzhalter kann nicht als „NULL“ in der Datenbank gespeichert werden. :/

**Comment by tbaddade** [comment]
> Ein Platzhalter kann nicht als „NULL“ in der Datenbank gespeichert werden. :/

Ich gehe nicht weiter darauf ein. Ich fasse nur zusammen: Du willst eine Checkbox als Select rendern, welches wiederum drei Werte annehmen und speichern kann. Mach doch bitte einen PR.

**Comment by alexplusde** [comment]
Bitte, bevor ich einen PR mache, schreib mir, unter welchen Umständen ich null erlauben darf und wie dieser Wert erfasst werden soll. Ist ja dein Feld.

**Comment by alexplusde** [comment]
Ich habe mich mit verschiedenen Personen über diese und andere Diskussionen mit dir beraten und stelle fest: Es lässt sich mit dir auf fachlicher Ebene nicht lösen.

Probleme in deiner Kommunikation nach außen kann ich jedoch für dich nicht lösen.
