### ISSUE TITLE
Docs - Value Pools erläutern

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/redaxo_yform#888]
was enthält `$this` im Kontext eines Formulars? Wie lässt es sich verändern? Was sind die einzelnen Value Pools.

**Comment by dergel** [comment]
irgendwie funktioniert das wohl so nicht .. Meldet sich keiner. Deswegen schliesse ich issues dieser Art. Ich versuche bei Docs immer was direkt zu machen oder es erstmal zu lassen..

**Comment by alxndr-w** [comment]
Passt, von mir ist erstmal keine weitere Unterstützung absehbar. Es ist genug, da dürfen andere bei Bedarf ran.
