### ISSUE TITLE
Table Manager: be_relation-Feld sortierbar machen mit Prio bei Relationstabellen

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/redaxo_yform#89]
Ich hatte die Problematik mal in einem PR für xform erläutert, laut @gharlan könnte das Problem bei yform noch genauso bestehen:

https://github.com/yakamara/redaxo_xform/pull/339

Das Feld be_relation" legt ja auch in seiner Optik mit den Pfeilen hoch/runter schon nahe, dass man Einträge eines Datensatzes auch nachträglich umsortieren kann und nicht nur beim hinzufügen neuer Datensätze.

**Comment by gharlan** [comment]
Kann bestätigen, bei Nutzung von Relationstabellen klappt das Umsortieren nicht.

(Bei Multiple-Popup-Relations ohne Relationstabelle hingegen schon, funktioniert aber ja auch ganz anders.)

**Comment by alexplusde** [comment]
PR müsste man doch recht schnell umbauen können? Bin nur gerade so viel mit yform_doku beschäftigt ;)

https://github.com/yakamara/redaxo_xform/pull/339/commits/018ec5efd2a672160f3df1f534c43e51708adbc5

**Comment by dergel** [comment]
wie im anderen issue bereits beschrieben ist das nicht in dieser Form leicht machbar.

Am besten in diesen Fällen das neue BE Inline Relation Feld nutzen. Dann die Verknüpfungstabelle mit einem Priofeld versehen und schon kann man alles sortieren.

**Comment by alexplusde** [comment]
Moment, Moment, kannst du mir einen Screenshot der Konfiguration schicken?

**Comment by dergel** [comment]
![bildschirmfoto 2018-12-24 um 13 40 22](https://user-images.githubusercontent.com/322951/50399692-7e246200-0781-11e9-9c3a-148fa77dde73.png)

Haupttabelle mit inline Verknüpfung
![bildschirmfoto 2018-12-24 um 13 41 04](https://user-images.githubusercontent.com/322951/50399708-9f854e00-0781-11e9-9ee7-6c8daecd0e88.png)

Verknüpfungstabelle. relations zurück
![bildschirmfoto 2018-12-24 um 13 41 19](https://user-images.githubusercontent.com/322951/50399709-a01de480-0781-11e9-8286-bd36f679fd64.png)

**Comment by alexplusde** [comment]
Das eignet sich nur begrenzt, weil die Datensätze ja vollständig angezeigt werden, oder? 

Eine Sortierung von sagen wir mal 20 Datensätzen ufert in sehr viel drag&drop/pfeilklicken aus, oder? Ich finde das noch unbefriedigend. Die Prios sollten auch in anderen Relations-Optionen funktionieren.

**Comment by dergel** [comment]
funktioniert ja nur bei den Relationstabelle nicht wie du es dir wünscht, weil nirgends eine Prio gesetzt werden kannn. Bei den normalen MultipleFeldern gehts ja.

Umbau ist möglich aber aufwändig. In der Relationstabelle müsste man zunächst ein Priofeld anlegen, und das müsste dann beim Sortieren beachtet werden.

**Comment by tbaddade** [comment]
Hätte dies eben auch gut gebrauchen können. 
Haben es jetzt aber mit Inlinerelationen umgesetzt. Ist nur in der Pflege aber eher supoptimal.

**Comment by alexplusde** [comment]
Finde auch, dass Inline das Problem nicht ausreichend löst

**Comment by alexplusde** [comment]
Uff, ich bräuchte das jetzt oder portiere wohl meine Lösung aus xform in eine eigene Felddefinition. Eine Lösung ist noch nicht in Aussicht, oder?

**Comment by alexplusde** [comment]
Entschuldigt, wenn ich hier ein Selbstgespräch führe, aber 3 Jahre später habe ich ein besseres Verständnis von YForm bekommen und sehe das jetzt eigentlich als machbar an:

* die 2 Relations-Felder in der Relationstabelle werden in ihrer Kombination als UNIQUE definiert
* die Relationstabelle muss zusätzlich über 2 Prioritätsfelder verfügen
* beim Speichern bekommen die Datensätze mittels ON DUPLICATE UPDATE grundsätzlich die neue Reihenfolge definiert - je nachdem, von wo ich die Relation bearbeite (es müssen nie beide Prio-Felder ausgefüllt werden)
* somit wird das Problem gelöst, dass nicht wie bei meiner Lösung neue Datensätze angelegt werden mit neuen IDs, sondern die bestehenden erhalten bleiben.
* Der Zustand "Sortierbarkeit" sollte zum Standardverhalten werden.

Ich würde gerne einen PR dazu beitragen, habe aber das Gefühl, dass andere das besser könnten.

Die Fragen, die sich für mich stellen sind: Wenn man kein Prio-Feld hat, wird dann vielleicht automatisch eins angelegt? Wie müssen die beiden Prio-Felder heißen oder kann man die manuell verknüpfen? Akzeptiert man einfach ein Fehlverhalten, wenn es die Felder nicht gibt oder bekommt sogar einen Fehler?

Das ganze bezieht sich natürlich nach wie vor nur auf Relationen mit Hilfstabelle.

**Comment by alexplusde** [comment]
in

https://github.com/yakamara/redaxo_yform/blob/beec3f064dda79263f03d42a666af72eca3fe98b/plugins/manager/lib/yform/value/be_manager_relation.php#L436-L441

tauschen durch

```

        try {
            rex_sql_table::get(rex::getTable($relationTable))
            ->ensurePrimaryIdColumn()
            ->ensureColumn(new rex_sql_column($relationTableField['source']."_prio", 'int(10) unsigned'))
            ->ensureColumn(new rex_sql_column($relationTableField['source'], 'int(10) unsigned'))
            ->ensureColumn(new rex_sql_column($relationTableField['target'], 'int(10) unsigned'))
            ->ensureColumn(new rex_sql_column($relationTableField['target']."_prio", 'int(10) unsigned'))
            ->ensureIndex(new rex_sql_index($relationTableField['source']."_".$relationTableField['target'], [$relationTableField['source'], $relationTableField['target']], rex_sql_index::UNIQUE))
            ->ensure();
        } catch (PDOException $ex) {
        }

        $prio = 1;
        foreach ($values as $value) {
            
            rex_sql::factory()->setDebug(1)->setQuery('INSERT INTO '.$sql->escapeIdentifier($relationTable).'(`id`,'.$sql->escapeIdentifier($relationTableField['source']."_prio").','.$sql->escapeIdentifier($relationTableField['source']).','.$sql->escapeIdentifier($relationTableField['target']).') VALUES (NULL, :prio, :source, :target) ON DUPLICATE KEY UPDATE '.$sql->escapeIdentifier($relationTableField['source']."_prio").' = :prio, '.$sql->escapeIdentifier($relationTableField['source']) .' = :source, '.$sql->escapeIdentifier($relationTableField['target']).' = :target', [":prio"=>$prio++, ":source" => $source_id, ":target" => $value]);
        }     
```

Leider wird ensure() nicht übernommen, aber das ist ein guter Weg imho. Gespeichert wird jetzt auf jeden Fall in der richtigen Reihenfolge.

Wie kann ich, sofern ein prio-Feld vorhanden ist, dieses auch wieder auslesen, wenn die Reihenfolge für das Feld zusammengestellt wird?

**Comment by tbaddade** [comment]
> vermutlich hier, aber ich kann ja hier nicht order by source_prio machen, da ich ja nicht weiß, ob das Feld existiert. Wie löst man das?

Über die Methode `getValueFields(['type_name' => 'prio']);` kannst du schauen ob ein pro Feld existiert.

**Comment by alexplusde** [comment]
ich muss aber prüfen, ob 2 Priofelder mit bestimmtem Namen existieren, wie müsste das dann aussehen? Kann ich da ['name' => $relationTableFields['source'].'_prio' ] schreiben?

**Comment by tbaddade** [comment]
Die Methode gibt dir ein Array zurück, wo der Key der Spaltenname ist. Schau dir mal diese Zeilen an, wo alle Choice-Felder geholt werden.

https://github.com/yakamara/redaxo_yform_docs/issues/139

Ich vermute das ist das, was du benötigst.

**Comment by alexplusde** [comment]
Ich probiere es Mal aus...

**Comment by dergel** [comment]
habe es nicht komplett durchgelesen. Aber ich nehme mal den Titel und denke dass dieses Issue durch ist - wenn nein, gerne nochmal den zentralen Punkt einzeln aufschreiben :)

**Comment by alxndr-w** [comment]
Nicht, dass ich wüsste. Gibt's dazu etwas in YForm 4?

Ich wüsste immer noch nicht, dass das geht.

**Comment by alxndr-w** [comment]
![image](https://github.com/yakamara/yform/assets/3855487/d3bc1931-8a91-4ea9-8255-80e20603c29c)
