### ISSUE TITLE
Values anderst sortieren

### ISSUE THREAD

**Issue by Sioweb** [yakamara/redaxo_yform#9]
Ho!

Ich würde die Values von YForm anderst sortieren. Entweder generell anderst, so dass Eingabefelder, Dropdowns, Checkboxen und andere reguläre Formular-Elemente als erstes in der Liste stehen, oder so dass man die Optionen in den Einstellungen einfach via Drag&Drop sortieren kann.

Als Nice2Have könnte man die Sortierung dann als JSON exportieren / importieren, damit man das nicht in den anderen Installationen jedes Mal neu einstellen muss.

Aktuell ist es einfach etwas lästig bis man "Text" findet.

![dragndrop](https://cloud.githubusercontent.com/assets/1318048/11835976/c5a7c024-a3d7-11e5-8f08-6b6dfa229032.png)

Die grünen Pfeile symbolisieren die Drag&Drop Geschichte :)

**Comment by dergel** [comment]
ich hatte mal sowas wie Favoriten.. Vielleicht wieder aufnehmen  ?? ..

**Comment by Sioweb** [comment]
+1

**Comment by alexplusde** [comment]
definiert sind die Favoriten sogar noch via "famous", siehe:

https://github.com/yakamara/redaxo_yform/blob/master/lib/yform/value/text.php#L50
