### ISSUE TITLE
option "schemadefinition immer überschreiben"

### ISSUE THREAD

**Issue by staabm** [yakamara/redaxo_yform#901]
was bedeutet diese option?

sie liest sich sehr destruktiv, d.h. vermutlich kann man damit schaden anrichten bzw. sich selbst daten überschreiben wenn man sie falsch einstellt. leider lässt der text viel interpretationsspielrraum.. sollte hier ein "infotext" die option näher beschreiben oder einfach nur der options-text "passender/freundlicher" umformuliert werden?

ich kann es nicht beurteilen da ich nicht weiß was diese option ausmacht..

![grafik](https://user-images.githubusercontent.com/120441/82829566-db12d300-9eb3-11ea-9d35-4ec22d25e7a7.png)

**Comment by alexplusde** [comment]
Es wird sichergestellt, dass die Datentypen (Text, varchar, ...) In der Tabelle übereinstimmen mit der Konfiguration. Vergleichbar mit `ensure`.

Manuelle Änderungen an der vom Table Manager verwalteten Datenbanktabelle gehen dann verloren.

**Comment by staabm** [comment]
> Es wird sichergestellt, dass die Datentypen (Text, varchar, ...) In der Tabelle übereinstimmen mit der Konfiguration.

dieser satz liest sich als wäre es ein "check".

wann wird was mit was überschrieben?

**Comment by alexplusde** [comment]
Klassischerweise hat sich YForm früher bis dato rausgehalten und manuelle Änderungen (Adminer/PHPMyAdmin) an den Datenbanktabellen, insbesondere Änderungen am Datentyp,  gekonnt zugelassen.

**Comment by staabm** [comment]
ich kann dir nicht folgen. wann wird was mit was überschrieben?

**Comment by alexplusde** [comment]
Wir können dazu gerne einen Screencast machen.

**Comment by alxndr-w** [comment]
Es wird sichergestellt, dass die Definitionen der Felder im Table Manager an der Tabelle auch in der Datenbank so abgebildet sind. Bspw. wenn man ein Decimal-Feld von DECIMAL(5,0) auf DECIMAL(7,2) stellt, wird dies auch an der Datenbanktabelle in MySQL aktualisiert.
