### ISSUE TITLE
tabellenname als datalist

### ISSUE THREAD

**Issue by staabm** [yakamara/redaxo_yform#902]
randnotiz: ich mache meine ersten steps mit yform und stelle die fragen, die mir in den sinn kommen.. ggf. sind sie quatsch und können geschlossen werden..

hier ist der tabellen-name ein freitextfeld

![grafik](https://user-images.githubusercontent.com/120441/82830466-1f06d780-9eb6-11ea-9f7f-e0618c3d20f9.png)

man gibt hier eine tabelle ein, die noch nicht in mysql existiert, oder wählt eine die es schon gibt, um diese im yform bekannt zu machen, richtig?

falls ja: hier würde ein `<datalist>` zum input sinn machen, sodass der browser eine vorschlags-komponente liefert (ähnlich einem dropdown), aber dennoch freitext zulässt, siehe https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist

**Comment by alexplusde** [comment]
Neu.

Für bestehende Tabellen gibt's die Migration.

Hast du bei deinen ersten Schritten auch in die Doku schon sehen können?
