### ISSUE TITLE
docs verlinken auf archiviertes github repo

### ISSUE THREAD

**Issue by staabm** [yakamara/redaxo_yform#903]
wenn man die doku öffnet https://redaxo.mst20/redaxo/index.php?page=yform/docs
bekommt man inhalte mit dateinamen

![grafik](https://user-images.githubusercontent.com/120441/82830821-1531a400-9eb7-11ea-8794-681f303f919c.png)

bei click auf die dateinamen landet man direkt auf github - in einem archivierten repo:
![grafik](https://user-images.githubusercontent.com/120441/82830856-27134700-9eb7-11ea-8250-6fdee5f184cb.png)

sind die urls ggf. veraltete? wie müssten die urls lauten?

**Comment by alexplusde** [comment]
Bitte Github-Version verwenden dazu.

**Comment by staabm** [comment]
> Bitte Github-Version verwenden dazu.

d.h. dieser bug existiert nicht im aktuellen master branch? oder wie darf ich das verstehen?

**Comment by alexplusde** [comment]
Ja, das docs-Plugin wurde entfernt und in dieses Repo integriert.
