### ISSUE TITLE
„ Ausgabe der Table Manager-Daten im Frontend“ auf YOrm hinweisen?

### ISSUE THREAD

**Issue by staabm** [yakamara/redaxo_yform#905]
Sollte man hier https://github.com/yakamara/redaxo_yform/blob/d8bacb95fbcfd087551e145177b7c794804f74e8/docs/table_manager.md#ausgabe-der-table-manager-daten-im-frontend Auch auf yorm hinweisen und verlinken?

**Comment by alexplusde** [comment]
Ja

**Comment by alexplusde** [comment]
Bitte auch im alten Docs-Repo die Issues beachten, da sind evtl. solche Sachen schon vermerkt.

**Comment by tbaddade** [comment]
> Bitte auch im alten Docs-Repo die Issues beachten, da sind evtl. solche Sachen schon vermerkt

Wäre es nicht besser diese Issues zu transferieren? Du kannst doch nicht verlangen, dass man sich alle Issues archivierter Repos ansieht.

**Comment by alexplusde** [comment]
War nicht gewünscht. Ja, ich fände es auch besser.

**Comment by staabm** [comment]
> Wäre es nicht besser diese Issues zu transferieren? Du kannst doch nicht verlangen, dass man sich alle Issues archivierter Repos ansieht.

seh ich auch so. die issues die noch relevant sind sollten transferiert werden

**Comment by alexplusde** [comment]
Ich habe dort keine Schreibrechte. Bitte gerne in Absprache mit @dergel transferieren und mit Docs labeln. Meinen Segen habt ihr.
