### ISSUE TITLE
Beispiel bei number-Feld verbessern

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/redaxo_yform#908]
https://github.com/yakamara/redaxo_yform/blob/ff38ae5b58c8d91b66d79091b24fc7e125425ce7/lang/de_de.lang#L81-L82

Zu komplex, um es auf Anhieb zu verstehen. Ich würde mit 2 einfachen Beispielen in der Notice arbeiten:

> Anzahl der Ziffern inkl. Dezimalstellen insg., z. B. `6` eingeben für `4999,95` oder `100.000`
> Anzahl der Ziffern für Nachkommastellen, z.B. `2` eingeben für `4999,95` oder `5` für `49.00001`

Wie verhält sich das eig. für Negativzahlen? Ist das Vorzeichen `-` auch eine Stelle?

**Comment by dergel** [comment]
gerne als PR.. Bis dahin würde es belassen.

**Comment by alxndr-w** [comment]
Der PR wäre sofort da, wenn meine Frage nach dem Vorzeichen beantwortet ist.

**Comment by dergel** [comment]
das Vorzeichen ist keine Ziffer.
