### ISSUE TITLE
Email als 3. Parameter .. 

### ISSUE THREAD

**Issue by dergel** [yakamara/redaxo_yform#909]
noch testen ..
phpstorm meldet komische dinge und ich hatte noch keine Zeit das zu prüfem

https://github.com/yakamara/redaxo_yform/commit/5368d083779fc708be270b0f2b0fc86401aff40e#diff-f9fb3ed5b605e74b9566c32c81a7a5fcR39

**Comment by tbaddade** [comment]
@olien und ich haben die Anpassungen vom @dergel nochmals getestet und scheint alles zu passen.

**Comment by alexplusde** [comment]
Danke dafür.
