### ISSUE TITLE
GeoPlugin :: Karte wird nicht initiiert, nach Klick auf "Übernehmen"

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#91]
Um das zu umgehen, hab ich hier die PHP-Abfrage herausgenommen, so dass die Api immer geholt wird.
https://github.com/yakamara/redaxo_yform/blob/master/plugins/geo/ytemplates/bootstrap/value.google_geocode.tpl.php#L25-L27

**Comment by dergel** [comment]
genau so ist es nun drin ..
