### ISSUE TITLE
REX_YFORM_TABLE_DATA für mblock

### ISSUE THREAD

**Issue by skerbis** [yakamara/redaxo_yform#911]
Aktuell kann REX_YFORM_DATA nich mit mblock eingesetzt werden. 
Genauere Infos hat ggf. @joachimdoeer

**Comment by tbaddade** [comment]
Betrifft das nicht auch alle anderen REX_VARs die nicht vom Core oder Core-AddOns kommen?

> Genauere Infos hat ggf. @joachimdoeer

Vielleicht kann @joachimdoerr das hier zusammenfassen. Ich fände es gut, wenn auch andere REX_VARs mit MBlock zusammenarbeiten können.
