### ISSUE TITLE
send lässt sich nicht auf 0 stellen

### ISSUE THREAD

**Issue by polarpixel** [yakamara/redaxo_yform#916]
Wenn ich es richtig verstehe, kann man durch
`$yform->setObjectparams('send', '0');`
"send" auf 0 stellen, um den Formularversand zu unterbinden.

"send" steht aber trotzdem immer auf 1.
Getestet mit `dump($_REQUEST)`

**Comment by dergel** [comment]
Kannst du es mit der aktuellen Version bitte nochmal testen, wenn es noch so ist, bitte ein einfaches Test php hier reinlegen. Daaanke Peter :)
