### ISSUE TITLE
Zyklische Abhängigkeiten zwischen yform, ycom, yrewrite 

### ISSUE THREAD

**Issue by staabm** [yakamara/redaxo_yform#917]
Slack Konversation:

> Wie kommt man denn am besten aus folgender Falle raus, dass sich die 3 AddOns gegenseitig bedingen und ich deshalb keines updaten darf? 🙂
> ![C37FF7FD-C0E9-4806-ADF1-497534E2F8AA](https://user-images.githubusercontent.com/120441/84568549-6a5b2a00-ad80-11ea-9e4a-455586fb62cb.jpeg)

Workaround:
> Du kannst in der package.yml von yrewrite und ycom die Mindestanforderung an YForm auskommentieren. Dann kannst du das updaten und anschließend die anderen beiden Addons. 

Wir sollten versuchne diese zyklische Abhängigkeit aufzulösen

**Comment by alexplusde** [comment]
Oder es muss die Möglichkeit geben, alle in einem Rutsch zu updaten.

**Comment by staabm** [comment]
> Oder es muss die Möglichkeit geben, alle in einem Rutsch zu updaten.

Wir sollten keine mechanismen bauen die das anti-pattern zyklische Abhängigkeiten begünstigen.

**Comment by alexplusde** [comment]
M.E. war das passiert durch eine zu strikt erzwungene Prüfung auf die 2.x-Branch von YForm. Es müsste ein Update für die jeweiligen Addons geben, das die 3.x-Branch erlaubt. Das ist Aufgabe der Addon-Entwickler und der Branches.

Aber m.E. ist YForm hier die verkehrte Anlaufstelle.

**Comment by gharlan** [comment]
Ich stimme Alex zu. Zyklisch sind die Abhängigkeiten nicht, denn YForm ist weder von YCom noch von YRewrite abhängig.
Problem ist einfach nur dass es eine YRewrite-Version gibt, die nur mit YForm 2 arbeitet, und eine andere, die nur mit YForm 3 arbeitet.
Ein gleichzeitiges Update wäre also sehr hilfreich. Aber gehe nicht davon aus, dass das sobald kommt.

Mein Workaround ist hier übrigens immer ein anderer. Nicht die package.yml ändern, sondern:

- YRewrite/YCom deaktivieren
- YForm aktualisieren
- YRewrite/YCom aktualisieren
- YRewrite/YCom wieder aktivieren

Sehe hier in YForm somit aber auch keine Änderungsmöglichkeit/-notwendigkeit, sondern entweder im Core (gleichzeitige Updates), oder in YRewrite/YCom (kompatibel zu älteren YForm bleiben).
