### ISSUE TITLE
`rex_`-Präfix in Tableset-Import veränderbar machen

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/redaxo_yform#919]
aufgefallen durch: https://github.com/FriendsOfREDAXO/yrewrite_domain_settings/issues/14

**Comment by alexplusde** [comment]
Ich glaube, es wäre am sinnvollsten, wenn YForm den table prefix als Information mit im Tablet speichert und beim Import entsprechend den Vorgaben der aktuellen redaxo Installation handelt.

**Comment by tbaddade** [comment]
@dergel Wird der [Platzhalter](https://github.com/redaxo/redaxo/blob/master/redaxo/src/core/lib/sql/util.php#L115) beim Import berücksichtigt?

**Comment by christophboecker** [comment]
Ich bin mir nicht sicher, ob es so einfach ist, xyz_ durch abc_ auszutauschen. Irgendwo tauchte mal der Fall auf, das Entwickler ihre eigenen Dateien mit einem anderen Präfix kennzeichnen. Nur ausgewählte Felder zu ändern ist riskant; man weiß ja nicht, welche eigenen Feldtypen was wo wie speichern  Der Export bzw. die Migration nehmen auch alles was in der DB bz. im Table-Manager ist. Ich kann verstehen, dass es so ist wie es ist.

**Comment by dergel** [comment]
Ich tendiere dazu, es einfach so zu lassen. Ich empfinde das als richtig, weil auch nicht rex_ tabellen dabei sein könnten und eigenständig funktionieren. Das Problem kommt durch z.B. Backups, wo man diese Tabellen nicht mehr "entdeckt". Meines Erachtens sollte man dort diese Optionen anbieten Tabellen auch ohne Präfixe sichern zu können.
