### ISSUE TITLE
validate type email prüft nicht vollständig

### ISSUE THREAD

**Issue by 191977** [yakamara/redaxo_yform#920]
Hi, 
laut doku soll man den validate email nicht mehr verwenden sondern auf type email prüfen.
Dieser fängt zwar vornehinten.de ab, lässt jedoch vorne@hinten durch ohne auf .tld zu prüfen.
Danke für schauen!

**Comment by jelleschutter** [comment]
Das ist weil der Validate sich gleich verhält wie der clientseitige E-Mail Input im Browser. Siehe #199

**Comment by alexplusde** [comment]
keine tld ergibt trotzdem eine gültige E-Mail-Adresse, bspw. `mail@localhost` ist gültig.
