### ISSUE TITLE
YForm-Formbuilder: Choice-Attribut "required" wird nicht korrekt übernommen.

### ISSUE THREAD

**Issue by danspringer** [yakamara/redaxo_yform#927]
Für das Frontend bringt folgender Code keine Select-Box mit "required"-Attribut:

```
$yform->setValueField('choice', array(
					'name' => 'auto',
					'label' =>'Auto',
					'placeholder' => 'Sind Sie mobil?',
					'choices' => 'Führerschein, Kein Führerschein',
					'required' => 'required'
					));
```
Versucht man es hingegen so, funktioniert es:
```
'required' => 'required',
'attributes' => '{"id":"foo", "class":"form-control"}'
```

Funktioniert auch:
`'attributes' => '{"required":"required", "id":"foo", "class":"form-control"}'`

Funktioniert nicht:
```
'required' => 'required'
// Keine Attributes
```

Rex 5.11
YForm 3.4

**Comment by tbaddade** [comment]
https://github.com/yakamara/redaxo_yform/blob/master/lib/yform/value/choice.php#L113-L126

Hier ist ein `required` gar nicht gelistet? Wie kommst du darauf, dass man es so notieren kann?

**Comment by danspringer** [comment]
Hatte ich gar nicht reingeschaut und bin aufgrund der Values für Text, bei denen das funktioniert, davor ausgegangen dass es sich bei Choice konsistent verhält.

**Comment by gharlan** [comment]
@tbaddade Hier wird es als explizites Attribut eingelesen, aber nur wenn "attributes" irgendwie gesetzt ist:
https://github.com/yakamara/redaxo_yform/blob/05619937c71a489ba76c9b9cc88dcb04b1e15ffe/lib/yform/value/choice.php#L79

**Comment by christophboecker** [comment]
Ich rate mal: Mißverständnis? 
Das oben beschriebene Array hat keine HTML-Attribute, sondern die Attribute des Choice-Feldes
https://github.com/yakamara/redaxo_yform/blob/d4b1b250e479875e9ecc52681889cc4b7690e90f/lib/yform/value/choice.php#L107-L132
Dort gibt es - konistent zu anderen values - das Feld "Attribute". Und das kriegt die HTML-Attribute. Deshalb ist das auch wie oben beschrieben richtig: 
> Funktioniert auch:
'attributes' => '{"required":"required", "id":"foo", "class":"form-control"}'

**Comment by gharlan** [comment]
Auch Textfelder haben in ihrer Definition kein `required`, und unterstützen es trotzdem als separaten Wert.
Die werden dort ebenso [über `getAttributeElements` eingelesen](https://github.com/yakamara/redaxo_yform/blob/d4b1b250e479875e9ecc52681889cc4b7690e90f/ytemplates/bootstrap/value.text.tpl.php#L38), bloß ohne if drum. Deswegen funktionieren sie dort auch ohne dass "attributes" auch gesetzt sein muss.

**Comment by christophboecker** [comment]
Ich hab ne Meinung (man könnte das Issue schließen), fühle mich aber nicht berufen, hier Entscheidungen zu treffen.

**Comment by gharlan** [comment]
Ich würde hier das if drum rum entfernen:
https://github.com/yakamara/redaxo_yform/blob/05619937c71a489ba76c9b9cc88dcb04b1e15ffe/lib/yform/value/choice.php#L78-L80

**Comment by dergel** [comment]
Habe die Abfrage entfernt
