### ISSUE TITLE
Formularcode in Tablemanager liefert bei 'compare_value' falschen Operator

### ISSUE THREAD

**Issue by cedrus86** [yakamara/redaxo_yform#928]
Im Tablemanager wird ein Feld definiert, z.B. ein Choicefeld. Dazu eine Validateregel vom Type 'compare_value'. im Formularcode wird anstelle des Operators eine ID ausgegeben (3 statt ==)
```
choice|obst|Obst|Bitte wählen=0,Birne=1,Banane=2,Kirsche=3,
validate|compare_value|obst|0|3|Bitte wähle ein Obst aus|
 bzw. in php:
$yform->setValueField('choice', array('obst','Obst','Bitte wählen=0,Birne=1,Banane=2,Kirsche=3','0','0','','','','','','','','','0'));
$yform->setValidateField('compare_value', array("obst","0","3","|Bitte wähle ein Obst aus"));
```

**Comment by tyrant88** [comment]
betrifft wohl alle Felder, die als Attribut eines vom typ "choice" haben.

**Comment by cedrus86** [comment]
> betrifft wohl alle Felder, die als Attribut eines vom typ "choice" haben.
Es liegt am Validate'compare_value'
Bei Integer habe ich genau das gleiche Problem:
`$yform->setValueField('integer', ['zahl','Zahl','','0']);
$yform->setValidateField('compare_value', ['zahl','10','3','muss gleich Zehn sein']);`
Es liegt also nicht am Feldtyp sondern am Validatetyp. Bei  validate 'compare' funktioniert es bei einem choice-Feld wie erwartet
`$yform->setValidateField('compare', ['name','obst','!=','ungleich']);
`

**Comment by cedrus86** [comment]
auch bei date-Feldern besteht das Problem:
`$yform->setValidateField('compare_value', ['startDate','0000-00-00 00:00:00'**,'0'**,'leer']); //!=
`
