### ISSUE TITLE
mit yForm Table Manager kann man Spalten von Systemtabellen überschreiben

### ISSUE THREAD

**Issue by iceman-fx** [yakamara/redaxo_yform#944]
Keine Ahnung ob das so gewollt ist, aber wenn man nicht aufpasst, dann kann man mit dem TM beim Anlegen von Tabellen und Spalten auch Redaxo-eigene Tabellen samt Spalten überschreiben.

Bsp:
Ich habe testweise mal als Name der Tabelle "rex_action" angegeben.
Dort konnte ich problemlos die Spalten verändern, z.B. aus createdate statt varchar ein tinyint (Checkbox) machen oder diese auch löschen.

Ich wäre jetzt davon ausgegangen, dass die Tabellennamen ein zusätzliches Prefix oder so automatisch davor gesetzt bekommen, damit man keine Bestandstabellen tangiert.

Ich denke, dass da eine Prüfung beim Anlegen prüfen sollte, ob es eine Systemtabelle ist und ob man eine bestehende Tabelle wirklich editieren möchte.
Sonst kann man schnell mal auch eine Addon-Tabelle oder eine Systemtabelle verändern oder zerschießen.

**Comment by alxndr-w** [comment]
Siehe auch #901

**Comment by dergel** [comment]
das ist ok so. Klar sollte man das nicht bei diesen Tabellen tun und wenn dann sehr aufpassen, aber das extra zu unterbinden sehe ich nicht als Aufgabe.

**Comment by alxndr-w** [comment]
Das kollidiert mit den anderen Issues - hier lässt sich nicht vermeiden, dass Änderungen durch die Migration passieren, die im Widerspruch stehen zu dem, was der Core oder das Addon möchte.

**Comment by iceman-fx** [comment]
@dergel 
So einfach würde ich dies nicht abtun, da man so immensen Schaden am Grundsystem verursachen kann.

Ist denn sichergestellt, dass ein normaler Redakteur keine Tabellen mit yform anlegen bzw. verändern kann?
Gibt es dazu entsprechende Berechtigungen?

**Comment by christophboecker** [comment]
In der package.yml des Managers steht, dass admin-Rechte erforderlich sind.

**Comment by dergel** [comment]
Jeder Admin kann das System zerstören. Und natürlich auch hier, wenn die falschen Tabellen migriert werden und man Änderungen durch ein YForm-Schema zulässt. Das gilt natürlich auch für nicht Core Tabellen, wenn z.B. ein AddOn eine eigene Tabelle hat - aber es kann auch mal gewollt sein, um z.B. die REST API zu nutzen.. Ich sehe das als Admin Entscheidung.

**Comment by iceman-fx** [comment]
Und genau das sehe ich als Denkfehler in Deiner Aussage.
Es ist nicht jeder ein Vollblut-Admin und bei Fragen zu einfachen Datenlisten wird meist yForm empfohlen.
Dadurch kann es nun sehr schnell mal passieren, dass diese Person damit sein Rex zerschießt, nur weil es keine Sicherheitsabfrage gibt.

Aus Programmierersicht finde ich das fatal, da es bei einer guten Software dazugehören sollte.
Aber gut, wenn es die Philosophie dahinter sein soll. War ja nur eine Anregung zur Verbesserung.
