### ISSUE TITLE
yrewrite: Bug: 2.7 :: URL-Typ: Umleitung zu Artikel vs. Metadaten

### ISSUE THREAD

**Issue by skerbis** [yakamara/redaxo_yform#945]
Die Widgets bekommen die gleiche ID in der Artikel-Sidebar

<img width="333" alt="94286888-e5bea100-ff55-11ea-97e9-0bf69eca4509" src="https://user-images.githubusercontent.com/791247/94338723-cc206680-fff4-11ea-97cf-693a9dba0691.png">

Wenn ich im BE_LINK Template ein Prefix für die ID setze z.B. 99 funktioniert es wieder. 
Hätte gerne yf_ oder sowas genommen, das js akzeptiert aber nur numerische Werte. 

aus
https://github.com/yakamara/redaxo_yform/blob/118bf1b0d31d4f601b905e27cc9c7c4d75da5679/plugins/manager/ytemplates/bootstrap/value.be_link.tpl.php#L11
mach
`$widget = rex_var_link::getWidget('99'.$buttonId, $name, $value, []);`

https://github.com/yakamara/redaxo_yrewrite/issues/365

**Comment by alxndr-w** [comment]
Das passierte übrigens auch, wenn man einen Block editiert. Wurde das Szenario auch gefixt?

**Comment by alxndr-w** [comment]
Wurde es nicht. https://github.com/redaxo/redaxo/issues/4610

**Comment by dergel** [comment]
genau.. das muss entweder jedes aufrufende system selbst dynamisch machen, also die ID zufällig setzen, oder im core dann pauschal. aber ist kein yform problem
