### ISSUE TITLE
Schemadefinition überschreiben - komplett abschalten

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/redaxo_yform#948]
Die Option "Datenbankfelder IMMER mit Schemadefinition überschreiben" zu deaktivieren, bedeutet nicht, dass die Schemadefinition NIE überschrieben wird. 

![image](https://user-images.githubusercontent.com/3855487/95731232-882d9280-0c7f-11eb-9a51-6b0efb5351a1.png)

Beispielsweise beim Import von Tablesets oder Addon-Installationen, die dies machen, hätte ich erwartet, dass ein Deaktivieren der Checkbox "Datenbankfelder IMMER mit Schemadefinition überschreiben" eben dies grundsätzlich unterlässt.

Als Entwickler erwartet man auch nicht, dass bei deaktivierter Option das Verhalten "Datenbankfelder MANCHMAL mit Schemadefinition überschreiben" eintritt.

Betrifft auch #901 

In meinem Fall wurden damit auch wichtige Konfigurationen überschrieben, die ich an der Datenbank vorgenommen hatte, ohne die Felddefinitionen im Table Manager nachzuziehen. Dabei gingen Daten verloren, wenn bspw. ein Decimal-Feld von 5 auf 2 Stellen zurückgesetzt wurden, oder binary auf varchar, etc.

**Comment by dergel** [comment]
Etwas spät, aber nun kam ich auch dazu mir das genauer anzusehen.. Ein paar Anpassungen sind mittlerweile gemacht worden und beim Migrieren eine Tabelle kann man mittlerweile einstellen, ob man ein Anpassung über das Schema haben möchte.

In diesem Fall sehe ich das aber anders. Wenn ich ein Schema importiere, möchte ich, dass dieses Schema genauso eingestellt wird, d.h. dass diese Schemainformationen genauso vorhanden sind, und damit es gesichert ist, dass ich das bekomme was im Schema drin steht. Das gilt für AddOns beim Import der Tablesets wie auch wenn man selbst einen Tableset manuell installiert.

Wenn es manchmal bei anderen Aktionen passieren sollte, ist das natürlich ein Fehler. Wenn du mir diese nennt, schaue ich natürlich gerne nach.

**Comment by alxndr-w** [comment]
Ich habe es nicht ganz im Blick. Ich meine der Erinnerung nach passierte es auch, wenn in Tabelle A die Feldaktualisierung angestoßen wurde, wurde auch die Schemadefinition in Tabelle B aktualisiert, selbst wenn der Haken „überschreiben“ an Tabelle B abgewählt war.

Ich müsste das nochmal nachstellen mit der aktuellen GitHub-Version. Kann ich leider gerade nicht leisten.

**Comment by dergel** [comment]
Kein Thema .. wenn du dazu kommst - top :) ..

**Comment by alxndr-w** [comment]
"Cache löschen" löste das ungewollt bei mir aus.
