### ISSUE TITLE
objparams in der Hilfe anzeigen

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#95]
Wäre grad im Formbuilder eine enorme Hilfe.

**Comment by dergel** [comment]
Oder wir legen an alle Felder immer einen Dokulink. D.h. dann wäre beim Infotext immer ein entsprechender Link. Müsste das Dokuteam noch helfen.. @alexplusde @polarpixel

**Comment by alexplusde** [comment]
Du meintest hier, oder?

Fände ich auch praktischer, wenn das nicht über einen Link, sondern direkt mit Beispielen zugänglich wäre.

![editiermodus freskoisten die neuen werber redaxo cms](https://cloud.githubusercontent.com/assets/3855487/18544526/4d1f740e-7b35-11e6-9466-d2f54aec9645.png)

**Comment by dergel** [comment]
muss man manuell reinlegen. Es viele objparams, die man nicht nutzen sollte und nur für interne zwecke sind

Hier schonmal meine Lists:

submit_btn_label=[Meintext]
submit_btn_show=[0/1]
real_field_names=[0/1]
form_method=[get/post]
form_action=[meineurl.php]
form_anchor=[meinanker]
form_showformafterupdate=[0/1]
form_show=[0/1]
form_name=[meinekennung]
form_class=[meineclass]
form_wrap_id=[meinehtmlid]
form_wrap_class=[wrapperclass]
form_ytemplate=[bootstrap,classic]
debug=[0/1]
hide_top_warning_messages=[0/1]
hide_field_warning_messages=[0/1]

getdata=[0/1]
main_where=[id=12]
main_id=[meineid]
main_table=[meinetabelle]

**Comment by alxndr-w** [comment]
@tbaddade würdest du sagen, die Doku hat eine Qualität erreicht, in der das ausreichend ist? Benutzt du noch den Formbuilder und die PHP-Schreibweise oder bist du nicht auch auf PHP umgestiegen?

**Comment by tbaddade** [comment]
Damals ging es um einen Kunden, der sich selbst über den Builder kleine Formulare erstellt hatte.

Ich selbst rufe immer diese [Datei](https://github.com/yakamara/redaxo_yform/blob/master/lib/yform.php) auf GH auf.

Und ja die Doku ist gut und würde hier jetzt schließen.
