### ISSUE TITLE
History :: Erfassen von Usern außerhalb Backend

### ISSUE THREAD

**Issue by skerbis** [yakamara/redaxo_yform#950]
Szenario. 
Ein YCOM-User hat "aus Spaß" mehrere Datensätze gelöscht. 
Dieser User wird jedoch nicht in der History erfasst und kann so nicht verantwortlich gemacht werden. 

Ein EP wäre hier sinnvoll um den YCOM-User erfassen zu können, der den Datensatz gelöscht hat. 
Aktuell wird als User nur "frontend" gelistet. 

![Bildschirmfoto 2020-10-21 um 11 50 12](https://user-images.githubusercontent.com/791247/96703808-95d7cc00-1393-11eb-9ede-f1c416f58b00.png)

**Comment by dergel** [comment]
```
$user = rex::getEnvironment();
if ('backend' == $user && rex::getUser()) {
    $user = rex::getUser()->getLogin();
}
```

in der dataset.php Zeile 610
EP einbauen ?

**Comment by skerbis** [comment]
@dergel jupp. Darfst mich gerne assingen. Ich mache einen PR.
