### ISSUE TITLE
Table Manager Listenansicht: Nur Datum ausspielen zeigt [2018-00-00] 

### ISSUE THREAD

**Issue by rkemmere** [yakamara/redaxo_yform#952]
Sehr komisches Verhalten. In der Eingabe kann man definieren, das nur das Jahr zur Eingabe steht. In der Listview wird aber das Jahr mit 00-00 angezeigt.

Meiner Meinung nach passt die Abfrage in der  getListValue($params) nicht 

`if (($d = DateTime::createFromFormat('Y-m-d', $params['subject'])) && $d->format('Y-m-d') == $params['subject']) {
            return '<nobr>'.self::date_getFromFormattedDate($params['subject'], 'YYYY-MM-DD', $format).'</nobr>';
        }`

Der Return wäre genau das was auch in der Eingabe ausgewählt wurde.

**Comment by rkemmere** [comment]
Vielleicht eine Abfrage nur, ob der DB Datensatz ein Objekt zurückliefert.

`DateTime::createFromFormat('Y-m-d', $params['subject'])`

**Comment by dergel** [comment]
Kannst du mir die Einstellungen des Feldes schicken ? eventuell einen Screenshot ?

**Comment by rkemmere** [comment]
![image](https://user-images.githubusercontent.com/2286625/96963732-7793dc80-1509-11eb-90f7-e7867e9dc843.png)

Ich habe beim Anlegen ausgewählt, dass nur Jahr angezeigt werden soll. Beim Speichern eines Datensatzes in die DB wird aber 2020-00-00 gespeichert. Das ist natürlich ein fehlerhaftes Format. Das gleiche Problem ist bei allen anderen Einstellungen auch, sofern nicht alle drei Select Felder für Jahr, Monat und Tag gesetzt werden.

**Comment by alxndr-w** [comment]
@rkemmere wenn du nur das Jahr eingeben willst, dann ist ein number-Feld das richtige für dich. Hier geht es um Datumsfelder. Ein Datum ist ein Tag im Kalender. https://dev.mysql.com/doc/refman/5.6/en/datetime.html#

**Comment by rkemmere** [comment]
@alxndr-w Ich bin über das Update von YFORM 2 zu YFORM 3 auf dieses Verhalten gekommen. Die DB ist ja nicht neu, sondern besteht schon mit vielen Datensätzen. Ich versteh schon den Ansatz was man wie in mysql abbildet, auch das ein Datum nur ein Datum ist, wenn es Valide gespeichert wird. Dennoch wird die Möglichkeit über das YFORM gegeben als Anzeigeformat nur Jahr zu wählen. 

Gehe ich mal von einem DAU User aus, der sich die DB über das Backend zusammenklickt, kommt dieser ebenfalls in dieses Verhalten.

**Comment by alxndr-w** [comment]
Also geht es eigentlich darum, dass in solchen Fällen der 1. des Monats und der 1. Monat des Jahres eingetragen wird, wenn diese Angaben fehlen?

**Comment by tyrant88** [comment]
Ich glaube es geht nur um die Ausgabe in der Listenansicht.
Eigentlich müsste die IF-Abfrage entfernt werden. Dann würde auch für ungültige Datumswerte das gewählte Ausgabeformat angewandt.

**Comment by rkemmere** [comment]
Entweder die IF Bedingung entfernt oder beim Speichern muss der Datensatz egal ob nur Jahr oder Jahr und Monat immer aufgefüllt werden. 

Weil das gleiche Verhalten ist auch, wenn jemand als Anzeigeformat YYYY-MM-DD wählt, bei der Eingabe aber DD leer lässt. Dann steht in der DB 2020-10-00 und die Ausgabe würde wieder nicht funktionieren und das Verhalten wäre wie am Anfang beschrieben.

**Comment by tyrant88** [comment]
Ob das Feld selbst versuchen sollte ein gültiges Datum zu speichern würde ich als separate Diskussion sehen.
