### ISSUE TITLE
Ergebnis editieren wirft Fehler wenn auf Date gefiltert

### ISSUE THREAD

**Issue by 191977** [yakamara/redaxo_yform#953]
Hi,

wenn auf ein Date-Feld gesucht wurde, entweder eindeutig oder auf Bereich, spuckt redaxo bei Klick auf "Datenergebnis editieren" den folgenden Fehler:

`Error while executing statement "SELECT `rex_activities`.* FROM `rex_activities` WHERE ( ( CAST(t0.`act_date` AS CHAR) = '2020-08-24' ) ) ORDER BY `act_date` DESC"! SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.act_date' in 'where clause'
#0 /var/www/vhosts/hosting.net/httpdocs/domain.de_2020/redaxo/src/core/lib/sql/sql.php(1166): rex_sql->setQuery('SELECT `rex_act...', Array)
#1 /var/www/vhosts/hosting.net/httpdocs/domain.de_2020/redaxo/src/addons/yform/plugins/manager/lib/yform/manager/dataset.php(194): rex_sql->getArray('SELECT `rex_act...', Array)
#2 /var/www/vhosts/hosting.net/httpdocs/domain.de_2020/redaxo/src/addons/yform/plugins/manager/lib/yform/manager/dataset.php(188): rex_yform_manager_dataset::queryCollection('SELECT `rex_act...', Array, 'rex_activities')
#3 /var/www/vhosts/hosting.net/httpdocs/domain.de_2020/redaxo/src/addons/yform/plugins/manager/lib/yform/manager/query.php(630): rex_yform_manager_dataset::queryCollection('SELECT `rex_act...', Array, 'rex_activities')
#4 /var/www/vhosts/hosting.net/httpdocs/domain.de_2020/redaxo/src/addons/yform/plugins/manager/lib/yform/manager.php(278): rex_yform_manager_query->find()
#5 /var/www/vhosts/hosting.net/httpdocs/domain.de_2020/redaxo/src/addons/yform/plugins/manager/pages/data_edit.php(20): rex_yform_manager->getDataPage()
#6 /var/www/vhosts/hosting.net/httpdocs/domain.de_2020/redaxo/src/core/lib/packages/package.php(250): include('/var/www/vhosts...')
#7 /var/www/vhosts/hosting.net/httpdocs/domain.de_2020/redaxo/src/core/lib/be/controller.php(476): rex_package->includeFile('pages/data_edit...', Array)
#8 /var/www/vhosts/hosting.net/httpdocs/domain.de_2020/redaxo/src/core/lib/util/timer.php(60): rex_be_controller::{closure}()
#9 /var/www/vhosts/hosting.net/httpdocs/domain.de_2020/redaxo/src/core/lib/be/controller.php(477): rex_timer::measure('Page: addons/yf...', Object(Closure))
#10 /var/www/vhosts/hosting.net/httpdocs/domain.de_2020/redaxo/src/core/lib/be/controller.php(432): rex_be_controller::includePath('/var/www/vhosts...', Array)
#11 /var/www/vhosts/hosting.net/httpdocs/domain.de_2020/redaxo/src/addons/yform/pages/index.php(6): rex_be_controller::includeCurrentPageSubPath()
#12 /var/www/vhosts/hosting.net/httpdocs/domain.de_2020/redaxo/src/core/lib/packages/package.php(250): include('/var/www/vhosts...')
#13 /var/www/vhosts/hosting.net/httpdocs/domain.de_2020/redaxo/src/core/lib/be/controller.php(476): rex_package->includeFile('pages/index.php', Array)
#14 /var/www/vhosts/hosting.net/httpdocs/domain.de_2020/redaxo/src/core/lib/util/timer.php(60): rex_be_controller::{closure}()
#15 /var/www/vhosts/hosting.net/httpdocs/domain.de_2020/redaxo/src/core/lib/be/controller.php(477): rex_timer::measure('Page: addons/yf...', Object(Closure))
#16 /var/www/vhosts/hosting.net/httpdocs/domain.de_2020/redaxo/src/core/lib/be/controller.php(415): rex_be_controller::includePath('/var/www/vhosts...')
#17 /var/www/vhosts/hosting.net/httpdocs/domain.de_2020/redaxo/src/core/backend.php(235): rex_be_controller::includeCurrentPage()
#18 /var/www/vhosts/hosting.net/httpdocs/domain.de_2020/redaxo/src/core/boot.php(137): require('/var/www/vhosts...')
#19 /var/www/vhosts/hosting.net/httpdocs/domain.de_2020/redaxo/index.php(9): require('/var/www/vhosts...')
#20 {main}`

**Comment by dergel** [comment]
Der Fehler scheint ja folgendes zu sein: Unknown column 't0.act_date'
Existiert das Feld in der Datenbank ? Wie sind die Einstellungen zu diesem Feld ?

**Comment by 191977** [comment]
Hey Jan,
act_date besteht, t0.act_date nicht. t0 scheint ein Index für das erste, von-Datum von den zwei möglichen in der Spanne zu sein? Einstellungen sind die Defaults für das date-field mit deutschem Anzeigeformat
![Screenshot_20201023-081829](https://user-images.githubusercontent.com/47699885/96963168-77dfa800-1508-11eb-90c9-9f4b2d4880d4.jpg)
![Screenshot_20201023-081815](https://user-images.githubusercontent.com/47699885/96963186-8037e300-1508-11eb-8eb3-c217fcded237.jpg)

**Comment by 191977** [comment]
![Screenshot_20201023-082144](https://user-images.githubusercontent.com/47699885/96963448-f3415980-1508-11eb-8d99-10b521ff0abd.jpg)
