### ISSUE TITLE
Fehler "Length Required" bei Reload eines Formulars

### ISSUE THREAD

**Issue by TobiasKrais** [yakamara/redaxo_yform#957]
Wenn die Option `$yform->setObjectparams("form_showformafterupdate", true);` aktiviert ist, ein Formular abgesandt ist und die Webseite dann z.B. mit Strg+R neu geladen wird erscheint der Fehler: "Length Required A request of the requested method POST requires a valid Content-length." Mehr als die Meldung wird nicht ausgegeben.
![Bildschirmfoto von 2020-10-28 13-37-37](https://user-images.githubusercontent.com/4131072/97472074-b67ec380-1949-11eb-83f4-79dec8fcb2e3.png)

**Comment by dergel** [comment]
noch nie gehört .. Passiert das bei jedem Formular und ist es wirklich nur bei `form_showformafterupdate` .. Kannst du mir das PHP vereinfacht hier reinlegen, damit ich den Fehler nachbauen kann

**Comment by TobiasKrais** [comment]
Den Fehler konnte ich nur bei `form_showformafterupdate` nachvollziehen. Hier ein Beispielmodul:
https://github.com/TobiasKrais/d2u_helper/blob/master/modules/14/1/output.php

Input und die anderen Dateien findest du hier: https://github.com/TobiasKrais/d2u_helper/tree/master/modules/14/1

Hilft dir das weiter? Gerne stehe ich dir zur Verfügung.

**Comment by dergel** [comment]
@TobiasKrais Sorry, dass ich mich erst jetzt melde. Kannst du mir den Fall runter brechen auf das Allernötigste ? Das wäre super.

**Comment by TobiasKrais** [comment]
Ich glaube der Fehler hat sich erledigt. Durch irgend eines der Updates in den letzten Monaten wurde der Fehler behoben.
