### ISSUE TITLE
choice multiple checkbocken

### ISSUE THREAD

**Issue by skerbis** [yakamara/redaxo_yform#968]
Um die checkbox-Liste herum wäre ein Wrapper sinnvoll. Damit man die höhe evtl. begrenzen kann und die Liste scrollbar bekommt.

**Comment by tbaddade** [comment]
> Um die checkbox-Liste herum wäre ein Wrapper sinnvoll.

Ist bereits.
https://github.com/yakamara/redaxo_yform/blob/master/ytemplates/bootstrap/value.choice.check.tpl.php#L74

Weiteres HTML sollte m.E. über ein eigenes YTemplate beeinflusst werden.

**Comment by skerbis** [comment]
Hmm ... das Label steckt aber drin ...
