### ISSUE TITLE
Doku kaputt? Einige Dateien scheinen zu fehlen.

### ISSUE THREAD

**Issue by georgkaser** [yakamara/redaxo_yform#969]
Wenn ich in der Doku auf diverse Links klicke (Value-Felder, Validate-Felder, Action-Felder, Objparams) erscheint eine 404 Seite. Diese Dateien scheinen zu fehlen. Kann da mal jemand nachsehen was da los ist?

**Comment by alxndr-w** [comment]
Das ist vermutlich meine Schuld. Die Links von GitHub und einer installierten Doku passen nicht zusammen. Am besten sollte man die Links vorübergehend entfernen.

**Comment by georgkaser** [comment]
Aber wenn du die Links vorübergehend entfernst, wo findet man dann die Dokumentation z.B. zu den Values?

**Comment by georgkaser** [comment]
Ah, ich seh grad - wenn man scrollt kommt man dahin.

**Comment by alxndr-w** [comment]
Falls du eine Idee hast, wie sich das auf Github und in YForm gleichermaßen lösen lässt, gerne einbauen.

**Comment by christophboecker** [comment]
Man muss die GitHUB-Links auf Elemente innerrhalb von addon/docs in der REX-Instanz so umbiegen, dass sie wieder funktionieren. Wird in focuspoint V3 irgendwann öffentlich, derzeit nur in meiner Dev-Branch. Der naheliegendste Schlüssel zur Lösung heißt help.php. Imho.
![](https://raw.githubusercontent.com/christophboecker/help.php/master/docs/readme.jpg)

**Comment by alxndr-w** [comment]
Gerade von der help.php wollten wir ja weg zum direkten rendern der .md-Datei

**Comment by christophboecker** [comment]
Solange die Doku aus einer einzelnen Datei oder aus mehreren Dateien ohne Querverlinkung besteht, klappt das. markdown::parseWithToc macht einen prima Job. Ich nutze es ja auch. 

Sobald Du mehr als eine Datei hast und dazwischen Verlinkungen, musst Du an die Links ran. Den Github-tauglichen Link bekommst Du unter R nicht an´s Laufen außer er wird so umgebaut, dass er ein valider Backend-Link wird. Ich sehe nicht, dass es anders lösbar ist.

Aber ich will hier keinen Glaubensstreit aufmachen. Nur mein Hinweis für komplexere Dokus: ohne Links von der "Github-tauglichen Version" in eine Backend-Url umzubauen. klappt das mit direktem Rendern nicht. Ob das in einer help.php (einfachste Lösung, imho) passiert oder in die Markdown-Klasse eingebaut wird oder sonstwie gelöst, ist eine andere Fragestellung.

**Comment by staabm** [comment]
bin ich heute auch drüber gestolpert.

![grafik](https://user-images.githubusercontent.com/120441/103299585-2ddddb80-49fd-11eb-9085-0fe4cf859903.png)

nahezu kein link auf der intro seite funktioniert. fast alle zeigen auf 4040

**Comment by christophboecker** [comment]
Jaaa, das liegt wohl an dem experimentellen Versuch, die Doku rein über die package.yml mit md-Dateien als Doku-Seite abzubilden. Das klappt so nicht; siehe Diskussionsteil zwischen Alex und mir. 

Workaround war mal das Doku-Plugin zu aktivieren; aber das ist wohl letztens rausgeflogen.

**Comment by alxndr-w** [comment]
Man sollte das direkt in REDAXO verbessern, statt dass alle Dokus solche Probleme einzeln für sich lösen.

**Comment by dergel** [comment]
Ich war ein bischen zu schnell bei der Übernahme der Änderungen und hatte zu wenig bis gar nicht geprüft. Sorry. Aber der Weg ist der Richtige.. Habe ein paar interne LInks verbessert - erstmal nur so, dass sie im AddOn funktionierten, was meines Erachtens wichtiger ist. In redaxo https://github.com/redaxo/redaxo/issues/4508 habe ich ein issue aufgemacht und ich hoffe, dass wir einiges dort optimieren könnnen.

Die Beispiel .json Importdateien funktionieren noch nciht als Download. Da würde ich mir gerne was allgemein sinnvolles überlegen. Eigentlich ist das einbinden von einzelnen Dateien in der package.yml nicht sinnvoll.
