### ISSUE TITLE
E-Mail Validierung anpassen ? Nach RFC rfc822 z.B.

### ISSUE THREAD

**Issue by dergel** [yakamara/redaxo_yform#97]
bei beiden benutzen wir einen regex:
"#^[\w.+-]{2,}\@\w[\w.-]*.\w+$#u";

aber.. ich hätte nichts gegen eine konforme Lösung z.B.

https://github.com/iamcal/rfc822/blob/master/rfc822.php
https://gist.github.com/sepehr/3340008

alexplusde: Die höchstmögliche Konsistenz wäre doch sicher, die Validierung analog zur Client-Validierung (<input type="email" />) zu haben. Sonst hat man so Effekte, dass eine clientseitige Validierung fehlschlägt, die in Redaxo erlaubt ist und vice versa.

**Comment by alexplusde** [comment]
[...]zur Client-Validierung (`<input type="email" />`) zu haben. [...]

**Comment by dergel** [comment]
https://html.spec.whatwg.org/multipage/forms.html#valid-e-mail-address

**Comment by alexplusde** [comment]
Querverlinkung:
https://github.com/yakamara/redaxo_yform_docs/issues/11
