### ISSUE TITLE
Table Manager - Feld Choice: dynamische Werte ermöglichen

### ISSUE THREAD

**Issue by DanielWeitenauer** [yakamara/redaxo_yform#970]
Es wäre praktisch, wenn die Auswahlmöglichkeiten des Choice-Feldes dynamisch über eine Funktion bestückt werden könnten. 
Damit würde das Anbinden externer APIs erleichtert.

**Comment by christophboecker** [comment]
Es geht aber nur um die per Table-manager interaktiv gebauten, Formulare, oder? PHP/PIPE ist ja eher easy. ich löse so was per dataset-Klasse. getForm() überschreiben:
```
class my_xyz_yform_table extends \rex_yform_manager_dataset
{
    public function getForm( )
    {
        $yform = parent::getForm();
        foreach( $yform->objparams['form_elements'] as $k=>&$fe ){
            if( $fe[0] == 'action' ) continue;
            if( $fe[0] == 'validate' ) continue:
            if( 'choicefeldname' == $fe[1] ){
                $fe[3] = ... die neue Auswahl ...;
                ...
                continue;
            }
        }
        return $yform;
    }
}
```
Ob es eleganter geht weiß ich nicht, klappt aber ziemlich universell. Z.B. IntegerFromTo-Validates dynamisch mit den aktuellen Grenzwerten bestücken.

**Comment by DanielWeitenauer** [comment]
Ja, es geht um den Table Manager. PHP und Pipe kann man ja beliebig manipulieren. Beim Table Manager kann man zwar auch mit einer Relationstabelle hantieren, die man dynamisch bestückt oder ein eigenes Feld bauen, aber da das Choice-Feld bereits fast alle denkbaren Varianten abdeckt, wäre es nett, wenn es diese Möglichkeit auch gäbe.

**Comment by christophboecker** [comment]
Dann wäre mein Vorschlag tatsächlich der eigene Dataset. Damit kann man  ja noch viel mehr tricksen. Beispiel, allerdings nicht für Choice, aber als Inspiration hier: https://github.com/christophboecker/geolocation/blob/master/lib/yform/dataset/geolocation_layer.php. Musst halt im Choice-Value nachschauen, welcher Index welchem Feld entspricht. Im Beispiel ist kein Choice, aber ein be_table (lang).

**Comment by tbaddade** [comment]
> Es wäre praktisch, wenn die Auswahlmöglichkeiten des Choice-Feldes dynamisch über eine Funktion bestückt werden könnten.
> Damit würde das Anbinden externer APIs erleichtert.

Würdest du nicht externe Daten erst einmal normalisieren bzw. überprüfen wollen? 
Was würde auch passieren, wenn die API einmal eine Option nicht mehr liefert, jedoch bei deinen Datensätze immer noch verwendet wird? 
Ich würde hier auch eher eine Zwischentabelle verwenden und dann via SELECT die Choices holen.

**Comment by DanielWeitenauer** [comment]
> Würdest du nicht externe Daten erst einmal normalisieren bzw. überprüfen wollen?
Dafür hätte ich ja gerne die Möglichkeit, die Choices über eine Callback-Funktion zu bestücken.

> Was würde auch passieren, wenn die API einmal eine Option nicht mehr liefert, jedoch bei deinen Datensätze immer noch verwendet wird?
Das wäre dann eben Aufgabe der Callback-Funktion und Ausgabe. 

> Ich würde hier auch eher eine Zwischentabelle verwenden und dann via SELECT die Choices holen.
Das ist explizit nicht gewünscht, da die API-Daten quasi sekundenaktuell sein müssen. Wird ein Datensatz in der API deaktiviert, soll das direkt in REDAXO abrufbar sein.

Bisher habe ich mir, wie geschrieben mit eigenen Feldern beholfen, allerdings wäre es im Hinblick auf Updatesicherheit praktischer, wenn es eine allgemeingültige Möglichkeit gäbe.

**Comment by alxndr-w** [comment]
@DanielWeitenauer du holst dir die Daten per API und willst sie direkt ausgeben - was im Table Manager dir nicht möglich ist, weil du hier kein Array übergeben konntest, sondern nur SQL oder statische Werte. Verstehe ich das richtig?

Du wünschst dir, dass hier als weiterer Punkt "callback" hinzukommt, mit dem du eine Methode angibst, die ein Array, JSON-Objekt o.ä. als return-Wert liefert?

![image](https://user-images.githubusercontent.com/3855487/120219513-a3173c00-c23b-11eb-826a-c57f88ce9bc7.png)

Das sollte nicht schwer sein, wenn gewünscht.

**Comment by DanielWeitenauer** [comment]
@alxndr-w Es scheint tatsächlich recht einfach zu sein. Ich glaube @dtpop hat das Problem hier gelöst: https://github.com/yakamara/redaxo_yform/pull/988

**Comment by dergel** [comment]
dann das hier schliessen ?
