### ISSUE TITLE
Upload Feld: Speichern in der Datenbank funktioniert nicht

### ISSUE THREAD

**Issue by georgkaser** [yakamara/redaxo_yform#971]
Ich komm hier nicht weiter - immer der gleiche Fehler: Wenn ich ein Upload Feld in PHP Notation anlege und den Wert in der Datenbank speichern möchte, wirft es folgenden Fehler:
`InvalidArgumentException | $id has to be an integer greater than 0, but "-1" given | redaxo/src/addons/yform/plugins/manager/lib/yform/manager/dataset.php | 87`
Das Feld hab ich jetzt auch schon mit dem Tabellen Manager angelegt und von dort den Code genommen - keine Veränderung:
`$yform->setValueField('upload', ['dokumente', 'Dokumente', '10000', '.pdf,.odt,.doc,.docx', '1', 'min_err,max_err,type_err,empty_err,delete_file_msg']);`

Übrigens: Versenden per Email funktioniert. 

yform 3.4.1

**Comment by alxndr-w** [comment]
Wie speicherst du den Wert in der DB?

**Comment by georgkaser** [comment]
So:
`$yform->setActionField('db', ['rex_tabellenname']);`

**Comment by alxndr-w** [comment]
Das ganze Upload-Feld funktioniert etwas anderes, als du vllt annimmst und Fehler auf dem Dateisystem beim Kopieren werden U.U. unterdrückt.

Es scheint aber schon vorher einen Fehler zu geben, denn es wird ja noch nicht Mal der Datensatz angelegt, in das das Upload-Feld schreiben soll. Wie sieht denn das ganze Formular dazu aus?

**Comment by georgkaser** [comment]
Glaubst du? Naja, ich hab schon einige Formulare vorher mit Upload Feldern gebaut - da hat es eigentlich immer gut funktioniert. 

Das Formular ist zu lange, das werde ich hier nicht posten. Aber ich beschreibe es mal: Es ist ein Bewerberformular wo der Bewerber seine Dokumente mitschicken kann/soll. Zusätzlich soll der Dateiname noch in der Datenbank gespeichert werden - muss aber nicht. Es würde auch langen, wenn die Datei nur als Anhang mitgeschickt wird und die restlichen Daten (Name, Adresse usw.) in der Tabelle gespeichert würden (Ausgabe im Tabellenmanager von mir aus auch einfach als Textfeld).

Soviel ich aus der Doku entnehmen kann gibt es beim Upload Feld keinen no_db Parameter, oder?

Ich gehe genau nach diesem Beispiel vor: [https://github.com/yakamara/redaxo_yform_docs/blob/master/de_de/demo_email-attachments.md](https://github.com/yakamara/redaxo_yform_docs/blob/master/de_de/demo_email-attachments.md)

**Comment by georgkaser** [comment]
Okay, ich hab den Fehler gefunden. Du hattest recht, der Fehler war ein kleiner Schreibfehler bei einem Feld vorher (hatte beim Feldnamen einen Schreibfehler). Trotzdem komische Fehlermeldung. Ich bin lediglich deshalb draufgekommen, weil ich im Addon selbst einiges auskommentiert und via dump() ausgegeben hab.
Ich schließe das mal.

**Comment by voteros** [comment]
Was ich in der Vergangenheit öfter hatte, war die Tatsache, dass mein per YForm definierter Submit-Button keinen no_db Parameter hatte. Dadurch wurde versucht, den Submit-Button in der Datenbank zu speichern. 
Vielleicht kann ich jemand anderem damit helfen, der diesen Post per Google findet. ;)
`$yform->setValueField('submit', ['submit','Kommentar absenden', '', '', 'no_db', '', 'btn-primary']);`
