### ISSUE TITLE
Tabellenschema gelöscht, Prio der restlichen Tabellen passt sich nicht an

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#973]
Auf dieser Seite hier
`/redaxo/index.php?page=yform/manager/table_edit`

**Comment by alxndr-w** [comment]
Auch bei Tableset-Importen ist das meines Wissens noch so, dass hier dann die Prios doppelt vergeben wurden. Wenns gefixt wird, dann an der Stelle gleich mit prüfen.

**Comment by dergel** [comment]
Table export ist mittlerweile ohne id und prio und demnach reiht es sich immer hinten dran. Diese Problem hier finde ich im Moment nicht relevant. Wenn irgendwann mal alles umgebaut wird, kommt das hier dazu.
