### ISSUE TITLE
Tableset Export: Namen anzeigen

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/redaxo_yform#977]
Es werden komischerweise "User" und "Group" angezeigt, aber sonst keine Namen

![image](https://user-images.githubusercontent.com/3855487/102013569-5f924980-3d51-11eb-846f-70e642cb7998.png)

**Comment by christophboecker** [comment]
Special Feature, würde ich mal sagen: Wenn Du in einer Lang-Datei stehen hast 
```
rex_geolocation_layer = Karten-Layer
```
ergibt das in der Liste
<img width="325" alt="grafik" src="https://user-images.githubusercontent.com/10065904/108694070-de002a00-74fe-11eb-96d9-eeb3ab797536.png">

Allerdings wäre es m.E. auch sinnvoller, wie in der Tabellenliste zu verfahren und bevorzugt die "Bezeichnung" heranzuziehen.

**Comment by alxndr-w** [comment]
Ah. Damit kann ich bei Addons leben.

**Comment by christophboecker** [comment]
Ist trotzdem uneinheitlich. Hab nen PR eingestellt #1002
