### ISSUE TITLE
Problem mit upload-Feld und übernehmen

### ISSUE THREAD

**Issue by thorol** [yakamara/redaxo_yform#978]
yform 3.4.1, Redaxo 5.11.0
Bei einem Upload-Feld im Backend im Tabellen-Manager geht der Wert eines upload-Feldes bei Klick auf übernehmen verloren. Dies wird erst nach einem weiteren Klick auf übernehmen sichtbar. Sprich klickt man 2x auf übernehmen, so ist auf jeden Fall der Dateiname weg und auch in der Datenbank ist der Wert leer.

Mit der upload.php aus yform 3.3, funktioniert alles korrekt. Es scheint, als läge es am Session Handling. Hatte sich bzgl. des Session Handlings nicht auch was im Core geändert? Wahrscheinlich hatte es damals bei der Prüfung funktioniert.

**Comment by dergel** [comment]
Kann ich leider nicht nachvollziehen. Habe es aber mit der aktuellsten REDAXO 5.12 getestet. D.h. wenn es an der Version gelegen habe sollte, passt es in der neuen Version

**Comment by bitshiftersgmbh** [comment]
Hab hier alles aktuell Stand heute und das selbe Problem. (nur zur Info)

**Comment by bitshiftersgmbh** [comment]
@dergel : _Hinweis von Oliver M. aus Slack:_

Da gibt es 2 Stellen, an denen man eingreifen muss.
Im Formular selbst muss, wenn es eine ID-Nummer gibt, diese mitgeteilt werden. Ansonsten hat das Formular die nicht und macht beim Absenden Mist. Sprich: Er findet die hochgeladene Datei nicht, nimmt an die ist gelöscht und entfernt den Eintrag im Datensatz.
```
if($id)
{
    $yform->setObjectparams('getdata', 1);
    $yform->setObjectparams('main_where', "id=$id");
    $yform->setObjectparams('main_id', $id);
}
```
Außerdem hat das ytemplate für bootstrap (classic benutze ich nicht, ist aber genau so buggy) einen groben Fehler drin. Aktuell steht in Zeile 31
```
$value = $this->getValue();
```

Viel besser funktioniert aber:
```
$filename = $this->getValue();
```

**Comment by dergel** [comment]
Danke für den Hinweis. Das erste würdest du wo einbinden ? und $value vs $filename.. diese Zeile ist grundsätzlich überflüssig und habe ich bereits entfernt.

**Comment by dergel** [comment]
Können das Andere bestätigen bei der jetzigen Version?

**Comment by marcohanke** [comment]
Gerade mit Redaxo und Yform aus github getestet. Dateiupload im Backend bleibt erhalten, egal wie oft man auf speichern oder auf übernehmen klickt.

**Comment by dergel** [comment]
Ich schliesse das Issue weil ich es nicht nachvollziehen kann. Gerne wieder öffnen bei Bedarf.

**Comment by marcohanke** [comment]
Ich hatte das Problem mit einer älteren Version auch. Aber wie beschrieben, jetzt isses wech, alles läuft
