### ISSUE TITLE
Ausgabe CSS und JavaScript im Backend optimieren

### ISSUE THREAD

**Issue by aeberhard** [yakamara/redaxo_yform#979]
Im Backend wird auf allen Seiten CSS+JavaScript für YForm geladen.
Sollte nur bei den notwendigen Seiten geladen werden!

**Comment by christophboecker** [comment]
Woran würdest Du das festmachen? Woren kann man erkennen dass das YForm CSS/JS benötigt wird?

**Comment by aeberhard** [comment]
z.B. an vorhandenen CSS-Klassen der Backend-Seite.
Codemirror wird z.B. nur geladen wenn auch eine CSS-Klasse für den Codemirror vorhanden ist.

**Comment by aeberhard** [comment]
Ok, beim Codemirror sieht man das nicht so offensichtlich im Quellcode da hier CSS/JavaScript per Script nachgeladen werden.

**Comment by alxndr-w** [comment]
Im Hinterkopf behalten: YForm-Tabellen werden ja auch nicht nur auf YForm-Seiten dargestellt, z.B. YCom und jedes X-beliebige Addon.

**Comment by alxndr-w** [comment]
Noch dazu sehe ich gar kein Problem darin, wenn das nach Login geladen wird und bereits verfügbar ist, wenn man auf die passende Seite wechselt. Andere nennen das Caching.

**Comment by dergel** [comment]
ich denke auch .. das wird zu oft auf verschiedenen Seiten verwendet + wenn einmal geladen, dass ist ja auch bereits alles gut,
