### ISSUE TITLE
Table Manager: emptyname führt zu Fehler

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#98]
Habe gerade aus Testgründen eine YForm-Tabelle nur mit einem Feld "emptyname" angelegt. Beim Erstellen des Datensatzes kommt:

`Warning: no values given to buildPreparedValues for update(), insert() or replace() in /kunden/322541_70190/alexplus.de/rex5/redaxo/src/core/lib/sql/sql.php on line 681
Error while executing statement "INSERT INTO `rex_test` SET ! SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1`

Hab jetzt nicht genauer nachgeforscht, ob es an emptyname direkt liegt oder an der Tatsache, dass es das einzige Feld ist.

**Comment by dergel** [comment]
das liegt daran, dass es das einzige feld ist und in dieser form keinen sinn ergibt
