### ISSUE TITLE
notice für text/textarea/select unterstützen, analog rex_form

### ISSUE THREAD

**Issue by staabm** [yakamara/redaxo_yform#983]
ich würde auch gerne in yform formularen solche notices an die eingabefelder packen:

![grafik](https://user-images.githubusercontent.com/120441/103301170-0c7eee80-4a01-11eb-93a3-02258178ac5b.png)

**Comment by staabm** [comment]
im bootstrap template scheint das fast überall zu gehen

![grafik](https://user-images.githubusercontent.com/120441/103301387-9a5ad980-4a01-11eb-9397-724b590e5082.png)

im classic template nur sehr eingeschränkt

![grafik](https://user-images.githubusercontent.com/120441/103301407-ac3c7c80-4a01-11eb-8009-f45c56a85da4.png)

**Comment by alxndr-w** [comment]
Weshalb nutzt du das Classic-Template?

**Comment by staabm** [comment]
Wir verwenden kein bootstrap, daher dachte ich classic wäre sinnvoll

**Comment by alxndr-w** [comment]
Laut @dergel dient Classic nur noch dem legacy-Modus, also für migrierte R4-Websites und soll irgendwann entfernt werden.

Ich fände es jedoch gut, wenn es auch ein simples minimales Template für YForm oder so gibt, das nicht auf bootstrap gemünzt ist.

Du könntest das, wenn @dergel einverstanden ist, auf Basis von bootstrap und Classic entwickeln.

Bitte korrigiert mich, falls ich das falsch in Erinnerung habe.

**Comment by dergel** [comment]
Das issue schliesse ich mal .. notices sind möglich, nur die class templates sind schrott und müssten raus. Ich warte auf twig im redaxo core :) ..
