### ISSUE TITLE
Fehlermeldung unspezifisch

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform#987]
**Frontend - Newsletteranmeldung**

Ich hatte im Formular ein Value, welches jedoch noch nicht als Feld in der yform-Tabelle existierte.

Speichert man dieses Formular jetzt, erhält man diese [Exception](https://github.com/yakamara/redaxo_yform/blob/4407527793c8c668bca175eddb47e647ea4e73b6/plugins/manager/lib/yform/manager/dataset.php#L87). 
Die Id war hier `-1`. 
Angestoßen wurde dies [hier](https://github.com/yakamara/redaxo_yform/blob/4407527793c8c668bca175eddb47e647ea4e73b6/plugins/manager/boot.php#L86). 

An dieser Stelle hätte ich mir eine Exception wie `Feld für value xyz existiert nicht` gewünscht. Das würde das Suchen erheblich erleichtern :)

**Comment by dergel** [comment]
das ist bereits verbessert. REX_YFORM_SAVED darf nicht ausgeführt werden, wenn kein Datensatz vorhanden ist oder angelegt wurde.

https://github.com/yakamara/redaxo_yform/blob/master/lib/yform/action/db.php#L82
