### ISSUE TITLE
Feature :: Datenergebnis als CSV exportieren nach aktueller Sortierung

### ISSUE THREAD

**Issue by skerbis** [yakamara/redaxo_yform#989]
Aktuell wird das CSV nach der festgelegten Sortierung im Tablemanager exportiert. 
Für eine Bearbeitung am lokalen Rechner wäre es denke ich sinnvoller den Export sortiert nach Id anzubieten. 

Eine Möglichkeit wäre dies bei den Tabellen einstellen zu können.

**Comment by alxndr-w** [comment]
Das sind 15 Sekunden in Excel und Co. Gerade dass die Sortierreihenfolge aber durch YForm festgelegt ist, fand ich schon ziemlich gut, wenn ich Daten an Kunden aushändigen konnte, die bspw. nach Status, Alphabetisch oder Prio sortiert wurden.

**Comment by skerbis** [comment]
Wenn die Daten bearbeitet und ergänzt werden sollen macht es Sinn diese exakt in der Reihenfolge der Datenbank nach id zu liefern. Gerade wenn beim Import später auch die ID der Datensätze beachtet werden müssen.

**Comment by alxndr-w** [comment]
Gilt für mich, wie für dich - aber in der Hoffnung, dass es eine Hilfe ist.

1. Ctrl+A für "alles markieren"
2. Als Tabelle formatieren und
3. Optik bestätigen
4. Sortieren

![image](https://user-images.githubusercontent.com/3855487/105112099-9252fe80-5ac2-11eb-9550-04da86875acf.png)

Ansonsten gibt's noch den Adminer, der kann dir direkt und nach id sortiert exportieren. 

Vlt. kannst du mehr über dein Szenario schreiben, wann das Sinn ergibt.

Ich meine auch, neue Datensätze kann man erzeugen, indem man die id freilässt. Ansonsten kümmert's den Import wenig, der funktioniert auch mit ids, die durcheinander sind.

**Comment by skerbis** [comment]
Szenario: Kund*in will Daten zur Korrektur und Ergänzung auslesen und bearbeiten/ergänzen.  Hierzu sollte Kund*in die Daten entsprechend der Id sortiert erhalten und nicht nach der Darstellung im Backend. Kund*in soll auf den ersten Blick erkennen welche id nicht vergeben ist. Neue Daten sollen immer am Ende der Tabelle hinzugefügt werden. Ich möchte dass die für jede Tabelle gilt. Damit Kund*in immer das gleiche Format erhält

**Comment by alxndr-w** [comment]
Tut mir leid, ich verstehe immer noch nicht, wann man wissen will, welche id nicht vergeben ist. ids nehmen doch keinen Platz weg. Neue Daten können am Ende der Tabelle hinzugefügt werden, egal, wie die Sortierreihenfolge ist. 

Ich weiß nicht, ob wir aneinander vorbei reden, oder ob da falsche Annahmen von einem von uns bestehen.

**Comment by skerbis** [comment]
Ich möchte nicht bei jeder exportierten Tabelle der Kundin erklären warum die Sortierung bei dem Export nach Name und bei dem nächsten Export nach id oder Ort ist. Ich möchte einheitlich exportiere Tabellen der Kundin zur Verfügung stellen, exakt entsprechend der Reihenfolge wie gewünscht - hier ID.

**Comment by alxndr-w** [comment]
Hab ich jetzt erstmal verstanden.

Vorher: Ich wähle mir die Sortierreihenfolge, die ich benötige, und exportiere diese, z.B. ID, Name, Beschreibung
Nachher: Ich kann nur nach ID exportieren

Wenn du sie zur Verfügung stellst, müsstest du nur einen Klick extra machen.

![image](https://user-images.githubusercontent.com/3855487/105377865-89217900-5c0b-11eb-8db5-ea7ce5204503.png)

**Comment by skerbis** [comment]
Äh nein, es wird immer die Sortierung übernommen die in den Tabelleneinstellungen eingestellt sind. Das ist ja mein Problem. 
Diese kann und darf ich nicht ändern, da Yorm diese benötigt.

**Comment by tbaddade** [comment]
Die Sortierung beim Export finde ich derzeit ok wie sie ist. Und hat der Kunde Sonderwünsche, kann ich via ExtensionPoint den Export beeinflussen.

**Comment by alxndr-w** [comment]
> Äh nein, es wird immer die Sortierung übernommen die in den Tabelleneinstellungen eingestellt sind

Du hast recht. 

Wäre es denn nicht sinnvoller, das Datenergebnis so zu exportieren, wie man die Sortierung im Tabellenkopf festlegt?
