### ISSUE TITLE
Feature :: Backup anlegen bei CSV Export

### ISSUE THREAD

**Issue by skerbis** [yakamara/redaxo_yform#990]
Vielleicht über einen EP anbieten? 
Oder ist es evtl. schon möglich?

**Comment by alxndr-w** [comment]
Oder eher dem Import?

**Comment by skerbis** [comment]
oder so

**Comment by dergel** [comment]
Verstehe ich nicht ..  Man kann vor dem Import und dem Export einen EP nutzen .. 

YFORM_DATA_TABLE_EXPORT
YFORM_DATASET_IMPORT

**Comment by skerbis** [comment]
Jan du hast Recht. Vielleicht doch besser als Trick vorstellen?

**Comment by dergel** [comment]
Dann schliesse ich mal .. Tricks sind ja woanders :)
