### ISSUE TITLE
Tableset-Export mit Karteileichen -> entschlacken

### ISSUE THREAD

**Issue by christophboecker** [yakamara/redaxo_yform#991]
Wenn im Table-Manager ein Export erfolgt, wird zu jedem Feld-Eintrag aus `rex_yform_field` der komplette Datensatz exportiert. tatsächlich sind das dann auch jede Menge Spalten, die eigentlich zu anderen Feldtypen gehören. Das hat die Konsequenz, dass beim Import gerne Spalten in `rex_yform_field` angelegt werden, die überflüssig sind oder längst veraltet, und macht den ohnehin langsamen Import noch langsamer. 

Heute hatte z.B. @skerbis das Problem im Slack-Channel angesprochen.

Hier mal im Beispiel 18 Felder im Export; jeweils alle 99 Spalten der Tabelle:
<img width="288" alt="grafik" src="https://user-images.githubusercontent.com/10065904/105389587-47e39600-5c18-11eb-96a6-1ac22ae0fcf2.png">

Meine Vermutung ist, dass tatsächlich nur die Basisfelder der `rex_yform_field` (wie im Install angelegt) sowie die feldbezogenen Spalten aus `$field->definitions["values"]` relevant sind. Darauf könnte man den Export beschränken:
```php
class rex_yform_manager_field implements ArrayAccess
{

   ....

   public function toArray()
    {
        $keys = array_unique(
            array_merge(
                ['table_name','prio','type_id','type_name','db_type','list_hidden','search','name','label','not_required'],
                array_keys( $this->definitions['values'] ?: [] )
            )
        );
        $values = array_intersect_key($this->values, array_flip($keys));
        return $values;
    }
 ```

Das Ergebnis wäre im Beispiel sowas, also deutlich entschlackt:
<img width="505" alt="grafik" src="https://user-images.githubusercontent.com/10065904/105390392-4797ca80-5c19-11eb-8ffd-61089dd47c08.png">

Wäre das tatsächlich so gangbar und vollständig?

**Comment by skerbis** [comment]
+1 Danke für die Analyse. 
Das wäre eine tolle Lösung

**Comment by christophboecker** [comment]
Vieleicht sollte man dann die Felder aus `rex_yform_table` auch etwas kürzen: ` id` und `prio` raus. `id` wird eh neu vergeben und prio kollidiert im Zweifel mit vorhandenen Tabellen. Lieber automatisch vergeben, sprich hinten anhängen.

```php
class rex_yform_manager_table implements ArrayAccess
{

    ....

    public function toArray()
    {
        return array_diff_key($this->values, ['id'=>0,'prio'=>0]);
    }
 ```

Alternativ `toArray()` weiterhin alles liefern lassen (was ja auch in einem anderen Kontext als Export sinnvoll sein kann) und statt dessen die Export-Routine ändern:

```php
class rex_yform_manager_table_api{

    ....

    public static function exportTablesets($table_names)
    {
        $export = [];
        foreach ($table_names as $table_name) {
            $export_table = rex_yform_manager_table::get($table_name);
            $export_fields = [];
            foreach ($export_table->getFields() as $field) {
                $export_fields[] = $field->toArray();
            }
            $export[$export_table['table_name']] = [
                'table' => array_diff_key($export_table->toArray(), ['id'=>0,'prio'=>0]),
                'fields' => $export_fields,
            ];
        }

        return json_encode($export);
    }
 ```

**Comment by dergel** [comment]
GUte Hinweise und gute Lösung. Habe ich geprüft und übernommen.

https://github.com/yakamara/redaxo_yform/commit/1949cccea1814eca63786d86a5a0b840b6fb2390

Danke.
