### ISSUE TITLE
createdb ist deprecated() - neue Action auf Basis von rex_sql ensure() o.ä.?

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/redaxo_yform#993]
https://github.com/yakamara/redaxo_yform/blob/cdb1b22473d94bcf93ebb4100b02ffd4f083437f/lib/yform/action/createdb.php#L45-L49

Ich schätze, aus Performance-Gründen sollte man die Action nie live verwenden - was spräche dagegen, dennoch aus einem YForm-Formular eine Tabelle on the fly zu generieren mit richtigen Felddefinitionen?

**Comment by dergel** [comment]
Ich habe die createdb noch in 4.0 gelassen, weil es doch oft geholfen hat und es noch keine gute Alternative gibt. Den Weg noch zusätzlich über ein YForm Formular eine Tabelle zu generieren sehe ich mittel- und kurzfristig nicht. Deswegen archiviere ich das issue erst mal
