### ISSUE TITLE
PHP 8.0

### ISSUE THREAD

**Issue by kobebeef** [yakamara/redaxo_yform#994]
Wenn Redaxo auf PHP >= 8.0 läuft, lässt sich yform und auch der Redaxo Core nicht aktualisieren.
Das hat wohl mit yform/package.yml zu tun

requires:
    php:
        version: '^7.0'

Bei «quicknavigation» sieht das Pendant wie folgt aus:

requires:
   php:
        version: '>=7, <9'

Ob es noch etwas mehr braucht, weiss ich nicht...

**Comment by alxndr-w** [comment]
Wenn du die package.yml editierst und das Update damit erlaubst (bitte nicht in einem Live-Projekt), funktioniert denn dann alles? (Table Manager, Formulare, E-Mail-Versand, YOrm, etc.?)

Denn falls nicht, wäre das ja eine durchaus zulässige Restriktion.

**Comment by kobebeef** [comment]
Ich konnte es noch nicht durchtesten. Ich hatte aber bei einem Projekt wo ich yform hauptsächlich für yrewrite benötige zuerst yform und yrewrite aktualisiert und danach auf PHP 8.0 umgestellt. Und dort funktioniert es (ohne aber Formulare, Mail-Versand zu testen).

**Comment by skerbis** [comment]
Funktioniert soweit alles unter PHP 8 @dergel
