### ISSUE TITLE
Tabellen aktualisieren -> be_manager_relation-Felder werden nicht neu angelegt

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/redaxo_yform#996]
Aus unerklärlichen Gründen gab es ein be_manager_relation-Feld nicht mehr in der MySQL-Datenbanktabelle. Die Aktion "aktualisieren" und "(mit Feldlöschung") haben dieses Feld jedoch nicht wiederhergestellt. Es hätte so sein müssen, dass diese Datenbankfelder wieder angelegt werden.

**Comment by dergel** [comment]
Konnte ich leider nicht nachvollziehen. Kannst du mir ein Testbeispiel aufbauen? Bis dahin schliesse ich
