### ISSUE TITLE
Datensatzname statt id

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/redaxo_yform#999]
https://github.com/yakamara/redaxo_yform/blob/cdb1b22473d94bcf93ebb4100b02ffd4f083437f/plugins/manager/lib/yform/manager.php#L416

Wäre es möglich, hier optional (falls vorhanden) ein Feld (bspw. `name` oder ein in den Tabelleneinstellungen gewähltes Feld zu verwenden, statt der Datensatz-ID?

![image](https://user-images.githubusercontent.com/3855487/108106051-bc7de900-708d-11eb-8f68-04a7ca3b4bd3.png)

**Comment by christophboecker** [comment]
Danach kommt doch noch ein EP. Hau im EP etwas JS raus, dass die id gegen ... tauscht. Sonst fällt auch nix ein.

**Comment by dergel** [comment]
würde ich gerne so belassen. gerne wir beschrieben lösen und in tricks schmeissen ?

**Comment by alxndr-w** [comment]
Ich bin kein Fan davon, alles per EP zu lösen. Da blickt doch irgendwann keiner mehr durch, wo was in YForm angeflantscht wurde. Ich hätte angenommen, dass der Punkt für alle relevant wäre - scheinbar leider nicht.
